### ISSUE TITLE
Request to pagead2.googlesyndication.com is stuck when DNS is in use

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardDNS#10]
Here is how it looks like inside Chrome:

```
175290: URL_REQUEST
https://pagead2.googlesyndication.com/pagead/gen_204?rt=dart&lid=17&sdkv=h.3.0.0&e=420706011&id&c=1408971686930332&domain=www.youtube.com
Start Time: 2016-07-27 18:05:16.993

t=  1447 [st=    0] +REQUEST_ALIVE  [dt=99609]
t=  1447 [st=    0]    DELEGATE_INFO  [dt=0]
                       --> delegate_info = "NavigationResourceThrottle"
t=  1447 [st=    0]   +URL_REQUEST_DELEGATE  [dt=2]
t=  1447 [st=    0]      DELEGATE_INFO  [dt=1]
                         --> delegate_info = "extension Tampermonkey"
t=  1448 [st=    1]      DELEGATE_INFO  [dt=0]
                         --> delegate_info = "extension Tampermonkey"
t=  1448 [st=    1]      DELEGATE_INFO  [dt=1]
                         --> delegate_info = "extension Adguard AdBlocker (Beta)"
t=  1449 [st=    2]   -URL_REQUEST_DELEGATE
t=  1449 [st=    2]    URL_REQUEST_START_JOB  [dt=0]
                       --> load_flags = 37120 (MAIN_FRAME | MAYBE_USER_GESTURE | VERIFY_EV_CERT)
                       --> method = "GET"
                       --> priority = "HIGHEST"
                       --> url = "https://pagead2.googlesyndication.com/pagead/gen_204?rt=dart&lid=17&sdkv=h.3.0.0&e=420706011&id&c=1408971686930332&domain=www.youtube.com"
t=  1449 [st=    2]   +URL_REQUEST_START_JOB  [dt=99607]
                       --> load_flags = 37120 (MAIN_FRAME | MAYBE_USER_GESTURE | VERIFY_EV_CERT)
                       --> method = "GET"
                       --> priority = "HIGHEST"
                       --> url = "https://pagead2.googlesyndication.com/pagead/gen_204?rt=dart&lid=17&sdkv=h.3.0.0&e=420706011&id&c=1408971686930332&domain=www.youtube.com"
t=  1449 [st=    2]     +URL_REQUEST_DELEGATE  [dt=2]
t=  1449 [st=    2]        DELEGATE_INFO  [dt=1]
                           --> delegate_info = "extension Adguard AdBlocker (Beta)"
t=  1450 [st=    3]        DELEGATE_INFO  [dt=0]
                           --> delegate_info = "extension Adguard AdBlocker (Beta)"
t=  1450 [st=    3]        DELEGATE_INFO  [dt=1]
                           --> delegate_info = "extension Adguard AdBlocker (Beta)"
t=  1451 [st=    4]     -URL_REQUEST_DELEGATE
t=  1451 [st=    4]      HTTP_CACHE_GET_BACKEND  [dt=0]
t=  1451 [st=    4]      HTTP_CACHE_OPEN_ENTRY  [dt=0]
                         --> net_error = -2 (ERR_FAILED)
t=  1451 [st=    4]      HTTP_CACHE_CREATE_ENTRY  [dt=0]
t=  1451 [st=    4]      HTTP_CACHE_ADD_TO_ENTRY  [dt=0]
t=  1451 [st=    4]      URL_REQUEST_DELEGATE  [dt=0]
t=  1451 [st=    4]     +HTTP_STREAM_REQUEST  [dt=99605]
t=  1451 [st=    4]        HTTP_STREAM_REQUEST_STARTED_JOB
                           --> source_dependency = 175294 (HTTP_STREAM_JOB)
t=  1452 [st=    5]        HTTP_STREAM_REQUEST_STARTED_JOB
                           --> source_dependency = 175293 (HTTP_STREAM_JOB)
t=101056 [st=99609]        CANCELLED
t=101056 [st=99609]     -HTTP_STREAM_REQUEST
t=101056 [st=99609] -REQUEST_ALIVE
175293: HTTP_STREAM_JOB
https://pagead2.googlesyndication.com/
Start Time: 2016-07-27 18:05:16.998

t=1452 [st=  0] +HTTP_STREAM_JOB  [dt=317]
                 --> alternative_service = "Uninitialized :0"
                 --> original_url = "https://pagead2.googlesyndication.com/"
                 --> priority = "HIGHEST"
                 --> source_dependency = 175290 (URL_REQUEST)
                 --> url = "https://pagead2.googlesyndication.com/"
t=1452 [st=  0]   +PROXY_SERVICE  [dt=0]
t=1452 [st=  0]      PROXY_SERVICE_RESOLVED_PROXY_LIST
                     --> pac_string = "DIRECT"
t=1452 [st=  0]   -PROXY_SERVICE
t=1452 [st=  0]    HTTP_STREAM_JOB_DELAYED
                   --> resume_after_ms = 300
t=1752 [st=300]   +HOST_RESOLVER_IMPL_REQUEST  [dt=0]
                   --> address_family = 0
                   --> allow_cached_response = true
                   --> host = "pagead2.googlesyndication.com:443"
                   --> is_speculative = false
t=1752 [st=300]      HOST_RESOLVER_IMPL_IPV6_REACHABILITY_CHECK
                     --> cached = true
                     --> ipv6_available = false
t=1752 [st=300]   -HOST_RESOLVER_IMPL_REQUEST
                   --> net_error = -804 (ERR_DNS_CACHE_MISS)
t=1752 [st=300]   +SOCKET_POOL  [dt=17]
t=1769 [st=317]      SOCKET_POOL_BOUND_TO_CONNECT_JOB
                     --> source_dependency = 175308 (CONNECT_JOB)
t=1769 [st=317]   -SOCKET_POOL
                   --> net_error = -102 (ERR_CONNECTION_REFUSED)
t=1769 [st=317] -HTTP_STREAM_JOB
175294: HTTP_STREAM_JOB
https://pagead2.googlesyndication.com/
Start Time: 2016-07-27 18:05:16.997

t=  1451 [st=    0] +HTTP_STREAM_JOB  [dt=99605]
                     --> alternative_service = "quic pagead2.googlesyndication.com:443"
                     --> original_url = "https://pagead2.googlesyndication.com/"
                     --> priority = "HIGHEST"
                     --> source_dependency = 175290 (URL_REQUEST)
                     --> url = "https://pagead2.googlesyndication.com/"
t=  1451 [st=    0]   +PROXY_SERVICE  [dt=0]
t=  1451 [st=    0]      PROXY_SERVICE_RESOLVED_PROXY_LIST
                         --> pac_string = "DIRECT"
t=  1451 [st=    0]   -PROXY_SERVICE
t=101056 [st=99605] -HTTP_STREAM_JOB
```

**Comment by ameshkov** [comment]
It seems that problem goes away if you disable QUIC in chrome://flags.

What could have happened?

**Comment by sandybeachit** [comment]
Is this still an issue, perhaps its better closed if its resolved as its an old issue?

**Comment by ameshkov** [comment]
Yeah, sure

**Comment by reinasalondra** [comment]
> Así es como se ve dentro de Chrome:
> 
> ```
> 175290: URL_REQUEST
> https://pagead2.googlesyndication.com/pagead/gen_204?rt=dart&lid=17&sdkv=h.3.0.0&e=420706011&id&c=1408971686930332&domain=www.youtube.com
> Start Time: 2016-07-27 18:05:16.993
> 
> t=  1447 [st=    0] +REQUEST_ALIVE  [dt=99609]
> t=  1447 [st=    0]    DELEGATE_INFO  [dt=0]
>                        --> delegate_info = "NavigationResourceThrottle"
> t=  1447 [st=    0]   +URL_REQUEST_DELEGATE  [dt=2]
> t=  1447 [st=    0]      DELEGATE_INFO  [dt=1]
>                          --> delegate_info = "extension Tampermonkey"
> t=  1448 [st=    1]      DELEGATE_INFO  [dt=0]
>                          --> delegate_info = "extension Tampermonkey"
> t=  1448 [st=    1]      DELEGATE_INFO  [dt=1]
>                          --> delegate_info = "extension Adguard AdBlocker (Beta)"
> t=  1449 [st=    2]   -URL_REQUEST_DELEGATE
> t=  1449 [st=    2]    URL_REQUEST_START_JOB  [dt=0]
>                        --> load_flags = 37120 (MAIN_FRAME | MAYBE_USER_GESTURE | VERIFY_EV_CERT)
>                        --> method = "GET"
>                        --> priority = "HIGHEST"
>                        --> url = "https://pagead2.googlesyndication.com/pagead/gen_204?rt=dart&lid=17&sdkv=h.3.0.0&e=420706011&id&c=1408971686930332&domain=www.youtube.com"
> t=  1449 [st=    2]   +URL_REQUEST_START_JOB  [dt=99607]
>                        --> load_flags = 37120 (MAIN_FRAME | MAYBE_USER_GESTURE | VERIFY_EV_CERT)
>                        --> method = "GET"
>                        --> priority = "HIGHEST"
>                        --> url = "https://pagead2.googlesyndication.com/pagead/gen_204?rt=dart&lid=17&sdkv=h.3.0.0&e=420706011&id&c=1408971686930332&domain=www.youtube.com"
> t=  1449 [st=    2]     +URL_REQUEST_DELEGATE  [dt=2]
> t=  1449 [st=    2]        DELEGATE_INFO  [dt=1]
>                            --> delegate_info = "extension Adguard AdBlocker (Beta)"
> t=  1450 [st=    3]        DELEGATE_INFO  [dt=0]
>                            --> delegate_info = "extension Adguard AdBlocker (Beta)"
> t=  1450 [st=    3]        DELEGATE_INFO  [dt=1]
>                            --> delegate_info = "extension Adguard AdBlocker (Beta)"
> t=  1451 [st=    4]     -URL_REQUEST_DELEGATE
> t=  1451 [st=    4]      HTTP_CACHE_GET_BACKEND  [dt=0]
> t=  1451 [st=    4]      HTTP_CACHE_OPEN_ENTRY  [dt=0]
>                          --> net_error = -2 (ERR_FAILED)
> t=  1451 [st=    4]      HTTP_CACHE_CREATE_ENTRY  [dt=0]
> t=  1451 [st=    4]      HTTP_CACHE_ADD_TO_ENTRY  [dt=0]
> t=  1451 [st=    4]      URL_REQUEST_DELEGATE  [dt=0]
> t=  1451 [st=    4]     +HTTP_STREAM_REQUEST  [dt=99605]
> t=  1451 [st=    4]        HTTP_STREAM_REQUEST_STARTED_JOB
>                            --> source_dependency = 175294 (HTTP_STREAM_JOB)
> t=  1452 [st=    5]        HTTP_STREAM_REQUEST_STARTED_JOB
>                            --> source_dependency = 175293 (HTTP_STREAM_JOB)
> t=101056 [st=99609]        CANCELLED
> t=101056 [st=99609]     -HTTP_STREAM_REQUEST
> t=101056 [st=99609] -REQUEST_ALIVE
> 175293: HTTP_STREAM_JOB
> https://pagead2.googlesyndication.com/
> Start Time: 2016-07-27 18:05:16.998
> 
> t=1452 [st=  0] +HTTP_STREAM_JOB  [dt=317]
>                  --> alternative_service = "Uninitialized :0"
>                  --> original_url = "https://pagead2.googlesyndication.com/"
>                  --> priority = "HIGHEST"
>                  --> source_dependency = 175290 (URL_REQUEST)
>                  --> url = "https://pagead2.googlesyndication.com/"
> t=1452 [st=  0]   +PROXY_SERVICE  [dt=0]
> t=1452 [st=  0]      PROXY_SERVICE_RESOLVED_PROXY_LIST
>                      --> pac_string = "DIRECT"
> t=1452 [st=  0]   -PROXY_SERVICE
> t=1452 [st=  0]    HTTP_STREAM_JOB_DELAYED
>                    --> resume_after_ms = 300
> t=1752 [st=300]   +HOST_RESOLVER_IMPL_REQUEST  [dt=0]
>                    --> address_family = 0
>                    --> allow_cached_response = true
>                    --> host = "pagead2.googlesyndication.com:443"
>                    --> is_speculative = false
> t=1752 [st=300]      HOST_RESOLVER_IMPL_IPV6_REACHABILITY_CHECK
>                      --> cached = true
>                      --> ipv6_available = false
> t=1752 [st=300]   -HOST_RESOLVER_IMPL_REQUEST
>                    --> net_error = -804 (ERR_DNS_CACHE_MISS)
> t=1752 [st=300]   +SOCKET_POOL  [dt=17]
> t=1769 [st=317]      SOCKET_POOL_BOUND_TO_CONNECT_JOB
>                      --> source_dependency = 175308 (CONNECT_JOB)
> t=1769 [st=317]   -SOCKET_POOL
>                    --> net_error = -102 (ERR_CONNECTION_REFUSED)
> t=1769 [st=317] -HTTP_STREAM_JOB
> 175294: HTTP_STREAM_JOB
> https://pagead2.googlesyndication.com/
> Start Time: 2016-07-27 18:05:16.997
> 
> t=  1451 [st=    0] +HTTP_STREAM_JOB  [dt=99605]
>                      --> alternative_service = "quic pagead2.googlesyndication.com:443"
>                      --> original_url = "https://pagead2.googlesyndication.com/"
>                      --> priority = "HIGHEST"
>                      --> source_dependency = 175290 (URL_REQUEST)
>                      --> url = "https://pagead2.googlesyndication.com/"
> t=  1451 [st=    0]   +PROXY_SERVICE  [dt=0]
> t=  1451 [st=    0]      PROXY_SERVICE_RESOLVED_PROXY_LIST
>                          --> pac_string = "DIRECT"
> t=  1451 [st=    0]   -PROXY_SERVICE
> t=101056 [st=99605] -HTTP_STREAM_JOB
> ```
