### ISSUE TITLE
Blocking non-ad site 

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardDNS#100]
It appears adgauard DNS is blocking noip.com which is a dynamic DNS service and not related to ads as far as i'm aware. I am attaching a nslookup showing adguard blocking it. Other than this, fantastic service, thank you!

![capture](https://cloud.githubusercontent.com/assets/15856304/21470409/4d95b588-ca90-11e6-80ee-7232f7448bc1.PNG)

**Comment by Alex-302** [comment]
Not reproduced. Please check again.
Next time write to AdguardFilters about the similar issues.

**Comment by ameshkov** [comment]
It was blocked indeed, it's just DNS has bigger cache TTL, we should just wait a bit mroe
