### ISSUE TITLE
Does AdGuard DNS has relation with third-party services?

### ISSUE THREAD

**Issue by Rru247** [AdguardTeam/AdGuardDNS#100]
As i have heared AdGuardDNS run in vult servers without relation with third-party services.
`https://status.adguard.com/` doesn't show any down due to quality of up time service :)

Check https://www.reddit.com/r/Adguard/comments/ht48xe/adgaurd_dns_down/
User also has mentioned Discord etc down too. (Discord also relate with cloudflare)

I think that may be due `adguard.com` use cloudflare nameservers :(

**Comment by ameshkov** [comment]
AdGuard DNS has been working okay. Please note, that due to Cloduflare outage domains that use them could not be resolved regardless of what DNS service you used.
