### ISSUE TITLE
hbbtv.ardmediathek.de - Blocked Stream 

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardDNS#103]
Description:

DNS filter seems to block German internet TV on http://hbbtv.ardmediathek.de/hbbtv-ard/mediathek/?devicegroup=hbbtv&context=samsungSmarthub

Can't open this stream on my Samsung TV with your DNS settings but with my providers DNS.

User ID: 1476935

**Comment by evgeniy-ADG** [comment]
там по ссылке про iOS, кажется, тут - просто DNS. как нам собрать логи DNS, прописанного в настройкаих интернет-соединения?

**Comment by Alex-302** [comment]
Если бы оформили как следует, лишние вопросы бы не возникали. @Tetiana2020 Если в сообщении от юзера что-то непонятно - нужно уточнять, а не сразу перешивать.

**Comment by evgeniy-ADG** [comment]
ok, если я через iOS соберу логи, будет толк?

**Comment by Alex-302** [comment]
Возможно. Но лучше ещё уточнить какие и где у него прописаны ДНС. У меня телек в инет не попадает, если в его настройках ДНС изменить на любой, отличный от дефолтного(гуглового вроде).

**Comment by sandybeachit** [comment]
Tetiana2020 is this still an issue?

If not can we close this ticket as its an old one with no response for a good while ?

**Comment by vozersky** [comment]
outdated
