### ISSUE TITLE
Ads not blocked on Crunchyroll and VRV

### ISSUE THREAD

**Issue by jimmysofat6864** [AdguardTeam/AdGuardDNS#103]
I noticed that ad's aren't blocked on any videos on Crunchyroll when I use AdGuard DNS. Same thing with VRV. I haven't tried funimaiton but I'm pretty sure ads still go through on Funimation.

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdGuardSDNSFilter #422](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/422) via [**ZenHub**](https://www.zenhub.com/)
