### ISSUE TITLE
Finding the right product

### ISSUE THREAD

**Issue by BullShark** [AdguardTeam/AdGuardDNS#104]
Which Adguard Project should I be using if I want a dns server, with filtering, custom filters I can add, and doh support and other encryption protocols? My system doesn't yet support some of those encrypted dns protocols, so I use dnscrypt-proxy to encrypt all my dns traffic, and connect my system to dns servers. But I'm using public dns servers, and I'm looking for a dns server I can run on my server. It is only 5-10 people maximum that will be using it, so I don't need something crazy like load balancing. I was looking at AdGuard Home. It has a nice web user interface. Then why can't I run that one on my server? Does the server have to be on my same lan network to use AdGuard Home? Let me know.

Thanks,

**Comment by ameshkov** [comment]
> I was looking at AdGuard Home. It has a nice web user interface. Then why can't I run that one on my server? Does the server have to be on my same lan network to use AdGuard Home?

Why can't you? AdGuard Home is exactly what you need.

Check out the installation instruction here:
https://github.com/AdguardTeam/AdGuardHome/wiki/Getting-Started
