### ISSUE TITLE
yellow app ios

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardDNS#104]
Cant verify my phone number without whitelisting digits.com it is a website used for verifying your phone number through the app

https://appsto.re/us/7Mj69.i

**Comment by Alex-302** [comment]
Is it broken by DNS filtering or filters?

**Comment by jo2dan23** [comment]
Dns filtering

**Comment by Alex-302** [comment]
> digits.com

excluded from dns filter
