### ISSUE TITLE
(whitelist) reachedhb.afl.rakuten.co.jp

### ISSUE THREAD

**Issue by kylehase** [AdguardTeam/AdGuardDNS#105]
Many product search results on google.co.jp link to Rakuten which uses the URL http://reachedhb.afl.rakuten.co.jp which is blocked.

This query may help to test. https://www.google.co.jp/search?q=楽天%20靴

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdGuardSDNSFilter #441](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/441) via [**ZenHub**](https://www.zenhub.com/)
