### ISSUE TITLE
ForkPlayer пропуск рекламы...

### ISSUE THREAD

**Issue by Smorvel** [AdguardTeam/AdGuardDNS#106]
Для смарт ТВ есть приложение ForkPlayer, так вот в нем начала прорываться реклама перед запуском видео..
Вот одна из них
http://195.88.208.101/rek_ivi.mp4
Думаю можно любые mp4 файлы с этого адреса отправить под блокировку... и реклама пропадет..

**Comment by ameshkov** [comment]
На уровне DNS нельзя заблокировать IP адрес, к сожалению.
