### ISSUE TITLE
Why is https://www.medicare.gov/physiciancompare blocked?

### ISSUE THREAD

**Issue by cyclej** [AdguardTeam/AdguardDNS#106]
www.medicare.gov is fine, but the full URL is blocked?

**Comment by ameshkov** [comment]
Can't reproduce it, is it really blocked by AG DNS?

**Comment by cyclej** [comment]
Thank you for taking a look! 

With AdGuard DNS enabled, I get a blank page using either chrome or Firefox. Switch my DNS back to Google (8.8.8.8) and that page displays a proper search dialog. It's only the 'physicialsearch' page that has this behavior. The rest of the site is fine. 

They must be referencing a blocked site from this page? If so, I'm guessing there's not much you can do about it. But if you can, that'd be great!

**Comment by Alex-302** [comment]
This domain is not blocked, but that page is broken by blocking of analytics - ethn.io
@ameshkov should we to exclude ethn.io?

**Comment by ameshkov** [comment]
@Alex-302 yep, let's exclude it in DNS filter

**Comment by Alex-302** [comment]
done
