### ISSUE TITLE
Please block the following ads api server

### ISSUE THREAD

**Issue by DavidTai780** [AdguardTeam/AdGuardDNS#107]
here is some of the ads server.

me.com.x9wj2.cn
zvb.z7wq1.cn
y4m.s9wf3.cn
x0o.d2wl1.cn
uf7.t7wp8.cn
sx2.f7wn6.cn
re.baidu.com.r2wb3.cn
r6t.b3wg2.cn
pc5.b6wq9.cn
en3.r2wm5.cn
df8.l5wt5.cn
bbq.y7wr7.cn
al1.t7wl8.cn
9ns.g1wn5.cn
8xc.p2wq1.cn
d3n.q9ww5.cn
y1.d2wl1.cn
x3z.g1wn5.cn
v2j.r2wm5.cn
ttl8.l5wt5.cn
ry4.s9wf3.cn
rm.baidu.com.r2wb3.cn
q01.t7wp8.cn
k99.b6wq9.cn
h36.y7wr7.cn
d7g.p2wq1.cn
ciu1.z7wq1.cn
8p3.f7wn6.cn
5nm.t7wl8.cn
f2.q9ww5.cn
v.tysjkw.cn
v.tlscqw.cn
v.tgslww.cn
v.sssgbw.cn
v.pcswtw.cn
v.lbsbbw.cn
v.jsbgh.cn
v.cqpsf.cn
c.tysjkw.cn
c.tlscqw.cn
c.tgslww.cn
c.lbsbbw.cn
so6.b3wg2.cn

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdGuardSDNSFilter #445](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/445) via [**ZenHub**](https://www.zenhub.com/)
