### ISSUE TITLE
Adguard DNS Family protection mode blocks 192.168.88.1 (microtik router web-interface)

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardDNS#108]
1. Роутер microtik ip адрес http://192.168.88.1/
2. включил в настройках днс сервера адгуард 176.103.130.132 и 176.103.130.134
3. теперь невозможно через браузер зайти в веб консоль роутера, выходит страница Сайт неприемлем для детей Данная страница была заблокирована из-за ограничений фильтра родительского контроля.

![2017-01-08_23-00-51](https://cloud.githubusercontent.com/assets/15856304/21761488/00d481ac-d65c-11e6-8c0d-7f2c1b8c6e02.png)

ID: 1485021

**Comment by zebrum** [comment]
@evgeniy-ADG please ask user send us logs from router

**Comment by ameshkov** [comment]
It's not Adguard DNS, I guess it is AG's own parental control module doing it.

This is a server-side bug, we'll fix it soon.

**Comment by sandybeachit** [comment]
Did you guys manage to fix this bug yet ?

**Comment by ameshkov** [comment]
Yep, thank you:)
