### ISSUE TITLE
Ошибочное блокирование ресурсов

### ISSUE THREAD

**Issue by LordMerlin** [AdguardTeam/AdguardDNS#109]
Добрый день.
Можно ли что-то сделать с блокировкой переходов по платным ссылкам?
Объясню, на разных сайтах с обзорами, или на форумах обсуждения устройств, даются ссылки где преобрели данный товар. И зачастую идет переадресация через ad.admitad.com. И при использовании ваших ДНС серверов они естественно блокируются.
Спасибо.

**Comment by LordMerlin** [comment]
Например вот здесь
http://www.taker.im/review/13680-Gigaset-Me-shikarnyiy-smartfon-s-Hi-Fi-zvukom-na-m

**Comment by Alex-302** [comment]
Проверьте в белом списке
```
ad.admitad.com
```

**Comment by Alex-302** [comment]
@ameshkov Стоит разблокировать ad.admitad.com в фильтре DNS? В виде скриптов мало где встречается, а на аналогичных сайтах переходы в магазины блокирует в Сафари.

**Comment by LordMerlin** [comment]
Разговор идет именно о ДНС. В нем надо разблокировать. Фильтрами не все пользуются.

**Comment by Alex-302** [comment]
Это рекламная сеть, не хотелось бы разблокироватьть, но ладно, попробуем.

**Comment by LordMerlin** [comment]
Спасибо. Оно как бы да, рекламная сеть, НО..самих по себе баннеров с нее не видно, а делается перенаправление через нее. Если не разблокировать, то получается блокируется переход, тоесть сломалась страница в итоге. А будет оно работать без аддона к браузеру, только если ДНС применены?

**Comment by LordMerlin** [comment]
nslookup ad.admitad.com 176.103.130.130
Server:  176-103-130-130.flops.ru
Address:  176.103.130.130

Non-authoritative answer:
Name:    ad.admitad.com
Address:  212.224.118.36

Отлично, работает.

**Comment by LordMerlin** [comment]
Тогда еще одина ошибка
nslookup tween-rnd.ru 176.103.130.130
Server:  176-103-130-130.flops.ru
Address:  176.103.130.130

Non-authoritative answer:
Name:    safebrowsing.block.dns.adguard.com
Address:  176.103.130.131
Aliases:  tween-rnd.ru

Сайт поставщиков бытовой техники. Почему он в небезопасных?

**Comment by Alex-302** [comment]
> самих по себе баннеров с нее не видно, а делается перенаправление через нее

поэтому разблокировал) Скрипты тоже бывают, но очень редкое явление.

> Тогда еще одина ошибка
> nslookup tween-rnd.ru 176.103.130.130

поправим.
