### ISSUE TITLE
Wrong location used

### ISSUE THREAD

**Issue by BlazDT** [AdguardTeam/AdGuardDNS#109]
### Issue URL (Incorrect Blocking)
 [https://adguard.com/en/adguard-dns/overview.html](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fadguard.com%2Fen%2Fadguard-dns%2Foverview.html)
### Comment
Username: @pradnyeshwalekar
> My location - India
> Adguard connected server location - Chicago, USA
> Issue - Not connected to nearest server such as london, tokyo. Hence internet slow.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/eDNRwom.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/k5fw77f.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | Android 10
AdGuard product: | AdGuard for Android v3.5 (63)
Browser: | Chrome
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | disabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base, <br/>AdGuard Mobile Ads, <br/>EasyList<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Language-specific:</b><br/> Thai Ads Filters
Custom filter subscriptions: |

_Originally posted by @adguard-bot in https://github.com/AdguardTeam/AdguardFilters/issues/64022#issuecomment-694836355_

**Comment by ameshkov** [comment]
We have no servers in India. Maybe in the future we'll have one, but that's not a bug anyway.

**Comment by pradnyeshwalekar** [comment]
Thanks for the reply.

I understand that currently you have no servers in India. But why am I connected to Chicago, USA?

Why not any nearest server such as SINGAPORE, TOKYO OR LONDON?

Maybe nearest server might improve my internet speed.

**Comment by ameshkov** [comment]
Unfortunately, networking does not work that way.

It does not choose the closest server geographically. Instead, it chooses the one that has the fewer number of "network hops" in its route.
