### ISSUE TITLE
Some domains are not blocked by rules from dns filter

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardDNS#11]
1) http://kinozal.tv/
The following requests 
```
http://jsc.marketgid.com/k/i/kinozal.tv.599051.js?t=11662719
http://mxtads.com/6922931762
```
should be blocked by rules from DNS filter
```
||mxtads.com
||marketgid.com
```
2) 4pda.ru + Ace Stream Web Extension
https://chrome.google.com/webstore/detail/ace-stream-web-extension/mjbepbhonbojpoaenhckjocchgfiaofo?utm_source=chrome-app-launcher-info-dialog
Counter is not blocked by
`||mstat.acestream.net`
`http://mstat.acestream.net/metrika.js`

**Comment by vbagirov** [comment]
Also missed ads and Google Analytics on following domains:

http://fastpic.ru/
https://www.yandex.ua/
http://www.free-torrents.org/forum/indexer1.php
http://www.besplatnyeprogrammy.ru/utorrent.html

**Comment by Alex-302** [comment]
If we start block GA, too many sites will be broken. See the number of exclusions in spyware filter.
