### ISSUE TITLE
IP Addresses

### ISSUE THREAD

**Issue by ericewers** [AdguardTeam/AdGuardDNS#111]
Hi,

I have noticed that the following pages may have outdated AdGuard IP addresses:

https://github.com/AdguardTeam/AdGuardDNS
https://kb.adguard.com/en/general/dns-providers#default

They all refer to 176.103.*.* instead of 94.140.*.* as well as the IPv6 addresses.

The following pages refer to the new IP addresses:

https://adguard.com/en/adguard-dns/setup.html
https://adguard.com/en/blog/adguard-dns-announcement.html

Please let me know if there is a better place to post this.

**Comment by ameshkov** [comment]
Yep, thank you! We'll update it here when the code is synced next time.

Regarding KB, we'll do it today.
