### ISSUE TITLE
What malware lists are used?

### ISSUE THREAD

**Issue by ingber** [AdguardTeam/AdguardDNS#111]
Hi.  I read that malware, as well as ads and spyware, are filtered, but I do not see any malware lists on this site?  For example, do you filter (at least once a day?) using IPs such as
http://malc0de.com/bl/IP_Blacklist.txt
https://lists.blocklist.de/lists/strongips.txt
https://www.openbl.org/lists/base_30days.txt.gz
etc.

Thanks.

**Comment by ameshkov** [comment]
We use several public sources (like malwaredomains and such) + our own database: https://adguard.com/en/how-malware-blocked.html#filtersUpdate
