### ISSUE TITLE
cost out of beta?

### ISSUE THREAD

**Issue by ingber** [AdguardTeam/AdguardDNS#113]
Hi.  We're considering alternatives to VPNs that include blocking malware & ads.

Your AdguardDNS definitely is a very good solution for us, as we can use my own VPS OpenVPN server pushing your DNS to our router, dd-wrt PCs and Phones that also run OpenVPN clients.  However, we'd like to have some idea of:
(a) Do you have a schedule when you will be out of beta?
(b) I assume you will offer Premium services, similar to your Adguard apps for Windows and Androids.  Can you give me you present inclinations on pricing?  The apps seem to have an advantage of being able to switch off adblocking on some pages that otherwise won't load, but the DNS product is much better for use on all our devices.

Right now, we are looking at AdguardDNS, Adguard apps, and PIA (Private Internet Access) with MACE.  With our 5 devices (2 PCs, 2 Androids, 1 DD-WRT router) your apps a bit expensive (needs 3 licenses?) but still worth our consideration.

Any comments would be appreciated.

Thanks for this product.

**Comment by ameshkov** [comment]
> (a) Do you have a schedule when you will be out of beta?

The main issue currently is the infrastructure; we still don't have servers in EU and Asia. As soon as it is solved and function properly, the first release will be announced.

> (b) I assume you will offer Premium services, similar to your Adguard apps for Windows and Androids.

Eventually, we'd like to provide the same functionality OpenDNS provides in their premium package. What for the price and the ETA on this, it's too early to talk about it yet. For instance, it might be offered for free for premium AG users.

> With our 5 devices (2 PCs, 2 Androids, 1 DD-WRT router) your apps a bit expensive (needs 3 licenses?) but still worth our consideration.

As I understand, it can be covered by a 2-device premium license.
