### ISSUE TITLE
DNSCrypt unavailable on new AdGuard IP addresses

### ISSUE THREAD

**Issue by yofiji** [AdguardTeam/AdGuardDNS#113]
Hello,

The new IP addresses defined on https://adguard.com/en/adguard-dns/overview.html don't seem to be responding to connections on port 5443 for DNSCrypt traffic. The old AdGuard DNS IPs support(ed) DNSCrypt on port 5443.

Will the new ones also be supporting DNSCrypt?

The IP addresses / port combinations I tested were:
94.140.14.14:5443
94.140.14.15:5443
[2a10:50c0::bad2:ff]:5443
[2a10:50c0::ad2:ff]:5443

Thanks

**Comment by ameshkov** [comment]
> Will the new ones also be supporting DNSCrypt?

Yes, we're going to support it later. We're migrating to our own DNSCrypt implementation and it requires a little bit more time to make it work properly.

**Comment by ameshkov** [comment]
Please don't close just yet, it's coming soon:)

**Comment by ameshkov** [comment]
Fixed it
