### ISSUE TITLE
dev.aepoh.gridsmart.app is not resolved

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardDNS#114]
@adguard-bot commented on [Sun Oct 18 2020](https://github.com/AdguardTeam/AdguardFilters/issues/65845)

### Issue URL (Incorrect Blocking)
 [https://dev.aepoh.gridsmart.app](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fdev.aepoh.gridsmart.app)
### Comment
Username: @nikmartin
> Adblock DNS will not resolve this DNS record for some reason. 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/cHurPdz.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/vsMCows.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | Adguard DNS
Browser: | Chrome
Filters: | <b>Other:</b><br/> AdGuard DNS
Other extensions used: | none

**Comment by ameshkov** [comment]
This seems to a bug of Amazon Route53, we can't do anything from our side
