### ISSUE TITLE
Using adguard DNS over TLS with unbound as a forwarder often stops resolving anything

### ISSUE THREAD

**Issue by monterrr** [AdguardTeam/AdGuardDNS#115]
When using adguard DNS over TLS with unbound as a forwarder it often stops working requiring a restart of the server, adguard DNS over TLS doesn't seem to be as reliable as those from other providers, my internet connection is not the problem.

Reproduced with adguard DNS over TLS with unbound as a forwarder:
94.140.14.14
94.140.15.15
176.103.130.130
176.103.130.131

https://github.com/NLnetLabs/unbound/issues/286

I can't reproduced this with clouflare DNS over TLS.

**Comment by ameshkov** [comment]
Could it be related to today's outage?
https://status.adguard.com/incidents/x925w0cn8j6j

**Comment by monterrr** [comment]
It could well be, but this happens frequently with your servers

**Comment by ameshkov** [comment]
Is there any option to enable debug logging in unbound? I'd like to understand why exactly it marks AG DNS offline.

Maybe the idle timeout is too short?

**Comment by monterrr** [comment]
Maybe add verbosity: 1 to the unbound.conf file

**Comment by monterrr** [comment]
This happens everyday if you use the computer for most part of the day you will notice this. Can be for example 15 seconds of downtime, nothing responding them after that it resumes.

**Comment by ameshkov** [comment]
There's a high probability that this issue is fixed long time ago. The root cause of it was that AG DNS was not processing multiple DNS queries sent into the same connection asynchronously.
