### ISSUE TITLE
404 error for *.png URLs blocked by Family Protection DNS

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardDNS#116]
Site: http://i.imgur.com/EKIURnT.png
Screen: http://s24.postimg.org/f3yck42t1/screenshot_145.png

**Comment by ameshkov** [comment]
Hm, so when you use AG DNS, some imgur links do not work?

**Comment by ameshkov** [comment]
2 issues here:

1. i.imgur.com is blocked by the family protection DNS.
2. It fails to show "access denied" page.

@nkartyshov first we should fix the point 2, then unblock i.imgur.com.

**Comment by nkartyshov** [comment]
I fixed my part.

**Comment by ameshkov** [comment]
Is it deployed already?

**Comment by nkartyshov** [comment]
Yes.

**Comment by nkartyshov** [comment]
Done. Domain unblocked and nginx configured.
