### ISSUE TITLE
Disney+ hotstar app issues

### ISSUE THREAD

**Issue by agdw18** [AdguardTeam/AdGuardDNS#116]
I have issued with app disney+ hotstar, it's shown error if i change with other dns it's work perfectly

![Screenshot_20201028-180302075](https://user-images.githubusercontent.com/73678090/97651827-aa048300-1a8f-11eb-8de1-650fbfde561d.jpg)

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdGuardSDNSFilter #479](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/479) via [**ZenHub**](https://www.zenhub.com/)
