### ISSUE TITLE
Adguard DNS profile on iOS 14 not resolving anything 

### ISSUE THREAD

**Issue by anonyme123** [AdguardTeam/AdGuardDNS#118]
Hello,

Since a few hours the iOS 14 Adguard DNS profile is not resolving anything anymore.

When I go to iOS settings > general > VPN & Network > DNS > switch back to "Automatic" the issue is immediately resolved (i.e. when NOT using Adguard DNS over HTTPS but instead reverting to my ISP's default DNS) 

I'm on iOS 14.2 public (NOT beta).
The Adguard DNS profile for iOS has been downloaded from https://adguard.com/en/blog/encrypted-dns-ios-14.html
I am using the default AdGuard DNS profile (i.e. NOT AdGuard DNS Family protection profile or AdGuard DNS Non-filtering profile)

I tried:
- rebooting my iPhone
- switching Airplane mode ON and OFF
- removing the profile and re adding it

**Comment by ameshkov** [comment]
Could you please test it again now?

**Comment by anonyme123** [comment]
Now working! Thank you 👍 
Could you please update the incident page to reflect the outage? https://status.adguard.com/history

**Comment by ameshkov** [comment]
Yeah, as soon as we understand what the hell was it:)

**Comment by ameshkov** [comment]
Very quick analysis: https://status.adguard.com/incidents/l6d37hdv5g81

**Comment by anonyme123** [comment]
Thanks for the update!
