### ISSUE TITLE
turkcell.com.tr cannot be resolved with AdGuard DNS

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardDNS#119]
@adguard-bot commented on [Mon Nov 09 2020](https://github.com/AdguardTeam/AdguardFilters/issues/67296)

### Issue URL (Incorrect Blocking)
 [https://www.turkcell.com.tr](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.turkcell.com.tr)
### Comment
Username: @Yildirimkursat
> dns.adguard.com is blocking incorrectly.  the site of the republic of turkey.  This site also has its own application, please watch the video I posted, you will understand the problem.
> 
> Youtube Link; https://youtu.be/bfnyzO1tIHU
> --
> The information below is automatically generated. Do not delete it.
> 
> Custom userscripts:
> https://userscripts.adtidy.org/release/disable-amp/1.0/disable-amp.meta.js
> https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.meta.js
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/XFlKOO4.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/fnYAMn0.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Android 10
AdGuard product: | AdGuard for Android v3.5.1 (65)
Browser: | Samsung Browser
Stealth mode options: | Strip URLs from tracking parameters, <br/>Self-destructing third-party cookies (0)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Mobile Ads, <br/>AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/> AdGuard Turkish, <br/>AdGuard Russian
Custom filter subscriptions: |

**Comment by Alex-302** [comment]
Reproduced with all types of our DNS servers
![image](https://user-images.githubusercontent.com/8361299/98677582-df4d8280-2365-11eb-994f-b467bda00c46.png)

**Comment by ameshkov** [comment]
Hm, I cannot reproduce this:
```
nslookup www.turkcell.com.tr 94.140.14.14
Server:		94.140.14.14
Address:	94.140.14.14#53

Non-authoritative answer:
Name:	www.turkcell.com.tr
Address: 86.108.185.72
Name:	www.turkcell.com.tr
Address: 2a02:4e0:101:1101::14

```

**Comment by yildirimkursat** [comment]
dns address not found problem persists
![Screenshot_20201110-174938_Samsung Internet](https://user-images.githubusercontent.com/59163713/98689668-33179600-237d-11eb-858f-a7ca4282cf49.jpg)

**Comment by ameshkov** [comment]
It seems some of the Turkcell nameservers are down that's why there's a noticeable delay with the resolution. But it should be working already.
