### ISSUE TITLE
Mitigation for SAD DNS

### ISSUE THREAD

**Issue by zznosar** [AdguardTeam/AdGuardDNS#120]
Hi team, can you please look into this research and apply some mitigation?

https://dl.acm.org/doi/pdf/10.1145/3372297.3417280

ABSTRACT
In this paper, we report a series of flaws in the software stack that leads to a strong revival of DNS cache poisoning — a clas- sic attack which is mitigated in practice with simple and effective randomization-based defenses such as randomized source port. To successfully poison a DNS cache on a typical server, an off-path adversary would need to send an impractical number of 232 spoofed responses simultaneously guessing the correct source port (16-bit) and transaction ID (16-bit). Surprisingly, we discover weaknesses that allow an adversary to “divide and conquer” the space by guess- ing the source port first and then the transaction ID (leading to only 216 + 216 spoofed responses). Even worse, we demonstrate a number of ways an adversary can extend the attack window which drastically improves the odds of success.
The attack affects all layers of caches in the DNS infrastructure, such as DNS forwarder and resolver caches, and a wide range of DNS software stacks, including the most popular BIND, Unbound, and dnsmasq, running on top of Linux and potentially other oper- ating systems. The major condition for a victim being vulnerable is that an OS and its network is configured to allow ICMP error replies. From our measurement, we find over 34% of the open resolver pop- ulation on the Internet are vulnerable (and in particular 85% of the popular DNS services including Google’s 8.8.8.8). Furthermore, we comprehensively validate the proposed attack with positive results against a variety of server configurations and network con- ditions that can affect the success of the attack, in both controlled experiments and a production DNS resolver (with authorization).

Test Link:

https://www.cs.ucr.edu/~zhiyunq/SADDNS.html 

It seems NextDNS already have a fixed on their DNS servers, i’m hoping that adGuard can do the same.

**Comment by BooBerry** [comment]
AdGuard DNS is not affected by this and never was in the first place. Andrey (AdGuard's CTO) posted this in the Telegram chat when somebody asked about it...

`AG DNS accepts queries on the main IP and forwards to the recursor, the recursor itself is on a different server and it does not accept queries from users.`

**Comment by ameshkov** [comment]
To be fully honest, our approach is not a full fix (there cannot be one) but it's a good mitigation on top of disabling ICMP which we had like forever on the recursor server.
