### ISSUE TITLE
Problem on NSFW site

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardDNS#120]
Site: http://www.codeonix.com/
With enabled AG DNS: http://s24.postimg.org/42ehnykvp/screenshot_204.png
But, without AG DNS site works great.

**Comment by Alex-302** [comment]
not reproduced

**Comment by thislife81** [comment]
Did you check with "Family Protection"?

**Comment by Alex-302** [comment]
Sure.

**Comment by vozersky** [comment]
looks like this website is not available anymore
