### ISSUE TITLE
Questions about the correlation between ping response time and internet browsing speed

### ISSUE THREAD

**Issue by Richelieu4771** [AdguardTeam/AdGuardDNS#121]
Hello, there!

I know how AdGuard DNS works. Announcing the same server address to the world and accessing servers with the least network path through routing.

Sadly, however, they seem to be slower than Cloudflare DNS.

Despite living in Korea, DNS queries on computers are routed to New York.

![Screenshot 2020-11-21 151553](https://user-images.githubusercontent.com/68171816/99869200-7dfe9c80-2c0c-11eb-8412-91f2e16b0e52.png)

If I do a ping test on my computer at 94.140.14.14 (new server address), I find it on average close to 200ms. Cloudflare DNS, on the other hand, has a little over 10ms. Given that the local ISP's server is 6ms, this is a significant ping response time.

Now, I have 2 questions about the AG DNS.

> Does the speed of Internet browsing depend on the server's ability to DNS filtering? So can I think of using an "AG unfiltered" server and applying SDNS Filter in AdGuard app as an alternative to slow Internet browsing?

> Is sending to servers with shorter geographic distances likely to be longer latency time than now?

The following are the results of a ping test for several servers. Among them, "168.126.63.1" is the DNS server of my local ISP.

    PS C:\> ping 94.140.14.14

    Pinging 94.140.14.14 with 32 bytes of data:
    Reply from 94.140.14.14: bytes=32 time=203ms TTL=53
    Reply from 94.140.14.14: bytes=32 time=202ms TTL=53
    Reply from 94.140.14.14: bytes=32 time=201ms TTL=53
    Reply from 94.140.14.14: bytes=32 time=202ms TTL=53

    Ping statistics for 94.140.14.14:
        Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
    Approximate round trip times in milli-seconds:
        Minimum = 201ms, Maximum = 203ms, Average = 202ms

    PS C:\> ping 1.1.1.1

    Pinging 1.1.1.1 with 32 bytes of data:
    Reply from 1.1.1.1: bytes=32 time=12ms TTL=57
    Reply from 1.1.1.1: bytes=32 time=13ms TTL=57
    Reply from 1.1.1.1: bytes=32 time=13ms TTL=57
    Reply from 1.1.1.1: bytes=32 time=13ms TTL=57

    Ping statistics for 1.1.1.1:
        Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
    Approximate round trip times in milli-seconds:
        Minimum = 12ms, Maximum = 13ms, Average = 12ms

    PS C:\> ping 168.126.63.1

    Pinging 168.126.63.1 with 32 bytes of data:
    Reply from 168.126.63.1: bytes=32 time=6ms TTL=58
    Reply from 168.126.63.1: bytes=32 time=6ms TTL=58
    Reply from 168.126.63.1: bytes=32 time=6ms TTL=58
    Reply from 168.126.63.1: bytes=32 time=6ms TTL=58

    Ping statistics for 168.126.63.1:
        Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
    Approximate round trip times in milli-seconds:
        Minimum = 6ms, Maximum = 6ms, Average = 6ms

    PS C:\> ping 8.8.8.8

    Pinging 8.8.8.8 with 32 bytes of data:
    Reply from 8.8.8.8: bytes=32 time=45ms TTL=116
    Reply from 8.8.8.8: bytes=32 time=46ms TTL=116
    Reply from 8.8.8.8: bytes=32 time=46ms TTL=116
    Reply from 8.8.8.8: bytes=32 time=45ms TTL=116

    Ping statistics for 8.8.8.8:
        Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
    Approximate round trip times in milli-seconds:
        Minimum = 45ms, Maximum = 46ms, Average = 45ms

Thank you for taking my questions!

**Comment by ameshkov** [comment]
> Does the speed of Internet browsing depend on the server's ability to DNS filtering?

Not really, DNS filtering is really fast, and it takes almost no time.

> So can I think of using an "AG unfiltered" server and applying SDNS Filter in AdGuard app as an alternative to slow Internet browsing?

Yes, sure. AdGuard app is capable of doing DNS filtering locally, and it is actually better than doing it on the server-side because it prevents sending DNS queries for blocked domains.

> Is sending to servers with shorter geographic distances likely to be longer latency time than now?

It's really hard to predict.

**Comment by Richelieu4771** [comment]
Thanks to your answer, the questions has been cleared up. I feel I lack knowledge of the network.

In AG for Android 3.6 beta, DNS over QUIC is experimentally implemented, and unfiltered server and local DNS filtering combine to make browsing seem faster.

In addition to the DoQ, I'm looking forward to applying encrypted SNI! :)

**Comment by ameshkov** [comment]
> In addition to the DoQ, I'm looking forward to applying encrypted SNI! :)

Hopefully, we'll implement it in the future when ECH standard (former ESNI) is more stable.
