### ISSUE TITLE
Adguard website cannot detect that DNS is in use

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardDNS#122]
Here:
https://www.wilderssecurity.com/threads/adguard-dns-beta.387403/page-5#post-2649209

It seems, that we have this issue when US DNS servers are in use.

**Comment by nkartyshov** [comment]
@ameshkov Please, tell user what would he is checking detector in website.

**Comment by ameshkov** [comment]
It works now, good job @nkartyshov
