### ISSUE TITLE
Better DNS-IP's Webpages @ port :80 

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdGuardDNS#123]
If 1 connects to http://[AGDNS-IP] (& click past the certificate warnings 😅), the standard webpage status pops up:
> # Welcome to nginx!
>
>If you see this page, the nginx web server is successfully installed and working. Further configuration is required.
>
> For online documentation and support please refer to nginx.org.
Commercial support is available at nginx.com.
>
>_Thank you for using nginx._

This doesn't seem ideal.  _Far_ better would be to have a proper redirect to https://adguard.com/adguard-dns/overview.html.  Why?  If this were to show up in a log someplace, there should be _something_ to identify what it is, right?

**Comment by ameshkov** [comment]
Worry not, this is a known issue and it's temporary.

**Comment by TPS** [comment]
Perhaps leave open _(temporarily)_ until it _is_ done?

**Comment by ameshkov** [comment]
Well we have this issue open in the internal bug tracker.

There's a technical reason for this -- we're in process of acquiring a new TLS certificate for AG DNS (now with IPs included), and we need to keep special "auth" files there. Once it's verified that IPs belong to us, we can rollback this config and the issue will be solved.
