### ISSUE TITLE
Get rid of unnecessary exceptions

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardDNS#124]
> https://github.com/AdguardTeam/AdguardDNS/blob/master/Filters/exceptions.txt

Why do we need those:
```
@@||cedexis.net^
@@||licdn.com^
```

Can't we use "exclusions" instead?

**Comment by Alex-302** [comment]
`cedexis.net` - moved to exclusions
`licdn.com` - [some] subdomains was blocked by parental control. Leaved as `@@||licdn.com^`

**Comment by ameshkov** [comment]
@Alex-302 we should solve this in parental control service then, no need to keep those filters here.

**Comment by Alex-302** [comment]
Can it be excluded in parental control with all sub-domains?

**Comment by ameshkov** [comment]
That's what I did.

**Comment by Alex-302** [comment]
Ok, `@@||licdn.com^` is removed.
