### ISSUE TITLE
qualtrics.com.com

### ISSUE THREAD

**Issue by yochananmarqos** [AdguardTeam/AdguardDNS#125]
I'm using the Adguard DNS default servers via my router. I noticed qualtrics.com is being blocked. I'm not able to access paid online surveys because of this. Could it be removed from the block list?

EDIT: Others:
survey.bz
survey1s3.affinnova.com
survey.us.confirmit.com

**Comment by Alex-302** [comment]
Not reproduced, they are not blocked on my side. Which DNS addresses are you using?
Please enter in console and make screenshots:
`nslookup qualtronics.com 176.103.130.130`
`nslookup qualtronics.com 176.103.130.132`
`nslookup survey.bz 176.103.130.130`
`nslookup survey.bz 176.103.130.132`

**Comment by vozersky** [comment]
qualtronics.com redirects to hugedomains.com and this one is in safebrowsing database.

**Comment by ameshkov** [comment]
@vozersky should it really be blocked?

**Comment by vozersky** [comment]
It depends. No viruses etc, but looks scammy. I did remove it.
@yochananmarqos give your surveys a try now, please. Any examples of them btw?

**Comment by yochananmarqos** [comment]
Oops. It's qualtrics.com. 

Nslookup returns a result for survey.bz, but I could not access a survey hosted there yesterday using Adguard DNS.

**Comment by yochananmarqos** [comment]
I've found another one: http://survey1s3.affinnova.com

**Comment by yochananmarqos** [comment]
...and another one: http://survey.us.confirmit.com

**Comment by vozersky** [comment]
@yochananmarqos could you please provide any example of actual survey i can try and reproduce the issue with? not just domain names

**Comment by yochananmarqos** [comment]
I use a few survey sites like I use OpinionOutpost.com, Prolific.ac & PineconeResearch.com. The survey URL's are unique to my profile ID and no one else would be able to access them. The surveys could be hosted anywhere, so I'd have to plug through a bunch of surveys before I'd get one of the blocked URL's again.

**Comment by vozersky** [comment]
can't reproduce tbo

@Alex-302 what about this two domains?
survey1s3.affinnova.com
survey.us.confirmit.com

**Comment by yochananmarqos** [comment]
@vozersky Here's one: https://readingagriculture.eu.qualtrics.com/jfe/form/SV_0etQF6b6Vtk4HBz

I've already completed the survey, so I'm not sure if it'll help.

**Comment by sandybeachit** [comment]
Maybe just whitelisting qualtrics.com would be enough ?

**Comment by vozersky** [comment]
@sandybeachit it's in the filter for a reason, why just whitelist it...

@Alex-302 we can't just whitelist qualtrics.com, can we?

**Comment by Alex-302** [comment]
ok
