### ISSUE TITLE
vcmedia.vn

### ISSUE THREAD

**Issue by kaerula3** [AdguardTeam/AdguardDNS#126]
[GenK.vn](url), for instance [http://genk.vn/dem-do-an-toi-van-phong-xua-roi-gio-nau-lau-va-an-luon-trong-gio-lam-moi-hot-co-20170219115242707.chn](url)
uses [vcmedia.vn](url) to load media (clip) from [.](vcplayer.vcmedia.vn) As you can see the clip couldn't load. It seems AdguardDNS is blocking this?

**Comment by Alex-302** [comment]
removed from DNS filter
```
||vcplayer.vcmedia.vn^
||video-thumbs.vcmedia.vn^
||static.hosting.vcmedia.vn^
```
Please check after 3-4 hours.

**Comment by kaerula3** [comment]
The reported issue is solved now. Thank you.
