### ISSUE TITLE
Adguard DNS not connecting to nearest server

### ISSUE THREAD

**Issue by danielprashaanth** [AdguardTeam/AdGuardDNS#127]
I am from India, recently I started using Adguard DNS for my home router.

Using the good old DNS address : **176.103.130.130** and **176.103.130.131** I get ping of 35 ms as it connects to Singapore (which is near to the my country)
![sing](https://user-images.githubusercontent.com/58475058/101981205-21cdec00-3c91-11eb-9abb-5d43f0b5a73a.jpg)

but using the [Adguard's new DNS](https://adguard.com/en/adguard-dns/overview.html#instruction) which is **94.140.14.14** and **94.140.15.15** am getting ping of 149 ms as it gets connected only to US server.
![us](https://user-images.githubusercontent.com/58475058/101981212-2e524480-3c91-11eb-9d3c-ddfee596f561.jpg)

Dear Adguard Team, kindly address this issue and fix the new DNS to connect to Singapore too as the old DNS does.

PS: Please don't suggest me [Adguard Home](https://adguard.com/en/adguard-home/overview.html) as I don't have a device to run 24x7.

**Comment by ameshkov** [comment]
The difference is that for old addresses we only keep a handful of servers in two locations -- NJ and AMS (Singapore was removed not long ago as I recall).

For new servers there are many more locations, and for most of the users this is good news, but not for all, it depends on your ISP peering with the hosting services we use.
