### ISSUE TITLE
doc.url.ph - false positive

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardDNS#127]
I use Adguard DNS in Family configuration but there is a problem because it is blockiing "doc.url.ph" domain that is my personal site for my son.

Ticket ID: 1511689

**Comment by ameshkov** [comment]
Fixed.

@evgeniy-ADG for other issues like that, the temporary solution would be to add a new line to the `hosts` file:
`doc.url.ph     real_ip_address`
