### ISSUE TITLE
http://176.103.130.130 should redirect to AG DNS overview

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardDNS#128]

**Comment by sandybeachit** [comment]
Lol it redirects to ADGuard DNS? Can we close this one as it does that ?

**Comment by ameshkov** [comment]
> Lol it redirects to ADGuard DNS? Can we close this one as it does that ?

Hm, it does not in my case.

**Comment by ameshkov** [comment]
What I mean is that when you enter http://176.103.130.130 in your browser, it opens an "access denied" page, while in fact it should redirect to a DNS overview.

**Comment by sandybeachit** [comment]
That's odd I get redirected to the attached screenshot and then to: https://adguard.com/en/adguard-dns/overview.html

When I click on or type in: http://176.103.130.130

![screenshot_20170617-122450](https://user-images.githubusercontent.com/11394779/27252501-18344b42-5358-11e7-9470-1790d2c7c531.png)


That's with me using chrome on android and Windows with adgaurd DNS only

**Comment by sandybeachit** [comment]
Maybe a browser thing blocking redirects or a different extension or plugin blocking the redirect?

**Comment by ameshkov** [comment]
I guess some of the servers are misconfigured (again)

**Comment by sandybeachit** [comment]
At least you know now :) is that a Ain to fix?

**Comment by sandybeachit** [comment]
Sorry I meant is that a pain to fix?

**Comment by ameshkov** [comment]
> Sorry I meant is that a pain to fix?

Nah, we just need to wait for @nkartyshov so that he examined servers configuration.

**Comment by nkartyshov** [comment]
done
