### ISSUE TITLE
Block ads in Yahoo Mail app on Android

### ISSUE THREAD

**Issue by alexkararo** [AdguardTeam/AdGuardDNS#128]
Hi, 

Using Adguard DNS, setup as Private DNS in Android 9 or newer, does not block ads in the Yahoo Mail app. 
I found this suggestions here, on how to block them: https://www.reddit.com/r/Adguard/comments/iibmdd/block_ads_on_yahoo_mail_app/

I tested those rules, I blocked them using a Mikrotik router and the DNS service included in these routers, they seem to work. 
Can those rules be included in the Adguard DNS service?

Thank you!

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdGuardSDNSFilter #512](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/512) via [**ZenHub**](https://www.zenhub.com/)
