### ISSUE TITLE
URL for addition to the blacklist

### ISSUE THREAD

**Issue by babylonx** [AdguardTeam/AdguardDNS#129]
Hello, I live in Greece and I have used your DNS servers to avoid youtube ads on my smart tv. Even though I used your DNS servers I still got ads so I used wireshark to capture the traffic from the tv and I found that during the ads **brsl3.cyta.gr** was accessed. I blocked that url via my routers url filter section and now my youtube app on my samsung smart tv is completely ads free. Please consider adding this url to the blocked list.

**Comment by Alex-302** [comment]
We can't block this domain, because it used not[only] for advertising.
Please capture traffic by Fiddler with enabled HTTPS decryption
https://www.fiddlerbook.com/fiddler/help/httpsdecryption.asp
