### ISSUE TITLE
Office 365 outlook.office.com / teams.microsoft.com / etc blocked

### ISSUE THREAD

**Issue by moranbw** [AdguardTeam/AdGuardDNS#130]
Hello, first off -- really impressed with what you've done with the DNS solution.  However I'm having one issue -- seems to be when I try to log into any Office 365 items, such as Outlook (outlook.office.com) and Teams (teams.microsoft.com).  These seem to redirect to their oauth 2 at https://login.microsoftonline.com, which is failing.  Is this a known issue?  I've tried logging out, clearing cache, etc, but don't seem to be having any luck.  Please let me know if there is any additional information I can provide.  Thanks!

**Comment by moranbw** [comment]
After some more digging, I think this may be due to it requesting **ajax.googleapis.com**.  This seems like something that may be blacklisted?

**Comment by ameshkov** [comment]
Tbh, this is not a known issue, and I cannot reproduce this.

> I ran drill on these 3 sites from my local environment, and the one that doesn't seem to get a good reply is login.microsoftonline.com.

The answer is truncated, but this behavior is expected.

Try doing `drill -b 4000 login.microsoftonline.com`

**Comment by moranbw** [comment]
I think you're actually right.  It seems like another DNS tool I have in my chain (stubby), is actually the one causing the issues.  I'll close this issue, sorry for the confusion!
