### ISSUE TITLE
more filter lists

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardDNS#131]
can we add these:
https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_trackingservers.txt
https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_thirdparty.txt
https://github.com/easylist/easylist/blob/master/easylist/easylist_thirdparty.txt

 to here:

https://github.com/AdguardTeam/AdguardDNS/blob/master/Filters/filter.template

**Comment by ameshkov** [comment]
@Alex-302 could you please check these?

**Comment by jo2dan23** [comment]
These should be added also

https://github.com/AdguardTeam/AdguardFilters/blob/master/MobileFilter/sections/specific_app.txt

https://github.com/AdguardTeam/AdguardFilters/blob/master/MobileFilter/sections/specific_web.txt

**Comment by ameshkov** [comment]
@jo2dan23 they are specific to apps, we cannot block them widely as it might break other apps.

**Comment by snhv** [comment]
Hi, not sure if you guys are aware of it but this guy has already compiled a good bunch of hosts into one here:
https://github.com/StevenBlack/hosts

**Comment by Alex-302** [comment]
> https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_trackingservers.txt

It is already merged. Look at your previous issues.

> https://github.com/easylist/easylist/blob/master/easylist/easylist_thirdparty.txt

It is a part of Easylist.

> https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_thirdparty.txt

I will check and add a part of domains later, because I am too busy with ads.

**Comment by Itsnothectic** [comment]
I wanna add this list, very good and has lots that are missing from AdGuard.
It is not an enhanced list so it shouldnt break websites for example reddit or imgur.

https://github.com/quidsup/notrack/blob/master/trackers.txt

**Comment by Itsnothectic** [comment]
Another one, its old but hosts are still used and some are missing from the DNS.
https://pastebin.com/YFu5WbTT

**Comment by sandybeachit** [comment]
Out of interest when you guys add the filter lists like the ones above is this a one off or do you pull from their github and other sources so your DNS is always upto date and you dont have to constantly manually update the lists ?

**Comment by ameshkov** [comment]
> Out of interest when you guys add the filter lists like the ones above is this a one off or do you pull from their github and other sources so your DNS is always upto date and you dont have to constantly manually update the lists ?

Yep, the filter is updated automatically:
https://github.com/AdguardTeam/AdguardDNS/commits/master

DNS servers use Github as a source for rules and periodically check for updates

**Comment by ZeroDot1** [comment]
https://github.com/ZeroDot1/CoinBlockerLists

**Comment by Alex-302** [comment]
That list contains a lot of dead domains. Also we don't block coinhive miner.

**Comment by ameshkov** [comment]
I'd disagree regarding CoinBlockerLIsts, this is the most comprehensive crypto-miners blocking filter I've ever seen.

**Comment by ameshkov** [comment]
@Alex-302 let's keep an eye on CoinBlockerLists and see how it goes with the crypto-jackers in the coming month. Of course, we can't include a third-party filter as a rules source right away (easylist is the only exception), but we can come up with some "staging/review" approach later.
