### ISSUE TITLE
filter not needed

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardDNS#132]
@@||tegna.sc.omtrdc.net^ can be removed from here: https://github.com/AdguardTeam/AdguardDNS/blob/master/Filters/exceptions.txt

we have the whole omtrdc.net domain here already: https://github.com/AdguardTeam/AdguardDNS/blob/master/Filters/exclusions.txt

**Comment by ameshkov** [comment]
+1

**Comment by Alex-302** [comment]
Removed
