### ISSUE TITLE
DNS Filter broke vnexpress.net header

### ISSUE THREAD

**Issue by xpduyson** [AdguardTeam/AdguardDNS#133]
The default dns settings block http://st.f1.vnecdn.net, which contain VnExpress header logo and weather icon:

without AdguardDNS:
![screenshot from 2017-03-29 16-29-08](https://cloud.githubusercontent.com/assets/6981890/24447984/f19095da-149c-11e7-96e1-0801f1ab365d.png)

with AdguardDNS (header logo at top left, weather icon at bottom right):
![screenshot from 2017-03-29 16-29-20](https://cloud.githubusercontent.com/assets/6981890/24447986/f5b8c15a-149c-11e7-87ab-366df76494ab.png)

**Comment by Alex-302** [comment]
ok, removed this domain from DNS filter
