### ISSUE TITLE
Domain blocking request

### ISSUE THREAD

**Issue by nisc3** [AdguardTeam/AdguardDNS#134]
These ad serving and telemetry domains are not blocked.
buzzadnetwork.com
pcpop.com
fasttoss.com
app.market.xiaomi.com
api.ad.xiaomi.com
abtest.mistat.xiaomi.com
mazu.sec.miui.com
adv.sec.miui.com
secure-ds.serving-sys.com
data.mistat.xiaomi.com
sdkconfig.ad.xiaomi.com
tracking.miui.com
visitor-language.herokuapp.com
webview.unityads.unity3d.com
everyplay.com
fast.wistia.com
famo.us
use.typekit.net
shenghuo.xiaomi.com
app.top1mobiad1.com

**Comment by Alex-302** [comment]
Added missed domains.
