### ISSUE TITLE
Many legit sites being blocked, including GitHub

### ISSUE THREAD

**Issue by ubalklen** [AdguardTeam/AdGuardDNS#134]
After configuring my router to use AdGuard DNS, many legit site domains are not being resolved, including GitHub itself.
Is the domain blacklist public available?

**Comment by ameshkov** [comment]
It is, although none of these sites are on that list.

https://github.com/AdguardTeam/AdGuardSDNSFilter

**Comment by ubalklen** [comment]
Any hints on how I should debug this? Some sites still open. Everything comes back to normal if I remove AdGuard DNS.

**Comment by ameshkov** [comment]
First of all, we need to figure out how exactly they're blocked. What error does the browser show?

What response do you have if you run this command in the console: `nslookup domain.com`

**Comment by ubalklen** [comment]
I've fixed the problem. My router interface hides DNS configurations for IPv6, so when I added AdGuard's IPv4 , there was still a standard DNS server around. I found a way to change it to AdGuard's IPv6 and now everything is working like a charm. Thank you @ameshkov.
