### ISSUE TITLE
Android app Hades Star is unable to connect when dns.adguard.com enabled

### ISSUE THREAD

**Issue by mrlucas** [AdguardTeam/AdGuardDNS#135]
The android app/game Hades star http://www.hadesstar.com/
Is unable to launch when I have dns.adguard.com enabled.
I'm using a Google Pixel 4 with private dns.

![Screenshot_20210119-163618](https://user-images.githubusercontent.com/290109/105102936-5180c880-5a75-11eb-9ae9-cfbca06aa9da.jpg)

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdGuardSDNSFilter #549](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/549) via [**ZenHub**](https://www.zenhub.com/)
