### ISSUE TITLE
soylent.com - breaks "Subscribe" and "Add to cart" buttons

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardDNS#135]
https://www.soylent.com/

Original report:
https://www.reddit.com//r/Adguard/comments/669975/adguard_blocking_soylentcom/

**Comment by ameshkov** [comment]
Once it's done we should report back to reddit.

**Comment by Alex-302** [comment]
It requires excluding of `google-analytics.com`
Not a best exclusion for the filters.

**Comment by ameshkov** [comment]
Yeah, that's too much for a single website
