### ISSUE TITLE
aptoide.com

### ISSUE THREAD

**Issue by SMed79** [AdguardTeam/AdguardDNS#136]
Hi, 

**aptoide.com** is blocked by adguard DNS, is this false a positive or voluntarily blacklisted?

- http://www.aptoide.com/
- https://github.com/Aptoide/
- [https://www.virustotal.com/url/5d66db9ae...552aa6b69b0/analysis/1492852063/](https://www.virustotal.com/url/5d66db9aec2b4dd2e8c854ea8bffda751331b5f74c60c5d43e295552aa6b69b0/analysis/1492852063/)

![aptoide.com](http://i.imgur.com/qcAKW3L.png)

Thank you.

**Comment by ameshkov** [comment]
@SMed79 false positive for sure, thanks for reporting it! The issue will be resolved in a few hours when cache is reloaded.

**Comment by SMed79** [comment]
a friend said that the **Aptoide TV** (App Store) still crash when using **adguard DNS**.
- https://m.aptoide.com/installer-aptoide-tv

**Comment by vozersky** [comment]
@SMed79 Hi, do you know what device does he use? Default DNS or family protection? And when does it crash?

**Comment by SMed79** [comment]
Tested on my side.

> do you know what device does he use?

KIII PRO Internet TV Box.

> Default DNS or family protection?

The family protection DNS (not Default)

> And when does it crash?

At the start up crach immediately.

**Comment by ameshkov** [comment]
I guess we can test it on an android device.

@vozersky please do it, i can't do at the moment.

**Comment by vozersky** [comment]
Reproduced. 
@nkartyshov please assist

**Comment by vozersky** [comment]
@SMed79 I am sorry for a late reply, it has been fixed, please give it a try when possible.

**Comment by SMed79** [comment]
> it has been fixed

Can you give details please.

> please give it a try when possible

Yes, after a test... I confirm that the issue is fixed now.

**Comment by nkartyshov** [comment]
> Can you give details please.

@SMed79 We added aptoide.com in a domain whitelist for Family Propection DNS

Can we close task?
