### ISSUE TITLE
DNS Rules number.

### ISSUE THREAD

**Issue by Quorum75** [AdguardTeam/AdGuardDNS#137]
What's the maximum DNS rules? 

It looks like it is between 400,000 and 500,000 but I cannot get the exact number. 

Thanks

**Comment by ameshkov** [comment]
What AdGuard product do you ask about?

**Comment by Quorum75** [comment]
> What AdGuard product do you ask about?

AG Pro iOS.

**Comment by ameshkov** [comment]
It's limited not by a count, but by the memory usage, AGH stops loading rules when the memory used by the index reaches 8MB. Depending on the filter list, it may be 200-500k rules.

**Comment by Quorum75** [comment]
Usually I get an error message if I go over the limit. I don't have any error anymore with 800K rules. ![image](https://user-images.githubusercontent.com/49731083/122059527-0503a400-cded-11eb-94dd-ea1997cc5098.png)

So are you sure of the figures?
