### ISSUE TITLE
Adguard DNS blocks click.malwarebytes.com

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardDNS#138]
Source report:
https://twitter.com/dorinmoise/status/856965765647523842

```
$ nslookup click.malwarebytes.com 176.103.130.130
Server:		176.103.130.130
Address:	176.103.130.130#53

Non-authoritative answer:
click.malwarebytes.com	canonical name = click.virt.s6.exacttarget.com.
Name:	click.virt.s6.exacttarget.com
Address: 127.0.0.1
```

It seems that AG DNS reacted on `exacttarget.com`, I think we shouldn't at least block `click.*.exacttarget.com`

**Comment by Alex-302** [comment]
> exacttarget.com

removed it. Maybe this domain was incorrectly added to Spyware filter.
