### ISSUE TITLE
Key rotation period

### ISSUE THREAD

**Issue by elliotjberg** [AdguardTeam/AdGuardDNS#138]
Hi there! Since switching to use AdGuard's DNS over HTTPS upstream through DNSCrypt-Proxy on various clients, I'm noticing hourly warnings on renewing keys that say this:

Sat Feb  6 13:13:19 2021 [INFO] Refetching server certificates
Sat Feb  6 13:13:19 2021 [INFO] Server certificate with serial #1584455174 received
Sat Feb  6 13:13:19 2021 [INFO] This certificate is valid
Sat Feb  6 13:13:19 2021 [INFO] Chosen certificate #1584455174 is valid from [2020-03-17] to [2022-03-17]
Sat Feb  6 13:13:19 2021 [INFO] The key rotation period for this server may exceed the recommended value. This is bad for forward secrecy.
Sat Feb  6 13:13:19 2021 [INFO] Server key fingerprint is A763:B117:0851:92FB:F45F:15E5:14CC:5858:0D51:D93B:BE33:623D:20E8:9812:3A7B:4B5D

The interesting part there is obviously this warning; "The key rotation period for this server may exceed the recommended value. This is bad for forward secrecy.". Are you able to confirm the key rotation period in use and whether there are any plans to lower it?

**Comment by ameshkov** [comment]
This sounds as if you're using a DNSCrypt upstream, not a DoH upstream.

First of all, I suggest switching to DoH as that DNSCrypt address is obsolete and it's going to be replaced in the nearest future. Most likely, we'll lower the key rotation later when we replace the obsolete addresses with the new ones.

**Comment by elliotjberg** [comment]
Ah yes you're absolutely right - the older clients have pulled down DNSCrypt-Proxy 1.9.x rather than 2.0.x, so aren't using the new servers. Thanks for the pointer and the super quick response!
