### ISSUE TITLE
Applications from Windows Store and system updates fail to download

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardDNS#14]
Happened in stable Win 10.

More info here and in other comments below:
https://forum.adguard.com/index.php?threads/12163/page-2#post-92791

**Comment by ameshkov** [comment]
@Alex-302 could you please take a look?

**Comment by Alex-302** [comment]
Tried, but nothing.
I found few blocked domains
```
c.msn.com
b.scorecardresearch.com
at.atwola.com
b.grvcdn.com
cdn.at.atwola.com
```
but when I try to completely block them by Adguard for Windows, I can't reproduce this issue.

**Comment by Alex-302** [comment]
and these
```
db5.settings.data.microsoft.com.akadns.net
a104-84-176-55.deploy.static.akamaitechnologies.com - blocked by family protection
```

**Comment by ameshkov** [comment]
@nkartyshov could you please take a look at this issue?

@vozersky please put these domains into the parental control whitelist:
```
grvcdn.com
akadns.net
akamaitechnologies.com
```

**Comment by vozersky** [comment]
done

**Comment by nkartyshov** [comment]
Первые несколько доменом от @Alex-302 я два дня назад добавил в whitelist.

Надо ещё раз проверить.

**Comment by ameshkov** [comment]
@nkartyshov так можешь проверить?:)

**Comment by nkartyshov** [comment]
done

**Comment by zebrum** [comment]
it seems that it happened again
id 1502400
"when I leave my pc to auto on the dns servers so it just uses the routers dns (adguard dns), it doesn't work. But if I manually set the dns servers on my pc, it works."

**Comment by ameshkov** [comment]
> But if I manually set the dns servers on my pc, it works."

Manually set it to AG DNS?

**Comment by HardKoreG** [comment]
> Manually set it to AG DNS?
Setting the DNS servers in the ipv4 settings in the network device on the PC. Doing it like that, the Windows 10 app store works fine. But if I leave the PC DNS settings on Automatic and set the AG DNS servers on the router, the Windows 10 store doesn't work.

**Comment by ameshkov** [comment]
That's quite weird. @Alex-302 could you please check it on your side?

**Comment by Alex-302** [comment]
It works on my side. Tried with an old snapshot and family DNS. DNS was applied with disabled Internet, DNS cache was flushed and system rebooted.
Blocked domains:
<details>

![image](http://imagizer.imageshack.com/img922/420/xqWdSG.png)
</details>

**Comment by HardKoreG** [comment]
The AG DNS is set in my router. Here's what happens on my PC: http://i.imgur.com/hVt776H.gifv

**Comment by ameshkov** [comment]
@HardKoreG I wonder, could it be that you router has cached wrong DNS responses? Is there any way to flush router's DNS cache?

**Comment by HardKoreG** [comment]
I don't think there's any way to do that. I don't see any options for that.

**Comment by Alex-302** [comment]
@HardKoreG please try to remove Adguard DNS from your router and leave it in Windows settings.

**Comment by ameshkov** [comment]
@Alex-302 what's the point? We know it works ok in this case.

What we need to do is take a look at the DNS requests log.
@Alex-302 what do you use for logging DNS requests?

**Comment by Alex-302** [comment]
@ameshkov 
WinPcap + DNSQuerySniffer(and flushing dns cache before it)
http://www.nirsoft.net/utils/dns_query_sniffer.html
