### ISSUE TITLE
AdGuard DNS answered 0.0.0.0 in login.live.com and login.microsoftonline.com

### ISSUE THREAD

**Issue by MasatoHanayama** [AdguardTeam/AdGuardDNS#140]
Hello, Thank you for services.
I'm using in Japan.

This title 2 address, I'd executed nslookup command to 2020/02/24 18:30 JST.
DNS answered address 0.0.0.0.

This address added blacklist these days?

**Comment by ameshkov** [comment]
Yep, we're looking into it right now. Should be okay in a few minutes.
