### ISSUE TITLE
False Positive for publish0x.com in AdGuard DNS Block List

### ISSUE THREAD

**Issue by bongochong** [AdguardTeam/AdGuardDNS#141]
Just reporting that publish0x.com is erroneously blocked by AdGuard's DNS filter. It's a legitimate platform, but I can see why it would set off alarms for some people. Thanks for the great work guys!

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdGuardSDNSFilter #597](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/597) via [**ZenHub**](https://www.zenhub.com/)
