### ISSUE TITLE
MovieBox app

### ISSUE THREAD

**Issue by SMed79** [AdguardTeam/AdguardDNS#141]
Hi, 

ads are pushed from these two hosts on the android app MovieBox `http://movieboxapps.com/`

```
sbfunapi.cc
sbfunservice.cc
```
Thank you.

**Comment by Alex-302** [comment]
Try to block sbfunservice.cc only. sbfunapi.cc looks like useful
https://github.com/hw20686832/moviebox/blob/master/moviebox.api

**Comment by Alex-302** [comment]
Or/adn, check  these rules
`||sbfunapi.cc^$app=*package.name*`
`||sbfunservice.cc^$app=*package.name*`
*package.name* - you can find it in Adguard apps settings.

**Comment by SMed79** [comment]
Thank you.

**Comment by Alex-302** [comment]
And? Does it work?

**Comment by SMed79** [comment]
> And?

I am not using the "apps" but Adguard DNS for that reason i reported here.

> Does it work?

Blocking only `sbfunservice.cc` (with the hosts file) work:

```
http://sbfunservice.cc/ads/get_android_ads.json
---
http://sbfunservice.cc/ads/img/jumpycube90.jpg
http://sbfunservice.cc/ads/img/pinballninja320.gif
http://sbfunservice.cc/ads/img/pinballninja728.gif
```

**Comment by Alex-302** [comment]
It is also used not only for ads
http://sbfunservice.cc/coolvideoapp/icon_256.png
http://sbfunservice.cc/coolvideoapp/1.png
http://sbfunservice.cc/coolvideoapp/2.png
Btw I don't see requests to these domains from this app.
