### ISSUE TITLE
Exceptions and exclusions

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardDNS#142]
Is there really a need for both these lists? Cant we just move the remaining filters from exceptions to exclusions since they do the same thing?

**Comment by ameshkov** [comment]
@Alex-302 do we really need all this?

As I see, `@@||cdn1.smartadserver.com^` is necessary indeed as we can't afford excluding whole `smartadserver.com` .

Not sure about other rules.

**Comment by Alex-302** [comment]
We have only necessary @@ exclusions now.
