### ISSUE TITLE
Whitelist RD Station

### ISSUE THREAD

**Issue by Dalcinrafa** [AdguardTeam/AdGuardDNS#142]
rdstation.com is an website of a tool we use in the marketing department in my company. It's not an ad website. I would appreciate a lot if you could whitelist it. Thanks for the amazing work so far!

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdGuardSDNSFilter #605](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/605) via [**ZenHub**](https://www.zenhub.com/)
