### ISSUE TITLE
Server in South America

### ISSUE THREAD

**Issue by Dalcinrafa** [AdguardTeam/AdGuardDNS#143]
Not really a problem with the DNS per se, but it would be really nice if you could host a server in South America. I would be very grateful. Thanks so much!

**Comment by sdgrs546547Q** [comment]
I join the petition, AdGuardDNS is not so fast here like quad9 or Google DNS. Thanks!

**Comment by ameshkov** [comment]
Well, we had a server in Sao Paulo before, but the routing was quite problematic and it received lots of unrelated traffic. We will make a second attempt somewhat later.

Anyways, users from South America should generally be routed to the Miami server and the ping should be okay.

If you're not routed there, we need to know the following information:

1. Your location (country would be enough)
2. Name of your internet service provider
3. We need to see the results of running the following command:
    * macOS: run it in Terminal: `traceroute 94.140.14.14`
    * on Windows run `cmd.exe`, then type in the command and press enter: `tracert 94.140.14.14`

**Comment by D13410N3** [comment]
Servers in SA (Sao Paolo) are added.
