### ISSUE TITLE
dc-unlocker/hcu-client issue

### ISSUE THREAD

**Issue by hooddy** [AdguardTeam/AdGuardDNS#144]
Have hard traffic blocking while tryin to accessing to dc-unlocker services from within dc-phoenix utility. It checks account first and its okay. Next its trying to download some servise information and a this stage its hard freeze. By scientific poke method i have found that reason is in AdGuard DNS filter at my router. As I disable it all turns to okay. Please check it out.

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdGuardSDNSFilter #622](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/622) via [**ZenHub**](https://www.zenhub.com/)
