### ISSUE TITLE
Parkingpay app is broken when using AdGuardDNS

### ISSUE THREAD

**Issue by digitalentity** [AdguardTeam/AdGuardDNS#145]
Parkingpay Android app is a Swiss mobile app to pay for car parking. 

When AdGuardDNS is using "Default" servers, the app doesn't work and shows a banner that the device is not connected to the internet.

When debugging, I found that blocking DNS resolution for `rum-http-intake.logs.datadoghq.com` and `ssl.google-analytics.com` breaks the app. Is there any reason why analytics tracking services and providers are blocked? They are critical for the functionality of some applications and websites.

Please consider creating an option that will block Ads, but not analytics trackers. Thanks!

**Comment by ameshkov** [comment]
@digitalentity would it be enough to unblock just `datadoghq.com`? I could understand if the app depends on the monitoring solution (which DataDog is), but it's definitely not normal to stop working when analytics is blocked, it's worthy of reporting to the app developer then.

**Comment by digitalentity** [comment]
I don't have an option to selectively disable hosts to test, but I would definitely expect the app to work with analytics disabled.

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdGuardSDNSFilter #621](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/621) via [**ZenHub**](https://www.zenhub.com/)
