### ISSUE TITLE
Whitelist these sites

### ISSUE THREAD

**Issue by ePSXe** [AdguardTeam/AdguardDNS#145]
Hi, I have joined some earning online money sites, such as ClixSense (clixsense.com), Neobux (neobux.com) and Adscend Media (asmwall.com), those sites are pretty safe and harmless but still being blacklisted by Adguard DNS...
Really hope you can whitelist them, and thank you for such a great service!

**Comment by vozersky** [comment]
We can't whitelist ClixSense and Neobux, those domains are used to show ads. 
I don't think we block asmwall.com though.
