### ISSUE TITLE
DNS is leaking when using AdGuard DNS DOQ Protocol

### ISSUE THREAD

**Issue by zznosar** [AdguardTeam/AdGuardDNS#146]
Hi team,

My DNS seems to be leaking when im using the DOQ protocol of AdGuard DNS.

When I go to browserleaks.com, i can see my ISP’s DNS plus adGuard DNS(via Choopa). This does not happen when I select DOT or DOH as protocol.

Please see below:

![121DB00F-44C0-4803-8A3D-8A649C94D90E](https://user-images.githubusercontent.com/27464836/111101232-93be1600-859d-11eb-9476-c7b53db6d334.png)

is this a bug or is this a bug in the browserleak website?

Superloop is my ISP.
Choopa is the AdGuard DNS provider here in Australia via anycast.

I tested it using AdGuard Pro / Premium for iOS.

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/DnsLibs #99](https://github.com/AdguardTeam/DnsLibs/issues/99) via [**ZenHub**](https://www.zenhub.com/)
