### ISSUE TITLE
blynk-cloud.com resolves older DNS

### ISSUE THREAD

**Issue by altokarev** [AdguardTeam/AdguardDNS#147]
Adguard DNS resolves blynk-cloud.com to 139.59.206.133.
This address is no longer correct. Blynk changed this address a few months ago. Should resolve to 45.55.96.146.
Blynk devices cannot connect through Adguard due to this incorrect IP resolution.

<details><summary>2ip info:</summary>

![screen shot 2017-05-30 at 13 11 13](https://cloud.githubusercontent.com/assets/28726429/26578666/831f6234-4539-11e7-90b9-5cc872d6face.png)

</details>

**Comment by altokarev** [comment]
https://dns.google.com/resolve?name=blynk-cloud.com

**Comment by altokarev** [comment]
Got some picture and traceroute:

<details><summary>pic</summary>

![screen shot 2017-05-30 at 20 13 01](https://cloud.githubusercontent.com/assets/28726429/26595558/7ff1041a-4574-11e7-86e7-961d8d68f4fa.png)

</details>
<br>
<details><summary>traceroute</summary>

traceroute to 176.103.130.130 (176.103.130.130), 64 hops max, 52 byte packets 
1  192.168.1.1 (192.168.1.1)  0.835 ms  0.525 ms  0.541 ms 
2  * * * 
3  blnmtfh1hb7-ge-0-1-0-u431.int.bresnan.net (69.144.188.153)  10.187 ms  11.705 ms  9.326 ms 
4  host-69-145-233-103.static.bresnan.net (69.145.233.103)  8.805 ms  13.746 ms  10.896 ms 
5  host-72-175-110-180.static.bresnan.net (72.175.110.180)  12.507 ms  13.139 ms  12.268 ms 
6  cspwy002cr5-ge-3-0-1-u0.int.bresnan.net (72.175.110.88)  19.712 ms  20.113 ms  17.756 ms 
7  host-69-146-192-2.chy-wy.client.bresnan.net (69.146.192.2)  18.984 ms  19.763 ms  23.404 ms 
8  host-72-175-110-219.static.bresnan.net (72.175.110.219)  22.734 ms  21.593 ms  18.617 ms 
9  xe-8-0-2.bar2.boston1.level3.net (4.68.127.189)  19.470 ms  22.705 ms  28.447 ms
10  * * *
11  br2.amsterdam1.surf.net (213.244.164.2)  137.226 ms  138.587 ms  153.545 ms
12  xe000-18.rt.ixc.msk.ru.retn.net (46.46.128.101)  176.948 ms  186.681 ms  197.005 ms
13  * * *
14  176-103-130-130.flops.ru (176.103.130.130)  190.345 ms  179.334 ms  178.352 ms

</details>

**Comment by ameshkov** [comment]
> Adguard DNS resolves blynk-cloud.com to 139.59.206.133.

Even my home ISP resolves that domain to that address.

**Comment by ameshkov** [comment]
> Got some picture and traceroute:

This just means that resolution is geo-aware, as you see the answer depends on the server location.
