### ISSUE TITLE
More optional filters

### ISSUE THREAD

**Issue by danwdart** [AdguardTeam/AdguardDNS#148]
It'd be great to have for example "fakenews" and "gambling" as an option for devices where hosts overrides aren't allowed - hosts files are here:
https://github.com/StevenBlack/hosts

**Comment by vozersky** [comment]
@Alex-302 @ameshkov what do you think?

**Comment by ameshkov** [comment]
We will eventually provide people with an option to sign up and set filtering up as they like. Just like what OpenDNS does.

Let's keep this feature request open until then.

**Comment by sergeevabc** [comment]
@kathiedart, I would not use ```hosts``` by Steven Black.
He’s a [rude fellow][1], who blindly aggregates various half outdated lists.
Try [Notracking’s][2] ```hosts``` instead, they are examined more thoroughly. 

[1]: https://github.com/StevenBlack/hosts/issues/281
[2]: https://github.com/notracking/hosts-blocklists

**Comment by kathiedart** [comment]
Fair enough. I'll still have to steal his gambling upstream as I don't care about gambling.

**Comment by ameshkov** [comment]
> He’s a rude fellow, who blindly aggregates various half outdated lists.

That's beautiful. More or less explains why we should be careful with adding more sources.

**Comment by woohooatb** [comment]
Since this thread is open and my topic is related, can you add anti-coin miner filters on your list? 

For example https://github.com/keraf/NoCoin 
Here are their block list https://github.com/keraf/NoCoin/blob/master/src/blacklist.txt and he says he will update them as new miner sites keep popping up. 

More info and news about coin miners https://www.theguardian.com/technology/2017/sep/27/pirate-bay-showtime-ads-websites-electricity-pay-bills-cryptocurrency-bitcoin

**Comment by ameshkov** [comment]
We did this for all AG products in a more gentle manner:
https://blog.adguard.com/en/adguard_vs_mining/

Blocking the whole coin-hive domain is too harsh, it's not too long till they finally fix this on their side and forbid hidden mining.

**Comment by snhv** [comment]
I think blocking of the mining should be default, and the users can choose to whitelist it if they want. My parents for example will click ok to everything.

**Comment by TPS** [comment]
@ameshkov Does this mining-block function on the mobile AG apps, also?

**Comment by ameshkov** [comment]
> Does this mining-block function on the mobile AG apps, also?

Sure

**Comment by ameshkov** [comment]
Duplicates #283
