### ISSUE TITLE
Linking to OpenNIC?

### ISSUE THREAD

**Issue by kathiedart** [AdguardTeam/AdguardDNS#149]
It would also be amazing to link to https://www.opennic.org/ - giving extra TLDs and extra community support.

If I add both, will this service override the ad domains resolved by opennic? Or will opennic resolve the ad domains because AG can't?

**Comment by vozersky** [comment]
@nkartyshov

**Comment by ameshkov** [comment]
Hi! AG is a recursive DNS, so to have an extra TLD which OpenNIC provides, we'll need to use the OpenNIC servers only as an upstream. We'll consider this option.

Also, we're planning to publish the source code once AG DNS is out of beta, so you'll be able to set it up for yourself with whatever DNS you want to have in the upstream.

**Comment by sergeevabc** [comment]
OpenNIC allows to resolve censorship resistant TLDs, e.g. ```.lib``` ([rutracker.lib][1], [flibusta.lib][2]…).
Why do you hesitate to add their anycasts (185.121.177.177, 169.239.202.202) as upstream?

[1]: http://rutracker.lib/
[3]: http://flibusta.lib/
