### ISSUE TITLE
recaptcha.net

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardDNS#149]
@adguard-bot commented on [Sat Apr 10 2021](https://github.com/AdguardTeam/AdguardFilters/issues/80101)

### Issue URL (Incorrect Blocking)
 [http://recaptcha.net](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Frecaptcha.net)
### Comment
Username: @spartanhooah
> Google's reCAPTCHA service (and anything served from a *.gstatic.com domain) has been loading slowly or not at all for me over the last few days when using your DNS servers. If I switch to e.g. Google's, everything works fine. The provided screenshots show the recaptcha JavaScript failing to load.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/uBUK31w.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/Yq5GlLL.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | AdGuard DNS
Browser: | Firefox
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base
Other extensions used: | N/A

---

@Alex-302 commented on [Mon Apr 12 2021](https://github.com/AdguardTeam/AdguardFilters/issues/80101#issuecomment-817837982)

I can't reproduce(in Europe). Is it location related? Please check with VPN+our DNS.

---

@spartanhooah commented on [Mon Apr 12 2021](https://github.com/AdguardTeam/AdguardFilters/issues/80101#issuecomment-817953969)

I don't have a VPN set up that can be in Europe.

**Comment by ameshkov** [comment]
Please re-test it today, this issue is resolved

**Comment by ameshkov** [comment]
@spartanhooah

We'll publish some kind of a post-mortem soon on the blog. There was indeed an issue with Google IPs, a rather interesting one.

**Comment by spartanhooah** [comment]
Oh, interesting. Glad I could help bring it to your attention.

I tested, and it is indeed working again. Thanks!
