### ISSUE TITLE
Returning an empty HTML file instead of nothing

### ISSUE THREAD

**Issue by azuretbn** [AdguardTeam/AdguardDNS#150]
![image](https://user-images.githubusercontent.com/24369901/27000250-217bf59c-4de0-11e7-872f-1a69be413f0c.png)

I think it would be better if it returned an empty HTML file instead when trying to resolve blocked domains. :)

An empty space would be a lot better than seeing this sad face every time, hehe.

**Comment by ameshkov** [comment]
Hi!

It's impossible to do on the DNS level.

I mean for plain HTTP we could resolve blocked domain into some "blocked" IP and always return an empty 1x1 png file, but that won't work for HTTPS at all, you'll always get an insecure certificate error.
