### ISSUE TITLE
Google search ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardDNS#151]
Original report:
https://forum.adguard.com/index.php?threads/google-ads.22304/

The problem is that we cannot hide Google ads on the DNS-level, so we should at least not break clicks on the adverts.

It appears that excluding googleadservices.com is not enough:
https://github.com/AdguardTeam/AdguardDNS/blob/master/Filters/exclusions.txt#L6

The problem is that it is resolved to `pagead.l.doubleclick.net` which is blocked:
```
$ nslookup www.googleadservices.com 176.103.130.130
Server:		176.103.130.130
Address:	176.103.130.130#53

Non-authoritative answer:
www.googleadservices.com	canonical name = pagead.l.doubleclick.net.
Name:	pagead.l.doubleclick.net
Address: 127.0.0.1
```

**Comment by ameshkov** [comment]
It seems that `pagead.l.doubleclick.net` is not used directly, so unblocking it will fix the issue and will not unblock `doubleclick.net` ads.

**Comment by sandybeachit** [comment]
Awesome sounds like a plan :)

Thanks

**Comment by Alex-302** [comment]
`www.googleadservices.com` also must be excluded.
What should I do?

**Comment by ameshkov** [comment]
@Alex-302 isn't it excluded already?

**Comment by Alex-302** [comment]
@ameshkov excluded
```
@@://www.googleadservices.com
```
but it seems not to be working with DNS.
Thesetwo domains in white list unblock useful ads:
```
pagead.l.doubleclick.net
www.googleadservices.com
```

**Comment by ameshkov** [comment]
@Alex-302 I see nothing here that could be blocking googleadservices:
https://github.com/AdguardTeam/AdguardDNS/blob/master/Filters/filter.txt

`pagead.l.doubleclick.net` -- this one indeed should be unblocked.

**Comment by Alex-302** [comment]
ok, excluded `pagead.l.doubleclick.net` only

**Comment by ameshkov** [comment]
Works okay:
```
$ nslookup www.googleadservices.com 176.103.130.130
Server:		176.103.130.130
Address:	176.103.130.130#53

Non-authoritative answer:
www.googleadservices.com	canonical name = pagead.l.doubleclick.net.
Name:	pagead.l.doubleclick.net
Address: 64.233.162.154
Name:	pagead.l.doubleclick.net
Address: 64.233.162.157
Name:	pagead.l.doubleclick.net
Address: 64.233.162.155
Name:	pagead.l.doubleclick.net
Address: 64.233.162.156
```

**Comment by sandybeachit** [comment]
just tried it and it works as expected :) Thanks guys !
