### ISSUE TITLE
Chromecast stopped working

### ISSUE THREAD

**Issue by Bonk-Choy** [AdguardTeam/AdGuardDNS#152]
Hello,

thanks for this DNS. I have enjoyed it for a while.

However, a few days ago I noticed that my 2 different Android TV devices' built-in Chromecast stopped working (the screen mirroring feature still works though). After troubleshooting, I realized that as long as I change the router's DNS to ISP's or 1.1.1.1, the problem will be gone. So I'm pretty sure AdGuard DNS 94.140.14.14 is causing the problem.

Cheers

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdGuardSDNSFilter #655](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/655) via [**ZenHub**](https://www.zenhub.com/)
