### ISSUE TITLE
[Question] - blocked adverts/placeholders break website, should website be unblocked, how to report/deal with this?

### ISSUE THREAD

**Issue by sandybeachit** [AdguardTeam/AdguardDNS#152]
I have some websites where adverts are blocked and the website stops working. This is normal as your blocking the website.

So say we have a site say for example a video streaming site such as (i have a ton more sites like this):

http://www.talkpinas.com/movies/pinoy-movies-youre-my-boss/

which i did log below but the placeholders can not be removed.

https://forum.adguard.com/index.php?threads/www-talkpinas-com.22411/#post-140560

My question is would we unblock that website completely so the site works 100% but also means the adverts get shown or do we keep blocking the adverts and the site breaks.

Im just not sure how best to report these sites as i don't want to be spamming the forum and i dont think its a good idea to let websites/companies know they can get around your system as they will all do it if you make an exception to the rule ?

Can you advise please?

Thanks

David

**Comment by vozersky** [comment]
@nkartyshov

**Comment by vozersky** [comment]
Hi. 

Well, if the website's functionality is broken by the filtering we will certainly look into the case to fix it. The example you've mentioned is not a video streaming site and I don't see anything incorrectly blocked there though.

Closed for now. Let me know if you have any examples, please.

**Comment by sandybeachit** [comment]
One example i have is:
www.watchpinoymoviesonline.com

I am only using Adguard DNS setup on my home router and no other adblocking on my laptop and when attempting to play the video on the above url i am presented with an anti-adblock warning to disable my adblocker, i checked with your filter team and they are unable to unblock this, so how should we proceed? There are a number of other sites like this that i have used and i am sure there are more out there other people use.

The issue is how do we get around these anti-adblock warnings that block content and effectively break the website on AdGuard DNS, should we just add the site to an exclusion list ?



![screenshot_20170614-130350 01](https://user-images.githubusercontent.com/11394779/27131539-f8df782c-5102-11e7-8d02-0b4fcaaf9e19.png)


![screenshot_20170614-130350 01](https://user-images.githubusercontent.com/11394779/27131514-dad2dd6a-5102-11e7-93c4-281a681586a7.png)

**Comment by vozersky** [comment]
Hm, I can't actually make any video play even without Adguard: 

![image](https://user-images.githubusercontent.com/17472907/27131744-ae76f2f8-5114-11e7-9d94-6ff76aaa76ce.png)

Can you?

To be honest, this kind of trashy, full of pop-ups and malicious redirects pages should go straight to safe browsing blacklist, that's what I think.

**Comment by sandybeachit** [comment]
I can get the video to play without using advised DNS and just using my USPS DNS.

There are alot of adverts though on the site


![Uploading Screenshot_20170614-140641.png…]()

**Comment by vozersky** [comment]
in this case please report to this repo: https://github.com/AdguardTeam/AdguardFilters/issues 
please provide the direct link to the video you've tested and specify what server do you use (default or family protection)
