### ISSUE TITLE
[LONG RESPONSE] DNS default ipv4

### ISSUE THREAD

**Issue by rAmfu** [AdguardTeam/AdGuardDNS#153]
Today in Poland we have trouble with use adguard DNS. Website cant load fully. Now DNS response is 300-400ms per ping.

**Comment by ameshkov** [comment]
What server do you see on https://adguard.com/test.html?

**Comment by rAmfu** [comment]
dns2-m247-pra-1

**Comment by ameshkov** [comment]
Weird, Prague is kinda close to you

**Comment by ameshkov** [comment]
Anyways, we're going to add new servers, I'll let you know

**Comment by rAmfu** [comment]
Ok thanks 😉

**Comment by ameshkov** [comment]
@rAmfu could you please check it again?

**Comment by rAmfu** [comment]
**Serwer:** dns2-dp-fra-1
![Screenshot_2021-04-29-20-38-57-394_ua com streamsoft pingtoolspro](https://user-images.githubusercontent.com/32688283/116601737-1a02a180-a92b-11eb-81ae-f85d4734b90b.jpg)
![Screenshot_2021-04-29-20-39-03-090_ua com streamsoft pingtoolspro](https://user-images.githubusercontent.com/32688283/116601740-1b33ce80-a92b-11eb-9f5f-39beedc78465.jpg)

**Ping:** MIN 45 / AVG 52 / MAX 57 / MDEV 4.5 MS

**Comment by ameshkov** [comment]
Well, definitely better than it was before

**Comment by rAmfu** [comment]
Thanks, bro <brofist>
