### ISSUE TITLE
[Improvement] - Additional IP BlockList (30+ Feeds regularly updated)

### ISSUE THREAD

**Issue by versavius** [AdguardTeam/AdguardDNS#154]
I would like to suggest adding this IP Blocklist to your filters, this is a good Feed which pulls in from alot of sources and is updated regularly, so perhaps this one or one similar would help to block out the bad sites and improve the malware/phishing protection.

IPsum is a threat intelligence feed based on 30+ different publicly available lists of suspicious and/or malicious IP addresses. All lists are automatically retrieved and parsed on a daily (24h) basis and the final result is pushed to this repository. List is made of IP addresses together with a total number of (black)list occurrence (for each). Greater the number, lesser the chance of false positive detection and/or dropping in (inbound) monitored traffic. Also, list is sorted from most (problematic) to least occurent IP addresses.

https://github.com/stamparm/ipsum

Thanks

David

**Comment by ameshkov** [comment]
As I understand, it is actually built on top of https://github.com/stamparm/maltrail

Part of the blacklists used by maltrail are already used by us, we'll check the other part.

**Comment by sandybeachit** [comment]
Awesome thanks I did notice one IP which slipped past your system but is on 
that blockbuster I mentioned which I reported here:

https://forum.adguard.com/index.php?threads/http-34-250-229-112.22653/

I figured there might of been something missed as it's on iblocklist but 
not yours :)

Thanks for checking!!

**Comment by sandybeachit** [comment]
Maybe it would be best to use both lists from malyrail and iblocklist? Or would that big down your system too much?

**Comment by vozersky** [comment]
@Alex-302 could you please take a look at those lists?

**Comment by ameshkov** [comment]
@vozersky that's part of the browsing security module, so that's on me

**Comment by ameshkov** [comment]
> Maybe it would be best to use both lists from malyrail and iblocklist? Or would that big down your system too much?

We block only phishing and malware, and maltrail seems to block much more, which will lead to tons of false positives.

**Comment by sandybeachit** [comment]
Ah gotcha, perhaps just using the malware and phishing lists they provide would be beneficial to your filter lists and ignore the rest as they are outside of the scope for Adguard?

**Comment by ameshkov** [comment]
> Ah gotcha, perhaps just using the malware and phishing lists they provide would be beneficial to your filter lists and ignore the rest as they are outside of the scope for Adguard?

Yeah, I'll need some time to examine these feeds, they might have special conditions for commercial use.

**Comment by sergeevabc** [comment]
Why is russianmasonry.ru blocked via “Default mode” DNS?

**Comment by vozersky** [comment]
@sergeevabc fixed 👍   :)
