### ISSUE TITLE
Wanted content is blocked in some Roku apps

### ISSUE THREAD

**Issue by ae5960e8-a6fc-491f-b252-898ecf59af95** [AdguardTeam/AdGuardDNS#155]
With AdGuard DNS enabled on my router, certain Roku apps such as ITV Hub and All 4 result in a black screen, blocking the pre-roll ad as well as the wanted content. (e.g. tv shows, movies, etc) This results in the app being more or less useless.

Only when the DNS is disabled does the issue resolve, so I am sure that AdGuard DNS is the cause.

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdGuardSDNSFilter #661](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/661) via [**ZenHub**](https://www.zenhub.com/)
