### ISSUE TITLE
[Improvement] - Additional Filter List - Block EU Cookie Notifications/Warnings

### ISSUE THREAD

**Issue by sandybeachit** [AdguardTeam/AdguardDNS#155]
This might be an interesting filter list to add, its for Adblock / Adblock plus filter list for blocking cookie notifications, this might eliminate some of the manual work and would be a nice addition to the annoyance list and would speed up browsing via AdGuard DNS by blocking those annoying popups !

Add https://raw.github.com/r4vi/block-the-eu-cookie-shit-list/master/filterlist.txt to your filter subscriptions if you want to block "EU cookie law" notifications and popups.

[https://github.com/r4vi/block-the-eu-cookie-shit-list](https://github.com/r4vi/block-the-eu-cookie-shit-list)

**Comment by ameshkov** [comment]
All these cookie hiding lists rely on cosmetic filters, which cannot be used on the DNS-level :(
