### ISSUE TITLE
Rename the Host Name of each servers to AdGuard DNS

### ISSUE THREAD

**Issue by zeezeepiggy** [AdguardTeam/AdGuardDNS#156]
Hi team,

Can you please rename the hostname of your servers to adGuard DNS something like dns.adguard.com.

Below are Examples:
For ahadns:

https://browserleaks.com/ip/103.73.64.132

Request | 103.73.64.132
IP Address Lookup
IP Address | 103.73.64.132
Hostname | au.ahadns.net

Nextdns is doing the same.

for AdGuard, it’s just vultr. No indicator that adguard dns is being used.

This is the Australian Server:
https://browserleaks.com/ip/139.180.168.247

Request | 139.180.168.247
IP Address Lookup
IP Address | 139.180.168.247
Hostname | 139.180.168.247.vultr.com

It would be great and helpful to users is the Host name is change to AdGuard DNS. Example:
dns.aguard.com or dns.au.adguard.com or etc. that will help identify that the server is indeed adguard. At the moment, there is no way to identify it using dnsleaks or ipleaks or any other tool except visiting your adguard test page or adguard dns website.

**Comment by ameshkov** [comment]
Makes sense. We'll consider doing this when the situation with servers is a little bit more stable (currently, we're setting up new servers and replacing some old ones).

**Comment by zeezeepiggy** [comment]
Bump! Can we do this now? Especially that AdGuard 2.0 is live? Currently, it’s a bit hard to determine if i am connected to AdGuard or Not if i dont  use the adguard test page.

**Comment by zeezeepiggy** [comment]
@ameshkov ✌🏻🙂

**Comment by zeezeepiggy** [comment]
Sorry for the late reply. Happy New Year. Yep. Seems to work now here in Australia - Sydney. Thank you!

**Comment by zeezeepiggy** [comment]
We can close this ticket if required.

**Comment by D13410N3** [comment]
Thank you for confirmation.
