### ISSUE TITLE
Start using Travis-CI for the filters build

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardDNS#157]
Instead of our build server, we'd better use Travis to do the same.

**Example:**
https://github.com/ameshkov/filters/blob/master/.travis.yml
https://ameshkov.github.io/filters/experimental.txt

**Comment by nkartyshov** [comment]
added

**Comment by ameshkov** [comment]
Use gh-pages instead

**Comment by nkartyshov** [comment]
done
