### ISSUE TITLE
increase dns server response time

### ISSUE THREAD

**Issue by Wyvern** [AdguardTeam/AdguardDNS#159]
ping to adguard dns always need 150~200ms to get response, it's almost unusable for general users. hope to increase to less 30ms !

**Comment by vozersky** [comment]
@Wyvern 
Hi! Do you use DNScrypt? 
Please make a traceroute to our servers.
If you are using Windows, you can run this .bat file:
[AdguardDNStest.bat.zip](https://github.com/AdguardTeam/AdguardDNS/files/1127434/AdguardDNStest.bat.zip)

**Comment by wrkerr** [comment]
Does DNScrypt significantly impact latency?

**Comment by vbagirov** [comment]
@wrkerr no, it doesn't really.

**Comment by sergeevabc** [comment]
@Wyvern, delay is a common thing when Alice and Bob are far apart. What is your location?

**Comment by vozersky** [comment]
should be fine with the new servers
please re-open if the issue is still relevant
