### ISSUE TITLE
Webpage shows 'not using AdGuard DNS' if DoH and DoT is blocked

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdGuardDNS#159]
Found this one interesting, when visiting the [set up page for AdGuard DNS](https://adguard.com/en/adguard-dns/overview.html), I noticed it will display that I'm not using AdGuard DNS when using the regular DNS servers, and if all DoH and DoT traffic is being blocked by a firewall (Common for workplaces or when heavy filtering is required).

DNS leak test confirms I am only using two AdGuard DNS regular servers (vultr), and the Chrome console shows failed connection requests to various dnscheck.adguard.com domains via HTTPS (as expected).

Is there a way to confirm for regular DNS connections? Or has something gone wrong with the check if it is supposed to include regular DNS server checking?

**Comment by ameshkov** [comment]
The easiest way to check it would be to run `nslookup dnscheck.adguard.com` and see if it's resolved to any IP address. If it is, AdGuard DNS is working.

**Comment by planet0** [comment]
@ameshkov doing that instantly resolves.

`Server:		127.0.0.1
Address:	127.0.0.1#53

Name:      dnscheck.adguard.com
Address 1: 94.140.14.14
Address 2: 94.140.15.15
Address 3: 2a10:50c0::ad1:ff
Address 4: 2a10:50c0::ad2:ff`

Would there be a way for the AdGuard website to show that I am using AdGuard DNS?

**Comment by ameshkov** [comment]
Well, if it does not show it means something is still wrong. Could it be that your browser uses a different DNS server?

What do you see when you open this page? https://dns.adguard.com/info.txt

**Comment by planet0** [comment]
Browser is using my system DNS, and DNS Leak Test in the browser is able to see the regular DNS servers.
For the page, it's a not found error, as DoH and DoT traffic and domains are being blocked by a firewall, but I am using regular DNS. Is there a way to do a familiar method that DNS Leak Test does, and check via the DNS server IPs?

**Comment by ameshkov** [comment]
You know, I think I know what's going on. Your firewall also blocked our test URLs and this breaks the test.

AdGuard test page requests `https://test-dns-standard-dnscheck.adguard.com/info.json` to check if DNS server is in use. It's located on the same IP address as the DNS server and since you have HTTPS traffic to that IP blocked, test URL does not work either.

**Comment by planet0** [comment]
Ah, I see. So my understanding is that there is no plan to use a seperate IP address for the check to avoid this issue?

**Comment by ameshkov** [comment]
Nope, that's a painful change and doing it for such a unique issue is an overkill.

**Comment by planet0** [comment]
Makes sense! At least now there's something documented for anyone else in this scenario.
