### ISSUE TITLE
Adguard DNS Default IP Possibly Breaking Walmart.com

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardDNS#16]
1. I have only used Adguard DNS (176.103.130.130, 176.103.130.131) with a
few websites because I have to disable it just to search for items on
http://www.walmart.com/ , and so this is the first website that I have
noticed with a problem when using Adguard DNS so far; but I have not gotten
to test Adguard DNS on many websites yet.

2. I can only give steps for one of the problems because if Adguard DNS is
enabled before searching for an item, I can not get to the other problem,
and so all you have to do is go to http://www.walmart.com/ , go to the
search area, type in what item you want to search for, and try to start the
search (clicking the magnifying glass icon on the right side of the search
area or hitting the enter key on your keyboard) but it will not work with
Adguard DNS enabled. I have tested this in the latest Google Chrome and Microsoft Edge on
Windows 10.

3. I do not think that the default Adguard DNS IPs/DNS servers should be set
to block trackers (the spyware list), that list is more likely to break
websites usually so that is one of the reasons that I do not use it even
with the Adguard extension or other adblocking extensions to decrease the
chance of breaking some functionality on websites, and so I think that the
default IPs/DNS servers for Adguard should only focus on blocking ads and
malicious/phishing/scam/grayware/adware/et cetera websites.
**1285994**

// Our agent has tested this at his end and was unable to reproduce the issue.

**Comment by ameshkov** [comment]
@Alex-302 please take a look at walmart issue

**Comment by Alex-302** [comment]
```
C:\Users\Alex>ping omniture.walmart.com

Обмен пакетами с walmart.com.d1.sc.omtrdc.net [::1] с 32 байтами данных:
Ответ от ::1: время<1мс
```
It is blocked by `||omtrdc.net`
Added to exclusions
```
@@||omniture.walmart.com^
@@||omtrdc.net^
```
