### ISSUE TITLE
Issue with adguard dns

### ISSUE THREAD

**Issue by bigbossksa** [AdguardTeam/AdGuardDNS#160]
Adguard dns is not functioning at all 
Ads shows up in games using wifi and 4g 5G network

I ran the app opened dns longs and blocked every connection ads still shows up.
Used adguard dns then adguard dns family 
All same result 

iOS

**Comment by ameshkov** [comment]
Hi, how exactly have you configured AdGuard DNS on your iOS device?

**Comment by mrhashishah** [comment]
> Hi, how exactly have you configured AdGuard DNS on your iOS device?

Installed the app then. Installed vpn profile then select adguard dns server that suppose to block ads and then nothing works google ads shows up.

**Comment by mrhashishah** [comment]
Here some screen shots 
![00C63D75-97F8-4F06-BE97-82B5B3C4C893](https://user-images.githubusercontent.com/47311132/119411763-96528f80-bcf3-11eb-9997-3f62f5a63dc5.jpeg)
![80FDAF86-3485-4B11-9DEA-01A340CD5559](https://user-images.githubusercontent.com/47311132/119411774-9b174380-bcf3-11eb-8f56-3d7a46160d6b.png)
![3D810D53-7FA6-4E83-8B1E-CBDA14A7C99B](https://user-images.githubusercontent.com/47311132/119411775-9bafda00-bcf3-11eb-9de2-5137b47b16c4.png)
![9A8868E9-E7BC-4426-9A9F-1E7EC211693E](https://user-images.githubusercontent.com/47311132/119411777-9c487080-bcf3-11eb-87f0-d4bfe73e13c6.png)

**Comment by ameshkov** [comment]
Just in case, try setting "Full tunnel" mode in AdGuard's low-level settings.

**Comment by mrhashishah** [comment]
> Just in case, try setting "Full tunnel" mode in AdGuard's low-level settings.

It blocked ads using full tunnel mode.
But why it won’t block using split tunnel.

**Comment by ameshkov** [comment]
Tbh, no idea. It'd be better to re-test when the new version of AG is out (most likely next week), there're some important changes in DNS filtering there.
