### ISSUE TITLE
Adguard DNS blocks manage.grab.co

### ISSUE THREAD

**Issue by NgoHuy** [AdguardTeam/AdguardDNS#160]
I found that Adguard DNS blocks some popular site in my country such as: manage.grab.co or phimmoi.net ( not www. phimmoi.net). I cannot see any filter which matched with these domains.

**Comment by vozersky** [comment]
@NgoHuy isn't manage.grab.co  a phishing page imitating grab.com? It's blocked by Browsing security.

You are using Family protection mode and phimmoi.net is blocked by family protection.

**Comment by Alex-302** [comment]
@zebrum manage.grab.co and grab.co are blocked by browsing security. Please check this site.

**Comment by NgoHuy** [comment]
Domain's belong to GrabTaxi, and use for fetch API's data.
![160607171654](https://user-images.githubusercontent.com/1238112/27905981-ef3ba424-626b-11e7-9439-297f90637e7b.jpg)

**Comment by NgoHuy** [comment]
Domain's belong to GrabTaxi and used for fetching API's data.
![160607171656](https://user-images.githubusercontent.com/1238112/27906065-34344df6-626c-11e7-8c28-c0f34b6e3eda.jpg)

**Comment by zebrum** [comment]
manage.grab.co redirects to gamma.grab.co
i'll remove it from our filter.

**Comment by NgoHuy** [comment]
About phimmoi.net and www. phimmoi.net are the same. But I don't see any adult content in this site. which category's it falled in, bro ?

**Comment by vozersky** [comment]
@NgoHuy 

Doesn't look like it, actually:

> grab.co
Domain Name:                                 GRAB.CO
Domain ID:                                   D1136125-CO
Sponsoring Registrar:                        GODADDY.COM, INC.
Sponsoring Registrar IANA ID:                146
Registrar URL (registration services):       www.godaddy.com
Domain Status:                               ok
Registrant ID:                               CR211674701
Registrant Name:                             Registration Private
Registrant Organization:                     Domains By Proxy, LLC
Registrant Address1:                         DomainsByProxy.com
Registrant Address2:                         14455 N. Hayden Road
Registrant City:                             Scottsdale
Registrant State/Province:                   Arizona
Registrant Postal Code:                      85260
Registrant Country:                          United States
Registrant Country Code:                     US
Registrant Phone Number:                     +1.4806242599
Registrant Facsimile Number:                 +1.4806242598
Registrant Email:                            grab.co@domainsbyproxy.com
Administrative Contact ID:                   CR211674702
Administrative Contact Name:                 Registration Private
Administrative Contact Organization:         Domains By Proxy, LLC
Administrative Contact Address1:             DomainsByProxy.com
Administrative Contact Address2:             14455 N. Hayden Road
Administrative Contact City:                 Scottsdale
Administrative Contact State/Province:       Arizona
Administrative Contact Postal Code:          85260
Administrative Contact Country:              United States
Administrative Contact Country Code:         US
Administrative Contact Phone Number:         +1.4806242599
Administrative Contact Facsimile Number:     +1.4806242598
Administrative Contact Email:                grab.co@domainsbyproxy.com
Billing Contact ID:                          CR211674703
Billing Contact Name:                        Registration Private
Billing Contact Organization:                Domains By Proxy, LLC
Billing Contact Address1:                    DomainsByProxy.com
Billing Contact Address2:                    14455 N. Hayden Road
Billing Contact City:                        Scottsdale
Billing Contact State/Province:              Arizona
Billing Contact Postal Code:                 85260
Billing Contact Country:                     United States
Billing Contact Country Code:                US
Billing Contact Phone Number:                +1.4806242599
Billing Contact Facsimile Number:            +1.4806242598
Billing Contact Email:                       grab.co@domainsbyproxy.com
Technical Contact ID:                        CR211674704
Technical Contact Name:                      Registration Private
Technical Contact Organization:              Domains By Proxy, LLC
Technical Contact Address1:                  DomainsByProxy.com
Technical Contact Address2:                  14455 N. Hayden Road
Technical Contact City:                      Scottsdale
Technical Contact State/Province:            Arizona
Technical Contact Postal Code:               85260
Technical Contact Country:                   United States
Technical Contact Country Code:              US
Technical Contact Phone Number:              +1.4806242599
Technical Contact Facsimile Number:          +1.4806242598
Technical Contact Email:                     grab.co@domainsbyproxy.com
Name Server:                                 NS-605.AWSDNS-11.NET
Name Server:                                 NS-421.AWSDNS-52.COM
Name Server:                                 NS-1234.AWSDNS-26.ORG
Name Server:                                 NS-1882.AWSDNS-43.CO.UK
Created by Registrar:                        TUCOWS DOMAINS INC.
Last Updated by Registrar:                   GODADDY.COM, INC.
Last Transferred Date:                       Tue Jun 12 16:51:06 GMT 2012
Domain Registration Date:                    Tue Jul 20 18:00:40 GMT 2010
Domain Expiration Date:                      Wed Jul 19 23:59:59 GMT 2017
Domain Last Updated Date:                    Thu Jan 21 08:32:41 GMT 2016
DNSSEC:                                      false

**Comment by NgoHuy** [comment]
grab.co redirects to grab.com and subdomains are using for some purposes from grab.com site. Domain is hided from whois :)
![170607171708](https://user-images.githubusercontent.com/1238112/27906466-d5157b0e-626d-11e7-8ec2-11daf5ac037f.jpg)

**Comment by zebrum** [comment]
@NgoHuy 

after small research we decided to leave grab.co in browsing security filter. If you trust the site you can click ‘Proceed anyway’ and our browsing security notification won’t bother you again.

phimmoi.net will be removed from Family protection blacklist.

**Comment by NgoHuy** [comment]
Hi @zebrum 
I use adguard dns and don't see any option to procced it, it redirects me to adguard.com. It's official of grab.com's domain. You can recheck with grab security team.

**Comment by ameshkov** [comment]
> after small research we decided to leave grab.co in browsing security filter

Why? The website is 100% legit, removed it as a false positive.

**Comment by ishangirdhar** [comment]
Hi @NgoHuy,

Thank you for bringing this to our attention. We have worked with AdguardDNS team to get our grab.co domain removed from the blacklist. It should be resolved now.

**Comment by ameshkov** [comment]
Guys, please note that it may take a couple of hours for the server cache to be updated.
