### ISSUE TITLE
Expand Yandex domain zones handling

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardDNS#163]
The user lives in the domain zone "by", although on other domains in the zones "ua", "kz", "com" there is the same situation (the user has not checked all domains only "ru", "by", and "ua").
Test method: 
-open yandex.by and write the word "porn", and there the user gets a bunch of requests and endpoints that are not blocked.
- On yandex.ru everything is blocked,  the user would like to see such a picture on other domains

Ticket ID: 1569125

**Comment by vozersky** [comment]
We should expand our rules on the following zones as well:
yandex.ua
yandex.kz
yandex.by
and probably yandex.com as well
@nkartyshov please assist

**Comment by TPS** [comment]
Just for clarity, could this be renamed to <kbd>Yandex domains expanded handling</kbd> or something?  The current title is basically useless.

**Comment by nkartyshov** [comment]
done
