### ISSUE TITLE
Adguard dns blocking a captcha?

### ISSUE THREAD

**Issue by ahoier** [AdguardTeam/AdGuardDNS#163]
Could it be possible AdGuard  dns is blocking a CAPTCHA on Id.spectrum.net? As it’s not allowing me to login to my account stating I need to verify a captcha but there isn’t one.

the page url is actually https://id.spectrum.net/login

Im on a mobile device to not totally sure how to view source (if that would help?) as you may need to be a subscriber/customer for the captcha to load?

**Comment by ameshkov** [comment]
Tbh, I don't think it's AG's fault, it seems that recaptcha is broken there even when I use no blocker at all
