### ISSUE TITLE
fadfada.esy.es - the Family protection false positive

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardDNS#164]
Looks like we block the safe site.

### Steps to reproduce

1. enable the Family protection DNS
2. go here: fadfada.esy.es
3. see what's captured on the screenshot below

### Expected behavior

The site is accessible through the Family protection DNS

### Actual behavior

It's not accessible.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/28571877-776d49b6-714d-11e7-8973-7c0524495a23.png)

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| Family protection ones
| How did you setup DNS configuration:| Reproduced on Adguard Pro as well
| Device model:| (e.g. Google Pixel)| Any
| Operating system and version:| (e.g. Android 7.1.2)| Any

**Comment by altokarev** [comment]
A website has been whitelisted.

Changes will take effect within 48 hours.
