### ISSUE TITLE
api.loganalytics.io and breeze.aimon.applicationinsights.io

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdGuardDNS#167]
I think both domains are blocked by the` ||monitor.azure.com^` rule. Please, take a look.

https://api.loganalytics.io/v1/metadata
https://breeze.aimon.applicationinsights.io/v2/track

```
nslookup api.loganalytics.io 1.1.1.1
Server:		1.1.1.1
Address:	1.1.1.1#53

Non-authoritative answer:
api.loganalytics.io	canonical name = api.monitor.azure.com.
api.monitor.azure.com	canonical name = api.privatelink.monitor.azure.com.
api.privatelink.monitor.azure.com	canonical name = draftprodoms.trafficmanager.net.
draftprodoms.trafficmanager.net	canonical name = azmon-prod-weu-0-ingress-draft.westeurope.cloudapp.azure.com.
Name:	azmon-prod-weu-0-ingress-draft.westeurope.cloudapp.azure.com
Address: 40.113.176.129
```

and 

```
nslookup api.loganalytics.io 
Server:		192.168.0.1
Address:	192.168.0.1#53

Non-authoritative answer:
Name:	api.loganalytics.io
Address: 0.0.0.0
```

**Comment by Alex-302** [comment]
@Eugene-Savenko What is broken?

**Comment by b1ackhawk-uh60** [comment]
@Eugene-Savenko I'm affected by this as well. I do a lot work in the Azure platform. There are tools in the azure portal that do not load correctly with these blocked. Like querying logs and viewing application metrics. Normal stuff from an application support perspective and makes it impossible to work with these blocked.

**Comment by flavio-neves** [comment]
Affected by that as well. If I try to access Azure portal logs blade.

![image](https://user-images.githubusercontent.com/35963484/147263773-71ed8b02-f841-47d2-aa4b-7b66a5ffd4fc.png)

**Comment by flavio-neves** [comment]
This issue only happens when using AD Guard DNS servers. Tried CloudFlare and OpenDNS, both works fine.

**Comment by ameshkov** [comment]
Duplicates https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/860
