### ISSUE TITLE
dns@adguard.com receives emails with empty URLs

### ISSUE THREAD

**Issue by altokarev** [AdguardTeam/AdguardDNS#169]
Started to receive emails with empty URLs. Actual only for 'Family protection' emails atm.a

![screen-shot-2017-08-09-at-17 24 23](https://user-images.githubusercontent.com/28726429/29127098-c8076f5a-7d28-11e7-934e-87d60952bc14.jpg)

**Comment by altokarev** [comment]
User uses Safari browser on iPad.

She just used the feedback button on the blocked page.

URL: http://van-kooten-soest-birkstraat.ambachtsbakker.nl/nl/webwinkel/brood/

**Comment by nkartyshov** [comment]
fixed
