### ISSUE TITLE
trackingshipment.apple.com

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdGuardDNS#169]
My iPhone detected a UPS tracking number in an iMessage chat, and it offered up a link to track the package. Unfortunately, AdGuard DNS blocked the link to trackingshipment.apple.com. I hope you consider unblocking it.

```
nslookup trackingshipment.apple.com
Server:		192.168.0.1
Address:	192.168.0.1#53

Non-authoritative answer:
Name:	trackingshipment.apple.com
Address: 0.0.0.0
Name:	trackingshipment.apple.com
Address: ::
```

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdGuardSDNSFilter #703](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/703) via [**ZenHub**](https://www.zenhub.com/)
