### ISSUE TITLE
www.pcworld.com 

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardDNS#17]
![image](https://cloud.githubusercontent.com/assets/15856304/17292830/08e671c4-57f5-11e6-8953-955f69283ed6.png)

1.open opera
2.navigate to www.pcworld.com
3.open any article

Scroll below for ad's missed by your DNS

**1368782**

**Comment by Alex-302** [comment]
@evgeniy-ADG ничего не разобрать на скрине. Проси не пережимать скрины.
У меня сторонней рекламы нет:
http://www.openscreenshot.com/i3/579f6fc1416415-06931831

**Comment by evgeniy-ADG** [comment]
Вот это 'you might like' - это что-то типа sponsored content. С DNS у себя проверю после 16.

**Comment by Alex-302** [comment]
Оно ж заблокировано. Текст на самом pcworld.com, не со стороннего домена.
