### ISSUE TITLE
GRC Spoofability test - Google IPs

### ISSUE THREAD

**Issue by cooperbang** [AdguardTeam/AdGuardDNS#170]
Hello,

when running the GRC Spoofability test AdguardDNS seems to try to connect to Google LLC IP addresses, but they obviously are not fully responding...

> One or More Nameservers Made Too Few Queries
During the DNS Nameserver Spoofability test, the nameserver(s) listed below failed to emit a sufficient quantity of queries to allow a reliable and accurate appraisal of the nameserver's spoofability. This is an unusual occurrence that typically means that some form of network intermediation, such as a bandwidth or query load-balancer may be interposed between the nameserver and the public Internet. The results from such low-query nameservers can typically be ignored since they are very likely spurious. However, since we did receive some queries, they are listed below in the interest of accuracy and completeness: 

Why AdguardDNS is trying to connect to Google IP addresses (172.x.x.x, 74.x.x.x)?
![ip](https://user-images.githubusercontent.com/75366896/124080214-67de7780-da4a-11eb-9582-461f26e166d3.png)

**Comment by ameshkov** [comment]
@cooperbang if AG DNS fails to resolve a DNS record, it consults Google or CF. In this particular case, it fails to resolve a record since GRC tries to poison the cache.
