### ISSUE TITLE
[request] alternative dns port

### ISSUE THREAD

**Issue by cubakcabak** [AdguardTeam/AdguardDNS#170]
as the title suggested please make the dns server alternative dns port available.

opendns has it on 5353 as alternative dns port.

the reason for it is that my isp block access to 3rd party dns server common port.

thank you in advance.

_Sent from my EVERCOSS S50D using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ameshkov** [comment]
We actually have it for testing purposes:
https://github.com/AdguardTeam/AdguardDNS/issues/140

**Comment by ameshkov** [comment]
It makes sense to add it for all the servers

**Comment by cubakcabak** [comment]
yes, please make it available on all main adguard dns ip.

thank you very much.

_Sent from my EVERCOSS S50D using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by nkartyshov** [comment]
Added alternative 5353 port for all DNS server.

**Comment by cubakcabak** [comment]
thank you for great work, it works wonderfully.

_Sent from my EVERCOSS S50D using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
