### ISSUE TITLE
||kinesis.us-east-1.amazonaws.com^

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdGuardDNS#171]
One of our customers would like to know why do we block that domain. Is it a tracking one? 

> I noticed that kinesis.us-east-1.amazonaws.com resolves to 0.0.0.0 when AdGuard DNS is enabled on my router. Why would it be blocked? Could you unblock it, please?

```
nslookup kinesis.us-east-1.amazonaws.com 94.140.14.14
Server:		94.140.14.14
Address:	94.140.14.14#53

Non-authoritative answer:
Name:	kinesis.us-east-1.amazonaws.com
Address: 0.0.0.0
```

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdGuardSDNSFilter #702](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/702) via [**ZenHub**](https://www.zenhub.com/)
