### ISSUE TITLE
safebrowsing warning page when going to 176.103.130.130 

### ISSUE THREAD

**Issue by woohooatb** [AdguardTeam/AdguardDNS#172]
### Steps to reproduce

1. 176.103.130.130 
2. http://safebrowsing.block.dns.adguard.com/?domain=176.103.130.131
3.
4.

### Expected behavior
Seeing Adguard safebrowsing page 

### Actual behavior
Same as above
![screenshot from 2017-08-26 05-04-51](https://user-images.githubusercontent.com/13932279/29735878-1ff38f14-8a1c-11e7-991d-cd3f74b45b3a.png)

### Your environment

|   Description  |     Value    |
Is this expected or something else going on here?

**Comment by ameshkov** [comment]
Should redirect to Adguard DNS overview

**Comment by nkartyshov** [comment]
fixed
