### ISSUE TITLE
[Feature Request] Block Page

### ISSUE THREAD

**Issue by zero77** [AdguardTeam/AdguardDNS#173]
Can you display a block page for every time a domain has been blocked. 
Also, can you add a proceed any way option to the block page that allows you to proceed to the website anyway, like googles malware detection page.
Thanks

**Comment by vozersky** [comment]
@zero77 hi! could you please elaborate a little bit more?  we do already have a page for blocked malware domains and domains blocked by family mode server

**Comment by zero77** [comment]
HI, @vozersky 
yes the sort of page you use now is good but with an option to proceed to the web site any way and a page that is displayed on every blocked domain.

For example, If I was to visit a domain that was blocked like adfly, I would get a warning/block page telling me it is blocked by adguard but with the option to visit the domain any way.
Like googles malware block page.

**Comment by vozersky** [comment]
Unfortunately, it is not technically possible, domains are blocked on DNS level, not HTTP. We can't add an option to proceed and make a personal exclusion for user like we do in Adguard browsing security.

**Comment by zero77** [comment]
Is it still possible to have the block page, even if there’s no redirect button allowing you to the blocked domain.

**Comment by vozersky** [comment]
@zero77 I still can't get what is wrong with one we already have

![image](https://user-images.githubusercontent.com/17472907/30272186-ea7e8630-96fb-11e7-989d-dea35984fd90.png)

**Comment by zero77** [comment]
Maybe it’s a problem at my end because that is what I mean, but I am not getting that although, I am using it through dnscrypt.

**Comment by vozersky** [comment]
@zero77 you will only see it if you try to go directly to the blocked domains

**Comment by vozersky** [comment]
@zero77 but normally when you use Adguard DNS, you don't see it much, 'cause mostly the requests are blocked (to adnetwork's domains etc.)

**Comment by zero77** [comment]
Yes, I didn’t think I would see it for third party blocks like google analytics. 
But, I don’t see it when I go directly do a domain like adf.ly I just get “server not found” without the block page.
