### ISSUE TITLE
A local LAN DNS server - Windows

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardDNS#174]
Can you add a local LAN DNS server that uses your preferred PC's configured DNS server filters it with Adguard installed and outputs the filtered URL's to the PC's local DNS on the user`s PC which is IP 192.168.5.24 
on the user`s LAN the user wants to use 192.168.5.24 as the user`s DNS server address in the secondary router or individual devices to make ad blocking possible when the PC's main DNS in network settings is set to a dns unblocking service like a DNS address from unotelly unblock-us
getflix etc. That way the user can block most ads on all my devices on my LAN

Ticket id : 1560748

**Comment by Bluscream** [comment]
So the user wants to use a local windows machine running Adguard For Windows as DNS server?

**Comment by pheggie** [comment]
Yes it is partially done for hosts files only so far on Acrylic DNS Server
I tested this DNS server called Acrylic DNS

http://mayakron.altervista.org/wikibase/show.php?id=AcrylicHome

that can be used on a LAN that blocks ads through it’s hosts files but it didn’t work well with my DNS unblocking Service though for some unknown reason. Maybe it could be modified for use with adguard

**Comment by pheggie** [comment]
Yes I'd like adguard to do the DNS filtering of ads on the same PC and the same PC act as a DNS server on my LAN. A mini windows 10 PC would be my preferred option

**Comment by Bluscream** [comment]
PyHole is also a good local dns adblocker

**Comment by pheggie** [comment]
Pyhole sounds great but unlike Pyhole i hope adblock dns server doesn't require setting up a seperate web server to work i'd like it to work for inexperienced dummies I'd like it self contained.

**Comment by pheggie** [comment]
In installing a DNS server like Acrylic DNS on windows 10 you have to free up port 80 in Services by
disabling World Wide Web Publishing Service on Windows 10 machines it'll be the same for
adguard DNS server

**Comment by pheggie** [comment]
I purged the Acrylic DNS cache and now it's working great with my unblocking DNS provider simpletelly 
I'd being changing DNS providers and must have screwed up the Acrylic DNS Cache
Acrylic DNS might be able to be modified to use adguard

**Comment by ameshkov** [comment]
We will eventually publish AG DNS as a standalone application which you can install wherever you want. But we didn't plan to make it a simple product for anyone, more like a pihole -- it'll require some knowledge to set it up.

**Comment by pheggie** [comment]
Great news @ameshkov I hope it has a built in web server and good guides for newbies

**Comment by pheggie** [comment]
@ameshkov you'd sell a lot more if you made AG DNS easy to setup like with a setup wizard and leave custom setup to techies who know what their doing and have adguard updates delivered silently

**Comment by pheggie** [comment]
@ameskhov antivirus anti-dns spoofing like by default ON in AVG Antivirus will have to be turned off
to play with DNS settings other than ISP DNS

**Comment by ameshkov** [comment]
> @ameshkov you'd sell a lot more if you made AG DNS easy to setup like with a setup wizard and leave custom setup to techies who know what their doing and have adguard updates delivered silently

First of all, we're planning to target *nix OS so that it was possible to install it on a router.

**Comment by jsEveryDay** [comment]
Just found out about AdGuard

It's called **DNSMASQ** people... made in the 80s. The most efficient, lightest, fastest dns management. You can install it on any router you have root access, any device really... old Nokia phones if you wish, install it on your smart tv if you want. It's a Server and a client. Set it up on 1 device on your LAN and you're set. Forward requests like Acrylic.. to 8.8.8.8 after you apply your own filter. You can even run a router (DHCP) and what not on DNSMASQ. You want to run it on the best networking device you have, your router. 
Latency? .. I get 14ms to reach 8.8.8.8 but how to measure the latency between router and pc over wifi? well, ping a blocked domain. ex. google-analytics.com => 0.02ms response.

Want an interface? How bout DD-WRT ? Use an old router if you have - connect it to your main one - your new DNS server is the old routers IP. Try tomato.... look at this.

![image](https://user-images.githubusercontent.com/16431055/31050236-b38a65c4-a612-11e7-894a-e4a1a74b1d75.png)

**Comment by ameshkov** [comment]
Duplicates #283
