### ISSUE TITLE
Please add the Pegasus Spyware List domains in AdGuard DNS

### ISSUE THREAD

**Issue by zznosar** [AdguardTeam/AdGuardDNS#176]
Hi team,

Any chance of adding the Pegasus spyware domains listed in the below:

https://github.com/AmnestyTech/investigations/blob/master/2021-07-18_nso/domains.txt

NextDNS added them in their threat intelligence.

Just thinking that this would be a great addition too to AdGuard DNS.

Thanks.

**Comment by ameshkov** [comment]
Sorry for the late reply, we've added it to the browsing security sources
