### ISSUE TITLE
freecounterstat.com adserver / Update for AdguardDNS

### ISSUE THREAD

**Issue by SMed79** [AdguardTeam/AdguardDNS#177]
Hello,
I am comming from this commit https://github.com/AdguardTeam/AdguardFilters/commit/fc7be9dd3aac8edaf4c66f410820df0e53ef245f

Can please merge the below hosts to Adguard [DNS servers](https://adguard.com/en/adguard-dns/overview.html)?

privacy + ads
```
counter8.besucherstatistiken.com
counter8.freecounterstat.com
counter2.besucherstatistiken.com
counter2.contadorvisitasgratis.com
counter7.contadorvisitasgratis.com
counter8.contadorvisitasgratis.com
counter2.allfreecounter.com
counter2.compteurdevisite.com
counter2.freecounterstat.com
counter7.fcs.ovh
counter2.freecounterstat.ovh
counter2.01counter.com
counter7.besucherstatistiken.com
counter7.allfreecounter.com
counter7.statcounterfree.com
counter8.bestfreecounterstat.com
counter8.contatoreaccessi.com
counter8.fcs.ovh
counter2.fcs.ovh
counter8.statcounterfree.com
counter8.allfreecounter.com
counter2.contatoreaccessi.com
counter7.contatoreaccessi.com
counter2.freecounter.ovh
counter7.01counter.com
counter8.webcontadores.com
counter8.compteurdevisite.com
counter2.statcounterfree.com
counter7.bestfreecounterstat.com
counter7.compteurdevisite.com
counter7.freecounter.ovh
counter7.freecounterstat.ovh
counter7.webcontadores.com
counter8.freecounterstat.ovh
counter2.bestfreecounterstat.com
counter2.webcontadores.com
counter8.freecounter.ovh
counter7.freecounterstat.com
counter8.01counter.com
```

privacy
```
geoloc11.geostats.ovh
geoloc12.geo20120530.com
geoloc13.geostats.ovh
geoloc13.whoaremyfriends.com
geoloc13.whoaremyfriends.net
geoloc14.geostats.ovh
geoloc14.whoaremyfriends.net
geoloc15.geo20120530.com
geoloc15.geovisite.ovh
geoloc11.geovisite.ovh
geoloc12.geostats.ovh
geoloc13.geovisite.ovh
geoloc15.geostats.ovh
geoloc15.whoaremyfriends.com
geoloc14.whoaremyfriends.com
geoloc12.whoaremyfriends.net
geoloc11.geo20120530.com
geoloc13.geo20120530.com
geoloc12.whoaremyfriends.com
geoloc14.geovisite.com
geoloc11.whoaremyfriends.net
geoloc11.whoaremyfriends.com
geoloc13.geovisite.com
geoloc15.geovisite.com
geoloc11.geovisite.com
geoloc12.geovisite.com
geoloc15.whoaremyfriends.net
geoloc14.9cd47096ab1495d8d3b18667f6a52b9c.com
geoloc11.9cd47096ab1495d8d3b18667f6a52b9c.com
geoloc12.9cd47096ab1495d8d3b18667f6a52b9c.com
geoloc15.9cd47096ab1495d8d3b18667f6a52b9c.com
geoloc13.9cd47096ab1495d8d3b18667f6a52b9c.com
geoloc14.9cd47096ab1495d8d3b18667f6a52b9c.com
ns336739.ip-37-187-249.eu
```
fyi @seanl-adg @StevenBlack @yous

Thank you.

**Comment by ameshkov** [comment]
@Alex-302 

Let's do the following:

1. Add `privacy + ads` part to the French filter (remove subdomains though: `counter2.contadorvisitasgratis.com` --> `contadorvisitasgratis.com`).
2. Include ad servers from the French filter to https://github.com/AdguardTeam/AdguardDNS/blob/master/Filters/filter.template
3. Add servers from the `privacy` list to the Spyware filter.

All these will be included into AG DNS after the filter rebuilding.

**Comment by SMed79** [comment]
> Add privacy + ads part to the French filter (remove subdomains though

Already added here https://hg.adblockplus.org/listefr/rev/c7891188163e#l1.48

**Comment by ameshkov** [comment]
@SMed79 the problem with Liste FR is that it's not divided into parts (third-party ad servers, first-party adservers, etc) as it is done in EasyPrivacy or EasyList for instance. Hence, trying to include the whole Liste FR into the DNS filtering may cause incorrect blocking due to the nature of DNS-level ad blocking. We'd be glad to include Liste FR as a source if you provide a separate file of third-party ad servers.

**Comment by SMed79** [comment]
Sorry, I thought you're talking about the **[French filter](https://filters.adtidy.org/extension/chromium/filters/16.txt)**.

**Comment by ameshkov** [comment]
@SMed79 yeah, we'll have to include duplicates to the part not inherited from Liste FR -- so that [this part](https://github.com/AdguardTeam/AdguardFilters/blob/master/FrenchFilter/sections/adservers.txt) could be then included into the DNS filter [sources list](https://github.com/AdguardTeam/AdguardDNS/blob/master/Filters/filter.template).

**Comment by ameshkov** [comment]
Duplicating the same lines in the fork is a bit clumsy indeed, we have to rework the filters build process so that the duplicates were eliminated from the final filter.

**Comment by Alex-302** [comment]
@ameshkov 

> Let's do the following:
> 
> Add privacy + ads part to the French filter (remove subdomains though: counter2.contadorvisitasgratis.com --> contadorvisitasgratis.com).
> Include ad servers from the French filter to https://github.com/AdguardTeam/AdguardDNS/blob/master/Filters/filter.template
> Add servers from the privacy list to the Spyware filter.
> All these will be included into AG DNS after the filter rebuilding.

done
