### ISSUE TITLE
DNS duplicate entries?

### ISSUE THREAD

**Issue by Quorum75** [AdguardTeam/AdGuardDNS#178]
[https://github.com/StevenBlack/hosts/issues/1181#issuecomment-594253098](Duplicate)

"Looking at AdguardDNS.txt, eyeballing from top to bottom, man that file is a mess. I have a legitimate question: how does one curate a large, random order file?

Interesting the file contains 29,193 domain lines, but only 29,172 unique domains, so there are 21 duplicate domains, which is not a lot, but it reinforces my central point: you can't curate a hot mess.

Looking at the commit history of adguardDNS.txt, that's automated curation. Nobody appears to be eyeballing this."

**Comment by ameshkov** [comment]
Tbh this is a very old discussion, I don't think there're any duplicates right now.

**Comment by Quorum75** [comment]
> Tbh this is a very old discussion, I don't think there're any duplicates right now.

Old? Seriously? 5 days ago only.... 😁

**Comment by ameshkov** [comment]
I mean the discussion that you linked in the issue.

**Comment by Quorum75** [comment]
Yes the discussion is 5 days old. 

Anyway, no biggie, just want to tell you that some people are using AG (with or without your approval) and some people are just critizing AG. 
And that upseted me the most.

**Comment by ameshkov** [comment]
Maybe the link is wrong? The last comment there is from 14 Jul 2020.

> Anyway, no biggie, just want to tell you that some people are using AG (with or without your approval) and some people are just critizing AG.
> And that upseted me the most.

No worries, people like to criticize, don't get upset over it:)
