### ISSUE TITLE
paybal.com phishing/malware distribution

### ISSUE THREAD

**Issue by snhv** [AdguardTeam/AdguardDNS#178]
paybal.com is a phishing/malware distribution domain which redirects to malware distribution site. Please block it. Thanks.

### Steps to reproduce

1.
2.
3.
4.

### Actual behavior

<details><summary>Screenshot:</summary>

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| (e.g. Default, 176.103.130.130)
| How did you setup DNS configuration:| (System/DNSCrypt app/Router)
| Device model:| (e.g. Google Pixel)
| Operating system and version:| (e.g. Android 7.1.2)

**Comment by ameshkov** [comment]
Done, thank you!
https://reports.adguard.com/en/paybal.com/report.html
