### ISSUE TITLE
mirdao.ru - false positive

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardDNS#179]
http://safebrowsing.block.dns.adguard.com/?domain=mirdao.ru

![image](https://user-images.githubusercontent.com/15856304/30206657-6402b4d6-9495-11e7-916f-d5cd1a5e2d51.png)

The site is safe.

**Comment by evgeniy-ADG** [comment]
Or deleting from filters would be enough to fix this?

**Comment by vozersky** [comment]
@evgeniy-ADG removing from safebrowsing DB is enough
