### ISSUE TITLE
(whitelist) link.safelinkconverter.com

### ISSUE THREAD

**Issue by 3xploiton3** [AdguardTeam/AdGuardDNS#18]
link
https://link.safelinkconverter.com/review.php?id=aHR0cHM6Ly9nKCguZ2wvTkxNanB2&c=1&user=54097

please whitelist safelinkconverter

SS :
https://i.imgur.com/UVaR16Q.png

**Comment by Alex-302** [comment]
@AdamWr should we block this domain?
It was blocked in
https://github.com/AdguardTeam/AdguardFilters/commit/bd3e687879a6af9390d81660cf98f49c24d6a560

**Comment by 3xploiton3** [comment]
Please whitelist this, it is short url like bit.Ly

**Comment by AdamWr** [comment]
>@AdamWr should we block this domain?

I don't remeber why I added this rule to `cryptominers` section, but on some websites script from this domain replaces orginal link to something like this:
`https://link.safelinkconverter.com/epub.php?id=<base64>`
so I consider it as some kind of ad.
For example here - `https://www.kubusoft.com/google-chrome-latest.html`

I will move this rule to `English > specific` section, so it will be not blocked by DNS.

**Comment by Alex-302** [comment]
ok
