### ISSUE TITLE
analytics.google.com blocked?

### ISSUE THREAD

**Issue by gingerbeardman** [AdguardTeam/AdGuardDNS#180]
I need to access this domain to check my website analytics.

Previously that worked just fine.

However recently this has begun to be blocked? 

https://analytics.google.com

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdGuardSDNSFilter #724](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/724) via [**ZenHub**](https://www.zenhub.com/)
