### ISSUE TITLE
search.aol.com allows turning off safe search

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardDNS#181]
search.aol.com allows turning off safe search and using the AdGuard content filtering for my family doesn’t enforce safe search on that site. I know that OpenDNS enforces it, but also blocks images on that site somehow.

STR:

With AdGuard DNS content filtering enabled, go to search.aol.com and search for boobs. By default, the safe search will be set to moderate. Turn it off and you will see boobs in the image search results.

**Comment by ameshkov** [comment]
As I recall, AG DNS does not enforce safe search on AOL. 

Also I can't find any network administrator instruction on enforcing the safe search. I wonder how OpenDNS does it.
