### ISSUE TITLE
Syntax Problem With "ttp"

### ISSUE THREAD

**Issue by Quorum75** [AdguardTeam/AdGuardDNS#182]

**Comment by ameshkov** [comment]
It has nothing to do with AG DNS

**Comment by Quorum75** [comment]
If so who is responsible for blocking the website when it is not mentionned in the filter?

**Comment by ameshkov** [comment]
Here, filed it to a proper repo: https://github.com/AdguardTeam/DnsLibs/issues/118

**Comment by Quorum75** [comment]
Thanks Andrey.
