### ISSUE TITLE
Sites are blocked with DNS enabled

### ISSUE THREAD

**Issue by darkulish** [AdguardTeam/AdguardDNS#182]
Access to some sites are blocked when DNS service is enabled - even
when DNS request blocking is disabled. Choice of DNS provider does not
matter. Site displays normally when DNS service is disabled.

1. Enable DNS
2. Open website
3. Site can't be reached

Ticket ID 644192

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| 176.103.130.130 , 176.103.130.131 
| How did you setup DNS configuration:| System
| Device model:| amzn Kindle Fire HDX
| Operating system and version:| AndroidVersion : 5.1.1 (sdk=22)

**Comment by ameshkov** [comment]
Should've been filed to the Android repo.

Moved it:
https://github.com/AdguardTeam/AdguardForAndroid/issues/1439
