### ISSUE TITLE
Video doesnt play

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardDNS#183]
In this site video doesnt play when DNS (Family protection) is enabled: http://www.hddizifullizle.com/esra-erol-14-eylul-2017-izle-hd/

Note: Without DNS video plays.

![screenshot_259](https://user-images.githubusercontent.com/19608513/30471048-441f85fe-9a08-11e7-9bfc-8f9acb4d6e24.png)

**Comment by Alex-302** [comment]
Not reproduced on my side.

**Comment by vozersky** [comment]
reproduced on my side, could you please check once more? @Alex-302

**Comment by Alex-302** [comment]
we don't block that player
![image](https://user-images.githubusercontent.com/8361299/33794455-30bbfb7c-dcd5-11e7-8246-fe75fbc4c432.png)
