### ISSUE TITLE
American user, recently started showing usage on London servers?

### ISSUE THREAD

**Issue by Nick2bad4u** [AdguardTeam/AdGuardDNS#183]
When I check the website:
https://adguard.com/en/adguard-dns/overview.html

I am now being shows as using the London server (and have been for a while now)

I also notice pinging the servers seems to give a 110ms response, which tells me its overseas.

Why am I not hitting the closer servers in America?

Currently setup:

Phone:
DHCP pushes out the AdGuard DNS IP (94.140.14.14) to my phone. Shows London.

PC:
Using Microsoft Edge Chromium and DNS-over-HTTPS (https://dns.adguard.com/dns-query). Shows London.

![image](https://user-images.githubusercontent.com/20943337/129498296-bd5b1c5b-ae4a-4cb9-bc35-6c1149ba4429.png)

**Comment by ameshkov** [comment]
Unfortunately, anycast IPs is not a 100% guarantee that you'll be routed to the closest server. From what I can see ~10% of US users are routed elsewhere. There's no silver bullet, but we hope that it will get better with time when we add more servers.
