### ISSUE TITLE
App-Measurement.com - sends device ID used for ads

### ISSUE THREAD

**Issue by EntropySmoke** [AdguardTeam/AdGuardDNS#185]
App-Measurement.com links Google Accounts to Android Device RDID (Resettable  Device  Identifier), also known as "Ad  ID". AdGuardDNS filter comments say that it is problematic to block/black-hole it.  Is that still the case? That domain is blocked in almost every major ad-block list. 

There is more information here - https://www.scss.tcd.ie/doug.leith/apple_google.pdf .

**Comment by ameshkov** [comment]
As I recall, if we have this domain blocked, Android devices may start to make thousands of queries to it.

@AdguardTeam/filters-maintainers guys, could you please check if that's the case now on your Android devices?

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdGuardSDNSFilter #739](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/739) via [**ZenHub**](https://www.zenhub.com/)
