### ISSUE TITLE
Adguard Family DNS allows to open some NSFW sites

### ISSUE THREAD

**Issue by abx-dx** [AdguardTeam/AdGuardDNS#186]
### **Steps to reproduce**
Using AdGuard DNS Family Protection as DNS over HTTPS or TLS
Open these sites:
https://hdabla.net
https://www.seemysex.com
https://bestpornohere.com
https://xxxshake.com

### **Expected behavior**
These sites should be blocked.

### **Actual behavior**
The sites opened successfully.

**Comment by ameshkov** [comment]
Fixed, please wait a few hours for the changes to take effect
