### ISSUE TITLE
smartredirect.de redirection broken

### ISSUE THREAD

**Issue by sdfasdfgawe456h4356** [AdguardTeam/AdguardDNS#186]
### Steps to reproduce

1. visit http://beste-apps.chip.de/android/app/telekom-mega-deal-android-app,de.telekom.megadeal/
2. click the link that should lead you to the download of the app
3.
4.

### Expected behavior

you should end up on the site where you can download the app

### Actual behavior

adguard dns blocks the redirection via smartdirect.
the problematic filter appears to be: https://github.com/AdguardTeam/AdguardDNS/blob/77511b48223aeff0fd6923adcb0b33e2d10cd608/Filters/filter.txt#L3480

i understand that this increases privacy but it completely breaks the redirection which i think is far too high a price. usability > privacy.

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| 176.103.130.130
| How did you setup DNS configuration:| Router
| Device model:| PC
| Operating system and version:| Windows 10

**Comment by nkartyshov** [comment]
@Alex-302 Please, exclude a domain ```smartredirect.de```

**Comment by Alex-302** [comment]
@nkartyshov Done.
