### ISSUE TITLE
||com.net^ - safebrowsing false positive?

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardDNS#187]
Hello,

all subdomains for com.net is blocked now:

![image](https://user-images.githubusercontent.com/45385632/131264498-5e1b8644-1df6-4196-ab13-dc4aaa12e44b.png)

It is really required? I don't think so 😄 Please, check this out.

Thank you.
Cheers!

**Comment by ameshkov** [comment]
Yep, false positive indeed. Should be good in 20 minutes, thanks for reporting it!
