### ISSUE TITLE
Apple TV ads are not being blocked

### ISSUE THREAD

**Issue by mattjis** [AdguardTeam/AdguardDNS#187]
I live in Australia and it seems all the channel apps on my Apple TV still have ads.

**Has ads:**
- 9now
- tenplay

**No longer work:**
- PLUS7

I'm keen to help find these domains/ips but am unsure where to look

**Comment by ameshkov** [comment]
Hm, it'd be complicated to troubleshoot without actual access to the DNS requests log(

**Comment by ameshkov** [comment]
Do you know how to extract DNS requests log from the router?

**Comment by mattjis** [comment]
I did some research and learnt how to log the network connections from an Apple TV.

Both the apps with ads seem to be accessing the same domains: akamaitechnologies.com & compute.amazonaws.com - the akamai domain is giving all the video (ads & actual content) while the compute.amazonaws.com only seems to connect before & during the ads.

Is this hopeless because the ads & content are coming from the same domain?

**Comment by ameshkov** [comment]
Sorry for the late reply:(

It *might* help to block `compute.amazonaws.com`, blocking `akamaitechnologies.com` will break the video for sure.

Have you tried it?

**Comment by mattjis** [comment]
How would I block them? My router doesn't have any way to block certain domains or ip address' :(
