### ISSUE TITLE
DNSCrypt udp not responding

### ISSUE THREAD

**Issue by mpas97** [AdguardTeam/AdGuardDNS#188]
Since a few months I have to force dnscrypt-proxy to use tcp as suddenly all udp requests to your DNSCrypt are not being answered anymore.

**Comment by mpas97** [comment]
Without forcing tcp, we have really long resolution times as it tries several times over udp, before it falls back to tcp. Browsers, for instance, end with "site not found" due to this timeout.
<img width="402" alt="grafik" src="https://user-images.githubusercontent.com/9994218/131363946-4ffe89c7-8546-47cc-8ff1-6365c0c2ad55.png">

**Comment by ameshkov** [comment]
@mpas97 hi, what SDNS stamp do you use?

**Comment by mpas97** [comment]
@ameshkov sdns://AQMAAAAAAAAAETk0LjE0MC4xNC4xNDo1NDQzINErR_JS3PLCu_iZEIbq95zkSV2LFsigxDIuUso_OQhzIjIuZG5zY3J5cHQuZGVmYXVsdC5uczEuYWRndWFyZC5jb20
I also tried the family one, it also fails.

**Comment by ameshkov** [comment]
Could you please tell me what it shows you here? https://dns.adguard.com/info.txt

**Comment by ameshkov** [comment]
One more question, I see that your UDP packets are padded to length 1252, is this a normal behavior or have you made any additional changes to dnscrypt-proxy settings?

**Comment by mpas97** [comment]
1) dns2-dp-ams-2
2) No idea. I did not change any settings like these, almost for sure. I tried other preconfigured sdns like quad9, that works fine.

**Comment by mpas97** [comment]
I just clicked through all files in the dnscrypt-proxy repo: `MaxDNSUDPSafePacketSize = 1252`

**Comment by ameshkov** [comment]
@jedisct1 Frank, could you please chime in for a moment? I don't understand why UDP packets are of that size here, is this a normal behavior for dnscrypt-proxy? I suspect this might be the reason why they don't come through to our server.

Also, we don't pad DNSCrypt messages to 1252 in our implementation, is this a recommended behavior?

**Comment by jedisct1** [comment]
Hi there!

In order to make amplification impossible, and also to be compatible with anonymization, the protocol recommends responses sent over UDP to not be larger than the question. If this is not the case, the response will be sent over TCP. The client can dynamically adjust the padding if it frequently gets large responses.

The actual issue is that AdGuard servers seem to drop questions that are larger than 512 bytes, padding included.

**Comment by ameshkov** [comment]
@jedisct1 

> The actual issue is that AdGuard servers seem to drop questions that are larger than 512 bytes, padding included.

Yep, right, that's how it's configured right now. Is it not compatible with the default settings in dnscrypt-proxy? Do you think we should increase the read buffer size?

**Comment by jedisct1** [comment]
A larger buffer size (at least for DNSCrypt) would fix this. Ideally, it should match the maximum size of a response.

**Comment by ameshkov** [comment]
Got it, will do then.

**Comment by ameshkov** [comment]
Probably, I should change the default buffer size in our dnscrypt implementation then, it currently defaults to 512B: https://github.com/ameshkov/dnscrypt/blob/master/server.go#L53

**Comment by ameshkov** [comment]
@mpas97 the issue should be gone in 1-2 hours, could you please test it again then?

**Comment by jedisct1** [comment]
You can bump it even more to support anonymization - Queries from relays always use UDP,

**Comment by mpas97** [comment]
@ameshkov It works! Thank you very much for this fast solution!

As a little side note, dnscrypt-proxy always tells me `[WARNING] [adguard-dns] uses a non-standard provider name ('2.dnscrypt.default.ns1.adguard.com.' doesn't start with '2.dnscrypt-cert.')`.

**Comment by ameshkov** [comment]
> As a little side note, dnscrypt-proxy always tells me [WARNING] [adguard-dns] uses a non-standard provider name ('2.dnscrypt.default.ns1.adguard.com.' doesn't start with '2.dnscrypt-cert.').

Well, it's been 5 years since we use that provider name, it's too late to change it now.
