### ISSUE TITLE
The Family Protection DNS blocks at.ua domain

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardDNS#188]
> [...] K сожалению из-за блокировки сайтов на домене at.ua мы не можем получить доступ к нашему сайту lyceum11.at.ua и различным рабочим сайтам mmk.at.ua.

ID: 1637005

**Comment by nkartyshov** [comment]
The domains added in the parental control exclusions. The users can check the work tomorrow.

**Comment by nkartyshov** [comment]
done
