### ISSUE TITLE
my.screenname.aol.com Access Denied

### ISSUE THREAD

**Issue by ashvets-sup** [AdguardTeam/AdguardDNS#189]
When trying to log in to one's personal account on AOL.com (http://myaccount.aol.com/ or https://my.screenname.aol.com) with the Adguard enabled, it is being reported as a phishing page and blocked.

The Adguard assistant, however, reports the website has an excellent reputation.

[screen shot 2017-09-29 at 5 30 25 am](https://user-images.githubusercontent.com/32528702/31203797-592b235e-a971-11e7-9760-2d82e7022a5c.png)

Should this website be removed from suspicious?

**Comment by ameshkov** [comment]
The strange thing about it is that it's not on the list of suspicious:
https://reports.adguard.com/en/my.screenname.aol.com/report.html

We'll check it, thanks for pointing it out!

**Comment by evgeniy-ADG** [comment]
I think it's been deleted by another support agent from the list a few days ago. How long does it take for the DNS list to update?

**Comment by nkartyshov** [comment]
@evgeniy-ADG The DNS refresh the cache once a day. Now, the website must be available.
