### ISSUE TITLE
www.bild.de - anti adblock message

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/AdguardDNS#19]
![](http://i.imgur.com/kW6Kjsx.png)

![](http://i.imgur.com/UB8znJ9.png)

tested on windows and adguard pro on iOS

**Comment by Alex-302** [comment]
temporary excluded
```
@@||ec-ns.sascdn.com^
@@||cdn1.smartadserver.com^
```

**Comment by Vincent-Michael** [comment]
same problem still @Alex-302

**Comment by Alex-302** [comment]
Please check now. Exclusion for smartadserver.com was changed.
