### ISSUE TITLE
safe search and restricted mode

### ISSUE THREAD

**Issue by superislam** [AdguardTeam/AdGuardDNS#19]
hello ad guard thanks for the dns and family filter but there is a problem in YouTube when restricted mode is forced on there is clean videos we cant see and clean comments too how can i solve this problem thanks

**Comment by TPS** [comment]
Wouldn't that be out-of-scope for AGDNS, iff all it's doing is enforcing YouTube's own Restricted Mode?  Try contacting them per/via https://support.google.com/youtube/answer/7354993

**Comment by ameshkov** [comment]
You can use the regular AdGuard DNS instead of "family protection".
