### ISSUE TITLE
Quad9

### ISSUE THREAD

**Issue by BirdInFire** [AdguardTeam/AdGuardDNS#190]
Hello,

I have a suggestion to add more security with the ads filtering.

Two possibility

One : every request you generate a request to quad9 dns (and store any nxdomain that you receive that your own dns does not found nxdomain), after that you implement this cache in the dns response.

It permit you to use the 18+ thread list of Quad9 without having to actually use them as forwarder.

Second possibility, use Quad9 as a forwarder for all your dns server with you blocklist.

I know adguard home permit it.
But many will install default dns and forget it, so add this feature enhance the security and block publicity as well.

**Comment by ameshkov** [comment]
That's just not how public DNS recursive resolvers work, we don't forward queries to some other DNS resolvers.

Also, I don't think Quad9 would allow this kind of usage. Their data is not free, we cannot use it that way.
