### ISSUE TITLE
redirection broken adjust.com

### ISSUE THREAD

**Issue by sdfasdfgawe456h4356** [AdguardTeam/AdguardDNS#191]
### Steps to reproduce

1. go to https://www.youtube.com/watch?v=ETCDN0l7Xxc and click on one of the ref-links in the description
2. for example: https://www.youtube.com/redirect?v=ETCDN0l7Xxc&event=video_description&q=http%3A%2F%2Fbit.ly%2F2uYAr9c&redir_token=i2mFzDDW6du91wmjdN2eEyR6kz18MTUwNzQxNTc4MkAxNTA3MzI5Mzgy
3.
4.

### Expected behavior
i should be send to the google play store to be able to download the app

### Actual behavior
adguard dns blocks adjust.com and i get stuck at https://app.adjust.com/97kwng?campaign=111085

<details><summary>Screenshot:</summary>

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| 176.103.130.130 standard
| How did you setup DNS configuration:| (System/DNSCrypt app/Router)
| Device model:| (e.g. Google Pixel)
| Operating system and version:| (e.g. Android 7.1.2)

**Comment by Alex-302** [comment]
excluded from dns filter
