### ISSUE TITLE
current updated list of blocked domains

### ISSUE THREAD

**Issue by eladkarako** [AdguardTeam/AdGuardDNS#192]
where may I get the current list of blocked domains (or rules) that is used in AdGuard public DNS now days?

<details><summary>this is a question related to AdGuard public DNS service,</summary>  

and not specifically to this repository (which hasn't been updated for quite some time now),  
but since it might be relevant to other people, I've choose to use the github issues system, and not addressing the support through email.
</details>

**Comment by ameshkov** [comment]
Here it is: https://github.com/AdguardTeam/AdGuardSDNSFilter

**Comment by eladkarako** [comment]
oh thanks.  
I can see now that https://github.com/AdguardTeam/AdGuardSDNSFilter/blob/master/configuration.json has recently changed and includes AdGuard block-list (which makes sense),  
and eventually I also found out that the newly blocked domains came from an overly eager avast's so called "internet protection", core protection, sat in the background, in quite mode... 
<details><summary>🚘/🥜</summary>
(it was driving me nuts)
</details>
