### ISSUE TITLE
http 404 error

### ISSUE THREAD

**Issue by dmheard** [AdguardTeam/AdguardDNS#192]
### Steps to reproduce

1.https://www.broadbandchoices.co.uk/product/4932#summary
2.http://www.moneysupermarket.com/broadband/fibre-optic-broadband/?postcode=DA3+7JR
3.
4.

### Expected behavior

When I click on the links to visit provider/go to site I should get redirected. Works if I switch off DNS.
### Actual behavior

I get http 404 error on every link I click.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/32650298/31353107-22690e2e-ad29-11e7-96d0-de0d73774ebf.png)

</details>

### Your environment

Windows 10 
Microsoft Edge 40.15063.0.0
Microsoft EdgeHTML 15.15063

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| (e.g. Default, 176.103.130.130) 176.103.130.130
| How did you setup DNS configuration:| (System/DNSCrypt app/Router) 
Go to ’Network and Internet’ category and then to ’Network and Sharing Center’
On the left side of the screen find ’Change adapter settings’ and click on it
Select your active connection, right-click on it and choose ’Properties’
Find ’Internet Protocol Version 4 (TCP/IP)’ in the list, select it and then click on ’Properties’ again
Choose ’Use the following DNS server addresses’ and enter these: 
176.103.130.130
176.103.130.131
| Device model:| (e.g. Google Pixel) Desktop PC
| Operating system and version:| (e.g. Android 7.1.2) Windows 10 Pro v.1703

**Comment by vozersky** [comment]
@Alex-302 could you please assist?

1. https://www.broadbandchoices.co.uk/product/4932#summary
2. click on those buttons: https://uploads.adguard.com/up05_4mi9q.png

reproduced, 404 with Adguard DNS

**Comment by Alex-302** [comment]
2 - fixed
1 - ad.doubleclick.net is blocked. We can't unblock it, because it is advertising domain
