### ISSUE TITLE
Server in South America

### ISSUE THREAD

**Issue by sdgrs546547Q** [AdguardTeam/AdGuardDNS#195]
Hello devs. Thanks for your AdGuard DNS service, I use it on a daily basis and it works quite well, and I look forward to the arrival of the new AdGuard DNS, when it comes out I will probably pay for it.When the new service is launched, will you still launch dns servers for South America? Thanks

**Comment by ameshkov** [comment]
We actually have a server in Brazil, but the routing is not ideal. We're continuing to look for the options there.

**Comment by marcelloinfoweb** [comment]
+1
