### ISSUE TITLE
Use random subdomains in DNS check

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardDNS#195]
Talking about AG DNS check on this page: https://adguard.com/en/adguard-dns/overview.html

We currently use these two domains to do the check:
dnscheck-default.adguard.com
dnscheck-parental.adguard.com

The problem is that they could be cached by Chrome and work even when AG DNS is disabled.

**Comment by vozersky** [comment]
done

**Comment by ameshkov** [comment]
Cannot confirm

**Comment by vozersky** [comment]
@nkartyshov
