### ISSUE TITLE
https://www.neobux.com - blocked by the DNS

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardDNS#196]
Can't reach the site https://www.neobux.com

### Steps to reproduce

1. Head to https://www.neobux.com
2. See the error

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/31863847-3f70531e-b75c-11e7-994c-4727538c12d9.png)

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| Standard
| How did you setup DNS configuration:| router or in AdGuard Pro
| Device model:| (e.g. Google Pixel) iPhone SE
| Operating system and version:| 11.1

**Comment by Alex-302** [comment]
Excluded from DNS filter.
