### ISSUE TITLE
AdGuard DNS breaks YouTube App Search & History functions on Roku and Apple TV

### ISSUE THREAD

**Issue by EntropySmoke** [AdguardTeam/AdGuardDNS#196]
During the past 2-3 days, YouTube Search & History functions within YouTube App on Roku and Apple TV broke when used with AdGuard DNS (and no other filters). It didn't affect browsers, only the YouTube App.

The issue appeared to be with blocking Google's "doubleclick" ad domains and blocking public Google DNS resolver IP's. 
https://www.reddit.com/r/Roku/comments/q25irc/unable_to_search_on_youtube/
https://www.reddit.com/r/pihole/comments/q27i76/youtube_on_roku_not_showing_search_box_when/
https://piunikaweb.com/2021/10/06/youtube-search-function-not-working-on-roku-workaround-inside/
https://community.roku.com/t5/Channel-Issues-Questions/Youtube-No-longer-able-to-search/td-p/726690
https://forums.macrumors.com/threads/apple-tv-4k-youtube-not-marking-videos-as-watched-and-not-adding-to-history.2310516/
https://forums.macrumors.com/threads/youtube-search-not-working.2315485/

**Comment by EntropySmoke** [comment]
Domain static.doubleclick.net + its CNAME servers need to be unblocked on filtered AdGuard DNS servers, but unblocking such domains is a big deal and a move in the wrong direction in the world of ad-blocking...
With ads and tracking moving from 3rd parties to 1st parties, domain blocking may become obsolete. Nothing can stop Google, Microsoft, Amazon, Apple, and Facebook from deliberately making an important service function break if any ad domains are blocked...

**Comment by EntropySmoke** [comment]
Any updates on this?

**Comment by planet0** [comment]
From memory, YouTube search and watch history is using `s.youtube.com` and I don't think this is currently blocked on AdGuard DNS. It may have changed since I last looked into it, though.

**Comment by Quorum75** [comment]
Same here no issue on ATV with YTV regarding the history. However, something watched on this iPhone takes some time to appear on the ATV. You need to give some time, the sync doesn't seem to be on real time.
