### ISSUE TITLE
 Youtube Ads are not blocked.

### ISSUE THREAD

**Issue by mkaliyannan** [AdguardTeam/AdguardDNS#197]
# Youtube Ads are not blocked.

Yyoutube ads are not blocked. I guess, quiet harder to block since dns work on domain level and doens't applied by filter. I wonder any idea to implement like https proxy for network level ad blocker.

**Comment by Bluscream** [comment]
It's even hard to block them with the "full" adguard version so why should the 'less power' DNS do it?

**Comment by ZeroDot1** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/7228

**Comment by vozersky** [comment]
It is not possible with DNS blocking
