### ISSUE TITLE
How do I choose Stockholm server?

### ISSUE THREAD

**Issue by Owyn** [AdguardTeam/AdGuardDNS#198]
I'm physically near Stockholm but it uses Singapore server with 300ms+ latency it seems, how do I fix it? 

can you maybe give me IP for Stockholm adguard dns?

![image](https://user-images.githubusercontent.com/1309656/136837200-0cc441d3-2147-488a-9b7c-299f6dbce7e6.png)

![image](https://user-images.githubusercontent.com/1309656/136837279-53fd6024-b858-4f56-a686-53e958148944.png)

````
tracert 94.140.14.14

Трассировка маршрута к dns.adguard.com [94.140.14.14]
с максимальным числом прыжков 30:

  1     1 ms     1 ms     1 ms  100.90.128.1
  2     2 ms     2 ms     2 ms  10.2.244.78
  3    13 ms    13 ms    13 ms  85.21.225.13
  4    13 ms    13 ms    13 ms  tc-bb-te3-5.corbina.net [195.14.54.180]
  5    13 ms    13 ms    13 ms  217.161.97.25
  6   198 ms   201 ms   198 ms  ae29-pcr1.fnt.cw.net [195.2.8.202]
  7    47 ms    47 ms    47 ms  ae9-xcr1.mrx.cw.net [195.2.25.189]
  8   184 ms   184 ms   184 ms  ae33-xcr1.sng.cw.net [195.2.2.58]
  9   280 ms   280 ms   280 ms  217.161.92.98
 10   308 ms   304 ms   305 ms  dns.adguard.com [94.140.14.14]

Трассировка завершена.

````

I could write to my ISP support and ask them to try to fix the route if you give me some details for it and the correct route \ ip or something

**Comment by ameshkov** [comment]
К сожалению, это просто невозможно.

Мы специально слушаем только на Anycast-адресах и пока что не планировали менять это. Возможно, в будущем мы добавим такую возможность, задачи в dnsproxy будет достаточно чтобы мы про это не забыли.

**Comment by planet0** [comment]
Hi @ameshkov, I've also noticed that although I'm close to Sydney, Australia, AdGuard DNS is also routing me to Singapore. Is there any reason why?

**Comment by ameshkov** [comment]
@Owyn добрый день! А можете запостить еще разок трейсы и всю информацию о провайдере?
https://github.com/AdguardTeam/AdGuardDNS/issues/99#issuecomment-957884990

Я сейчас не вижу, чтобы русские пользователи вообще попадали куда-то кроме Франкфурта и Стокгольма.

**Comment by Owyn** [comment]
````
tracert 94.140.14.14

Трассировка маршрута к dns.adguard.com [94.140.14.14]
с максимальным числом прыжков 30:

  1     1 ms     1 ms     1 ms  100.126.0.1
  2     *        *        *     Превышен интервал ожидания для запроса.
  3    45 ms    43 ms    43 ms  85.21.225.13
  4    14 ms    13 ms    13 ms  tc-bb-te3-5.corbina.net [195.14.54.180]
  5    43 ms    41 ms    40 ms  ancotel-bb.fra.corbina.net [83.102.167.65]
  6    54 ms    42 ms    44 ms  ae6.francoforte73.fra.seabone.net [195.22.214.196]
  7    43 ms    43 ms    43 ms  ae2.franco31.fra.seabone.net [195.22.211.213]
  8    39 ms    40 ms    39 ms  79.140.89.18
  9    43 ms    43 ms    43 ms  dns.adguard.com [94.140.14.14]

Трассировка завершена.
````

https://beeline.ru

**Comment by ameshkov** [comment]
Ну нормально, франкфурт это ожидаемо и это примерно то же качество, что и Стокгольм.
