### ISSUE TITLE
[Question] DNSCrypt

### ISSUE THREAD

**Issue by Snapy** [AdguardTeam/AdguardDNS#198]
Hi! I have a few questions regarding recent changes.

1. You're latest PRs on the dnscrypt-proxy repo removed half of your DNS servers from the list of supported DNSCrypt servers : Which DNS servers support DNSCrypt?
2. Regular DNS says it supports ports 53 & 5353 but nothing regarding DNSCrypt (even in the KB). DNSCrypt "official" port is 443 (official port for https) but common ones are 5353, 1053, 443, 5053, 2053. I see you use port 5443. Which port(s) is(are) supported by which type of DNS?
3. Do you plan on implementing DNSCrypt for other app?

TIA

**Comment by ameshkov** [comment]
> You're latest PRs on the dnscrypt-proxy repo removed half of your DNS servers from the list of supported DNSCrypt servers : Which DNS servers support DNSCrypt?

We just don't want to spam the resolvers list with too many AG servers. These 4 servers should be enough. However, DNSCrypt is still supported by secondary servers.

> Regular DNS says it supports ports 53 & 5353 but nothing regarding DNSCrypt (even in the KB). DNSCrypt "official" port is 443 (official port for https) but common ones are 5353, 1053, 443, 5053, 2053. I see you use port 5443. Which port(s) is(are) supported by which type of DNS?

Just as you said, 53 and 5353 are for regular DNS, 5443 for DNSCrypt.

> Do you plan on implementing DNSCrypt for other app?

We will implement it in AG for iOS. We don't plan to implement it in the desktop apps as there are plenty of other options for both PC&Mac that can be used along with AG.

**Comment by Snapy** [comment]
So if I understand correctly, to use non listed DNSCrypt servers one must configure them manually ?

**Comment by ddhelmet** [comment]
I am using Simple DNSCrypt and every DNS server except AdGuard works. Choosing AdGuard DNS breaks the internet and Windows says something about DNS server not responding.

**Comment by ameshkov** [comment]
> So if I understand correctly, to use non listed DNSCrypt servers one must configure them manually ?

Sorry for the late reply. Yes, you're right.

> I am using Simple DNSCrypt and every DNS server except AdGuard works. Choosing AdGuard DNS breaks the internet and Windows says something about DNS server not responding.

What exact version of Simple DNSCrypt do you use?

**Comment by vozersky** [comment]
@ddhelmet please let me know if the question is still relevant. If you were using ipv6 servers please make sure you've enabled ipv6 in the network interface
