### ISSUE TITLE
Feature request: add DNSCrypt support

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardDNS#2]
Please look into it. What should be done to add it?

DNSCrypt website:
https://dnscrypt.org/

Yandex browser has dnscrypt support, but I am not sure if they allow using a third party DNS server.

**Comment by ameshkov** [comment]
Note on Yandex, they have a hardcoded list of dnscrypt servers:
![capture_07272016_001718](https://cloud.githubusercontent.com/assets/5947035/17157499/6aa57344-5398-11e6-8b60-73b23b15f64a.jpg)

**Comment by lordraiden** [comment]
This should be a must have for Adguard DNS, I would use it without hesitation.
And take a look to DNSSEC
https://www.reddit.com/r/sysadmin/comments/2hn435/dnssec_vs_dnscrypt/
https://security.stackexchange.com/questions/91725/dnscrypt-vs-dnscurve
https://www.dnssec-validator.cz/

**Comment by nkartyshov** [comment]
done

**Comment by TPS** [comment]
Is Android getting this builtin?

https://android-review.googlesource.com/#/q/topic:dns-dev-opt+(status:open+OR+status:merged)

via https://www.xda-developers.com/android-dns-over-tls-website-privacy/ .  Does this change anything for y'all?

**Comment by ameshkov** [comment]
Nobody supports DNS over TLS on the server side yet. However, I guess DNS over TLS will quickly surpass DNSCrypt if it gets native support on Android.
