### ISSUE TITLE
Family Protection: Enforce SafeSearch

### ISSUE THREAD

**Issue by andrews05** [AdguardTeam/AdguardDNS#20]
For the family protection DNS, it would be really good to enforce Google SafeSearch. Google tells how to do this at the DNS level here: https://support.google.com/websearch/answer/186669?hl=en

[edit] Also YouTube restricted mode: https://support.google.com/a/answer/6214622

**Comment by ameshkov** [comment]
@andrews05 great idea, thank you!

**Comment by ameshkov** [comment]
@nkartyshov please do both things: Google SafeSearch and YT restricted mode.

**Comment by andrews05** [comment]
Bing SafeSearch: http://help.bingads.microsoft.com/apex/index/18/en-US/10003

**Comment by ameshkov** [comment]
@andrews05 I wonder will it work for the Yahoo search as well?

**Comment by andrews05** [comment]
From what I've been able to find, Yahoo doesn't currently have a similar feature.

**Comment by ameshkov** [comment]
@nkartyshov also here is an instruction for Yandex:
https://yandex.ru/support/search/schoolsearch.xml#hosts

**Comment by nkartyshov** [comment]
done

**Comment by andrews05** [comment]
I'm not seeing this in effect yet, is it supposed to be live now?

**Comment by ameshkov** [comment]
Oh, I see what's the issue 

```
192-168-10-199:~ ameshkov$ nslookup www.google.com
Server:		176.103.130.132
Address:	176.103.130.132#53

Non-authoritative answer:
www.google.com	canonical name = forcesafesearch.google.com.
Name:	forcesafesearch.google.com
Address: 216.239.38.120

192-168-10-199:~ ameshkov$ nslookup www.google.ru
Server:		176.103.130.132
Address:	176.103.130.132#53

Non-authoritative answer:
Name:	www.GOOGLE.ru
Address: 216.58.209.195
```

@nkartyshov you have forgotten about ALL other google domains.

**Comment by ameshkov** [comment]
@nkartyshov the list of google domains:
https://www.google.com/supported_domains

**Comment by nkartyshov** [comment]
@andrews05 I added the missing domains. Please, check.

**Comment by andrews05** [comment]
Yup, all working now thanks!

**Comment by andrews05** [comment]
DuckDuckGo Safe search: https://duck.co/help/features/safe-search

**Comment by ameshkov** [comment]
@andrews05 can't be enforced on DNS level, see #268

**Comment by andrews05** [comment]
Ah, sorry should have searched first.
Hope they can get that sorted sometime...
