### ISSUE TITLE
'Stable' download location for current filter.txt?

### ISSUE THREAD

**Issue by dibdot** [AdguardTeam/AdguardDNS#200]
Hi,

I'm the developer of the 'adblock' package for OpenWrt/LEDE (see [here](https://github.com/openwrt/packages/tree/master/net/adblock/files) and I'm using your outstanding filter list as one source for my adblocker.
Currently the following download link of your 'master' branch is configured:
https://raw.githubusercontent.com/AdguardTeam/AdguardDNS/master/Filters/filter.txt 
=> this seems to be a stale file, more than 4 months old!

There is another branch 'gh-pages' which seems to hold the current filter.txt:
https://raw.githubusercontent.com/AdguardTeam/AdguardDNS/gh-pages/Filters/filter.txt

Last but not least there is a third download location with current filter.txt, but with windows line end encodings:
https://filters.adtidy.org/windows/filters/15.txt

Which one is the 'right' / stable download location, preferable without windows line encodings?
Thanks!

**Comment by nkartyshov** [comment]
@dibdot 
A stable and current version of the filter is located at: https://filters.adtidy.org/windows/filters/15.txt
