### ISSUE TITLE
blocklist colletion to block yt ads

### ISSUE THREAD

**Issue by nofx2thedarkgod** [AdguardTeam/AdGuardDNS#201]
Hello,I love your dns and your work but I noticed your lists do not block youtube ads.
I'd like to share with you my collection list,if you upload it in your blitz but,please,also in ipv4 dns,I am sure it will block youtube too (tested till today) .
Here you can download it : https://www.dropbox.com/s/rvzr29j22dikf4v/nofx2list.txt?dl=0
let me know if u like it and if you will implement it!
cheers

**Comment by ameshkov** [comment]
Unfortunately, there is no way to block YT ads on the DNS level that would work for anyone.

Your list may work for you, but it'd break YT for some other user.
