### ISSUE TITLE
Spotify app ads not blocked

### ISSUE THREAD

**Issue by chaNcharge** [AdguardTeam/AdguardDNS#201]
Spotify ads are basically not being blocked. Similar to #197, it may be difficult to block ads.

### Expected behavior

Spotify ads are skipped
### Actual behavior

Ads continue like normal

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| Default
| How did you setup DNS configuration:| Router, AirPort Extreme
| Device model:| iPhone 6 Plus
| Operating system and version:| iOS 11.0.3

**Comment by vozersky** [comment]
@Alex-302 is it possible with dns?

**Comment by Alex-302** [comment]
Never seen them.

**Comment by Bluscream** [comment]
I see them sometimes and then they only disappear after a LuckyPatcher patch

**Comment by chaNcharge** [comment]
It also doesn't work on the youtube mobile app.

**Comment by ameshkov** [comment]
Spotify ads are loaded from this location:
`https://spotify.com/ads/`

DNS is too rough, it cannot block a location without blocking the whole spotify.com :(

**Comment by chaNcharge** [comment]
Ouch, that's unfortunate. Oh well, they aren't too frequent or too long anyway.
