### ISSUE TITLE
Slow DNS in UK

### ISSUE THREAD

**Issue by Altycoder** [AdguardTeam/AdGuardDNS#203]
I'm using a dns test app ([link](https://play.google.com/store/apps/details?id=com.catinthebox.dnsspeedtest&hl=en_GB&gl=US)) on android and cloudflare, google, quad9 and cleanbrowsing are all in the 9-12ms range on average. adguard dns is usually 150-200 ms on average.  Picture of dns test results attached.

![20211102_081606](https://user-images.githubusercontent.com/1990152/139810435-6338d146-edad-4cad-8137-6177114c84f3.jpg)

I'm in the Manchester area (ISP is BT g.fast) and https://dns.adguard.com/info.txt returns "dns2-dp-lon-1"

If I ping dns.adguard.com I get an average ping of ~7.5 ms but if I ping 94.140.15.15 I get an average ping of ~250 ms. For 94.140.14.14 I get an average ping of ~7.5ms.

```
traceroute to dns.adguard.com (94.140.15.15), 30 hops max, 60 byte packets

1 _gateway (192.168.1.1) 0.254 ms 0.285 ms 0.323 ms
2 * * *
3 * * *
4 31.55.185.188 (31.55.185.188) 7.167 ms 7.494 ms 7.207 ms
5 core2-hu0-17-0-1.colindale.ukcore.bt.net (195.99.127.156) 7.932 ms core1-hu0-15-0-8.colindale.ukcore.bt.net (213 .121.192.12) 7.868 ms core1-hu0-17-0-5.colindale.ukcore.bt.net (195.99.127.150) 8.799 ms
6 peer7-et-3-0-4.telehouse.ukcore.bt.net (109.159.252.160) 8.650 ms peer7-et-0-1-4.telehouse.ukcore.bt.net (109.15 9.252.94) 36.209 ms peer7-et-3-1-7.telehouse.ukcore.bt.net (109.159.252.172) 7.367 ms
7 166-49-214-194.gia.bt.net (166.49.214.194) 7.708 ms 7.388 ms 7.490 ms
8 * 212.119.4.140 (212.119.4.140) 9.468 ms ldn-b3-link.ip.twelve99.net (213.248.71.146) 9.134 ms
9 ae-7.r20.londen12.uk.bb.gin.ntt.net (129.250.4.140) 14.887 ms 14.426 ms ldn-bb1-link.ip.twelve99.net (62.115.12 0.74) 8.470 ms
10 * * ldn-b11-link.ip.twelve99.net (62.115.141.247) 7.575 ms
11 ae-0.r21.nwrknj03.us.bb.gin.ntt.net (129.250.6.17) 77.161 ms ae-4.r24.sttlwa01.us.bb.gin.ntt.net (129.250.6.177) 137.269 ms ae-0.r21.nwrknj03.us.bb.gin.ntt.net (129.250.6.17) 77.095 ms
12 dns.adguard.com (94.140.15.15) 7.610 ms ae-13.r30.tokyjp05.jp.bb.gin.ntt.net (129.250.4.143) 223.855 ms 222.26 6 ms
```

**Comment by ameshkov** [comment]
> If I ping dns.adguard.com I get an average ping of ~7.5 ms but if I ping 94.140.15.15 I get an average ping of ~250 ms. For 94.140.14.14 I get an average ping of ~7.5ms.

Tbh, this is the first time I am seeing such an issue. Both subnets should've been routed similarly, but it seems in one case you're routed to our London server, and in the other case you're routed to Tokyo.

**Comment by Altycoder** [comment]
@ameshkov thanks, yes Tokyo is a fair distance from Manchester!

Is this routing something you can fix?  Why does dns.adguard.com resolve to the far slower of the two possible IP addresses?  The benefit of having a primary and secondary IP address is to always be routed to the fastest, or is it more of a failover?

**Comment by ameshkov** [comment]
@Altycoder it resolves to both IP addresses, and it's up to the client to choose which one of them to use. Usually, clients use them in a random order.

**Comment by Altycoder** [comment]
So there's nothing we can do about this then?

**Comment by ameshkov** [comment]
Well, there're two options.

1. We'll check our configuration and see if we properly announce all the routes.
2. But if the configuration is okay, the problem is on the ISP side.

**Comment by ameshkov** [comment]
@Altycoder could you please also show traceroute to 14.14?

**Comment by Altycoder** [comment]
traceroute to 94.140.14.14 (94.140.14.14), 30 hops max, 60 byte packets
 1  _gateway (192.168.1.1)  0.313 ms  0.275 ms  0.220 ms
 2  * * *
 3  * * *
 4  31.55.185.180 (31.55.185.180)  6.327 ms  6.571 ms 31.55.185.184 (31.55.185.184)  7.511 ms
 5  core1-hu0-12-0-3.colindale.ukcore.bt.net (195.99.127.216)  6.364 ms core1-hu0-8-0-1.colindale.ukcore.bt.net (195.99.127.144)  7.696 ms core1-hu0-17-0-5.colindale.ukcore.bt.net (195.99.127.150)  7.528 ms
 6  core5-hu0-4-0-15.faraday.ukcore.bt.net (109.159.252.136)  8.464 ms core5-hu0-3-0-15.faraday.ukcore.bt.net (109.159.252.132)  8.153 ms peer7-et-3-1-7.telehouse.ukcore.bt.net (109.159.252.172)  7.395 ms
 7  166-49-209-132.gia.bt.net (166.49.209.132)  8.559 ms 166-49-214-194.gia.bt.net (166.49.214.194)  7.635 ms 166-49-209-132.gia.bt.net (166.49.209.132)  7.928 ms
 8  * * ldn-b3-link.ip.twelve99.net (213.248.71.146)  8.346 ms
 9  ldn-bb4-link.ip.twelve99.net (62.115.122.180)  8.315 ms  8.949 ms ldn-bb1-link.ip.twelve99.net (62.115.120.74)  7.965 ms
10  ldn-b11-link.ip.twelve99.net (62.115.138.169)  7.330 ms * ldn-b11-link.ip.twelve99.net (62.115.141.247)  7.912 ms
11  datacamp-svc073886-ic362025.c.telia.net (62.115.187.2)  8.683 ms  7.567 ms *
12  dns.adguard.com (94.140.14.14)  7.343 ms  7.494 ms  7.217 ms

**Comment by Altycoder** [comment]
and for completeness are your ipv6 servers being routed correctly as well?

`traceroute to 2a10:50c0::ad1:ff (2a10:50c0::ad1:ff), 30 hops max, 80 byte packets
 1  2a00:23c4:6011:15aa:2e0:67ff:fe26:4971 (2a00:23c4:6011:15aa:2e0:67ff:fe26:4971)  0.344 ms  0.316 ms  0.373 ms
 2  * * *
 3  * * *
 4  * * *
 5  2a00:2380:3013:8000::34 (2a00:2380:3013:8000::34)  8.033 ms * 2a00:2380:3013:8000::18 (2a00:2380:3013:8000::18)  8.130 ms
 6  * peer7-et3-1-7.telehouse.ukcore.bt.net (2a00:2380:13::ad)  18.552 ms peer7-et4-0-4.telehouse.ukcore.bt.net (2a00:2380:13::d5)  8.739 ms
 7  2a00:2000:2066::7c (2a00:2000:2066::7c)  8.661 ms  7.975 ms 2a00:2000:2073:2::30 (2a00:2000:2073:2::30)  22.119 ms
 8  * * *
 9  ae-7.r20.londen12.uk.bb.gin.ntt.net (2001:728:0:2000::5d)  8.720 ms ldn-bb1-v6.ip.twelve99.net (2001:2034:1:7a::1)  7.480 ms ae-7.r20.londen12.uk.bb.gin.ntt.net (2001:728:0:2000::5d)  9.541 ms
10  ae-7.r20.nwrknj03.us.bb.gin.ntt.net (2001:418:0:2000::252)  76.548 ms  76.019 ms *
11  ae-4.r24.sttlwa01.us.bb.gin.ntt.net (2001:418:0:2000::332)  135.833 ms  135.924 ms ae-0.r21.nwrknj03.us.bb.gin.ntt.net (2001:418:0:2000::1c6)  82.681 ms
12  dns.adguard.com (2a10:50c0::ad1:ff)  9.154 ms  8.832 ms  8.710 ms
`

`traceroute to 2a10:50c0::ad2:ff (2a10:50c0::ad2:ff), 30 hops max, 80 byte packets
 1  2a00:23c4:6011:15aa:2e0:67ff:fe26:4971 (2a00:23c4:6011:15aa:2e0:67ff:fe26:4971)  0.342 ms  0.310 ms  0.324 ms
 2  * * *
 3  * * *
 4  2a00:2302::1103:100:37 (2a00:2302::1103:100:37)  7.949 ms  8.030 ms  8.222 ms
 5  2a00:2380:3013:8000::38 (2a00:2380:3013:8000::38)  7.996 ms * *
 6  * peer7-et4-1-4.telehouse.ukcore.bt.net (2a00:2380:13::d7)  7.426 ms *
 7  2a00:2000:2066::7c (2a00:2000:2066::7c)  7.400 ms  7.107 ms 2a00:2000:2073:2::30 (2a00:2000:2073:2::30)  7.993 ms
 8  * ae-23.r04.londen05.uk.bb.gin.ntt.net (2001:728:0:5000::1702)  8.613 ms *
 9  ldn-bb4-v6.ip.twelve99.net (2001:2034:1:7b::1)  10.145 ms ae-7.r20.londen12.uk.bb.gin.ntt.net (2001:728:0:2000::5d)  23.058 ms ldn-bb1-v6.ip.twelve99.net (2001:2034:1:7a::1)  7.307 ms
10  ldn-b11-v6.ip.twelve99.net (2001:2034:0:181::1)  7.292 ms *  8.137 ms
11  datacamp-svc073886-ic362025.c.telia.net (2001:2000:3080:579::2)  7.239 ms * datacamp-ic357609-ldn-b7.ip.twelve99-cust.net (2001:2000:3080:21de::2)  7.386 ms
12  * dns.adguard.com (2a10:50c0::ad2:ff)  6.818 ms ae-3.r22.chcgil09.us.bb.gin.ntt.net (2001:418:0:2000::75)  97.175 ms
`

**Comment by ameshkov** [comment]
@Altycoder we've made some changes to the routing on our side. Could you please check it again in a couple of minutes?

**Comment by Altycoder** [comment]
sure no problem

**Comment by Altycoder** [comment]
```traceroute to 94.140.14.14 (94.140.14.14), 30 hops max, 60 byte packets
 1  _gateway (192.168.1.1)  0.317 ms  0.239 ms  0.352 ms
 2  * * *
 3  * * *
 4  31.55.185.180 (31.55.185.180)  8.328 ms 31.55.185.184 (31.55.185.184)  8.136 ms 31.55.185.180 (31.55.185.180)  7.680 ms
 5  core1-hu0-15-0-7.colindale.ukcore.bt.net (213.121.192.10)  8.296 ms core2-hu0-2-0-5.colindale.ukcore.bt.net (195.99.127.116)  7.521 ms core1-hu0-6-0-6.colindale.ukcore.bt.net (213.121.192.0)  8.050 ms
 6  core5-hu0-3-0-15.faraday.ukcore.bt.net (109.159.252.132)  8.540 ms core5-hu0-7-0-15.faraday.ukcore.bt.net (195.99.127.36)  8.576 ms peer7-et-0-1-4.telehouse.ukcore.bt.net (109.159.252.94)  7.685 ms
 7  166-49-209-132.gia.bt.net (166.49.209.132)  7.449 ms  7.276 ms 166-49-214-194.gia.bt.net (166.49.214.194)  6.978 ms
 8  * 166-49-209-131.gia.bt.net (166.49.209.131)  9.140 ms  8.976 ms
 9  ldn-bb1-link.ip.twelve99.net (62.115.120.74)  8.099 ms  8.712 ms  8.362 ms
10  be2572.ccr21.lon02.atlas.cogentco.com (154.54.61.254)  8.365 ms ldn-b11-link.ip.twelve99.net (62.115.138.169)  8.021 ms be2572.ccr21.lon02.atlas.cogentco.com (154.54.61.254)  9.093 ms
11  149.6.148.194 (149.6.148.194)  8.784 ms datacamp-ic357609-ldn-b1.ip.twelve99-cust.net (195.12.254.250)  7.451 ms  7.797 ms
12  dns.adguard.com (94.140.14.14)  8.073 ms  7.704 ms  7.732 ms
```

```traceroute to 94.140.15.15 (94.140.15.15), 30 hops max, 60 byte packets
 1  _gateway (192.168.1.1)  0.364 ms  0.340 ms  0.293 ms
 2  * * *
 3  * * *
 4  31.55.185.176 (31.55.185.176)  7.792 ms 31.55.185.188 (31.55.185.188)  7.906 ms  7.108 ms
 5  core1-hu0-8-0-1.colindale.ukcore.bt.net (195.99.127.144)  7.929 ms core2-hu0-2-0-5.colindale.ukcore.bt.net (195.99.127.116)  7.372 ms 213.121.192.138 (213.121.192.138)  7.648 ms
 6  core5-hu0-4-0-15.faraday.ukcore.bt.net (109.159.252.136)  8.438 ms peer7-et-7-0-4.telehouse.ukcore.bt.net (62.172.103.164)  7.131 ms peer7-et-4-1-4.telehouse.ukcore.bt.net (194.72.16.140)  7.291 ms
 7  166-49-209-132.gia.bt.net (166.49.209.132)  7.484 ms  7.940 ms 166-49-214-194.gia.bt.net (166.49.214.194)  24.084 ms
 8  166-49-209-131.gia.bt.net (166.49.209.131)  9.436 ms  9.522 ms  9.363 ms
 9  be3487.ccr41.lon13.atlas.cogentco.com (154.54.60.5)  9.487 ms ldn-bb4-link.ip.twelve99.net (62.115.122.180)  7.911 ms be3487.ccr41.lon13.atlas.cogentco.com (154.54.60.5)  9.291 ms
10  ldn-b11-link.ip.twelve99.net (62.115.138.169)  6.960 ms be2572.ccr21.lon02.atlas.cogentco.com (154.54.61.254)  8.651 ms  8.696 ms
11  datacamp-ic357609-ldn-b1.ip.twelve99-cust.net (195.12.254.250)  6.591 ms  6.877 ms datacamp.demarc.cogentco.com (149.6.149.234)  7.480 ms
12  dns.adguard.com (94.140.15.15)  7.325 ms  8.367 ms  7.894 ms
```

```traceroute to 2a10:50c0::ad1:ff (2a10:50c0::ad1:ff), 30 hops max, 80 byte packets
 1  <redacted>  0.375 ms  0.354 ms  0.344 ms
 2  * * *
 3  * 2a00:2302::1103:100:36 (2a00:2302::1103:100:36)  7.344 ms  7.204 ms
 4  * * *
 5  * 2a00:2380:3013:8000::3e (2a00:2380:3013:8000::3e)  8.400 ms 2a00:2380:3013:9000::30 (2a00:2380:3013:9000::30)  7.768 ms
 6  peer7-et3-1-4.telehouse.ukcore.bt.net (2a00:2380:13::a9)  8.217 ms peer7-et3-0-4.telehouse.ukcore.bt.net (2a00:2380:13::a1)  19.060 ms peer7-et3-1-4.telehouse.ukcore.bt.net (2a00:2380:13::a9)  19.312 ms
 7  2a00:2000:2073:2::30 (2a00:2000:2073:2::30)  7.694 ms  7.755 ms  7.644 ms
 8  * * *
 9  ldn-bb4-v6.ip.twelve99.net (2001:2034:1:7b::1)  25.615 ms  25.460 ms  25.587 ms
10  ldn-b11-v6.ip.twelve99.net (2001:2034:0:181::1)  7.543 ms  7.496 ms  8.450 ms
11  datacamp-svc073886-ic362025.c.telia.net (2001:2000:3080:579::2)  7.903 ms datacamp-ic357609-ldn-b7.ip.twelve99-cust.net (2001:2000:3080:21de::2)  7.303 ms datacamp-svc073886-ic362025.c.telia.net (2001:2000:3080:579::2)  7.168 ms
12  dns.adguard.com (2a10:50c0::ad1:ff)  7.763 ms  8.111 ms  7.674 ms
```

```traceroute to 2a10:50c0::ad2:ff (2a10:50c0::ad2:ff), 30 hops max, 80 byte packets
 1  <redacted>
 2  * * *
 3  * * *
 4  * * 2a00:2302::1103:100:37 (2a00:2302::1103:100:37)  7.235 ms
 5  2a00:2380:3013:8000::3e (2a00:2380:3013:8000::3e)  7.182 ms * 2a00:2380:3013:8000::2c (2a00:2380:3013:8000::2c)  8.265 ms
 6  peer7-et3-1-4.telehouse.ukcore.bt.net (2a00:2380:13::a9)  7.705 ms peer7-et0-1-4.telehouse.ukcore.bt.net (2a00:2380:13::7d)  7.937 ms peer7-et3-1-4.telehouse.ukcore.bt.net (2a00:2380:13::a9)  7.198 ms
 7  2a00:2000:2073:2::30 (2a00:2000:2073:2::30)  8.041 ms  7.763 ms  8.618 ms
 8  ldn-b3-link.ip.twelve99.net (2001:2000:3080:1c99::1)  8.722 ms * *
 9  ldn-bb4-v6.ip.twelve99.net (2001:2034:1:7b::1)  7.920 ms  13.511 ms ldn-bb1-v6.ip.twelve99.net (2001:2034:1:7a::1)  7.801 ms
10  ldn-b11-v6.ip.twelve99.net (2001:2034:0:181::1)  7.722 ms  7.535 ms  7.968 ms
11  datacamp-ic357609-ldn-b7.ip.twelve99-cust.net (2001:2000:3080:21de::2)  7.070 ms datacamp-svc073886-ic362025.c.telia.net (2001:2000:3080:579::2)  7.506 ms datacamp-ic357609-ldn-b7.ip.twelve99-cust.net (2001:2000:3080:21de::2)  7.426 ms
12  dns.adguard.com (2a10:50c0::ad2:ff)  7.479 ms  7.297 ms  8.295 ms
```

**Comment by Altycoder** [comment]
Looking good :-)
![20211102_095856](https://user-images.githubusercontent.com/1990152/139825974-903cae48-d581-41be-887c-6f08b1b866da.jpg)

**Comment by ameshkov** [comment]
Great! Hopefully, our changes won't negatively affect other people.

Thank you for your help!

**Comment by Altycoder** [comment]
No problem, thanks for the very quick response.
