### ISSUE TITLE
Cannot use Adguard DNS

### ISSUE THREAD

**Issue by LaxusiC** [AdguardTeam/AdguardDNS#205]
Been using it nearly 1 month but today i can't connect to the internet because of AG DNS Family. What happen?

I'm using iOS, both ipv4 and ipv6 make me cannot connect to the internet

**Comment by nkartyshov** [comment]
Sorry, we had a problem with server on Singapore. Now this problem is fix.
Can you check connection to the internet again?

**Comment by ForkedLightning** [comment]
176.103.130.130 is still not responding to normal and dnscrypt requests.
176.103.130.131 is working normally. Does it have dnscrypt?

**Comment by nkartyshov** [comment]
@ForkedLightning Yes, both servers have dnscrypt.

Can you check connection to the internet again?

**Comment by ForkedLightning** [comment]
@nkartyshov Normal requests work but dnscrypt is still broken on it.

**Comment by ForkedLightning** [comment]
Dnscrypt for adguard-dns (176.103.130.130) started working as of a minute ago. Thank you for fixing it!

**Comment by vozersky** [comment]
fiexed :)
