### ISSUE TITLE
Page takes 5 min to Load

### ISSUE THREAD

**Issue by bravucod** [AdguardTeam/AdguardDNS#206]
### Steps to reproduce

1.go to fox13now.com
2.Open a link that contains a video
3.
4.

### Expected behavior

It should load Instantly!
### Actual behavior

IT takes 5 min to load the page

<details><summary>Screenshot:</summary>

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| (e.g. Default, 176.103.130.130)
| How did you setup DNS configuration:| (System/DNSCrypt app/Router)
| Device model:| (e.g. Google Pixel)
| Operating system and version:| (e.g. Android 7.1.2)

**Comment by vozersky** [comment]
looks like the issue is not relevant anymore, can't rep

**Comment by bravucod** [comment]
Here are some examples the pages that have videos on it take a long time to Load
http://fox13now.com/2017/12/07/tooele-teen-recounts-frightening-encounter-after-attempted-abduction/

http://fox13now.com/2017/12/07/rocky-mountain-raceways-to-close-after-2018-season/

**Comment by bravucod** [comment]
The problem still persist. Every link that contains a vide on that domain
takes a long time to load.



http://fox13now.com/2017/12/07/rocky-mountain-raceways-to-
close-after-2018-season/







*From:* Vladimir Ozersky [mailto:notifications@github.com]
*Sent:* Wednesday, December 6, 2017 10:39 AM
*To:* AdguardTeam/AdguardDNS <AdguardDNS@noreply.github.com>
*Cc:* bravucod <bravo.d@live.com>; Author <author@noreply.github.com>
*Subject:* Re: [AdguardTeam/AdguardDNS] Page takes 5 min to Load (#206)



looks like the issue is not relevant anymore, can't rep

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAdguardTeam%2FAdguardDNS%2Fissues%2F206%23issuecomment-349717405&data=02%7C01%7C%7C1170cc07eac84ed3ec5e08d53cd03d4b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636481787430301992&sdata=aKErLrZYmILrZ9rmlbkwEjj2OzaZfOTIMxK7VAiv%2FBA%3D&reserved=0>,
or mute the thread
<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAgB2OXmw3QRhdEgiC8bP-Olykbwd7qBFks5s9tE0gaJpZM4Qaq5o&data=02%7C01%7C%7C1170cc07eac84ed3ec5e08d53cd03d4b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636481787430301992&sdata=SjJx3kdFqvaiZn3pMC25kH%2FiVfZufGGlsmTEw16EsFk%3D&reserved=0>
.

**Comment by bravucod** [comment]
Here is another link. It does take a long time to load in any video made by
the company

http://fox13now.com/2017/12/10/unified-police-responding-to-taylorsville-shooting/

Daniel Bravo
(801) 860-8605

**Comment by zebrum** [comment]
also can't reproduce.
tell us more about your device and it's configuration

**Comment by ameshkov** [comment]
Actually, we'd better take a look at the HAR file:
https://support.zendesk.com/hc/en-us/articles/204410413-Generating-a-HAR-file-for-troubleshooting
