### ISSUE TITLE
Is it possible to add ads server domain to AGDNS?

### ISSUE THREAD

**Issue by LaxusiC** [AdguardTeam/AdguardDNS#208]
Title

**Comment by vozersky** [comment]
It is.
Which one?

**Comment by LaxusiC** [comment]
@vozersky 

heyzap.com
mobusi.com
umengcloud.com
iwadserver.com
ocio.leadzutw.com

**Comment by vozersky** [comment]
@LaxusiC unfortunately we can't just add a list of domains, it can, moreover, break some pages. Need an example of page with ads, and it's better to use this repo: https://github.com/AdguardTeam/AdguardFilters/issues
