### ISSUE TITLE
Azure Portal not working properly when using ADGuard DNS servers

### ISSUE THREAD

**Issue by flavio-neves** [AdguardTeam/AdGuardDNS#209]
Hi, 

Whenever I try to use Log analytics or application insights, both use specific URLs outside azure domain, I got a timeout error.

More details here:

![image](https://user-images.githubusercontent.com/35963484/147264276-1287ddc6-a3ac-43fc-bd3f-e5621adb1cc8.png)

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdGuardSDNSFilter #860](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/860) via [**ZenHub**](https://www.zenhub.com/)
