### ISSUE TITLE
ios ipv6 issues

### ISSUE THREAD

**Issue by mikeoleary7528** [AdguardTeam/AdguardDNS#209]
No ipv6 filtering on ios, connects to the network but does not block ads on iPhone X 11.2 beta 4.  Regular ipV4 networks work and yes I have ipv6 connection.  I pass that google link that says I am ready.

**Comment by ameshkov** [comment]
Do you mean IPv6 only? What cellular provider do you have?

**Comment by mikeoleary7528** [comment]
Yes, I’m on Verizon and have tried the port method also still no luck. I’m guessing has to do with their DNS hijacking?

**Comment by ameshkov** [comment]
Might be the case indeed. Let's wait for the DNSCrypt support in AG Pro then.
