### ISSUE TITLE
DNSCrypt timeout problems (with UDP and TCP)

### ISSUE THREAD

**Issue by ForkedLightning** [AdguardTeam/AdguardDNS#210]
Follow up to: https://github.com/AdguardTeam/AdguardDNS/issues/205

**Normal DNS:**
Primary server does not respond sometimes.
No problems with secondary server.

**DNSCrypt:**
Since the server had problems two weeks ago, DNSCrypt is mostly unusable. Most requests time out, both on UDP and TCP.

```
11/23/17 04:41:24 [NOTICE] Starting dnscrypt-proxy 1.9.5
11/23/17 04:41:24 [INFO] Generating a new session key pair
11/23/17 04:41:24 [INFO] Done
11/23/17 04:41:39 [ERROR] Unable to retrieve server certificates
11/23/17 04:41:40 [INFO] Refetching server certificates
11/23/17 04:41:40 [INFO] Server certificate with serial #1511299801 received
11/23/17 04:41:40 [INFO] This certificate is valid
11/23/17 04:41:40 [INFO] The key rotation period for this server may exceed the recommended value. This is bad for forward secrecy.
11/23/17 04:41:40 [INFO] Server key fingerprint is **************
11/23/17 04:41:40 [NOTICE] Proxying from 0.0.0.0:53 to 176.103.130.130:5443
11/23/17 04:41:51 [DEBUG] resolver timeout (UDP)
11/23/17 04:41:53 [DEBUG] resolver timeout (UDP)
11/23/17 04:41:56 [DEBUG] resolver timeout (UDP)
11/23/17 04:41:58 [DEBUG] resolver timeout (UDP)
11/23/17 04:42:03 [DEBUG] resolver timeout (UDP)
11/23/17 04:42:05 [DEBUG] resolver timeout (UDP)
```

**Comment by ameshkov** [comment]
@ForkedLightning could you plz show tracert to 176.103.130.130 ?

**Comment by ForkedLightning** [comment]
Tested on 2017/11/23 at 19:15:36.16 

Tracing route to 176-103-130-130.flops.ru [176.103.130.130]
over a maximum of 30 hops:

  1    <1 ms    <1 ms    <1 ms  192.168.1.1 
  2    41 ms    41 ms    40 ms  118.101.110.254 
  3    49 ms    48 ms    49 ms  10.55.74.33 
  4    48 ms    50 ms    48 ms  10.55.39.150 
  5    44 ms    45 ms    47 ms  10.55.48.58 
  6    50 ms    46 ms    45 ms  10.55.41.117 
  7    57 ms    58 ms    48 ms  10.55.50.58 
  8    44 ms    47 ms    47 ms  10.55.32.162 
  9    51 ms    51 ms    51 ms  63-218-165-181.static.pccwglobal.net [63.218.165.181] 
 10    54 ms    54 ms    55 ms  HundredGE0-3-0-0.br03.sin02.pccwbtn.net [63.223.34.134] 
 11     *        *       57 ms  63-218-229-130.static.pccwglobal.net [63.218.229.130] 
 12     *       92 ms    77 ms  vl808-ds1-j2-r1252.sgp1.choopa.net [45.32.97.146] 
 13     *        *        *     Request timed out.
 14    69 ms    69 ms    57 ms  176-103-130-130.flops.ru [176.103.130.130] 

Trace complete.

**Comment by ameshkov** [comment]
Singapore server, got it.

@nkartyshov plz check what's wrong with the primary server there.

**Comment by ForkedLightning** [comment]
My ISP may be suspected of dropping the dnscrypt packets.
Please tell me if you need me to test anything more.

**Comment by nkartyshov** [comment]
@ForkedLightning Fixed. Please, check connection to internet with DNSCrypt.

**Comment by ForkedLightning** [comment]
@nkartyshov 
It's "kinda working". I have to restart the client until it works.
The log doesn't say anything useful except " [DEBUG] resolver timeout " when it fails. The two OpenNIC servers on the list have stopped working for me in the same way after use for a while. Very strange behaviour because Cisco OpenDNS using DNSCrypt works without problems. I'll chalk this up to ISP being a *********.

Very sorry for the trouble caused and thanks again!
