### ISSUE TITLE
Bild.de not working with DNS Family protections

### ISSUE THREAD

**Issue by jonathanmmm** [AdguardTeam/AdguardDNS#212]
Hi Adguard Team,

Bild.de is not accessible with Family Protection DNS Servers.
I tried only Ipv4 (Ipv6 = no internet connection in my test).

With the normal Adguard DNS nothing gets blocked.

http://cdn1.smartadserver.com/ is not blocked with Adguard DNS "Normal" but with

Adguard Family Protection it says there is content not for kids or smth. similar (Redirection to Adguard page)

**Comment by vozersky** [comment]
@jonathanmmm hi!
We are investigating the issue with ipv6 servers, thanks a lot!
Regarding Bild.de, can't reproduce on my side, is it still blocked for you?

**Comment by vozersky** [comment]
@jonathanmmm well, ipv6 servers seems to be working fine, maybe you didn't enable ipv6 in the network interface

**Comment by vozersky** [comment]
I've excluded `cdn1.smartadserver.com`from Family Protection list
