### ISSUE TITLE
Adguard Family DNS Bild.de again not working

### ISSUE THREAD

**Issue by jonathanmmm** [AdguardTeam/AdguardDNS#213]
Hello,

Bild.de is still not working and showing adblocking in family adguard dns

ww251.smartadserver.com is blocked, maybe that`s another server.

Please can you check if there is any difference in adguard family and normal adguard dns regarding Bild.de?

Because with the normal dns all is working fine.

**Comment by vozersky** [comment]
Issue moved to [AdguardTeam/AdguardFilters #8392](https://github.com/AdguardTeam/AdguardFilters/issues/8392) via [**ZenHub**](https://www.zenhub.com/)
