### ISSUE TITLE
AdGuard kinda slow.

### ISSUE THREAD

**Issue by SwiftyPop** [AdguardTeam/AdGuardDNS#213]
When I use the DNS, I frequently get DNS PROBE POSIBLE
![Discord_5NP4081f8b](https://user-images.githubusercontent.com/90952326/148040032-65aa1ad3-fd78-42e6-88e1-a6ffaa24275e.png)
 and slow browsing experience in some sites 
![brave_d4EbuQ6fVy](https://user-images.githubusercontent.com/90952326/148040687-10787807-1399-43d6-8d77-b51b89771247.png)

 I do test with this site: https://dns.adguard.com/info.txt and got `dns2-dp-sg-1`. It seem like the server located at Singapore,which is pretty close to me so what is the slowness I got?

**Comment by ameshkov** [comment]
How exactly have you configured AdGuard DNS?

Did you configure it system-wide or in Brave browser only?

**Comment by SwiftyPop** [comment]
@ameshkov system-wide.

**Comment by ameshkov** [comment]
Does the same issue happen if you try a different browser?

This DNS_PROBE_POSSIBLE error seems to be specific to Brave browser.

**Comment by SwiftyPop** [comment]
Sorry for the confusion; I recently tried the AdGuard DNS again and no longer receive the error, and the site loads quickly. I'm curious if AdGuard DNS is affected by undersea cable issues. My issue started when my (ISP) had a nationwide submarine cable failure, which I was unaware of at the time I reported the problem.
