### ISSUE TITLE
AdGuard encrypted DNS via macOS/iOS Profile doesn't work (macOS 12.1)

### ISSUE THREAD

**Issue by vordenken** [AdguardTeam/AdGuardDNS#214]
On my MacBook Air m1 (macOS 12.1) I have installed the AdGuard profile but it appears to not be working even after a reboot. The AdGuard test page and other dns tools show that my networks dns server is used instead.
<img width="1167" alt="Bildschirmfoto 2022-01-14 um 20 00 44" src="https://user-images.githubusercontent.com/62395860/149571843-d6039401-1a74-4995-a510-425f6b65be41.png">

**Comment by ameshkov** [comment]
Questions:
1. Do you have a custom DNS configured in your browser?
2. Do you have any VPN app running at the same time?

**Comment by vordenken** [comment]
Hi Andrey,

1. No I don't. Tried it with brave and safari.
2. No VPN App running but LittleSnitch - maybe that is the problem?

**Comment by ameshkov** [comment]
2. Yes, most likely this is the case. LittleSnitch runs a network extension and macOS considers this a "VPN" connection for some reason.
