### ISSUE TITLE
https://www.tradepub.com/ is blocked

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardDNS#214]
With AdGuard Family protection DNS:

![image](https://uploads.adguard.com/sva5k.png)

Without:

![image](https://user-images.githubusercontent.com/15856304/34115350-1519919a-e41e-11e7-975c-6ee8896dea92.png)

**Comment by vozersky** [comment]
Issue moved to [AdguardTeam/AdguardFilters #8683](https://github.com/AdguardTeam/AdguardFilters/issues/8683) via [**ZenHub**](https://www.zenhub.com/)
