### ISSUE TITLE
Website false positive ilto.run

### ISSUE THREAD

**Issue by SelaO** [AdguardTeam/AdGuardDNS#215]
https://ilto.run is being used by a very popular shipping company in Israel to send a link to customers to pick a pickup location for their packages.
Please remove it from the blacklist.

I'm using dns.adguard.com and it's blocked there.

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdGuardSDNSFilter #877](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/877) via [**ZenHub**](https://www.zenhub.com/)

**Comment by SelaO** [comment]
@ameshkov so Alex brought me back here: https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/877#issuecomment-1022594034

**Comment by ameshkov** [comment]
Well, it seems their nameservers serve different results depending on the resolver location. Does not look normal to me, tbh.

Probably, it should be reported to them, not to us.

**Comment by SelaO** [comment]
Is it possible to simply remove the blocking on ilto.run? 
They're not a software company and their support isn't helpful on those matters at all. 

It's not spam or malware so there's no reason to block it...

**Comment by ameshkov** [comment]
@SelaO there's no blocking. Their nameserver behaves incorrectly which is why the domain cannot be resolved from the countries where AdGuard DNS servers are located.
