### ISSUE TITLE
Reject Apple Revokes

### ISSUE THREAD

**Issue by LegitSoulja** [AdguardTeam/AdguardDNS#217]
This simple addition, would turn adguard premium. Block this incoming/outgoing traffic,

**oscp.apple.com**

**Comment by ameshkov** [comment]
Guys, that'd be illegal

**Comment by LegitSoulja** [comment]
I don’t think this would be illegal but ok. I managed my own solution, avoiding conflicts with adguard.

**Comment by ameshkov** [comment]
For instance, AdGuard Pro allows you to have your own blacklist, that should be your decision whether it is blocked or not.
