### ISSUE TITLE
paypal.com 2FA issue

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardDNS#218]
@adguard-bot commented on [Sat Jan 22 2022](https://github.com/AdguardTeam/AdguardFilters/issues/107853)

### Issue URL (Incorrect Blocking)
 [https://paypal.com](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fpaypal.com)
### Comment
Username: @jeremygaither
> I receive this error when default filters and adguard DNS are used. I usually have to pass a captcha and PayPal begins to fail after trying to authenticate. The issue persists for a period (not sure duration). If I connect over VPN and turn off filter and DNS protection, PayPal works as expected. This is a recent change. I am using mobile Safari on iOS 15.2.1. I have also turned off Safari IP address hiding. Cross-site tracking doesn't seem to matter.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/ZkuoEI6.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/113CdLs.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard/AdGuard Pro for iOS v4.3.1
Browser: | Safari
DNS filtering: | server: `AdGuard Pro vpn dns`<br>
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base, <br/>AdGuard Mobile Ads, <br/>EasyList<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection, <br/>EasyPrivacy<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances, <br/>Web Annoyances Ultralist, <br/>Adblock Warning Removal List, <br/>I don't care about cookies<br/><br/><b>Security:</b><br/>NoCoin Filter List

---

@jeremygaither commented on [Sat Jan 22 2022](https://github.com/AdguardTeam/AdguardFilters/issues/107853#issuecomment-1019361462)

I believe AdGuard blocking is triggering some kind of web app firewall rule at PayPal that is new. I haven't sniffed the connections it makes now. I've also added `paypal.com` and `paypalobjects.com` to DNS filtering and browser filtering rules (to disable filtering) and disabled content blocking in Safari for `paypal.com`. Deleting website data in Safari doesn't help correct the issue (which is what their HelpDesk told me).

---

@Alex-302 commented on [Tue Jan 25 2022](https://github.com/AdguardTeam/AdguardFilters/issues/107853#issuecomment-1021100340)

@jeremygaither Hi. I can login and send money with enabled DNS. 
Please describe steps, when PayPal failed.

---

@jeremygaither commented on [Wed Feb 02 2022](https://github.com/AdguardTeam/AdguardFilters/issues/107853#issuecomment-1028053753)

Steps that allow me to repro the issue:

- Browse to https://paypal.com in a private window in iOS Safari (or delete website data for `paypal.com` and `paypalobjects.com`)
- Click the link to log in
- Use an account with 2FA enabled
- Enter the username and password, then click the button to log in
- The 2FA screen is presented 
- Enter the proper 2FA code and click to validate
- The first indication of a problem is 2FA rejecting a valid code 2 or more times
- Next, PayPal displays a 503 error:

```
Error 403 Forbidden

Forbidden

Guru Mediation:

Details: cache-dal21258-DAL 1643815157 3783935379

Varnish cache server
```
The "Details" ID changes on every attempt.

There is an older discussion on Apple support regarding similar behavior, where the accepted solution was to use Google DNS or Cloudflare DNS. That defeats the point of using AdGuard DNS filtering. That discussion is here: <https://discussions.apple.com/thread/252866903>.

**Comment by ammnt** [comment]
@Alex-302, try to unblock `t.paypal.com` host. FYI:
https://github.com/StevenBlack/hosts/issues/1876

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdguardFilters/commit/89e957dcb072c14f8ebbd8489aed49e06f9df93d

**Comment by homewirehub** [comment]
I'm running into the same issue. While I have DNS filtering activated no 2FA code is requested. When I deactivate DNS filtering in AdGuard Pro on iOS is working again.
