### ISSUE TITLE
Indonesia (Telkomsel) routed to Germany instead of the closest PoP

### ISSUE THREAD

**Issue by leonicholasthe3** [AdguardTeam/AdGuardDNS#219]
Hello, I'm user from Indonesia who use Telkomsel (AS23693 PT. Telekomunikasi Selular) as my ISP and unfortunately it's not connect into nearest server (Singapore) but far away into Germany

is this problems can be fix? 
![Screenshot_20220224-185318_Samsung Internet](https://user-images.githubusercontent.com/87444835/155519473-35e91eda-5924-4395-b123-9cba5fcdb028.jpg)

**Comment by MarcoHoKongMa** [comment]
I have this issue as well. Before Feb 2022, I was able to connect to Adguard's Chicago server (2nd closest server, my closest server is Toronto). However, after the start of Feb 2022, I am constantly getting connected to Adguard's Frankfurt server in Germany. I live in Oshawa, Ontario (1-hour drive from Toronto) and my ISP is Bell Canada. I have tried with other DNS services like Cloudflare (1.1.1.1) and I was able to connect to their Chicago server at low latency. I have tried to address this issue through technical support at Adguard more than a week ago, but they have yet to reply.
![image](https://user-images.githubusercontent.com/60004908/156244056-a819e785-43a5-4220-8653-e5b11aff991e.png)
![image](https://user-images.githubusercontent.com/60004908/156244109-7c06e148-029e-4957-b297-c54754ad4790.png)
My Location: Oshawa, ON, Canada (A 1-hour drive away from downtown Toronto)
ISP: Bell Canada

![image](https://user-images.githubusercontent.com/60004908/156244149-3570ef07-eb14-45cd-ae96-18f87b51e2e9.png)
![image](https://user-images.githubusercontent.com/60004908/156244167-ef60007d-07dc-40fd-80da-f8065a8342cc.png)

**Comment by MarcoProlo** [comment]
I have this issue as well. Before Feb 2022, I was able to connect to Adguard's Chicago server (2nd closest server, my closest server is Toronto). However, after the start of Feb 2022, I am constantly getting connected to Adguard's Frankfurt server in Germany. I live in Oshawa, Ontario (1-hour drive from Toronto) and my ISP is Bell Canada. I have tried with other DNS services like Cloudflare (1.1.1.1) and I was able to connect to their Chicago server at low latency. I have tried to address this issue through technical support at Adguard more than a week ago, but they have yet to reply.

![image](https://user-images.githubusercontent.com/60004908/156244056-a819e785-43a5-4220-8653-e5b11aff991e.png)
![image](https://user-images.githubusercontent.com/60004908/156244109-7c06e148-029e-4957-b297-c54754ad4790.png)
My Location: Oshawa, ON, Canada (A 1-hour drive away from downtown Toronto)
ISP: Bell Canada

![image](https://user-images.githubusercontent.com/60004908/156244149-3570ef07-eb14-45cd-ae96-18f87b51e2e9.png)
![image](https://user-images.githubusercontent.com/60004908/156244167-ef60007d-07dc-40fd-80da-f8065a8342cc.png)

**Comment by leonicholasthe3** [comment]
Update 02 July 2022 -  I'm **Telkomsel** sim card user (**AS23693 PT. Telekomunikasi Selular**) as my ISP and **unfortunately still don't connect** into _**nearest server (Singapore)**_ but far away into _**Germany**_ 
![Web capture_2-7-2022_12272_browserleaks com](https://user-images.githubusercontent.com/87444835/176987948-fd8513f7-917f-46ab-b3dc-a46bbbca8fc7.jpeg)
![traceroute 02 july 2022](https://user-images.githubusercontent.com/87444835/176988091-af7666e6-5fc5-4753-94de-0759d3f319a8.png)

**Comment by ameshkov** [comment]
Servers in Singapore will soon be moved to a different data center, we'll see how the routes will change after that.
