### ISSUE TITLE
No response to query with dns-over-tls

### ISSUE THREAD

**Issue by Ch4t4r** [AdguardTeam/AdGuardDNS#22]
I'm trying to run a dns-over-tls client in Java. For most servers it works quite well, for AdGuard however I get an EOFException when trying to read the answer to my question. Below is a simple example. Connecting to any other server (dns.quad9.net, dns.google, ...) works correctly and prints the proper received answer. The EOFException occurs in readUnsignedShort(), indicating that no response to the query is sent. Does this DoT server require me to wrap the DNS message in an udp packet?

```// Connect
val socket = SSLSocketFactory.getDefault().createSocket() as SSLSocket
socket.connect(InetSocketAddress("dns.adguard.com", 853))

// Create a question
val msg = DnsMessage.builder()
        .setId(12345678)
        .addQuestion(Question("google.com", Record.TYPE.A))
        .setQrFlag(false)
        .setRecursionDesired(true).build()
println(msg)

// Send the question
val dnsData = msg.toArray()
val outputStream = DataOutputStream(socket.outputStream)
outputStream.writeShort(dnsData.size) // The message has to be prefixed by the length: https://tools.ietf.org/html/rfc7858#section-3.3
outputStream.write(dnsData)
outputStream.flush()

// Receive the answer
val inStream = DataInputStream(socket.inputStream)
val readData = ByteArray(inStream.readUnsignedShort())
inStream.read(readData)

// Print the received answer
val response = DnsMessage(readData)
println(response)
```
My assumption that no data is transmitted seems to be backed up by wireshark:
![grafik](https://user-images.githubusercontent.com/26578153/55518088-0664ae00-5673-11e9-9d6a-cd1cd31ed82e.png)

Feel free to close if unrelated.

**Comment by ameshkov** [comment]
@Ch4t4r sorry for the late reply.

The code looks okay. AG DNS could close the connection if it failed to unpack the DNS query, but I don't understand why it happened in this particular case.

Possible issues:
1. You've got rate-limited for some reason
2. Smth might be wrong with `outputStream.writeShort(dnsData.size)`, it must be big endian.

**Comment by Ch4t4r** [comment]
@ameshkov no worries, I have been busy as well.

It wasn't the first option, I tested in different networks and with different users.
However, you were absolutly right with the big endian tip, I completely forgot that network byte-order is big endian, java default is little endian.
Changing the relevant lines to
```
        val size = dnsData.size
        val arr:ByteArray = byteArrayOf(((size shr 8) and 0xFF).toByte(), (size and 0xFF).toByte())
        outputStream.write(arr)
        outputStream.write(dnsData)
        outputStream.flush()
```
does the magic, it now works. Seems like other DNS servers aren't as strict as AdGuard and accept the query regardless.

Thank you for your help, closed.
