### ISSUE TITLE
Add some advertising network in Vietnam

### ISSUE THREAD

**Issue by bigdargon** [AdguardTeam/AdguardDNS#221]
I am a user in Vietnam, I see Adguard DNS has missed some ad networks in vietnam. I listed below a list of some advertisers that I found, can you block them on DNS?

qc.coccoc.com
adtima.vn
mobilead.vn
amobi.vn
vads.vn
adsota.com
adsplus.vn
vietnamnetad.vn
novaonads.com
myad.vn

**Comment by Alex-302** [comment]
added, but next time please provide examples of the sites.
