### ISSUE TITLE
The problem of DNS query speed in Asian countries

### ISSUE THREAD

**Issue by bigdargon** [AdguardTeam/AdguardDNS#222]
After Adguard iOS Pro updated version 1.3.0, I no longer block ads like version 1.2.1, so I had to use Adguard DNS to block ads in the app. I noticed the speed of Adguard DNS domain name is too slow, sometimes I watch video on Youtube or Facebook is broken.

I use the DNS Benchmark DNS test here: https://www.grc.com/dns/benchmark.htm

The process of checking my speed:
- Clean DNS cache on computer.
- Plug the LAN cable directly to the router.
- Use your ISP's default DNS.

And the result I have the log file after the check is attached below. Through the test I found Adguard very slow.
[log_test_dns.txt](https://github.com/AdguardTeam/AdguardDNS/files/1605952/log_test_dns.txt)

I see users in Taiwan also complain about the Adguard DNS query speed here: 
https://github.com/AdguardTeam/AdguardForiOS/issues/543#issuecomment-355344405
https://github.com/AdguardTeam/AdguardForiOS/issues/562#issuecomment-355334879

Hope you can fix it!

**Comment by lancelot-moon** [comment]
> After importing filters by URL is ready, I think that using a fast DNS and a comprehensive local filter is better, especially sometimes AdGuard DNS filtering is invalid...
(Maybe there is trouble in VPN tunnel or DNS hijacking.)

Simply choose a fast DNS (Your ISP or Google DNS) and add a comprehensive local filter in the blacklist.
For some filters with large numbers of rules, it's better to use only one custom local filter.
You should wait for AdGuard Pro v2.0.
It's difficult that AdGuard sets DNS servers in Taiwan or somewhere in Asia.

**Comment by ameshkov** [comment]
I hope the issue will go away with the v2.0 release when we introduce custom blocking subscriptions.

**Comment by lancelot-moon** [comment]
Hi,
Where will you introduce custom blocking subscriptions?
I really think that 1hosts.cf is a good source if it keeps updating!
You can introduce some good filters in the article.

Due to Apple policy, it's impossible that you introduce it in app or send users the notification of teaching guide by email, right?
So, on AdGuard blog?

Thanks a lot!
I really look forward to AdGuard Pro for iOS v2.0.

**Comment by ameshkov** [comment]
> Where will you introduce custom blocking subscriptions?

In AG for iOS v2.0

> Due to Apple policy, it's impossible that you introduce it in app or send users the notification of teaching guide by email, right?
> So, on AdGuard blog?

It seems that letting ppl know about that in our blog is okay.
