### ISSUE TITLE
Why DNS AdGuard run so slow in ASIA?

### ISSUE THREAD

**Issue by 3xploiton3** [AdguardTeam/AdguardDNS#223]
i'm leave in indonesia, i have tested many dns server for comparing

can you put dns adguard in singapore sir? it would be great 

![dns slow](https://user-images.githubusercontent.com/19517680/34856529-26e94f4c-f778-11e7-809c-3b3186f073b1.png)

**Comment by bigdargon** [comment]
@3xploiton3 same here https://github.com/AdguardTeam/AdguardDNS/issues/222

**Comment by 3xploiton3** [comment]
i think different i just used dns adguard, not ios product

**Comment by lancelot-moon** [comment]
Though AdGuard DNS is public and free service...
Why do you ask AdGuard to set DNS servers in Asia since you're not a customer?

**Comment by ameshkov** [comment]
That's simple. The closest server we have is in Singapore. However, we cannot guarantee that the network route to that server is the shortest for you -- it depends on your ISP. There's no easy solution for that -- we just need more servers all over the world to make anycast work better.
