### ISSUE TITLE
exey.io anti-adblock issue

### ISSUE THREAD

**Issue by gototheskinny** [AdguardTeam/AdGuardDNS#223]
When i use this dns site says "please disable your adblock"I assume this site is a mirror site of [exe.io](url) . When i switch to another non-filtering DNS there is no issue.
System: Win10 x64, uBlock Origin with annoyence filters enabled, no vpn or other filtering method.
Example link: [https://exey.io/NXNKyy1](url)

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdGuardSDNSFilter #925](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/925) via [**ZenHub**](https://www.zenhub.com/)
