### ISSUE TITLE
Iwanttfc.com not playing

### ISSUE THREAD

**Issue by mg8297819** [AdguardTeam/AdGuardDNS#224]
It plays when I switch back to default dns but not playing using adguard dns.
It works on pc or windows device but not on android.

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdGuardSDNSFilter #924](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/924) via [**ZenHub**](https://www.zenhub.com/)
