### ISSUE TITLE
Australia's biggest ISP is routing to US servers instead of Sydney

### ISSUE THREAD

**Issue by jupester** [AdguardTeam/AdGuardDNS#225]
Hi,  I am a customer of Australia's largest ISP (so a large amount of users will be affected by this) and since recently Adguard DNS always uses LA or Chicago DNS servers instead of the preferable Sydney one, it seems a common issue that the nearest server isn't used in many countries going by the open/closed issues, and you mentioned in one of those topics that sometimes it is any easy fix and sometimes it is not, hopefully you can look into this issue and see if it is possible to fix easily since it is a long way overseas to a US server in this case.

I will provide a screenshot of the traceroute from my ISP since I live in Victoria (not NSW where Sydney is) but below that is also a text excerpt from the looking glass tool (also link to that provided below) which shows even my ISP's main Sydney POP routes overseas instead of to AdGuards Sydney DNS server which is in the same city.

I don't have ipv6 so haven't included those traceroute results.

![AdGuard DNS 2022-03-27_151511](https://user-images.githubusercontent.com/50538846/160312305-60e7761f-0c9e-4ad4-8e94-4718ef9f0ff6.png)

https://lg.telstraglobal.com/

 1  i-91.sydp-core04.telstraglobal.net (202.84.222.85) 2 msec  1 msec  2 msec 
 2  i-91.sydp-core04.telstraglobal.net (202.84.222.85) [MPLS: Label 25165 Exp 0] 137 msec  136 msec  137 msec 
 3  i-20802.eqnx-core02.telstraglobal.net (202.84.141.25) 137 msec  137 msec  136 msec 
 4  i-92.eqnx03.telstraglobal.net (202.84.247.17) 135 msec  135 msec  135 msec 
 5  134.159.61.78 135 msec  135 msec  135 msec 
 6  Hu0-0-0-0.br06.chc01.pccwbtn.net (63.218.4.186) 182 msec  183 msec  182 msec 
 7  Hu0-0-0-0.br06.chc01.pccwbtn.net (63.218.4.186) 182 msec  182 msec  182 msec 
 8  209.8.108.66 186 msec  186 msec  186 msec 
 9  dns.adguard.com (94.140.14.14) 186 msec  186 msec  187 msec 
 

1  i-91.sydp-core04.telstraglobal.net (202.84.222.85) 2 msec  1 msec  0 msec 
 2  i-91.sydp-core04.telstraglobal.net (202.84.222.85) [MPLS: Label 25165 Exp 0] 135 msec  136 msec  136 msec 
 3  i-20802.eqnx-core02.telstraglobal.net (202.84.141.25) 136 msec  135 msec  136 msec 
 4  i-92.eqnx03.telstraglobal.net (202.84.247.17) 135 msec  136 msec  135 msec 
 5  134.159.61.78 135 msec  135 msec  135 msec 
 6  Hu0-0-0-0.br06.chc01.pccwbtn.net (63.218.4.186) 182 msec  182 msec  182 msec 
 7  Hu0-0-0-0.br06.chc01.pccwbtn.net (63.218.4.186) 182 msec  182 msec  182 msec 
 8  209.8.108.66 186 msec  186 msec  186 msec 
 9  dns.adguard.com (94.140.15.15) 187 msec  186 msec  186 msec 

Anyway up until recently thanks for supplying a great service, hopefully this issue is able to be rectified, thanks in advance.

**Comment by ameshkov** [comment]
Yeah, approximately half of the Australian users are routed to Chi/La servers. We'll need time to adjust BGP and reroute them to the proper location.

**Comment by jupester** [comment]
Is there an rough ETA on this getting resolved?, I noticed another user just reported the same issue,

https://github.com/AdguardTeam/AdGuardDNS/issues/335

**Comment by ameshkov** [comment]
Sorry that it takes so long, resolving this kind of issues requires communicating to ISPs and this takes time (but only the first time).

**Comment by D13410N3** [comment]
Can you please check your routing now?

**Comment by jupester** [comment]
Yes, thanks, I noticed it had changed 2 days ago, I was just waiting a couple days to make sure it was stable, before replying, I will included an updated traceroute just for your info. It is a massive change for me, less hops, and faster, I have also included the results from my ISP looking glass tool, which is also slightly faster and a couple less hops, but the change isn't as prominent as mine.

Thanks very much.

![2022-08-30_133552](https://user-images.githubusercontent.com/50538846/187725507-1c3981f3-02fb-424d-b0b5-a001ab50c111.png)
![2022-08-30_134317](https://user-images.githubusercontent.com/50538846/187725532-615f34be-4877-458c-b43e-ea0c5c859f11.png)

**Comment by jupester** [comment]
This same issue has happened to me again, I am getting routed to US server instead of Sydney AU.

Could you please look into it.

**Comment by emeritaacuity0u** [comment]
Same results here with Telstra.

**Comment by ameshkov** [comment]
The reason is that there's an issue with Telstra, their BGP communities seem to partially not work as we receive lots of traffic from Asia to Sydney. We had to temporary disable Telstra until it starts working again.

**Comment by emeritaacuity0u** [comment]
Hi @ameshkov,

Is there any indication of a time frame for when this issue will be resolved?

I’ve been experiencing this problem for many years now. Whenever I check, I often find myself connected to the LA and Miami servers, and only occasionally to the correct Sydney server.

Additionally, in the past year or two, Telstra has changed the way they handle DNS traceroutes on mobile devices, no longer showing the hops during a traceroute.

**Comment by ameshkov** [comment]
Unfortunately, we can't give any time frame as we can't control that. We can only report the issue to Telstra.

**Comment by jupester** [comment]
Ok, thanks for prompt reply and the info.  Hopefully it is something you can autonomously keep following up on, so that when/if Telstra resolve it on their end you can make your required changes.
