### ISSUE TITLE
Investigate Async DNS resolver compatibility

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardDNS#228]
> Recently the Google Chrome's developers have introduced a new feature, built inside the Chrome for Android, starting from v63 release (the current stable release is also v63), named "Async DNS resolver"; this is actually a built-in DNS resolver implemented inside Chrome for Android.
> 
> This feature's behavior is currently controllable by a Chrome flag; "chrome://flags/#enable-async-dns".
> 
> Recently they've switched this option to "Enabled" by using the "Default" value; just by a simple server-side command; this wasn't the case until some days ago. This flag is probably aimed to fight adblockers which rely on DNS blocking, like AdGuard DNS and AdGuard for Android app. With the Chrome's built-in DNS resolver Enabled; AdGuard DNS won't filter any advertisements; when one uses Chrome for Android.
> 
> Currently; it's easy to set the above-mentioned flag status to "Disabled", but if the Chrome's developer team remove the flag and leave the active built-in DNS resolver inside Chrome, the thing they surely intend to do in near future with upcoming updates, AdGuard DNS servers won't block any ad in Chrome, anymore.
> 
> I send a PNG screenshot as an attachment to this Email. It shows the flag.
> 
> <details>
> 
> ![image](https://user-images.githubusercontent.com/15856304/35185733-8bbcdc6e-fe11-11e7-8621-16cdf66dce45.png)
> 
> </details>
> 
> Is there any way to make their move against ad-blocking In-effective?

**Comment by ameshkov** [comment]
I cannot confirm this. Chrome's DNS resolver uses the same system DNS settings and it won't affect AdGuard.

> With the Chrome's built-in DNS resolver Enabled; AdGuard DNS won't filter any advertisements; when one uses Chrome for Android.

@evgeniy-ADG how exactly was AG DNS set up on the device?

**Comment by evgeniy-ADG** [comment]
@ameshkov 

>I've used both "OpenVPN Connect" and "OpenVPN for Android"
> OpenVPN clients for Android; my device is running Android 5.1.1; Lollipop.
> 
> The failure of AdGuard DNS after enabling the flag in Chrome for Android
> can be tested easily on many Websites, including "https://www.apkmirror.com

**Comment by ameshkov** [comment]
> I've used both "OpenVPN Connect" and "OpenVPN for Android"
> OpenVPN clients for Android; my device is running Android 5.1.1; Lollipop.

I don't really understand what these apps have to do with the DNS settings :(

I've used the AdGuard app and DNS filtering continues to work just okay.

**Comment by ameshkov** [comment]
On the other hand:
https://www.xda-developers.com/fix-dns-ad-blocker-chrome/

**Comment by ameshkov** [comment]
Not that we can do anything about that, though.

AG for Android will continue to work as it should. What for the DNS-based ad blocking, disabling Async DNS is the way.

**Comment by ameshkov** [comment]
You see, there's not much we can do from our side. Also, I suppose that this behavior is actually a bug of Chrome, and it will eventually be fixed.

**Comment by evgeniy-ADG** [comment]
As discussed, posting it here: 

> I think the first sentence of Andrew's comment/answer is correct and true, but about the second sentence; I think you have an optimistic view about the issue; Google, a company whose profits come almost fully from ads, really won’t stay in-active against ad-blocking industry; this definitely isn’t a bug and will be irreversible soon.

> I’m worried about the possibility of implementing this “Asynchronous DNS” feature into other apps (specially “Google Play services” app, which controls Google’s own “Google Mobile Ads” & “AdMob” ad plug-ins in Android), in the future, specially if this feature is free-to-use and/or license-free, this will be more important and worrying.

> I recently updated to the new Chrome v64 and a new bug-fix release, again from v64, some hours ago, tested again, nothing has changed, the flag is still there.

> I won’t discontinue the simultaneous use of AdGuard DNS with OpenVPN; instead I prefer to switch to Firefox for Android, after the change in Chrome becomes permanent, despite the fact that I always preferred Chrome over Firefox.

> I also attached four screenshots about the new test I’ve done with Chrome v64; after taking a look to the screenshots and also the name of “PNG” files, as a description, you will probably be surprised by finding out that the flag only allows the Advertisements to bypass the AdGuard’s DNS filtering, and the DNS check on AdGurad Website still shows I’m using the AdGuard DNS servers at the time of the test

<details> <summary> SCREENSHOTS </summary>

![image](https://user-images.githubusercontent.com/15856304/35517165-538de0e8-0516-11e8-94d6-6eeaa9d2ccf7.png)

![image](https://user-images.githubusercontent.com/15856304/35517170-57980b32-0516-11e8-96ac-1c274095aaa1.png)

![image](https://user-images.githubusercontent.com/15856304/35517176-5d2b5cf2-0516-11e8-8464-4604b8bcf225.png)

![image](https://user-images.githubusercontent.com/15856304/35517183-613f6a04-0516-11e8-9ad5-bd4bc1df665c.png)

</details>

> I think this whole matter is worth to be mentioned on AdGurad’s Weblog.

**Comment by ameshkov** [comment]
> 1. Google, a company whose profits come almost fully from ads, really won’t stay in-active against ad-blocking industry; this definitely isn’t a bug and will be irreversible soon.
> 2. I’m worried about the possibility of implementing this “Asynchronous DNS” feature into other apps (specially “Google Play services” app, which controls Google’s own “Google Mobile Ads” & “AdMob” ad plug-ins in Android), in the future, specially if this feature is free-to-use and/or license-free, this will be more important and worrying.

They are much smarter than that, really.

> I recently updated to the new Chrome v64 and a new bug-fix release, again from v64, some hours ago, tested again, nothing has changed, the flag is still there.

The flag itself is not bad, this is actually an improved DNS client. The problem is that *sometimes* Chrome switches to using Google DNS and that is actually a bug.

**Comment by ameshkov** [comment]
> I think this whole matter is worth to be mentioned on AdGurad’s Weblog.

Yes, I think you're right here.
