### ISSUE TITLE
Не блокирует рекламу в форкплеере в Украине.

### ISSUE THREAD

**Issue by Smorvel** [AdguardTeam/AdguardDNS#229]
Я нахожусь в Италии у меня все ок, никакой рекламы.. установил форк кое кому в Украине, там перед запуском плеера с фильмом идет реклама.

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| (176.103.130.130)
| How did you setup DNS configuration:| (Настройка ТВ)
| Device model:| (Samsung SmartTV K серии)
| Operating system and version:| (tizen)

**Comment by Alex-302** [comment]
А у кое-кого есть возможность в роутере лог DNS снять?

**Comment by Smorvel** [comment]
Ну сейчас его нет.. не счет лога не знаю получится ли.. если выйдет отпишусь.

**Comment by ameshkov** [comment]
Очень велика вероятность, что дело в провайдере - он просто перехватывает и подменяет DNS запросы.

А попробуйте использовать порт отличный от стандартного (5353)
