### ISSUE TITLE
DNS server blocking legit site.

### ISSUE THREAD

**Issue by razz100** [AdguardTeam/AdGuardDNS#23]
Hi,

I'm using Adguard DNS servers ( 176.103.130.130
176.103.130.131 ) with my WiFi modem configuration i.e 192.168.1.1.

Everything was working fine but of late it is giving trouble with legit sites.

For example this legit mobile site is not opening with Adguard DNS server : https://www.91mobiles.com/ . I get DNS_PROBE_FINISHED_NXDOMAIN error on trying to access this site.

What is the issue here? I have checked everything on my end. The site promptly opens up when I use 4g on my phone!

Please look into it and rectify the error. This must be happening with other sites as well!

**Comment by zzebrum** [comment]
@razz100 The rule was removed from CDN filter. It should be ok now, please recheck.
