### ISSUE TITLE
americatv.com.ar - anti-adblock message

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardDNS#23]
What exactly causes this?

Affected domain:
vmf.edge-apps.net

**Comment by Alex-302** [comment]
Can't reproduce
<details> 
![s](http://imagizer.imageshack.com/img923/461/9w0c6J.png)
</details>

**Comment by ameshkov** [comment]
@Alex-302 here is a link:
http://www.americatv.com.ar/vivo

**Comment by ameshkov** [comment]
Seems to be resolved with `@@||imasdk.googleapis.com^`

**Comment by ameshkov** [comment]
I've added this rule to exceptions, let's see if it helps

**Comment by Alex-302** [comment]
No detection now.

**Comment by Alex-302** [comment]
Added to English filter:
```
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$domain=vmf.edge-apps.net
```

**Comment by ameshkov** [comment]
@Alex-302 the issue is back

**Comment by Alex-302** [comment]
@ameshkov I think it is caused by
```
googleadapis.l.google.com
```
It was excluded in DNS filter today. I will check it after rebuild of DNS filter.
