### ISSUE TITLE
Based in NYC but AdGuard DNS connects to Germany

### ISSUE THREAD

**Issue by subhajitsaha97** [AdguardTeam/AdGuardDNS#230]
I just switched to AdGuard DNS from NextDNS and noticed that all my connections route through Frankfurt and not servers in New York City. Is there a fix for this? 

When I run the AdGuard Services Check Page, I get this as the server I'm connecting to: "dns2-dp-fra-10."

**Comment by ameshkov** [comment]
Hello,

In order to troubleshoot this issue we need to know the following information:

1. Your location (country would be enough)
2. Name of your internet service provider
3. We need to see the results of running the following command (on macOS run it in Terminal, on Windows run `cmd.exe`, then type in the command and press enter): `traceroute 94.140.14.14`

**Comment by KygekDev** [comment]
> Hello,
> 
> In order to troubleshoot this issue we need to know the following information:
> 
> 1. Your location (country would be enough)
> 2. Name of your internet service provider
> 3. We need to see the results of running the following command (on macOS run it in Terminal, on Windows run `cmd.exe`, then type in the command and press enter): `traceroute 94.140.14.14`

Correction: If you use Windows, use `tracert 94.140.14.14` instead.

**Comment by subhajitsaha97** [comment]
1) New York City, US
2) Verizon FiOS
3) Traceroute on macOS
traceroute to 94.140.14.14 (94.140.14.14), 64 hops max, 52 byte packets
 1  192.168.1.1 (192.168.1.1)  11.970 ms  3.588 ms  3.633 ms
 2  * * *
 3  100.41.26.46 (100.41.26.46)  21.096 ms
    100.41.26.48 (100.41.26.48)  10.501 ms
    100.41.26.46 (100.41.26.46)  19.185 ms
 4  0.csi1.whplnywp-mse01-bb-su1.alter.net (140.222.3.212)  8.039 ms
    0.csi1.grcynygc-mse01-bb-su1.alter.net (140.222.3.206)  14.713 ms  9.646 ms
 5  * * *
 6  * * *
 7  0.ae14.gw14.nyc1.alter.net (140.222.235.131)  21.054 ms  8.364 ms  9.359 ms
 8  vodafone-gw.customer.alter.net (204.148.1.254)  10.404 ms  15.195 ms  9.319 ms
 9  ae0-xcr1.nyh.cw.net (195.2.25.70)  90.313 ms  90.443 ms  91.673 ms
10  ae28-tcr1.pat.cw.net (195.2.24.242)  91.367 ms  90.766 ms  106.879 ms
11  ae44-pcr1.fis.cw.net (195.2.16.229)  93.687 ms  87.935 ms  91.096 ms
12  ae0-tcr1.fis.cw.net (195.2.30.73)  96.227 ms  90.295 ms  91.845 ms
13  62.208.195.130 (62.208.195.130)  90.736 ms  94.926 ms  91.182 ms
14  dns.adguard.com (94.140.14.14)  91.618 ms  89.459 ms  91.161 ms

**Comment by Chinaski1** [comment]
Hello there!

AdGuard DNS uses [Anycast](https://adguard-dns.io/en/blog/anycast-and-bgp-how-adguard-dns-serves-millions-of-queries.html) technology so we can't manage traffic routing 100% of the time.

At this point, we're compiling problems in internal list with the possibility of their correction in nearest future.
Please provide following information via email to support@adguard.com (also share a link to this issue on GitHub):

1) Your IP address: https://adguard.com/en/test.html
2) ASN. 
3) ISP name.
4) DNS server location: https://adguard.com/en/test.html

I am closing this task as it goes to the internal list of routing issues.
