### ISSUE TITLE
ilto.run not resolved with AdGuard DNS

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardDNS#231]
@adguard-bot commented on [Wed Apr 06 2022](https://github.com/AdguardTeam/AdguardFilters/issues/114807)

### Issue URL (Incorrect Blocking)
 [http://ilto.run](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Filto.run)
### Comment
Username: @LiorLL
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/bZRTD6r.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/ASbuybp.jpg)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard/AdGuard Pro for iOS v4.3.3
Browser: | Chrome
DNS filtering: | server: `https://dns.adguard.com/dns-query`<br>filters: `https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt, https://abp.oisd.nl/basic/`
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Security:</b><br/>NoCoin Filter List<br/><br/><b>Language-specific:</b><br/>EasyList Hebrew

---

@Alex-302 commented on [Fri Apr 08 2022](https://github.com/AdguardTeam/AdguardFilters/issues/114807#issuecomment-1092664329)

It is just vailable in Israel only.

**Comment by ameshkov** [comment]
The issue should go away when we add support for ECS to our DNS servers.

The problem is that this domain is only served when requested with an Israeli IP address.
