### ISSUE TITLE
blutv.com VOD video player doesn't work with AdGuardDNS

### ISSUE THREAD

**Issue by Sanseviearia** [AdguardTeam/AdGuardDNS#233]
Hi, 2 weeks ago blutv VOD site's video player was not loading with one of the rules of EasyPrivacy, created a ticket there and it is fixed. For the last few days it started to fail with AdGuard DNS too. Probably one of the lists updated with a rule that is preventing the player to load as well.

Here's the ticket with details on EasyPrivacy's Git.
`https://github.com/easylist/easylist/issues/11456`

This issue is happening on all devices that I set AdGuard Private DNS:
DoH: Opera, Chrome on both Mac and PC. iPhone and iPad.
DoT: AndroidTV, Android Phone.

blutv
`https://www.blutv.com/canli-yayin/kanal-d-izle`

Thanks

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdGuardSDNSFilter #934](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/934) via [**ZenHub**](https://www.zenhub.com/)
