### ISSUE TITLE
Logging in with Apple ID shows AdGuard VPN

### ISSUE THREAD

**Issue by gGkAC3qfszbdViFkw4Fk9ooS2u** [AdguardTeam/AdGuardDNS#234]
When signing in to AdGuard DNS dashboard (or any other AdGuard product) using your Apple ID, it says that it's logging into AdGuard VPN rather than AdGuard. This should not be happening, instead it should be showing the generic AdGuard logo and AdGuard text without the addition of VPN.

**Comment by ameshkov** [comment]
Here's the thing.

We're using a single AdGuard account for all our services. With Apple login you must link the login to some app and we at some point in the past linked it to AdGuard VPN app so here we are now.
