### ISSUE TITLE
Adblock is blocking www.financialpeace.com

### ISSUE THREAD

**Issue by jmdacd** [AdguardTeam/AdguardDNS#234]
### Steps to reproduce

1.  nslookup www.financialpeace.com 
2. brows to daveramsey.com/fpu --> click Sign In --> click yellow Sign under Financial Peace

### Expected behavior

It should resolve to allow the user to login to the Financial Peace site
### Actual behavior

It is blocked by family.block.dns.adguard.com (176.103.130.132)

<details><summary>Screenshot:</summary>

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| (176.103.130.132)
| How did you setup DNS configuration:| (pfSense)
| Device model:| (All Computers behind pfSense)
| Operating system and version:| (N/A)

**Comment by jmdacd** [comment]
AdGuard DNS is block, sorry meant to say "Adguard"

**Comment by ameshkov** [comment]
Seems to be resolved:
```
$ nslookup www.financialpeace.com 176.103.130.132
Server:		176.103.130.132
Address:	176.103.130.132#53

Non-authoritative answer:
Name:	www.financialpeace.com
Address: 52.84.213.189
```
