### ISSUE TITLE
AdGuard DNS says device is not added for every device

### ISSUE THREAD

**Issue by gGkAC3qfszbdViFkw4Fk9ooS2u** [AdguardTeam/AdGuardDNS#235]
When logging onto AdGuard DNS from any of my devices, AdGuard DNS shows a notification that the device is not added, even though the DNS requests are increasing.
The last request time is also increasing in time correctly.

All devices are using a config generated by AdGuard DNS.

Device 1: iOS 15.5
Device 2 iOS 15.4
Device 3: macOS 12.4

![5D4F12D3-FEB3-455D-8C87-71C878B07FA4](https://user-images.githubusercontent.com/95468948/163332262-e4b95163-0052-4e50-85d3-c8772d877e4a.png)

**Comment by ameshkov** [comment]
Do you use any VPN alongside the configuration profile?

**Comment by gGkAC3qfszbdViFkw4Fk9ooS2u** [comment]
I do not use a VPN.

It seems the issue is Apple's Private Relay product.
If I disable Private Relay, then reenable it, AdGuard DNS will show the device connected. It does the same thing with Next DNS, however NextDNS will show Private Relay and AdGuard DNS flicking back and forth continuously.

If this is the expected result with Private Relay and not something that can be worked around, feel free to close the issue.

**Comment by ameshkov** [comment]
As I recall, Private Relay ignores DNS profiles and uses its own DNS server for Safari.

**Comment by ameshkov** [comment]
I don't think we can do anything with it (unless Apple fixes this themselves).

**Comment by gGkAC3qfszbdViFkw4Fk9ooS2u** [comment]
> As I recall, Private Relay ignores DNS profiles and uses its own DNS server for Safari.

As this is going to affect all Apple devices with Private Relay enabled for the foreseeable future, would it be possible to add a minimise/close button for that notification?
