### ISSUE TITLE
phpMyAdmin official site is blocked

### ISSUE THREAD

**Issue by samuelaguilera** [AdguardTeam/AdguardDNS#237]
### Steps to reproduce

Just try to access to [phpMyAdmin](https://www.phpmyadmin.net) with a browser when having AdGuard DNS configured in the router or device.

### Expected behavior

It should not block access to phpMyAdmin site, that is a well known open source project for managing databases, and not an ads server or anything else.
### Actual behavior

It blocks the access to this domain.

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| 176.103.130.130 and 176.103.130.131
| How did you setup DNS configuration:| System or Router (same result)
| Device model:| Desktop PC / Galaxy S7
| Operating system and version:| Windows 10 / Android 7.0

**Comment by Alex-302** [comment]
I can't reproduce this issue.

**Comment by ameshkov** [comment]
Yup, seems to be okay:

```
$ nslookup www.phpmyadmin.net 176.103.130.130
Server:		176.103.130.130
Address:	176.103.130.130#53

Non-authoritative answer:
Name:	www.phpmyadmin.net
Address: 185.59.222.23
```

@samuelaguilera please reopen the issue if it still happens on your side. If so, we'll need to see the nslookup command output.

**Comment by samuelaguilera** [comment]
The issue is not with the DNS resolution, as I'm getting the same result for nslookup:

```
me@desktop:~$ nslookup www.phpmyadmin.net
Server:         176.103.130.130
Address:        176.103.130.130#53

Non-authoritative answer:
Name:   www.phpmyadmin.net
Address: 185.59.223.22
```

But as explained in the steps to reproduce the issue of my original message, **if you try to open the site in a browser it will not load**. Returning an ERR_TIMED_OUT error in the browser. 

I tried this with latest versions of Chrome, Firefox and Edge with same result.

**Changing the DNS servers in the device to any other DNS servers solves the issue.** 

Please let me know if you need me to do any other test.

**Comment by ameshkov** [comment]
Interesting, here's what I'm getting with a local DNS server:

```
$ nslookup www.phpmyadmin.net
Server:		192.168.10.125
Address:	192.168.10.125#53

Non-authoritative answer:
www.phpmyadmin.net	canonical name = 1115546720.rsc.cdn77.org.
Name:	1115546720.rsc.cdn77.org
Address: 87.245.204.28
```

This might be the same issue as with custom DNS and Akamai CDN:
https://www.cnet.com/news/google-dns-slowing-down-itunes-and-apple-tv/

**Comment by samuelaguilera** [comment]
Interesting,  I'm also getting different results when using nslookup with my ISP DNS servers.

```
me@desktop:~$ nslookup www.phpmyadmin.net
Server:         192.168.1.1
Address:        192.168.1.1#53

Non-authoritative answer:
www.phpmyadmin.net      canonical name = 1115546720.rsc.cdn77.org.
Name:   1115546720.rsc.cdn77.org
Address: 185.93.3.18
```
Is AdGuard using an upstream DNS provider as PiHole does to perform the DNS resolution? If so I wonder if the issue could be in this upstream DNS provider not having up to date information for the www.phpmyadmin.net domain.

Is this something you can check somehow?

**Comment by ameshkov** [comment]
It might be that CDN77 relies on the DNS resolution and using custom DNS server might be messing with it somehow (just like the link from my comment).

**Comment by samuelaguilera** [comment]
I did further testing using a few third-party DNS servers as Google (8.8.8.8) or Alternate DNS  (23.253.163.53 and 198.101.242.72) and Open DNS ( 208.67.222.222
208.67.220.220 ) I was able to access to www.phpmyadmin.net without any issues using any of these. So it's not about using custom DNS but about using AdGuard DNS servers. At least for the phpMyAdmn site...

As in addition to this I found accidentally another site that can't be visited when using AdGuard DNS: [www.elespanol.com](https://www.elespanol.com/)

And repeated the testing with this site, and found something more weird... I can access to the site using Google DNS and Open DNS but not using AdGuard DNS or Alternate DNS. And to add more weirdness I can't see any difference in the resolution results, I'm pasting them below in case that I'm missing something:

**AdGuard DNS** (Both phpmyadmin.net and elespanol.com are reaching time out when visiting them in a browser)

```
me@desktop:~$ nslookup www.elespanol.com
Server:         23.253.163.53
Address:        23.253.163.53#53

Non-authoritative answer:
www.elespanol.com       canonical name = caching.elespanol.edge2befaster.com.
caching.elespanol.edge2befaster.com     canonical name = cec01.use.elespanol.edgetcdn.com.
Name:   cec01.use.elespanol.edgetcdn.com
Address: 185.59.223.154
```

**Alternate DNS** (elespanol.com site is reaching time out when visiting it in a browser, but phpmyadmin.net is loading without issues)

```
me@desktop:~$ nslookup www.elespanol.com
Server:         23.253.163.53
Address:        23.253.163.53#53

Non-authoritative answer:
www.elespanol.com       canonical name = caching.elespanol.edge2befaster.com.
caching.elespanol.edge2befaster.com     canonical name = cec01.use.elespanol.edgetcdn.com.
Name:   cec01.use.elespanol.edgetcdn.com
Address: 185.59.223.154
```

**Google** (Both sites are loading without issues)

```
me@desktop:~$ nslookup www.elespanol.com
Server:         23.253.163.53
Address:        23.253.163.53#53

Non-authoritative answer:
www.elespanol.com       canonical name = caching.elespanol.edge2befaster.com.
caching.elespanol.edge2befaster.com     canonical name = cec01.use.elespanol.edgetcdn.com.
Name:   cec01.use.elespanol.edgetcdn.com
Address: 185.59.223.154
```

**Open DNS** (Both sites are loading without issues)

```
me@desktop:~$ nslookup www.elespanol.com
Server:         23.253.163.53
Address:        23.253.163.53#53

Non-authoritative answer:
www.elespanol.com       canonical name = caching.elespanol.edge2befaster.com.
caching.elespanol.edge2befaster.com     canonical name = cec01.use.elespanol.edgetcdn.com.
Name:   cec01.use.elespanol.edgetcdn.com
Address: 185.59.223.154
```

So I wonder if these sites could be blocking users using DNS servers specifically intended to block ads. Is that possible somehow?

**Comment by ameshkov** [comment]
Well, I can say what's the difference between Google/OpenDNS and us.

AdGuard DNS has just 6 different locations over the world while both Google/OpenDNS have many more locations.

> And to add more weirdness I can't see any difference in the resolution results, I'm pasting them below in case that I'm missing something:

You've copy/pasted the same result 4 times (the same DNS server -- `23.253.163.53`)
