### ISSUE TITLE
IPv6 addresses are newly missing from new device setup

### ISSUE THREAD

**Issue by gGkAC3qfszbdViFkw4Fk9ooS2u** [AdguardTeam/AdGuardDNS#237]
When adding a new device to AdGuard DNS, in step 2 it lists all the addresses that can be manually used.
It appears that the IPv6 addresses are missing where they used to be there.

Are they meant to be there now, or is this a bug?

![image](https://user-images.githubusercontent.com/95468948/163557466-0dfa8957-07f0-41bf-9d06-b480f731b10b.png)

**Comment by ameshkov** [comment]
Link IP currently works with IPv4 only.

Regarding IPv6, we'll either use a different way (provide unique IPv6 address to use) or add Link IP support as well.
