### ISSUE TITLE
Bug: Adguard DNS do not block YouTube ads

### ISSUE THREAD

**Issue by mzabuawala** [AdguardTeam/AdguardDNS#238]
Hello,

First of all `Thank you so much for the great product`.

I am using Adguard DNS in my home router to block ads and it is working properly, the only issue I've is it does not blocks ads on YouTube videos (Ads which comes at the beginning of the video and in-between that video)

Details:
OS: macOS Yosemite
Affected browsers: All
I'm using `Family protection` DNS in my home router.

Screenshot: https://imgur.com/a/QTsKg

Expected behaviour:
YouTube videos play without ads.

Could you please fix that?

**Comment by mzabuawala** [comment]
<img width="912" alt="screen shot 2018-02-19 at 9 13 12 am" src="https://user-images.githubusercontent.com/19573369/36362056-363aca28-1557-11e8-9910-4cb496ec9958.png">
<img width="1332" alt="screen shot 2018-02-19 at 9 13 28 am" src="https://user-images.githubusercontent.com/19573369/36362057-366aa856-1557-11e8-91d6-2b6c100abcc6.png">
<img width="1372" alt="screen shot 2018-02-19 at 9 28 36 am" src="https://user-images.githubusercontent.com/19573369/36362064-4effa4ac-1557-11e8-90cc-84f80632d206.png">

**Comment by ameshkov** [comment]
@Alex-302 could you please take a look?

**Comment by Alex-302** [comment]
Hi
It seems video ads can't be blocked[in some cases].
It is impossible to block this ad request using DNS filtering 
![image](https://user-images.githubusercontent.com/8361299/36373837-0e0b4d0a-1572-11e8-9128-f89f303b9022.png)
But on my side I see only yellow labels on progress bar without video ads.

**Comment by ameshkov** [comment]
@mzabuawala in order to troubleshoot we'll need to get a HAR file with the issue recorded:
https://support.zendesk.com/hc/en-us/articles/204410413-Generating-a-HAR-file-for-troubleshooting

**Comment by mzabuawala** [comment]
Attaching `har` file, there was a video ad at beginning of video, After 80% ad playback I clicked on `Skip Ad` to continue with actual video.

[www.youtube.com.har.zip](https://github.com/AdguardTeam/AdguardDNS/files/1736871/www.youtube.com.har.zip)

**Comment by Alex-302** [comment]
I can't find video ad. Could you please make new HAR and screenshot of one of the first ad frames?
It seems video ad is loaded from `*.googlevideo.com`

**Comment by mzabuawala** [comment]
[ScreenRecording_Youtube_Ad.m4v.zip](https://github.com/AdguardTeam/AdguardDNS/files/1737917/ScreenRecording_Youtube_Ad.m4v.zip)


I'm not able to upload har file due to large size, I've uploaded it 3rd party hosting.
Download link: https://nofile.io/f/7dp5WDrjFDU/www.youtube.com.har.zip

**Comment by Alex-302** [comment]
No, it is impossible with DNS filtering only.

**Comment by mzabuawala** [comment]
That's disappointing :(

**Comment by Alex-302** [comment]
But you can install AdGuard extension or the app:)

**Comment by bigdargon** [comment]
This is disappointing! I'm using Adguard for iOS and Youtube video ads appear continuously :(

**Comment by ameshkov** [comment]
Yeah, the very same problem is with the iOS. The only ugly workaround is to use Youtube in Safari.

**Comment by Gaspard-Bourgeois** [comment]
Are they any update about it ? I'm facing the same issue. It even bring more ads on youtube.

**Comment by stamatgeorge** [comment]
I'm facing the same issue.

**Comment by toutvukantabu** [comment]
if you have any solution, thanks in advance !!

**Comment by Gaspard-Bourgeois** [comment]
It is in fact not possible to block ads with adguard home, as it filters
only dns. I can't explain why, but I read that on the internet. Try Adblock
Plus if you can.
