### ISSUE TITLE
AdGuard DNS not using Singapore server

### ISSUE THREAD

**Issue by KingCWL** [AdguardTeam/AdGuardDNS#239]
Hi Adguard team, 

please assist on the below and hope this helps.

Thank you

Singapore
Singtel

Tracing route to dns.adguard.com [94.140.14.14]
over a maximum of 30 hops:

1 17 ms <1 ms <1 ms 118.118.118.118
2 3 ms 2 ms 2 ms bb116-14-45-254.singnet.com.sg [116.14.45.254]
3 3 ms 3 ms 3 ms 165.21.193.18
4 3 ms 4 ms 3 ms 165.21.193.17
5 4 ms 3 ms 5 ms 165.21.138.181
6 3 ms 3 ms 3 ms SN-SINTP1-BO402-ae1.singnet.com.sg [165.21.138.94]
7 3 ms 3 ms 3 ms 203.208.177.217
8 3 ms 3 ms 3 ms 203.208.183.134
9 4 ms 4 ms 3 ms 203.208.182.250
10 4 ms 4 ms 5 ms 203.208.153.246
11 4 ms 4 ms 4 ms 203.208.182.254
12 199 ms 199 ms 200 ms 203.208.182.126
13 179 ms 179 ms 178 ms 203.208.171.118
14 188 ms 188 ms 188 ms 63-218-42-9.static.pccwglobal.net [63.218.42.9]
15 235 ms 235 ms 235 ms BE43.br06.chc01.pccwbtn.net [63.218.4.194]
16 226 ms 226 ms 226 ms 209.8.108.66
17 228 ms 228 ms 228 ms dns.adguard.com [94.140.14.14]

Tracing route to dns.adguard.com [94.140.15.15]
over a maximum of 30 hops:

1 6 ms <1 ms <1 ms 118.118.118.118
2 3 ms 2 ms 2 ms bb116-14-45-254.singnet.com.sg [116.14.45.254]
3 3 ms 3 ms 3 ms 165.21.193.18
4 3 ms 3 ms 3 ms 165.21.193.17
5 5 ms 26 ms 5 ms 165.21.138.181
6 3 ms 3 ms 3 ms SN-SINTP1-BO402-ae1.singnet.com.sg [165.21.138.94]
7 4 ms 3 ms 3 ms 203.208.177.217
8 8 ms 8 ms 4 ms 203.208.183.134
9 4 ms 3 ms 3 ms 203.208.183.250
10 178 ms 177 ms 177 ms 203.208.182.42
11 164 ms 164 ms 164 ms 203.208.171.118
12 174 ms 174 ms 174 ms 63-218-42-9.static.pccwglobal.net [63.218.42.9]
13 221 ms 221 ms 221 ms BE43.br06.chc01.pccwbtn.net [63.218.4.194]
14 213 ms 212 ms 212 ms 209.8.108.66
15 225 ms 225 ms 225 ms dns.adguard.com [94.140.15.15]

Tracing route to dns.adguard.com [2a10:50c0::ad1:ff]
over a maximum of 30 hops:

1 Transmit error: code 1231.

**Comment by D13410N3** [comment]
Hello! Can you please check results now?

**Comment by KingCWL** [comment]
Hi, please refer to the traceroute below

traceroute to 94.140.14.14 (94.140.14.14), 64 hops max, 72 byte packets
 1  181-181-181-181 (181.181.181.181)  6.940 ms  2.167 ms  2.117 ms
 2  bb42-60-217-254.singnet.com.sg (42.60.217.254)  4.748 ms  5.244 ms  4.153 ms
 3  165.21.193.234 (165.21.193.234)  4.365 ms *  4.861 ms
 4  165.21.193.233 (165.21.193.233)  4.441 ms  4.386 ms  3.947 ms
 5  165.21.139.169 (165.21.139.169)  6.615 ms  4.209 ms  4.844 ms
 6  165.21.139.134 (165.21.139.134)  5.927 ms  5.289 ms  5.975 ms
 7  203.208.143.129 (203.208.143.129)  4.584 ms  4.821 ms  4.364 ms
 8  203.208.154.98 (203.208.154.98)  4.763 ms  4.655 ms  4.924 ms
 9  203.208.173.82 (203.208.173.82)  485.766 ms  198.155 ms  198.328 ms
10  63-218-42-9.static.pccwglobal.net (63.218.42.9)  211.735 ms  461.254 ms  207.601 ms
11  be43.br06.chc01.pccwbtn.net (63.218.4.194)  406.661 ms  249.688 ms  311.903 ms
12  209.8.108.66 (209.8.108.66)  251.442 ms  239.180 ms *
13  * * *
14  dns.adguard.com (94.140.14.14)  259.360 ms  304.610 ms  307.402 ms

traceroute to 94.140.15.15 (94.140.15.15), 64 hops max, 72 byte packets
 1  181-181-181-181 (181.181.181.181)  3.136 ms  2.142 ms  2.107 ms
 2  bb42-60-217-254.singnet.com.sg (42.60.217.254)  5.890 ms  16.448 ms  4.462 ms
 3  165.21.193.234 (165.21.193.234)  10.176 ms  18.912 ms  4.510 ms
 4  165.21.193.233 (165.21.193.233)  5.010 ms  4.678 ms  3.889 ms
 5  165.21.139.169 (165.21.139.169)  6.993 ms  11.591 ms  10.523 ms
 6  165.21.139.134 (165.21.139.134)  12.507 ms  11.099 ms  5.457 ms
 7  203.208.143.129 (203.208.143.129)  6.251 ms  12.320 ms  5.730 ms
 8  203.208.154.98 (203.208.154.98)  18.065 ms  11.741 ms  5.246 ms
 9  203.208.182.254 (203.208.182.254)  8.052 ms  5.112 ms  4.905 ms
10  203.208.172.214 (203.208.172.214)  4.771 ms  8.048 ms  5.011 ms
11  xn-lhrcl1-bo706.ix.singtel.com (203.208.183.81)  8.190 ms  5.131 ms  6.580 ms
12  203.208.151.182 (203.208.151.182)  199.609 ms  439.680 ms  175.889 ms
13  63-218-42-9.static.pccwglobal.net (63.218.42.9)  182.473 ms  187.771 ms  193.006 ms
14  be43.br06.chc01.pccwbtn.net (63.218.4.194)  225.253 ms  225.929 ms  346.500 ms
15  209.8.108.66 (209.8.108.66)  230.117 ms  231.117 ms  457.306 ms
16  * * *
17  dns.adguard.com (94.140.15.15)  354.434 ms  289.193 ms  222.400 ms

**Comment by KingCWL** [comment]
It shows this dns2-dp-chi-2

**Comment by Chinaski1** [comment]
Hello there!

AdGuard DNS uses [Anycast](https://adguard-dns.io/en/blog/anycast-and-bgp-how-adguard-dns-serves-millions-of-queries.html) technology so we can't manage traffic routing 100% of the time.

At this point, we're compiling problems in internal list with the possibility of their correction in nearest future.
Please provide following information via email to support@adguard.com (also share a link to this issue on GitHub):

1) Your IP address: https://adguard.com/en/test.html
2) ASN. 
3) ISP name.
4) DNS server location: https://adguard.com/en/test.html

I am closing this task as it goes to the internal list of routing issues.
