### ISSUE TITLE
host-tracker.com, smart-ip.net

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardDNS#239]
Both sites are redirected to 127.0.0.1 when using AdGuard DNS:

nslookup for host-tracker.com:
```
Сервер:  UnKnown
Address:  192.168.0.1

Имя:     host-tracker.com
Addresses:  ::1
	  127.0.0.1
```

nslookup for smart-ip.net:
```
Сервер:  UnKnown
Address:  192.168.0.1

Имя:     smart-ip.net
Addresses:  ::1
	  127.0.0.1
```

In both cases, AdGuard DNS is used on the router.

**Comment by Alex-302** [comment]
smart-ip.net - tracker
host-tracker.com - replaced to ext.host-tracker.com
