### ISSUE TITLE
Adguard DNS Connects Me to Germany, Even Though I am Closest to Toronto (1-hour drive)

### ISSUE THREAD

**Issue by MarcoProlo** [AdguardTeam/AdGuardDNS#240]
In the past (Before Feb 2022), I used to connect Adguard's Chicago DNS. However, after used the Chicago DNS for around half a year, in the mid Feb 2022, Adgaurd decided to connect me to the server located in Frankfurt, Germany. This has significantly slow down the web experience, a ping to google.ca gone from <20ms to around 90-110ms.

I am located in Oshawa, ON (Closest to Toronto)
Country: Canada
ISP: Bell Canada
Traceroute Results:

![image](https://user-images.githubusercontent.com/34116046/164362443-73abd339-9808-4bd1-bbda-f2d87be98813.png)

![image](https://user-images.githubusercontent.com/34116046/164362630-33b0d110-f53c-4ff7-af7d-8efa8d2d42e1.png)

(Cannot run traceroute 2a10:50c0::ad1:ff as Bell Canada does not support IPv6)

**Comment by gpodder770** [comment]
Moved to Winnipeg, Manitoba
Using Bell as provider
Having the same problem where I get connected to Chicago and newyork with koodo mobile sim

but if I use nextdns or controld then I get connected to their torronto servers

It is baffling that it is still happening!!!

**Comment by Chinaski1** [comment]
Hello there!

AdGuard DNS uses [Anycast](https://adguard-dns.io/en/blog/anycast-and-bgp-how-adguard-dns-serves-millions-of-queries.html) technology so we can't manage traffic routing 100% of the time.

At this point, we're compiling problems in internal list with the possibility of their correction in nearest future.
Please provide following information via email to support@adguard.com (also share a link to this issue on GitHub):

1) Your IP address: https://adguard.com/en/test.html
2) ASN. 
3) ISP name.
4) DNS server location: https://adguard.com/en/test.html

I am closing this task as it goes to the internal list of routing issues.
