### ISSUE TITLE
prxsolutions.com blocked by Family Protection DNS

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardDNS#241]
Website: http://prxsolutions.com

Screenshot:
![image](https://user-images.githubusercontent.com/33634917/36802262-209ab878-1cbd-11e8-8ae1-95661cbfe90f.png)

**Comment by akmLaVx** [comment]
The website is a specialized website for professionals working in medical & pharmacy industry.

**Comment by vbagirov** [comment]
I've removed the website from the blacklist. The changes will take effect in ~24 hours.
