### ISSUE TITLE
hqq.watch

### ISSUE THREAD

**Issue by MajkiIT** [AdguardTeam/AdguardDNS#242]
### Steps to reproduce

1.  Open this page http://cda-x.pl/filmy/botoks/
2. then you insert play button then will open new window
3.
4.

### Expected behavior

Not open new page

### Actual behavior

Opne new page

<details><summary>Screenshot:</summary>

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use: |176.103.130.130
| How did you setup DNS configuration:| static dns setting on TV
| Device model: |SONY TV
| Operating system and version:| Android  6.x.

**Comment by MajkiIT** [comment]
Popup scripts 
lyuswpdanr.com

**Comment by ameshkov** [comment]
Thank you, added it:
https://github.com/AdguardTeam/AdguardDNS/commit/298d094e1178d84a29aef5912b7c3606f20b6928

**Comment by adamibeata** [comment]
https://cda-tv.pl

**Comment by MajkiIT** [comment]
@adamibeata https://github.com/MajkiIT/polish-ads-filter/commit/c3bf1847c57f9064d58c29b86a42313569435dfb
