### ISSUE TITLE
email.propertybeforeprada.com being blocked

### ISSUE THREAD

**Issue by gGkAC3qfszbdViFkw4Fk9ooS2u** [AdguardTeam/AdGuardDNS#243]
Hi,

email.propertybeforeprada.com is being blocked within AdGuard DNS with the only filter being the AdGuard DNS filter. This breaks functionality for a mortgage broker portal.

This issue was raised here as I could not find it within the AdGuard DNS filter source.

<img width="540" alt="Screen Shot 2022-04-29 at 13 22 32" src="https://user-images.githubusercontent.com/95468948/165880954-c082c64a-b027-46d4-95b5-8fecf86f3102.png">
.

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdGuardSDNSFilter #946](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/946) via [**ZenHub**](https://www.zenhub.com/)
