### ISSUE TITLE
cda-x.pl

### ISSUE THREAD

**Issue by MajkiIT** [AdguardTeam/AdguardDNS#243]
### Steps to reproduce

1.  Open this page http://cda-x.pl/filmy/botoks/
2. then you insert play button then will open new window
3.
4.

### Expected behavior

Not open new page

### Actual behavior

Open new page

### Solution block this 2 domains 
```
www.vahufapave.com
www.cewegncr.com
```

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use: |176.103.130.130
| How did you setup DNS configuration:| static dns setting on TV
| Device model: |SONY TV
| Operating system and version:| Android  6.x.

**Comment by Alex-302** [comment]
Hi
I see 404
![image](https://user-images.githubusercontent.com/8361299/37039739-da11625a-2160-11e8-8512-6f8c2283e9b7.png)

**Comment by MajkiIT** [comment]
@Alex-302 Ok... 
So try this url http://cda-x.pl/filmy/wyglodniali-ravenous-les-affames/

I see scripts, from domains:
```
www.vahufapave.com
www.cewegncr.com
www.dwabissw.com
www.weline.info
```

**Comment by Alex-302** [comment]
I see only `eline.info`, and it is not blocked by DNS. This site works fine on my device.

**Comment by Alex-302** [comment]
Damn. Do you mean clickunder?

**Comment by MajkiIT** [comment]
@Alex-302 Yes, open the page and click play on player, then you will see this random domains.

**Comment by Alex-302** [comment]
Ok. Added few domains.
Can you install AG on your TV?

**Comment by MajkiIT** [comment]
hmmm I will try.

**Comment by adamibeata** [comment]
https://cda-tv.pl
