### ISSUE TITLE
I am in Brazil, routing to Amsterdam

### ISSUE THREAD

**Issue by jadasilvampsc** [AdguardTeam/AdGuardDNS#246]
Hi Adguard team,

High latency, I prefer Miami

Tracing route to dns.adguard.com:
traceroute to dns.adguard.com (94.140.15.15), 30 hops max, 60 byte packets
 1  _gateway (10.0.0.2)  3.578 ms  3.555 ms  4.021 ms
 2  172.24.199.1 (172.24.199.1)  7.586 ms  8.953 ms  10.089 ms
 3  * * 172.22.0.69 (172.22.0.69)  37.959 ms
 4  * * *
 5  * * *
 6  172.22.0.253 (172.22.0.253)  19.567 ms  3.901 ms  4.902 ms
 7  172.24.165.9 (172.24.165.9)  10.637 ms  11.847 ms  13.416 ms
 8  172.24.161.165 (172.24.161.165)  14.787 ms  15.966 ms  17.108 ms
 9  172.24.161.85 (172.24.161.85)  17.661 ms  18.120 ms  19.412 ms
10  172.24.161.1 (172.24.161.1)  18.722 ms  20.044 ms  20.606 ms
11  * * *
12  * * *
13  172.23.241.101 (172.23.241.101)  19.826 ms  20.314 ms  20.895 ms
14  * * *
15  * * *
16  * * *
17  * * *
18  * * *
19  * * *
20  * * *
21  dns.adguard.com (94.140.15.15)  241.266 ms  241.291 ms  232.699 ms

**Comment by ameshkov** [comment]
Duplicates https://github.com/AdguardTeam/AdGuardDNS/issues/29
