### ISSUE TITLE
Issues with taking surveys due to a Confirmit.com filter

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdguardDNS#247]
Adguard DNS currently has a filter against confirmit.com (Entry №14176 in filter.txt), which made me unable to access [a legitimate survey](http://www.uib.no/medborger) made by a Norwegian university (https://survey.euro.confirmit.com/wix/7/p1863116897.aspx). Therefore I wonder if it's possible to remove confirmit.com from the filters, or to whitelist survey.euro.confirmit.com, euro.confirmit.com, or however else you guys see fit to resolve the problem.

### Steps to reproduce

1. Apply Adguard DNS's main IPv4 address and two IPv6 addresses to the ASUS RT-AC68U
2. Try to go to https://survey.euro.confirmit.com/wix/7/p1863116897.aspx in Google Chrome or in Basilisk Browser.

### Expected behavior

A password login screen for _Norsk Medborgerpanel_ shows up.

### Actual behavior

Chrome loads an ERR_CONNECTION_REFUSED error page.

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| IPv6 DNS servers, from main to tertiary: 2a00:5a60::ad1:0ff (Adguard), 2a00:5a60::ad2:0ff (Adguard), 2620:0:ccc::2 (OpenDNS) — IPv4 DNS servers in use, from main to secondary: 176.103.130.130 (Adguard), 198.101.242.72 (AlternativeDNS Ad Blocking)
| How did you setup DNS configuration:| Router (ASUS RT-AC68U, native ASUSWRT GUI)
| Device model:| Self-built desktop PC based on an ASUS X87-EXPERT motherboard
| Operating system and version:| Windows 10, build 10.0.16299, recentmost security update KB4058043

**Comment by Alex-302** [comment]
will be fixed after merging new changes
