### ISSUE TITLE
AdGuard DNS Family Protection blocks OkCupid.

### ISSUE THREAD

**Issue by abx-dx** [AdguardTeam/AdGuardDNS#247]
When i use AdGuard DNS Family Protection either with IP adresses at router or DoH at Firefox or Android 10, i cannot use OkCupid (okcupid.com). At Vivaldi it gives NET::ERR_CERT_COMMON_NAME_INVALID, at Firefox it gives SSL_ERROR_BAD_CERT_DOMAIN and at Android it says it cannot connect to server.

There is not such as problem at AdGuard DNS Default.

**Comment by ameshkov** [comment]
The website is supposed to be used by adults only, that's why it's blocked by the family protection configuration.

**Comment by abx-dx** [comment]
I couldn't get the point while Bumble and Tinder (this one contains more of adult content than Okcupid) are reachable while Okcupid has blocked.
