### ISSUE TITLE
The DNSCrypt alternative

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardDNS#248]
> I know that you were using DNSCrypt in the past since you're still linking to it from here: https://adguard.com/en/adguard-dns/overview.html. It used to be such a great tool, but sadly, it's no longer available.
> 
> If you're interested in a replacement for that link, feel free to check out the DNSCrypt alternatives guide <https://thebestvpn.com/dnscrypt-best-alternatives/> that I've recently composed. I think it could be a beneficial resource for your audience, if you agree, feel free to replace the broken link. :)

ID 1784849

**Comment by SheepKid12** [comment]
DNSCrypt isn’t discontinued, I found a website (which I hope is the official one) here: https://dnscrypt.info

**Comment by evilvibes** [comment]
> DNSCrypt appears to still be available. I found a website (which I hope is the official one) here: https://dnscrypt.info

That is the official site also you can find it here: [https://github.com/jedisct1/dnscrypt-proxy](https://github.com/jedisct1/dnscrypt-proxy)

**Comment by SheepKid12** [comment]
Good. I think the problem here is that the DNSCrypt setup page is linking to dnscrypt.org, which doesn’t seem to work anymore.

**Comment by evilvibes** [comment]
Just did a pull to fix the url

https://github.com/AdguardTeam/AdguardDNS/pull/249
