### ISSUE TITLE
Can't move devices between servers

### ISSUE THREAD

**Issue by gGkAC3qfszbdViFkw4Fk9ooS2u** [AdguardTeam/AdGuardDNS#248]
Whilst adding some additional devices, I needed to move them to a different server within my AdGuard DNS dashboard. When I tried to move them to a new server, it said that it had taken effect up the top, but when navigating back to the server list it still stated that the device was in the original server.

Steps taken:
1. Create server 'A'
2. Connect a device to server 'A'
3. Create server 'B'
4. Set device to server 'B'
5. View server 'A' connected devices, and the device will not have moved servers as it was told to

**Comment by gGkAC3qfszbdViFkw4Fk9ooS2u** [comment]
Seems to be experiencing the same issues as #236.

**Comment by IldarKamalov** [comment]
Thanks for your report. Will be fixed in the next release

**Comment by gGkAC3qfszbdViFkw4Fk9ooS2u** [comment]
> Thanks for your report. Will be fixed in the next release

As there has been no announcements of AdGuard DNS releases in the past in regards to versioning, and there is no versioning displayed on the dashboard, how will I know when the next release happens?

**Comment by ameshkov** [comment]
@gGkAC3qfszbdViFkw4Fk9ooS2u oh, don't worry, we'll announce it soon. The update is substantial.

**Comment by Chinaski1** [comment]
Fixed in v0.3.1 beta update
