### ISSUE TITLE
Increase viewable device name length on Dashboard

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardDNS#249]
When using the AGDNS dashboard on a mobile device in portrait, only 8 characters of a devices name is present. This requires the device to be rotated horizontally or device settings to be viewed.

Could the viewable character limit be extended in the trailing white space after the name, or by word wrapping?

**Comment by gGkAC3qfszbdViFkw4Fk9ooS2u** [comment]
Not exclusively covered by #238, but of a similar nature. Left open for now.

**Comment by Batman2814** [comment]
I noticed that as well.

**Comment by Chinaski1** [comment]
FIxed in the latest beta.
