### ISSUE TITLE
Test web page where we can check if Adguard DNS is ON

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardDNS#25]
Test web page like this:
https://www.opendns.com/welcome/

I suggest adding such a test block to the DNS overview page:
https://adguard.com/en/adguard-dns/overview.html

Something like this:
https://monosnap.com/file/MFbYhCTOK0WrPIXlNxJD1mGM9xjS21

**Comment by nkartyshov** [comment]
done

**Comment by ameshkov** [comment]
@nkartyshov it does not work on the russian side:
https://adguard.com/ru/adguard-dns/overview.html

**Comment by Marko321** [comment]
Looks like status is not working. I'm not using Adguard DNS and it's showing me "You are using "Default" Adguard DNS configuration You are using "Family protection" Adguard DNS configuration You are not currently using Adguard DNS".

http://imgur.com/a/uUptE

**Comment by ameshkov** [comment]
@nkartyshov now it works on the ru side and does not work on en side.

Also I guess in @Marko321 case it could work that way because of dns cache.
To fix it you should use random subdomains instead.

Something like this:
```
$(function() {
    $.ajax({
        url: 'https://' + Math.floor(Math.random() * 100000) + '.dnscheck-default.adguard.com/',
        method: 'GET',
        timeout: 3000,
        success: setDnsMode
    });
    $.ajax({
        url: 'https://' + Math.floor(Math.random() * 100000) + '.dnscheck-parental.adguard.com/',
        method: 'GET',
        timeout: 3000,
        success: setDnsMode
    });
});

function setDnsMode(mode) {
    var dnsCheck = $('.dns-check');
    $(dnsCheck).find('.fa').removeClass('fa-times').addClass('fa-check');
    $(dnsCheck).find('.text').hide();
    if (mode == 'default') {
        $(dnsCheck).find('#default-mode').show();
    }
    if (mode == 'family') {
        $(dnsCheck).find('#family-mode').show();
    }
}
```

**Comment by nkartyshov** [comment]
@Marko321 I fixed the problem. Please, check.

**Comment by Marko321** [comment]
@nkartyshov Works perfect now. :)

**Comment by nkartyshov** [comment]
done
