### ISSUE TITLE
Increasing statistics view to 90 days presents overlapped text in Top Companies and Top Destinations

### ISSUE THREAD

**Issue by gGkAC3qfszbdViFkw4Fk9ooS2u** [AdguardTeam/AdGuardDNS#250]
<img width="994" alt="Screen Shot 2022-05-12 at 4 09 30 pm" src="https://user-images.githubusercontent.com/95468948/168003785-3fc15005-5d91-494c-b0da-0f591f09f70a.png">
<img width="396" alt="Screen Shot 2022-05-12 at 4 16 17 pm" src="https://user-images.githubusercontent.com/95468948/168004289-6b8d41ce-8279-4dbc-a331-ee57c4a0458c.png">

**Comment by Chinaski1** [comment]
Fixed in v0.3.1 [beta update](https://adguard-dns.io/en/versions.html)
