### ISSUE TITLE
Host list is not saved in user rules

### ISSUE THREAD

**Issue by Higor-Matos** [AdguardTeam/AdGuardDNS#252]
Hello, I'm encountering problems with saving a list of hosts in user rules.

I made a list of hosts based on lists I found on the internet. I treated them all with [Adguard HostlistCompiler ](https://github.com/AdguardTeam/HostlistCompiler)

And the list was like this after being treated [List Block](https://raw.githubusercontent.com/Higor-Matos/testehosts/main/listblock.txt)

However, I can't save to user rules. When trying to import or edit and save the "save" loops. I've let the loop run for two days to see if it saves, but with no success.

[Here ](https://github.com/Higor-Matos/testehosts/blob/main/configuration.json)I have the lists and [parameters ](https://github.com/Higor-Matos/testehosts/blob/main/exclusions.txt) used in creating mine.
![Captura de tela 2022-05-12 103644](https://user-images.githubusercontent.com/54960146/168087754-794e7e16-afa0-4e10-87fb-d36a9ab3557e.png)

Forgive me for my english, i'm brazilian and i'm learning.

**Comment by gGkAC3qfszbdViFkw4Fk9ooS2u** [comment]
The same issue as #229

**Comment by Higor-Matos** [comment]
Yes, we are having issues saving user rules.  So far I've only had problems when I'm saving a large amount.

**Comment by Higor-Matos** [comment]
> The same issue as #229

Yes, we are having issues saving user rules.  So far I've only had problems when I'm saving a large amount.

**Comment by ameshkov** [comment]
> So far I've only had problems when I'm saving a large amount.

Please note, that the maximum amount of rules in the user rules is 1000 rules.

**Comment by Higor-Matos** [comment]
> > Até agora só tive problemas quando estou economizando muito.
> 
> Observe que a quantidade máxima de regras nas regras do usuário é de 1.000 regras.

would it be possible to add more?

**Comment by Chinaski1** [comment]
Fixed in [v0.3.1](https://adguard-dns.io/en/versions.html) beta update.
