### ISSUE TITLE
Linked IP is not recognising a home internet provider

### ISSUE THREAD

**Issue by gGkAC3qfszbdViFkw4Fk9ooS2u** [AdguardTeam/AdGuardDNS#253]
I'm trying to use AdGuard DNS on a Ubiquiti airCube with a fixed wireless setup.

The airCube's only allow for a single IPV4 address for DNS.

I have set the DNS as below, however AdGuard DNS is telling that it can't be linked for security reasons as my provider is not a home internet provider, which isn't the case.

![image](https://user-images.githubusercontent.com/95468948/168401635-8c9e0b08-25ee-4c0d-8608-b00d185988b5.png)
![image](https://user-images.githubusercontent.com/95468948/168401639-46410078-868e-4ae2-9b6b-0dc7d39346eb.png)

**Comment by ameshkov** [comment]
Could you please send your IP address and the information about your home provider to `devteam@adguard.com`? Please mention this issue in the email.

**Comment by gGkAC3qfszbdViFkw4Fk9ooS2u** [comment]
> Could you please send your IP address and the information about your home provider to `devteam@adguard.com`? Please mention this issue in the email.

Email sent.
