### ISSUE TITLE
AdGuard DNS Family

### ISSUE THREAD

**Issue by jonathanmmm** [AdguardTeam/AdguardDNS#257]
Hello Guys,

I try to find out a website that is blocked by Adguard DNS with Family and shows this message like on 
family.block.dns.adguard.com (which you can see even without adguard dns, so it is not a website to check).

Hope you can help me.

If I make nslookup (windows 10) with examples from https://github.com/AdguardTeam/AdguardDNS/blob/master/Filters/filter.txt
I get 127.0.0.1 as an result, but to let this message work it should point somewhere else I believe.

Also is there a list for Family Protection to see what is in there? I only found smth. like https://github.com/AdguardTeam/AdguardDNS/blob/master/Filters/filter.txt?

**Comment by ameshkov** [comment]
For family protection to work we respond with a CNAME record that points to family.block.dns.adguard.com.

Regarding the list, it works differently, there's a web service used by both AdGuard for Windows and AdGuard DNS, that answers a question if this or that domain is safe for a kid.
