### ISSUE TITLE
Request control?

### ISSUE THREAD

**Issue by Higor-Matos** [AdguardTeam/AdGuardDNS#258]
With plans being limited by DNS server requests, a new impasse arises.

How will the home network administrator have this control? Assuming that I admin put DNS directly on my router and every device that connects to it will be in contact with requests.

Assuming I have a party and have several visitors for a weekend. Therefore, my requests will exceed extremely fast.

Another point, is how Apple and Alexa talk and are noisy with the servers all the time. They make requests all night just by being connected to the network.

I find it interesting to review the limit for orders as it becomes unfeasible.

Example of 1 single Alexa overnight.
![Inkedadguard-dns io_pt_br_dashboard_statistics_query_limit=100 search=amazon cursor=1653586601789%3A19%3A100%3A14959 retention=DAYS_30_LI](https://user-images.githubusercontent.com/54960146/170551912-bc244dd8-59ea-4036-bfa2-9907559bf0a4.jpg)

My house with only 3 residents and 1 alexa. We have pretty normal usage.
![image](https://user-images.githubusercontent.com/54960146/170551624-da0af9db-618b-4364-8e10-3d2223cdf848.png)

**Comment by ameshkov** [comment]
What do you think would be the reasonable limit?

**Comment by Higor-Matos** [comment]
> Qual você acha que seria o limite razoável?

It really is a delicate case.

Each type of user will have an order demand and this demand is not something fixed. I can't measure a good number because I don't have that data. AdguardDNS is in beta, I think the best way out is to capture the average number of requests from betas (with their consent), ask them about usage, number of devices. Gather the data with a survey and thus make a decision on the order numbers.

It is important to analyze competitors too, even though Adguard is a concrete company. Most users are looking for value for money.

It is important to note that the vast majority of common users do not care and do not have the slightest knowledge of DNS. Therefore, a service that limits requests is not so interesting for them;

The number of orders, in my view, fits more in the corporate environment, with attractive plans and it is important to emphasize the importance of a plan with unlimited orders.
