### ISSUE TITLE
[Enhancement] Reduce taps required to access device settings

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardDNS#259]
It currently takes 2 taps to access a devices settings as a hint pops up on the first tap to tell you what tapping the text will do.

It would be nice not to have to tap text twice to access a new page, whether it be by having an information button next to the text or having a tutorial telling a user what each function does.

iOS: 15.6
Browser: Safari

https://user-images.githubusercontent.com/95468948/170688522-b94069d1-27b3-4877-b379-67ca3df2aa70.MOV

**Comment by Chinaski1** [comment]
Fixed in the latest beta update,
