### ISSUE TITLE
adguard DoH returns two values while cloudflare and google return just one

### ISSUE THREAD

**Issue by mflannery** [AdguardTeam/AdGuardDNS#26]
In playing around with DoH i have found that adguard DNS doesn't work as well with cloudflared as cloudflare does (issue #25).  In testing DoH responses I found that adguard DoH returns two values from a query where cloudflare and google return only one (using this as my troubleshooting guide - https://medium.com/@nykolas.z/troubleshooting-dns-over-https-c1e1009d3eb8):

[root@admin ~]# curl "https://dns.google.com/experimental?ct&dns=q80BAAABAAAAAAAAB2V4YW1wbGUDY29tAAABAAE" | strings
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    45  100    45    0     0    300      0 --:--:-- --:--:-- --:--:--   298
example
[root@admin ~]# curl "https://1.1.1.1/dns-query?ct&dns=q80BAAABAAAAAAAAB2V4YW1wbGUDY29tAAABAAE" | strings
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   128  100   128    0     0   1422      0 --:--:-- --:--:-- --:--:--  1422
example
[root@admin ~]# curl "https://dns.adguard.com/dns-query?ct&dns=q80BAAABAAAAAAAAB2V4YW1wbGUDY29tAAABAAE" | strings
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    56  100    56    0     0    339      0 --:--:-- --:--:-- --:--:--   339
example
example

I wonder if this could be the source of my problem in issue #25 ...

Thanks!
Mike

**Comment by ameshkov** [comment]
Sorry for the late reply! The difference is that CF and Google use DNS answer compression.

We're going to enable it on our side as well soon.
