### ISSUE TITLE
Routing issue (should be routed to AMS, instead routed to FRA)

### ISSUE THREAD

**Issue by ijuliank** [AdguardTeam/AdGuardDNS#260]
Tracing route to 94-140-14-49.adguard.com [94.140.14.49]
over a maximum of 30 hops:

  1     1 ms    <1 ms    <1 ms  mijnmodem [192.168.2.254]
  2     7 ms     5 ms     6 ms  (Removed MY IP)
  3    93 ms    80 ms   107 ms  139.156.98.101
  4     *        *        *     Request timed out.
  5     *        *        *     Request timed out.
  6    16 ms    17 ms    25 ms  de-fra02a-rc1-ae-14-0.aorta.net [84.116.130.149]
  7    13 ms    13 ms    13 ms  de-fra05a-ri1-ae-4-0.aorta.net [84.116.137.202]
  8    14 ms    14 ms    14 ms  se-sto01a-ra2-ge-0-1-0-5.aorta.net [213.46.176.38]
  9    12 ms    13 ms    12 ms  94-140-14-49.adguard.com [94.140.14.49]

going to france instead netherlands

**Comment by mnvr1991** [comment]
Hi!
Doens't FRA means Frankfurt?
I'm also located in the Netherlands (near Rotterdam) and being routed to FRA.. 
Never have I been routed to AMS..

**Comment by ijuliank** [comment]
> Hi! Doesn't FRA means Frankfurt? I'm also located in the Netherlands (near Rotterdam) and being routed to FRA.. Never have I been routed to AMS..

yes

**Comment by D13410N3** [comment]
Can you provide additional info, at least we need your ISP

**Comment by mnvr1991** [comment]
> Can you provide additional info, at least we need your ISP

What additional info do you need?
Should I do a trace route to a specific server?

It happens both on my cellular connection (Vodafone) and my home ISP (Ziggo)

**Comment by ameshkov** [comment]
The issue should be resolved now, please check it.

**Comment by mnvr1991** [comment]
> The issue should be resolved now, please check it.

Thanks, but it doesn't seem to work on my local network (Ziggo). 
My cellular connection (Vodafone) routes to Amsterdam.

MacBook Wifi (Ziggo)
<img width="746" alt="Scherm­afbeelding 2022-09-09 om 13 07 04" src="https://user-images.githubusercontent.com/83885255/189337202-7ba6dd1a-8694-43c6-80ba-5b449def9086.png">

MacBook Hotspot iPhone (Vodafone)
<img width="433" alt="Scherm­afbeelding 2022-09-09 om 13 07 30" src="https://user-images.githubusercontent.com/83885255/189337278-999713f9-c453-49ed-b8c3-f9b578eb5cbf.png">

I get the same results with my iPhone, wifi and cellular.
About 2 hours ago, the local connection (Ziggo) got routed to London, but currently keeps routing to Frankfurt again.

**Comment by D13410N3** [comment]
Can you please actual traceroute

**Comment by mnvr1991** [comment]
traceroute to 94.140.14.49 (94.140.14.49), 64 hops max, 52 byte packets
 1  192.168.178.1 (192.168.178.1)  4.681 ms  3.026 ms  3.504 ms
 2  asd-tr0021-cr141-sys.core.as33915.net (213.51.1.123)  16.387 ms  16.951 ms  21.670 ms
 3  asd-tr0021-cr101-be51.core.as33915.net (213.51.7.104)  19.158 ms  18.863 ms  26.577 ms
 4  nl-ams14a-ri1-ae51-0.core.as9143.net (213.51.64.186)  26.028 ms  16.319 ms  19.242 ms
 5  nl-ams14a-ri1-ae28-cdn77.aorta.net (213.46.162.26)  15.802 ms  15.253 ms  16.090 ms
 6  94-140-14-49.adguard.com (94.140.14.49)  13.754 ms  22.083 ms  15.434 ms

<img width="437" alt="Scherm­afbeelding 2022-09-09 om 13 20 56" src="https://user-images.githubusercontent.com/83885255/189339000-5d40baca-138e-43ab-af4a-9ebe96a9b14e.png">

**Comment by ameshkov** [comment]
@mnvr1991 please show the output of this command `traceroute6 2a10:50c0::ad1:ff`

@D13410N3 a small part of AS1136 is still there. Might be IPv6.

**Comment by ameshkov** [comment]
Yeah, that's it. We're trying to resolve this with the peer that's causing it. Unfortunately, they provide no options to change the routes on our side so we have to rely on them to fix the routing.

**Comment by ijuliank** [comment]
its still going to London/Frankfurt, KPN for me

**Comment by D13410N3** [comment]
@ijuliank can you please actualize your traceroute and provide traceroute6 (if your have IPv6)?

**Comment by ijuliank** [comment]
@D13410N3 i have ipv6 yes

Tracing route to dns.adguard.com [2a10:50c0::ad1:ff]
over a maximum of 30 hops:

  1     1 ms     1 ms     1 ms  2a02-a46b-2e5e-1-b2bb-e5ff-fef8-xxxx.fixed6.kpn.net [removed my ip]
  2     6 ms     6 ms     6 ms  2001:67c:2502:f100::2:4c
  3     *      123 ms   123 ms  2001:730:2209:a::d52e:ba26
  4     *        *        *     Request timed out.
  5     8 ms    15 ms     8 ms  2001:730:2200::5474:802c
  6     *        *        *     Request timed out.
  7    18 ms    18 ms    17 ms  uk-lon01c-ri2-lo0-0.v6.aorta.net [2001:730:2900::5474:8027]
  8     *        *        *     Request timed out.
  9    28 ms    27 ms    28 ms  dns.adguard.com [2a10:50c0::ad1:ff]

**Comment by D13410N3** [comment]
@ijuliank I've contacted your ISP, they'll try to fix routing

**Comment by D13410N3** [comment]
@ijuliank @mnvr1991 is this issue resolved?

**Comment by mnvr1991** [comment]
> @ijuliank @mnvr1991 is this issue resolved?

Unfortunately not. Sometimes it routes to Amsterdam with IPv6, but mostly to Frankfurt.


I couldn’t use terminal this time, so here’s a traceroute from my iPhone:
#1
- RTT [ms]: 10.6
- Probe Send Time: 21:01:50
- IP Address: 2001:1c02:151c:a800:4e38:*:*:*
- Hostname: 2001-1c02-151c-a800-4e38-*-*-*.cable.dynamic.v6.ziggo.nl
- TTL: 255
- AS Number: AS33915
- AS Name: Vodafone Libertel B.V.
- Country Name: Netherlands
- Country Code: NL
- Time Zone: Europe/Amsterdam

#2
- Probe Send Time: 21:01:50

#3
- RTT [ms]: 15.6
- Probe Send Time: 21:01:53
- IP Address: 2001:b88:0:d99::1
- Hostname: hvs-rc0002-cr102-ae114-0.core.as9143.net
- TTL: 62
- AS Number: AS33915
- AS Name: Vodafone Libertel B.V.
- Country Name: Netherlands
- Country Code: NL
- Time Zone: Europe/Amsterdam

#4
- RTT [ms]: 27.5
- Probe Send Time: 21:01:53
- IP Address: 2001:b88::159:102
- Hostname: asd-tr0021-cr101-lo10.core.as9143.net
- TTL: 61
- AS Number: AS33915
- AS Name: Vodafone Libertel B.V.
- Country Name: Netherlands
- Country Code: NL
- Time Zone: Europe/Amsterdam

#5
- RTT [ms]: 15.7
- Probe Send Time: 21:01:55
- IP Address: 2001:b88:0:480::2
- Hostname: nl-ams02a-rc2-lag60-2.core.as9143.net
- TTL: 60
- AS Number: AS33915
- AS Name: Vodafone Libertel B.V.
- Country Name: Netherlands
- Country Code: NL
- Time Zone: Europe/Amsterdam

#6
- RTT [ms]: 22.8
- Probe Send Time: 21:01:55
- IP Address: 2001:730:2d00::5474:807c
- Hostname: de-fra05a-ri1-lo0-0.v6.aorta.net
- TTL: 58
- AS Number: AS6830
- AS Name: Liberty Global B.V.
- Country Name: Netherlands
- Country Code: NL
- Time Zone: Europe/Amsterdam

#7
- Probe Send Time: 21:01:55

#8
- RTT [ms]: 24.5
- Probe Send Time: 21:01:58
- IP Address: 2a10:50c0::ad1:ff
- Hostname: dns.adguard.com
- TTL: 54
- AS Number: AS212772
- AS Name: AdGuard Software Limited
- Country Name: Cyprus
- Country Code: CY
- Time Zone: Asia/Nicosia

![98FCACF9-93BF-41F9-9A20-FC7B3E09FA25](https://user-images.githubusercontent.com/83885255/196003855-64d317db-aece-41ea-a31a-e63798789759.jpeg)

**Comment by ijuliank** [comment]
> > @ijuliank @mnvr1991 is this issue resolved?
> 
> Unfortunately not. Sometimes it routes to Amsterdam with IPv6, but mostly to Frankfurt.
> 
> I couldn’t use terminal this time, so here’s a traceroute from my iPhone: #1
> 
> * RTT [ms]: 10.6
> * Probe Send Time: 21:01:50
> * IP Address: 2001:1c02:151c:a800:4e38:_:_:*
> * Hostname: 2001-1c02-151c-a800-4e38-_-_-*.cable.dynamic.v6.ziggo.nl
> * TTL: 255
> * AS Number: AS33915
> * AS Name: Vodafone Libertel B.V.
> * Country Name: Netherlands
> * Country Code: NL
> * Time Zone: Europe/Amsterdam
> 
> #2
> 
> * Probe Send Time: 21:01:50
> 
> #3
> 
> * RTT [ms]: 15.6
> * Probe Send Time: 21:01:53
> * IP Address: 2001:b88:0:d99::1
> * Hostname: hvs-rc0002-cr102-ae114-0.core.as9143.net
> * TTL: 62
> * AS Number: AS33915
> * AS Name: Vodafone Libertel B.V.
> * Country Name: Netherlands
> * Country Code: NL
> * Time Zone: Europe/Amsterdam
> 
> #4
> 
> * RTT [ms]: 27.5
> * Probe Send Time: 21:01:53
> * IP Address: 2001:b88::159:102
> * Hostname: asd-tr0021-cr101-lo10.core.as9143.net
> * TTL: 61
> * AS Number: AS33915
> * AS Name: Vodafone Libertel B.V.
> * Country Name: Netherlands
> * Country Code: NL
> * Time Zone: Europe/Amsterdam
> 
> #5
> 
> * RTT [ms]: 15.7
> * Probe Send Time: 21:01:55
> * IP Address: 2001:b88:0:480::2
> * Hostname: nl-ams02a-rc2-lag60-2.core.as9143.net
> * TTL: 60
> * AS Number: AS33915
> * AS Name: Vodafone Libertel B.V.
> * Country Name: Netherlands
> * Country Code: NL
> * Time Zone: Europe/Amsterdam
> 
> #6
> 
> * RTT [ms]: 22.8
> * Probe Send Time: 21:01:55
> * IP Address: 2001:730:2d00::5474:807c
> * Hostname: de-fra05a-ri1-lo0-0.v6.aorta.net
> * TTL: 58
> * AS Number: AS6830
> * AS Name: Liberty Global B.V.
> * Country Name: Netherlands
> * Country Code: NL
> * Time Zone: Europe/Amsterdam
> 
> #7
> 
> * Probe Send Time: 21:01:55
> 
> #8
> 
> * RTT [ms]: 24.5
> * Probe Send Time: 21:01:58
> * IP Address: 2a10:50c0::ad1:ff
> * Hostname: dns.adguard.com
> * TTL: 54
> * AS Number: AS212772
> * AS Name: AdGuard Software Limited
> * Country Name: Cyprus
> * Country Code: CY
> * Time Zone: Asia/Nicosia
> 
> ![98FCACF9-93BF-41F9-9A20-FC7B3E09FA25](https://user-images.githubusercontent.com/83885255/196003855-64d317db-aece-41ea-a31a-e63798789759.jpeg)

agrees to this one

**Comment by D13410N3** [comment]
Yes, this issue exists again. Unfortunately, transit ISP provider doesn't answer on my e-mails. That's why this vicious triangle "London - Amsterdam - Frankfurt" exists. At this moment I'm not sure that we can resolve this issue promptly.

**Comment by ijuliank** [comment]
![image](https://user-images.githubusercontent.com/64658680/199809180-72e3fd3d-fc14-4eef-8b07-8bcd8c5169d0.png)
for now it seems ok, testing again tommorow

**Comment by ijuliank** [comment]
testing 3rd day, it seems fixed for now, on my side this issue can be closed
