### ISSUE TITLE
Change the DNS provider from vultr.com to cloudflare.com?

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardDNS#261]
@ameshkov 

1. I read the article.
https://www.reddit.com/r/Adguard/comments/8387ye/adguard_dns_very_slow/
That's my first time to know that you use DNS service from vultr.com.
https://www.vultr.com/status/

Are Taiwanese users routed through Singapore or Japan (Tokyo) DNS server if using AdGuard DNS?

Today, I found that the now resolution speed of AdGuard DNS became faster than the past.
Past: 170ms
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/AtWKUYE.png)
</details><br/>

Now: 70ms
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/R2SGQ5b.png)
</details><br/>

What did you improve?

2. And then I'm not sure if Cloudflare.com can provide the DNS service to AdGuard DNS.
https://www.cloudflare.com/dns/

According to the above photo, the DNS resolution speed of cloudflare public DNS is only 10ms, which is really fast!

Cloudflare Global Coverage From an Anycast-Powered Network:
https://www.cloudflarestatus.com
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/Rd6HUdz.png)
</details><br/>

Anycast Network of vultr.com: (Only a few servers. Not good global coverage.)
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/p1pHNrn.png)
</details><br/>

The most important thing...
Cloudflare has a Taiwan server. XD
Well, it's a good thing if AdGuard DNS has a Taiwan server.
Cloudflare DNS also supports IPv6.

Cloudflare Public DNS:
https://1.1.1.1/

IPv4:
one.cloudflare-dns.com     1.1.1.1
two.cloudflare-dns.com     1.0.0.1

IPv6:
2606:4700:4700::1111
2606:4700:4700::1001

It supports both DNS-over-TLS and DNS-over-HTTPS.

Thanks.

**Comment by ameshkov** [comment]
Cloudflare is not a hosting provider unfortunately :(

**Comment by lancelot-moon** [comment]
Is this not the service?
https://www.cloudflare.com/cdn/
https://www.cloudflare.com/plans/pro/

**Comment by ameshkov** [comment]
No, they don't actually "host" servers.

AdGuard actually is already a CloudFlare customer.
