### ISSUE TITLE
Block Button in Query Log Override all user rules in settings

### ISSUE THREAD

**Issue by DavidTai780** [AdguardTeam/AdGuardDNS#265]
Step to produce the situation in Adguard DNS
1. Get some of the rules in user rules at settings.
2. Click any of the block button at the query log page to quickly block a domain.
![Screenshot 2022-05-28 222357](https://user-images.githubusercontent.com/26398101/170829591-6a561814-7bd9-4ec7-aa0e-3abd52ef6ce4.png)

And _**all your rules**_ in user rules will be overridden/replaced with 1 rule you had just added by clicking the block button on the query log page.
![Screenshot 2022-05-28 222100](https://user-images.githubusercontent.com/26398101/170829607-feccadf9-a62f-48a8-8cd7-346de35b6f8f.png)

**Comment by Chinaski1** [comment]
Fixed in 0.3.1 beta update
