### ISSUE TITLE
Clearing logs and statistics takes an excessive amount of time 

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardDNS#266]
When clearing logs and statistic, it seems to take an excessively long time.
In the below video, it took approximately 5 minutes for the change to appear on the dashboard.

1. Access server settings
2. Tap clear logs or clear statistics

https://user-images.githubusercontent.com/95468948/170839473-44bd62c0-94c6-4f53-8dc8-680d3b7a7b5c.MOV

It would be great if this could be seemingly instantaneous.

**Comment by ijuliank** [comment]
Yes

**Comment by gork7777** [comment]
Duplicate: https://github.com/AdguardTeam/AdGuardDNS/issues/228
