### ISSUE TITLE
Retain the set hours/days for queries shown in dropdown menu

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardDNS#267]
When setting the amount of hours/days for queries to be shown, every time you refresh the page, it defaults back to 24 hours.

It would be nice if there was some way to default to a set hours/days without having to change it every time the page refreshed.

https://user-images.githubusercontent.com/95468948/170909329-4a76f195-785f-465f-88ed-38c74497eb95.MOV

**Comment by Chinaski1** [comment]
Fixed in one of the updates.
