### ISSUE TITLE
Dashboard takes excessively long to load up

### ISSUE THREAD

**Issue by gGkAC3qfszbdViFkw4Fk9ooS2u** [AdguardTeam/AdGuardDNS#269]
Every time I refresh the dashboard, the dashboard takes approximately 15seconds to present the statistics.
The page itself loads in ~3 seconds consistently.

This is reproducible on a mobile data connection of 140/20, and a wifi connection of 100/20.
An iPhone with Safari, and MBP with Safari was tested.

15 seconds feels exceedingly too long to wait for a dashboard to present statistics, when a Nextcloud instance running on a RPi3b+ takes considerably less time than that.

**Comment by ameshkov** [comment]
Oh, private relay :(
