### ISSUE TITLE
Adguard DNS Blocks Ibotta/Amazon 

### ISSUE THREAD

**Issue by Ryan-Goldstein** [AdguardTeam/AdguardDNS#269]
### Steps to reproduce
1. Open the Ibotta app and navigate to Amazon.
2. Click 'Shop' next to any any of the categories.

### Expected behavior
It should jump to the Amazon app, passing along the Ibotta affiliate information to credit the user for that purchase.

### Actual behavior
A pop-up appears: "Oops! Something went wrong. Please try again later."

Disabling DNSCloak, or switching to a different DNS provider in DNSCloak, like Cloudflare, avoids this issue, and the expected behavior as above occurs.

<details><summary>Screenshot:</summary>

![photo apr 15 4 56 02 pm](https://user-images.githubusercontent.com/8300089/38783290-fc3bad5e-40cd-11e8-9f51-c9effbe2d77d.png)

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| adguard-dns in DNSCloak iOS app (176.103.130.130)
| How did you setup DNS configuration:| DNSCloak iOS app
| Device model:| iPhone 7
| Operating system and version:| iOS 11.3

**Comment by Alex-302** [comment]
I can't install Ibotta on my device, even if region is changed to USA.
Do you see requests with IP in the log of DNSCloak?

@AdamWr could you please check it?

**Comment by AdamWr** [comment]
Unfortunately this app is not available in my region, so I can't check it.

**Comment by Ryan-Goldstein** [comment]
I ran a side by side test trying to load Amazon through Ibotta using Adguard, then using Cloudflare (1.1.1.1), and assessing the DNSCloak logs, I believe the culprit is Adguard's blocking of brahe.apptimize.com and/or t.singular.net.

I'm sure those domains are likely affiliated with advertising, but one or both appears to be required to be able to get credit for shopping on Amazon through Ibotta. So unless/until this is resolved, I have to stop using Adguard to be able to get credit for shopping on Amazon through Ibotta.

If you make any changes to Adguard, I'd be happy to run these tests again to see whether this functionality is restored.

Thanks!

**Comment by Alex-302** [comment]
@Ryan-Goldstein what about log?
Could you install AdGuard for test? It can to show blocked domains.

**Comment by Ryan-Goldstein** [comment]
If I'm not mistaken, that would require AdGuard Pro, right? I haven't purchased that app.

If it helps, I've attached logs from DNSCloak from both tests. It doesn't show what was blocked or not, but I found that this makes it easy to identify whether resolution is being blocked:

https://digwebinterface.com/?hostnames=brahe.apptimize.com&type=&useresolver=8.8.4.4&ns=self&nameservers=176.103.130.130%0D%0A1.1.1.1

**Comment by Alex-302** [comment]
Ok, excluded 
`apptimize.com` and `brahe.apptimize.com`
I see a lot of domains with ip 127.0.0.1 in
Adguard.txt
Cloudflare.txt
for example apple.com and inbox.google.com Is it your own dns config?

**Comment by Ryan-Goldstein** [comment]
That's just how DNSCloak handles DNS resolution - it runs a local resolver at 127.0.0.1 on the device to be able to cache records locally when appropriate. That's why I'm using digwebinterface to test how domains will actually resolve using each resolver.

I don't see brahe.apptimize.com resolving properly yet using [this](https://digwebinterface.com/?hostnames=brahe.apptimize.com&type=&useresolver=8.8.4.4&ns=self&nameservers=176.103.130.130%0D%0A1.1.1.1) - when would that exclusion take effect?

**Comment by Alex-302** [comment]
> when would that exclusion take effect?

maybe after 1-3 hours. Not sure.

**Comment by Ryan-Goldstein** [comment]
Maybe @Ibotta can chime in to help?

**Comment by Alex-302** [comment]
I hope)

**Comment by ameshkov** [comment]
Please reopen if there's new information.
