### ISSUE TITLE
question

### ISSUE THREAD

**Issue by ibksturm** [AdguardTeam/AdguardDNS#270]
hi there

i'm back, question, did you plan to connect adguarddns over DoH? 

Greets

Andi

**Comment by ameshkov** [comment]
Sure, we're planning to support both DoH and DoT. Can't give you an ETA yet, though.

**Comment by lucasban** [comment]
Is there anything I can follow to be notified when an ETA is announced or this feature is available?

**Comment by ameshkov** [comment]
> Is there anything I can follow to be notified when an ETA is announced or this feature is available?

Not yet, the issues in this repo are in chaos, I'll try to bring them in order soon.
