### ISSUE TITLE
Add ability to block recently created domains

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdGuardDNS#272]
Most phishing domains are generally newly created so we need to add the ability to block them immediately after creation.

**Comment by Wladefant** [comment]
should be implemented now

![image](https://github.com/AdguardTeam/AdGuardDNS/assets/79611093/63e75350-3bea-4ad5-af25-8dc293478e56)

**Comment by TPS** [comment]
Thanks very much!
