### ISSUE TITLE
7plus + Freeview Blocked on Sony TV

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdguardDNS#273]
With AdGuard DNS, our Sony TV which uses [Freeview Plus](http://www.freeview.com.au/freeview-plus/) has an issue launching [7plus](http://about.7plus.com.au/), as it is completely blocked. Using another DNS on the TV (Google, 1.1.1.1, ISP) resolves the issue.

Some particular domain blocked by AdGuard DNS is preventing 7plus from working.

### Steps to reproduce

1. Use a Sony KD-55X7000E
2. Go to any channel provided by Channel 7
3. Launch 7plus by pressing the red button /OR/
4. Launch Freeview and try to watch a Channel 7 TV Show

### Expected behavior

TV launches into 7plus by pressing the red button /OR/ a black screen appears with a spinning wheel to start viewing the video.

### Actual behavior

Nothing launches pressing red and the TV is stuck /OR/ a black screen appears and gets soft-locked as no wheel appears and no video ever shows.

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| Default
| How did you setup DNS configuration:| Router, for IPv4 and IPv6
| Device model:| Sony KD-55X7000E

**Comment by ameshkov** [comment]
@planet0 is there any option to record a DNS requests log?

**Comment by planet0** [comment]
@ameshkov Unfortunately not. Thankfully the standalone app was updated as well, so there is a workaround now at the very least.

Seems to be only related to 7plus and something they are specifically requesting that is being blocked.

I would normally ignore or not report such a specific issue, however the scope of the issue is quite large, as any Australian with a TV who decides to use AdGuard DNS will be blocked access to one of three major TV networks here for streaming.

**Comment by planet0** [comment]
Don't think there's going to be anything that can be done for the moment, going to close this issue.
