### ISSUE TITLE
Renaming a device has become nearly impossible

### ISSUE THREAD

**Issue by gGkAC3qfszbdViFkw4Fk9ooS2u** [AdguardTeam/AdGuardDNS#274]
Below is a screen recording of me trying to rename the device to 'MacBook Pro Mojave'.

As you can see, the letters keep deleting inconsistently as they're getting typed.

This is reproducible on iOS and macOS.

https://user-images.githubusercontent.com/95468948/172353784-4ec05239-59de-4149-96f1-bef094d29f0c.MOV

**Comment by Chinaski1** [comment]
Hello there!

I cant reproduce your issue, can you specify which browser are you using?

**Comment by Chinaski1** [comment]
Not reproduced

You need to change the name and update the page.
But in the near future, we plan to add `Save` button, so changing the settings will be more obvious.
