### ISSUE TITLE
graph.instagram.com blocking instagram

### ISSUE THREAD

**Issue by Higor-Matos** [AdguardTeam/AdGuardDNS#275]
After the new instagram update, I noticed that when I block the graph.instagram.com domain, instagram doesn't communicate anymore.

**Comment by Higor-Matos** [comment]
i.instagram.com also prevents access to instagram

**Comment by ameshkov** [comment]
Yep, unfortunately, that's how Instagram works. It loads both ads metadata and legitimate content from the same domain.
