### ISSUE TITLE
ru.yandex.weatherplugin

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardDNS#275]
@adguard-bot commented on [Wed Apr 18 2018](https://github.com/AdguardTeam/AdguardFilters/issues/14941)

### Issue URL (Incorrect Blocking)
[https://play.google.com/store/apps/details?id=ru.yandex.weatherplugin&hl=ru](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dru.yandex.weatherplugin%26hl%3Dru)
### Comment
> При включении DNS, в Яндекс.Погода не показывает КАРТУ осадков.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/huZshah.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/eX1n914.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 7.0
AdGuard version: | 2.11.81
AdGuard mode: | proxy
Filtering quality: | High-speed
HTTPS filtering: | enabled
Filters: | Russian,<br>English,<br>Spyware,<br>Social media,<br>Mobile Ads

---

@Alex-302 commented on [Thu Apr 19 2018](https://github.com/AdguardTeam/AdguardFilters/issues/14941#issuecomment-382861518)

Не повторяется.
@vozersky проверь у себя.

---

@sergii333 commented on [Sat Apr 21 2018](https://github.com/AdguardTeam/AdguardFilters/issues/14941#issuecomment-383300169)

Повторяется, если вкл. DNS

https://prnt.sc/j88ohi

---

@vozersky commented on [Tue Apr 24 2018](https://github.com/AdguardTeam/AdguardFilters/issues/14941#issuecomment-383864631)

> Повторяется, если вкл. DNS
> https://prnt.sc/j88ohi

@Alex-302  у меня то же самое

---

@Alex-302 commented on [Wed Apr 25 2018](https://github.com/AdguardTeam/AdguardFilters/issues/14941#issuecomment-384250377)

@vozersky без фильтров, с DNS тоже? Заскринь заблокированные домены и попробуй поисключать.

---

@sergii333 commented on [Wed Apr 25 2018](https://github.com/AdguardTeam/AdguardFilters/issues/14941#issuecomment-384253196)

http://prntscr.com/j9wh7a
dns://mc.yandex.ru/  - надо в исключения)

---

@sergii333 commented on [Wed Apr 25 2018](https://github.com/AdguardTeam/AdguardFilters/issues/14941#issuecomment-384257143)

@@||mc.yandex.ru$app=com.adguard.dns

---

@Alex-302 commented on [Fri Apr 27 2018](https://github.com/AdguardTeam/AdguardFilters/issues/14941#issuecomment-384960428)

~Ок, добавил.~

---

@Alex-302 commented on [Fri Apr 27 2018](https://github.com/AdguardTeam/AdguardFilters/issues/14941#issuecomment-384960588)

не, не добавил

---

@Alex-302 commented on [Fri Apr 27 2018](https://github.com/AdguardTeam/AdguardFilters/issues/14941#issuecomment-384960769)

@vozersky посмотри у себя, что помогает.

---

@vozersky commented on [Fri Apr 27 2018](https://github.com/AdguardTeam/AdguardFilters/issues/14941#issuecomment-385021115)

@Alex-302 я вообще не вижу в логе ничего заблокированного

---

@Alex-302 commented on [Sat Apr 28 2018](https://github.com/AdguardTeam/AdguardFilters/issues/14941#issuecomment-385153888)

@vozersky т.е. у тебя именно DNS ломает, ничего при этом не блокируя?

---

@vozersky commented on [Sat Apr 28 2018](https://github.com/AdguardTeam/AdguardFilters/issues/14941#issuecomment-385181533)

@Alex-302 да

---

@Alex-302 commented on [Sat Apr 28 2018](https://github.com/AdguardTeam/AdguardFilters/issues/14941#issuecomment-385190131)

@vozersky наверное DNS перетащить надо

**Comment by vozersky** [comment]
@nkartyshov pls assist

**Comment by ameshkov** [comment]
Ребят, ну мы не можем взять и глобально разблокировать `mc.yandex.ru`, так что проблема не очень решаемая.
