### ISSUE TITLE
DNS not using the nearest server in Canada

### ISSUE THREAD

**Issue by Dynasty-Dev** [AdguardTeam/AdGuardDNS#276]
Hello, I'm located in toronto canada and I can see that you have servers there however I am being connected to the server all the way in germany

**Comment by D13410N3** [comment]
Hello.
Can you please send traceroute-output to address 94.140.14.14 ?

**Comment by Dynasty-Dev** [comment]
> Hello. Can you please send traceroute-output to address 94.140.14.14 ?

Hello, here is the traceroute output to 94.140.14.14



traceroute to 94.140.14.14 (94.140.14.14), 30 hops max, 60 byte packets
 1  192.168.8.1 (192.168.8.1)  3.458 ms  3.597 ms  3.520 ms
 2  10.11.10.137 (10.11.10.137)  4.840 ms  4.176 ms  4.867 ms
 3  * * *
 4  * * *
 5  tcore4-toronto63_37.net.bell.ca (64.230.59.196)  21.901 ms  22.294 ms tcore4-toronto21_34.net.bell.ca (64.230.59.192)  18.223 ms
 6  * * *
 7  tcore3-chicagocp-bundle-ether15.net.bell.ca (142.124.127.96)  17.670 ms tcore4-chicagocp-bundle-ether15.net.bell.ca (142.124.127.174)  22.771 ms  21.625 ms
 8  bx6-chicagodt_0-7-0-0.net.bell.ca (64.230.79.87)  14.547 ms  17.564 ms  17.452 ms
 9  xe-7-1-0-xcr1.chg.cw.net (195.2.14.25)  15.948 ms  15.963 ms  15.943 ms
10  195.2.31.6 (195.2.31.6)  109.655 ms  109.629 ms  109.149 ms
11  et-10-3-0-xcr1.ptl.cw.net (195.2.24.242)  105.102 ms  108.481 ms  108.160 ms
12  ae44-pcr1.fis.cw.net (195.2.16.229)  106.738 ms  107.012 ms  110.404 ms
13  ae0-tcr1.fis.cw.net (195.2.30.73)  105.851 ms  108.429 ms  109.409 ms
14  62.208.195.138 (62.208.195.138)  102.170 ms  102.382 ms  105.334 ms
15  dns.adguard.com (94.140.14.14)  102.272 ms  105.225 ms  105.184 ms

**Comment by Chinaski1** [comment]
Hello there!

AdGuard DNS uses [Anycast](https://adguard-dns.io/en/blog/anycast-and-bgp-how-adguard-dns-serves-millions-of-queries.html) technology so we can't manage traffic routing 100% of the time.

At this point, we're compiling problems in internal list with the possibility of their correction in nearest future.
Please provide following information via email to support@adguard.com (also share a link to this issue on GitHub):

1) Your IP address: https://adguard.com/en/test.html
2) ASN. 
3) ISP name.
4) DNS server location: https://adguard.com/en/test.html

I am closing this task as it goes to the internal list of routing issues.
