### ISSUE TITLE
'Reconnect device' scrolls to the bottom of next page

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardDNS#278]
When tapping the 'Reconnect device' button, instead of going to the top of the next page, it seems to go to the bottom.

https://user-images.githubusercontent.com/95468948/173693044-2c4c75e0-5dd5-4370-b741-0bdc8bb62266.MOV

**Comment by Chinaski1** [comment]
The issue is fixed in the latest update.
