### ISSUE TITLE
cultofmac.com is unresolved

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/AdguardDNS#278]
Original issue - https://github.com/AdguardTeam/AdguardFilters/issues/16380
>https://www.cultofmac.com won’t load when using the AdGuard DNS server. When I pick something else the site loads just fine.

### Steps to reproduce

1. Go here - https://www.cultofmac.com/

### Expected behavior

Website should works

### Actual behavior

Website is unresolved

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29142494/40380719-2b70383a-5dfa-11e8-8087-23f6ce00a26d.png)
![image](https://user-images.githubusercontent.com/29142494/40380929-a191a436-5dfa-11e8-8479-badc85bd96d0.png)

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| 176.103.130.130
| How did you setup DNS configuration:| System
| Device model:| -
| Operating system and version:| Windows/iOS

**Comment by ameshkov** [comment]
Fixed

**Comment by ameshkov** [comment]
We'll need some time to rebuild the filters and reload the cache
