### ISSUE TITLE
my5.tv - videos won't play

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardDNS#28]
For instance:
https://www.my5.tv/celebrity-big-brother/season-11/episode-14

**Comment by Alex-302** [comment]
Can't reproduce with British VPN.

**Comment by ameshkov** [comment]
@Alex-302 are you sure AG DNS works through that VPN?

**Comment by Alex-302** [comment]
No... How can I check this site?

**Comment by ameshkov** [comment]
Open doubleclick.net:)

**Comment by Alex-302** [comment]
It doesn't blocked with my VPN(Hola extension).

**Comment by ameshkov** [comment]
@nkartyshov advise something for @Alex-302 to test such geo-restricted cases

**Comment by Alex-302** [comment]
Still can't reproduce with privateinternetaccess.com VPN. Checked both DNS.
With Adguard for windows with enabled parental control it also works.

**Comment by sandybeachit** [comment]
I was able to play the videos perhaps it's all ok and best to close this one?

**Comment by ameshkov** [comment]
Yep, thank you
