### ISSUE TITLE
Request Limit = "shot in the foot"?

### ISSUE THREAD

**Issue by Higor-Matos** [AdguardTeam/AdGuardDNS#282]
###  Great update!

![image](https://user-images.githubusercontent.com/54960146/174866579-09abc3d6-242b-4417-8dad-30a9f4991811.png)

However, limiting plans by number of requests is still something to think about. The number of requests is too fluctuating to parameterize, you never know when we will receive visits or when we will use them more. Vendors like Apple and Amazon are extremely noisy, not to mention smart home appliances. In my opinion, there is not a good number for the limit of requests in the personal field. Perhaps enterprise-oriented DNS will better handle this limitation. However, in my opinion, putting plans with request limits is a "shot in the foot" to drive users away.

![image](https://user-images.githubusercontent.com/54960146/174867766-b7a2b03b-f4ed-4295-a58f-2525ec31bf8d.png)

We've discussed this here and come back again https://github.com/AdguardTeam/AdGuardDNS/issues/258

I recommend seeing the market, analyzing competitors. As much as Adguard is a consolidated company with high visibility in the market. It is necessary to verify the market viability.

Ahh, and I never get tired of asking. And what about the betas? hahah

_Anyway, I've been following Adguard for a long time and I'm a big user of almost every product. Great job! I'm a programmer, I'm only 20 years old. Who knows, maybe one day I can work with Adgurad._

**Comment by ameshkov** [comment]
Thank you for the good words!

We plan to have some limits anyway, but we try to take noisy devices into account and have a comfortable requests limit. The 3M limit is probably not final, we'll reassess it once again before the release. There's a chance that the limit will be increased.
