### ISSUE TITLE
Integrate squidblacklist.org lists

### ISSUE THREAD

**Issue by snhv** [AdguardTeam/AdguardDNS#282]
Hi, the lists from squidblacklist.org (ads, malware) are well-maintained and available for free on filterlists.com
I suggest we integrate them into the simplified domain list. Thanks.

**Comment by dfmcvn** [comment]
+1

**Comment by ameshkov** [comment]
It's against their license :(

**Comment by ameshkov** [comment]
But worry not, the self-hosted AdGuard DNS server will be published in coming month and you'll be able to use whichever filters/hosts you want there.
