### ISSUE TITLE
Self-hosted AdGuard DNS software

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardDNS#283]
## Short checklist

* [x] Switch to CoreDNS instead of the current scheme
* [x] Prepare an admin server that provides a simple REST API to manage the DNS server instance
* [x] Front-end code
* [ ] Deb/rpm packages and the installation script

**Comment by snhv** [comment]
Will it support wildcard for domain filtering?

**Comment by ameshkov** [comment]
Yep

**Comment by snhv** [comment]
It's great news that linux is put in priority. Guess the timing of the release will now depend on how far Russia goes in the World Cup. Good luck!

**Comment by ameshkov** [comment]
> It's great news that linux is put in priority. Guess the timing of the release will now depend on how far Russia goes in the World Cup. Good luck!

If it goes far, this will postpone the release for sure. The good news is that this is a fantastical scenario so you have nothing to worry about:). Thank you!

**Comment by JamesXatu2** [comment]
I don't know much about the scripts, but to install it I did this in bash on 64-bit architecture and I made this script:

```
#!/bin/sh

curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash - 

sudo apt-get install -y nodejs 

curl https://dl.google.com/go/go1.11.1.linux-amd64.tar.gz 

tar -C /usr/local -xzf go$VERSION.$OS-$ARCH.tar.gz

git clone https://github.com/AdguardTeam/AdguardDNS

cd AdguardDNS && make
```


What do you think about it?

**Comment by dfmcvn** [comment]
> curl https://dl.google.com/go/go1.11.1.linux-amd64.tar.gz 

you should use `curl -O https://dl.google.com/go/go1.11.1.linux-amd64.tar.gz ` or `wget https://dl.google.com/go/go1.11.1.linux-amd64.tar.gz
`

**Comment by hmage** [comment]
@JamesXatu2 

For most users, downloading a single binary is the recommended way -- we've published the guides that cover most use cases on the [Wiki](https://github.com/AdguardTeam/AdguardDNS/wiki).

We're planning on releasing new binaries soon, so there should be less pressure on building from sources -- building from sources is documented in README.md as well.

Is that not sufficient information? What would you like to see?

**Comment by JamesXatu2** [comment]
@hmage 

Nothing, it is perfect as it is, indeed, I congratulate you for your magnificent work! I wrote my script for those who wanted to compile their track and always have the latest version, at least, I came back very useful and returns after each of your commits, maybe it can also serve others!
