### ISSUE TITLE
Add important lists

### ISSUE THREAD

**Issue by Higor-Matos** [AdguardTeam/AdGuardDNS#283]
Hi, I think these lists would add a lot to Adguard:

### [GoodbyeAds](thub.com/jerryn70/GoodbyeAds):

![174871209-0482d86b-7e70-499c-b228-1bb5bb003116 (1)](https://user-images.githubusercontent.com/54960146/174871804-ed98611b-e13e-489d-8537-8e7c9165d100.png)

![image](https://user-images.githubusercontent.com/54960146/174869882-80fdc3b2-b205-4015-9979-d187bcc7e342.png)

> [Block list of annoying smartphone ads like Xiaomi Adblock & Samsung Adblock list and Malware list](https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Hosts/GoodbyeAds.txt)

![image](https://user-images.githubusercontent.com/54960146/174870407-0d8aa44b-378f-45df-87b3-29ad9ef68514.png)

> [Youtube ad blocking list. It shouldn't work 100% as we already know that video ads cannot be blocked at DNS level. But it's already a step forward.](https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Extension/GoodbyeAds-YouTube-AdBlock.txt)

![image](https://user-images.githubusercontent.com/54960146/174870825-4400b284-eb54-4928-b881-895f2437ccef.png)

> [Spotify Ad Block List. I confess that I would like to try this one because it caught my attention. However, I have no means to try at home. But I emphasize the feasibility to verify results.](https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Extension/GoodbyeAds-Spotify-AdBlock.txt)

### [StevenBlack](https://github.com/StevenBlack)

![image](https://user-images.githubusercontent.com/54960146/174871448-6ec4710b-bc62-4406-956a-51f08c536c7f.png)

This repository allows many variations, paying attention to it is essential

![image](https://user-images.githubusercontent.com/54960146/174872146-e669a3c0-8a16-4846-a2b7-a5556c596d50.png)

> [Unified hosts + fakenews + gambling: Unified hosts + fakenews + gambling](https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling/hosts)

![image](https://user-images.githubusercontent.com/54960146/174872331-215e1e0d-370f-4e0f-92d7-166e6ca66958.png)

And as private as adult site block lists are, I've already caught a few without blocking. Checking this list is a good alternative.

> [Unified hosts + porn](https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/porn-social/hosts)

![image](https://user-images.githubusercontent.com/54960146/174872688-c5bb54fe-061b-428f-a5d7-8cc44b87da73.png)

**Comment by ameshkov** [comment]
Please check if there're issues opened here about hose lists:
https://github.com/AdguardTeam/HostlistsRegistry

If there're, please upvote them.
