### ISSUE TITLE
Is the white box around hovered over statistics intended?

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardDNS#285]
Hi,

In the below screen recording a white box is displayed to indicate which portion of the statistics is being hovered over with the pointer.

https://user-images.githubusercontent.com/95468948/175232303-509e66a3-2427-43fa-98dc-7d98f491cf41.mov

When hovering over other items in the dashboard a much darker grey is used to highlight the area being hovered over which feels much more natural.
<img width="1106" alt="Screen Shot 2022-06-23 at 4 43 23 pm" src="https://user-images.githubusercontent.com/95468948/175232865-121c12bf-bf6c-428b-8b22-8fcbc6fef7e6.png">

Was the white colour intended when highlighting statistics?

**Comment by Chinaski1** [comment]
Thanks, that seems to be a bug in the dark theme. We'll fix it in the next update
