### ISSUE TITLE
www.hkjc.com is not resolved with AdGuard DNS

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardDNS#286]
@adguard-bot commented on [Sun Jun 19 2022](https://github.com/AdguardTeam/AdguardFilters/issues/122247)

### Issue URL (Incorrect Blocking)
 [http://www.hkjc.com](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Fwww.hkjc.com)
### Comment
> Cannot browse www.hkjc.com, using AdGuard DNS (default with ad filtering).

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/pgCWNr3.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/oBL2wSt.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard/AdGuard Pro for iOS v4.4.0
Browser: | Safari
DNS filtering: | server: `AdGuard DNS `<br>filters: `AdGuard DNS Filter List`
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base, <br/>AdGuard Mobile Ads, <br/>EasyList, <br/>Peter Lowe's Blocklist<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection, <br/>EasyPrivacy, <br/>Fanboy's Enhanced Tracking List<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances, <br/>Fanboy's Annoyances, <br/>Web Annoyances Ultralist, <br/>Adblock Warning Removal List, <br/>I don't care about cookies, <br/>EasyList Cookie List, <br/>Dandelion Sprout's Annoyances List<br/><br/><b>Security:</b><br/>NoCoin Filter List<br/><br/><b>Other:</b><br/>AdGuard DNS<br/><br/><b>Language-specific:</b><br/>AdGuard Chinese, <br/>EasyList China, <br/>CJX's Annoyances List, <br/>ChinaList+EasyList
Other extensions used: | Nil

---

@jellizaveta commented on [Fri Jun 24 2022](https://github.com/AdguardTeam/AdguardFilters/issues/122247#issuecomment-1165525713)

All works fine on my end. @AdguardTeam/filters-maintainers please, take a look.

**Comment by ameshkov** [comment]
Cannot reproduce
