### ISSUE TITLE
Update Vietnamese domain filter

### ISSUE THREAD

**Issue by snhv** [AdguardTeam/AdguardDNS#286]
Hi,

Can you replace the following domains from the "Vietnamese" section of the "Simplified domain names filter" list:

||f37.img.vnecdn.net^
||f38.img.vnecdn.net^
||raovat.vnecdn.net^
||shop.vnecdn.net^
||raovat.vnexpress.net^
||shop.vnexpress.net^
||imgshop.vnexpress.net^

with the following domains:
||*shop.vnecdn.net^
||*raovat.vnecdn.net^

These above are adserving domains of VnExpress network sites (most notably vnexpress.net - the most popular online news site in Vietnam). They regularly change the adserving domains so we need to monitor and update accordingly.

Thank you.

**Comment by Alex-302** [comment]
Done.
