### ISSUE TITLE
www.alamo.com is not resolved with AdGuard DNS

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardDNS#287]
@adguard-bot commented on [Sun Jun 26 2022](https://github.com/AdguardTeam/AdguardFilters/issues/122802)

### Issue URL (Incorrect Blocking)
 [https://www.alamo.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.alamo.com%2F)
### Comment
> Alamo (as in the screenshots) “servers can’t reach/found”, tried only with Safari
> 
> Also VirginAtlantic.com website, which I tried both with safari and chrome, immediately after turn-off AdGuard works well.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/WjGmIhR.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/2hbrcO8.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard/AdGuard Pro for iOS v4.4.0
Browser: | Safari
DNS filtering: | server: `https://dns.adguard.com/dns-query`<br>
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection

**Comment by Chinaski1** [comment]
That issue is not reproduced on my side.

If it still happens, please connect to AdGuard DNS and go to [this page](https://adguard.com/en/test.html) and send the test results with a screenshot.
