### ISSUE TITLE
I've figured out how to get Windows 11 to recognise AdGuard DNS as encryptable, but I don't know which folder/page to add such info to

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdGuardDNS#288]
Windows 11's "Network and Internet" settings added an option to set DNS servers as encrypted. But by default, they only made it possible to turn on for the IP addresses used by Google DNS, CloudFlare DNS, and Quad9, which can be displayed with `netsh dns show encryption` in PowerShell. I have however figured out how to get it to recognise public AdGuard DNS IPs too.

The .reg file content that would've enabled it, from what I can tell:
<details>

```
;Allows Windows 11's (Not earlier Windows versions) network settings to recognise AdGuard DNS IPs as being possible to turn on encryption for.
;Users probably won't need to use both IPv4 connection addresses in their settings, as they'd both lead to the same DoH address.

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters\DohWellKnownServers\94.140.14.14]
"Template"="https://dns.adguard.com/dns-query"

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters\DohWellKnownServers\94.140.15.15]
"Template"="https://dns.adguard.com/dns-query"

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters\DohWellKnownServers\2a10:50c0::ad1:ff]
"Template"="https://dns.adguard.com/dns-query"

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters\DohWellKnownServers\2a10:50c0::ad2:ff]
"Template"="https://dns.adguard.com/dns-query"

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters\DohWellKnownServers\94.140.14.140]
"Template"="https://dns-unfiltered.adguard.com/dns-query"

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters\DohWellKnownServers\94.140.14.141]
"Template"="https://dns-unfiltered.adguard.com/dns-query"

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters\DohWellKnownServers\2a10:50c0::1:ff]
"Template"="https://dns-unfiltered.adguard.com/dns-query"

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters\DohWellKnownServers\2a10:50c0::2:ff]
"Template"="https://dns-unfiltered.adguard.com/dns-query"

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters\DohWellKnownServers\94.140.14.15]
"Template"="https://dns-family.adguard.com/dns-query"

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters\DohWellKnownServers\94.140.15.16]
"Template"="https://dns-family.adguard.com/dns-query"

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters\DohWellKnownServers\2a10:50c0::bad1:ff]
"Template"="https://dns-family.adguard.com/dns-query"

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters\DohWellKnownServers\2a10:50c0::bad2:ff]
"Template"="https://dns-family.adguard.com/dns-query"
```

</details>

What the settings menu looks like, complete with `94.140.14.140` having encryption turned on, which can't be done on stock Windows 11 stable installations (In this case, it was accomplished with direct registry editing instead of a .reg file. I can take a UK English screenshot on request):

<details>

![image](https://user-images.githubusercontent.com/22780683/176100504-02bc4c51-dcdf-493d-bb2b-ef752b28aed8.png)

</details>

Ideally, this kind of info would've been suited for https://adguard-dns.io/en/public-dns.html → "Method 2: Configure AdGuard DNS manually" → Windows 11; but it doesn't seem to be part of the main Knowledge Base at the time of writing, nor are there any pages in the actual Knowledge Base that are anywhere nearly as suited for it.

**Comment by ameshkov** [comment]
Yeah, this probably should be a part of the DNS configuration instructions, not the knowledge base.

**Comment by ameshkov** [comment]
We'll have to postpone this until the update is out then.

**Comment by DandelionSprout** [comment]
I still feel the OP stuff is worth mentioning, since seemingly no relevant search results on Google seem to demonstrate any such registry fix, thus AdGuard would've shared new info with the world.

**Comment by Chinaski1** [comment]
Added at v[2.4 update](https://adguard-dns.io/en/versions.html)

**Comment by Chinaski1** [comment]
The instruction `How to configure personal DNS manually` was added at v[2.4 update](https://adguard-dns.io/en/versions.html)
