### ISSUE TITLE
Pandora Plus

### ISSUE THREAD

**Issue by techrayz** [AdguardTeam/AdGuardDNS#289]
Pandora Plus streaming music paid subscribers are given the option of searching for and listening to any song they want as long as they watch a video advertisement. It appears AdGuard public DNS is blocking the ability to watch the advertisement, which doesn't allow me to listen to the song I searched for. The Pandora app just sits there without movement when I try to play a song by searching for the title.

This makes the Pandora app useless for Pandora Plus subscribers. Could the public filter be modified to allow ads in the Pandora Android/iOS app for Pandora Plus subscribers?

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdGuardSDNSFilter #987](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/987) via [**ZenHub**](https://www.zenhub.com/)
