### ISSUE TITLE
kinovo.me - HD video player is broken

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardDNS#29]
Source:
https://forum.adguard.com/index.php?threads/adguard-%D0%9F%D0%A0%D0%9E-%D0%B4%D0%BB%D1%8F-ios-v1-0-%D0%B1%D0%B5%D1%82%D0%B0.12328/#post-95468

Example:
https://kinovo.me/3419-mehanik2-2016.html

I am not sure about DNS though, it may be broken by other products as well.

**Comment by Alex-302** [comment]
Added to Russian filter:
```
@@/mxtads.com\/[0-9]/$domain=couber.be
||047855sphr.com^$popup
```
To DNS filter:
```
@@||mxtads.com^
```

**Comment by Alex-302** [comment]
Example is bad, player is not working even without filtering.
Fixed.
http://kinovo.me/4208-tarzan-legenda-2016.html
