### ISSUE TITLE
Query log filter selection auto-update

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardDNS#291]
When selecting filters in the query log filters page, it would be handy if the filter results would reflect results for the set filter.

For example, if I select Device A for theories sake, it would be handy if the results for countries, companies, status and type would reflect results for that device only.
If Device A had only visited google.com, and Device B had only visited apple.com, I wouldn't expect apple.com to show up when Device A is selected as a device in the filter page.

![image](https://user-images.githubusercontent.com/95468948/176988210-c3668d2f-6ac8-4bd0-a154-201a39faf2c6.png)

**Comment by Chinaski1** [comment]
Frankly, I don't really understand your request.

Do you want the filter settings to be reset when you change the selected device?
