### ISSUE TITLE
the CU app wont open due to the dns records missing

### ISSUE THREAD

**Issue by JadeMin** [AdguardTeam/AdGuardDNS#292]
https://play.google.com/store/apps/details?id=com.bgfcu.membership
when i open this app, it says "network connection error" and wont open
can you add the dns records of this app? i think its due to the dns records missing
its not the device or misblocking issue. ive already checked that

thank you <3

\- Aguard DNS Beta

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdGuardSDNSFilter #989](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/989) via [**ZenHub**](https://www.zenhub.com/)
