### ISSUE TITLE
Login issues

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardDNS#293]
When logging into AdGuard DNS on macOS Safari with Apple ID, I am forced to login a second time as the AdGuard login does not seem to handle the login the first time around, forcing me to login a second time which seems to work.

**Reproducible Steps**
1. Clear AdGuard website data from browser
2. Visit https://adguard-dns.io/en/dashboard/auth
3. Tap _Continue with Apple ID_ > pop-up appears to request apple authentication login, original screen states _Logging in with your social login_
4. Complete Apple ID authentication and enter AdGuard authentication code from Safari Passwords
5. Login pop-up either takes me to the AdGuard Account page showing my device licenses, or back to the AdGuard DNS login page
6. Repeat steps 1 to 5 to login.

A video of this has been sent to devteam@adguard.com, reproduced 3 times by clearing all AdGuard website data from the browser.

**Comment by Chinaski1** [comment]
Also looks like a bug.
We will find out what caused it and fix it in the next update, thank you.

**Comment by Chinaski1** [comment]
@jslawler 

We fixed some things on our side. And this issue should not be reproduced. 
Please try again and let us know the result.

**Comment by Chinaski1** [comment]
Can you please specify the version of the Safari browser?
The first issue is not reproduced on my side on Version 15.4 (17613.1.17.1.6)

And I also want to ask you to resend the video, because the last email got lost somewhere.

Thank you.
