### ISSUE TITLE
Broken CZAM

### ISSUE THREAD

**Issue by liberodark** [AdguardTeam/AdguardDNS#293]
Hi,

Broken not work great the page no show correctly just blank !
Please fix that

https://mon.compteczam.fr/

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| (176.103.130.130)
| How did you setup DNS configuration:| (System/Router)
| Device model:| (PC)
| Operating system and version:| (Linux / WIndows)

**Comment by liberodark** [comment]
Have make fix : https://github.com/AdguardTeam/AdguardDNS/pull/294

**Comment by liberodark** [comment]
Hi,

After 10 days czam bank not work !
But have make fix and why is not merged ?
You dns is broken mon.compteczam.fr is a important online bank in france by carrefour.
Please make a little effort for fix that.

Thank you

Cordialy

**Comment by Alex-302** [comment]
mon.compteczam.fr is not blocked by DNS.

**Comment by liberodark** [comment]
have screen and proof

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdguardDNS/pull/294#issuecomment-402083552
