### ISSUE TITLE
I can't link my device to unencrypted server

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardDNS#295]
Hello,

I have the error when I try to link my device to unencrypted server with DDNS or curl:
![2022-07-03_10-34-17](https://user-images.githubusercontent.com/45385632/177030017-babd6bd2-1217-41c5-8960-f35e09b6aeb6.png)

![image](https://user-images.githubusercontent.com/45385632/177030027-010bb893-af1b-45f2-b762-e17daea4fd8f.png)

The domain is resolved correctly:
https://www.whatsmydns.net/#A/ammnt.ddns.net

The support ticket # 615263 and still no have answer. Please take a look and try to correct it🙃

Thank you.
Best regards.

**Comment by ameshkov** [comment]
Reported internally, AGDNS-847
