### ISSUE TITLE
Error 500 page from user rules link

### ISSUE THREAD

**Issue by RicoHeat** [AdguardTeam/AdGuardDNS#298]
https://www.reddit.com/r/Adguard/comments/vqq5yf/user_rules_on_ag_dns_beta_oops/

**Comment by ameshkov** [comment]
@RicoHeat could you please send us the account details (email) to `devteam@adguard.com` and link this GH issue there as well?

**Comment by RicoHeat** [comment]
Everything seems to be back to normal 👍
