### ISSUE TITLE
Nvidia shield Tv. Cannot login to Geforce now

### ISSUE THREAD

**Issue by Bim-Bom** [AdguardTeam/AdguardDNS#298]
Hi,
when i use Adguard dns in my router or in Nvidia Shield Tv, this device can not be logged in to GeforseNow. If use other dns records, all work great.
Please fix that
https://photos.app.goo.gl/pDMEL42dBgLk2Sor5

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| 176.103.130.130
| How did you setup DNS configuration:| (System/Router)
| Device model:| Nvidia Shield TVbox
| Operating system and version:| Android 8.0.0 Oreo

**Comment by Alex-302** [comment]
@Bim-Bom is it possible to check DNS log on your router?

**Comment by Bim-Bom** [comment]
This is my log when starting login
Jul  2 18:37:36 dnsmasq[2893]: query[A] events.gfe.nvidia.com from 192.168.1.50
Jul  2 18:37:36 dnsmasq[2893]: cached events.gfe.nvidia.com is <CNAME>
Jul  2 18:37:36 dnsmasq[2893]: cached events-dc1.gfe.nvidia.com is 8.36.112.54
Jul  2 18:37:36 dnsmasq[2893]: cached events-dc1.gfe.nvidia.com is 8.36.120.11
Jul  2 18:37:36 dnsmasq[2893]: cached events-dc1.gfe.nvidia.com is 8.36.120.249
Jul  2 18:37:36 dnsmasq[2893]: cached events-dc1.gfe.nvidia.com is 8.36.113.113
Jul  2 18:37:36 dnsmasq[2893]: cached events-dc1.gfe.nvidia.com is 8.36.113.137
Jul  2 18:37:42 dnsmasq[2893]: query[A] login.nvgs.nvidia.com from 192.168.1.50
Jul  2 18:37:42 dnsmasq[2893]: cached login.nvgs.nvidia.com is 13.33.76.150
Jul  2 18:37:42 dnsmasq[2893]: cached login.nvgs.nvidia.com is 13.33.76.16
Jul  2 18:37:42 dnsmasq[2893]: cached login.nvgs.nvidia.com is 13.33.76.181
Jul  2 18:37:42 dnsmasq[2893]: cached login.nvgs.nvidia.com is 13.33.76.41
Jul  2 18:37:42 dnsmasq[2893]: query[A] rum-static.pingdom.net.lan from 192.168.1.50
Jul  2 18:37:42 dnsmasq[2893]: config rum-static.pingdom.net.lan is NXDOMAIN
Jul  2 18:37:42 dnsmasq[2893]: query[A] www.google-analytics.com.lan from 192.168.1.50
Jul  2 18:37:42 dnsmasq[2893]: config www.google-analytics.com.lan is NXDOMAIN
Jul  2 18:37:53 dnsmasq[2893]: query[A] rum-static.pingdom.net.lan from 192.168.1.50
Jul  2 18:37:53 dnsmasq[2893]: config rum-static.pingdom.net.lan is NXDOMAIN
Jul  2 18:37:53 dnsmasq[2893]: query[A] www.google-analytics.com.lan from 192.168.1.50
Jul  2 18:37:53 dnsmasq[2893]: config www.google-analytics.com.lan is NXDOMAIN
Jul  2 18:38:01 dnsmasq[2893]: query[A] rum-static.pingdom.net.lan from 192.168.1.50
Jul  2 18:38:01 dnsmasq[2893]: config rum-static.pingdom.net.lan is NXDOMAIN
Jul  2 18:38:01 dnsmasq[2893]: query[A] www.google-analytics.com.lan from 192.168.1.50
Jul  2 18:38:01 dnsmasq[2893]: config www.google-analytics.com.lan is NXDOMAIN

**Comment by Bim-Bom** [comment]
Jul  2 18:50:35 dnsmasq[2893]: query[A] events.gfe.nvidia.com from 192.168.1.50
Jul  2 18:50:35 dnsmasq[2893]: forwarded events.gfe.nvidia.com to 176.103.130.130
Jul  2 18:50:35 dnsmasq[2893]: forwarded events.gfe.nvidia.com to 176.103.130.131
Jul  2 18:50:35 dnsmasq[2893]: reply events.gfe.nvidia.com is <CNAME>
Jul  2 18:50:35 dnsmasq[2893]: reply events-dc1.gfe.nvidia.com is 8.36.113.113
Jul  2 18:50:35 dnsmasq[2893]: reply events-dc1.gfe.nvidia.com is 8.36.113.137
Jul  2 18:50:35 dnsmasq[2893]: reply events-dc1.gfe.nvidia.com is 8.36.120.11
Jul  2 18:50:35 dnsmasq[2893]: reply events-dc1.gfe.nvidia.com is 8.36.120.249
Jul  2 18:50:35 dnsmasq[2893]: reply events-dc1.gfe.nvidia.com is 8.36.112.54
Jul  2 18:50:37 dnsmasq[2893]: query[A] services.tegrazone.com from 192.168.1.50
Jul  2 18:50:37 dnsmasq[2893]: forwarded services.tegrazone.com to 176.103.130.130
Jul  2 18:50:37 dnsmasq[2893]: query[A] services.tegrazone.com from 192.168.1.50
Jul  2 18:50:37 dnsmasq[2893]: forwarded services.tegrazone.com to 176.103.130.130
Jul  2 18:50:37 dnsmasq[2893]: reply services.tegrazone.com is <CNAME>
Jul  2 18:50:37 dnsmasq[2893]: reply services.tegrazone.com.global.ogslb.com is <CNAME>
Jul  2 18:50:37 dnsmasq[2893]: reply cs326284.adn.phicdn.net is 192.229.182.215
Jul  2 18:50:37 dnsmasq[2893]: reply services.tegrazone.com is <CNAME>
Jul  2 18:50:37 dnsmasq[2893]: reply services.tegrazone.com.global.ogslb.com is <CNAME>
Jul  2 18:50:37 dnsmasq[2893]: reply cs326284.adn.phicdn.net is 192.229.182.215
Jul  2 18:50:40 dnsmasq[2893]: query[A] play.googleapis.com from 192.168.1.50
Jul  2 18:50:40 dnsmasq[2893]: forwarded play.googleapis.com to 176.103.130.130
Jul  2 18:50:40 dnsmasq[2893]: reply play.googleapis.com is <CNAME>
Jul  2 18:50:40 dnsmasq[2893]: reply googleapis.l.google.com is 173.194.73.95
Jul  2 18:50:40 dnsmasq[2893]: reply googleapis.l.google.com is 74.125.131.95
Jul  2 18:50:40 dnsmasq[2893]: reply googleapis.l.google.com is 64.233.164.95
Jul  2 18:50:40 dnsmasq[2893]: query[A] accounts.nvgs.nvidia.com from 192.168.1.50
Jul  2 18:50:40 dnsmasq[2893]: forwarded accounts.nvgs.nvidia.com to 176.103.130.130
Jul  2 18:50:40 dnsmasq[2893]: reply accounts.nvgs.nvidia.com is <CNAME>
Jul  2 18:50:40 dnsmasq[2893]: reply d2cphiaceuxrpi.cloudfront.net is 52.84.213.107
Jul  2 18:50:40 dnsmasq[2893]: reply d2cphiaceuxrpi.cloudfront.net is 52.84.213.30
Jul  2 18:50:40 dnsmasq[2893]: reply d2cphiaceuxrpi.cloudfront.net is 52.84.213.128
Jul  2 18:50:40 dnsmasq[2893]: reply d2cphiaceuxrpi.cloudfront.net is 52.84.213.120
Jul  2 18:50:40 dnsmasq[2893]: query[A] login.nvgs.nvidia.com from 192.168.1.50
Jul  2 18:50:40 dnsmasq[2893]: forwarded login.nvgs.nvidia.com to 176.103.130.130
Jul  2 18:50:40 dnsmasq[2893]: reply login.nvgs.nvidia.com is 52.84.213.20
Jul  2 18:50:40 dnsmasq[2893]: reply login.nvgs.nvidia.com is 52.84.213.175
Jul  2 18:50:40 dnsmasq[2893]: reply login.nvgs.nvidia.com is 52.84.213.209
Jul  2 18:50:40 dnsmasq[2893]: reply login.nvgs.nvidia.com is 52.84.213.218
Jul  2 18:50:41 dnsmasq[2893]: query[A] www.google-analytics.com.lan from 192.168.1.50
Jul  2 18:50:41 dnsmasq[2893]: config www.google-analytics.com.lan is NXDOMAIN
Jul  2 18:50:41 dnsmasq[2893]: query[A] rum-static.pingdom.net.lan from 192.168.1.50
Jul  2 18:50:41 dnsmasq[2893]: config rum-static.pingdom.net.lan is NXDOMAIN
Jul  2 18:50:47 dnsmasq[2893]: query[A] rum-static.pingdom.net.lan from 192.168.1.50
Jul  2 18:50:47 dnsmasq[2893]: config rum-static.pingdom.net.lan is NXDOMAIN
Jul  2 18:50:47 dnsmasq[2893]: query[A] www.google-analytics.com.lan from 192.168.1.50
Jul  2 18:50:47 dnsmasq[2893]: config www.google-analytics.com.lan is NXDOMAIN

**Comment by Alex-302** [comment]
Thanks. Excluded from dns filtering `pingdom.net`

**Comment by Alex-302** [comment]
Please check it after 12 hours.
