### ISSUE TITLE
AdGuard DNS not getting detected by AdGuard test website

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardDNS#299]
I am connected to AdGuard Private DNS via iOS config.
It's also not being detected by devices connected to my router using AdGuard DoT.

https://adguard.com/en/test.html

![image](https://user-images.githubusercontent.com/95468948/178119552-76dbcd9e-ffd7-4fab-8e25-a56fa943be84.png)
![image](https://user-images.githubusercontent.com/95468948/178119555-ec3b93d9-7c8c-4a51-b165-fd33b12792ab.png)

**Comment by ameshkov** [comment]
iCloud Private Relay?
