### ISSUE TITLE
kinozal.tv is not accessible with AdguardDNS

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardDNS#3]
Tested with 

176.103.130.130 
176.103.130.131 
 
on a router.

**952965**

**Comment by Alex-302** [comment]
Confirmed with Windows, but not always. 
Maybe is is caused by dns cache?

**Comment by Alex-302** [comment]
Removed from Russian filter(strange rule)
```
||kinozal.tv^$third-party
```

**Comment by nkartyshov** [comment]
done
