### ISSUE TITLE
rutracker.org, rutracker.net

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardDNS#30]
Пропущена реклама слева страницы. 
http://i80.fastpic.ru/big/2016/0809/e8/c76645bed781c386c5166e40ca6f5ae8.png

Оригинальный тред: https://forum.adguard.com/index.php?threads/adguard-dns-%D0%91%D0%B5%D1%82%D0%B0.12163/page-3#post-95100

**Comment by Alex-302** [comment]
Добавил в фильтр DNS для fastpic.ru:
```
||torvind.com^
```
На rutracker баннер не убрать с помощью DNS, т.к. расположен на домене, на котором хранятся их ресурсы. Как минимум - пропадёт логотип.
