### ISSUE TITLE
certificate issues

### ISSUE THREAD

**Issue by DooML** [AdguardTeam/AdGuardDNS#30]
Most blocked sites in family protection return this
> NET::ERR_CERT_COMMON_NAME_INVALID

![image](https://user-images.githubusercontent.com/26717942/57973217-f68bf980-7994-11e9-9cbd-06d382a3b2af.png)

**Comment by ameshkov** [comment]
There's no solution to this. We cannot use a proper certificate for the blocked domain so we have to use our own certificate.
