### ISSUE TITLE
Broken CZAM #2

### ISSUE THREAD

**Issue by liberodark** [AdguardTeam/AdguardDNS#300]
Hi,

Broken not work great the page no show correctly just blank !
Please fix that

https://mon.compteczam.fr/

Proof : 
With DNS : https://i.imgur.com/44j80jy.png
Without DNS : https://i.imgur.com/8gayqeA.png
Content blocked is : 
https://et2.eulerian.net/ian4695.js
https://tag.aticdn.net/574362/smarttag.js
(https://tag.aticdn.net) (https://et2.eulerian.net) is blocked by dns

Better solution is make exclusion of mon.compteczam.fr

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| (176.103.130.130)
| How did you setup DNS configuration:| (System/Router)
| Device model:| (PC)
| Operating system and version:| (Linux / WIndows)

**Comment by Alex-302** [comment]
excluded tag.aticdn.net and fixed for ad blockers.

**Comment by liberodark** [comment]
Thx
