### ISSUE TITLE
Odd dark rings around the background border and all highlighted objects

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardDNS#300]
I'm not sure whether this is intentional or not, but I didn't notice it in beta 4.

I seem to be getting a lot of dark rings around objects as I highlight them, and surrounding the background colour of the dashboard.
It almost looks like it's an attempt to add a shadow effect that doesn't get displayed right maybe?

<img width="1904" alt="Screen Shot 2022-07-14 at 02 16 02" src="https://user-images.githubusercontent.com/95468948/178782816-6b1b6b07-e518-41ff-a630-bba67ab54cc7.png">
<img width="1183" alt="Screen Shot 2022-07-14 at 02 19 51" src="https://user-images.githubusercontent.com/95468948/178782833-0e0ce95e-8ab6-4335-a68e-b2dad763c82a.png">

https://user-images.githubusercontent.com/95468948/178783330-b9be870b-4c40-4fd5-9999-fd42a000c384.mov

macOS Safari: 15.5 (17613.2.7.1.8)

**Comment by Chinaski1** [comment]
Hi there!

It is already fixed and be available in the next update.
Tnx for the report.
