### ISSUE TITLE
iOS/macOS Password AutoFill does not work correctly for AdGuard DNS login

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardDNS#301]
### Username
When tapping on the email text box at adguard-dns.io, Password Autofill does not ask to enter in a username even if it is added to iOS Passwords. Instead, it asks you to enter your email by bringing up AutoFill data from your personal Contacts information.
What should appear is the Password AutoFill data for the website added to Password AutoFill.

Inspecting in the console, I can see that autofill is only added for the email, and not username or password.
Here is the what's currently in place for adguard-dns.io:
`<input name="email" type="email" placeholder="example@mail.com" class="jsauth-input jsauth-input_email" autocomplete="email" value="">`

Here's what's in place for auth.adguard.com:
`<input class="form__input" id="username" name="username" required="required" type="email" autocomplete="username" value="">`

As we can see, autocomplete="email" is being used where autocomplete="username" should be used.

<details><summary>Screenshots</summary>
<p>

<img width="605" alt="Screen Shot 2022-07-14 at 04 04 35" src="https://user-images.githubusercontent.com/95468948/178801010-1c32b057-3052-4d90-8d3d-e2dd6a88ebe2.png">

![IMG_0003](https://user-images.githubusercontent.com/95468948/178801140-644f28af-b961-4f2b-9a92-375db0cafdbd.jpeg)

</p>
</details>

### One Time Code
The one time code, or two factor authentication text box also is not detected by Safari on macOS or iOS.

<details><summary>Screenshots</summary>
<p>

<img width="629" alt="Screen Shot 2022-07-14 at 04 04 23" src="https://user-images.githubusercontent.com/95468948/178801037-63b0bfcd-7d43-40c6-a48a-4812557cce09.png">

![IMG_0004](https://user-images.githubusercontent.com/95468948/178801077-aa2cc27c-15f1-42ee-8e8e-8defc40f0c03.PNG)

</p>
</details>

Docs: https://developer.apple.com/documentation/security/password_autofill/enabling_password_autofill_on_an_html_input_element

macOS Safari: 15.5
iOS: 15.5

**Comment by Chinaski1** [comment]
Fixed in today's update.
