### ISSUE TITLE
Goat.com keeps getting blocked for no reason

### ISSUE THREAD

**Issue by sumanthneerumalla** [AdguardTeam/AdguardDNS#302]
### Steps to reproduce

1. http://goat.com/
2.
3.
4.

### Expected behavior

It should let me browse this site on desktop and mobile views

### Actual behavior

The page does not load due to dns resolution

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/10293775/42301614-65674f72-7fe4-11e8-9ea8-f9c545731c41.png)
</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| Defaults  176.103.130.130, 176.103.130.131
| How did you setup DNS configuration:| dns settings in home router
| Device model:| Dell laptop, motorola android phone
| Operating system and version:| Androd 8 , Windows 10

**Comment by Alex-302** [comment]
@zebrum please unblock this site

**Comment by vozersky** [comment]
@nkartyshov are we able to fix it?

**Comment by Alex-302** [comment]
![image](https://user-images.githubusercontent.com/8361299/42312380-d88b76ae-8048-11e8-9694-4cde12eeba8a.png)

**Comment by vozersky** [comment]
I've removed it from SafeBroswing database but that's a different case, i guess.

**Comment by vozersky** [comment]
yep, related to SB #303
