### ISSUE TITLE
AdGuard Public DNS - DNS6 Unreachable

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdGuardDNS#303]
When I try to use IPv6 and have the DNS6 server set to 2a10:50c0::ad1:ff and 2a10:50c0::ad2:ff, my IPv6 traffic cannot use the DNS6 servers, only the DNS4 servers.

This for me is causing slowdowns and timeouts as IPv6 traffic continues to try to use DNS6 servers and timeout.

Using http://ipv6-test.com

<img width="579" alt="Screen Shot 2022-07-14 at 7 36 30 pm" src="https://user-images.githubusercontent.com/65204836/178952756-be87b12b-205f-4271-b381-a5a613c75e8f.png">

Using https://test-ipv6.com

<img width="568" alt="Screen Shot 2022-07-14 at 7 39 25 pm" src="https://user-images.githubusercontent.com/65204836/178952986-1e34e791-1b59-4098-b4b7-527560d38eb2.png">

Easy way to test:

https://ds.v6ns.test-ipv6.com.au/ip/?callback=?&testdomain=test-ipv6.com&testname=test_v6ns

<img width="311" alt="Screen Shot 2022-07-14 at 7 39 10 pm" src="https://user-images.githubusercontent.com/65204836/178953077-7cd162b1-80b5-4e34-a900-ff17f8bd6930.png">

Which for me, fails.

<img width="570" alt="image" src="https://user-images.githubusercontent.com/65204836/178953354-47957d90-fcd7-4500-89dc-f813cf7dfdce.png">

I've encountered this on AdGuard for Windows, AdGuard for Mac, AdGuard for Android and AdGuard for iOS — all using AdGuard DNS via DNS-over-HTTPS as well as just using plain DNS via a router.

If I use my ISP DNS, Google DNS or 1.1.1.1 DNS with their IPv6 DNS Servers, they all work.

**Comment by ameshkov** [comment]
Our recursor currently only works over IP4. This is not much of an issue for DNS customers, IP6-only nameservers is a thing that exists in these tests only. The reason for that is that when IPv4 is in use, the CDN nameservers answers are more precise (geoIP databases for IP6 addresses aren't ideal). 

However, now since AG DNS implemented ECS (in a non-convential way, but anyways) it is not much of a problem and we can enable IP6 on the recursor.

**Comment by ameshkov** [comment]
Just in case, we've enabled IPv6 on the recursor:
![image](https://user-images.githubusercontent.com/5947035/180980108-efad91b0-67b3-4539-b8f6-657ff79ae645.png)

**Comment by planet0** [comment]
Great news, @ameshkov.

Although it shouldn't be an issue, for some reason my IPv6 traffic slows down or times out trying to use DNS6 first. 

Now, my internet activity seems to be behaving well.

Thank you for doing this!

**Comment by ameshkov** [comment]
No problem:)
