### ISSUE TITLE
CHIN: Adrules DNS List blocking ISP

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardDNS#305]
when this blocklist is on and when running smarthub connection test on my samsung tv it is is unable to complete ISP Blocking test. The message I get is ISP Blocking service Error Code 202. it works fine when i disable that blocklist. so if someone could help me fix this.

**Comment by Chinaski1** [comment]
@Batman2814 

Hi there!

Sorry for the late reply.
I think you should try to run the test, open the filtering log and check the blocked requests.
Unblock requests one by one to find out which rule is blocking access.

**Comment by Batman2814** [comment]
I figured out what rules were blocking. There where 2.
cdn.samsungcloudsolution.com 
and
gpm.samsungqbe.com
