### ISSUE TITLE
False Positive report on our domain ip2location.com in your list filter.txt

### ISSUE THREAD

**Issue by ip2location** [AdguardTeam/AdguardDNS#306]
Hi AdguardDNS, recently when we reviewed your list filter.txt, we found out that our domain was reported on the list and this is false positive as our domain was not ads website, it should not been blocked. The IP2Location is a geolocation look up database that can be used to reverse translate IP address to the geolocation information such as country and city.

**Comment by ameshkov** [comment]
@ip2location hi! It comes from EasyPrivacy: https://easylist-downloads.adblockplus.org/easyprivacy.txt

If it's removed from there, it will be removed from the DNS filter as well.
