### ISSUE TITLE
Change Safebrowsing answer to 0.0.0.0

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardDNS#306]
Hello,

I want to change Safebrowsing answer from blocked page A record to 0.0.0.0. Please explain how to make it. I think we need to add rewrite rule, but not sure🤨

Thank you.
Best regards.

**Comment by Chinaski1** [comment]
I'm not sure that we can implement this function at this stage.

But we will come back to it in the future.

**Comment by ammnt** [comment]
@Chinaski1, I also use AdGuard Home. AdGuard DNS just as upstream servers. How to properly make the rewrite rule for change safebrowsing answer from your IP to null IP? Thank you.

**Comment by ameshkov** [comment]
Try these (in AdGuard Home):

* For parental control: `|94.140.14.35^`
* For safebrowsing: `|94.140.14.33^`

**Comment by ammnt** [comment]
@ameshkov, works fine! Thank you☺️
