### ISSUE TITLE
Adguard DNS Website not loading with Adgaurd VPN

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardDNS#307]
I have Adguard for Android setup on my Galaxy phone with Adguard VPN when Adguard VPN is one the Adguard DNS website login account will not load shows a blank screen. Can someone tell me how to fix it with disabling the Adgaurd VPN.

**Comment by Chinaski1** [comment]
Please specify to what server are you connected to?
Does this issue recur if you select a different server?
