### ISSUE TITLE
Request to add non-standard ports

### ISSUE THREAD

**Issue by miaomiaosoft** [AdguardTeam/AdguardDNS#308]
HI,In China, all foreign DNS default ports ( 53 ) will be hijacked, and the resolution results returned by DNS will be forcibly replaced with inaccessible random IP addresses. if ports 5353 or 443 are supported like opendns, hijacking will not occur.

I understand that using dnscrypt can also achieve the goal, but I can easily set it up on the router and use it. it supports non-standard ports and does not need to install dnscrypt.

**Comment by ameshkov** [comment]
AG DNS is available on port 5353
