### ISSUE TITLE
videos don't work on sbs.com

### ISSUE THREAD

**Issue by Bt7fdbufffdk** [AdguardTeam/AdGuardDNS#31]
link for example: [https://www.sbs.com.au/news/our-hearts-ache-mourning-in-virginia-beach-after-150th-mass-shooting-in-us](url)
 is there any way to make it work?

**Comment by Alex-302** [comment]
@Bt7fdbufffdk hi. This player is not working on my end with/without AdGuard even with AU VPN.
Could you, please, check with disabled filters? If the issue will gone, enable filters one-by-one with checking.

**Comment by Alex-302** [comment]
That's because `ensighten.com` is blocked by our DNS. but it is a popular tracker.

But you can try to add these strings to HOSTS file:
```
34.253.250.174 nexus.ensighten.com
```
or
```
18.203.144.171 nexus.ensighten.com
```
or
```
34.253.250.174 nexus.ensighten.com
18.203.144.171 nexus.ensighten.com
```

**Comment by Bt7fdbufffdk** [comment]
i'm not sure what hosts file you're referring to but it's not just ensighten.com, it doesn't seem to be blocked though. it seems that akamaihd.net, cxense.com, jsdelivr.net and theplatform.com are all required for videos to play
