### ISSUE TITLE
Show more records in the Query Log

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardDNS#313]
Change the page size to 500.

**Comment by hmage** [comment]
Server-side querylog is 1000 elements.

@maximtop @IldarKamalov Do you limit number of entries on JS-side?

**Comment by hmage** [comment]
```bash
hmage@whmd:~/test/go$ curl -s http://127.0.0.1:3000/control/querylog|jq .|fgrep '"client"'|wc -l
    1000
```

This is definitely on JS side.

@maximtop @IldarKamalov Can you guys fix that? Right now querylog page shows only 20 entries.
