### ISSUE TITLE
ipv6 dns resolution consistently 50-60% slower than ipv4 (UK)

### ISSUE THREAD

**Issue by Altycoder** [AdguardTeam/AdGuardDNS#313]
As the titles says, from the UK, dns resolution time to ipv6 servers (e.g. 2a10:50c0::bad1:ff) is consistently 50-60% slower than ipv4 resolution (e.g. 94.140.14.15).  Doing a traceroute for both of these  IP addresses gives different results:

```
traceroute to 94.140.14.15 (94.140.14.15), 30 hops max, 60 byte packets
 1  _gateway (192.168.1.1)  0.240 ms  0.157 ms  0.172 ms
 2  * * *
 3  * * *
 4  dns-family.adguard.com (94.140.14.15)  8.094 ms  8.318 ms  7.646 ms
 5  dns-family.adguard.com (94.140.14.15)  8.106 ms  7.215 ms  7.809 ms
 6  dns-family.adguard.com (94.140.14.15)  16.295 ms  33.610 ms  8.753 ms
 7  dns-family.adguard.com (94.140.14.15)  7.834 ms  7.703 ms  7.080 ms
 8  dns-family.adguard.com (94.140.14.15)  47.545 ms  47.467 ms  47.386 ms
 9  dns-family.adguard.com (94.140.14.15)  8.233 ms  9.007 ms  9.046 ms
10  dns-family.adguard.com (94.140.14.15)  8.749 ms  8.289 ms  8.508 ms
11  dns-family.adguard.com (94.140.14.15)  7.783 ms  8.160 ms  8.065 ms
12  dns-family.adguard.com (94.140.14.15)  7.637 ms  7.528 ms  7.951 ms

traceroute to 2a10:50c0::bad1:ff (2a10:50c0::bad1:ff), 30 hops max, 80 byte packets
 1  pfSense.home (2a00:23c4:<redacted>)  0.400 ms  0.345 ms  0.332 ms
 2  * * *
 3  * * *
 4  * 2a00:2302::1103:100:33 (2a00:2302::1103:100:33)  8.529 ms *
 5  * * *
 6  peer7-et0-0-4.telehouse.ukcore.bt.net (2a00:2380:13::9d)  7.679 ms peer7-et0-1-4.telehouse.ukcore.bt.net (2a00:2380:13::7d)  7.347 ms peer7-et4-0-1.teleouse.ukcore.bt.net (2a00:2380:13::d1)  7.253 ms
 7  2a00:2000:2073:2::30 (2a00:2000:2073:2::30)  7.675 ms  7.111 ms  7.426 ms
 8  * * *
 9  if-ae-66-2.tcore1.ldn-london.ipv6.as6453.net (2a01:3e0:10:2000::90)  7.542 ms  8.357 ms  7.636 ms
10  if-ae-17-2.tcore1.l78-london.ipv6.as6453.net (2001:5a0:2000:400::49)  8.151 ms  9.199 ms  6.975 ms
11  if-ae-2-2.tcore2.l78-london.ipv6.as6453.net (2001:5a0:2000:500::1)  11.229 ms  8.645 ms  10.362 ms
12  if-ae-14-2.tcore2.av2-amsterdam.ipv6.as6453.net (2001:5a0:2000:500::23)  11.705 ms  13.445 ms  12.488 ms
13  if-be-45-2.ecore1.av2-amsterdam.ipv6.as6453.net (2a01:3e0:ff40:200::43)  12.559 ms * *
14  2a01:3e0:ff40:1000::1a (2a01:3e0:ff40:1000::1a)  13.992 ms  14.240 ms  14.011 ms
15  dns-family.adguard.com (2a10:50c0::bad1:ff)  13.174 ms  13.338 ms *
```

**Comment by D13410N3** [comment]
Hello.
Can you please check traceroute to v6 now?

**Comment by Altycoder** [comment]
Much worse, dns response up to twice as long now, was averaging around 16ms previously, now up to 30ms.  Traceroute:

traceroute 2a10:50c0::bad1:ff
traceroute to 2a10:50c0::bad1:ff (2a10:50c0::bad1:ff), 30 hops max, 80 byte packets
 1  2a00:23c4:<redacted> (2a00:23c4:<redacted>)  0.296 ms  0.270 ms  0.251 ms
 2  * * *
 3  * * *
 4  2a00:2302::1103:100:3f (2a00:2302::1103:100:3f)  7.700 ms * *
 5  2a00:2380:3013:2000::e (2a00:2380:3013:2000::e)  7.354 ms 2a00:2380:3013:8000::2a (2a00:2380:3013:8000::2a)  8.151 ms 2a00:2380:3013:8000::38 (2a00:2380:3013:8000::38)  7.629 ms
 6  peer7-et4-0-1.telehouse.ukcore.bt.net (2a00:2380:13::d1)  7.475 ms peer7-et0-1-1.telehouse.ukcore.bt.net (2a00:2380:13::95)  6.978 ms peer7-et0-0-4.telehouse.ukcore.bt.net (2a00:2380:13::9d)  7.246 ms
 7  2a00:2000:2073:2::30 (2a00:2000:2073:2::30)  7.101 ms  7.169 ms  6.790 ms
 8  * * *
 9  if-ae-66-2.tcore1.ldn-london.ipv6.as6453.net (2a01:3e0:10:2000::90)  7.646 ms  7.617 ms  7.272 ms
10  if-ae-17-2.tcore1.l78-london.ipv6.as6453.net (2001:5a0:2000:400::49)  10.575 ms  6.807 ms  7.212 ms
11  if-ae-3-2.tcore1.pye-paris.ipv6.as6453.net (2a01:3e0:fff0:400::2a)  15.751 ms  14.672 ms  15.608 ms
12  if-ae-11-2.tcore1.pvu-paris.ipv6.as6453.net (2a01:3e0:ff80:100::91)  14.664 ms  15.145 ms  15.721 ms
13  if-ae-49-2.tcore2.pvu-paris.ipv6.as6453.net (2a01:3e0:ff80:100::b)  14.230 ms  14.272 ms  14.117 ms
14  if-ae-55-2.tcore1.fr0-frankfurt.ipv6.as6453.net (2a01:3e0:ff80:8000::7)  20.114 ms  20.913 ms  20.842 ms
15  if-ae-54-2.tcore2.fr0-frankfurt.ipv6.as6453.net (2a01:3e0:ff20::125)  22.293 ms  22.511 ms  22.096 ms
16  2a01:3e0:ff20:400::2e (2a01:3e0:ff20:400::2e)  20.504 ms  20.351 ms  20.296 ms
17  dns-family.adguard.com (2a10:50c0::bad1:ff)  20.614 ms  20.562 ms  20.595 ms

**Comment by Altycoder** [comment]
Sorry on ipad can’t seem to do a code block!

**Comment by D13410N3** [comment]
As you can see, your v6-traffic comes to AS6453, "TATA" (9th hop on each traceroute) and then it comes through its internal network to Amsterdam & Frankfurt. That means it's the simplest way to route IPv6 for your provider.

Sorry, we can't help you with this, but you can ask your provider about this strange routing issue (when IPv4 & IPv6 are not routing in the same way to one physical location)

**Comment by Altycoder** [comment]
OK but things are worse since you made changes yesterday and asked me to re-check.  Previously queries went through London and Amsterdam, now they're going through London, Paris and Frankfurt and ipv6 dns latency is 100% worse.

Can you at least revert any changes you made yesterday?

**Comment by D13410N3** [comment]
Changes are reverted. Sorry for a long answer
