### ISSUE TITLE
AdGuard verification code Autofill not detected for Apple login on iOS Safari

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardDNS#314]
When logging in with 2FA enabled for AdGuard, the verification code box isn't detected by Safari for iOS, and instead tries to insert the saved email for the website rather than the verification code.

iOS Safari 15.6

![image](https://user-images.githubusercontent.com/95468948/182231699-7b70aa60-a8ec-4621-b0b0-9dbc0ed0fbdd.jpeg)

**Comment by Chinaski1** [comment]
Same for this task

@jslawler can you please confirm it?
