### ISSUE TITLE
Block access to iCloud Private Relay

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardDNS#315]
I'm not seeing any difference in operation with the tick box for block access to iCloud Private Relay ticked.

Should I be seeing some evidence in the dashboard or logs that this is working?

![image](https://user-images.githubusercontent.com/95468948/182234613-ed65d42c-b2f3-4dcf-89fe-f78bcdf1851e.jpeg)
![image](https://user-images.githubusercontent.com/95468948/182234625-f8b8d9dc-11cc-47f0-ae3e-c8e1dc149e28.png)

**Comment by ameshkov** [comment]
When "Block access to iCloud Private Relay" is enabled, queries to `mask.icloud.com` should return NXDOMAIN.

**Comment by ameshkov** [comment]
We don't print the actual DNS response status in the log, but it should've been NXDOMAIN.

Try opening it in the browser. If the error is something like "domain does not exist" or NXDOMAIN, it works properly.
If the error will be something like "cannot connect to this server", something went wrong.

**Comment by ameshkov** [comment]
Both return NXDOMAIN, I've just mentioned the first one to not complicate the check:)
