### ISSUE TITLE
There's no reaction on some actions in the web interface

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardDNS#316]
Every action must provide some feedback (depending on the action result).
We should use some simple toast/notification library, for instance, https://github.com/CodeSeven/toastr or https://github.com/MohammadYounes/AlertifyJS or something like that.

I'd say we should use the same approach as with the https://agrd.io/report.

Also, for any long-running action, we must use [nprogress.js](http://ricostacruz.com/nprogress/).

### Error

In case of any unexpected error, we must show an error alert: `Unexpected error occurred while doing ACTION_NAME: error details`.

### Settings page

When you change any setting, you need to show an alert that settings were successfully updated.

### Filters page

* Check updates: nprogress + toast
* Add filter: nprogress + result in the dialog (with the filter data -- you might need to change the backend for that)
* Apply: toast

**Comment by hmage** [comment]
@maximtop @IldarKamalov 

 * for errors, same as #315 — API already responds with HTTP error codes and text
 * for settings — wait until API replies with HTTP OK and then show 'settings were successfully updated'.
 * for filters — wait till I change the API to support previewing filters before adding

**Comment by hmage** [comment]
Fixed in 81c7dbbc1684622e8b2e05d39dcd4605339ff24f
