### ISSUE TITLE
Update the README of this repo

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardDNS#318]
Here's the plan

- [x] What is AdGuard DNS? Briefly, what it is.
- [x] How does it work?
- [x] Public AdGuard DNS servers TBD. This is a section about AG DNS we host on our servers. Describe how to set it up, what are the options, etc.
- [x] Self-hosted AdGuard DNS. Explain what it is and what it provides (dashboard, filters settings, etc, etc).
- [x] How to install your own AdGuard DNS
  - [x] Linux
  - [x] Mac
  - [ ] Windows
- [x] How to build
  - [x] Prerequisites
- [x] How to run
  - [x] Linux/Mac
  - [ ] Windows
- [x] Contributing
- [x] Reporting issues

**Comment by hmage** [comment]
Updated README in 38cfe95280732514d39326103c556307feb4001c
