### ISSUE TITLE
Connected devices data alignment iOS Safari

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardDNS#318]
There seems to be a lot of inconsistency to how common data is visualised on the interface.

I've listed a few issues below.

**Companies data**
![image](https://user-images.githubusercontent.com/95468948/182279187-cb2ae8bc-8ea9-4516-bc47-6083e61eb5e0.jpeg)

To be clear I think this data above is presented best on mobile, and easily switches between portrait and landscape without issue.

**Server Settings Connected Devices**
![image](https://user-images.githubusercontent.com/95468948/182241330-8db64bad-028f-4778-96b8-c586abff5315.jpeg)

**Landscape view**
![image](https://user-images.githubusercontent.com/95468948/182241305-b30758ad-7680-4aea-84f6-14f004cad265.png)

When the device is in landscape, the device statistics are quite neatly aligned to the right side of the page, but when in portrait mode, they seem to be squashed over to the left.

**Dashboard Devices**
![image](https://user-images.githubusercontent.com/95468948/182279015-b12c2abf-d03b-4c0b-9a71-270b0eca8244.jpeg)

The data here is very oddly presented on a second line, tabbed apart which looks like a waste of space.

**Comment by Chinaski1** [comment]
Fixed in v2.0
