### ISSUE TITLE
Provide IPv6 DNS addresses

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardDNS#32]
Read here the details:
https://blog.adguard.com/en/adguard-dns-beta/#comment-2846431854

We should do something about it.

**Comment by ameshkov** [comment]
It already resolves IPv6 addresses, so this is no issue.

What we need is to provide IPv6 DNS servers for those who simply cannot access IPv4.

**Comment by TPS** [comment]
Why wouldn't simple address conversion like @ http://www.ipaddressguide.com/ipv4-to-ipv6 "just work"?

**Comment by TPS** [comment]
I ended up using http://en.toolpage.org/tool/ipv4-to-ipv6 to bulk-convert

176.103.130.130
176.103.130.131
176.103.130.132
176.103.130.134

to

0:0:0:0:0:ffff:b067:8282
0:0:0:0:0:ffff:b067:8283
0:0:0:0:0:ffff:b067:8284
0:0:0:0:0:ffff:b067:8286

which is, of course, same as

::ffff:b067:8282
::ffff:b067:8283
::ffff:b067:8284
::ffff:b067:8286

D'y'all mind testing? I'm not (yet) using AGDNS, but probably will soon.

**Comment by TPS** [comment]
I ended up using http://en.toolpage.org/tool/ipv4-to-ipv6 to bulk-convert

176.103.130.130
176.103.130.131
176.103.130.132
176.103.130.134

to

0:0:0:0:0:ffff:b067:8282
0:0:0:0:0:ffff:b067:8283
0:0:0:0:0:ffff:b067:8284
0:0:0:0:0:ffff:b067:8286

which is, of course, same as

::ffff:b067:8282
::ffff:b067:8283
::ffff:b067:8284
::ffff:b067:8286

D'y'all mind testing? I'm not (yet) using AGDNS, but probably will soon.

**Comment by Bluscream** [comment]
These look like local adresses

**Comment by TPS** [comment]
What do mean, @Bluscream?  I'm quite ignorant of fine IPv6 details.

**Comment by Bluscream** [comment]
They look like adresses used in an own LAN / WLAN network, not WAN ips

**Comment by TPS** [comment]
How do you suggest the conversion be done?

**Comment by Bluscream** [comment]
The ISP needs to assign ipv6 adresses for the dns servers

**Comment by Bluscream** [comment]
Damn i wish ag ipv6 dns would be a thing now :)

**Comment by koesherbacon** [comment]
I'm not certain if this is still an open issue, but is there a roadmap that estimates when AdGuard DNS will have its own IPv6 addresses as well as the tried and true IPv4? Many thanks

**Comment by ameshkov** [comment]
At the moment we use two different hosting providers. One of them provides IPv6 connectivity and the other one does not. 

The other problem is that we don't own an IPv6 block and using some random address is not an option.

So, once we buy an IPv6 addresses block, we can use it for at least some servers.

@vbagirov need you to assist me on this.

**Comment by SMed79** [comment]
Are there any news about IPv6 Adguard DNS addresses?

**Comment by planet0** [comment]
As soon as there are IPV6 addresses, I'm going to switch all my devices over as I'm unable to control the IPv6 DNS on my gateway. Being able to add the Adguard DNS IPv6 to my devices to override it would be wonderful.

**Comment by ameshkov** [comment]
We've acquired an IPv6 addresses block, so we're close.

**Comment by Snapy** [comment]
@ameshkov Can you update readme with the now [available](https://blog.adguard.com/en/dns-ipv6-support/) IPv6 addresses ? TIA

**Comment by TPS** [comment]
Also, update the regular/DNSCrypt sections of the apps w/ AG IPv6 options (like y'all have for OpenDNS, Babylon, D0wn Resolver, &c)?

**Comment by ameshkov** [comment]
Done!
https://github.com/AdguardTeam/AdguardDNS

Regarding DNSCrypt, it will be updated in due course (the pull request was accepted recently, but we need to add one more).

**Comment by jravid** [comment]
@ameshkov Thank you so much for this! The IPv6 DNS server addresses are essential because T-Mobile USA is an IPv6 only network, so overriding the system default DNS using the IPv4 addresses ends up providing an unusably slow connection. I just updated to the IPv6 addresses though, and we're back in business! I would update the Readme.md and/or the guide to reflect this (the necessity of using the IPv6 addresses when on T-Mobile USA)- I'm not sure that many folks would otherwise figure this out without doing quite a bit of digging.

As an aside, this is why Adblock by FutureMind doesn't work properly when using T-Mobile USA (the DNS server their app creates/uses is IPv4). Likewise with DNS Override by QRMedia (they only support IPv4 DNS servers).
