### ISSUE TITLE
Can you do like this

### ISSUE THREAD

**Issue by luxysiv** [AdguardTeam/AdGuardDNS#32]
Please visit this https://nextdns.io
User can creat owner dns with personal rules
![47FEA83B-60EC-496F-B067-A5228FA6DA03](https://user-images.githubusercontent.com/46205571/58748474-a9834980-84a3-11e9-84cd-7a30df03840e.png)
![9020329B-2EAB-42AC-8D60-86872F95B7C4](https://user-images.githubusercontent.com/46205571/58748475-aa1be000-84a3-11e9-9469-0fb12a4c593d.png)
![2F09F579-4EB5-4365-8724-52CF8D1AC662](https://user-images.githubusercontent.com/46205571/58748476-aa1be000-84a3-11e9-8ffd-3cae2c8be301.png)

**Comment by TPS** [comment]
It seems similar to [OpenDNS Dashboard](https://dashboard.opendns.com/), so, [of course I'd love this, too](https://github.com/AdguardTeam/AdguardForAndroid/issues/491#issuecomment-224298531).

If you had this, I'd switch everything over myself, from the hybrid of router AGDNS, Android AG w/ OpenDNS Dashboard, laptops w/ AdGuard addons & OpenDNS Dashboard, & other IoT devices running on customized router defaults.

Clearly, it'd make my life simpler.

**Comment by luxysiv** [comment]
Ofcouse I don’t have. 
Adguard 3.0 for iOS does not seem to block ads in 3rd party apps anymore.  And it seems that users cannot add their own filters like Adguard Pro 2.0.  So I suggest you do Adguard DNS in the way of NextDNS, users use AdguardDNS but can still add their own filters.  For example, I would like to block ocsp.apple.com but you will definitely not add AdguardDNS

**Comment by ameshkov** [comment]
This is a nice idea indeed, but rather complicated to implement. Thanks for sharing it!

Please note that you can use NextDNS in AdGuard 3.0 for iOS, it supports both DNS-over-HTTPS and DNS-over-TLS.

**Comment by luxysiv** [comment]
I used NextDNS on adguard

**Comment by TPS** [comment]
_(Could this issue's title be updated to be more descriptive?)_

**Comment by TPS** [comment]
Just wanted to mention, the AGDNS "Dashboard" beta is _nice_!

**Comment by ameshkov** [comment]
Oh, good issue :)
