### ISSUE TITLE
Improve the "Filters" settings

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardDNS#320]
It's all on the screenshot:
![](https://uploads.adguard.com/up04_orpqg_AdGuard_DNS_.png)

**Comment by hmage** [comment]
@IldarKamalov @maximtop There's `"name"` field in `/filtering/status` for each filter, use it instead of URL for filter name.

**Comment by hmage** [comment]
@maximtop @IldarKamalov make the filter's link clickable in the table

**Comment by hmage** [comment]
Fixed by 2ca1a0e5861c19dc2517c885e9a378837ef2a447
