### ISSUE TITLE
Dashboard isn't detecting connected iOS device

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardDNS#320]
When using the AdGuard DNS config file on iOS the device is no longer detected on the dashboard.

Please note that iCloud Private Relay is disabled and no other network modifications have been made.
This was reproduced by another user on Telegram.

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/95468948/182243405-d009545a-3a9f-4800-a9ae-c814b0df140f.png)

</details>

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/95468948/182243479-1153d033-71e6-4a0d-a1b4-c17087e950da.png)

</details>

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/95468948/182243672-6b65c15b-e004-4c81-b4fc-11aa8e8b1cd6.jpeg)

</details>

**Comment by Batman2814** [comment]
Had the same problem but when going into settings for the device and running Adguard test page it on. It's not just iOS it's on windows, android. It seems to happen after releasing beta 6 if Adguard Personal DNS beta.

**Comment by githubuser013** [comment]
I have windows and android with the same issue.

**Comment by Chinaski1** [comment]
Hi all.

At the moment there is an issue with the detection of devices, but the service is working correctly. We will try to fix it in the short term.

**Comment by ameshkov** [comment]
Fixed
