### ISSUE TITLE
Add a "Test" button to the "Upstreams" settings

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardDNS#321]
![](https://uploads.adguard.com/up04_8tw3w_AdGuard_DNS_.png)

**Comment by hmage** [comment]
@maximtop @IldarKamalov API has been added, please add a button "Test upstreams" which calls `/control/test_upstream_dns` as per updated OpenAPI specs, wait for it to complete and parse returned JSON. If all entries are OK, show a checkmark. If some entries are not OK, show something like `Server "1.2.3.4": could not be used, please check that you've written it correctly"`
