### ISSUE TITLE
Switching from 90 days to anything less causes dates to overlap

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardDNS#323]
Switching Home statistic data between 90 days, and anything less causes the dates to overlap.

iOS Safari 16.0

![image](https://user-images.githubusercontent.com/95468948/182973369-5e53aa1f-3707-4f78-9986-de0edb04e9b7.jpeg)

**Comment by Chinaski1** [comment]
@jslawler 

Hello there!
Is the issue still reproduced?
I have not been able to reproduce it on my side. Could you please provide the reproduction steps?
