### ISSUE TITLE
Youtube ad block

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardDNS#324]
@konstantin59 commented on [Fri Aug 24 2018](https://github.com/AdguardTeam/AdguardKnowledgeBase/issues/231)

I'm using the mibox3 international version on Oreo, since recently your dns stopped blocking ads in YouTube, why?

**Comment by ameshkov** [comment]
YouTube Android app? I doubt DNS has ever blocked ads in the YT app, DNS is just not enough for that.
