### ISSUE TITLE
Netflix logo icon HTML code incorrect, producing a "?" icon

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardDNS#327]
The HTML code for Netflix is incorrect, producing a "?" icon.
`<div class="companyNameIconWrapper___3dml-"><div class="companyNameIcon___2xqY5" style="background-image: url(&quot;/../img/a6cacac294e68ac917000aa0d2cb3771.svg&quot;);"></div></div>`

<img width="99" alt="Screenshot 2022-08-06 at 12 25 07 am" src="https://user-images.githubusercontent.com/95468948/183099128-5b5b72b5-48a6-4e04-9b60-7536b818f639.png">

Here is the correct code, when added it works correctly:
`<div class="companyNameIcon___2xqY5" style="background-image: url(&quot;https://icons.adguard.org/icon?domain=www.netflix.com&quot;);"></div>`

<img width="113" alt="Screenshot 2022-08-06 at 12 37 33 am" src="https://user-images.githubusercontent.com/95468948/183100049-e753258c-8a4f-4c06-88c7-a6b4614a142a.png">

<img width="396" alt="Screenshot 2022-08-06 at 12 41 23 am" src="https://user-images.githubusercontent.com/95468948/183100728-c5dd6d02-dfca-4508-b4c8-dd0d2274c14b.png">

**Comment by Batman2814** [comment]
I"m getting the same thing next to Netflix with question mark

**Comment by Batman2814** [comment]
I think the problem has been fixed with the Netflix logo not showing ?
