### ISSUE TITLE
Is there a way to hide this?

### ISSUE THREAD

**Issue by As3ro** [AdguardTeam/AdguardDNS#329]
It's possible? It's… annoying.
![cattura](https://user-images.githubusercontent.com/31776296/45313676-d798b600-b52f-11e8-9afc-c6076a7cdcf4.PNG)

**Comment by karina-archazh** [comment]
Hi, 

you can block these ads by yourself using our assistant or give us a full link and we'll upgrade our filters.

**Comment by ameshkov** [comment]
@As3ro not on the DNS level, unfortunately.
