### ISSUE TITLE
Connecting a new smart TV or game console produces a blank page on step 2

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardDNS#329]
The device still gets added to the server, but does not show the connection information that would normally show for step 2 of the connection process.

<img width="1904" alt="Screenshot 2022-08-06 at 12 52 50 am" src="https://user-images.githubusercontent.com/95468948/183103059-b130d309-d434-4f06-9e55-9f9399530c4c.png">
<img width="396" alt="Screenshot 2022-08-06 at 12 53 25 am" src="https://user-images.githubusercontent.com/95468948/183103167-760c769a-b60a-4b62-a62e-8b6c584f111c.png">

**Comment by planet0** [comment]
Having the same issue with Safari Version 15.6 (17613.3.9.1.5).
Any way around this for now?

**Comment by Chinaski1** [comment]
Temporarily removed these instructions.
Detailed instructions for more devices will be coming soon.
Stay tuned :)
