### ISSUE TITLE
Add more DNS servers

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardDNS#33]
By the time of release we should add the following servers:
1 NY
1 SF
2 Netherlands

**Comment by ameshkov** [comment]
First, let's make the common configuration on all servers (here i mean bind config).

Default configuration always listens to:
`176.103.130.130`
`176.103.130.131`

Family protection always listens to:
`176.103.130.132`
`176.103.130.134`

**Comment by ameshkov** [comment]
After that set up automatic deployments to all the new servers.

**Comment by Opensourcecommunitydevelopment** [comment]
isn´t it anycasted anyway?

**Comment by ameshkov** [comment]
> isn´t it anycasted anyway?

Yep, it is. Currently our servers are located in US and RU. New locations are coming soon.

**Comment by sandybeachit** [comment]
I know you guys added the two in Netherlands have you added the NY and SF servers yet?

**Comment by vozersky** [comment]
@sandybeachit yes, we had

**Comment by sandybeachit** [comment]
Can we close this ticket as it's complete then?

**Comment by vozersky** [comment]
yep, we have added 8 new servers and that's it for now :)
