### ISSUE TITLE
AdGuard DNS not being detected by AdGuard Test website

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardDNS#330]
https://adguard.com/en/test.html

<img width="810" alt="Screenshot 2022-08-06 at 12 58 08 am" src="https://user-images.githubusercontent.com/95468948/183104356-ac895134-6d4e-4af5-bc18-af310ccd182b.png">
<img width="482" alt="Screenshot 2022-08-06 at 1 00 03 am" src="https://user-images.githubusercontent.com/95468948/183104770-0cd3b90b-0b77-4221-ba99-776a24d83d31.png">
<img width="475" alt="Screenshot 2022-08-06 at 12 59 16 am" src="https://user-images.githubusercontent.com/95468948/183104839-fa5c47eb-30ab-41b7-adcf-7d7b93fd64eb.png">
<img width="396" alt="Screenshot 2022-08-06 at 1 00 16 am" src="https://user-images.githubusercontent.com/95468948/183104854-262de766-bf89-4707-bc4b-ae1300a802d5.png">

**Comment by ameshkov** [comment]
Will be resolved in 5 minutes, thanks for reporting it!
