### ISSUE TITLE
New devices take over 15 seconds to appear on the dashboard after creation

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardDNS#331]
I tested this 3 times, with each test being around 16 seconds, ± 1 second. I feel like this should be a pretty instantaneous thing to show on the dashboard if the server addresses area already generated for the user in step 2 of the connection process.

**Comment by ameshkov** [comment]
Could it be actually a consequence of the 90-days period and statistics reload taking long time?
