### ISSUE TITLE
Many companies/icons missing from query log, but show up correctly in the companies page

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardDNS#332]
Many company names and icons seem to be missing from the query log, but show up correctly on the company page.

**Examples**
- apples.news
- outlook.com
- internode.on.net

**Companies page**
<img width="726" alt="Screenshot 2022-08-06 at 2 40 51 am" src="https://user-images.githubusercontent.com/95468948/183122745-11b4182c-24bf-426d-ab00-f5fd16ee78be.png">

**Query log**
<img width="682" alt="Screenshot 2022-08-06 at 2 41 10 am" src="https://user-images.githubusercontent.com/95468948/183122758-3da20621-562c-456a-ac6a-029ab9f0635f.png">

**Comment by ameshkov** [comment]
We should update https://github.com/AdguardTeam/companiesdb

**Comment by jslawler** [comment]
Issue is not really needed anymore as its handled in the companiesdb repo.
