### ISSUE TITLE
Unoptimal Amazon IP addresses for a Canadian ISP

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardDNS#333]
when watching tv on prime video on samsung tv and watching a show that has episodes when i click on the episode it buffers forever and I have to press return and click the episode again again before it starts to play on the 10th time. this does not happen when I disabled Adguard DNS beta so the issue lies with Adguard DNS beta. is anyone else having this problem to.

**Comment by ameshkov** [comment]
We need to know two things:
1. Your IP address (drop the last octet).
2. What exact AG DNS server you're using (open https://dns.adguard-dns.com/info.txt to check it)

**Comment by Batman2814** [comment]
what is the last octet? Please explain?

**Comment by ameshkov** [comment]
X.X.X.Y, Y is the last octet

**Comment by Batman2814** [comment]
Where would I find that on the Eero router

**Comment by ameshkov** [comment]
It does not depend on the router, just google "what is my ip"

**Comment by Batman2814** [comment]
Just give the last 5 digits of ip

**Comment by Batman2814** [comment]
Reason why I was looking in the Eero router app for my IP the my tv uses I'd that I'm away from the tv so would I be able to give you gateway Eero IP in the app. The last 5 digits

**Comment by ameshkov** [comment]
The thing is I need to know your IP address to figure out what exact DNS response we're returning to you (the response may differ depending on the IP address).

What's printed here?
https://whatismyipaddress.com/

**Comment by Batman2814** [comment]
50.70.198.102 ipv4

**Comment by ameshkov** [comment]
And the second question:)
https://github.com/AdguardTeam/AdGuardDNS/issues/333#issuecomment-1207427006

**Comment by Batman2814** [comment]
?

**Comment by Batman2814** [comment]
What do u mean second question?

**Comment by Batman2814** [comment]
second question is dns2-dp-chi-1

**Comment by Batman2814** [comment]
was that the correct information?

**Comment by ameshkov** [comment]
Yep, that's correct.

I see what's causing this, AG DNS does indeed serves unoptimal Amazon IP address for your ISP. We'll resolve this, but this will require time.

**Comment by Batman2814** [comment]
I recently put https://dns.adguard-dns.com/info.txt in my browser on my smart tv and I got a different answer from question 2 you asked which gave me dns2-dp-ch-2

**Comment by Batman2814** [comment]
my mistake dns2-dp-chi-2

**Comment by Batman2814** [comment]
When u said this will require time to fix does that mean it will be fixed in the beta or after the public release?

**Comment by ameshkov** [comment]
The public release is coming really soon so soon after it.

**Comment by Batman2814** [comment]
has this been fixed with September 7 release rollout today?

**Comment by Batman2814** [comment]
Any ideal when this bug will be fixed because it's getting annoying when trying to watch on Prime video and I watch alot of films on there. This bug has been happening more then it did when I first reported it.

**Comment by Batman2814** [comment]
Any update on when this issue will be fixed?

**Comment by Batman2814** [comment]
any Update when this issue will be fixed.

**Comment by D13410N3** [comment]
Looks like your ISP is Shaw Communications

1. Route tracing shows us a delay in 25 ms, and 24 ms of them is in your provider network. It's pretty good result for DNS
2. Looks like it's really the nearest server for your location.
3. Moreover, your ISP has almost direct peering with DNS-server in Chicago, your trace to AdGuard DNS server is very short

Summing up, if you have any problems with Amazon Prime Video while using AdGuard DNS - routing is not a reason.

**Comment by Batman2814** [comment]
Then why is the issue labeled bug because Adguard labeled it when I reported the issue last year in August?

**Comment by Batman2814** [comment]
So any idea when this bug will be fixed?

**Comment by Batman2814** [comment]
So is this issue still a bug or not? Just wondering if this GitHub issue report could be closed. Would Unoptimal Amazon IP addresses for a Canadian ISP have an issue with having "Local DNS caching" enabled on my Eero router? which is a feature that speeds up page loads for all devices by storing domain name resolutions at the network level. Would this have any negative impacts when using this with Adguard private DNS?

**Comment by Batman2814** [comment]
any idea when this issue will be fixed?

**Comment by Batman2814** [comment]
Do you have any idea when this will be fixed?

**Comment by Batman2814** [comment]
Can you check again:

IPv4: 50.71.93.241

dns2-dp-chi-1

**Comment by Eugene-Savenko** [comment]
Closing, since our team responded above: https://github.com/AdguardTeam/AdGuardDNS/issues/333#issuecomment-1548415840

**Comment by Batman2814** [comment]
Why did you close it? It hasn't been fixed.

**Comment by D13410N3** [comment]
You were answered here - https://github.com/AdguardTeam/AdGuardDNS/issues/333#issuecomment-1548415840

I will repeat you one more time: this is the most optimal route in your case.

**Comment by Batman2814** [comment]
Well, there's no label under the release notes for Adguard DNS that has been fixed, and I haven't received any confirmation that they've fixed it. I still have the problem on my network.

**Comment by D13410N3** [comment]
This WON'T be fixed because id DID NOT depends on AdGuard DNS.
You can ask your ISP about routing.

We can't do anything in your case.

**Comment by Batman2814** [comment]
The exact wording you guys said was

"I see what's causing this, AG DNS does indeed serves unoptimal Amazon IP address for your ISP. We'll resolve this, but this will require time."
