### ISSUE TITLE
not block youtube ads

### ISSUE THREAD

**Issue by lUjekSh** [AdguardTeam/AdguardDNS#335]
not block youtube ads

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard DNS server:| v1.0
| How did you setup DNS configuration:| Router
| If it's a router or IoT, please write device model:| tp link wr840n (TP-Link TL-WR841N/ND v9)
| Operating system and version:| OpenWrt Chaos Calmer 15.05

**Comment by karina-archazh** [comment]
Hi, 
what browser do you use?
Give us some more information and please add some screenshots.

**Comment by zebrum** [comment]
duplicate #324  #238
