### ISSUE TITLE
Adguard DNS blocking https://www.urbanairship.com services

### ISSUE THREAD

**Issue by SeriousHoax** [AdguardTeam/AdguardDNS#336]
I have a mobile app (Fotmob) and it uses urbanairship's services or something for push notifications.
But now I'm not receiving any. If I tap on "Test Notification" on the app it shows, "try whitelisting urbanairship.com in you Adblocker"

Screenshot: http://imgbox.com/QmBzde7X

I'm not receiving any push notification from the app. urbanairship is not an ad company, right?

**Comment by ameshkov** [comment]
> urbanairship is not an ad company, right?

This is a mobile analytics company and that's why it can't simply be unblocked as this will unblock it for all AdGuard DNS users.

Another solution would be to set up your own AG DNS server as it's explained in the repo readme.

**Comment by SeriousHoax** [comment]
I see. Okay.

**Comment by SeriousHoax** [comment]
> > urbanairship is not an ad company, right?
> 
> This is a mobile analytics company and that's why it can't simply be unblocked as this will unblock it for all AdGuard DNS users.
> 
> Another solution would be to set up your own AG DNS server and whitelist it there as it's explained in the repo readme.

A question. Can you tell me if urbanairship is added on the list recently or it's been there from before?

**Comment by ameshkov** [comment]
> A question. Can you tell me if urbanairship is added on the list recently or it's been there from before?

The company is not new, it was there for quite some time

**Comment by SeriousHoax** [comment]
Alright.
