### ISSUE TITLE
Adguard dns blocks api.jquery.com

### ISSUE THREAD

**Issue by FinnYoung** [AdguardTeam/AdguardDNS#337]
Using these dns servers: 176.103.130.132 and 176.103.130.134 
i trying to visit https://api.jquery.com
and i see: "Adguard DNS blocked this page because you use “Family protection” mode."
please unblock this website

**Comment by hmage** [comment]
After we rollout the changes in dcbe3dd4051f421553eb7782af67378f3d9ce85b on our servers, the blocking should be gone.

**Comment by hmage** [comment]
New servers are now live,  the website is no longer blocked. Thank you for reporting this @FinnYoung
