### ISSUE TITLE
Not able to use share to earn extension with Samsung Internet with Adgaurd DNS

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardDNS#337]
![Screenshot_20220815-100602_Samsung Internet](https://user-images.githubusercontent.com/96619913/184662402-2e695e38-81f1-472d-af29-ae81fcd7788e.jpg)

I'm not able to use the extension share to earn that is a add-on to Samsung Internet to get cashback when Adguard DNS is on. I switched to Google DNS in Adguard and it was able to connect and work.

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdGuardSDNSFilter #1021](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1021) via [**ZenHub**](https://www.zenhub.com/)
