### ISSUE TITLE
The Blocklist named "Perflyst and Dandelion Sprout's Smart-TV Blocklist" decreases the Wi-fi speeds on network

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardDNS#338]
When I turned that Block list off my Wi-fi speeds on the network had increased when having the blocklist on enabled my Wi-Fi network had decreased. Has anyone had this problem and can this be fixed with a future update?

**Comment by ameshkov** [comment]
How did you measure it?

**Comment by Batman2814** [comment]
I just used speedtest.net

**Comment by ameshkov** [comment]
Honestly, I don't think a blocklist may have anything to do with speedtest results. Might be a coincidence.

**Comment by Batman2814** [comment]
Would you be able to double check to make sure because everytime I had that Blocklist enable my internet speeds were slower for when I had it disabled. I been turning that Blocklist on and off to test it since the beginning of Adgaurd DNS beta. I would just like to be sure.

**Comment by ameshkov** [comment]
I've checked it on my side and saw no difference.
