### ISSUE TITLE
How to setup your own AdGuard DNS guides

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardDNS#339]
We need step-by-step instructions on how to set up your own AdGuard DNS server.

* [x] Guide for VPS  (DigitalOcean, Vultr, etc, etc)
* [x] Guide for Raspberry Pi

These guides need to be linked from the README page.

**Comment by JamesXatu2** [comment]
I think that you can use this methodology on any architecture and create an ad-hoc script for each of them by directly changing the links to download from

https://github.com/AdguardTeam/AdguardDNS/issues/283#issuecomment-427289721

**Comment by hmage** [comment]
Raspberry Pi -- https://github.com/AdguardTeam/AdguardDNS/wiki/Raspberry-Pi
VPS -- https://github.com/AdguardTeam/AdguardDNS/wiki/VPS
