### ISSUE TITLE
v2.0 - Dashboard server statistics off the page

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardDNS#340]
![image](https://user-images.githubusercontent.com/95468948/185346386-fcd974d4-2522-4df5-a999-e0d05f61abf6.jpeg)

Similar to #318, but this was introduced in v2.0.

iOS Safari: 15.6.1

**Comment by Batman2814** [comment]
I have the same problem on my samsung phone in Samsung Internet browser Google Chrome Mobile. when I'm in samsung internet browser i always have it setup to 100%. The only way i can fix it so it shows the whole screen is i change the wedpage zoom to 75% but that just makes everything smaller. never had this problem in the beta version.

**Comment by Chinaski1** [comment]
@jslawler 

Hello Justin!
Can you confirm if the issue reproduced on the latest version of the AdGuard DNS site?

**Comment by Batman2814** [comment]
The issue is still there

**Comment by Chinaski1** [comment]
Should be fixed in v2.1

Can you confirm this info? @Batman2814 @jslawler
