### ISSUE TITLE
Add "block" and "unblock" buttons to the Query Log

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardDNS#341]
Add these buttons to the Query Log as explained here:
https://uploads.adguard.com/up04_mssk9_AdGuard_DNS.png

Notify users what rule was created and where to find it.

**Comment by hmage** [comment]
@IldarKamalov let's do this on JS-side, as @ameshkov proposes.

Logic is relatively simple.

If user clicks 'block' on `www.example.com`:
1. Search in user's custom filtering rules for `@@||www.example.com^$important`, if it exists remove it.
2. If search in previous step gives no results, append rule `||www.example.com^$important` to the end of user's custom rules.

For `unblock` on `www.example.com` logic is similar:
1. Search in user's custom filtering rules for `||www.example.com^$important`, if it exists remove it.
2. If search in previous step gives no results, append rule `@@||www.example.com^$important` to the end of user's custom rules.

**Comment by hmage** [comment]
Merged in 0c3c8dba9b615355fbc7c2e68820b9cb5cd4bc5f
