### ISSUE TITLE
Statistic dates are cut off on left and right side

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardDNS#341]
![image](https://user-images.githubusercontent.com/95468948/185348476-415cb07d-8e3b-4dbb-9728-2f1fd4ba3f67.jpeg)

Dashboard was set to 90 days, but the issue occurs on each period setting.

iOS Safari: 15.6.1

**Comment by Chinaski1** [comment]
Fixed in the v2.1 update.
