### ISSUE TITLE
Dashboard is left aligned when iOS Safari is zoomed to 100%

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardDNS#342]
![image](https://user-images.githubusercontent.com/95468948/185348816-2203afc3-2b68-45a9-8b5e-daf64f5595eb.png)

iOS Safari 15.6.1

**Comment by Chinaski1** [comment]
I believe these tasks are related and the correction will be in the framework of https://github.com/AdguardTeam/AdGuardDNS/issues/340
