### ISSUE TITLE
Add a list of known hosts files and filters

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardDNS#342]
1. We can add a Wiki article
2. Link this article from the "Filters" page: https://uploads.adguard.com/up04_rq7vi_AdGuard_DNS.png

**Comment by ameshkov** [comment]
Add these but keep them disabled by default:

* `AdAway` 
    URL=`https://adaway.org/hosts.txt`
* `hpHosts - Ad and Tracking servers only` 
    URL=`https://hosts-file.net/ad_servers.txt`
* `MalwareDomainList.com Hosts List`
    URL=`http://www.malwaredomainlist.com/hostslist/hosts.txt`

**Comment by hmage** [comment]
Was done in 3a5ecb9fc132659fb9b5f738b142e0e7391fe59a.
