### ISSUE TITLE
DNS for routers are no longer being detected OR filtering

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardDNS#344]
I have 2 routers connected to AdGuard DNS with seperate DNS addresses, they are no longer being detected by AdGuard DNS and also no longer filtering ads or trackers.

I'm only using the AdGuard DNS filter for both.

I verified this by turning off all other filtering products and visiting a standard website with ads.
The ads were there.
After switching to AdGuard DNS for the device instead of the router, the ads then disappeared.

![image](https://user-images.githubusercontent.com/95468948/185352325-14bac175-ac8c-40a7-9739-33757146bbf5.jpeg)
![image](https://user-images.githubusercontent.com/95468948/185352349-036313c5-dbc2-4244-a0da-e2873bcd6912.jpeg)
![image](https://user-images.githubusercontent.com/95468948/185352377-96dfc845-c2a9-49d0-a3d7-69425f7b1058.jpeg)
![image](https://user-images.githubusercontent.com/95468948/185352400-5ce10a64-0e9b-4da6-9e39-fd1a17303c83.jpeg)

**Comment by ameshkov** [comment]
IP somehow unlinked?

**Comment by ameshkov** [comment]
Can you try using dnslookup and make a query to the addresses you're using on routers?
