### ISSUE TITLE
https://hotels24.ua/ is blocked by the Default DNS

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardDNS#345]
https://hotels24.ua/

### Expected behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/46073354-5840ee80-c18d-11e8-8b65-03430a600ecc.png)

</details>

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/46073325-419a9780-c18d-11e8-9723-dd6854d722ae.png)

![image](https://user-images.githubusercontent.com/15856304/46073395-727acc80-c18d-11e8-8442-4ea68bb5a08b.png)

</details>

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdGuardSDNSFilter #3](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/3) via [**ZenHub**](https://www.zenhub.com/)
