### ISSUE TITLE
Rename e-mail button to settings

### ISSUE THREAD

**Issue by Tealk** [AdguardTeam/AdGuardDNS#346]
I would appreciate it if you could not only delete the logs manually but also set an automatic deletion.
Currently it is also not clear how long logs are kept, so the user would have a better control and overview.

**Comment by Tealk** [comment]
> This already exists unless I'm mistaking your request?

So I clicked through the whole page again, I don't see these settings anywhere. Can you describe the path to it for me?

**Comment by Tealk** [comment]
> tap your email
thank you
ok i did not recognize this as a menu

Maybe this should be renamed to settings?

**Comment by Chinaski1** [comment]
It really sounds like a good idea. In a future update, we'll change the name to Account Settings, and just below that, we'll specify what email the account was logged in with.

**Comment by Chinaski1** [comment]
Changed in the v2.1 update.
