### ISSUE TITLE
Query Log changes

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardDNS#348]
1. [x] Move buttons up (like it's done on the dashboard)
2. [x] Change the mechanism from ring buffer to 2 rotating buckets.
3. [x] Change the label from "DNS queries log" to "Last 5000 DNS queries"
4. [x] Add a search control to the query log: search input, "blocked" checkbox (to filter only the blocked requests).
5. [x] Implement the "infinite" scroll feature (show first N records, show the next N when user scrolls down).

**Comment by hmage** [comment]
All done by a54984f6886e0bfd7b7fccc9f818c989fc084616
