### ISSUE TITLE
DNS_PROBE_FINISHED_NXDOMAIN at every first access

### ISSUE THREAD

**Issue by pdario** [AdguardTeam/AdGuardDNS#348]
I always used AdGuard on Windows and set it to use AdGuard DNS; the problem is still present now that I linked the PC to AdGuarda DNS 2.0 (https://adguard-dns.io/en/dashboard/).

When I access some URL in Chrome, say the first time in a day, I get DNS_PROBE_FINISHED_NXDOMAIN error; if I refresh the page, it loads, but it may lack some content got from external URLs; a new refresh fixes.
This is very annoying.
Moreover, many sw that does not "refresh", does not start or run because their first connection attempt fails.

Please fix this ASAP!

Thank you

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdguardForWindows #4385](https://github.com/AdguardTeam/AdguardForWindows/issues/4385) via [**ZenHub**](https://www.zenhub.com/)
