### ISSUE TITLE
Dashboard: This device is not added to AdGuard DNS. Connect it to enable DNS protection.

### ISSUE THREAD

**Issue by pdario** [AdguardTeam/AdGuardDNS#349]
I don't know why, but **sometimes** I read 

This device is not added to AdGuard DNS. Connect it to enable DNS protection.

even if I'm using a device configured to use AdGuard DNS.

**Comment by Chinaski1** [comment]
Hello there!

At that time, there were indeed issues with determining the connection status. 

This problem has now been fixed, open the task if the situation still persists.
