### ISSUE TITLE
Any more servers planned?

### ISSUE THREAD

**Issue by gurgun-dayioglu** [AdguardTeam/AdGuardDNS#35]
Wouldn’t a server in Istanbul or Ankara be very beneficial for the area? Not just for Turkey. I know lots of people who would directly switch to AG DNS if it were to be faster than Cloudflare DNS. I know it’s not possible everywhere but I saw a gap when I looked at the map with server locations.

**Comment by ameshkov** [comment]
Yeah, we'd like to add more servers in the future, but not too soon :(
