### ISSUE TITLE
vod.pl, player.pl incorrect blocking cause adblock detect 

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardDNS#350]
Adguard DNS block **required** domains for polish sites VOD.

When AdguardDNS is Active then cannot playing any content on player.pl site for example. It's showing adblock detect.

Polish filters have enabled whitelisting for:
![20181001205933-screenshot](https://user-images.githubusercontent.com/9846948/46309552-ed444d00-c5bc-11e8-9bd9-9a9b8bc1f126.png)

Site sample: https://vod.pl/playerpl-promocja/seriale-online/pulapka-odcinki,13643/odcinek-4,S01E04,113014

@AdamWr

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdGuardSDNSFilter #5](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/5) via [**ZenHub**](https://www.zenhub.com/)
