### ISSUE TITLE
Please exclude from the list

### ISSUE THREAD

**Issue by blshkv** [AdguardTeam/AdguardDNS#351]
I host my mail at mail.gandi.net. For some reason, that domain is in the ads list and is getting resolved to ```
dig mail.gandi.net @176.103.130.132

ANSWER SECTION:
mail.gandi.net.         115     IN      A       176.103.133.78
```

Please exclude that domain from the list

**Comment by ameshkov** [comment]
False positive indeed, thank you!

**Comment by blshkv** [comment]
wow, that was fast. Thank you so much for supporting it!!!
