### ISSUE TITLE
AdGuard DNS breaks Coda

### ISSUE THREAD

**Issue by tyteen4a03** [AdguardTeam/AdGuardDNS#351]
Steps to reproduce:

1. Turn off AdGuard DNS
2. Sign up for Coda on coda.io
3. Download the Coda app (https://play.google.com/store/apps/details?id=io.coda.codaapp&hl=en&gl=US)
4. Log into the app and ensure dashboard is loading
5. Turn on AdGuard DNS
6. Close the Coda app and reopen it

You will see only a turquoise background.

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdGuardSDNSFilter #1030](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1030) via [**ZenHub**](https://www.zenhub.com/)
