### ISSUE TITLE
Subscription states that it's cancelled for a 5 year AdGuard VPN plan

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardDNS#352]
This is misleading, I imagine it shouldn't say cancelled, and should probably having the cancelled part removed.

Safari Version 15.6.1 (17613.3.9.1.16)

<img width="236" alt="Screen Shot 2022-08-21 at 06 14 41" src="https://user-images.githubusercontent.com/95468948/185764631-994bac0f-d2fc-4371-b51b-6bbc6af87bd2.png">

**Comment by Chinaski1** [comment]
Fixed in the v2.1 update.

**Comment by Chinaski1** [comment]
@jslawler we just release v2.1.1 and the issue should be fixed
