### ISSUE TITLE
Problem with accessing website 

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardDNS#355]
i get this message when going to website when having Adguard personal DNS on. Not sure if it belongs under adgaurd DNS but if you could check and see if Adgaurd is the culprit.

![20220821_16315450](https://user-images.githubusercontent.com/96619913/185811935-f20db7eb-d2aa-462d-84a8-bbe5be6d35eb.png)

**Comment by ameshkov** [comment]
What website is it?

**Comment by Batman2814** [comment]
Torlock.com

**Comment by ameshkov** [comment]
Hm, the site just does not work for me at all regardless of what DNS is used. The screenshot also does not seem to be DNS-related.
