### ISSUE TITLE
is this a dead repo?

### ISSUE THREAD

**Issue by ryancastro** [AdguardTeam/AdGuardDNS#357]
Hi friends,

I notice it's been years since this project has been updated. Is it dead? Will you continue to update it in the future? It seems like the product you offer based on this has taken off, but perhaps you switched technologies since this implementation?

Just curious as I've also adopted Adguard home and I wanted to compare the two.

**Comment by ameshkov** [comment]
We're going to publish the new version's source code rather soon, we were waiting for the official release.

**Comment by ameshkov** [comment]
> Just curious as I've also adopted Adguard home and I wanted to compare the two.

Note, that they are VERY different. AdGuard Home is intended for personal use while AdGuard DNS purpose is different and there are many complications that are simply not needed in AGH.
