### ISSUE TITLE
Family Filter: directory.fsf.org is blocked.

### ISSUE THREAD

**Issue by ForkedLightning** [AdguardTeam/AdguardDNS#359]
I wonder how this got into the list... Anyways I have tested these and they are working:

fsf.org
www.fsf.org
static.fsf.org
shop.fsf.org

Only directory.fsf.org is blocked.

**Comment by karina-archazh** [comment]
Hi!
Can you check it right now?

**Comment by ForkedLightning** [comment]
It works. Thank you!
