### ISSUE TITLE
m.ciudad.com.ar - video won't play

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardDNS#36]
Example:
http://m.ciudad.com.ar/espectaculos/luciano-castro-visito-sabrina-rojas-showmatch-duelo-abdominales-marcelo-tinelli_76469

**Comment by Alex-302** [comment]
Can't reproduce with family protection.
It is slow, but video works:
![1](http://imagizer.imageshack.com/img924/7720/b5XtUc.png)

**Comment by ameshkov** [comment]
@Alex-302 could it be Safari issue? I mean guy use both Safari content blocker and DNS

**Comment by tosbsas** [comment]
You might be Right. I tried in Chrome on iPhone with DNS enabled and it works. In Safari its spinning and spinning

**Comment by ameshkov** [comment]
@Alex-302 could you please use the single content blocker? I mean not AG Safari extension, just load the content blocker extracted from iOS.

**Comment by Alex-302** [comment]
@tosbsas 
could you send me your content blocker?(through  the support. I need a ticket ID)
Also you can try to find a filter, which causes this issue. Is the issue still exists when you disable DNS filtering?

**Comment by sandybeachit** [comment]
The video plays fine for me on adguard DNS default settings can we close this as it's now resolved?

**Comment by vozersky** [comment]
@zebrum please re-check it

**Comment by zebrum** [comment]
with both Adguard default and Family Protection DNS video plays ok in safari.
