### ISSUE TITLE
Filter exceptions are shown as unblocked by user rules

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardDNS#361]
In this example I was using AdGuard DNS filter.

When visiting a site in the exceptions.txt file, the query log shows the website has been unlocked.

When the unblocked status is tapped, it says unblocked by user rule.
This is false, and should not say that it's unblocked by a user rule.

![image](https://user-images.githubusercontent.com/95468948/187050681-28f606d1-65a8-4cfa-a33c-1e2e4a476916.png)

**Comment by Chinaski1** [comment]
Fixed in the v2.1 update.
