### ISSUE TITLE
Blocked services and websites section in Parental Control gives no indication that it's a scrollable field

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardDNS#363]
In the Parental Services page, there's no indication that the Blocked services and websites field may be a scrollable area until you start scrolling.

As there are no other pages that have a scrolling field like this in AdGuard DNS it stands out considerably.

I'd suggest either showing the area with a different shade background to indicate the size of the scrollable field, or remove it entirely and just having it as a pop up when the user taps Manage services like every other function like it on AdGuard DNS.

https://user-images.githubusercontent.com/95468948/187574067-00c9aef7-fe8c-4e04-9eac-f13906da7e04.MOV

**Comment by Chinaski1** [comment]
Similar logic is used on all AdGuard DNS settings pages.
The scrollbar is initially invisible, but as soon as you scroll through the page it appears and disappears after a few seconds of activity.
