### ISSUE TITLE
Add more known trackers to the known trackers list

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardDNS#365]
* Domain: `crashlytics.com`
* Company: Google

* Domain: `flurry.com`
* Company: Yahoo

* Domain: `hockeyapp.net`
* Company: Microsoft

* Domain: `app-measurement.com `
* Company: Google

* Domain: `appsflyer.com`

**Comment by hmage** [comment]
Fixed in 2f61b42e9048e9d6e1f31d7ed37611afa2418a6e
