### ISSUE TITLE
Query log data cutoff in desktop mode

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardDNS#366]
Is there a better way that all data can be shown on the page rather than being cutoff?
Specifically for the date/time, it feels kinda of pointless presenting the information if it's going to be cutoff for most of the year.

Maybe a expanded view for each query might be better, something similar to AdGuard Home's query log which utilises 2 lines for each query so information isn't too compact or runs off the page.

<img width="1154" alt="Screenshot 2022-09-01 at 21 19 21" src="https://user-images.githubusercontent.com/95468948/187902731-155e038e-8cea-4dc5-a9d4-7a9dbbff4161.png">

**Comment by Chinaski1** [comment]
Hello!
Sounds like a good idea, especially the date and time block, we will think about implementing this feature

**Comment by Chinaski1** [comment]
Changed in the v2.1 update.
