### ISSUE TITLE
macOS/iOS configuration profile name simplification

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardDNS#367]
The current configuration profile naming is overly complex for what it really needs to be.

Given that the current profile name is "d.adguard-dns.com DoH/DoT", this isn't a lot of use to an end user.

It would likely make more sense to just having some text such as "AdGuard DNS ("device identifier")", which tells the user that it's clearly a configuration profile for AdGuard DNS, with their device identifier, without any form of overly technical information user facing.

<img width="199" alt="Screenshot 2022-09-03 at 00 06 19" src="https://user-images.githubusercontent.com/95468948/188166823-99dec9f3-65ef-490e-981e-9565b6b5ad2d.png">

**Comment by zeezeepiggy** [comment]
I really hope they implement this soon in a more simpler and understandable naming convention.

**Comment by Chinaski1** [comment]
We managed this daunting task after 2 years. Easy
