### ISSUE TITLE
Requests are "filtered by safesearch" despite that it's not enabled

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardDNS#368]
Here it is:
https://uploads.adguard.com/up04_nb1tf_AdGuard_DNS.png

Reproduced on my private server.

**Comment by ameshkov** [comment]
I am getting it when a request is blocked by a hosts file.

**Comment by ibksturm** [comment]
same bug here with 0.91

**Comment by ameshkov** [comment]
@ibksturm what are the exact steps to reproduce it? I can't reproduce it on v0.91
