### ISSUE TITLE
Adguard DNS breaks Cartoon Network Roku App

### ISSUE THREAD

**Issue by BlohoJo** [AdguardTeam/AdGuardDNS#37]
No videos will play on Cartoon Network Roku App when using Adguard DNS on main router. All videos will only show "Something went wrong" screen. Confirmed by switching back to ISP DNS, and Cartoon Network Roku app functions normally again.

**Comment by Alex-302** [comment]
Hi
I don't have Roku device.
Could you, please, setup AdGuard Home DNS on PC, configure Roku to use AdGuard Home DNS and collect DNS log?

**Comment by BlohoJo** [comment]
The AdGuard Home guide export's log file is all on one line and is delimited with several characters. It needs to have an easy to read output option.

I attached screenshots of the log from the web interface. I ran the Cartoon Network app on Roku and let it try to play several videos in a row. They all failed, showing "Something went wrong." It appears that the filter causing the issue is `||auditude.com^`, from the _AdGuard Simplified Domain Names filter_. When a video fails to play it is trying to contact manifest.auditude.com which is blacklisted by this filter.

![AdGuard_CartoonNetwork_Roku_DNSLog](https://user-images.githubusercontent.com/8242464/59678088-7b875000-9199-11e9-8695-82f19c503191.png)
![AdGuard_CartoonNetwork_Roku_Rule](https://user-images.githubusercontent.com/8242464/59678089-7b875000-9199-11e9-94b9-53aa215d6a50.png)

**Comment by Alex-302** [comment]
Not sure if this domain must be excluded completely.
<details>
ad.auditude.com
adfiles.auditude.com
cdn.auditude.com
cdn2.auditude.com
manifest.auditude.com
otcdn2.auditude.com
</details>

@BlohoJo thanks. Could you please unblock `manifest.auditude.com` only and check again?

**Comment by BlohoJo** [comment]
I apologize, I have no idea why I didn't think to do that. Sorry for the delay.

Yes, unblocking only `manifest.auditude.com` fixes the Cartoon Network Roku app, and it functions normally again. (It unfortunately doesn't block ads, despite seeing ad.auditude.com blocks in the DNS log... it's likely one of those apps where ads can't be completely blocked.)

![AdGuard_CN_Fixed](https://user-images.githubusercontent.com/8242464/59728886-e83a3300-9209-11e9-9c65-6c836cf8fc22.png)

**Comment by Alex-302** [comment]
Great. Thanks. Fixed.

Could you, please, try to block these domains and check this app?
`ads.roku.com`
`http://logs.roku.com`

**Comment by BlohoJo** [comment]
Again, sorry for the delay... still waiting for the fix on the main servers. (I'm using 176.103.130.130 and 176.103.130.131.) Still not fixed. How long does it typically take changes to propagate?

**Comment by BlohoJo** [comment]
Roku seems to run fine (I didn't check it extensively) with `ads.roku.com` and `logs.roku.com` blocked. Cartoon Network and Adult Swim apps work with those two blocked. But they do still play ads.

Here is Cartoon Network loading its initial video successfully, then an Adult Swim title being played, which shows a 15 second ad first. `ads.roku.com`, `captive.roku.com`, and `logs.roku.com` are all blocked:
<details>
![adguard1](https://user-images.githubusercontent.com/8242464/59958653-19b83600-9478-11e9-9ed0-33e7c6c7c1a2.png)
</details>
.

I know that Tubi, another "free" app that plays content with ads, still has ads with AdGuard DNS. I checked this one, and found that the domain `ads.adrise.tv` was not filtered. Blocking this domain seems to have stopped ads on Tubi. Blocking the entire adrise.tv domain makes the Tubi app not load at all.

Here is Tubi with all of the above plus `ads.adrise.tv` added to the blocklist. Several titles were successfully played without ads showing first, which it normally does:
<details>
![adguard2](https://user-images.githubusercontent.com/8242464/59958661-32285080-9478-11e9-8185-3f9796a890d3.png)
</details>
.

The Youtube app is another one where ads still play using Adguard. I checked and it appears that YouTube ads are either coming from a direct IP or from the same googlevideo.com domains as regular content so it probably isn't possible to block ads on YouTube with Adguard DNS. I tried adding `captive.roku.com` to the blocklist and while Roku still appears to function with that domain blocked it doesn't have any effect on ads, at least on YouTube.
<details>
![adguard3](https://user-images.githubusercontent.com/8242464/59958671-52580f80-9478-11e9-8122-61a9eb70b8fc.png)
</details>

Since you say Roku isn't really being checked, maybe this thread should be the Roku thread? Or there should be either an "official" or "non official" thread for Roku and Roku apps, since Roku has no advanced Network settings, the only way to block is Adguard DNS on the main router.

**Comment by BlohoJo** [comment]
I tried adding some of the other blocklists into Adguard Home. That seems to block YouTube ads. It appears `ade.googlesyndication.com` is important, that comes from hpHosts. Adult Swim ads still play however, even with all four filters enabled (AdAway, hpHosts, and MalwareDomainList.com).

**Comment by Alex-302** [comment]
Hi
Some ads are loaded from domains, which cannot be blocked safely. For example - `fwmrm.net`. In some apps ads cannot be blocked, because they are using the same domain for useful content ans ads(YouTube app and site)

> How long does it typically take changes to propagate?

usually less than 24 hours. But it seems my changes are not works, as I see auditude.com is blocked with all sub-domains.
