### ISSUE TITLE
picarto.tv - incorrect blcoking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardDNS#37]
При использовании "Семейного" варианта стал блокироваться сайт picarto.tv, 
сайт со стримами художников:
1. Проблема проявляется с конкретным сайтом (Picarto.tv) на всех браузерах.
2. Установить ADGuard DNS "Семейный" в свойствах сетевой карты, роутера, 
   модема и тп.
3. Скриншоты сравнения ADGuard DNS "Семейный" и Yandex DNS "Семейный" 
   прилагаю.

<details>
adg dns
![image](https://cloud.githubusercontent.com/assets/15856304/18082111/5b4c9128-6e6b-11e6-8d4f-539c04c87746.png)

yandex dns
![image](https://cloud.githubusercontent.com/assets/15856304/18082118/646fed0e-6e6b-11e6-9b4a-b22ee2fa6f08.png)

</details>
1403292

**Comment by sandybeachit** [comment]
Is this still an issue?

If not can we close this ticket ?

**Comment by zebrum** [comment]
can not reproduce the issue with Adguard family DNS.
