### ISSUE TITLE
Problem with weather.com (mparticle.com) - solved by old.reddit.com

### ISSUE THREAD

**Issue by Rusenche** [AdguardTeam/AdGuardDNS#370]
https://old.reddit.com/r/uBlockOrigin/comments/x3fskl/problem_with_weathercom/ - open this address, read the reviews and be sure of the decision.

https://old.reddit.com/r/uBlockOrigin/comments/x3fskl/problem_with_weathercom/imte4mf/

> After many tests it turned out that...

> The problem for me was that in the settings of Chromium v.105.0.5195.54 in Settings -> Privacy and security -> Security -> Use secure DNS -> Custom -> **https://dns.adguard.com/dns-query** or **https://dns-family.adguard.com/dns-query**.
> 
> Adding either DNS-over-HTTPS:
> 1. **https://dns.adguard.com/dns-query**;
> 2. **https://dns-family.adguard.com/dns-query**

1. https://i.postimg.cc/j2m1NjMX/1.png
2. https://i.postimg.cc/DfMHRC7X/2.png

> **was causing the _weather.com_ search bar to be unable to type/use.**
> 
> Hope this helps someone, because I was surprised that the problem was caused by adding Adguard DNS-over-HTTPS to the browser.

**I hope you will take a stand on this particular issue in this thread so we can get back to using your Adguard DNS-over-HTTPS to the browser.**

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdGuardSDNSFilter #1034](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1034) via [**ZenHub**](https://www.zenhub.com/)
