### ISSUE TITLE
What is backend URL?

### ISSUE THREAD

**Issue by shahidcodes** [AdguardTeam/AdGuardDNS#371]
I am trying to run adguard locally. I was able to go till build step. 
what is this https://github.com/AdguardTeam/AdGuardDNS/blob/master/doc/externalhttp.md#backend and where to obtain this from?

**Comment by ameshkov** [comment]
Hi, you need to supply your own implementation since API server is not open source (too much internal billing logic there).

The easiest way would be to run a simple HTTP server that serves JSON files with the structure explained in the documentation.
