### ISSUE TITLE
Getting Error message

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardDNS#372]
When I have Adguard Personal DNS enabled in Adguard VPN for custom DNS i get this meesage.
I have Adgaurd Adblocker installed on my laptop with Adgaurd Personal DNS

![20220905_15005390](https://user-images.githubusercontent.com/96619913/188507994-02d04213-e474-417a-bcb8-62449703ca34.png)

**Comment by ameshkov** [comment]
Is it a stable issue?

**Comment by ameshkov** [comment]
Could you please elaborate on your exact configuration?

Platform, applications versions, browser (I guess it's Firefox)

**Comment by Batman2814** [comment]
It's Adgaurd Nighlty for windows which I'm using because Adgaurd VPN Stable for windows is having troubling taking forever to connect and disconnect. I use quic protocol Adguard private DNS in the custom DNS. 

Its Firefox and google Chrome it is happening in 
Firefox Version: 104.0.1 (64 bit Windows 11)
Google Chrome: Version 105.0.5195.102 (Official Build) (64-bit)
Adgaurd Adblcoker for Windows Version: 7.10.2
Adgaurd VPN for Windows version Nightly: 2.0629.0

**Comment by Batman2814** [comment]
its works fine if I use surfshark VPN when Adgaurd is not working.

**Comment by adbuker** [comment]
@Batman2814 , as I can see you faced with two problem
Frist - 
>When I have Adguard Personal DNS enabled in Adguard VPN for custom DNS i get this meesage.

could please also specify
1. Does the issue persist, if you are using Adguard without AdGuardVPN and visa versa?
2. Does the issue persist, if you aren't using DoQ server (only DoH, DoT, etc.)?
3. Please grab and send the "trace" logs (instruction [here](https://kb.adguard.com/windows/solving-problems/adguard-logs)) to the devteam@adguard.com with the issue number in the letter's label. Please specify "timestamp" when the problem occurred
4. Is this issue appear frequently (or even stable) or too rare and depend on some pre-conditions (e.g. just after first application start, after waking up from the sleep-mode, etc.)

Second
>is having troubling taking forever to connect and disconnect 

1. Have you got any "cloud"-related application installed? I mean Google Drive etc. If so, please add them to the "App exclusions"
2. If you face this issue - the only thing you can do to exit the routine it's just kill the process, isn't it?

**Comment by Batman2814** [comment]
1.) I sent the Adguard Logs to the email.

2.) I do not of google drive on my laptop but I do have Microsoft Onedrive
my Bitdefender security has Online threat prevention which is cloud based for when serving the web in browser.

**Comment by adbuker** [comment]
@Batman2814 , 
1) thanks, but could you provide with the answers for the rest questions
2)ok, great, could you add Microsoft Onedrive and Bitdefender to the "App exclusions" and what about 2nd questions?

**Comment by adbuker** [comment]
@Batman2814 , btw, the logs yo've sent is not a trace logs, unfortunately. Could you please follow the instructions [how to grab **trace** logs](https://kb.adguard.com/windows/solving-problems/adguard-logs). It's very important to grab trace logs in order to find out the reason

**Comment by Batman2814** [comment]
> 
 for the 2nd question when you say DoQ Server (only DoH, DoT) do you mean the protocol DNS over QUIC, DNS over TLS, DNS over Https is active your asking

**Comment by Batman2814** [comment]
correct logs have been sent. confirmation would be nice if you can.
I believe the issue happened when I woke my laptop from sleep mode it was the only was to reproduce it.

**Comment by Batman2814** [comment]
Any idea when this issue will be fixed I'm still getting the page error pop-up.
