### ISSUE TITLE
Parental Services isn't blocking https://www.snapchat.com when enabled

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardDNS#376]
1. Enable Parental Services
2. Enable Snapchat in Blocked Services
3. Visit https://www.snapchat.com

I confirmed this against FaceBook, and Facebook.com couldn't be loaded, as expected.

Also, is there a location for these parental services lists?
I couldn't find them on GitHub.

**Comment by ameshkov** [comment]
Here it is:
https://github.com/AdguardTeam/HostlistsRegistry/blob/main/assets/services.json

**Comment by ameshkov** [comment]
There's a possibility that it's loaded from the service worker's cache.

Try incognito tab to verify.

**Comment by ameshkov** [comment]
Cannot reproduce this so far. Both `snapchat.com` and `www.snapchat.com` are blocked for me.

**Comment by ameshkov** [comment]
Tbh I have no idea save for cache (or maybe it's private relay all over again).
