### ISSUE TITLE
increase TTL interval

### ISSUE THREAD

**Issue by bmbshlly** [AdguardTeam/AdGuardDNS#379]
The TTL (time to live) ranges from 0 to 3600 seconds. Can you increase the range to 1 year? If not why?

**Comment by ameshkov** [comment]
This TTL is only used for blocked requests, increasing it up to 7 days will lead that the blocked response will be cached for a long time and even when the blocklist is updated, the changes in it will only be applied after the cache is manually cleared or after 7 days.

**Comment by bmbshlly** [comment]
@ameshkov i don't mind cache getting updated for 7 days. I hardy update the list so want a long caching time?
