### ISSUE TITLE
Add a block page with a link to report a page that shouldn't be blocked

### ISSUE THREAD

**Issue by Sloppyedwards** [AdguardTeam/AdguardDNS#38]
I like the idea of the Adguard DNS, and I was trying the Family Protection servers.  However, I've encountered too many links (like hyperlinks from emails) that won't load.

For now, I've switched to the OpenDNS Familyshield servers.

I suggest you add a block page when a page is blocked by the DNS server, and provide a link for reporting a page/domain that is believed to be blocked in error.

**Comment by Snapy** [comment]
FYI OpenDNS has a block page which can be customized and include a way to contact the administrator.

**Comment by ameshkov** [comment]
@Snapy what do they do for blocked HTTPS websites?

**Comment by Snapy** [comment]
@ameshkov This [support page](https://support.opendns.com/entries/21909235-Blocking-https-site) says https is blocked (as is http). I suppose they also display the block page.

**Comment by ameshkov** [comment]
@Snapy the problem is that when website is accessed via https we can't display the block page content as the block page won't pass https verification.

**Comment by ameshkov** [comment]
Ah, ok, I see.

All blocked domains are resolved to 146.112.61.106, which in turn simply redirects you to block.opendns.com.

For plain HTTP it works as intended.

For HTTPS you'll see certificate error: 
<details>
![privacy error 2016-09-12 11-26-56](https://cloud.githubusercontent.com/assets/5947035/18429409/cfb7fa3c-78db-11e6-8252-e3bfe36c3451.png)
</details>

I guess there's no better option, so we'll do the same.

**Comment by ameshkov** [comment]
@nkartyshov for this page use the same page layout as in AG for Windows parental control module.

Add a simple javascript there:
1. If domain name is not "block.dns.adguard.com" redirect user to that domain (pass url in parameter).
2. If domain name is "block.dns.adguard.com", show the block page content.
3. There should be a "mailto:" link allowing send a complaint.

Set appropriate subject and body of the mailto link:
http://stackoverflow.com/questions/4782068/can-i-set-subject-content-of-email-with-using-mailto

**Comment by nkartyshov** [comment]
done
