### ISSUE TITLE
AdGuard DNS seems to have stopped recording queries over the last few hours

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardDNS#380]
This is also being reported on Telegram.

<img width="1132" alt="Screenshot 2022-09-14 at 18 28 26" src="https://user-images.githubusercontent.com/95468948/190103013-4c5e3d49-85b9-4404-839e-90873004e3ee.png">
<img width="650" alt="Screenshot 2022-09-14 at 18 30 33" src="https://user-images.githubusercontent.com/95468948/190103264-f282b5ea-18dc-4183-b8e7-f7c11fbfe7bf.png">

**Comment by ameshkov** [comment]
Is the issue still there? Logs ETL is not real-time so if there's any issue with transferring logs there may be a delay.

**Comment by ameshkov** [comment]
Probably the connectivity between the server in Sydney and the central API is flapping.

**Comment by ameshkov** [comment]
The good thing is that nothing is lost when it happens, the logs will eventually be transferred :)
