### ISSUE TITLE
Disney Plus app won't work

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardDNS#388]
![20220926_072402](https://user-images.githubusercontent.com/96619913/192277474-b26774d4-2252-41f5-9ab5-ea430bde073f.jpg)

I'm not able to use the Disney plus app on my Samsung TV or Amazon fire TV stick 4k max.

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdGuardSDNSFilter #1052](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1052) via [**Zenhub**](https://www.zenhub.com/)
