### ISSUE TITLE
DNS-over-HTTP/3 (DoH3) support

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardDNS#389]
Hello,

please add DNS-over-HTTP/3 support. For example, NextDNS has an DoH3 endpoint so you can try to test it too:
https://doh3.dns.nextdns.io/subscription_id/clients_id
https://help.nextdns.io/t/y4hfw14/cant-use-doh3

Now I use NGINX for this purpose, but I want to see native support of upstream DNS servers from AdGuard🥹

Thank you.
Best regards!🎃

**Comment by Chinaski1** [comment]
Hello there!

Yes, we plan to add HTTP/3 support in future updates.

**Comment by ammnt** [comment]
Works perfect now. Thank you!
