### ISSUE TITLE
Adguard DNS fails to load timesofindia.indiatimes.com

### ISSUE THREAD

**Issue by kuttan85** [AdguardTeam/AdguardDNS#39]
Adguard DNS fails to load timesofindia.indiatimes.com website links which uses constantly updated Anti-Adblocker technologies and there is no alternative other than disabling Adgurad DNS to browse such sites.

http://timesofindia.indiatimes.com/us-elections-2016/Trump-threatens-remittance-blackmail-to-fund-border-wall-with-Mexico/articleshow/53964815.cms

Hope Adguard able to overcome sites that uses Anti-Adblockers.

**Thank You.**

**Comment by ameshkov** [comment]
Hi! Do you mean there is an anti-adblock message there?

**Comment by kuttan85** [comment]
Hi,

Now the site working fine with Adguard DNS. Yes when I made the comment here the site prompted me to disable my Adblocker in order to browse the site. Recent days many Indian news sites made very aggressive usage of  Anti-Adblocker scripts which they updates them frequently in order to bypass Adblockers attempts to bypass them. 

Thank You
