### ISSUE TITLE
Disable TLS session resumption

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardDNS#393]
Hello,

please think about disable TLS session resumption:
https://success.qualys.com/discussions/s/question/0D52L00004TnuEQSAZ/how-session-tickets-will-compromise-pfs
https://timtaubert.de/blog/2014/11/the-sad-state-of-server-side-tls-session-resumption-implementations/

Thank you.
Best regards!😋

**Comment by ameshkov** [comment]
We definitely won't do that.
