### ISSUE TITLE
Discovery of Designated Resolvers (DDR) support

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardDNS#396]
Hello,

I can't find any information about this for AdGuard DNS, so please add Discovery of Designated Resolvers (DDR) support:
https://datatracker.ietf.org/doc/draft-ietf-add-ddr/
https://blogs.cisco.com/networking/improving-dns-security-while-preserving-resiliency

Thank you.
Best regards!😬

**Comment by ameshkov** [comment]
AG DNS supports DDR.
