### ISSUE TITLE
(Email) Action needed: Your device is not active

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardDNS#397]
On 19 September, I deleted an AdGuard DNS config from one of my iOS devices that hasn't been used with AdGuard DNS for well over 6 months now.

I've just received an email stating that the device is no longer active.

It seems that the AdGuard DNS reminder email service is being prompted to send out emails regardless of whether the device is added to AdGuard DNS or not.

![image](https://user-images.githubusercontent.com/95468948/192388220-9e0ea336-1f2f-4507-857b-7965197eeddd.jpeg)

**Comment by ameshkov** [comment]
Is this device still visible on AG DNS dashboard with zero stats or have you removed it from there too?
