### ISSUE TITLE
nnmclub.to - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardDNS#4]
![image](https://cloud.githubusercontent.com/assets/15856304/17165889/44038444-53dc-11e6-8b5b-5066794a7baf.png)
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/17165905/6414c342-53dc-11e6-89c8-9539258082b0.png)

</details>
DNS прописаны в
роутере (чистку кеша браузера и dns делал)
**952965**

**Comment by Alex-302** [comment]
Добавил:
||nighter.club^
||trafmag.com^
||marketgid.com^
||directadvert.ru^
||betweendigital.com^
Но реклама на скрине на самом сайте хранится.
