### ISSUE TITLE
Ping for asia country too slow

### ISSUE THREAD

**Issue by ookangzheng** [AdguardTeam/AdguardDNS#40]
I live in Japan, Taiwan, Hongkong ~~ Used Adguard DNS for nearly 2 months. My friends and I love it, but one issue is ping to the Adguard DNS Server too slow ~~ 
Hope can add some server in Asia country

**Comment by ameshkov** [comment]
It should be a bit better after we add 2 more US servers.

As I understand, currently you are using the east coast server, connection to the west coast server will be a bit faster.

We will add asian servers eventually, it's just we need more time to do it.

**Comment by ookangzheng** [comment]
in witch city ?

**Comment by ameshkov** [comment]
> in witch city ?

You mean in which asian city? No idea yet.

I am thinking about Singapore, I hope it will allow us cover both Asia and Australia.

**Comment by TPS** [comment]
I suppose following #33 should keep 1 updated on all the new DNS server deployments.

**Comment by KrasnayaPloshchad** [comment]
I think add servers on Asian countries would help.

**Comment by vozersky** [comment]
@ookangzheng  We have added 2 servers in Singapore, it has to be better now, please test when you have a chance
