### ISSUE TITLE
Trackers

### ISSUE THREAD

**Issue by trackerct** [AdguardTeam/AdGuardDNS#401]
Can you add blocklist please?

Trackers by Vivo Mobile (have a couple of dns queries)

tr-vcode-od.vivoglobal.com
tr-vcode-api.vivoglobal.com
tr-st-sl.vivoglobal.com
tr-domaincfg.vivoglobal.com
tr-timesync.vivoglobal.com
tr-romsp-unifyconfig.vivoglobal.com
asia-ex-adlog.vivoglobal.com
asia-analyzer-appstore.vivoglobal.com
asia-exstsdk.vivoglobal.com
asia-comort-stsdk.vivoglobal.com
asia-comonrt-stsdk.vivoglobal.com
asia-analyzer-appstore.vivoglobal.com

Trackers by Vodafone

netperform-is.vodafone.com.tr
vodafonetr.sc.omtrdc.net
mplusps.ims.vodafone.com
mpluswf.ims.vodafone.com

Advertising
advertise.ldplayer.net
creative.eagllwin.com
api.eagllwin.com
storeen.ldmnq.com

Google Spyware (have a couple of dns queries)

telephonyspamprotect-pa.googleapis.com
growth-pa.googleapis.com
deviceintegritytokens-pa.googleapis.com
gmscompliance-pa.googleapis.com
mdh-pa.googleapis.com
firebaseinstallations.googleapis.com
digitalassetlinks.googleapis.com
tags.tiqcdn.com

**Comment by ameshkov** [comment]
Should be reported to https://github.com/AdguardTeam/AdGuardSDNSFilter

Please don't just spam domain names, make sure something from that is not blocked.
And if it should be blocked, we'll need an explanation of what this domain is, how is it used and why it should be blocked.
