### ISSUE TITLE
Public DNS cant connect to webpage

### ISSUE THREAD

**Issue by aIemtro** [AdguardTeam/AdGuardDNS#403]
I have public dns configurated in my router
I tried to open the pages:

https://mise.ccss.sa.cr/MISEAutogestion/olvidoClave

can't solve the name and with provider DNS or Google for example it solve the name

Should be nice if can add it in whitelist

**Comment by ameshkov** [comment]
Something seems to be very wrong with the domain itself.

It cannot be resolved neither by AdGuard DNS, nor by Google, nor by Cloudflare.

You should probably contact the domain owners to resolve this.
