### ISSUE TITLE
EDNS improvements

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardDNS#404]
Hello,

please add these EDNS improvements:
- EDNS0 TCP keepalive Option:
https://datatracker.ietf.org/doc/html/rfc7828
https://datatracker.ietf.org/doc/html/rfc7830

- EDNS0 Padding Option:
https://datatracker.ietf.org/doc/html/rfc8467

Thank you.
Best regards!😬

**Comment by ameshkov** [comment]
Padding improvements will be rolled out with v2.1.4.
EDNS0 TCP keep-alive is actually supported.
