### ISSUE TITLE
theme.shalltry.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdGuardDNS#409]
### Steps to reproduce

1. Go to themes app in aby infinix phone 
2. See bug the themes are nit loading because theme.shalltry.com is blocked.

### Expected behavior
Not Blocked

### Actual behavior
Blocked

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdGuardSDNSFilter #1060](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1060) via [**Zenhub**](https://www.zenhub.com/)
