### ISSUE TITLE
Can't download from rusfolder.com with JDownloader

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardDNS#41]
При использовании Adguard DNS (адреса прописаны в роутере) происходит блокировка загрузки файлов приложением [JDownloader](http://jdownloader.org/) с rusfolder.com

Другие файлообменики работают нормально.

В браузерах (Яндекс, Сафари) такой проблемы не наблюдается, при использовании Adguard DNS. Только в приложении JDownloader.

Служба поддержки приложения JDownloader сообщила, что это связано с блокировкой api.adverigo.com/127.0.0.1:80

Действительно, при удалении адресов Adguard DNS, работа JDownloader с rusfolder.com восстановилась.

**Comment by Alex-302** [comment]
какие адреса прописаны? Это важно.

**Comment by Alex-302** [comment]
Исключил этот домен. Часа через два-три можно будет проверять.
