### ISSUE TITLE
Missing DNS entry

### ISSUE THREAD

**Issue by helledi** [AdguardTeam/AdGuardDNS#411]
The domain csf.tools seem to be missing from the 94.140.14.14 and the 94.140.15.15 servers.

**Comment by ameshkov** [comment]
Can't confirm:
```
dnslookup csf.tools tls://94.140.14.14
dnslookup v. 1.8.0
dnslookup result:
;; opcode: QUERY, status: NOERROR, id: 47662
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;csf.tools.	IN	 A

;; ANSWER SECTION:
csf.tools.	86387	IN	A	35.209.88.35
```

Please tell me what you see when you open https://dns.adguard-dns.com/info.txt

The issue may be specific to some location.

**Comment by Chinaski1** [comment]
@helledi 

Any news?

**Comment by Chinaski1** [comment]
Closed due not reply
