### ISSUE TITLE
adguard dns 2.0

### ISSUE THREAD

**Issue by ijuliank** [AdguardTeam/AdGuardDNS#415]
more like a feature request/addon (its no issue)
![image](https://user-images.githubusercontent.com/64658680/194729220-c262e639-9f95-4456-a63a-1f04b9571efb.png)
i hope adguard will introduce in the future unlimited queries

**Comment by Chinaski1** [comment]
To unblock unlimited requests you can buy an enterprise plan

https://uploads.adguard.org/Chinaskiao7zn.png
