### ISSUE TITLE
In Germany but always routed to Singapore/Asia

### ISSUE THREAD

**Issue by derKief** [AdguardTeam/AdGuardDNS#417]
Some problem like #416

Atm DNS request are routed to Singapore/Asia instead to Frankfurt/Germany.
This happend a few days ago. Before everything was routed correctly to Frankfurt (for Germany)

In my case provider is Vodafone DE

>   1     1 ms     1 ms     1 ms  FB6660 [192.168.xxx.xxx]
>   2     *        *        *     Zeitüberschreitung der Anforderung.
>   3     8 ms    10 ms    10 ms  ip-xx.xx.xx.xx.um21.pools.vodafone-ip.de [xx.xx.xx.xx]
>   4    15 ms    18 ms    17 ms  de-str01c-rc1-ae-46-0.aorta.net [84.116.197.133]
>   5    15 ms    13 ms    15 ms  de-fra04d-rc1-ae-10-0.aorta.net [84.116.140.205]
>   6    15 ms    15 ms    15 ms  84.116.190.94
>   7    13 ms    13 ms    15 ms  ae32-100-pcr1.fnt.cw.net [195.2.18.217]
>   8    30 ms    30 ms    31 ms  ae9-xcr1.mrx.cw.net [195.2.25.189]
>   9   179 ms   181 ms   180 ms  ae3-xcr1.sng.cw.net [195.2.30.150]
>  10   185 ms   181 ms   179 ms  217.161.92.98
>  11   189 ms   190 ms   188 ms  vl211.sgp-eq3-core-1.cdn77.com [138.199.0.220]
>  12   190 ms   191 ms   188 ms  dns.adguard.com [94.140.15.15]

**Comment by D13410N3** [comment]
Hello. Thanks for your report. We'll try to fix it. If you have IPv6 configured, can you please provide traceroute for it too? 

`traceroute6 2a10:50c0::ad1:ff`

**Comment by derKief** [comment]
No IPv6 here ... sorry.
Hopefully you get this working correctly asap 
Like it is atm ADGuard DNS isn't usable for me. Latency way to high for DNS.

**Comment by D13410N3** [comment]
Okay, I was asking you about IPv6 traceroute in case you're using it. If no - IPv4 is enough

This is some issue on transit-provider, not our fault, but we can try to fix it by ourself. I'll contact you when we'd find some solution

**Comment by derKief** [comment]
OK ... thanks for feedback

**Comment by D13410N3** [comment]
@derKief Hello!
Issue should be resolved now - can you please check?

**Comment by derKief** [comment]
@D13410N3 
everything is working fine now. Hopefully this is a permanent solution ;-)
Thanks a lot for your support.

**Comment by D13410N3** [comment]
Thanks for your feedback
