### ISSUE TITLE
Adgaurd DNS disconnecting in Adguard VPN Nightly

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardDNS#424]
when I have Adguard private DNS setup in Adguard  VPN Nightly it disconnects and my browser can't load any websites. it just keeps showing the loading symbol. the only way to fix it is to disconnect it and connect Adgaurd VPN when adguard DNS is setup in it.

**Comment by Chinaski1** [comment]
@Batman2814 

Hello there!
Please specify what platform and version of AdGuard you are using.

**Comment by Batman2814** [comment]
Windows 11 Home Version 21H2
Adguard Adblocker version 7.10.2
Adguard VPN Nightly Version 2.0.678.0
