### ISSUE TITLE
"AdGuard DNS does not support HTTP/2" error 10/18/2022

### ISSUE THREAD

**Issue by Ry0OBSSc9H8VjeVE** [AdguardTeam/AdGuardDNS#425]
YogaDNS began displaying "AdGuard DNS does not support HTTP/2" error for all AdGuard DoH servers about 2 days ago. Cloudflare and Quad9 DoH servers did not show this error. This happened before (a long time ago) and it was something about AdGuard DNS configuration, not YogaDNS. 

Here's a debug log for [https://94.140.14.14/dns-query]:
DnsCrypt log: Refreshing certificates
_**DnsCrypt log: [https://94.140.14.14/dns-query] does not support HTTP/2**_
DnsCrypt log: [https://94.140.14.14/dns-query] TLS version: 303 - _**Protocol: http/1.x**_ - Cipher suite: 49195
DnsCrypt log: Advertised cert: [CN=dns.adguard.com] [929e3bd4d1546713bac4bc89496afba92d2d65dc4652fb73e10f7968adc74ae5]
DnsCrypt log: Advertised cert: [CN=ZeroSSL ECC Domain Secure Site CA,O=ZeroSSL,C=AT] [9a3a34f727deb9bca51003d9ce9c39f8f27dd9c5242901c2bab1a44e635a0219]

Here's a debug log for [https://1.1.1.2/dns-query]:
DnsCrypt log: Refreshing certificates
DnsCrypt log: [https://1.1.1.2/dns-query] TLS version: 303 - _**Protocol: h2**_ - Cipher suite: 49195
DnsCrypt log: Advertised cert: [CN=security.cloudflare-dns.com,O=Cloudflare\, Inc.,L=San Francisco,ST=California,C=US] [ac3c38d6e068bd1e2920df86ac340add4a70ee5bb32e8ed175661c0af2027593]
DnsCrypt log: Advertised cert: [CN=DigiCert TLS Hybrid ECC SHA384 2020 CA1,O=DigiCert Inc,C=US] [2a15f5d6acb6e7c0901ade4ebbc743b2ccd489032b46e1642f0693683001258a]

I noticed protocol report difference - "http/1.3" for AdGuard DNS and "h2" for Cloudflare.

**Comment by ameshkov** [comment]
Hm, we had a big update yesterday, must be due to it. Thank you for reporting it!

**Comment by ameshkov** [comment]
Please check it now, should be okay
