### ISSUE TITLE
Adgaurd DNS Connection information wrong 

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardDNS#427]
After Adgaurd DNS got updated to version 2.1
It's showing connection information in lastest activity the wrong time under device settings. In the screenshot it says 1:45pm but the current time was 10:45 am. 
It does show the correct time in query log but not device settings.

![20221020_10465984_Edited](https://user-images.githubusercontent.com/96619913/196999083-bb6124a9-4bce-4c18-b829-409f1fab8d56.png)

**Comment by Chinaski1** [comment]
Fixed in v2.1.1
