### ISSUE TITLE
Destination flags don't fit their boundaries

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardDNS#428]
It appears from the screenshot as if the flags aren't designed to fit in a round boundary with many flags having white at the top and bottom of their boundaries, making it feel not very purpose built.

It would be much better if the destination flags were better designed to fit their boundaries appropriately.

![image](https://user-images.githubusercontent.com/95468948/197096744-6e6d3f7d-9533-469d-814d-ed5f3ee12cc0.jpeg)

**Comment by Chinaski1** [comment]
Changed at release v[2.1.2](https://adguard-dns.io/en/versions.html)
