### ISSUE TITLE
DNS stopped working few hours ago

### ISSUE THREAD

**Issue by MichalPetryka** [AdguardTeam/AdGuardDNS#43]
Few hours ago Adguard DNS stopped working completly, no webpages load, everything works after changing to 1.1.1.1

**Comment by Roshanalexander** [comment]
Seems to be resolved now.

**Comment by MichalPetryka** [comment]
Yeah, seems working for now, but it may break again in some time, i'll leave this open so that adguards team can take a look at what's causing it.
