### ISSUE TITLE
Adguard DNS blocks ali link shorteners

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardDNS#43]
http://ali.pub/4qz93
http://alipromo.com/redirect/cpa/o/rs2r2dq1pv9qb9x63pezck1zqjook2d3/?to=http%3A%2F%2Fru.aliexpress.com%2Fitem%2F5m-300-LED-SMD3528-60leds-m-Flexible-LED-Strip-Light-60led-m-IP65-Waterproof-White-Blue%2F1688086875.html%3Fspm%3D2114.13010608.0.134.YLNrAR&material=cashback

**Comment by Alex-302** [comment]
Added
```
@@||alipromo.com^
```
it also blocks urls like this
`http://cityadspix.com/click-JQEXXAX0-KIGQB9TF?bt=25&tl=1&sa=116&url=http%3A%2F%2Fwww.aliexpress.com%2F`
I got it when open it in private tab. There are few redirects, and one of them was through cityadspix.com(not every time)
http://imagizer.imageshack.com/img922/138/wsuuic.png
Unblock it?

**Comment by ameshkov** [comment]
Huh, I guess we shouldn't unblock it.

**Comment by Alex-302** [comment]
Ok then.
