### ISSUE TITLE
Blank space on connection check section

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardDNS#431]
It would likely look better if the green dot was next to the text, rather than below it. It feels like wasted space.

I've edited the site locally to show an example mock-up, but it might even look better to centre it to the left of the text with a flexbox container.

Old
![image](https://user-images.githubusercontent.com/95468948/197098665-489c58f4-d0e0-41be-a719-9b35730b7617.jpeg)

New
![image](https://user-images.githubusercontent.com/95468948/197099383-d58baa69-d6bf-4da6-bdfd-2dfb4dafeed1.jpeg)

**Comment by Chinaski1** [comment]
Changed at release v[2.1.2](https://adguard-dns.io/en/versions.html)
