### ISSUE TITLE
Sign in with apple ID in firefox not working

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardDNS#434]
when I was trying to sign in with my Apple ID in Indeed.com it wouldn't log me in. so I tried a different browser like Microsoft Edge and I had no problem signing in there. I would like to have this fixed so I can use my default browser Firefox like i always do.
This is on a Windows laptop

**Comment by Chinaski1** [comment]
Hello @Batman2814 

The issue is not reproduced on the FF browser v106.0.1 (64-bit).
Can you inform us which version of the browser are you using?

**Comment by Batman2814** [comment]
I'm on firefox 106.0.2 which was just released today but it was also happening in version 106.0.1
when i type my apple ID for login site it shows a blank screen and doesn't log me in at all.

![20221026_08485243 Apple ID 1](https://user-images.githubusercontent.com/96619913/198044878-1e28337d-302b-431b-a938-66d5215d913e.png)
![20221026_08475997 apple id 2](https://user-images.githubusercontent.com/96619913/198044920-847e2b80-00f3-4f93-8e41-bf55b510e53a.png)

**Comment by Batman2814** [comment]
Also when I have Adguard VPN for windows on it does not allow me at all to sign in with apple ID

**Comment by Batman2814** [comment]
Its works with Adgaurd VPN ON now
