### ISSUE TITLE
'Try AdGuard DNS' button alignment issues in iOS Safari

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardDNS#436]
It seems the button reading 'Try AdGuard DNS' can't be reached on iOS 16 Safari, but shows correctly in WebView.

https://user-images.githubusercontent.com/95468948/198277702-ae66610e-5c5a-401c-b9b8-7b29ba48f06e.MOV

![image](https://user-images.githubusercontent.com/95468948/198278103-37a68f44-188a-419c-b291-3675bdce710d.png)

**Comment by Chinaski1** [comment]
Fixed in [v2.1.6](https://adguard-dns.io/en/versions.html#2.1.6)
