### ISSUE TITLE
site blocked by mistake

### ISSUE THREAD

**Issue by syrianmvp** [AdguardTeam/AdguardDNS#44]
hello guys,i believe that http://www.filecroco.com/ site is clean and no need to block it with Ad Guard dns  it just contains free software to download and not a harmful site.

best regards

**Comment by Alex-302** [comment]
@vozersky please check this site.

**Comment by vozersky** [comment]
removed it from our safebrowsing filter

**Comment by syrianmvp** [comment]
thanks alot , your dns service is awesome keep it amazing and .....free ;)
