### ISSUE TITLE
Weird DNS routing issues from Germany

### ISSUE THREAD

**Issue by derKief** [AdguardTeam/AdGuardDNS#441]
Hi Adguard team,

since yesterday evening my DNS routing issues are back. 
A few weeks back i created a ticket with similar issue about that -> [#417](https://github.com/AdguardTeam/AdGuardDNS/issues/417)
Yesterday evening there was a short DNS outage and afterwards my DNS requests where routed to Amsterdam/Netherlands instead of Frankfurt/Germany.
Today, a few minutes ago, i had another DNS outage and now my DNS requests are routed to Stockholm/Sweden -> Server: „**dns2-dp-sto-3**”
What is going on ? Its annoying.
Just for your information: I'm a payed customer of adguard-dns.io but atm this service is not very reliable !

![image](https://user-images.githubusercontent.com/30367720/199207682-bf2cff27-9515-4296-a732-0ba18d02f66e.png)

traceroute to server IP of configured adguard-dns.io: 
>   1     1 ms     1 ms     1 ms  FB6660 [192.168.2xx.x]
>   2     *        *        *     Zeitüberschreitung der Anforderung.
>   3    12 ms     7 ms     9 ms  ip-081-210-148-066.um21.pools.vodafone-ip.de [81.210.xxx.xxx]
>   4    15 ms    13 ms    14 ms  de-str01c-rc1-ae-46-0.aorta.net [84.116.197.133]
>   5    16 ms    14 ms    14 ms  de-fra01b-rc2-ae-4-0.aorta.net [84.116.140.201]
>   6    14 ms    16 ms    16 ms  de-bfe18a-rt01-lag-1.aorta.net [84.116.190.34]
>   7    15 ms    17 ms    14 ms  ae32-100-pcr1.fnt.cw.net [195.2.18.217]
>   8    14 ms    17 ms    15 ms  telia-gw.fnt.cw.net [195.2.22.238]
>   9    14 ms    13 ms    15 ms  ffm-bb1-link.ip.twelve99.net [62.115.124.116]
>  10    34 ms    34 ms    33 ms  s-bb1-link.ip.twelve99.net [62.115.143.28]
>  11    33 ms    35 ms    34 ms  s-b3-link.ip.twelve99.net [62.115.118.107]
>  12    35 ms    34 ms    35 ms  datacamp-svc070114-lag003278.ip.twelve99-cust.net [62.115.191.202]
>  13    35 ms    35 ms    34 ms  94-140-14-xx.adguard.com [94.140.14.xx]

traceroute to public Adguard DNS:
>  1    1 ms     1 ms     1 ms  FB6660 [192.168.2xx.x]
>  2     *        *        *     Zeitüberschreitung der Anforderung.
>  3     9 ms     8 ms     8 ms  ip-081-210-148-066.um21.pools.vodafone-ip.de [81.210.xxx.xxx]
>  4    14 ms    14 ms    13 ms  de-str01c-rc1-ae-46-0.aorta.net [84.116.197.133]
>  5    17 ms    19 ms    15 ms  de-fra04d-rc1-ae-10-0.aorta.net [84.116.140.205]
>  6    15 ms    18 ms    15 ms  84.116.190.94
>  7    13 ms    15 ms    14 ms  ae32-100-pcr1.fnt.cw.net [195.2.18.217]
>  8    14 ms    13 ms    13 ms  telia-gw.fnt.cw.net [195.2.22.238]
>  9    15 ms    13 ms    14 ms  ffm-bb1-link.ip.twelve99.net [62.115.124.116]
> 10    34 ms    33 ms    35 ms  s-bb1-link.ip.twelve99.net [62.115.143.28]
> 11    33 ms    37 ms    34 ms  s-b3-link.ip.twelve99.net [62.115.118.107]
> 12    36 ms    34 ms    34 ms  datacamp-svc070114-lag003278.ip.twelve99-cust.net [62.115.191.202]
> 13    34 ms    34 ms    34 ms  dns.adguard.com [94.140.15.15]
> 12    36 ms    34 ms    34 ms  datacamp-svc070114-lag003278.ip.twelve99-cust.net [62.115.191.202]
> 13    34 ms    34 ms    34 ms  dns.adguard.com [94.140.15.15]

Please fix that ... and please permanent.

Thanks in advance

**Comment by ameshkov** [comment]
Might be a side-effect of re-routing of Amsterdam POP. Could you please check it again in the evening?

**Comment by derKief** [comment]
seems to fixed now 👍 

![image](https://user-images.githubusercontent.com/30367720/199236748-c4fe8348-9754-4da0-9509-c8e87c5c1075.png)

**Comment by D13410N3** [comment]
Thanks for your answer. Closing the issue
