### ISSUE TITLE
Adguard DNS not recording data from Nest Wi-fi

### ISSUE THREAD

**Issue by Perfectlynk** [AdguardTeam/AdGuardDNS#442]
Hello,

I have an issue where I've put the DNS addresses in my Nest Wi-fi DNS settings and data passing through is not being recorded. There's just a red dot.

It was working before yesterday, but I had to factory reset but it's not working anymore. Nothing has changed with the system and setup. 
The only change on the website is I deleted the old data Google Wi-fi and created a new one Nest Wi-fi. (Only the name changed)

![Screenshot_20221102-130542.png](https://user-images.githubusercontent.com/72349391/199497409-98969d68-b870-40a6-b36d-2ac49dd1777a.png)

![Screenshot_20221102-130608.png](https://user-images.githubusercontent.com/72349391/199497454-555e45ac-08fd-4e09-92c7-299f9a96c08d.png)

![Screenshot_20221102-130508.png](https://user-images.githubusercontent.com/72349391/199497482-7bc87fe4-bb38-400c-9713-7283f9440814.png)

**Comment by ameshkov** [comment]
Two things to do:

1. Check that the IP is linked to AdGuard DNS.
2. Try removing the IPv6 server (IP linking only works with IPv4 at this moment, for IPv6 we plan to have dedicated IPv6 per device but it's not implemented yet).

**Comment by Perfectlynk** [comment]
I couldn't link it, and thought that was normal but I found the issue. Turns out you can't link your IP when Adguard VPN is on (well I can't). So I disabled it, and I was able to link my IP with my Router. It started reading requests and doing it's thing so I re-enabled my VPN. Not sure if this will cause any issues but so far so good.

**Comment by ameshkov** [comment]
Yeah, we don't allow linking VPN IP as this way you may be able to see requests from other VPN users.

On the other hand, all AdGuard VPN apps allow using an encrypted DNS resolver (iOS version with this feature is in beta testing stage now).
