### ISSUE TITLE
Indonesia routed to US

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardDNS#443]
1. Country: `Indonesia`
2. ISP: `PT. Telekomunikasi Indonesia (IndiHome)`
3. Traceroute 94.140.14.14
 ```
traceroute to 94.140.14.14 (94.140.14.14), 30 hops max, 60 byte packets
 1  router.lan (192.168.88.1)  0.326 ms  0.333 ms  0.359 ms
 2  192.168.1.1 (192.168.1.1)  3.535 ms  5.380 ms  6.367 ms
 3  * * *
 4  180.252.3.25 (180.252.3.25)  12.339 ms  20.517 ms  14.521 ms
 5  180.240.190.109 (180.240.190.109)  28.973 ms  31.007 ms *
 6  180.240.190.109 (180.240.190.109)  26.559 ms *  30.300 ms
 7  180.240.192.9 (180.240.192.9)  199.904 ms  201.275 ms  199.544 ms
 8  101.203.74.30 (101.203.74.30)  194.283 ms  197.290 ms  196.124 ms
 9  dns.adguard.com (94.140.14.14)  216.356 ms  207.267 ms  202.574 ms
```
![Screenshot at 2022-11-06 03-08-25](https://user-images.githubusercontent.com/117177126/200139029-33d3ab83-6ac2-42c1-8210-0dc6aa72e2dd.png)

**Comment by davinhanif** [comment]
I can confirm I have the same issue within same country and ISP. My location is in Jakarta, Indonesia which should be routed to Singapore. Instead, DNS query routed through `dns2-dp-la-2` server with DoH protocol on my Windows 11 laptop.

Country: `Indonesia`
City: `Jakarta`
ISP: `PT Telekomunikasi Indonesia`
AS Code: `AS7713`

```
Tracing route to [dns.adguard.com](http://dns.adguard.com/) [94.140.14.14]
over a maximum of 30 hops:

  1     1 ms     *        2 ms  192.168.0.1
  2     2 ms     2 ms     2 ms  36.83.192.1
  3     6 ms     1 ms     2 ms  180.252.0.157
  4     *        *        *     Request timed out.
  5     *        *       15 ms  180.240.190.109
  6   189 ms   190 ms   190 ms  180.240.192.9
  7   189 ms   189 ms   189 ms  101.203.74.30
  8   187 ms   187 ms   187 ms  [dns.adguard.com](http://dns.adguard.com/) [94.140.14.14]
```

**Comment by D13410N3** [comment]
Hello @hondact125 @davinhanif 
Can you please check now?

**Comment by davinhanif** [comment]
Hi @D13410N3, sure. Umm... this is strange. My Windows 11 laptop and android phone now both routed through `dns2-dp-lon-2` with DoH and DoTLS respectively. Here's tracert result from my Windows 11 laptop:

`Tracing route to dns.adguard.com [94.140.14.14]
over a maximum of 30 hops:

  1     1 ms     1 ms     1 ms  192.168.0.1
  2     2 ms     2 ms     2 ms  36.70.208.1
  3    13 ms     4 ms     6 ms  180.252.0.157
  4     *       17 ms     *     180.240.190.109
  5     *        *       16 ms  180.240.190.109
  6   249 ms   273 ms   250 ms  180.240.192.242
  7   256 ms   258 ms   255 ms  ae6-0.nyk10.core-backbone.com [198.32.160.234]
  8   245 ms   245 ms   245 ms  ae10-2092.lon10.core-backbone.com [5.56.18.93]
  9   250 ms   251 ms   250 ms  core-backbone.cdn77.com [5.56.17.178]
 10   250 ms   250 ms   251 ms  dns.adguard.com [94.140.14.14]`

![image](https://user-images.githubusercontent.com/39960696/202255998-10967f5c-9a52-4e18-98a8-13161abbcc44.png)


And here's tracert from my android phone:

`traceroute to 94.140.14.14 (94.140.14.14), 30 hops max
Hop 1:
    From 192.168.0.1, 3 ms

Hop 2:
    From 36.70.208.1, 4 ms

Hop 3:
    From 180.252.0.157, 5 ms

Hop 4:
    * 

Hop 5:
    * 

Hop 6:
    From 180.240.192.242, 280 ms

Hop 7:
    From 198.32.160.234, 279 ms

Hop 8:
    From 5.56.18.93, 279 ms

Hop 9:
    From 5.56.17.178, 279 ms

Hop 10:
    From dns.adguard.com (94.140.14.14), 278 ms

Traceroute complete: 10 hops, time: 12133 ms
`

![Screenshot_2022-11-17-00-52-27-501-edit_com android chrome](https://user-images.githubusercontent.com/39960696/202256725-dbfebf40-af11-4965-aace-84f4bcc82083.jpg)

**Comment by davinhanif** [comment]
I also tried to reboot my modem and re-run the tracert just in case. Still routed through `dns2-dp-lon-2` though. Just let me know if you need more info to troubleshoot this issue @D13410N3

**Comment by D13410N3** [comment]
Hello.
Communication with transit ISP had no effect.
Anyway can you please check what server are you using now?

**Comment by davinhanif** [comment]
@D13410N3 I ran the test before and after restarted my modem just to be sure. However the results are still the same:

On my laptop:
Server: `dns2-dp-lon-3`
Protocol: DoH

On my phone:
Server: `dns2-dp-lon-2`
Protocol: DoT

**Comment by davinhanif** [comment]
Same here. Apparently since recent outage it changed to `dns2-dp-fra-16` both with DoH and DoT

```
Tracing route to dns.adguard.com [94.140.14.14]
over a maximum of 30 hops:

  1     5 ms     4 ms     4 ms  192.168.0.1
  2     3 ms     3 ms     4 ms  36.83.192.1
  3    60 ms     3 ms    10 ms  180.252.0.157
  4    75 ms    19 ms    19 ms  180.240.190.109
  5   118 ms    17 ms    18 ms  180.240.190.109
  6   243 ms   243 ms   243 ms  180.240.192.242
  7   265 ms   380 ms   263 ms  ae6-0.nyk10.core-backbone.com [198.32.160.234]
  8   250 ms   248 ms   246 ms  ae7-2093.fra10.core-backbone.com [5.56.20.101]
  9   328 ms   276 ms   276 ms  core-backbone.cdn77.com [5.56.19.238]
 10   311 ms   262 ms   262 ms  dns.adguard.com [94.140.14.14]

Trace complete.
```

**Comment by twitterblue** [comment]
I have been using NordVPN as well as AdGuard VPN and when I connect to the Irish servers of both VPNs then my DNS over QUIC as well as DNS over HTTPS are redirected to the London server. Any explanation for this scenario?

**Comment by akeyakey** [comment]
@D13410N3 

I can confirm that this only happens to the Telkom Group (Indihome and Telkomsel).
Other ISPs route through Singapore just fine.

I use Yetoya as a backup ISP.
There are no problems with the route.

**Comment by mahara** [comment]
This used to be working correctly until last month ago or so, but now I'm not sure where it's being routed to. It becomes roughly 5x slower, 20 ms vs. 100 ms. Is this an internal ISP issue, Telkomsel IndiHome in this case, or AdGuard DNS routing issue?

```
Tracing route to dns.adguard.com [94.140.14.14]
over a maximum of 30 hops:

  1     1 ms    <1 ms    <1 ms  192.168.50.1
  2     1 ms     1 ms     1 ms  192.168.1.1
  3     5 ms     2 ms     2 ms  10.213.64.1
  4     *        3 ms     3 ms  125.160.0.62
  5     3 ms     3 ms     4 ms  125.160.0.61
  6    24 ms    18 ms    14 ms  180.240.190.77
  7    14 ms    15 ms    14 ms  180.240.190.77
  8    98 ms    97 ms    97 ms  dns.adguard.com [94.140.14.14]

Trace complete.
```

The [test page](https://adguard.com/en/test.html) is correctly showing it's being routed to Singapore DNS server though.

```
You are using your private AdGuard DNS server
Protocol: "DNS-over-QUIC"
Server: "dns2-dp-sg-8"
```

**Comment by D13410N3** [comment]
@mahara Hello!
Yes, it's Singapore.
Hop `180.240.190.77` is Telin. I' ll contact our upstream for information why link between them and Telin is so slow.
Thank you for report

**Comment by mahara** [comment]
@D13410N3 Thanks! Added trace route data to other DNS servers for comparisons.
