### ISSUE TITLE
Living in moldova but routing to frankfurt not from prague

### ISSUE THREAD

**Issue by Vangogh2022md** [AdguardTeam/AdGuardDNS#446]
C:\Users\admin>tracert 94.140.14.14

Tracing route to dns.adguard.com [94.140.14.14]
over a maximum of 30 hops:

  1    <1 ms    <1 ms    <1 ms  g1-c105nx.nxdomain.md [192.168.1.1]
  2    29 ms    28 ms    30 ms  g1-c101nx.nxdomain.md [100.67.33.1]
  3    37 ms    36 ms    35 ms  host-static-89-41-119-58.moldtelecom.md [89.41.119.58]
  4    32 ms    32 ms    33 ms  89-41-119-59.Te0-0-0-v1360.ISG-29.telco.md [89.41.119.59]
  5    35 ms    35 ms    35 ms  212-0-199-72.Te0-2-0-8-v1378.C-CORE-A.telco.md [212.0.199.72]
  6    38 ms    34 ms    35 ms  host-static-212-0-200-194.moldtelecom.md [212.0.200.194]
  7    38 ms    38 ms    38 ms  ae5.RT.HST.ODS.UA.retn.net [87.245.237.218]
  8    78 ms    72 ms    73 ms  ae8-10.RT.IRX.FKT.DE.retn.net [87.245.232.139]
  9    70 ms    69 ms    82 ms  ae17.cr6-fra2.ip4.gtt.net [154.14.40.233]
 10    75 ms    74 ms    74 ms  ip4.gtt.net [154.14.141.170]
 11    73 ms    72 ms    72 ms  dns.adguard.com [94.140.14.14]

Trace complete.

please fix this

**Comment by Vangogh2022md** [comment]
The problem is stiil not resolved

**Comment by D13410N3** [comment]
We're trying to fix this.

**Comment by D13410N3** [comment]
Couldn't be totally fixed at this moment. Based on our research, most routes from Moldova to Frankfurt is shorter than route to Prague.
