### ISSUE TITLE
High latency with Singapore ViewQwest ISP

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdGuardDNS#449]
> I'm a user from Singapore and I've been noticing my latency to be around 80-100ms while using Adguard DNS.
> I am being routed to the Tokyo servers supposedly, is there any way the team can help me with this?

Traceroute results in helpdesk: 676144

**Comment by ameshkov** [comment]
We need traceroute at least

**Comment by Eugene-Savenko** [comment]
@ameshkov I am not sure if it's okay to post it here publicly, but it's in the ticket (676144).

**Comment by ameshkov** [comment]
AS number would be enough.

The problem is with AS18106.

**Comment by D13410N3** [comment]
Issue should be fixed now
