### ISSUE TITLE
Incorrect blocking

### ISSUE THREAD

**Issue by andrews05** [AdguardTeam/AdguardDNS#45]
Domain www.kiwihealthjobs.co.nz is being blocked for some reason. Possibly something to do with snaphire.com which is the primary domain for the server.

**Comment by Alex-302** [comment]
Which DNS addresses are you using?

**Comment by andrews05** [comment]
Family Protection

**Comment by ameshkov** [comment]
@nkartyshov could you please take a look?

**Comment by Alex-302** [comment]
This domain was blocked by family protection. It was reported to vozersky.
@andrews05 please check it again.

**Comment by andrews05** [comment]
Working now, thanks!
