### ISSUE TITLE
DNSSEC issues with AdGuardDNS

### ISSUE THREAD

**Issue by derKief** [AdguardTeam/AdGuardDNS#456]
Hi,
since today i have issues with DNSSEC on my router.
Its an OpenWRT based device which is running Unbound with DoT as internal DNS forwarder.
Since today i get following message when DNSSEC is enabled.

**Thu Nov 24 20:21:15 2022 daemon.info unbound: [2270:0] info: failed to prime trust anchor -- could not fetch DNSKEY rrset . DNSKEY IN**

When i disable DNSSEC it's working again.
This was no problem at all since i use AdGuardDNS on this OpenWRT installation ( at least 3 months now)
With other DNS resolver (e.g. Quad9) no problems at all.
No updates or changes where made on the router so this must be an AdGuard DNS issue.

May you please check whats the problem here ?
If you need further information please let me know.

Regards

**Comment by derKief** [comment]
@ameshkov what to do that this issue will ne resolved ?
Opening a support Ticket or is it enough to post an issue here at Github ?
As i'm payjng for that service its a bit annoying when the Service doesnt work proberly.

**Comment by ameshkov** [comment]
Support ticket is not necessary.

Please check now if the issue is still there.

**Comment by derKief** [comment]
> 

unfortunately it's not fixed ... at least for me.
Just tested it.

**Comment by ameshkov** [comment]
Figured it out, the fix is on the way (~1 hour)

**Comment by derKief** [comment]
short feedback ... it's fixed.
Thanks for fast support

**Comment by dienteperro** [comment]
In the logs: [CRITICAL] [dnsfilter] may be a lying resolver

## dnsfilter

A DNS service provider that offers a secure and private DNS solution. Logs, no DNSSEC, filters some malicious domains.
Homepage: https://www.dnsfilter.com/

sdns://AgAAAAAAAAAADjEwMy4yNDcuMzYuMTUwoMwQYNOcgym2K2-8fQ1t-TCYabmB5-Y5LVzY-kCPTYDmoPf1ryiAHod9ffOivij-FJ8ydKftKfE2_VA845jLqAsNoLNeBZUM-9gln5N1uhAYcLjDxMDsWlKXV-YxZ-neJqnooEROvWe7g_iAezkh6TiskXi4gr1QqtsRIx8ETPXwjffOoOZEumlj4zX-dly5l2sSsQ61QpS0JHd2TMs6OsyjrLL8ICquP7e_BeTIHEGU3KRFEdT5rzBHhuwa5yGECc9ioINVEWRvaC5kbnNmaWx0ZXIuY29tCi9kbnMtcXVlcnk
