### ISSUE TITLE
DnsCrypt log: "AdGuard-DoH-IP" may be a lying resolver

### ISSUE THREAD

**Issue by Ry0OBSSc9H8VjeVE** [AdguardTeam/AdGuardDNS#457]
YogaDNS log reports:
DnsCrypt log: "AdGuard-DoH-IP" may be a lying resolver 

What does "may be a lying resolver" mean?

**Comment by ameshkov** [comment]
No idea, but might be the same issue as this one: https://github.com/AdguardTeam/AdGuardDNS/issues/456

**Comment by ameshkov** [comment]
Please check if the issue is still there now.

**Comment by ameshkov** [comment]
Should be solved now. Please reopen if it happens again.

**Comment by Ry0OBSSc9H8VjeVE** [comment]
Resolved :). What was the issue? DNSSEC key compromise?

**Comment by ameshkov** [comment]
Nope, a mistake in the updated version that made it respond incorrectly to non-A and non-AAAA queries.
