### ISSUE TITLE
Add Adguard DNS to DnsCrypt list

### ISSUE THREAD

**Issue by nkartyshov** [AdguardTeam/AdguardDNS#46]
DnsCrypt list https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-resolvers.csv

Information about Adguard DNS https://gist.github.com/nkartyshov/29f82b5967ffba233ed161a3afe640c9

**Comment by Opensourcecommunitydevelopment** [comment]
port 5443 is currently unreachable !
176.103.130.130, 176.103.130.131

 176.103.130.132, 176.103.130.134

**Comment by ameshkov** [comment]
@Opensourcecommunitydevelopment hm, we'll check it asap, thanks for alerting us!

**Comment by ameshkov** [comment]
@Opensourcecommunitydevelopment should be good now

**Comment by Opensourcecommunitydevelopment** [comment]
correct. i can confirm works fine again thanks!

**Comment by ameshkov** [comment]
@Opensourcecommunitydevelopment great, thank you!

**Comment by ameshkov** [comment]
@nkartyshov please update website instruction according to this:
https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-resolvers.csv#L3

**Comment by nkartyshov** [comment]
Updated
