### ISSUE TITLE
Real-time query log updates doesn't retain filter changes

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardDNS#460]
I didn't see real-time query log updates announced, so I'm not sure if it was a silently released feature, or whether it's not meant to be released yet.

When changing the query log filters, and enabling real-time update in the query log, the next query log refresh will remove all selected filter changes.

1. Select any filter changes in query log
2. Enable real-time updates in query log
3. Wait until next refresh, and all filter settings won't be shown

For example, selecting filtered status only will refresh back to showing all results on next refresh poll.

https://user-images.githubusercontent.com/95468948/204445737-1b89a421-111b-4e96-85f3-478a46c2bb2f.mov

**Comment by Batman2814** [comment]
Any idea when this will be fixed? Because I'm trying to figure out what domain is causing my Samsung TV to show ads. With this bug can't do that.

**Comment by Chinaski1** [comment]
I can't give you an exact date, but we will try to fix this in the next updates

**Comment by Chinaski1** [comment]
Fixed at [v2.2](https://adguard-dns.io/en/versions.html)
