### ISSUE TITLE
Routing issues forthnet.gr

### ISSUE THREAD

**Issue by VladisLoveZh** [AdguardTeam/AdGuardDNS#462]
ISP: http://forthnet.gr 
Location: Greece
Tracert results: 94.140.14.14 
![image](https://user-images.githubusercontent.com/103937301/204451801-3e6d1170-c615-4a08-a375-49fac78981d9.png)
AdGuard test page: _dns2-dp-ny-4_

**Comment by D13410N3** [comment]
Should be London, Frankfurt or Istanbul now
