### ISSUE TITLE
Encrypted and unencrypted DNS statistics

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdGuardDNS#463]
If we could get a statistic for how many encrypted and unencrypted DNS traffic received from the devices, so we can better look into it and see why it is behaving in that fashion. I have seen this same settings with NextDNS, and they give better picture for devices and their security.

Requested by: 689453

**Comment by twitterblue** [comment]
I just read a blog on the AdGuard which stated that more than 90% of the DNS requests that AdGuard receives are in an encrypted format, so if we let users see that which devices of theirs are sending 100% or whatever portion of the total queries in the unencrypted format, then they can take action with that device and make sure that they are not leaking any information outside through plain DNS requests. I am using ARP spoofing with my ISP router as my ISP router does not support encrypted DNS requests. I have set up the AdGuard DNS IPv4 address there, and it is harder for me to see what portion of this setup is sending out DNS requests in plain text format. Until this is implemented, can we see a filter where we can filter the plain text DNS requests in the query log?

**Comment by Chinaski1** [comment]
Added in [v2.4 update](https://adguard-dns.io/en/versions.html)
