### ISSUE TITLE
Virgin Media ISP Routing To Amsterdam

### ISSUE THREAD

**Issue by Eow2022yia** [AdguardTeam/AdGuardDNS#465]
Hi,

This issue was fixed for a short period of time but has now frustratingly returned.

Same issue as previously stated by AidanGee7 on https://github.com/AdguardTeam/AdGuardDNS/issues/416

![image](https://user-images.githubusercontent.com/109627209/205715828-94047ffe-97cc-4b42-9125-6241510ad20d.jpeg)

Please can you fix this issue again? It is only occurring on Virgin Media UK and no other networks or ISP's.

Thanks.

**Comment by D13410N3** [comment]
Sorry, there is no fix for this at this moment. Anyway, this route is the fastest for you

**Comment by D13410N3** [comment]
VirginMedia is using wide infrastructure provided by LibertyGlobal. They have their own routing rules working for all their european points. At this moment they don't have direct peering with us in London and the real route from you to our London server is long and has higher latency than route to Amsterdam.

We tried to contact them. They sometimes answer us, but in most cases they do nothing. 

You can trust me: at this moment Amsterdam is really fastest solution for VirginMedia in UK. The only way is to implement totally blocking rules, so traffic won't come to LibertyGlobal at all, but it will cause unpredictable consequences, they are too big to ignore them

**Comment by Eow2022yia** [comment]
> VirginMedia is using wide infrastructure provided by LibertyGlobal. They have their own routing rules working for all their european points. At this moment they don't have direct peering with us in London and the real route from you to our London server is long and has higher latency than route to Amsterdam.
> 
> 
> 
> We tried to contact them. They sometimes answer us, but in most cases they do nothing. 
> 
> 
> 
> You can trust me: at this moment Amsterdam is really fastest solution for VirginMedia in UK. The only way is to implement totally blocking rules, so traffic won't come to LibertyGlobal at all, but it will cause unpredictable consequences, they are too big to ignore them

Hi,

Thank you for the explanation :)

**Comment by ijuliank** [comment]
> > VirginMedia is using wide infrastructure provided by LibertyGlobal. They have their own routing rules working for all their european points. At this moment they don't have direct peering with us in London and the real route from you to our London server is long and has higher latency than route to Amsterdam.
> > We tried to contact them. They sometimes answer us, but in most cases they do nothing.
> > You can trust me: at this moment Amsterdam is really fastest solution for VirginMedia in UK. The only way is to implement totally blocking rules, so traffic won't come to LibertyGlobal at all, but it will cause unpredictable consequences, they are too big to ignore them
> 
> Hi,
> 
> Thank you for the explanation :)
you should step away from anything what is working with liberty global, its fucking up alot things, also for me, a dutch ISP called Ziggo wich is part of liberty global, also fucked it up

**Comment by Eow2022yia** [comment]
> > > VirginMedia is using wide infrastructure provided by LibertyGlobal. They have their own routing rules working for all their european points. At this moment they don't have direct peering with us in London and the real route from you to our London server is long and has higher latency than route to Amsterdam.
> 
> > > We tried to contact them. They sometimes answer us, but in most cases they do nothing.
> 
> > > You can trust me: at this moment Amsterdam is really fastest solution for VirginMedia in UK. The only way is to implement totally blocking rules, so traffic won't come to LibertyGlobal at all, but it will cause unpredictable consequences, they are too big to ignore them
> 
> > 
> 
> > Hi,
> 
> > 
> 
> > Thank you for the explanation :)
> 
> 
> 
> you should step away from anything what is working with liberty global, its fucking up alot things, also for me, a dutch ISP called Ziggo wich is part of liberty global, also fucked it up

Hi,

Fair point but sadly in the UK the fixed-line internet speeds are awful and Virgin Media is the only ISP that offers decent speeds around my local area.

To add to this, I went to my friends house who uses TalkTalk ISP and the anycast location on AdGuard DNS was incorrect on this as well, on this note I think @ad

**Comment by Eow2022yia** [comment]
> > > VirginMedia is using wide infrastructure provided by LibertyGlobal. They have their own routing rules working for all their european points. At this moment they don't have direct peering with us in London and the real route from you to our London server is long and has higher latency than route to Amsterdam.
> 
> > > We tried to contact them. They sometimes answer us, but in most cases they do nothing.
> 
> > > You can trust me: at this moment Amsterdam is really fastest solution for VirginMedia in UK. The only way is to implement totally blocking rules, so traffic won't come to LibertyGlobal at all, but it will cause unpredictable consequences, they are too big to ignore them
> 
> > 
> 
> > Hi,
> 
> > 
> 
> > Thank you for the explanation :)
> 
> 
> 
> you should step away from anything what is working with liberty global, its fucking up alot things, also for me, a dutch ISP called Ziggo wich is part of liberty global, also fucked it up

Hi,

Fair point but sadly in the UK the fixed-line internet speeds are awful and Virgin Media is the only ISP that offers decent speeds around my local area.

To add to this, a few days ago I went to my friends house who uses TalkTalk ISP and the anycast location on AdGuard DNS was incorrect on this as well, pointing to Sweden instead of London, on this note I think @D13410N3 and @adguard need to look into this more a global scale rather than just Liberty Global.
