### ISSUE TITLE
Adguard Services check page not working on iOS App

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardDNS#468]
![41A7A38E-F696-4D92-B8F8-0048FB7A9587](https://user-images.githubusercontent.com/96619913/206788918-0fd74c6a-86ea-45d1-8a1f-85d9d6ab6255.jpeg)

When I run a test on Adguard services check page when Adguard Pro iOS app is enabled it doesn't register on Adguard services check page that it is enabled. Not serve if this belongs in Adguard DNS. Hopefully you can fix this.

**Comment by Batman2814** [comment]
I ran it again and still says it's not on even though it is on. I'm using Adguard Pro iOS App from the Apple store. It was working in the past before.

**Comment by Batman2814** [comment]
I was able to follow what u said and it's now detecting the app. Do u know why it wasn't detecting the app and is there a way to prevent this from happening again.

**Comment by ameshkov** [comment]
There's a nasty bug in iOS, an OS update somehow may break content blockers and re-enabling them is required to make it work. What's bad is that we cannot detect this breakage on the app side, everything looks normal to the app.
