### ISSUE TITLE
These Domains need to be unblocked for my Shaw app to work

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardDNS#470]
1.) www.google-analytics.com
2.) rum-collector-2.pingdom.net
3.) siteintercept.qualtrics.com
4.) rum-static.pingdom.net
5.) strack.shaw.ca
6.) cdn.appdynamics.com
7.) shaw.demdex.net
8.) cm.everesttech.net

As far as I know this is on Android.

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdGuardSDNSFilter #1142](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1142) via [**Zenhub**](https://www.zenhub.com/)
