### ISSUE TITLE
These Domains need to be unblocked for Paybbight app to work

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardDNS#471]
1.) Inside paybright app to open apple website in the app this domain needs to be unblocked
apple.sjv.io 

2.) This domain also must be unblocked to open Samsung website in the app 
i.w55c.net

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdGuardSDNSFilter #1143](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1143) via [**Zenhub**](https://www.zenhub.com/)
