### ISSUE TITLE
Issue with the statistics and log retention settings

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardDNS#472]
Hi team,

So I recently set my log retention period to 24 hours. Still, the statistics retention period to 90 days, which means whenever I am on the statistics tabs of the Adguard DNS 2.0, I should effectively be able to see 90 days' worth of statistics, but logs should only be kept for 24 hours. But this is not the case, I can see. I only see two options selecting 'Last Hour' and 'Last 24 Hours'. 
 
<img width="528" alt="Screenshot 2022-12-14 at 11 34 12 PM" src="https://user-images.githubusercontent.com/118989300/207738685-3e1881ea-88ad-4c22-82ce-e23dff8eebec.png">

<img width="260" alt="Screenshot 2022-12-14 at 11 38 29 PM" src="https://user-images.githubusercontent.com/118989300/207738695-61230c38-faf0-4f90-9a7f-e4a59f0389b8.png">

Ideally, I want to reach the level of privacy with AdGuard DNS to keep the query log for one hour(in case there are any issues or blocking of the legitimate domains by any list); only AdGuard DNS will delete all query logs automatically. Still, the stats for those logs would remain there for 90 days. In short, the aggregated report of my usage pattern with domains and their blocked status, as well as all other stats, should be visible for 90 days, irrespective of the query log retention period.

**Comment by chatch314** [comment]
I came to say the same thing.  In a privacy bid I changed it to no logs, but 90 days stats retention which I assumed would do, well exactly that.

Instead the stats appear to be for the last minute?
