### ISSUE TITLE
Support for nintendo switch

### ISSUE THREAD

**Issue by CodeRiverFoxLife** [AdguardTeam/AdGuardDNS#475]
Is it possible to get adguard dns able to work on nintendo switch?

**Comment by ameshkov** [comment]
It is just a matter of setting up the DNS there:

1. Go to the home menu and choose System Settings (the wrench icon).
2. Select Internet Settings > Connection Settings.
3. Select your Internet connection and then select Change Settings.
4. Select Change DNS.
5. Set Auto-Obtain DNS to No.
6. Select Detailed Setup.
7. Set Primary DNS and Secondary DNS to AdGuard DNS addresses
