### ISSUE TITLE
Support for chrome secure dns

### ISSUE THREAD

**Issue by CodeRiverFoxLife** [AdguardTeam/AdGuardDNS#476]

**Comment by ameshkov** [comment]
Here's how to do it:

1. Select the three-dot menu in your browser > Settings.
2. Select Privacy and security > Security.
3. Scroll down and enable Use secure DNS.
4. Select the With option, choose "Customized"
5. Enter AdGuard DNS address. For instance, `https://dns.adguard-dns.com/dns-query`
