### ISSUE TITLE
Conn closed: TLS - *Failure*

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardDNS#48]
@ameshkov, последнее время постоянные сбои в работе дефолтных серверов через DoT:
https://yadi.sk/i/5wDzoFXMeUr6Hg

Время по логам: -3 часа от московского. Работа в режиме "Strict Profile", клиент DoT - **Stubby** (версия **0.2.6, Entware**). Вывод **echo | openssl11 s_client -connect 176.103.130.131:853**:
**New, TLSv1.2, Cipher is ECDHE-RSA-CHACHA20-POLY1305
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-CHACHA20-POLY1305
    Session-ID: B7EA2A4C8A90C0132BD0C9A4BA4969C20E194379232395B1ABA224775C69C129
    Session-ID-ctx: 
    Master-Key: BB8BAD51BF34FD08131D9DD48384B9869AE3997962178B5AE0BBEFC90DF13EE7E225CF3D9F63ED1BE08AF36CD198065C
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1565541292
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no**

Настройки Stubby:
**tls_min_version: GETDNS_TLS1_2
tls_ciphersuites: "TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256"**

**DNSSEC** включен через dnsmasq. Какие ещё данные предоставить для устранения неполадки?

Спасибо.

**Comment by ammnt** [comment]
Похоже, что это проблемы с DNSSEC. Вот логи dnsmasq в момент, когда опять проявляется проблема и домен accounts.epicgames.com возвращает NXDOMAIN:

> Aug 15 18:27:53 dnsmasq[989]: query[A] accounts.epicgames.com from 192.168.1.3
Aug 15 18:27:53 dnsmasq[989]: forwarded accounts.epicgames.com to 127.0.1.1
Aug 15 18:27:53 dnsmasq[989]: dnssec-query[DS] amazonaws.com to 127.0.1.1
Aug 15 18:27:53 dnsmasq[989]: Insecure DS reply received for com, could be bad domain configuration or lack of DNSSEC support from upstream DNS servers
Aug 15 18:27:53 dnsmasq[989]: reply amazonaws.com is BOGUS DS
Aug 15 18:27:53 dnsmasq[989]: validation accounts.epicgames.com is BOGUS
Aug 15 18:27:53 dnsmasq[989]: reply accounts.epicgames.com is <CNAME>
Aug 15 18:27:53 dnsmasq[989]: reply accountportal-website-prod07-epc-739724359.us-east-1.elb.amazonaws.com is 52.202.243.46
Aug 15 18:27:53 dnsmasq[989]: reply accountportal-website-prod07-epc-739724359.us-east-1.elb.amazonaws.com is 35.168.66.53
Aug 15 18:27:53 dnsmasq[989]: reply accountportal-website-prod07-epc-739724359.us-east-1.elb.amazonaws.com is 35.171.206.70
Aug 15 18:27:53 dnsmasq[989]: reply accountportal-website-prod07-epc-739724359.us-east-1.elb.amazonaws.com is 34.205.226.14
Aug 15 18:27:53 dnsmasq[989]: reply accountportal-website-prod07-epc-739724359.us-east-1.elb.amazonaws.com is 34.230.100.209
Aug 15 18:27:53 dnsmasq[989]: reply accountportal-website-prod07-epc-739724359.us-east-1.elb.amazonaws.com is 34.203.152.178
Aug 15 18:27:53 dnsmasq[989]: query[A] accounts.epicgames.com from 192.168.1.3
Aug 15 18:27:53 dnsmasq[989]: forwarded accounts.epicgames.com to 127.0.1.1
Aug 15 18:27:53 dnsmasq[989]: dnssec-query[DS] amazonaws.com to 127.0.1.1
Aug 15 18:27:53 dnsmasq[989]: Insecure DS reply received for com, could be bad domain configuration or lack of DNSSEC support from upstream DNS servers
Aug 15 18:27:53 dnsmasq[989]: reply amazonaws.com is BOGUS DS
Aug 15 18:27:53 dnsmasq[989]: validation accounts.epicgames.com is BOGUS
Aug 15 18:27:53 dnsmasq[989]: reply accounts.epicgames.com is <CNAME>
Aug 15 18:27:53 dnsmasq[989]: reply accountportal-website-prod07-epc-739724359.us-east-1.elb.amazonaws.com is 52.202.243.46
Aug 15 18:27:53 dnsmasq[989]: reply accountportal-website-prod07-epc-739724359.us-east-1.elb.amazonaws.com is 35.168.66.53
Aug 15 18:27:53 dnsmasq[989]: reply accountportal-website-prod07-epc-739724359.us-east-1.elb.amazonaws.com is 35.171.206.70
Aug 15 18:27:53 dnsmasq[989]: reply accountportal-website-prod07-epc-739724359.us-east-1.elb.amazonaws.com is 34.205.226.14
Aug 15 18:27:53 dnsmasq[989]: reply accountportal-website-prod07-epc-739724359.us-east-1.elb.amazonaws.com is 34.230.100.209
Aug 15 18:27:53 dnsmasq[989]: reply accountportal-website-prod07-epc-739724359.us-east-1.elb.amazonaws.com is 34.203.152.178
Aug 15 18:27:53 dnsmasq[989]: query[A] accounts.epicgames.com from 192.168.1.3
Aug 15 18:27:53 dnsmasq[989]: forwarded accounts.epicgames.com to 127.0.1.1
Aug 15 18:27:53 dnsmasq[989]: dnssec-query[DS] amazonaws.com to 127.0.1.1
Aug 15 18:27:53 dnsmasq[989]: Insecure DS reply received for com, could be bad domain configuration or lack of DNSSEC support from upstream DNS servers
Aug 15 18:27:53 dnsmasq[989]: reply amazonaws.com is BOGUS DS
Aug 15 18:27:53 dnsmasq[989]: validation accounts.epicgames.com is BOGUS
Aug 15 18:27:53 dnsmasq[989]: reply accounts.epicgames.com is <CNAME>
Aug 15 18:27:53 dnsmasq[989]: reply accountportal-website-prod07-epc-739724359.us-east-1.elb.amazonaws.com is 52.202.243.46
Aug 15 18:27:53 dnsmasq[989]: reply accountportal-website-prod07-epc-739724359.us-east-1.elb.amazonaws.com is 35.168.66.53
Aug 15 18:27:53 dnsmasq[989]: reply accountportal-website-prod07-epc-739724359.us-east-1.elb.amazonaws.com is 35.171.206.70
Aug 15 18:27:53 dnsmasq[989]: reply accountportal-website-prod07-epc-739724359.us-east-1.elb.amazonaws.com is 34.205.226.14
Aug 15 18:27:53 dnsmasq[989]: reply accountportal-website-prod07-epc-739724359.us-east-1.elb.amazonaws.com is 34.230.100.209
Aug 15 18:27:53 dnsmasq[989]: reply accountportal-website-prod07-epc-739724359.us-east-1.elb.amazonaws.com is 34.203.152.178
Aug 15 18:27:53 dnsmasq[989]: query[A] accounts.epicgames.com from 192.168.1.3
Aug 15 18:27:53 dnsmasq[989]: forwarded accounts.epicgames.com to 127.0.1.1
Aug 15 18:27:53 dnsmasq[989]: dnssec-query[DS] amazonaws.com to 127.0.1.1
Aug 15 18:27:53 dnsmasq[989]: Insecure DS reply received for com, could be bad domain configuration or lack of DNSSEC support from upstream DNS servers
Aug 15 18:27:53 dnsmasq[989]: reply amazonaws.com is BOGUS DS
Aug 15 18:27:53 dnsmasq[989]: validation accounts.epicgames.com is BOGUS
Aug 15 18:27:53 dnsmasq[989]: reply accounts.epicgames.com is <CNAME>
Aug 15 18:27:53 dnsmasq[989]: reply accountportal-website-prod07-epc-739724359.us-east-1.elb.amazonaws.com is 52.202.243.46
Aug 15 18:27:53 dnsmasq[989]: reply accountportal-website-prod07-epc-739724359.us-east-1.elb.amazonaws.com is 35.168.66.53
Aug 15 18:27:53 dnsmasq[989]: reply accountportal-website-prod07-epc-739724359.us-east-1.elb.amazonaws.com is 35.171.206.70
Aug 15 18:27:53 dnsmasq[989]: reply accountportal-website-prod07-epc-739724359.us-east-1.elb.amazonaws.com is 34.205.226.14
Aug 15 18:27:53 dnsmasq[989]: reply accountportal-website-prod07-epc-739724359.us-east-1.elb.amazonaws.com is 34.230.100.209
Aug 15 18:27:53 dnsmasq[989]: reply accountportal-website-prod07-epc-739724359.us-east-1.elb.amazonaws.com is 34.203.152.178
Aug 15 18:27:58 dnsmasq[989]: query[A] accounts.epicgames.com from 192.168.1.3
Aug 15 18:27:58 dnsmasq[989]: forwarded accounts.epicgames.com to 127.0.1.1
Aug 15 18:27:58 dnsmasq[989]: dnssec-query[DS] amazonaws.com to 127.0.1.1
Aug 15 18:27:58 dnsmasq[989]: Insecure DS reply received for com, could be bad domain configuration or lack of DNSSEC support from upstream DNS servers
Aug 15 18:27:58 dnsmasq[989]: reply amazonaws.com is BOGUS DS
Aug 15 18:27:58 dnsmasq[989]: validation accounts.epicgames.com is BOGUS
Aug 15 18:27:58 dnsmasq[989]: reply accounts.epicgames.com is <CNAME>
Aug 15 18:27:58 dnsmasq[989]: reply accountportal-website-prod07-epc-739724359.us-east-1.elb.amazonaws.com is 35.168.66.53
Aug 15 18:27:58 dnsmasq[989]: reply accountportal-website-prod07-epc-739724359.us-east-1.elb.amazonaws.com is 35.171.206.70
Aug 15 18:27:58 dnsmasq[989]: reply accountportal-website-prod07-epc-739724359.us-east-1.elb.amazonaws.com is 34.205.226.14
Aug 15 18:27:58 dnsmasq[989]: reply accountportal-website-prod07-epc-739724359.us-east-1.elb.amazonaws.com is 34.230.100.209
Aug 15 18:27:58 dnsmasq[989]: reply accountportal-website-prod07-epc-739724359.us-east-1.elb.amazonaws.com is 34.203.152.178
Aug 15 18:27:58 dnsmasq[989]: reply accountportal-website-prod07-epc-739724359.us-east-1.elb.amazonaws.com is 52.202.243.46
Aug 15 18:27:58 dnsmasq[989]: query[A] accounts.epicgames.com from 192.168.1.3
Aug 15 18:27:58 dnsmasq[989]: forwarded accounts.epicgames.com to 127.0.1.1
Aug 15 18:27:58 dnsmasq[989]: dnssec-query[DS] amazonaws.com to 127.0.1.1
Aug 15 18:27:58 dnsmasq[989]: Insecure DS reply received for com, could be bad domain configuration or lack of DNSSEC support from upstream DNS servers
Aug 15 18:27:58 dnsmasq[989]: reply amazonaws.com is BOGUS DS
Aug 15 18:27:58 dnsmasq[989]: validation accounts.epicgames.com is BOGUS
Aug 15 18:27:58 dnsmasq[989]: reply accounts.epicgames.com is <CNAME>
Aug 15 18:27:58 dnsmasq[989]: reply accountportal-website-prod07-epc-739724359.us-east-1.elb.amazonaws.com is 35.168.66.53
Aug 15 18:27:58 dnsmasq[989]: reply accountportal-website-prod07-epc-739724359.us-east-1.elb.amazonaws.com is 35.171.206.70
Aug 15 18:27:58 dnsmasq[989]: reply accountportal-website-prod07-epc-739724359.us-east-1.elb.amazonaws.com is 34.205.226.14
Aug 15 18:27:58 dnsmasq[989]: reply accountportal-website-prod07-epc-739724359.us-east-1.elb.amazonaws.com is 34.203.152.178
Aug 15 18:27:58 dnsmasq[989]: reply accountportal-website-prod07-epc-739724359.us-east-1.elb.amazonaws.com is 34.230.100.209
Aug 15 18:27:58 dnsmasq[989]: reply accountportal-website-prod07-epc-739724359.us-east-1.elb.amazonaws.com is 52.202.243.46

**Comment by ameshkov** [comment]
Проспал вопрос:(

Он еще актуален?

**Comment by ammnt** [comment]
@ameshkov, похоже, что нет. Со дня обновления версии TLS до 1.3 на DNS проблем не наблюдается. Спасибо.
