### ISSUE TITLE
question for adguard dns private

### ISSUE THREAD

**Issue by ijuliank** [AdguardTeam/AdGuardDNS#484]
are these features comming? 
- EDNS Client Subnet -> Speed up the delivery of data from content delivery networks
- Cache Boost -> Minimize DNS queries by enforcing a minimum TTL (Time to live).
- CNAME Flattening -> Prevent CNAME-chasing resolvers from making unnecessary queries and pollute the logs with intermediate domains.
thankyou

**Comment by jslawler** [comment]
#408: CNAME flattening support feature request 
#404 EDNS improvements feature request

You can already edit TTL. Noting that these requests come from NextDNS, it would be beneficial to know that all their Cache Boost setting does is set minimum TTL to 300 (5 minutes).

**Comment by ijuliank** [comment]
close as already requested
