### ISSUE TITLE
DNS-over-QUIC - constant time-outs with YogaDNS

### ISSUE THREAD

**Issue by Ry0OBSSc9H8VjeVE** [AdguardTeam/AdGuardDNS#486]
When using YogaDNS with AdGuard DoQ protocol, DNS resolution is functional, but there are many time-outs. NextDNS DNS-over-QUIC servers do not have such time-outs when used via YogaDNS. The issue exists only for AdGuard DoQ.

**Comment by ameshkov** [comment]
This should probably be reported to YogaDNS, there're no issues with DoQ on our side. If it was open source we could've taken a look, but debugging closed source software is too inconvenient.

The only idea I have is that YogaDNS does not keep alive the QUIC connection properly, i.e. sends ping frames not often enough.

**Comment by GY8VSdYYzvL8-K6T** [comment]
It was narrowed down that use of more than one AdGuard DoQ server (in a pool) results in massive timeouts within 10-20 seconds of heavy browsing, but using any single AdGuard DoQ server by itself does not create any problems.

I realize its not up to AdGuard team to troubleshoot other closed-source software, but input to this reply may shed some light on the origin of the issue (timeouts when using multiple AdGuard DoQ servers).

RFC Draft for DoQ is not very clear on how often KeepAlive packets must be sent. Does AdGuard have its own documentation about its DoQ servers?

**Comment by ameshkov** [comment]
Yeah, the problem might indeed be in how YogaDNS keeps the connection alive.

It should send KeepAlive packets AT LEAST once in 20 seconds to make sure that the connection stays alive.
