### ISSUE TITLE
Error message checking for updates on applications

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardDNS#489]
I get a message saying "Host not found (49410)" when check for Applications updates when I have Adgaurd VPN for windows enabled with Adgaurd Private DNS setup in Adguard VPN for windows. so if you can look into this and see if it can be fixed.

**Comment by Chinaski1** [comment]
Hello there!

Are we talking about any specific applications?
If you use the regular AdGuard DNS as a DNS server, won't the issue recur?

**Comment by Batman2814** [comment]
Application name Tixati

**Comment by Chinaski1** [comment]
Most likely, when you update the application, ad domains are used and they are blocked by AdGuard DNS.

You can try to update the application and immediately open the filtering log, probably you will be able to find out which rule is blocking the update and add it to the allowlist if you want.

**Comment by Batman2814** [comment]
There isn't any ad domains in this software. Sometimes in order for me to fix with adguard dns enabled in adguard VPN for windows is to update the filters in adguard adblocker for windows and disconnect and connect adguard VPN for windows then when I press check for updates it check correctly without giving me that message host not found.

**Comment by Batman2814** [comment]
i figured out that this only happens on Adguard Persoanl DNS using protocol QUIC.

everything was fine when i switched it to protocol TLS
