### ISSUE TITLE
Setup dnscrypt monitoring

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardDNS#49]
It appears that dnscrypt process was down on both US servers:
https://github.com/AdguardTeam/AdguardDNS/issues/46

**Comment by Opensourcecommunitydevelopment** [comment]
at the moment i experience again connection issue with 176.103.130.130 while 176.103.130.131 works with dnscrypt but its not in https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-resolvers.csv#L3

**Comment by nkartyshov** [comment]
done
