### ISSUE TITLE
Add days to new month

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardDNS#490]
It would be handy to know when the new month starts as there is no indicator as to when that may be.

To avoid congesting the UI with more information, it would likely be best shown in the requests tooltip.

In favour of readability, my preferred way of viewing it would be similarly to the first example below: "In 8 days, on 9 January, you'll get another 5GB".
Or in AGDNS's case: "In 31 days, on 1 February, you will get another 10M requests".

![image](https://user-images.githubusercontent.com/95468948/210154484-f0f1f5ab-bf1e-438c-8a87-5f893fbd13f4.jpeg)

<details><summary>Here are some examples from apps that I use. </summary>
<p>

![image](https://user-images.githubusercontent.com/95468948/210154349-0f2b19f1-6a25-4309-9022-b24ad44c7cca.jpeg)
![image](https://user-images.githubusercontent.com/95468948/210154351-2daee60f-b24e-45de-9590-9caee88dead3.jpeg)
![image](https://user-images.githubusercontent.com/95468948/210154353-00f34948-7c9c-4674-a23d-81a3fadf8f43.jpeg)

</p>
</details>

**Comment by ameshkov** [comment]
Good idea!

**Comment by Chinaski1** [comment]
Added at [v2.2](https://adguard-dns.io/en/versions.html)
