### ISSUE TITLE
kb: Private AdGuard DNS beta test

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardDNS#492]
The AdGuard kb advertises the [Private AdGuard DNS beta test](https://adguard-dns.io/kb/miscellaneous/beta-testing/), even though this has ended (for now?).

Should it still be there?

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/KnowledgeBaseDNS #88](https://github.com/AdguardTeam/KnowledgeBaseDNS/issues/88) via [**Zenhub**](https://www.zenhub.com/)
