### ISSUE TITLE
User rules changes aren't taking effect within the AdGuard TTL

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardDNS#493]
There seems to be something going very wrong at the moment when trying to make user list changes, with changes not taking effect anywhere near the set TTL time.

**Steps to reproduce**
1. Set TTL to 0 to ensure changes take effect swiftly
2. Block a domain such as google.com for example
3. Visit google.com
4. Site will open normally (and will continue to open minutes later)

Confirming _Check the domain_ tool and the query log, it shows the domain as blocked in accordance with the TTL.
I also pinged the domain from a CLI to ensure it couldn't be reached, which it couldn't.

When it came to a browser, I tested this over a 10 minute period between iOS and macOS Safari with the changes either not taking effect within this time (macOS), or taking close to 10 minutes (iOS).

On both of these devices, I am using AdGuard DNS from a config profile for DNS.
On macOS I am using AdGuard for Safari.
On iOS I'm only using Safari filtering and advanced filtering.

There is no VPN being used and Private Relay isn't being used.

There is no additional filtering being done by firewalls, proxies etc.

**Comment by ameshkov** [comment]
TTL setting works for blocked requests only, it does not override TTL of all DNS records so it's okay that you're using the cached `www.google.com` record for a few minutes.

However, once it's blocked and you're trying to **unblock** `www.google.com`, the changes should be applied quickly.

**Comment by sjhgvr** [comment]
> TTL setting works for blocked requests only, it does not override TTL of all DNS records so it's okay that you're using the cached `www.google.com` record for a few minutes.
> 
> However, once it's blocked and you're trying to **unblock** `www.google.com`, the changes should be applied quickly.

I've actually posted about this bug the other way around in Adguard Telegram group.
- Domain blocked by blocklist.
- manually unblock domain
- remains blocked for a minute or more before it gets unblocked. (Even when TTL was set to 1)

**Comment by jslawler** [comment]
> TTL setting works for blocked requests only, it does not override TTL of all DNS records so it's okay that you're using the cached `www.google.com` record for a few minutes.
> 
> However, once it's blocked and you're trying to **unblock** `www.google.com`, the changes should be applied quickly.

Even when a private window is opened after the blocked requests are in place I can access the blocked domain.

**Comment by ameshkov** [comment]
Using [dnslookup](https://github.com/ameshkov/dnslookup) to verify.

1. Configured TTL to 1.
2. Run `dnslookup doubleclick.net https://${my device id}.d.adguard-dns.com/dns-query`
3. The response is this:

  ```
  dnslookup v. 1.8.1
  dnslookup result:
  ;; opcode: QUERY, status: NOERROR, id: 38108
  ;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
  
  ;; QUESTION SECTION:
  ;doubleclick.net.	IN	 A
  
  ;; ANSWER SECTION:
  doubleclick.net.	1	IN	A	0.0.0.0
  ```

4. This line is what matters: `doubleclick.net.	1	IN	A	0.0.0.0`, `1` here is the TTL.

So it seems on the DNS side it works as expected, something else in the chain caches it longer than it should.

How exactly do you have DNS configured on your devices?

**Comment by jslawler** [comment]
> Using [dnslookup](https://github.com/ameshkov/dnslookup) to verify.
> 
> 1. Configured TTL to 1.
> 2. Run `dnslookup doubleclick.net https://${my device id}.d.adguard-dns.com/dns-query`
> 3. The response is this:
> 
> ```
> dnslookup v. 1.8.1
> dnslookup result:
> ;; opcode: QUERY, status: NOERROR, id: 38108
> ;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
> 
> ;; QUESTION SECTION:
> ;doubleclick.net.	IN	 A
> 
> ;; ANSWER SECTION:
> doubleclick.net.	1	IN	A	0.0.0.0
> ```
> 
>  4. This line is what matters: `doubleclick.net.	1	IN	A	0.0.0.0`, `1` here is the TTL.
> 
> So it seems on the DNS side it works as expected, something else in the chain caches it longer than it should.
> 
> How exactly do you have DNS configured on your devices?

I'm using the config generated for macOS/iOS from AdGuard DNS.

**Comment by ameshkov** [comment]
Well, the only idea so far is that macOS/iOS has a minimum TTL and just ignore the values below that limit?

**Comment by jslawler** [comment]
> Well, the only idea so far is that macOS/iOS has a minimum TTL and just ignore the values below that limit?

Quite possibly.

The TTL on macOS was 65 last I checked, which doesn't explain why it would be multiple minutes for these changes to take effect.

In either case, happy for this to be closed if you can't reproduce it.

**Comment by ameshkov** [comment]
There are definitely some issues with respecting records TTL on macOS:
https://developer.apple.com/forums/thread/687725

**Comment by sjhgvr** [comment]
![2023-01-05 07_11_33-Media viewer](https://user-images.githubusercontent.com/51121527/210714166-b435e2be-ec59-4fd2-a066-8e40f1ca92ed.png)

**Comment by ameshkov** [comment]
@sjhgvr moved here: https://github.com/AdguardTeam/AdGuardDNS/issues/499
