### ISSUE TITLE
Unblocked request is marked as blocked in the query log

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardDNS#499]
![2023-01-05 07_11_33-Media viewer](https://user-images.githubusercontent.com/51121527/210714166-b435e2be-ec59-4fd2-a066-8e40f1ca92ed.png)

_Originally posted by @sjhgvr in https://github.com/AdguardTeam/AdGuardDNS/issues/493#issuecomment-1371825936_

**Comment by ameshkov** [comment]
Internal ID is AGDNS-1297

**Comment by ameshkov** [comment]
@sjhgvr as I understand, this was a DNS query that was originally blocked, and then you unblocked it from the Query log?

In this case the behavior is correct, the query was actually blocked, but now with the new state of User rules it is marked as "unblocked by this rule".

**Comment by Chinaski1** [comment]
Initially, when you unblock a domain via query log, it gets the behavior shown on the [screenshot](https://uploads.adguard.org/Chinaskivge1g.png).
But if you refresh the page after a short time or go to a previously blocked domain it will be marked as [unblocked](https://uploads.adguard.org/Chinaskijvds4.png) and a custom rule will be displayed
