### ISSUE TITLE
Why can't I access the AdGuardDNS website?

### ISSUE THREAD

**Issue by KevinGu0611** [AdguardTeam/AdGuardDNS#500]
I'm in China, and my ISP is China Mobile.This page cannot be accessed is displayed.I have tried clearing cookies but it didn't work.
<img width="605" alt="image" src="https://user-images.githubusercontent.com/107782505/211280943-a0c0afa6-43b4-4f8c-a699-b911f15d4d10.png">

**Comment by Chinaski1** [comment]
As of now, both adguard-vpn.com and adguard-dns.io are blocked for Chinese users. 

And while we can't say we are surprised to see the Chinese government take down the AdGuard VPN website, it's beyond us why the AdGuard DNS website was banned too.

We will keep you updated if anything changes in this regard.
