### ISSUE TITLE
WOT domain is blocked

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardDNS#501]
The WOT domain is blocked  in Adguard DNS
mywot.com

Let's you know the website score and if the website is safe or dangerous. I think this has to be unlocked by default.

**Comment by hagezi** [comment]
@Batman2814 I can't find `mywot.com` on the AdGuardDNS blocklist, on the @StevenBlack blocklist it can be found. Are you using this as a blocklist?

**Comment by ameshkov** [comment]
You can also unblock it manually in the User rules.
