### ISSUE TITLE
TTL settings are not working

### ISSUE THREAD

**Issue by twitterblue** [AdguardTeam/AdGuardDNS#502]
Hey Team,

I am facing a sudden spike in traffic as well as the TTL I set seems to be not working at all. Could you please check what is the issue with it?

![image](https://user-images.githubusercontent.com/118989300/212477327-0617cade-1b01-4c9d-87eb-74652d575a54.jpeg)
![image](https://user-images.githubusercontent.com/118989300/212477334-1466869d-af81-475b-be10-2a5b09529851.jpeg)
![image](https://user-images.githubusercontent.com/118989300/212477338-222e4d71-b9c9-4e9e-a9ac-93a74e179aed.jpeg)
![image](https://user-images.githubusercontent.com/118989300/212477345-799d4b13-0750-45d2-89d7-c08744cc666d.jpeg)

At midnight, the block rate went upto 93%. If blocked requests are not supposed to be made before 3600 seconds then why the similar blocked requests are showing up in the query log?

**Comment by ijuliank** [comment]
that is because you blocking those domains, wich the app keeps trying over and over again until it can reach the domain

**Comment by twitterblue** [comment]
So that is why we are putting TTL right? I mean what is the use of TTL if the app can ignore the TTL and request the domain again?

**Comment by ijuliank** [comment]
no thats not why you are putting a TTL, TTL is time to life yes, but that doest effect the app usage of trying it again

**Comment by twitterblue** [comment]
Then why we are setting it? I mean I have a genuine concern if that TTL is not working at all for appa then why to use it at first place? What would be the use of it or what if I disable it altogether?

**Comment by ijuliank** [comment]
because its a time to life for any query, it cant stop a phone sending queries, it will keep blocking it because its blocked,
and the phone keeps trying it until it reach the dest..

**Comment by hagezi** [comment]
DNS TTL (time to live) is a setting that tells the DNS resolver how long to cache a request before making a new request. The collected information is then stored in the cache of the recursive or local resolver for the duration of the TTL before it queries again for new, updated details.

For example, if the DNS TTL is set to 1800 seconds (30 minutes), the resolver will need to re-collect information about a website such as varonis.com every 30 minutes. If 100 users visit the website during this period, they will all see the same thing until the resolvers update their TTL. Time to live is the least understood element of the entire DNS strategy.

You have changed the TTL of the DNS resolver, of AdGuardDNS, not for the local client.
To get the desired behaviour you would have to change the TTL of the client OS.

**Comment by twitterblue** [comment]
Then why the description is contrary to what you are suggesting? ![image](https://user-images.githubusercontent.com/118989300/212498929-dfd90ce4-b710-49c3-9a13-400cebc8ad41.jpeg)

**Comment by hagezi** [comment]
You are right, we are talking about DNS TTL. Maybe your client ignores the TTL.

**Comment by hagezi** [comment]
@twitterblue 

https://github.com/AdguardTeam/AdGuardDNS/issues/493

**Comment by twitterblue** [comment]
Hey thank you for pointing me to the thread direction. But I still believe this bug needs more attention. If I can still see similar blocked requests multiple times then it is not working as expected. Please if this gets checked then it would be great!!

**Comment by Chinaski1** [comment]
For example, you set the TTL at 3600 sec.
This means that the blocked request will be cached for 60 minutes (If you unblock it, it will be available after this time interval).
This setting does not affect the requests themselves, it only stores information about the response.
Therefore, if the application sends them, DNS continues to block them and all requests go to the log.

**Comment by twitterblue** [comment]
Ohh okay got it, sorry, both of you for the confusion. So basically when server encounters first request which ideally should be blocked by any set blocklists by the user, the server remembers that the request which just got hit for the first time will needs to be blocked for next 60 minutes (in my case). So my applications or clients which are using this AG DNS 2.0 are not aware of the TTL so they will continually send the DNS requests to AdGuard server and then AdGuard server will directly tell my clients that this link was blocked in last 60 minutes so serving the same response from the server cache instead of making further queries to other root dns servers. Got it. Thanks.
