### ISSUE TITLE
Infinite redirection when accessing a Gov website in Philippines

### ISSUE THREAD

**Issue by zeezeepiggy** [AdguardTeam/AdGuardDNS#503]
Hi team, 

can you please check this website:

https://consular.dfa.gov.ph/services/passport/passport-faqs

it will try to redirect to a new website to  dfa-oca.ph which is the updated site but its doing an infinite loop.

when i disable Adguard DNS, the redirection works. 

Please check.

**Comment by Chinaski1** [comment]
Hello there!

AdGuard DNS uses [Anycast](https://adguard-dns.io/en/blog/anycast-and-bgp-how-adguard-dns-serves-millions-of-queries.html) technology so we can't manage traffic routing 100% of the time.

At this point, we're compiling problems in internal list with the possibility of their correction in nearest future.
Please provide following information via email to support@adguard.com (also share a link to this issue on GitHub):

1) Your IP address: https://adguard.com/en/test.html
2) ASN. 
3) ISP name.
4) DNS server location: https://adguard.com/en/test.html

I am closing this task as it goes to the internal list of routing issues.
