### ISSUE TITLE
AdGuard DNS breaks Rostelecom IPTV

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdGuardDNS#51]
Contents (in Russian):

> Здравствуйте.
> 
> Имеется следующее оборудование:
> 1) ТВ-приставка (SML-482HD) "Интерактивное телевидение 2.0" от компании "Ростелеком".
> 2) Роутер Keenetic Ultra (KN-1810) с включенным на нем AdGuard DNS. Опция была активирована в настройках роутера в разделе Internet Safety, а не путем прописывания в соответствующем разделе настроек роутера DNS серверов AdGuard.
> 
> Если для ТВ-приставки установлена опция фильтрации трафика через AdGuard DNS, то приставка при загрузке не может получить от серверов "Ростелекома" ссылки на плей-листы и, как следствие, проигрывать их. На приставке также не работают диагностические тесты, например, на проверку необходимой ширины канала.
> 
> При отключении для приставки функции фильтрации трафика (установка опции в настройках роутера "No Protection") никаких проблем с интерактивным телевидением не возникает - приставка работает, как должна, осуществляя стриминг онлайн-контента и проходя все диагностические тесты.
> 
> При отсутствии проблем приставка соединяется с серверами 212.193.155.242 и 212.193.153.146 и работает с плей-листами http://zabava-htlive.cdn.ngenix.net/*, http://a3569457554-zabava-htlive.cdn.ngenix.net/* и http://212.193.153.146/*.
> 
> Проблема появилась 20.09. Днем ранее - 19.09 - при включенном AdGuard DNS на роутере для всех устройств локальной сети, включая ТВ-приставку, никаких проблем не наблюдалось.
>

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdGuardSDNSFilter/pull/131
@akmLaVx подправили вроде. Пусть проверит вечером
