### ISSUE TITLE
Update information about Adguard DNS on the website

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardDNS#51]
https://adguard.com/en/adguard-dns/overview.html

Update this line:
`—  Adguard DNS is completely free **for personal use**. You don’t install anything, so there is nothing to pay for :)`

Add a "Pricing" section.
#### Personal use

Adguard DNS is completely free for personal use.
#### Enterprise

Significant requirements? Please contact us (mailto:dns@adguard.com) TODO: Text

@vbagirov please provide text for the enterprise section and for email subject and content.

**Comment by nkartyshov** [comment]
Done someone else
