### ISSUE TITLE
www.ghmc.gov.in not opening using public DNS

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardDNS#512]
@mohitanchalia commented on [Wed Jan 18 2023](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1195)

### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

Public DNS 94.140.14.14, 94.140.15.15

### What browser or app do you use?

Chrome, Safari

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://www.ghmc.gov.in

### Add your comment and screenshots

Trying to access a government website ([www.ghmc.gov.in](http://www.ghmc.gov.in/)) in India, but it does not load with AdGuard Public DNS turned on as seen in below screenshot (with and without Adguard DNS):
![Without and with Adguard DNS ghmc gov in](https://user-images.githubusercontent.com/122956584/213086868-1d6931cb-caac-4239-800c-dbe40cf70091.png)

Request you to please allow this website to load via your Public DNS.

### Privacy

- [X] I agree to follow this condition

---

@Alex-302 commented on [Wed Jan 18 2023](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1195#issuecomment-1386916723)

I guess this is site's DNS configuration issue. Maybe this site works in India only.

Same with Google DNS 

![image](https://user-images.githubusercontent.com/8361299/213162200-68798839-fe31-409e-ae36-3fdd98e636ac.png)

---

@mohitanchalia commented on [Wed Jan 18 2023](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1195#issuecomment-1387220237)

But it's opening correctly here using Google's DNS server 8.8.8.8, 8.8.8.4. 
Only when I change to Adguard Public DNS, it stops working.

---

@Alex-302 commented on [Wed Jan 18 2023](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1195#issuecomment-1387591340)

Are you in India or outside?

---

@mohitanchalia commented on [Thu Jan 19 2023](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1195#issuecomment-1396297334)

India

---

@Alex-302 commented on [Thu Jan 19 2023](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1195#issuecomment-1396623054)

Please check if you can visit this site with VPN.

---

@mohitanchalia commented on [Thu Jan 19 2023](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1195#issuecomment-1396941965)

Yes, it's working with a USA VPN

**Comment by mohitanchalia** [comment]
![Screenshot_20230123-102915_Chrome](https://user-images.githubusercontent.com/122956584/213968657-19e4cde6-02cc-4b2a-9581-742702aeb477.png)
The Adguard Test page shows DNS Server being used as: "dns2-dp-sg-2"
Maybe it is an issue from this side.

**Comment by mohitanchalia** [comment]
Just checked, it's working now.
DNS Server is being used is "dns2-dp-sg-6"

**Comment by mohitanchalia** [comment]
Request you to please close this issue as the website is now working on AdGuard Public DNS.
