### ISSUE TITLE
DNS Blocking Orders

### ISSUE THREAD

**Issue by trimechee** [AdguardTeam/AdGuardDNS#514]
Hello, thank you again for these amazing dns servers : 

I discover that some dns providers have Blocking Orders Court Ruling even if these dns providers try to oppose this censorship....

https://www.quad9.net/fr/news/blog/quad9-files-official-objection-opposing-sony-music-s-german-court-ruling/

https://torrentfreak.com/cloudflare-vows-to-fight-global-1-1-1-1-dns-blocking-orders-220915/

so my question does AdGuardDNS receive  Blocking Orders and does AdGuardDNS block access to certain streaming websites ?

Thank you !

**Comment by ameshkov** [comment]
We're aware of the issue: https://adguard.com/en/blog/adguard-quad9-statement.html

Thank god we haven't yet received any blocking orders.

**Comment by trimechee** [comment]
Awesome !! Thank you very much :) 💯
