### ISSUE TITLE
Test required for this scenario of YouTube

### ISSUE THREAD

**Issue by twitterblue** [AdguardTeam/AdGuardDNS#516]
Hi Everyone,

I just tested one from my end that if we are blocking, **manifest.googlevideo.com** on the DNS level then most of the ads on the browser level for non-YT premium users getting disappeared and it is working most of the time. If someone can test it on the mobile as well as other devices level would be much appreciated.

**Comment by ameshkov** [comment]
Can't confirm it here unfortunately.
