### ISSUE TITLE
Missed trackers and ads for iphone

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardDNS#52]
settings.crashlytics.com Is on amazon app and whisper app and ifunny app

**Comment by jo2dan23** [comment]
On iphone sorry forgot to include that

**Comment by jo2dan23** [comment]
e.crashlytics.com And the above is also on whisper app for iphone also

**Comment by jo2dan23** [comment]
api.branch.io is also located in whisper app. Its a metrics thing found on Google

**Comment by jo2dan23** [comment]
iadsdk.apple.com is another ad domain that should be blocked used by apple

**Comment by jo2dan23** [comment]
adserver.snapads.com Isnt being blocked on snapchat app for iphone

**Comment by jo2dan23** [comment]
mobileanalytics.us-east-1.amazonaws.com is another that appeared in my logs

**Comment by Alex-302** [comment]
Added:
```
||crashlytics.com^
||adserver.snapads.com^
||mobileanalytics.*.amazonaws.com^
||adserver.snapads.com^
```
> api.branch.io

It will break some apps.

>iadsdk.apple.com
I can't check it

**Comment by jo2dan23** [comment]
Thanks for the fast response how long does it take for it to take effect? It still shows not blocked in my dns logs. Also datametrical.com is a tracker in whisper app and sc-analytics.appspot is a tracker in snapchat

**Comment by Alex-302** [comment]
I don't know, but is not fast, as with common filters. Maybe 12 hours.

**Comment by jo2dan23** [comment]
Ok thanks if i find anymore i will post them here.

**Comment by jo2dan23** [comment]
gate.hockeyapp.net Is another found in ifunny app

**Comment by jo2dan23** [comment]
Were u able to test the datametrical and sc-analytics? If anything is broken on my end i will let you know so they can be removed

**Comment by jo2dan23** [comment]
sb.scorecardresearch.com And www.googletagmanager.com are unblocked in flixster app

**Comment by jo2dan23** [comment]
So is google analytics. Im guessing those three are not blocked for a reason? Or is adguard dns just starting up? Sorry for all the comments

**Comment by jo2dan23** [comment]
ssl-google-analytics.l.google.com Is found in video tube app

**Comment by jo2dan23** [comment]
www-google-analytics.l.google.com Appears in my logs. Dont know which app requests it.

**Comment by jo2dan23** [comment]
admarvel.s3.amazonaws.com
m.quantcount.com

**Comment by ameshkov** [comment]
@Alex-302 I suppose that you should put these rules to the "Mobile Ads Filter", don't make it dns specific. All these domains are also used in Android apps, so it could be helpful for AG Android.

**Comment by ameshkov** [comment]
@Stillness-2 could you please what happens if we block Apple ad SDK domain?
`iadsdk.apple.com `

**Comment by ameshkov** [comment]
I guess we should try blocking these three:
`googleadapis.l.google.com`
`www-google-analytics.l.google.com`
`ssl-google-analytics.l.google.com`

Blocking google tag manager is dangerous, some apps may depend on it.
`www-googletagmanager.l.google.com`

**Comment by Alex-302** [comment]
Ok. Added to mobile filter:
```
||googleadapis.l.google.com^$empty
||www-google-analytics.l.google.com^$empty
||ssl-google-analytics.l.google.com^$empty
||adserver.snapads.com^$empty
||crashlytics.com^$empty
```
to spyware
```
||collector.githubapp.com^
||events-endpoint-*.amazonaws.com^
```
But these rule are missed in DNS filter:
```
||mobileanalytics.*.amazonaws.com^
||quantcount.com^
```

**Comment by ameshkov** [comment]
@Alex-302 give it some time, they will be transferred to DNS filter eventually.

**Comment by jo2dan23** [comment]
@ameshkov so these will be added to dns filter for iphone by the auto update correct? Just makikg sure xD

**Comment by jo2dan23** [comment]
alog.umeng.com
stats.jpush.cn
log.iyunmai.com

**Comment by ameshkov** [comment]
> @ameshkov so these will be added to dns filter for iphone by the auto update correct? Just makikg sure xD

Yeah, it's just we do it not very often for DNS.

**Comment by Alex-302** [comment]
```
||alog.umeng.com^
||stats.jpush.cn^
||log.iyunmai.com^
||admarvel.*.amazonaws.com^
||analytics-collector-*.elb.amazonaws.com^
```
I need a strings from the log for these requests.

**Comment by jo2dan23** [comment]
What do you mean by strings? Sorry confused

**Comment by Alex-302** [comment]
Text lines from the log file.

**Comment by jo2dan23** [comment]
@Alex-302 here is what i see
![img_2684](https://cloud.githubusercontent.com/assets/15130139/19214011/70318916-8d3f-11e6-9ac1-696fff7b9298.PNG)

**Comment by jo2dan23** [comment]
Also these were never added to dns: ( I think because the list they were added to isnt part of the filter template)

||googleadapis.l.google.com^
||www-google-analytics.l.google.com^
||ssl-google-analytics.l.google.com^
||adserver.snapads.com^
||crashlytics.com^
||collector.githubapp.com^
||events-endpoint-*.amazonaws.com^
||quantcount.com^

**Comment by jo2dan23** [comment]
If i may suggest these list be added to dns:

https://github.com/AdguardTeam/AdguardFilters/blob/master/MobileFilter/sections/spyware.txt
https://github.com/AdguardTeam/AdguardFilters/blob/master/SpywareFilter/sections/tracking_servers_firstparty.txt

**Comment by jo2dan23** [comment]
www.adtilt.com
api.instabug.com

Some more

**Comment by jo2dan23** [comment]
Sorry i didnt mean to close it. You mean the IP address correct?

**Comment by ameshkov** [comment]
@jo2dan23 it would be better to get the whole requests log file. It will be attached to the support email, named "tunnel.txt"

**Comment by jo2dan23** [comment]
@ameshkov i sent it to support@adguard.com

**Comment by ameshkov** [comment]
@jo2dan23 could you please tell us your customer ID so that we could find the ticket?

**Comment by jo2dan23** [comment]
@ameshkov here is my log 

https://nopaste.me/view/55f135c7

**Comment by ameshkov** [comment]
@jo2dan23 great, thank you! @Alex-302 will take a look at it.

**Comment by jo2dan23** [comment]
@ameshkov no problem it looks like there is some more trackers i missed that are in that log file also

**Comment by jo2dan23** [comment]
device-api.urbanairship.com
jnjconsumer.sc.omtrdc.net
combine.urbanairship.com

These are trackers i think they are in the log file

**Comment by jo2dan23** [comment]
b.stats.paypal.com
slc.stats.paypal.com

Found in paypal app

**Comment by Alex-302** [comment]
> @Alex-302 will take a look at it.

there are over 5k records. What should I do with it?

**Comment by Alex-302** [comment]
@ameshkov 
> @Alex-302 will take a look at it.

there are over 5k records. What should I do with it?

**Comment by jo2dan23** [comment]
@Alex-302 if you use notepad ++ you can find what you  need easy. I assume thats what your asking? Otherwise i cAn cut and paste the lines you need

**Comment by jo2dan23** [comment]
here is the full list of trackers from the logs that can be blocked:

omtrdc.net
urbanairship.com
datametrical.com
log.iyunmai.com
stats.jpush.cn
umeng.com
collect-elb-*.amazonaws.com
leanplum.com
appboy.com
adserver.pandora.com
intowow.com
device-analytics.rollout.io
ce-global-track-*.amazonaws.com
analytics-rollout-*.amazonaws.com
data.mob.com
stats.pandora.com
log.musical.ly

**Comment by jo2dan23** [comment]
@Alex-302 did that log help?

**Comment by jo2dan23** [comment]
@Alex-302 found some more in starbucks app

sbux-dl.urbanairship.com
c00.adobe.com (Adobe app marketing)
assets.adobedtm.com

**Comment by Alex-302** [comment]
@jo2dan23 please don't remove messages.
I will check and add domains a little bit later.
