### ISSUE TITLE
cifraclub.com.br incorrect blocking

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdGuardDNS#52]
Website: https://www.cifraclub.com.br/

User 2327004 reports that this website is actually a legitimate music site in Brazil. They believe the blocking is not justified.

**Comment by batata004** [comment]
Yeap, that website is legit the and largest one in south america that provide tabs and keys for millions of songs. I see no reason why it should be being blocked! Just google around, this website is massive and has nothing to do with ads

**Comment by Alex-302** [comment]
wrong repository. About incorrect blocking write here next time https://github.com/AdguardTeam/AdGuardSDNSFilter
