### ISSUE TITLE
nflximg.com is missing the icon svg for Netflix in the query log

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardDNS#522]
<img width="853" alt="Screenshot 2023-01-26 at 9 29 24 pm" src="https://user-images.githubusercontent.com/95468948/214825048-38b7be12-2d07-4c8a-8139-c4f6871ffb72.png">

It should be showing the Netflix icon as the domain is in the [services.json](https://github.com/AdguardTeam/HostlistsRegistry/blob/a688b5072f1599194819d77113af614d9264d2a9/assets/services.json#L1451) file.

**Comment by Chinaski1** [comment]
Moved to https://github.com/AdguardTeam/companiesdb/issues/35
