### ISSUE TITLE
Resetting filters does not clear the search box

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardDNS#524]
When resetting the filters in the query log, I would expect the search box to also be cleared to fully reset the search query.
Currently it does not.

https://user-images.githubusercontent.com/95468948/214934515-273e3ccb-c421-4c19-998f-917bbb863ccc.mov

**Comment by Chinaski1** [comment]
Fixed in [v2.1.5](https://adguard-dns.io/en/versions.html#2.1.5)

**Comment by jslawler** [comment]
@Chinaski1, this hasn't been resolved yet it seems.

https://user-images.githubusercontent.com/95468948/216706922-0ed59806-ea78-468f-ad79-0ab030e72e7f.mov
