### ISSUE TITLE
Query Log doesn't seem to filter live right away

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardDNS#525]
![20230126_13374313 Adguard dns 111](https://user-images.githubusercontent.com/96619913/214934254-8b77c46c-f632-441a-9f23-2812947bc914.png)

its takes along time for it to refresh the query log I was waiting over 6 minutes and still it wasn't refreshing so it actually takes longer then 6 minutes. the screenshot time says 1:30pm so I waited to 1:36 and it still wouldn't refresh Query Log

**Comment by Chinaski1** [comment]
I checked the situation you described and encountered no issues.
The automatic filter update interval is 10-15 seconds and works correctly.

If the issue reproduces again reopen the task.
