### ISSUE TITLE
DNS Client (Dnscache) service

### ISSUE THREAD

**Issue by trimechee** [AdguardTeam/AdGuardDNS#529]
Hello, I remember having read that when we modify the host files to block ads, it is recommended to deactivate the DNS Client (Dnscache) service... and therefore concerning our beloved AdGuardDNS adblock which certainly uses many of adblock filters, do you advise us to disable the DNS Client service (Dnscache) of windows 10 for more effective ad blocking please ?

**Comment by ameshkov** [comment]
Not really, I am not sure what would be the purpose of disabling caching.
