### ISSUE TITLE
To activate the search box in the query log, you must hit the enter/return key

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardDNS#530]
When entering a search term in the search box within the query log, the user must hit enter/return to activate the filter within the query log else it won't show the result.

This should likely either have a button to activate the search, or live refresh as the user is typing. Given the issues live refreshing has had in the past with the AdGuard DNS dashboard, I assume the better choice here would be to have a button instead similar to when changing the server or device name.

The enter/return key was pressed at 11seconds in this video. You'll see nothing happens for the first 10 seconds.

https://user-images.githubusercontent.com/95468948/216708039-7aeb1c17-4a73-4d63-88a5-d4dacbfdbb8a.mov

**Comment by Chinaski1** [comment]
The described situation is reproduced only when copypaste the domain, if you enter the domain manually then the search takes place in real-time.
But in any case the search must be activated regardless of the input method, we will fix that.

**Comment by Chinaski1** [comment]
Fixed in [v2.1.6](https://adguard-dns.io/en/versions.html#2.1.6)
