### ISSUE TITLE
Increase max block ttl to 7200 or go all the way to 86400

### ISSUE THREAD

**Issue by GiddyGoatGaming** [AdguardTeam/AdGuardDNS#531]
I would like to request to add the ability for a block ttl higher than the current max of 3600. This feature would be more impactful on free users that only have 300k queries a month. I find that it is reasonable to request a higher block ttl since the filters get updates ~18 times a day and not 24 times if that makes sense.

Currently, controld supports higher than 86400 for block ttl which is insane and if that were possible here, some people would benefit greatly. (Some people being very non aggressive blocklist users that don’t need whitelisting hardly ever)

**Comment by Chinaski1** [comment]
Hello there!
The answer to a similar request was given [in this issue](
https://github.com/AdguardTeam/AdGuardDNS/issues/379).
