### ISSUE TITLE
FR: Resolve domain to another domain

### ISSUE THREAD

**Issue by ankushg** [AdguardTeam/AdGuardDNS#532]
Hosts style syntax lets me write a rule like `REDIRECT_IP DOMAIN_1 DOMAIN_2` that resolves requests for `DOMAIN_1`/`DOMAIN_2` to `REDIRECT_IP`

I'd like to write rules like `REDIRECT_DOMAIN DOMAIN_1 DOMAIN_2` which would resolve requests for `DOMAIN_1` to `REDIRECT_DOMAIN`

**Comment by Chinaski1** [comment]
Hello there!
This feature is already implemented with[ dnsrewrite rules](https://adguard-dns.io/kb/general/dns-filtering-syntax/#rule-modifiers).
