### ISSUE TITLE
Adguard private DNS not showing filtering

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardDNS#533]
All of my devices are not showing filtering it all stopped 2-3 hours ago but still says I'm connected when I go onto adgaurd services check page. Don't know what going on.

**Comment by Batman2814** [comment]
![Screenshot_20230207_142114_Samsung Internet](https://user-images.githubusercontent.com/96619913/217356509-548b13f9-33c6-4be6-9e8b-69dc470ef17b.jpg)
![Screenshot_20230207_142026_Samsung Internet](https://user-images.githubusercontent.com/96619913/217356511-f58ab5d6-c283-44a3-9b03-27138d31989f.jpg)


The time says 11:04 on every device. The time right now is 2:23pm .
Nothing showing filtering but days I'm still connected to adgaurd private dns.

**Comment by Batman2814** [comment]
Seems to be fixed now.

**Comment by Batman2814** [comment]
The live filtering seems to stop at random at times even though the device is being used it doesn't update filtering. At times there is 10 minutes or more of delay. There's definitely a problem here.

**Comment by Chinaski1** [comment]
Can you specify how this manifests itself, there is no information in the Filtering log during this period?

**Comment by hagezi** [comment]
@Chinaski1 Yes, I can confirm that, for a time the filter log is not updated. I have noticed this a few times, but have not paid attention to how long it is. At some point it is then up to date again. The entries from the period without update are then also included.

**Comment by Chinaski1** [comment]
If you notice a similar issue one more time, please follow [this link](https://dns.adguard-dns.com/info.txt) and send information regarding the server you are connected to.

**Comment by Batman2814** [comment]
![Screenshot_20230209_080600_Samsung Internet](https://user-images.githubusercontent.com/96619913/217834906-88fb734c-600d-4377-81cc-616bc2f60c73.jpg)

**Comment by Batman2814** [comment]
On mobile

**Comment by Batman2814** [comment]
dns2- dp-chi-2 (mobile)

**Comment by Batman2814** [comment]
Mobile: dns2-dp-chi-1

**Comment by Batman2814** [comment]
dns2-dp-chi-2

**Comment by Chinaski1** [comment]
We did manage to catch the issue.
Will be fixed it in the next update, thanks for the information.

**Comment by hagezi** [comment]
Thanks @Chinaski1

**Comment by Batman2814** [comment]
Was this issue fixed in Version 2.2 of AdGuard Private DNS you guys said it would be fixed in the next update which was Version 2.2 or is this still an issue that will be fixed in the next update after Version 2.2?
