### ISSUE TITLE
Add default TTL hint

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardDNS#535]
If the default TTL is changed, the only way to know what the default TTL is, is to create a new server.

Consider adding the default TTL as a hint in the text box.

![image](https://user-images.githubusercontent.com/95468948/217758196-aae4c628-4bdb-426f-9455-36ad13286ad8.jpeg)

**Comment by Chinaski1** [comment]
Added in [v2.1.6](https://adguard-dns.io/en/versions.html#2.1.6)
