### ISSUE TITLE
Correct hint for clearing device logs/statistics

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardDNS#536]
Every device has a clear logs/statistics button, but they all say it will clear logs/statistics of all servers instead of that device.

I haven't tested it, but if it is only for the device, the text will need to change to show that it's for the device and not all servers.

If it does infect wipe all servers, my request is for a per device statistics/log wipe.

**Comment by Chinaski1** [comment]
Hello @jslawler 

In general, three types of statistical data cleaning are provided:
- From the [**Server settings**](https://uploads.adguard.org/Chinaski8g04q.png). Clears the statistics and filtering log on all server devices
- From the [**Device settings**](https://uploads.adguard.org/Chinaskislj8k.png). Clears the statistics and filter log for a separately selected device
- From the [**Account settings**](https://uploads.adguard.org/Chinaski7fy78.png). Clears all account statistics

**Comment by jslawler** [comment]
Hi @Chinaski1,

In that case, the hint text is wrong for clearing device logs and statistics.

It reads:
> Statistics of all servers will be deleted, and it will be impossible to restore them. Logs will remain available.

But should read something like:
> All statistics of this device will be deleted, and it will be impossible to restore them. Logs will remain available.

![image](https://user-images.githubusercontent.com/95468948/217797814-3904fdb9-3ec0-40d1-8699-0886ce761c85.png)

![image](https://user-images.githubusercontent.com/95468948/217797875-e21b8ec3-4ae6-40cd-b7ca-232eeffd4935.png)

**Comment by Chinaski1** [comment]
Yes, the text needs to be corrected.

**Comment by jslawler** [comment]
I've updated the title if you want to reopen in.

**Comment by Chinaski1** [comment]
Fixed in [v2.1.6](https://adguard-dns.io/en/versions.html#2.1.6)
