### ISSUE TITLE
Query log is unable to load

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardDNS#537]
When trying to load the query log, I'm getting the below errors.

[Error] Failed to load resource: the server responded with a status of 500 () (companies_filter, line 0)
https://api.adguard-dns.io/api/v1/stats/companies_filter?time_from_millis=1675849760737&time_to_millis=1675936160736

[Error] Unhandled Promise Rejection: Error: getCompaniesFilter
	Sl (a.main.637.min.js:1:2509149)
	u (a.main.637.min.js:1:2524237)
	promiseReactionJob

**Comment by ameshkov** [comment]
Looking into it, probably some of the companiesdb changes were problematic
