### ISSUE TITLE
Requests from Ontario routed to Miami instead of Toronto

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdGuardDNS#538]
So I just started using AdGuard DNS and for some reason, it is connecting me to the Miami server even though I’m located in Ontario, Canada. Should I not be connected to a closer server?

CRM ID (w/ traceroute logs): **719549**

**Comment by D13410N3** [comment]
At this moment Toronto server is serving old AdGuard DNS addresses (not 94.140.*).
So, routing you to US servers is right behaviour in this case
