### ISSUE TITLE
Delay on query log refreshing

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardDNS#540]
I presume this is an intermittent issue (#525), but as it stands, no new data has come across for a considerable amount of time (see query log time vs system time).

At minute 39, all the missing queries came across in a huge chunk of data (about 3 pages worth) rather than live as I would have expected it to be.
I'm guessing the way that it came across in a large chunk this is by design. In any case, if it's not intentional I've raised an issue to resolve the issue if there is one.

<img width="1346" alt="Screenshot 2023-02-15 at 3 36 42 pm" src="https://user-images.githubusercontent.com/95468948/218942065-b8748e57-3db7-4c0b-ba05-4b2f457b68d8.png">

**Comment by ameshkov** [comment]
I am trying to understand, do the queries actually missing from the query log or is the problem is that auto-refresh does not work as expected?

**Comment by jslawler** [comment]
It seems there's not a delay, but rather refreshing the page does not act the same as tapping the blue reload button on the query log.
For some reason when the page is refreshed by the browser, the old data is presented again, rather a continuation of the live data.

**Comment by Chinaski1** [comment]
@jslawler 
I can't reproduce the issue, could you specify the browser version?

**Comment by jslawler** [comment]
Safari Version 16.3 (18614.4.6.1.6)

I can no longer reproduce this after a reboot. I'll open a new issue if I can repo it again, but it seems like there may have been some sort of data retention here that wasn't clearing on page refresh.
