### ISSUE TITLE
EDNS Client Subnet could not be disabled

### ISSUE THREAD

**Issue by msoxzw** [AdguardTeam/AdGuardDNS#542]
In order to protect privacy, EDNS Client Subnet ought to be opted out, like Google Public DNS.

The "ecs" (EDNS Client Subnet) could be handily checked via opening https://test.nextdns.io/
Meanwhile, we could enable or disable ECS by setting `network.trr.disable-ECS` in `about:config` page of Firefox.

**Comment by ameshkov** [comment]
In the case of AdGuard DNS, ECS is implemented in a privacy-conscious way and does not contain your actual subnet.

We're going to post an article later explaining the details later.

PS: `test.nextdns.io` when you're not using NextDNS seems to be showing data that comes from your HTTPS connection and not from a DNS query.

**Comment by msoxzw** [comment]
For starters, https://test.nextdns.io/ gives the identical ECS result with `o-o.myaddr.l.google.com`.

The AdGuard Public DNS sends to authoritative servers the EDNS Client Subnet Header which is Internet geolocationally near to the client subnet. However, ECS makes DNS Cache less effective, and more importantly, the substituted subnet might be more inaccurate than anycast.

I use `dig` command to explore ECS feature of AdGuard Public DNS (94.140.14.14).
Plain
`dig o-o.myaddr.l.google.com TXT @94.140.14.14 +short`
Disable ECS
`dig o-o.myaddr.l.google.com TXT @94.140.14.14 +short +subnet=0.0.0.0/0`
[Massachusetts Institute of Technology subnet 128.30.0.0/15](https://ipinfo.io/AS3/128.30.0.0/15)
`dig o-o.myaddr.l.google.com TXT @94.140.14.14 +short +subnet=128.30.0.0/15`
[Stanford University subnet 171.64.0.0/14](https://ipinfo.io/AS32/171.64.0.0/14)
`dig o-o.myaddr.l.google.com TXT @94.140.14.14 +short +subnet=171.64.0.0/14`
All of it return the same result: "edns0-client-subnet 213.209.148.0/24", [located in Finland](https://ipinfo.io/AS51765/213.209.148.0/24).

As a result, I hope that AdGuard Public DNS allows users opt out ECS instead of always-on.

**Comment by ameshkov** [comment]
> For starters, https://test.nextdns.io/ gives the identical ECS result with o-o.myaddr.l.google.com.

Hm, now it does indeed, but at the time when I was checking it, it was showing a wrong IP in ECS.

> However, ECS makes DNS Cache less effective, and more importantly, the substituted subnet might be more inaccurate than anycast.

The point about DNS caching is kind of true, but according to our measurements the difference is negligible.
The second point about accuracy is definitely not true. Moreover, it won't be true even if we had POPs in every country in the world.

> I use dig command to explore ECS feature of AdGuard Public DNS (94.140.14.14).

Interesting, let me get back to you once we figure out what's the reason for that.

**Comment by Chinaski1** [comment]
@msoxzw 

We have done work on changing the processing of ESC caching.
Could you check the changes on your side?

**Comment by msoxzw** [comment]
@Chinaski1
I appreciate your effort to fix this issue. Nonetheless, a seeming glitch might not well align with standard if ECS is disabled, i.e. `dig o-o.myaddr.l.google.com TXT @94.140.14.14 +short +subnet=0.0.0.0/0`.

According to [RFC 7871](https://datatracker.ietf.org/doc/html/rfc7871),

> The total
> number of octets used MUST only be enough to cover SOURCE PREFIX-
> LENGTH bits, rather than the full width that would normally be used
> by addresses in FAMILY.

The AdGuard Public DNS sends client subnet with full width to the authoritative nameserver instead of SOURCE PREFIX-LENGTH bits.

> A SOURCE PREFIX-LENGTH value of 0 means that the Recursive Resolver
> MUST NOT add the client's address information to its queries.  The
> subsequent Recursive Resolver query to the Authoritative Nameserver
> will then either not include an ECS option or MAY optionally include
> its own address information, which is what the Authoritative
> Nameserver will almost certainly use to generate any Tailored
> Response in lieu of an option.  This allows the answer to be handled
> by the same caching mechanism as other queries, with an explicit
> indicator of the applicable scope.  Subsequent Stub Resolver queries
> for /0 can then be answered from this cached response.

`dig o-o.myaddr.l.google.com TXT @8.8.8.8 +short +subnet=0.0.0.0/0`

Google public DNS (8.8.8.8) chooses to exclude an ECS option, whereas AdGuard Public DNS selects to include its own address information.

**Comment by Chinaski1** [comment]
Fixed at [v2.2](https://adguard-dns.io/en/versions.html)
