### ISSUE TITLE
Malware domain is not in statistics

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardDNS#543]
Hello,

looks like the malware domains is not shown in statistics. This domain is marked as blocked by safebrowsing:
![image](https://user-images.githubusercontent.com/45385632/220054793-c80d68a5-22aa-4a88-85ac-7c2098fe2d91.png)

but:

![image](https://user-images.githubusercontent.com/45385632/220054339-a75fe291-25c6-4438-8e7b-b3e96bec2d13.png)

![image](https://user-images.githubusercontent.com/45385632/220054448-9665103f-cf00-4d6d-aab3-387d3f3ade05.png)

Please take a look.

Thank you.

**Comment by Chinaski1** [comment]
The point is that these domains are [modified](https://uploads.adguard.org/Chinaskircima.png) by safebrowsing rules and do not apply to blocked requests. Therefore, they are not displayed in the statistics section as blocked.
