### ISSUE TITLE
Please adopt Anycast Network in Adguard DNS Free

### ISSUE THREAD

**Issue by jakecharlie** [AdguardTeam/AdGuardDNS#546]
I would like to suggest adopting Global anycast network of servers for Adguard DNS Free service.

For many years, users from different countries have been waiting for Adguard DNS to launch a local server so that the ping decreases.

For example, until today there is not even one server in Latin America and in Africa there is only one in South Africa to cover the entire continent. In Southeast Asia there is only one server in Singapore.

Do you know what the consequence of that is? Many people who want to use Adguard DNS list end up using this list through NextDNS.io, precisely because of the low ping, often not because of the possibility of adding other blockers lists. Or even give up this list and choose another free one in ControlD.com

As a result, the Adguard team has less browsing access data to analyze and identify new trackers and online ads.

I truly believe Global anycast network of servers is the solution so that Adguard free DNS can quickly expand to many countries. Unfortunately, ping currently reaches more than 200 ms in many countries, while Google Public DNS, Cloudflare DNS, NextDNS and Control D reach less than 10 ms.

Thank you

**Comment by ameshkov** [comment]
AdGuard DNS is already an anycast service with 15 points of presence.

We slowly expand it, but due to a very high load on our servers, we have strict requirements to the hosting providers that are used.

We have a plan of adding sao paulo this year this year.
