### ISSUE TITLE
Haven't received email Stats from Adguard Private DNS

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardDNS#547]
![Screenshot_20230226_140757_Samsung Internet](https://user-images.githubusercontent.com/96619913/221434533-02ed1179-48c2-4b30-8960-6cc35ea2ce37.jpg)

I haven't been receiving stats reports from Adguard Private DNS in my email.

**Comment by jslawler** [comment]
The last 2 weekly reports seem to have not been sent out. The last report received was 15 Feb 2023, showing information between 06 Feb 2023 and 12 Feb 2023.

**Comment by Batman2814** [comment]
My last Stat report was January 30 which was a weekly report. I didn't receive the Monthly stat report for January and no stat report for all of February.

**Comment by Chinaski1** [comment]
Hello!
Please contact me at k.gretskyi@adguard.com
I will check if the reports were sent to your email addresses correctly

**Comment by Chinaski1** [comment]
We fixed an issue with sending AdGuard DNS usage reports.
Thank you for the report.
