### ISSUE TITLE
Блокирование трафика с lh3.googleusercontent.com

### ISSUE THREAD

**Issue by BOR-LAND** [AdguardTeam/AdGuardDNS#549]
Используя AdGuardDNS - https://unfiltered.adguard-dns.com/dns-query блокируется трафик с lh3.googleusercontent.com

lh3.googleusercontent.com в https://chrome.google.com/webstore/category/extensions?hl=ru - нет картинок
lh3.googleusercontent.com в поисковике - https://www.google.com пропадает картинка аккаунта Google
+
не могу обновить приложения в браузере Opera, связанные домены:
clients2.google.com
clients2.googleusercontent.com
googlehosted.l.googleusercontent.com
Возможно проблема с доменами типа: *.googleusercontent.com

С Google DNS, Cloudflare DNS, OpenDNS таких проблем нет, странно, что такое происходит с "AdGuard DNS без фильтрации".
![Opera Снимок_2023-02-27_161628_chrome google com](https://user-images.githubusercontent.com/93826441/221549110-9eb30f12-a050-4ab3-ad6e-ca8000bc3fdd.png)

**Comment by BOR-LAND** [comment]
AdGuard DNS ping lh3.googleusercontent.com
Обмен пакетами с googlehosted.l.googleusercontent.com [64.233.162.132] с 32 байтами данных:
Ответ от 64.233.162.132: число байт=32 время=129мс TTL=57
Ответ от 64.233.162.132: число байт=32 время=129мс TTL=57
Ответ от 64.233.162.132: число байт=32 время=129мс TTL=57
Ответ от 64.233.162.132: число байт=32 время=129мс TTL=57

Google DNS ping lh3.googleusercontent.com
Обмен пакетами с googlehosted.l.googleusercontent.com [172.217.18.97] с 32 байтами данных:
Ответ от 172.217.18.97: число байт=32 время=97мс TTL=116
Ответ от 172.217.18.97: число байт=32 время=97мс TTL=116
Ответ от 172.217.18.97: число байт=32 время=97мс TTL=116
Ответ от 172.217.18.97: число байт=32 время=96мс TTL=116

Cloudflare DNS ping lh3.googleusercontent.com
Обмен пакетами с googlehosted.l.googleusercontent.com [142.250.207.193] с 32 байтами данных:
Ответ от 142.250.207.193: число байт=32 время=323мс TTL=113
Ответ от 142.250.207.193: число байт=32 время=324мс TTL=113
Ответ от 142.250.207.193: число байт=32 время=323мс TTL=113
Ответ от 142.250.207.193: число байт=32 время=323мс TTL=113

OpenDNS ping lh3.googleusercontent.com
Обмен пакетами с googlehosted.l.googleusercontent.com [172.217.18.97] с 32 байтами данных:
Ответ от 172.217.18.97: число байт=32 время=97мс TTL=116
Ответ от 172.217.18.97: число байт=32 время=97мс TTL=116
Ответ от 172.217.18.97: число байт=32 время=97мс TTL=116
Ответ от 172.217.18.97: число байт=32 время=97мс TTL=116

Quad9 DNS ping lh3.googleusercontent.com
Обмен пакетами с googlehosted.l.googleusercontent.com [142.250.74.97] с 32 байтами данных:
Ответ от 142.250.74.97: число байт=32 время=126мс TTL=57
Ответ от 142.250.74.97: число байт=32 время=127мс TTL=57
Ответ от 142.250.74.97: число байт=32 время=126мс TTL=57
Ответ от 142.250.74.97: число байт=32 время=126мс TTL=57

Проблема присутствует с ip адресом 64.233.162.132, сейчас AdGuard DNS выдает 142.250.185.65 с ним проблемы нет.
ping lh3.googleusercontent.com
Обмен пакетами с googlehosted.l.googleusercontent.com [142.250.185.65] с 32 байтами данных:
Ответ от 142.250.185.65: число байт=32 время=100мс TTL=116
Ответ от 142.250.185.65: число байт=32 время=99мс TTL=116
Ответ от 142.250.185.65: число байт=32 время=100мс TTL=116
Ответ от 142.250.185.65: число байт=32 время=100мс TTL=116
ping clients2.googleusercontent.com
Обмен пакетами с googlehosted.l.googleusercontent.com [142.250.185.65] с 32 байтами данных:
Ответ от 142.250.185.65: число байт=32 время=100мс TTL=116
Ответ от 142.250.185.65: число байт=32 время=100мс TTL=116
Ответ от 142.250.185.65: число байт=32 время=100мс TTL=116
Ответ от 142.250.185.65: число байт=32 время=100мс TTL=116

**Comment by Chinaski1** [comment]
Вы не могли бы выполнить команду `traceroute 94.140.14.140` и прислать её результат?
А также, пожалуйста, уточните каким провайдером/оператором связи вы пользуетесь.

**Comment by BOR-LAND** [comment]
Трассировка маршрута к dns-unfiltered.adguard.com [94.140.14.140]
с максимальным числом прыжков 30:

  1    <1 мс    <1 мс    <1 мс  192.168.100.1
  2     2 ms     2 ms     1 ms  82.200.242.222
  3     *        *        *     Превышен интервал ожидания для запроса.
  4     *        *        *     Превышен интервал ожидания для запроса.
  5   100 ms    99 ms   100 ms  82.200.159.197
  6   102 ms   102 ms   104 ms  212.162.43.245
  7   105 ms   105 ms   105 ms  AS33891-NET.edge9.Frankfurt1.Level3.net [62.67.4.226]
  8   101 ms   101 ms   101 ms  ae2-2029.fra10.core-backbone.com [81.95.15.69]
  9   115 ms   115 ms   115 ms  core-backbone.cdn77.com [5.56.19.238]
 10   116 ms   116 ms   116 ms  vl201.fra-mc1-dist-1.cdn77.com [185.229.188.155]
 11   101 ms   101 ms   100 ms  dns-unfiltered.adguard.com [94.140.14.140]

Мой провайдер: Kazakhtelecom - ASN9198

**Comment by ameshkov** [comment]
> Проблема присутствует с ip адресом 64.233.162.132, сейчас AdGuard DNS выдает 142.250.185.65 с ним проблемы нет.

Вроде бы сейчас выдает ожидаемый адрес (142.250.185.65). Может быть временные проблемы роутинга?

Давайте пока прикрою задачу, но если снова повторится, переоткройте пожалуйста.
