### ISSUE TITLE
Ads in investing.com app on iOS with Adguard Pro

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardDNS#55]
With DNS filtering enabled, the app shows an ad upon start. Only happens when you start the app several times. I was able to reproduce.

The screenshot of DNS requests log is available here:

https://forum.adguard.com/index.php?threads/adguard-pro-not-blocking-ads-in-investing-com-app.14451/#post-105213

**Comment by nkartyshov** [comment]
Advertising is loaded from the domain ```a.investingsapp.net```, but the app do not working if this domain is blocked.
