### ISSUE TITLE
gras.mahakosh.gov.in not opening using public DNS

### ISSUE THREAD

**Issue by mohitanchalia** [AdguardTeam/AdGuardDNS#551]
What DNS filters do you have enabled?
Public DNS 94.140.14.14, 94.140.15.15

What browser or app do you use?
Chrome, Safari

Which device type do you use?
Desktop

What type of problem have you encountered?
Website or app doesn't work properly

Where did you encounter the problem?
https://gras.mahakosh.gov.in/

Add your comment and screenshots
Trying to access a government website (https://gras.mahakosh.gov.in) in India, but it does not load with AdGuard Public DNS turned on as seen in below screenshot (with and without Adguard DNS):
<img width="1405" alt="Screenshot 2023-03-01 at 10 42 12 AM" src="https://user-images.githubusercontent.com/122956584/222051206-48edbf51-3f7c-4b26-b1f3-aa626c2ccff3.png">
<img width="1403" alt="Screenshot 2023-03-01 at 10 41 50 AM" src="https://user-images.githubusercontent.com/122956584/222051224-d5fb51fb-382f-4b0c-b7c6-d4d60580dae1.png">

**Comment by jslawler** [comment]
As of this moment, the website is down. It is unrelated to AdGuard.

**Comment by mohitanchalia** [comment]
I can confirm that it is not down, and indeed opens when using Google DNS 8.8.8.8. 
However, it does not open when using USA VPN but opens from Indian ISP and Google DNS:
<img width="1216" alt="Screenshot 2023-03-01 at 4 47 03 PM" src="https://user-images.githubusercontent.com/122956584/222124996-e110111c-4f06-4bc4-9c3e-80b4b6c81e8a.png">

**Comment by jslawler** [comment]
Possibly region locked then.

**Comment by mohitanchalia** [comment]
Is there any solution? Apart from changing DNS back to Google DNS everytime I need to use this website?

**Comment by ameshkov** [comment]
It is indeed region locked on the name server level. It seems they don't respond to recursors that are not located in India.

Unfortunately, this is not something we can solve without adding servers in India. I hope we'll so that in the future, but can't give any ETA yet.
