### ISSUE TITLE
Allow responding to blocked domains for user rules

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardDNS#558]
In the event a user wants to respond to a blocked user rule a different way to the others, allow  the choice to do so rather than responding to all blocked domains the same way.

**Comment by ameshkov** [comment]
But there's `$dnsrewrite` modifier for this.

**Comment by jslawler** [comment]
Excellent point, I completely looked over that.

While on the subject and still related, the [kb states](https://adguard-dns.io/kb/general/dns-filtering-syntax/#dnsrewrite) that AdGuard Home treats `$dnsrewrite as a higher priority. Does it do the same for AdGuard DNS too?

> Rules with the dnsrewrite response modifier have higher priority than other rules in AdGuard Home.

**Comment by ameshkov** [comment]
> Does it do the same for AdGuard DNS too?

Yes, AG DNS uses the same filtering engine as AGH.
