### ISSUE TITLE
Bypass link on malware/phishing page alert

### ISSUE THREAD

**Issue by portalvasco** [AdguardTeam/AdguardDNS#56]
I see that page web alerts is working, dns shows a alert when anybody try to navigate to a malicious url.

My suggestion is that alert can bypass clicking on a link. 

The problem is that if the alert is a false positive users have to change dns to access it.

![adguarddns2](https://cloud.githubusercontent.com/assets/22648547/19142204/0a37c156-8b9c-11e6-8b78-dea4be87291a.jpg)

**Comment by ameshkov** [comment]
The problem is that it is almost impossible to do on the DNS-level, it has already resolved domain into a "blocking" address, you can't just roll it back.

For false positives the only way is to report it to us and wait for the fix.

**Comment by portalvasco** [comment]
Ok, thank you very much.
