### ISSUE TITLE
Merge list of badware sites

### ISSUE THREAD

**Issue by Esokrates** [AdguardTeam/AdGuardDNS#56]
In the following list
https://github.com/uBlockOrigin/uAssets/blob/master/filters/badware.txt
quite a few sites are not blocked using adguard dns, please consider merging that list!

Noticed it because the kids installed maleware from audacity.de, a fake site, which pretends to be the official page of the audacity software. The same goes for vlc.de and many others in that list.

**Comment by ameshkov** [comment]
@Chinaski1 please take a look.

Please note that the list by that link is very subjective. **Some** domains from there might be okay for adding to the parental control blacklist, but half of them are legit domains we cannot block.

**Comment by Chinaski1** [comment]
@Esokrates 
I will check these sites for harmful or fraudulent content.
Suspicious sites will be added to the AdGuard DNS blacklist.

**Comment by Chinaski1** [comment]
Here's a list of the sites I blacklisted:
stremanp.com
greatdexchange.com
pc-scan.website
wiilberedmodels.com
activeandbanflip.com
download.cnet.com
com.com
softonic.com
flexytalk.net
quickdomainfwd.com
roughted.com
vlc.de
audacity.de
securetoolext.com
appdownloads.co
audacity.es
audacity.fr
audacity.it
audacity.pl
azureus.es
bittorrent.es
bluestacksdownloads.com
celestia.es
celestia.fr
clonezilla.es
clonezilla.fr
clonezilla.it
filezilla.es
filezilla.fr
filezilla.it
garagebandforpc.org
gimp.es
gparted.fr
gparted.it
greenshot.fr
gparted.fr
gparted.it
greenshot.org
bitcoinqrcodegenerator.win
check-prizes-now2.life


As for the others, they were either already on the blacklist or their malignancy was not confirmed

**Comment by Esokrates** [comment]
@Chinaski1 Thanks, but the protection is not effective unfortunately. While `vlc.de` gets blocked, `https://www.vlc.de/` leads directly to the site, tested on chromium on ubuntu and chrome on android. This is a problem, since googeling for "vlc download" gives me the fake site on top and clicking the link leads to the site.

Please have a look again.

**Comment by Esokrates** [comment]
@Chinaski1 @ameshkov audacity.de and vlc.de still work. Could you please have a look at those?
