### ISSUE TITLE
Toggling filter lists too quickly results in some actions not registering

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardDNS#562]
If toggling filter lists too quickly before the previous action has completed its cycle, some actions won't be carried out.

https://user-images.githubusercontent.com/95468948/223460818-0f09338c-37fa-46da-82b3-1a112301b2b6.MOV

**Comment by Chinaski1** [comment]
Internal ID: AGDNS-1486

**Comment by Chinaski1** [comment]
Fixed at v2.3
