### ISSUE TITLE
The error condition is not reset when the type of line to be added is changed

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardDNS#563]
### Steps to reproduce

1. Open `Add user rule` window
2. Enter `||example.com^` and press `Block`
3. After the frame turns red (it has no error message), select `Add custo rule`.

### Actual behavior

`Add` button is disabled.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/8361299/224364219-14c60a5d-a34b-44f3-bbe3-f54fcdfab948.png)

</details>

The `Add` button is unlocked if you edit entered text (add/remove any symbol).

### Expected behavior

Reset the error condition on switching the type of the added text.

**Comment by ameshkov** [comment]
Internal ID: AGDNS-1384

**Comment by Chinaski1** [comment]
Fixed at [v2.2](https://adguard-dns.io/en/versions.html))
