### ISSUE TITLE
https://github.com/AdguardTeam/AdGuardDNS/issues is not opening but it is valid 

### ISSUE THREAD

**Issue by cuedutest** [AdguardTeam/AdGuardDNS#567]
### Platform

Android

### Protocol

Regular

### Do you use AdGuard app?

Yes I am

### Issue Details

https://github.com/AdguardTeam/AdGuardDNS/issues is not being resolved

### Actual Behavior

it should open the website 

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Chinaski1** [comment]
Frankly speaking, I don't really understand what the issue is.
Could you describe the situation in more detail?

**Comment by jslawler** [comment]
@Chinaski1 i believe this may be the issue [here](https://t.me/adguard_en/220737).

>Hello promos.www.adjarabet.com is not resolving by using your DNS

The timeline matches up with what the Telegram user was saying.

**Comment by Chinaski1** [comment]
At the first glance like this website is [fraud](https://uploads.adguard.org/Chinaskiyun8y.png).

**Comment by Chinaski1** [comment]
@cuedutest 
We do our best to reduce the percentage of false positives, but they still occur. If you come across this behavior from AdGuard, please send us a complaint about the false-positive alarm. You can submit such complaints via our technical support at support@adguard.com or on our [forum](https://forum.adguard.com/index.php).

**Comment by cuedutest** [comment]
I'll try to explain in detail 

https://promos.www.adjarabet.com/mysafe/?lang=ka&device=mobile& -  when using adguarddns this website is not accessable.  giving you the image 

![image](https://user-images.githubusercontent.com/71916099/227019995-0da19c5c-9b93-4c77-90c7-3ee2e338a75c.png)

**Comment by cuedutest** [comment]
ssl is fully valid
