### ISSUE TITLE
Not receiving Adguard private DNS Stats report to email

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardDNS#568]
### Platform

Other

### Protocol

DNS-over-QUIC

### Do you use AdGuard app?

Yes I am

### Issue Details

Na

### Actual Behavior

na

### Additional Information

This is the second time I'm reporting this problem of not receiving regular stats reports for Adguard Private DNS in my email I should be receiving it weekly and then monthly. when this feature came out I was receiving it but haven't been since the new year began. so can you look into this problem again?

**Comment by Chinaski1** [comment]
Please contact me at k.gretskyi@adguard.com
In order to check your issue I need to know your email address

**Comment by Batman2814** [comment]
So I received last weeks weekly report this monday for last weeks Stats once I sent my email to you so if we can keep this open for a while while we can see if I receive this monthly Stats report for March and maybe 2 in the beginning of April then if so we can close this issue.
