### ISSUE TITLE
adguard-dns-ipv6 and adguard-dns-family-ipv6 currently unreachable

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardDNS#57]
@jedisct1 commented on [Mon Oct 07 2019](https://github.com/AdguardTeam/dnsproxy/issues/66)

Hi!

Looks like Adguard over DNSCrypt is currently not reachable over IPv6 (but totally fine over IPv4).

Can you take a look?

Thanks!

**Comment by ameshkov** [comment]
@jedisct1 thanks, we're looking into it!

**Comment by ameshkov** [comment]
@jedisct1 actually, I cannot reproduce the issue.

Here's what I am trying:
```
$ ./dnslookup pornhub.com '[2a00:5a60::bad2:ff]:5443' 2.dnscrypt.family.ns2.adguard.com 8C21:17A9:EBC1:57D6:FB64:056F:0ADB:C11C:5D83:6734:73C4:6E25:8D9B:2F57:D4EE:351F
```

The same using a DNS stamp:
```
./dnslookup example.org sdns://AQcAAAAAAAAAGVsyYTAwOjVhNjA6OmJhZDI6ZmZdOjU0NDMgjCEXqevBV9b7ZAVvCtvBHF2DZzRzxG4ljZsvV9TuNR8hMi5kbnNjcnlwdC5mYW1pbHkubnMyLmFkZ3VhcmQuY29t
```

Using the [dnslookup tool](https://github.com/ameshkov/dnslookup).

**Comment by jedisct1** [comment]
```sh
drill txt -p 5443 2.dnscrypt.default.ns2.adguard.com @2a00:5a60::ad2:0ff
```

doesn't return anything for me. Same for the other address.

It may just be an IPv6 local routing issue, then. Not sure if these addresses are supposed to respond to `ping` as well, but they don't from my endpoint.

**Comment by jedisct1** [comment]
PS: that `dnslookup` tool is super cool. How come it's not in every single operating system/distro already?

**Comment by jedisct1** [comment]
https://atlas.ripe.net/measurements/23033563/#!probes

Looks like routing issues, indeed.

**Comment by jedisct1** [comment]
That network apparently still has IPv6 reachability issues today: https://atlas.ripe.net/measurements/23048282/#!probes ¯\_(ツ)_/¯

**Comment by ameshkov** [comment]
IPv6 is the future, they were saying

**Comment by jedisct1** [comment]
A more realistic future is that the price of IPv4 blocks will go through the roof.

Invest in IPv4 blocks, not in cryptocurrencies :)
