### ISSUE TITLE
Translation updates

### ISSUE THREAD

**Issue by olavinto** [AdguardTeam/AdGuardDNS#570]
It would be nice to see more languages, in my case Finnish, which has been completed for a long time and it's a bit funny how the service sends notification emails in Finnish but everything in the dashboard is in English. Even the public DNS configuration page is in still English while the main site is otherwise in Finnish.

**Comment by ameshkov** [comment]
Our bad, we'll add new languages in v2.2

**Comment by Chinaski1** [comment]
Updated at [v2.2](https://adguard-dns.io/en/versions.html)

**Comment by olavinto** [comment]
@Chinaski1 Otherwise everything is ok but the Public DNS page (https://adguard-dns.io/fi/public-dns.html) is still in English. Could you check what's going on there also?
