### ISSUE TITLE
Adguard dns private, statistics are not working after resetting it

### ISSUE THREAD

**Issue by ijuliank** [AdguardTeam/AdGuardDNS#571]
### Platform

Other

### Protocol

Regular

### Do you use AdGuard app?

Yes I am

### Your configuration

Not required 

### Issue Details

Title

### Actual Behavior

Graphics isn’t updating after clicking clear statistics 
![IMG_0173](https://user-images.githubusercontent.com/64658680/228945685-2c1b84aa-5514-4d03-889b-99d91a7faaf2.jpeg)

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by jslawler** [comment]
Is this the same as #228?

**Comment by ijuliank** [comment]
> Is this the same as #228?

Not exactly i think, the data is still not from the missing hour,

**Comment by Chinaski1** [comment]
The statistics section is working, just at the moment there are delays with the receipt of information, we are working to fix this problem
