### ISSUE TITLE
Adguard Private DNS doesn't configure right when setting up on iOS

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardDNS#572]
### Platform

iOS

### Protocol

Regular

### Do you use AdGuard app?

No I don't

### Your configuration

When I was adding Adguard Private DNS to a family phone by setting up DNS on iOS iPhone without using the Adguard Ad blocker app and just installing the DNS by using Use a configuration profile it said I was connected when using the Adguard services test page. Still, it showed a red dot next to settings for that device with no DNS history or information for the categories. Is this a bug that needs to be fixed? 

### Issue Details

setting up Adguard DNS on iOS iPhone using "Use a configuration Profile"

### Expected Behavior

should show complete history up to the point it was configured by showing live Query logs of the iPhone filtering through Adguard Private DNS.

### Actual Behavior

shows a red dot next to settings for that device and no live history of DNS which there should be because, on the Adguard Services test page, it was saying Adguard private DNS was active on the iOS iPhone

### Additional Information

Should be fixed in the next update

**Comment by Batman2814** [comment]
Looks like it's filtering now. There was about a 3-4 hour delay, don't know why. But if you Adguard can take a look at this to make sure it's not a bug and if everything seems fine, then can you close this issue.

**Comment by ijuliank** [comment]
https://github.com/AdguardTeam/AdGuardDNS/issues/571 seems like the same issue

**Comment by Chinaski1** [comment]
All of these problems are related to сhanges on the side of AdGuard DNS, we are currently working on fixing them, I will let you know when they are ready under this [task](https://github.com/AdguardTeam/AdGuardDNS/issues/573).}

Thank you for the report.
