### ISSUE TITLE
Over 10 minute delay in queries showing up in log

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardDNS#573]
When trying to fault find an issue I was trying to analyse the query log to determine what needed unblocking.
Unfortunately there seems to be over a 10min delay on the data being passed to to the AGDNS query log making it near on impossible to use.

Usually the query log is only a few seconds behind in showing new queries.

This is possibly related to the other issues raised recently with configuring devices and clearing logs.

![image](https://user-images.githubusercontent.com/95468948/229115484-1525373a-7b6c-4604-8637-3c0de1cbef6c.png)

**Comment by Chinaski1** [comment]
Hi there!
There are some issue at the moment, we are in the process of fixing.

**Comment by Chinaski1** [comment]
@Batman2814, @jslawler, @ijuliank

Could you check and confirm that the log is being written in real time?

**Comment by ijuliank** [comment]
> @Batman2814, @jslawler, @ijuliank
> 
> Could you check and confirm that the log is being written in real time?

thanks for checking out, nope its not written in realtime

**Comment by Batman2814** [comment]
you want it set to the" Last hour" for information on stats. right?

**Comment by Batman2814** [comment]
when it is set to the last hour it is showing a graph by minute by minute.

**Comment by jslawler** [comment]
The query log seems to be coming through between a few seconds and a few minutes of being real-time.

**Comment by Batman2814** [comment]
![Screenshot_20230331_153133_Samsung Internet](https://user-images.githubusercontent.com/96619913/229224056-4f449b2b-f1b5-4b09-90ae-b12b40104db0.jpg)
There's is hours of delay

**Comment by Batman2814** [comment]
Not showing filtering in query log. Only shows from this morning which was hours ago

**Comment by jslawler** [comment]
> The query log seems to be coming through between a few seconds and a few minutes of being real-time.

Update: Currently approximately 6 seconds delay.

**Comment by ameshkov** [comment]
Generally, the logs are not real-time and the delay may depend on the connectivity from the DNS server to the main database server.

On one hand, it may lead to delays like you're experiencing sometimes. On the other hand, it guarantees that the log is never lost and at some point it will be delivered.

**Comment by ijuliank** [comment]
> Generally, the logs are not real-time and the delay may depend on the connectivity from the DNS server to the main database server.
> 
> On one hand, it may lead to delays like you're experiencing sometimes. On the other hand, it guarantees that the log is never lost and at some point it will be delivered.

![image](https://user-images.githubusercontent.com/64658680/229849138-0a4c62b4-1dae-4506-85c1-24751cc5a601.png)
then this doesnt make sense also, if its not realtime. because its updating is behind

**Comment by ijuliank** [comment]
@jslawler please reopen this issue

**Comment by ameshkov** [comment]
Real-time updates means that the query log will be updated automatically and always show the latest we got.

I don't think we need to reopened this issue. It does not mean we are not working on optimizing the delivery times, it's just this is not a bug and does not need to be an issue on GH.

**Comment by jslawler** [comment]
@ameshkov it seems the query log has become entirely unreliable when trying to fault remote issues.

The query log at this moment has been waiting over 30 minutes for new data.
I have little doubt that they will come through at some stage, but by then it will be rather difficult to work out the issues that require close to real-time diagnosing. 

I'm not sure if there's been a change within the last week or two with how query logs are passed on but they definitely aren't as they have been. Maybe this is the new norm?

![image](https://user-images.githubusercontent.com/95468948/230090846-42ba3b21-6cd8-452c-98d7-99b5e7c2c77e.jpeg)
![image](https://user-images.githubusercontent.com/95468948/230090858-52ec7f99-32d1-4bbc-97f5-c8020c7290e9.png)
