### ISSUE TITLE
"Device not connected" indicator dot pushes row out of alignment with column

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardDNS#575]
### Browser

Safari - but will happen with any full-size desktop browser. Issue does not seem to happen on the smaller displays I tested with.

### Issue Details

1. Create device on AdGuard DNS
2. Leave device unconnected until red indicator dot appears

### Expected Behavior

Column text stays in alignment when red indicator dot appears.
<img width="176" alt="Screenshot 2023-04-01 at 11 25 43" src="https://user-images.githubusercontent.com/95468948/229259108-88f33245-4d66-40d1-89c0-c29c1ce366cf.png">

### Actual Behavior

Red indicator dot pushes row alignment further to the left, out of alignment with the column.
<img width="174" alt="Screenshot 2023-04-01 at 11 18 57" src="https://user-images.githubusercontent.com/95468948/229259116-9a77d023-c1e0-47ee-8f70-1ecd2be14538.png">

**Comment by Chinaski1** [comment]
Internal ID: AGDNS-1419

**Comment by Chinaski1** [comment]
Fixed at [v2.2.1](https://adguard-dns.io/en/versions.html#2.2.1)
