### ISSUE TITLE
Slashes are not preserved in comments (URLs look weird)

### ISSUE THREAD

**Issue by contribucious** [AdguardTeam/AdGuardDNS#576]
### Platform

Windows

### Protocol

DNS-over-HTTPS

### Do you use AdGuard app?

Yes I am

### Issue Details

Hi. :wave: &nbsp;|&nbsp; Steps to reproduce:
1. Open a `User rules editor` from [your dashboard](https://adguard-dns.io/dashboard/).
2. Add the comment line `! Source: https://example.org/test` ([visual result](https://user-images.githubusercontent.com/4764956/229323428-72a3618d-9772-4561-9103-c662ac6d3573.png)).

### Expected Behavior

In the `User rules` listing, slashes are preserved in comments, especially for URLs (should be ideally like the screenshot n°1 below).

### Actual Behavior

In the `User rules` listing, slashes are not preserved in comments (see the current situation in the screenshot n°2 and 3).

> __Note:__ The content itself is not altered though (i.e. when you click on `Open editor` again, everything is preserved correctly).

### Screenshots

<details>
<summary><strong>View screenshot n°1</strong> (ideal situation) …</summary>

&nbsp;
![Screenshot n°1 — Ideal situation](https://user-images.githubusercontent.com/4764956/229322904-d5ff3c7b-23f6-47b4-b121-58cdc93f896a.png)
</details>
&nbsp;

<details>
<summary><strong>View screenshot n°2</strong> (current situation) …</summary>

&nbsp;
![Screenshot n°2 — Current situation](https://user-images.githubusercontent.com/4764956/229322896-f7fdb505-eafa-4443-b8ec-37db3e42cd89.png)
</details>
&nbsp;

<details>
<summary><strong>View screenshot n°3</strong> (current situation — tooltip) …</summary>

&nbsp;
![Screenshot n°3 — Current situation (tooltip)](https://user-images.githubusercontent.com/4764956/229323049-f5f1ed7d-259a-451d-ab73-5d968986ea9d.png)
</details>

### Additional Information

I note that backslashes do not have this problem ([screenshot](https://user-images.githubusercontent.com/4764956/229323818-78e1cff2-b911-410c-9083-7035efa6306b.png)).

**Comment by Chinaski1** [comment]
Internal ID: AGDNS-1428

**Comment by Chinaski1** [comment]
Fixed at [v2.2](https://adguard-dns.io/en/versions.html)

**Comment by contribucious** [comment]
Works indeed as expected now.

Thank you! 👍
