### ISSUE TITLE
www.tnpds.gov.in is not resolved with AdGuard DNS

### ISSUE THREAD

**Issue by alexx7311** [AdguardTeam/AdGuardDNS#577]
### Platform

Android

### Protocol

Regular

### Do you use AdGuard app?

No I don't

### Issue Details

With AdGuard DNS (Public or Private) enabled, this site is not resolved on Chrome, but if you disable it, it starts to open.

### Actual Behavior

Error message: This site can’t be reached www.tnpds.gov.in’s DNS address could not be found. Diagnosing the problem.
DNS_PROBE_POSSIBLE

### Screenshots

<details>
<summary>Screenshot</summary>

![Screenshot](https://user-images.githubusercontent.com/114913601/229491712-9f9c1678-de12-4019-bf18-02b0d3d5cfce.jpg)

</details>

<details>
<summary>Screenshot2</summary>

![Screenshot](https://user-images.githubusercontent.com/114913601/229593201-07ae9d93-a4e2-4b05-b74e-09b217d8c19d.jpg)

</details>

### Additional Information

This is an Indian government website.

**Comment by cryptopatik22** [comment]
![229491712-9f9c1678-de12-4019-bf18-02b0d3d5cfce](https://user-images.githubusercontent.com/104494839/229494509-34434240-bd5b-43e2-8c9b-b05faa296b5b.jpg)

**Comment by Chinaski1** [comment]
Maybe geo-blocking is triggered
User can try another protocol to connect (DoH, QUIC, TLS)

**Comment by ameshkov** [comment]
Can't be resolved with Google as well:
```
dnslookup www.tnpds.gov.in tls://dns.google     
dnslookup 1.9.1
dnslookup result (elapsed 5.556233476s):
;; opcode: QUERY, status: SERVFAIL, id: 49823
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;www.tnpds.gov.in.	IN	 A
```

Might be a strange blocking on the name server side.
