### ISSUE TITLE
3 hour period with no queries logged

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardDNS#579]
Between 04:00-06:00 5 Apr 2023 (AEST GMT+10), no queries have been logged by AGDNS.

With 9 devices connected, and all of those being used for those 3 hours at least once, it's not possible there were no queries received via AGDNS.

All devices should be connected to the Sydney, Australia server.

https://user-images.githubusercontent.com/95468948/230070717-0462ec2a-1ed6-4aed-adf0-a269d08f5025.MOV

It seems a similar thing happened on the 29 Mar 2023 also.

https://user-images.githubusercontent.com/95468948/230084803-ba472cdc-8e97-4183-b455-d98f4e337813.MOV

Again on the 6 Mar 2023
![image](https://user-images.githubusercontent.com/95468948/230085759-cdeb8fd0-c429-4d9e-a911-f147d8cd4c06.jpeg)

Possibly again on the 5 Jan 2023, and a few other dates there in between. When set to 90 days it's too hard to get a granular perspective of those periods, but there's definitely outliers where large chunks of logs don't seem to have come through.
![image](https://user-images.githubusercontent.com/95468948/230086454-d22cdc82-d2fa-4112-8072-4e6053d525fe.jpeg)

Although not a concern personally as to whether I have these logs on hand, only using them for short term use, there does seem to be an issue worth discussing there.

**Comment by ijuliank** [comment]
> Should be solved by now (took too much time though, we'll look into speeding the re-sync process up a lot).

its not fixed

**Comment by ameshkov** [comment]
We finally switched from Logstash to Vector for logs delivery, the situation with the delay should be much more stable now.
