### ISSUE TITLE
Add the ability to block websites by categories

### ISSUE THREAD

**Issue by alexx7311** [AdguardTeam/AdGuardDNS#582]
### Issue Details

A feature is needed that allows you to block certain categories, such as "Gambling", "Dating", "Porn", "Social Network".

### Proposed solution

This can be implemented the way the Annoyances blocking feature is implemented in the new AdGuard app for Android.
<details>
<summary>Screenshot</summary>

![Screenshot](https://user-images.githubusercontent.com/114913601/232209045-b53b55d3-dc8d-4511-976b-099dac1c54c7.png)

</details>

**Comment by Chinaski1** [comment]
The thing is that the peculiarities of AdGuard DNS blocking do not allow you to add these categories to the lists of filters or blocked services.

**Comment by Chinaski1** [comment]
But such categories as porn and gambling can be blocked by parental control feature
