### ISSUE TITLE
[https://github.com/AdguardTeam/KnowledgeBase/pull/181#issue-1678000041](https://github.com/AdguardTeam/KnowledgeBase/pull/181#issue-1678000041)

### ISSUE THREAD

**Issue by rwgan** [AdguardTeam/AdGuardDNS#583]
[https://github.com/AdguardTeam/KnowledgeBase/pull/181#issue-1678000041](https://github.com/AdguardTeam/KnowledgeBase/pull/181#issue-1678000041)

**Comment by rwgan** [comment]
> [https://github.com/AdguardTeam/KnowledgeBase/pull/181#issue-1678000041](https://github.com/AdguardTeam/KnowledgeBase/pull/181#issue-1678000041)

![605523D6-4184-434E-BB69-6A6361C038BA](https://user-images.githubusercontent.com/39743925/233571432-33e9cf46-f2aa-4c39-80fd-463d5097b66e.png)

**Comment by Chinaski1** [comment]
Could you be more specific about what you're trying to do?
