### ISSUE TITLE
On Mobile browser scrolling down in Query Log doesn't work or show pages numbers.

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardDNS#587]
### Platform

Other

### Protocol

Regular

### Do you use AdGuard app?

Yes I am

### Your configuration

When on my mobile phone using my browser, when I go into Query log for my devices, I'm not able to keep on scrolling down on mobile browser. Also, it doesn't show you pages at the bottom of the query log on mobile like it does on the Galaxy tablet or iPad. For example, on the tablet, when in Query log and you scroll down, it shows pages 1,2,3,4,5, then on the other side, you can choose how many requests you want per page. Where it will not show it on mobile even though it's on tablet or even showing on laptop. I attached a screen recording of it.

### Issue Details

Na

### Actual Behavior

Scrolling will not work. Just stays in the same spot.

[]()https://user-images.githubusercontent.com/96619913/234732915-c6679b99-421f-4c11-b7f3-077a3d02a4df.mp4

_No response_

**Comment by Chinaski1** [comment]
The mobile version of adguard DNS has no page separation. To see the rest of the filter log, wait a moment and scroll the screen again. Apparently the information is being loaded at the moment

**Comment by Chinaski1** [comment]
Not reproduced on my side.
Maybe you have a slow Internet connection or your device does not have enough resources to download all the data
Video: https://uploads.adguard.org/RPReplay_Final1682594131.MP4.mp4

If anyone else encounters this issue, I will reopen the task.
