### ISSUE TITLE
Adguard DNS not working 

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardDNS#588]
### Platform

Other

### Protocol

Regular

### Do you use AdGuard app?

Yes I am

### Your configuration

I'm getting ads on my TV, which should be blocked also when I'm in Adguard DNS the green checkmark isn't there. On adguard services check page says I'm using my private adguard dns.

### Issue Details

Not working

### Actual Behavior

Seeing ads

**Comment by ameshkov** [comment]
The root cause of the issue has been found, we're rolling a fix urgently.

Sorry for the inconvenience.
