### ISSUE TITLE
developer.amazon.com signin Broken

### ISSUE THREAD

**Issue by georgeduckett** [AdguardTeam/AdGuardDNS#59]
Going to the developer.amazon.com page and clicking sign in brings you to a page (`https://developer.amazon.com/settings/console/registration/nextstep` to input username/password, however clicking Sign-In just seems to reload the page, rather than logging in properly.

There's a request to `uedata` that's returning a 204, as well as two requests to `OE/` that both also return 204s.

**Comment by Alex-302** [comment]
Hi
I can't reproduce this issue. Which DNS address are you using?

**Comment by georgeduckett** [comment]
Using the standard one (not family). Not sure what the issue was though as it's working now. I guess it wasn't something related to AdGuard, sorry about that.

**Comment by Alex-302** [comment]
Ok)
