### ISSUE TITLE
No requests observed 2 hours on the dashboard

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardDNS#591]
### Platform

macOS

### Protocol

DNS-over-HTTPS

### Do you use AdGuard app?

Yes I am

### Your configuration

DNS filter: AdGuard DNS filter
Devices: 8
Requests to date: 2M
Requests in 24h: 66k

### Traceroute to AdGuard DNS

traceroute to 94.140.14.14 (94.140.14.14), 64 hops max, 52 byte packets
 1  192.168.178.1 (192.168.178.1)  8.056 ms  1.354 ms  1.605 ms
 2  100.127.0.102 (100.127.0.102)  8.135 ms  7.859 ms  8.251 ms
 3  core02.bne01s.launtel.net.au (203.12.3.241)  8.779 ms  8.456 ms  8.648 ms
 4  et32.core01.bne01.launtel.net.au (103.214.222.105)  8.750 ms  8.248 ms  9.154 ms
 5  po272.core02.syd01.launtel.net.au (103.214.222.100)  19.795 ms  20.298 ms  19.831 ms
 6  po999.core01.syd01.launtel.net.au (103.214.222.84)  22.808 ms  23.950 ms  22.767 ms
 7  as60068.syd.edgeix.net.au (202.77.88.64)  19.963 ms  20.905 ms  20.216 ms
 8  dns.adguard.com (94.140.14.14)  22.958 ms  23.807 ms  23.066 ms

### Issue Details

For 10:00 and 11:00 27 April, no requests are displayed on the AdGuard DNS dashboard. Either side of those 2 hours, I'm seeing on average 2000 requests an hour.

### Expected Behavior

All requests are displayed.

### Actual Behavior

Bulk requests are missing for certain time periods.

### Screenshots

<details><summary>Screenshot 1:</summary>

<img width="1161" alt="Screenshot 2023-04-28 at 19 23 46" src="https://user-images.githubusercontent.com/95468948/235109759-e9fedb07-3ead-41f9-b0ce-e47adfb48c02.png">

</details>

**Comment by Chinaski1** [comment]
At this time there were problems with the AdGuard DNS service. Now it is working normally.
Logs will probably appear in the log in the near future.

**Comment by jslawler** [comment]
> At this time there were problems with the AdGuard DNS service. Now it is working normally.
> 
> Logs will probably appear in the query log in the near future.

Should I change the title to reflect improving the reliability of the query logs then and have it reopened?

Having missing logs and being told that it should turn up eventually doesn't instil a lot of faith that it will ever be more reliable.

**Comment by D13410N3** [comment]
@jslawler Hello. It's already fixed and now query logs are processed with a more reliable way. What about a missing interval - we're doing our best to back-log it
