### ISSUE TITLE
Rule number strings of filters in the Blocklist cannot be localized

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdGuardDNS#595]
### Platform

Windows

### Protocol

Regular

### Do you use AdGuard app?

Yes I am

### Issue Details

Steps to reproduce:
1. Go to Blocklist.

### Expected Behavior

Please let us to localize this rule number strings.

### Actual Behavior

We can't localize this rule strings (ex: English: 20K rule - Turkish: 20Bin kural). No string related to these strings is available at Crowdin.

### Screenshots

<details><summary>Screenshot 1:</summary>

![image](https://user-images.githubusercontent.com/35523759/235555985-3adb43b9-21ec-473b-9aec-bb3f04ca870f.png)
</details>

**Comment by Chinaski1** [comment]
Hello there!

You are most likely looking for the lines: `dashboard.tr.resx` `block_list_description_dns_rules_multiple`

**Comment by gork7777** [comment]
@Chinaski1 The string that is in these rule numbers (the "K" word) is missing at Crowdin. That's why I opened this issue.

**Comment by Chinaski1** [comment]
For sure its `block_list_description_dns_rules_multiple` and `block_list_description_dns_rules`.
