### ISSUE TITLE
Native Tracking Protection

### ISSUE THREAD

**Issue by dspdhckr** [AdguardTeam/AdGuardDNS#597]
### Issue Details

There are many developers who are creating their native tracking systems to better track their user's usage patterns. It is not possible to block them though classic filters but a dedicated system needs to be developed in a way to fend off our users from their tracking behavior

There are so many chinese phone vendors who effectively works on this tactic to know more about their users.

### Proposed solution

NextDNS has their own Native Tracking protection available for their users which we can implement where instead of going through technicality, user can only select manufacturers from the list for which he wants to block tracking. Please see the screenshot below from NextDNS dashboard. Considering NextDNS has same pricing model as AdGuard DNS, we would want to see this on our beloved AdGuard DNS 2.0 please.

<img width="1126" alt="Screenshot 2023-05-07 at 11 50 08" src="https://user-images.githubusercontent.com/132819104/236673341-b4020a73-94a0-4bdc-bce0-1de8247c4a5b.png">

### Alternative solution

As of now, blocking Private Relay is not working at all on any AdGuard DNS level. We have to block those two domains from Apple Technical Support to block Private Relay working on all Apple products. I think we can start from there first.

**Comment by ameshkov** [comment]
Hm, the thing is that this option just enables small blocklists and nothing more.

We'll need to evaluate whether it's actually required, I tend to believe that all these trackers are already blocked by AdGuard DNS filter.

**Comment by dspdhckr** [comment]
Hey, this ask is to make AdGuard DNS even more customisable. Let’s say I want to block tracking from certain companies or device manufacturers; then, we can do it with a single click instead of loading the whole list. If I want only to block tracking from the above trackers but let other DNS requests be appropriately resolved, I can achieve it without breaking the internet for other users.
