### ISSUE TITLE
DOQ Routing Issue for Vodafone Ireland

### ISSUE THREAD

**Issue by dspdhckr** [AdguardTeam/AdGuardDNS#598]
### Platform

Router

### Protocol

DNS-over-QUIC

### Do you use AdGuard app?

Yes I am

### Your configuration

Hi Team,
I have set up my AdGuard Home server on an OpenWRT router using DOQ. My ISP is Vodafone Ireland, and whenever I use a WiFi connection at home, all my queries are routed through AdGuard's Istanbul server instead of the London Server, which adds latency to my DNS query resolution. I am also using the DOQ server on my iPhone, and when my iPhone is on WiFi, the latency increases to 3.1 seconds. Not milli seconds but more than three seconds. This isn't very pleasant, considering I have gigabit internet, and my queries are resolved slower. By any chance, if you could fix this issue would significantly improve my overall browsing experience. Also, when I use my cellular network on my iPhone, I correctly connect to the London server. My cellular network provider is 48 Networks, a child company of Three. I have set up a DOQ server on my Mac, too and recently, I used my friend's wifi network provided by Sky Broadband with 100 Mbps internet; my queries were correctly routed through the London server. Can you guys do anything from your end to resolve it or manually redirect Vodafone Irish Customer queries to the London server and reduce overall response time? Because 5 seconds are too much and there are so many connections, most of the time drops because of the same. 

Please see below screenshot of DNS Leak Test result to further prove my point,

<img width="976" alt="Screenshot 2023-05-07 at 17 27 18" src="https://user-images.githubusercontent.com/132819104/236690041-eea8dfb9-7b0f-4793-b04a-1ce585d2326f.png">

![IMG_3436](https://user-images.githubusercontent.com/132819104/236690263-cba3ccf8-1cab-47cd-b57e-c3a0a83bca5d.jpeg)

### Traceroute to AdGuard DNS

traceroute to 94.140.14.14 (94.140.14.14), 64 hops max, 52 byte packets
 1  192.168.0.1 (192.168.0.1)  11.475 ms  2.963 ms  3.234 ms
 2  10.10.10.1 (10.10.10.1)  5.054 ms  3.691 ms  3.674 ms
 3  10.8.18.1 (10.8.18.1)  9.138 ms  10.574 ms  9.411 ms
 4  89.19.85.140 (89.19.85.140)  10.633 ms  9.561 ms
    89.19.85.144 (89.19.85.144)  10.417 ms
 5  ae5-111-xcr1.dcw.cw.net (195.2.21.245)  13.893 ms  12.107 ms  10.387 ms
 6  ae25-xcr1.ltw.cw.net (195.2.3.129)  67.479 ms  63.032 ms
    ae18-xcr1.hex.cw.net (195.2.8.94)  69.145 ms
 7  ae8-tcr1.pat.cw.net (195.2.9.93)  71.994 ms  69.525 ms  85.224 ms
 8  ae29-xcr1.mlu.cw.net (195.2.24.229)  76.328 ms  70.201 ms  72.844 ms
 9  ae23.0-xcr1.sof.cw.net (195.2.16.2)  58.543 ms
    ae9-xcr1.ise.cw.net (195.2.22.69)  65.052 ms  63.148 ms
10  cust-gw-ae3-17-xcr1.ise.cw.net (195.2.26.254)  68.399 ms  63.725 ms
    ae1-xcr1.ise.cw.net (195.2.18.209)  66.302 ms
11  213.194.115.38 (213.194.115.38)  68.850 ms  67.452 ms  113.007 ms
12  213.194.115.38 (213.194.115.38)  70.491 ms  65.722 ms *
13  * * *
14  185.137.215.90 (185.137.215.90)  73.079 ms  67.799 ms *
15  dns.adguard.com (94.140.14.14)  69.942 ms  62.832 ms  64.254 ms

### Issue Details

I am not sure how this can be reproduced on your end as this is particularly affecting Vodafone Ireland users.

### Expected Behavior

My AdGuard DNS DOQ should ideally connect to the Dublin server, which is not in place but closer to the London server. 

### Actual Behavior

My AdGuard DNS DOQ set on the OpenWRT router connects to the Istanbul server more than the London one.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by D13410N3** [comment]
Hello!
Issue should be fixed now.
Can you please show content of https://dns.adguard.com/info.txt ?

**Comment by dspdhckr** [comment]
Hi there no luck yet. Please see the screenshot below. 
![IMG_5311](https://github.com/AdguardTeam/AdGuardDNS/assets/132819104/ea8160fe-4820-4f0f-9510-d67df09e2913)

**Comment by D13410N3** [comment]
Even worse. That's strange, because yesterday I've got rid of all Vodafone routes to Istanbul. I need some more time for researching.
