### ISSUE TITLE
Create a new server (and a new DNS list) to block only ads

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/AdGuardDNS#599]
### Issue Details

All the details here: https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1335

### Proposed solution

Create a new DNS server to block only ads. Obviously DNS filter too needs to be splitted.

### Alternative solution

Change non-filtering DNS to Adblock-only? If it's not too popular.

**Comment by Chinaski1** [comment]
Hello
In the near future definitely do not plan to add this type of server.
