### ISSUE TITLE
4pda.ru - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardDNS#6]
![image](https://cloud.githubusercontent.com/assets/15856304/17165936/95badff8-53dc-11e6-986a-bd0c3b0cbb1c.png)

<details>
![image](https://cloud.githubusercontent.com/assets/15856304/17165957/aebdcbe6-53dc-11e6-9cff-d0178f581509.png)

</details>

DNS прописаны в
роутере (чистку кеша браузера и dns делал)
952965

**Comment by Alex-302** [comment]
У них реклама на самом сайте хранится, даже с Адгардом не очень просто заблокировать.
