### ISSUE TITLE
Adguard DNScrypt offline

### ISSUE THREAD

**Issue by wmrichard** [AdguardTeam/AdguardDNS#60]
It looks like Adguard Dnscrypt (176.103.130.130:5443) is down at the moment. I have updated the public dns file. I cannot connect to the server.

**Comment by ameshkov** [comment]
Weird, monitoring is silent. We'll check it asap

**Comment by ameshkov** [comment]
Ah, I found the issue.

The thing is that current resolvers list is out of date, dnscrypt guys haven't yet merged the new data into it.

Here is the current csv:
https://gist.github.com/ameshkov/8cc0da559229f7e0dccd4fe2e1e4f355
