### ISSUE TITLE
Mobile game Blue Archive suddenly stopped working with AdGuard DNS

### ISSUE THREAD

**Issue by MichalPetryka** [AdguardTeam/AdGuardDNS#601]
### Platform

Android

### Protocol

Regular

### Do you use AdGuard app?

Yes I am (the issue happens also without it)

### Your configuration

Poco F3 with Android 13

### Traceroute to AdGuard DNS

n/a

### Issue Details

Enable Adguard DNS in any way, even without the app. I can reproduce the issue by disabling the app and only using system settings.
Try to launch the game.
The game will usually crash during the loading screen.
If not, it will crash within a few clicks in the menu.

### Expected Behavior

Game works normally.

### Actual Behavior

Game crashes constantly in 4 ways:
- the app just closes
- system says "The app is not responding"
- system says "The app is crashing frequently"
- system says "Illegal instruction detected (106/0)"
- system says "Illegal instruction detected (110/1)"

### Screenshots

Info from known issue list:
![image](https://github.com/AdguardTeam/AdGuardDNS/assets/35800402/18f5da08-c3f8-41da-9b93-07693c4f1f0e)
Example crash on loading screen:
![image](https://cdn.discordapp.com/attachments/791769456085827607/1108772049838674010/Screenshot_2023-05-18-17-03-52-067_com.nexon.bluearchive.jpg)
Blocked requests from the log (seems like it's requests to Nexon and Unity Cloud servers):
![image](https://github.com/AdguardTeam/AdGuardDNS/assets/35800402/03ce395b-726d-492b-a707-e17859895b08)
![image](https://github.com/AdguardTeam/AdGuardDNS/assets/35800402/7bf16cb1-4606-4e04-881e-6b1fc3179c7c)
![image](https://github.com/AdguardTeam/AdGuardDNS/assets/35800402/a51dc698-8c3c-4a01-aeb8-df31baaa2a06)
![image](https://github.com/AdguardTeam/AdGuardDNS/assets/35800402/2a23ad8b-b0e7-405e-8642-c5e76cdef7ce)

### Additional Information

The issues started seemingly today. Seemingly AdGuard started blocking telemetry logging calls made by the game.
I've been able to play the game fine for the past few years, I still could do it about 24h ago.
All players that use AdGuard DNS seem to be experiencing this issue since support discord is full of people reporting it.
[Issue announcement from the publisher.](https://forum.nexon.com/bluearchive-en/board_view?thread=2130378)

**Comment by piquark6046** [comment]
@MichalPetryka Can you send more details with screenshots and steps to reproduce?

**Comment by piquark6046** [comment]
Can adding the following rules into your DNS user rules resolve your issue:
```adblock
@@||log.ngsm.nexon.com^
@@||log.nexon.io^
```

I think that the game works normally if the above rules are applied and AdGuard Tracking Protection filter including [the related rules](https://github.com/AdguardTeam/AdguardFilters/commit/0053456cb05d8b6816ad512789dffe21c2eb94aa) is enabled.

**Comment by MichalPetryka** [comment]
I can confirm that it works after adding those (and switching to AdGuard Unfiltered servers so that the server itself doesn't return 0.0.0.0) makes the game work again.
