### ISSUE TITLE
Reduce blank space in sidebar so all buttons are visible

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardDNS#603]
The blank space in the sidebar pushes the support and account settings off the page.

All buttons should be able to comfortably fit on the same page with ample blank space still remaining, without having to scroll.

![image](https://github.com/AdguardTeam/AdGuardDNS/assets/95468948/7cd474ab-7000-45ae-9ab6-bc1557b4a2ce)

https://github.com/AdguardTeam/AdGuardDNS/assets/95468948/c5ed5ee4-5e7d-4ab5-b4a8-d7d2db626634

**Comment by jslawler** [comment]
I noticed it had changed appearance today.

I'm not sure if this is the final appearance, but I would have thought the bottom 3 menus would have appeared at the bottom of the screen rather than halfway up.

![image](https://github.com/AdguardTeam/AdGuardDNS/assets/95468948/a45561ad-ec6c-44dd-a0be-38b8abc6d857)

**Comment by Chinaski1** [comment]
This change was made in v2.2.1 and this is the final view.
