### ISSUE TITLE
AdGuard DNS service DOWN

### ISSUE THREAD

**Issue by Chamiu** [AdguardTeam/AdGuardDNS#604]
AdGuard DNS down Japan and South Korea from 12:38 (JST).
Plase announce and recovery.

**Comment by ameshkov** [comment]
We're investigating the issue. There was indeed a downtime in Japan which then resolved by itself about an hour later.

Looks like a networking issues in the Data Center, but it's unclear to us why the traffic was not rerouted automatically to a different data center.

Once the investigation is finished we'll post the details to https://status.adguard.com/
