### ISSUE TITLE
Is there any way to select the unicast IP?

### ISSUE THREAD

**Issue by trmdi** [AdguardTeam/AdGuardDNS#605]
### Issue Details

In Ho Chi Minh City, Vietnam, users of Viettel ISP (one of the major ISPs in Vietnam) are being routed to the EU badly, which is very far away, even though the best destination for the area should be Singapore. This is causing very high latency when querying to Adguard DNS servers.

![1684768338455](https://github.com/AdguardTeam/AdGuardDNS/assets/11857205/97afdbe2-b5b0-4064-9d0d-532d32b9b9b0)

Is there any way to use the unicast IP in Singapore directly?

**Comment by D13410N3** [comment]
Can you please send actual traceroute results?

**Comment by D13410N3** [comment]
What `tracert 94.140.14.14` shows now?

**Comment by trmdi** [comment]
Thank you for explaining it. I will try to contact my ISP to fix it. :)
