### ISSUE TITLE
macOS Ventura ignores Adguard DNS configuration profile

### ISSUE THREAD

**Issue by jeremybickerstaffe** [AdguardTeam/AdGuardDNS#606]
### Platform

macOS

### Protocol

Regular

### Do you use AdGuard app?

No I don't

### Your configuration

14" Macbook Pro M1
macOS Ventura 13.3.1 (a)
No VPN running
Using the Adguard DNS configuration profile downloaded from my Adguard DSN account. Uses whichever protocol is specified in the profile. This profile works as expected for my iPhone and my iPad.

### Traceroute to AdGuard DNS

traceroute to 94.140.14.14 (94.140.14.14), 64 hops max, 52 byte packets
 1  192.168.50.1 (192.168.50.1)  20.499 ms  4.139 ms  6.017 ms
 2  * * *
 3  * * *
 4  136.hiper04.sheff.dial.plus.net.uk (195.166.143.136)  21.566 ms  18.141 ms  19.285 ms
 5  core5-hu0-0-0-26.faraday.ukcore.bt.net (195.99.127.68)  19.500 ms
    peer7-et-4-0-5.telehouse.ukcore.bt.net (194.72.16.130)  22.384 ms
    peer7-et-3-1-5.telehouse.ukcore.bt.net (109.159.252.236)  29.908 ms
 6  166-49-214-194.gia.bt.net (166.49.214.194)  19.012 ms  22.763 ms  18.252 ms
 7  * * *
 8  * * be3487.ccr41.lon13.atlas.cogentco.com (154.54.60.5)  27.303 ms
 9  be2572.ccr21.lon02.atlas.cogentco.com (154.54.61.254)  20.278 ms  19.566 ms  19.923 ms
10  * * datacamp.demarc.cogentco.com (149.6.149.234)  24.782 ms
11  * dns.adguard.com (94.140.14.14)  27.249 ms  23.215 ms

### Issue Details

Set up Adguard DNS using Configuration Profile
1. Open web browser on Mac
2. Log in to Adguard DNS account
3. Follow the steps to connect a Mac using a configuration profile
4. Download configuration profile
5. Open System Settings to install profile
6. Clear DNS cache from terminal

Check if Mac is using Adguard DNS
1. Go to Adguard DNS account in web browser and see if Mac is using Adguard 
2. Connect Mac to a wifi network that doesn't use Adguard DNS
3. Connect Mac to mobile data using personal iPhone that has Adguard DNS configuration profile installed

### Expected Behavior

For all three checks – macOS uses personalised Adguard DNS server for DNS queries. Blacklisted URLs are blocked.

### Actual Behavior

For all three checks – macOS ignores the configuration profile and uses upstream DNS server. Blacklisted URLs are accessible from all browsers.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by jslawler** [comment]
Is the AdGuard DNS configuration profile enabled under System Settings > Network > Filters?

<img width="827" alt="Screenshot 2023-05-24 at 20 35 23" src="https://github.com/AdguardTeam/AdGuardDNS/assets/95468948/a30dda07-9670-4462-a3bb-472622e7a219">

**Comment by jeremybickerstaffe** [comment]
Hi there. I didn't know about that setting. I enabled it and did some tests. My findings are that it has made blocking effective in Safari. However I use Vivaldi, and sites that should be blocked by user rules are still accessible from Vivaldi.

Background: I contacted Adguard support about this and after they couldn't help they passed information onto development team but suggested I raise a bug ticket for a quicker response. NB Enabling the DNS filter is not listed as a setup step in the Adguard documentation page.

**Comment by jslawler** [comment]
@jeremybickerstaffe

For the first issue, try turning off "Use secure DNS" in Vivaldi settings by typing the following in the address bar: vivaldi://settings/security.

For the second issue, I've raised an issue to address the setup not being updated for macOS Ventura.

**Comment by jeremybickerstaffe** [comment]
Thanks. I checked and "Use secure DNS" is already disabled in Vivaldi settings.
I'll see if I can find any other settings that might be overriding the system DNS.

**Comment by jeremybickerstaffe** [comment]
I can get Vivaldi to use Adguard DNS by setting Secure DNS to customised and entering my personal DNS-over-HTTPS address. It doesn't accept DNS-over-TLS or DNS-over-QUIC.

**Comment by Chinaski1** [comment]
Hello guys.

Yes, it seems that Vivaldi is overriding the DNS profile settings because the browser uses its own DNS server. 

As for checking if you are connected to DNS servers, the easiest way to find out is to go to the [test page](https://adguard.com/en/test.html).

Also in the next update, we'll try to have time to update the macOS Ventura profile setup instructions.

**Comment by Chinaski1** [comment]
I close this task, then I will report an update to the instructions within the https://github.com/AdguardTeam/AdGuardDNS/issues/607
