### ISSUE TITLE
Update configuration profile setup instructions for macOS Ventura

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardDNS#607]
macOS Ventura changed the layout of System Settings as well as how configuration profiles are handled by the OS.

The instructions on the AdGuard DNS device setup pages for macOS configuration profiles are no longer current for macOS Ventura and will not work as they are without extra work being required by the user.

The new way to install a configuration profile can be found [here](https://support.apple.com/my-mm/guide/mac-help/mh35561/mac#:~:text=Install%20a%20configuration%20profile%20you%27ve%20received&text=Choose%20Apple%20menu%20%3E%20System%20Settings,or%20other%20information%20during%20installation.).

**Comment by jslawler** [comment]
Issue identified in #606

**Comment by Chinaski1** [comment]
Thanks for the information, I will attempt to add the instructions in the next update.

**Comment by Chinaski1** [comment]
Internal id AGDNS-1503

**Comment by Chinaski1** [comment]
Added in v2.3 update.
