### ISSUE TITLE
Add "Clubhouse" in Blocked services and websites

### ISSUE THREAD

**Issue by sayedarifuddin** [AdguardTeam/AdGuardDNS#609]
### Issue Details

Ability to block/unblock "Clubhouse" (The social audio app – https://www.clubhouse.com/)

### Proposed solution

Server settings > Parental control > Blocked services and websites > Manage services > Block/unblock "Clubhouse"

**Comment by Chinaski1** [comment]
Moved to https://github.com/AdguardTeam/HostlistsRegistry/issues/225
