### ISSUE TITLE
lcpdfr.com blocked

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardDNS#61]
I found it in the dns log.. it says blocked. but i cant find it in the filters list.

**Comment by jo2dan23** [comment]
I found it in the dns log.. it says blocked?

**Comment by Alex-302** [comment]
Which DNS are you using?

**Comment by jo2dan23** [comment]
Default

**Comment by jo2dan23** [comment]
Found the problem. 

@@||g17media.com^ will fix it. Thats the cname which blocks both sites

**Comment by Alex-302** [comment]
Ok, added.
