### ISSUE TITLE
AdGuard DoH in Google Chrome

### ISSUE THREAD

**Issue by LazyAspect** [AdguardTeam/AdGuardDNS#61]
Hello,

as you know Google Chrome supports DNS-over-HTTPS from version 78:
https://www.zdnet.com/article/how-to-enable-dns-over-https-doh-in-google-chrome/

Several providers for this protocol will soon be added (Quad9, Cloudflare, Google, OpenDNS, Cleanbrowsing etc.). You can also request that your servers be included in this list. More information here:
https://www.chromium.org/developers/dns-over-https
http://lists.encrypted-dns.org/scripts/wa-ENCDNS.exe?A2=ENCRYPTED-DNS;f98e120c.1910&S
https://blog.chromium.org/2019/10/addressing-some-misconceptions-about.html

It will be great if your service is also on this list.

Thank you.

**Comment by ameshkov** [comment]
We requested adding AG DNS to the DNS resolvers list
