### ISSUE TITLE
Cursor takes effect on button even though there's a space between titles and button

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdGuardDNS#611]
### Platform

Windows

### Protocol

Regular

### Do you use AdGuard app?

Yes I am

### Steps to reproduce:
1. Go to server settings

### Expected Behavior

Space in between should be deleted or not select button when cursor is in space.

### Actual Behavior

There's a space between the titles and the button and the cursor affects the area of the button. But the cursor doesn't select the button (the square box behind the button)

### Screenshots

<details><summary>Screenshot 1:</summary>

https://github.com/AdguardTeam/AdGuardDNS/assets/35523759/5e0d19d8-207c-4589-b353-118f70abedce
</details>

**Comment by Chinaski1** [comment]
Hello there!
This is made intentionally for the convenience of users.
