### ISSUE TITLE
Getting server connect to Los Angeles California

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardDNS#614]
### Platform

Router

### Protocol

Regular

### Do you use AdGuard app?

Yes I am

### Issue Details

Na

### Actual Behavior

On Adguard services check page I'm getting server "dns2-dp-la-1" which says it's located in Los Angeles California. The location I am in is in Canada Manitoba. 

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

Should it be located at least in Chicago the closer

**Comment by D13410N3** [comment]
Currently there is no way to connect to server in Canada - it is serving old AdGuard DNS addresses only.
We will change this behaviuor in near future, but at this moment LA is the best available server for you
