### ISSUE TITLE
Improve readability of highlighted text when using dark mode

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardDNS#617]
### Issue Details

When highlighting a domain in AdGuard DNS when using dark mode, it is hard to see the highlighted text on the grey background.

<img width="519" alt="Screenshot 2023-06-05 at 04 59 26" src="https://github.com/AdguardTeam/AdGuardDNS/assets/95468948/ca53142e-35f2-488d-a4c4-c953c5fe900e">

### Proposed solution

Consider changing the background colour or highlighting colour to make it more readable.

**Comment by Chinaski1** [comment]
Internal ID: AGDNS-1522

**Comment by Chinaski1** [comment]
Fixed at [v2.2.1](https://adguard-dns.io/en/versions.html#2.2.1)
