### ISSUE TITLE
Redirect HACKING.md to the AdGuard Code Guidelines repo

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardDNS#619]
### Issue Details

The HACKING.md file directs users to the code guidelines in the AdGuard Home repo, which then redirects users a second time to the AdGuard Code Guidelines repo.

### Proposed solution

Cut out the AdGuard Home repo, and redirect users to the [AdGuard Code Guidelines](https://github.com/AdguardTeam/CodeGuidelines) repo.

**Comment by ameshkov** [comment]
Fixed it, thank you!
