### ISSUE TITLE
Add incom.org to whitelist

### ISSUE THREAD

**Issue by ookangzheng** [AdguardTeam/AdguardDNS#62]
This my school workspace website ( FH potsdam)
https://incom.org

**Comment by Alex-302** [comment]
What's wrong?

**Comment by ameshkov** [comment]
Seems to work ok on my side

**Comment by sandybeachit** [comment]
can we close this off as its an old ticket and no response from the user?

**Comment by vozersky** [comment]
@sandybeachit sure thing, cheers
