### ISSUE TITLE
No filter lists have been updated for 3+ days

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardDNS#623]
It seems the filter lists aren't being updated at the moment. As an example see the last modified time for [1Hosts (Lite)](https://adguardteam.github.io/HostlistsRegistry/assets/filter_24.txt).

Experienced also on [Telegram](https://t.me/adguard_en/227546).

<img width="496" alt="Screenshot 2023-06-07 at 21 33 05" src="https://github.com/AdguardTeam/AdGuardDNS/assets/95468948/d6f62c7f-c9a9-438c-b628-a4111a9444c8">

**Comment by KnightmareVIIVIIXC** [comment]
Same issue here
