### ISSUE TITLE
Bad routing. US to Turkey.

### ISSUE THREAD

**Issue by OlgaPetukhova** [AdguardTeam/AdGuardDNS#624]
### Platform

Windows

### Protocol

DNS-over-HTTPS

### Do you use AdGuard app?

Yes I am

### Issue Details

1. I am on Verizon 
2. Fios in the United States.
3. dns2-dp-ist.2 

### Actual Behavior

When trying to access [www.virginia.gov](http://www.virginia.gov/) it's impossible through AdGuard DNS. If to switch the DNS server to anything but AdGuard, there is no access to the virginia site

### Screenshots

![image (7)](https://github.com/AdguardTeam/AdGuardDNS/assets/104968678/60ddcc8f-633b-4d46-924c-7bde45218106)

![image (6)](https://github.com/AdguardTeam/AdGuardDNS/assets/104968678/c20998ca-dd76-4fb5-916d-080dc595ad30)

**Comment by D13410N3** [comment]
Hello!
Issue should be fixed now.
Can you please show content of https://dns.adguard.com/info.txt ?
