### ISSUE TITLE
Show full DNS address on device setup in mobile browser

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardDNS#625]
### Issue Details

On step 2 of setting up a device, and tapping the Encrypted DNS servers drop-down, the addresses listed are cut off unnecessarily preventing the full address from being read without copying and pasting the address somewhere else.

iOS/Safari 16.6
iPhone 13 Pro

### Proposed solution

On displays that are large enough for the full address, show the full address.

On displays that are too small to handle the full address, continue the address on a new line.

![IMG_0461](https://github.com/AdguardTeam/AdGuardDNS/assets/95468948/c816d10d-b596-4f45-b7d2-634a21ed610a)

**Comment by Chinaski1** [comment]
Internal ID: AGDNS-1548
