### ISSUE TITLE
Where is this server located

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardDNS#626]
### Platform

Router

### Protocol

Regular

### Do you use AdGuard app?

No I don't

### Your configuration

I have AdGuard Private DNS setup on my Eero router where it's showing the protocol DNS server is going to "dns2-dp-lon-1". Not sure if this is London but if you can confirm for me where the location is where I'm also located in Canada.

### Issue Details

N/A

### Actual Behavior

N/A

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Chinaski1** [comment]
Most likely you really got connected to London. Try restarting the router and checking again.

**Comment by Batman2814** [comment]
I restarted router and it still got connected to server "dns2-dp-lon-1""
