### ISSUE TITLE
Adguard dns seems to be down

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardDNS#629]
### Platform

Other

### Protocol

Regular

### Do you use AdGuard app?

Yes I am

### Your configuration

had to switch to different DNS other then adguard private dns

### Issue Details

NA

### Actual Behavior

Youtube app showing Chinese letters 
Can't load anything 

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by ameshkov** [comment]
There were no issues with the DNS according to the monitoring.

Next time please add traceroute output to the report and try opening `https://dns.adguard-dns.com/info.txt` in the browser to see to which server you're routed.
