### ISSUE TITLE
Bad filter

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardDNS#63]
![img_2737](https://cloud.githubusercontent.com/assets/15130139/19360525/927192ec-9144-11e6-9380-06cf24179a44.PNG)
googleadapis.l.google.com blocks fonts.googleapis which shouldnt be blocked and it blocks imadsk.googleapis in the exceptions list. Maybe we just remove this filter completely.

**Comment by Alex-302** [comment]
excluded from DNS filter
