### ISSUE TITLE
NoTracking List Discontinued 

### ISSUE THREAD

**Issue by KnightmareVIIVIIXC** [AdguardTeam/AdGuardDNS#630]
### Issue Details

https://github.com/notracking/hosts-blocklists/issues/900

### Proposed solution

Remove notracking list

### Alternative solution

I have lists if you need a replacement. Just something I threw together on the fly. I can rename it if needed or make edits.
https://github.com/KnightmareVIIVIIXC/AIO-Firebog-Blocklists

**Comment by Chinaski1** [comment]
Transferred to related repo https://github.com/AdguardTeam/HostlistsRegistry/issues/258
