### ISSUE TITLE
Dutch translation error 

### ISSUE THREAD

**Issue by mnvr1991** [AdguardTeam/AdGuardDNS#632]
### Platform

Other

### Protocol

DNS-over-HTTPS

### Do you use AdGuard app?

Yes I am

### Issue Details

There is a translation error for the list “OISD Big”. 

In Dutch it is translated to “Energized Spark”.

See screenshots in English and Dutch
![IMG_5248](https://github.com/AdguardTeam/AdGuardDNS/assets/83885255/87375efb-abdf-4e11-abb9-e2782e32ea54)
![IMG_5247](https://github.com/AdguardTeam/AdGuardDNS/assets/83885255/3f521b40-eb9a-4ad8-bf43-f62a8e8f2d45)

### Actual Behavior

Dutch should be OISD Big blokkeerlijst

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Chinaski1** [comment]
Translations for third-party filters are not performed.

**Comment by mnvr1991** [comment]
Who is responsible for the translation at https://adguard-dns.io/nl/dashboard/settings/blocklist?
Where can I report this translation error?
