### ISSUE TITLE
Retain last page settings upon returning to page

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardDNS#633]
It would be nice if last settings used could be retained, similarly to days and query limit in the website url (https://adguard-dns.io/en/dashboard/statistics/query?limit=100&retention=DAYS_90).

As an example:
1. Navigate to the Companies page
2. Set "Top requested companies first"
3. Navigate to Query Log
4. Navigate back to Companies page
5. Companies page will show "Top blocked companies first"

**Comment by Chinaski1** [comment]
Internal ID: 1563

**Comment by Chinaski1** [comment]
Closed due not reproducing.
