### ISSUE TITLE
AdGuard DNS DoH protocol prioritisation

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardDNS#634]
With the release of AdGuard for iOS v4.5, we can now use DoH3.

Obviously we can choose to exclusively use DoH3 (h3://), but what is the current status when using just DoH (https://)?

Will it negotiate whether to use h2 or h3, or will it just use h2 for the moment?

If it currently negotiates whether to use h2 or h3, what factors does it consider for this?

If it's strictly h2 for the moment, is there an open issue I can follow to see when it's rolled out?

**Comment by ameshkov** [comment]
No, it sticks to using H2 at the moment and we haven't yet added a low-level setting that would switch that behaviour.

Opened a public issue about that here: https://github.com/AdguardTeam/AdguardForiOS/issues/2183
