### ISSUE TITLE
Query Log Shows Two entries for same request

### ISSUE THREAD

**Issue by anxiouslelimo** [AdguardTeam/AdGuardDNS#635]
For almost all queries there are two entries in query log of adguard-dns.io, the difference being one is of type https and the other type A. 

1. Is this the intended behaviour? 
2. Does this two entries count towards total query limit of 300k?[](url)
<img width="293" alt="Screenshot 2023-07-20 180228" src="https://github.com/AdguardTeam/AdGuardDNS/assets/115996455/bcaa41ed-e5ea-48c4-810b-b729852c2291">
<img width="395" alt="Screenshot 2023-07-20 180311" src="https://github.com/AdguardTeam/AdGuardDNS/assets/115996455/6966038d-1bc2-4865-ad82-74a416c545bf">

**Comment by Chinaski1** [comment]
Hello there!

Yes, this is expected behavior, different types of queries were used. They will both be counted in the statistics
