### ISSUE TITLE
really slow connecting to multiple services with adguard dns personal 

### ISSUE THREAD

**Issue by ijuliank** [AdguardTeam/AdGuardDNS#636]
### Platform

Other

### Protocol

Regular

### Do you use AdGuard app?

No I don't

### Your configuration

plain dns on console 

### Traceroute to AdGuard DNS

Tracing route to dns.adguard.com [94.140.14.14]
over a maximum of 30 hops:

  1    <1 ms    <1 ms    <1 ms  192.168.2.254
  2     7 ms     8 ms     6 ms  static.kpn.net [HIDED IP]
  3     *        *        *     Request timed out.
  4     *        *        *     Request timed out.
  5    16 ms    14 ms    13 ms  datacamp-3.gw.opentransit.net [193.251.141.240]
  6     *        *        *     Request timed out.
  7     *        *        *     Request timed out.
  8    12 ms    13 ms    13 ms  dns.adguard.com [94.140.14.14]

### Issue Details

connecting to like 1.1.1.1 fixes the issue

### Expected Behavior

normal starting downloads and starting games 

### Actual Behavior

real ratelimited connection, downloads or games starting does not work, and ps store wont open or reeeaaally slow

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by ameshkov** [comment]
Do you use personal AdGuard DNS? Could you please try narrowing it down to a specific playstation domain that's being used?

**Comment by ijuliank** [comment]
> Do you use personal AdGuard DNS? Could you please try narrowing it down to a specific playstation domain that's being used?

Playstation.com 
Idk its just the whole Playstation platform from the console what slows down too much then its getting unplayable 

Yes i use the adguard dns personal

**Comment by ameshkov** [comment]
Does it depend on which lists are enabled? What happens if you use non-filtering DNS?

If you're using AG DNS personal, you can check out the query log and look for playstation domains there.

What I am trying to understand is whether the issue is caused by content blocking or if it's a resolution issue.

**Comment by ijuliank** [comment]
> Does it depend on which lists are enabled? What happens if you use non-filtering DNS?
> 
> If you're using AG DNS personal, you can check out the query log and look for playstation domains there.
> 
> What I am trying to understand is whether the issue is caused by content blocking or if it's a resolution issue.

Ive whitelisted their domains, nothing from them is blocked

**Comment by ameshkov** [comment]
@ijuliank all domains? It could be third-party trackers for instance.

Could you please try somehow extract all domains that appear in the log when you enable playstation and open PS store?

I'll also need to know your IP address and which server you're routed to (dns.adguard-dns.com/info.txt)

**Comment by ijuliank** [comment]
> dns.adguard-dns.com/info.txt

Looks like its all under Playstation.com subdomains
dns2-dp-ams-2

**Comment by ijuliank** [comment]
Same issue appears for Nintendo services..

**Comment by ijuliank** [comment]
@ameshkov i have you on telegram, @miixms to get my ip please

**Comment by ijuliank** [comment]
Also, lagg with tiktok somethimes.. Wich causes rendering issues at the beginning of the video, or when its a long video and in the middle of it its just stop playing  
![IMG_1032](https://github.com/AdguardTeam/AdGuardDNS/assets/64658680/d4c8cf56-3ab0-4a7f-90b0-6b811241a1ff)
As shown on the screenshot, a loading line

**Comment by gpodder770** [comment]
> Also, lagg with tiktok somethimes.. Wich causes rendering issues at the beginning of the video, or when its a long video and in the middle of it its just stop playing ![IMG_1032](https://user-images.githubusercontent.com/64658680/256930341-d4c8cf56-3ab0-4a7f-90b0-6b811241a1ff.jpeg) As shown on the screenshot, a loading line

I am having the same issue with tiktok on singapore server. If I use from my network tiktok mobile app won't play videos, but if I use agvpn with agdns then it would play...because of this had to remove agdns from router

**Comment by ijuliank** [comment]
The issue seems randomly fixed for me😅🤷‍♂️ everything is working again as expected

**Comment by ijuliank** [comment]
closing issue for now because i cant do anything rn
