### ISSUE TITLE
Incorrect routing to LA, US instead of Sydney, AUS

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardDNS#637]
### Platform

iOS

### Protocol

DNS-over-HTTPS

### Do you use AdGuard app?

Yes I am

### Your configuration

AdGuard Personal DNS is being used on 6 mobile devices.
DNS is being provided by AdGuard for iOS. DNS is in native mode.

I have also tried a configuration file with the same result.

The mobile extender is provided by Telstra, and is being used on the Telstra network.
When connected to WiFi provided by Aussie Broadband, the routing is correct (via Australia).
When connected via mobile, yesterday it was routing via Miami. Today it is routing via LA.

This has been reported to @D13410N3 on Telegram.

### Traceroute to AdGuard DNS

```
Host Details
- IP Address: 2001:8004:11d0:4e2a::5e8c:e0e
- Hostname: N/A
- TTL: 53
- AS Number: AS1221
- AS Name: Telstra Corporation Ltd
- Country Name: Australia
- Country Code: AU
- Time Zone: Australia/Sydney
- Region: N/A

Statistics
- Minimum: 48.4 ms
- Maximum: 298.9 ms
- Median: 59.3 ms
- Lost: 3 pkt

Ping
- #1 (06:09:05): N/A
- #2 (06:09:08): N/A
- #3 (06:09:11):  62.9 ms
- #4 (06:09:12): N/A
- #5 (06:09:15):  81.9 ms
- #6 (06:09:16):  56.6 ms
- #7 (06:09:16):  50.1 ms
- #8 (06:09:16):  64.1 ms
- #9 (06:09:16):  57.7 ms
- #10 (06:09:16):  60.1 ms
- #11 (06:09:16):  53.6 ms
- #12 (06:09:17):  57.7 ms
- #13 (06:09:17):  55.7 ms
- #14 (06:09:17):  150.3 ms
- #15 (06:09:18):  56.7 ms
```

### Issue Details

Refer to configuration above.

### Expected Behavior

Routing via Australia.

### Actual Behavior

Routing via US.

### Screenshots

<details><summary>Screenshot 1:</summary>

![IMG_0130](https://github.com/AdguardTeam/AdGuardDNS/assets/95468948/3c7715f1-d972-4b5f-97ed-75e9d8e958be)
![IMG_0131](https://github.com/AdguardTeam/AdGuardDNS/assets/95468948/4f0751f8-5cad-41c0-a291-6828423f1254)

</details>

**Comment by D13410N3** [comment]
Please provide traceroute details on case when you're routed to US servers. You can do it here, via mail `noc@adguard.com` or just send it to my Telegram (you know it)
