### ISSUE TITLE
Enable ECS EDNS Client Subnet in DNS Queries

### ISSUE THREAD

**Issue by trimechee** [AdguardTeam/AdGuardDNS#638]
### Issue Details

Hello, EDNS Client Subnet (ECS) makes DNS connections much faster, does our beloved AdGuard DNS enable by default EDNS Client Subnet ?

if not, I think it will be great not to activate EDNS Client Subnet  in the family dns and activate EDNS on the dns server which filters the ads and malware please, thank you very much !

**Comment by ameshkov** [comment]
We actually send ECS, here're the details: https://github.com/AdguardTeam/AdGuardDNS/issues/542#issuecomment-1436555175
