### ISSUE TITLE
New Location

### ISSUE THREAD

**Issue by gpodder770** [AdguardTeam/AdGuardDNS#639]
### Issue Details

I am from Bangladesh and can't use the Singapore server anymore as tiktok mobile app won't play videos and says network is unstable
Sometimes facebook and instagram also says that

### Proposed solution

Please open a Bangladesh location

**Comment by gpodder770** [comment]
ISP dns routes to 54.230.65.72, 54.230.65.18 for tiktok which doesn't seem to have this problem

**Comment by ameshkov** [comment]
Could you please let us know:

1. What's your IP address?
2. What server name is printed here? https://dns.adguard-dns.com/info.txt

**Comment by Bhooty** [comment]
103.180.245.59
dns2-dp-sg-8

**Comment by Bhooty** [comment]
@ameshkov 

I am having the problem with tiktok sir and asked some info in telegram
You replied saying google and cloudflare dns are fallback

Upon testing doh of both seperately it seems google seems to always send to the closest server thus I have ping like 12-20 and everything plays

but cloudflare reports the sg server(58-60) or taiwan(200+) for which tiktok seems to lag

I am now pretty sure cloudflare is the reason why my tiktok is lagging :(

**Comment by gpodder770** [comment]
> @ameshkov
> 
> I am having the problem with tiktok sir and asked some info in telegram You replied saying google and cloudflare dns are fallback
> 
> Upon testing doh of both seperately it seems google seems to always send to the closest server thus I have ping like 12-20 and everything plays
> 
> but cloudflare reports the sg server(58-60) or (200+) for which tiktok seems to lag
> 
> I am now pretty sure cloudflare is the reason why my tiktok is lagging :(

try now. I tried for two days after @ameshkov commented about edns and now seems to be fixed. I get the less ping like my isp and is much more responsive.
