### ISSUE TITLE
[Blocking Request] Block Gopher Buddy Spyware

### ISSUE THREAD

**Issue by Cybo1927** [AdguardTeam/AdGuardDNS#64]
Gopher Buddy is spyware that pretends to update ChromeOS. My tech people keep adding things like this to the school computers even though they monitor the network directly from Cisco, please block `gopher-buddy-prod.appspot.com`.

![Screenshot 2019-12-09 at 9 21 21 AM](https://user-images.githubusercontent.com/39284087/70448112-7bd81800-1a65-11ea-8d64-9443991aea79.png)

More Information:
https://gsuite.google.com/marketplace/app/gopher_buddy_service/974563760330

Note: It also tends to block legit sites slowing down productivity as noted in `https://github.com/Cybo1927/Block-Gopher-Buddy`

**Comment by Rayn322** [comment]
Even if it wasn't spyware, I don't see a point in using it. It does the same thing as the regular update checker does.

**Comment by TTVLilScope** [comment]
alot of people have said this is spyware.. and the reviews for the extension are veryyy low 826 reviews ALL either 1 or 2 stars. this extension is spyware and google gets breached sometimes and this extension has all of everyone's data and IP data stored on it! imagine everyone's data getting leaked. then were all screwed. even google.
