### ISSUE TITLE
DNS being routed from Ohio in US to Prague in Czechia

### ISSUE THREAD

**Issue by CorrosiveCat2** [AdguardTeam/AdGuardDNS#640]
### Platform

Router

### Protocol

DNS-over-QUIC

### Do you use AdGuard app?

Yes I am

### Your configuration

I have tried both DNS-over-TLS and DNS-over-QUIC and both result in this incorrect routing. This is both through the apps as well as directly setting the server.

### Traceroute to AdGuard DNS

Tracing route to dns.adguard.com [94.140.14.14]
over a maximum of 30 hops:

  1    <1 ms    <1 ms    <1 ms  GT-AX11000-Pro [192.168.50.1]
  2     2 ms    <1 ms     1 ms  192.168.1.1
  3     2 ms     2 ms     3 ms  celina-9006-1.cniteam.com [209.173.171.1]
  4     6 ms     6 ms     6 ms  watch-wabash-dia.bright.net [216.201.0.101]
  5     6 ms     6 ms     6 ms  e0-29.core2.cmh1.he.net [216.66.72.29]
  6     *       11 ms     *     port-channel1.core1.cmh1.he.net [184.104.188.76]
  7     *        *        *     Request timed out.
  8     *        *        *     Request timed out.
  9     *      102 ms     *     100ge0-73.core2.prg1.he.net [184.105.213.14]
 10   102 ms   101 ms   102 ms  datacamp.peering.cz [185.0.20.13]
 11   102 ms   102 ms   102 ms  vl248.prg-ttc2-cdn77-dist-2.cdn77.com [138.199.0.159]
 12   106 ms   102 ms   101 ms  dns.adguard.com [94.140.14.14]

Trace complete.

### Issue Details

Choose any protocol to connect to Adguard DNS from this ISP and this will occur. The ISP is Wabash Mutual Telephone/CNI Inc.

### Expected Behavior

It should route to a closer server such as the one in Columbus or Chicago

### Actual Behavior

The DNS routes all the way across the world to Czechia

**Comment by Chinaski1** [comment]
Hello there!

AdGuard DNS uses [Anycast](https://adguard-dns.io/en/blog/anycast-and-bgp-how-adguard-dns-serves-millions-of-queries.html) technology so we can't manage traffic routing 100% of the time.

At this point, we're compiling problems in internal list with the possibility of their correction in nearest future.
Please provide following information via email to support@adguard.com (also share a link to this issue on GitHub):

1) Your IP address: https://adguard.com/en/test.html
2) ASN. 
3) ISP name.
4) DNS server location: https://adguard.com/en/test.html

I am closing this task as it goes to the internal list of routing issues.
