### ISSUE TITLE
subscription status for ag dns personal out of range

### ISSUE THREAD

**Issue by ijuliank** [AdguardTeam/AdGuardDNS#645]
### Platform

Windows

### Protocol

Regular

### Do you use AdGuard app?

Yes I am

### Your configuration

subscription status for ag dns personal out of range

### Issue Details

![image](https://github.com/AdguardTeam/AdGuardDNS/assets/64658680/76457b16-b5cf-4865-bae9-1841188a6e74)

### Actual Behavior

it should be in range

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Chinaski1** [comment]
Internal ID: AGDNS-1558

**Comment by Chinaski1** [comment]
Fixed in [v2.3](https://dns-mirror.website.agrd.dev/en/versions.html)
