### ISSUE TITLE
mbp.hanabank.com does not work with AdGuard DNS

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardDNS#648]
### Platform

Windows

### Protocol

DNS-over-HTTPS

### Do you use AdGuard app?

Yes I am

### Your configuration

**Original report:**

https://github.com/AdguardTeam/AdguardFilters/issues/154370

### Issue Details

hanabank app does not work.

### Actual Behavior

> mbp.hanabank.com DNS response is SERVFAIL

### Screenshots

<details><summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdGuardDNS/assets/8361299/53a9836b-7c4c-4a9c-aaa7-bd83ef953dd9)

</details>

**Comment by ameshkov** [comment]
Already solved
