### ISSUE TITLE
Allow the user to send their real subnet for ECS

### ISSUE THREAD

**Issue by trmdi** [AdguardTeam/AdGuardDNS#649]
### Issue Details

Currently Adguard DNS uses an anonymized subnet for ECS which may be inaccurate in some countries.
For example in Vietnam,  if Adguard uses an subnet in HCM which tells the upstream DNS server to prefer to return servers near HCM/Singapore, while servers in HN/Hongkong are better if you are in Hanoi. (map: https://www.mapcustomizer.com/map/hn-hcm-hk-sgp)

### Proposed solution

Could you make this optional, something like this:
![Screenshot 2023-08-12 102934](https://github.com/AdguardTeam/AdGuardDNS/assets/11857205/0f5a593c-f49e-40a6-9c10-3331f484893d)
(captured from nextDNS's website)
- enable anonymized ECS -> use an anonymized subnet chosen by Adguard as currently.
- disable -> use the real subnet of the user eg. `14.226.xx.0/24`
- or whatever is set by the user in e.g. AdguardHome, dnsproxy...

**Comment by ameshkov** [comment]
Note, that NextDNS does not send your real ECS, it tries to anonymize it using the way that's very similar to ours.

We use different approaches to improve cache efficiency though. They only enable ECS for a "whitelist" of domains, and we use a limited set of AS numbers instead. We'll publish an article with a more detailed explanation.

Anyways, I suggest you trying again, we made some improvements recently.

The last issue to solve with our anonymization algorithm is big providers in large countries, once we solve it everyone will be happy.
