### ISSUE TITLE
Android System DNS?

### ISSUE THREAD

**Issue by LunarstarPony** [AdguardTeam/AdGuardDNS#65]
![Screenshot_20191218-103446](https://user-images.githubusercontent.com/36251959/71051158-4e385080-2182-11ea-8bf8-6e5a75c85a69.jpg)
Can ADGuard DNS Work with this?

**Comment by TPS** [comment]
Since it's not immediately clear, this is part of the network settings under Android 9+.

**Comment by LunarstarPony** [comment]
Eeyup

**Comment by admitrevskiy** [comment]
Automatic Private DNS mode tries to make DNS-over-TLS queries to system resolver (if it supports this feature).

You can explicitly specify Private DNS provider hostname `dns.adguard.com`.

**Comment by LunarstarPony** [comment]
![Screenshot_20191218-155240](https://user-images.githubusercontent.com/36251959/71066908-98cfc200-21ae-11ea-8edd-f4e9b5d93fac.jpg)
yay It works thanks!
