### ISSUE TITLE
Home network routing via LA, Instead of Sydney

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardDNS#650]
Pretty much the same as #637. As of today, my home network is now showing on dnscheck.tools and the AdGuard test page as using the LA dns server.

I am located in Australia, the closest AGDNS server to me is Sydney, Australia.

Traceroute below.

![image](https://github.com/AdguardTeam/AdGuardDNS/assets/95468948/1eb0812c-c120-4f70-8629-1e7541b93d06)
![image](https://github.com/AdguardTeam/AdGuardDNS/assets/95468948/7688734c-f02e-4979-95c1-d7de249c92ec)
![image](https://github.com/AdguardTeam/AdGuardDNS/assets/95468948/046e88c8-1103-4ecd-9aa7-378f080615d2)

**Comment by ameshkov** [comment]
BGP :(
