### ISSUE TITLE
Google DNS appearing as a resolver when connected to the Sydney, AU AGDNS server

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardDNS#653]
I currently have the ability to test this on the Sydney, AU and the LA, US AGDNS due to a routing issue between my mobile connection and home VDSL connection.

When connected via the SN, AU AGDNS server additional Google DNS resolvers are appearing on dnscheck.tools. There's also Cloudflare appearing, but that could possibly be from iOS's Limit IP Address Tracking feature.

When connected to the LA, US AGDNS server, I don't experience the additional Google DNS resolvers.

@ameshkov [mentioned](https://t.me/adguard_en/234282) this in the Telegram group chat, but I wanted to determine whether that was happening here, or it's something else.

**Connected to SN, AU AGDNS server**
![image](https://github.com/AdguardTeam/AdGuardDNS/assets/95468948/6eab5b86-0b70-4383-a38b-bb9d076dc850)
![image](https://github.com/AdguardTeam/AdGuardDNS/assets/95468948/f3f78b89-db95-4589-9cd5-7a2597fa32cc)
![image](https://github.com/AdguardTeam/AdGuardDNS/assets/95468948/f5fa3087-dc7d-497f-8a7e-cfc522784403)

**Connected to LA, US AGDNS server**
![image](https://github.com/AdguardTeam/AdGuardDNS/assets/95468948/53472c26-a887-4dd1-b535-8984289aa276)

**Comment by 7ossam-3tman** [comment]
@ameshkov your support pls. 
I have also problem with DNS Leak when I sue the Wintun driver and check the leak using dnscheck.tools. Here is the result 

<img width="890" height="869" alt="Image" src="https://github.com/user-attachments/assets/5774c371-5d10-4f27-bccf-19c06dc48da8" />

<img width="923" height="387" alt="Image" src="https://github.com/user-attachments/assets/f93f808a-fd2a-41a7-8f38-a42a42c9392b" />

but I have no DNS leak when I disable the Wintun i have DNS leak at all. 

<img width="863" height="555" alt="Image" src="https://github.com/user-attachments/assets/89bcd6c2-34f0-499d-b067-2c48ab89c18f" />

pls fix this issue ASAP

**Comment by ameshkov** [comment]
WinTun driver in AG VPN?

Could you please explain the full setup that you have?

**Comment by 7ossam-3tman** [comment]
I'm using Adguard VPN on my Windows 11, when activating the WinTun driver I see DNS leak as sent before.
But when I disable the WinTun driver, there are no DNS leaks at all. 
Note: in my router setting, I have set and pushed the DNS that I want. 
Note2: I have windscribe Pro and using it without any DNS on the same setting. 
Note3: I have changed all my router DNS setting and make it Auto and then connect to Adguard VPN with Enabling to WinTun driver and now finally have no DNS leak. 

Note4: I will test it again tomorrow on my Work to see if the result, (I'm using the Current version: 2.7.0 Beta 1 (1794))
Note5: no DNS leak on my Android mobil or TV (whatever the router DNS setting) no LEAK at all.

**Comment by vankos** [comment]
@7ossam-3tman hi,

So, according to note 3 and 5, is the problem resolved?

As @ameshkov mentioned earlier:

> dnscheck.tools triggers many different DNS queries that fail due to a DNSSEC error and records the IP addresses the queries were sent from. AG DNS unfortunately cannot distinguish network errors from DNSSEC errors, so in both cases it tries to use a fallback.

For me, it’s the same behaviour with or without Wintun. You can verify that this is a DNS-side feature —not Wintun or the Windows app—by setting a non-AdGuard DNS server in the app and checking dnscheck.tools.
