### ISSUE TITLE
Incorrect routing again, LA instead of Sydney

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardDNS#656]
**ISP**
Telstra

**Closest Server**
Sydney, Aus

**Being routed to**
LA, US

**Traceoute**

```
Host Details
- IP Address: 2001:8004:11d0:4e2a::5e8c:e0e
- Hostname: N/A
- TTL: 55
- AS Number: AS1221
- AS Name: Telstra Corporation Ltd
- Country Name: Australia
- Country Code: AU
- Time Zone: Australia/Sydney
- Region: N/A

Statistics
- Minimum: 62.0 ms
- Maximum: 62.0 ms
- Median: 62.0 ms
- Lost: 0 pkt

Ping
- 1 (06:32:16):  44.7 ms
```

![image](https://github.com/AdguardTeam/AdGuardDNS/assets/95468948/ae2c5fb7-364c-40d9-8556-38560c16e1c1)

Previous routing issues: #637, #335

**Comment by Chinaski1** [comment]
Hello there!

AdGuard DNS uses [Anycast](https://adguard-dns.io/en/blog/anycast-and-bgp-how-adguard-dns-serves-millions-of-queries.html) technology so we can't manage traffic routing 100% of the time.

At this point, we're compiling problems in internal list with the possibility of their correction in nearest future.
Please provide following information via email to support@adguard.com (also share a link to this issue on GitHub):

1) Your IP address: https://adguard.com/en/test.html
2) ASN. 
3) ISP name.
4) DNS server location: https://adguard.com/en/test.html

I am closing this task as it goes to the internal list of routing issues.
