### ISSUE TITLE
Query log: Status filter "Processed" also shows "Blocked"

### ISSUE THREAD

**Issue by hagezi** [AdguardTeam/AdGuardDNS#657]
### Platform

Router

### Protocol

DNS-over-HTTPS

### Do you use AdGuard app?

No I don't

### Issue Details

1. Open Query log
2. Set Status filter to "Processed"

### Expected Behavior

Only processed entries are displayed. The same behaviour as in AdGuard Home.

### Actual Behavior

Processed and blocked entries are displayed.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Chinaski1** [comment]
Fixed in [v2.3](https://dns-mirror.website.agrd.dev/en/versions.html)

**Comment by hagezi** [comment]
@Chinaski1 Thank you for the quick and uncomplicated implementation.
