### ISSUE TITLE
Improved EDNS Client Subnet

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardDNS#659]
### Issue Details

Currently, AdGuard DNS uses a random subnet from the same ASN where the user comes from.

This provides good enough precision for small AS, but large AS (Comcast, China Mobile, etc) need better granularity.

### Proposed solution

In order to achieve better quality we should take "country" and "subdivision" into account alongside the ASN itself.

Internal task ID: AGDNS-1622

**Comment by trmdi** [comment]
Hello, is there any update on this? This would be a big improvement that benefits many users.

**Comment by ameshkov** [comment]
It has been done already, we just haven't announced it publicly. I explained the details on the last DNS OARC: https://www.youtube.com/watch?v=YWWJKvtX7vQ

**Comment by gpodder770** [comment]
> It has been done already, we just haven't announced it publicly. I explained the details on the last DNS OARC: https://www.youtube.com/watch?v=YWWJKvtX7vQ

Thanks came back to try my personal sub again after seeing your comment. After trying for two days, I can say this really improved the speed. The tiktok you mentioned in the video was reported by me and seems to be fixed. I get 15-17 ping now instead of 200+ before the change. Furthermore, it seems facebook and instagram which uses cdn also seems to more faster now and lower ping like tiktok. Really appreciate for the changes.

**Comment by ameshkov** [comment]
@gpodder770 thanks, I am happy to see that this approach actually works. It's not yet finalized and only enabled for a select few countries, we may need to come up with "subdivision" approach for other countries too (see #729)

**Comment by ameshkov** [comment]
UPD: Official announcement is ready: https://adguard-dns.io/en/blog/privacy-friendly-edns-client-subnet.html

**Comment by gpodder770** [comment]
> If possible provide an option to send real ECS? I'm a China user, AdGuard DNS always send the other province's ECS... So it slows down the Internet experience, I wouldn't say I like the idea of sending random ECS.

Yes same

I am having the same problem today in adguard vpn

![IMG_2579](https://github.com/user-attachments/assets/067a1d48-e62f-42c7-96e9-d618546e57ba)
