### ISSUE TITLE
Make it easyer to access the dashboard 

### ISSUE THREAD

**Issue by ijuliank** [AdguardTeam/AdGuardDNS#661]
### Issue Details

Instead using https://adguard-dns.io/en/dashboard/
A different approach what is more easy https://my.adguard-dns.io

### Proposed solution

A different approach what is more easy https://my.adguard-dns.io

**Comment by gpodder770** [comment]
+1

**Comment by Chinaski1** [comment]
These addresses are used to access the AdGuard personal account:
- my.adguard.com / my.adguard-vpn.com
Here you can find information about licenses, their renewal, subscription cancellation, etc.

In the case of the DNS site, the functionality is still different, so we decided to use a more appropriate naming.

**Comment by ijuliank** [comment]
> These addresses are used to access the AdGuard personal account:
> 
>     * my.adguard.com / my.adguard-vpn.com
>       Here you can find information about licenses, their renewal, subscription cancellation, etc.
> 
> 
> In the case of the DNS site, the functionality is still different, so we decided to use a more appropriate naming.

what about https://my.adguard-dns.io/en/
