### ISSUE TITLE
Amend name of Apple Private Relay to iCloud Private Relay in Linked IPv4 address section

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardDNS#664]
<img width="619" alt="Screenshot 2023-09-07 at 6 57 14 am" src="https://github.com/AdguardTeam/AdGuardDNS/assets/95468948/e108cb03-a7f0-4abb-9830-960dbe212a26">

The correct name should be [iCloud Private Relay](https://support.apple.com/en-au/102602), not Apple Private Relay.

**Comment by Chinaski1** [comment]
Fixed at [v2.4 update](https://adguard-dns.io/en/versions.html)
