### ISSUE TITLE
Question about DNS server authentication

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardDNS#665]
Something I noticed today, when raising an issue with a broken website directly from the AdGuard for iOS app was that it automatically inputted my AdGuard Personal DNS address into the GitHub issue.

I have concerns that someone else could effectively use that address without my knowledge.

Is there any form of authentication preventing someone else from using opening that GH issue and using that address for themselves, or any way that I would know someone else was using it?

If not, is there any way we could incorporate some form of authentication in future if someone was to get hold of an AdGuard Personal DNS address?

**Comment by ameshkov** [comment]
We're actually going to detect and mask the AG Personal DNS addresses in reports, it's just not done yet (but will be done soon).
