### ISSUE TITLE
Adguard DNS popup on Linux mint

### ISSUE THREAD

**Issue by Perfectlynk** [AdguardTeam/AdGuardDNS#666]
![Adguard DNS](https://github.com/AdguardTeam/AdGuardDNS/assets/72349391/d31b6b15-5d41-4a76-8dc2-cec8d88691f4)

This keeps popping up when I open Vivaldi. Why is it requesting this? Also I'm assuming and putting this in Adguard DNS because Adguard DNS uses .io.

Linux Mint 21.2
Vivaldi 6.2.3105.47 (64bit)

How to probably reproduce:
Went to _adguard-dns.io/en/dashboard/_ right click on the tab and install Adguard DNS. It's above 'create shortcut or customise' at the bottom of menu (unsure if I clicked 'open in separate tab' which might appear, it's a tick box in the pop up window). It doesn't happen all the time but once you close out of Vivaldi (all windows) and after a while, open back Vivaldi the login may pop up.

This is something new as this never happened on windows 10.

The same kind happens if you do the same thing to Adguard service check page, install it and close Vivaldi but open the Adguard service check in it's own window under 'Vivaldi apps' in the start menu.

I can just cancel the pop up and everything works normally. Also notice when it pops up the web-page doesn't load until I close it.

**Comment by Chinaski1** [comment]
Hello there!

This is a known bug in Chromium browsers, the relevant report is compiled on[ their website](https://bugs.chromium.org/p/chromium/issues/detail?id=1448133).

So we can't do anything on the AdGuard DNS side. We can only wait for a solution from Chromium developers

**Comment by Chinaski1** [comment]
A temporary solution may be to restart your browser.
