### ISSUE TITLE
Family DNS not blocking adult site

### ISSUE THREAD

**Issue by NekoMSG** [AdguardTeam/AdGuardDNS#667]
### Platform

Android

### Protocol

Regular

### Do you use AdGuard app?

No I don't

### Your configuration

Using family.adguard-dns.com in android Private DNS setting.  Not sure if that's tls or https or something else..

### Issue Details

Visit dolcemodz.xyz

Edit: also links through to starsessions.sbs, which apparently also isn't blocked. 

### Expected Behavior

Blocked

### Actual Behavior

Not blocked

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Chinaski1** [comment]
Doman added to the parental control list.
It should be blocked within three days.
