### ISSUE TITLE
Dns leak test fails 

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardDNS#67]
"Настроил в качестве резолвера ваш сервер adguard-dns-ns1 и непонятно почему, но DNS leak test проваливается; при настройке в качестве резолвера других серверов (yandex, d0wn-ru-ns1, soltysiak) DNS leak test проходит замечательно."

"Клиент dnscrypt-proxy 1.7.0 на сервере Debian. А тест - www.dnsleaktest.com"

**Comment by TPS** [comment]
A stronger/customizable/explained version of this test is @ https://www.grc.com/dns/dns.htm

**Comment by vozersky** [comment]
explained here: #110
