### ISSUE TITLE
Routing Issue - AT&T in Los Angeles resolving in Chicago

### ISSUE THREAD

**Issue by jqberry** [AdguardTeam/AdGuardDNS#671]
Hello, I am in Los Angeles, California, my ISP is AT&T fiber, and my IP is in this range 12.160.225.XXX - When I use the public DNS (94.140.14.14 or the .15.15) or my AdGuard paid account, and go to the test page it says:

You are using "Default" AdGuard DNS configuration
Protocol: "DNS"
Server: "dns2-dp-chi-1"

I confirmed it by going to https://browserleaks.com/dns and it shows:

Your DNS Servers	
IP Address :	ISP :	Location :
154.47.25.34	Datacamp Limited	United States, Chicago

Anyway to correct Adguard Home DNS to resolve locally in Los Angeles instead of going to Chicago? I did an IP location test and most if not all GEO IP databases say Los Angeles, but I notice google.com would just say United States, maybe AdGuard Home is going off Google GEO IP location? Thank you!

**Comment by Chinaski1** [comment]
Hello there!

AdGuard DNS uses [Anycast](https://adguard-dns.io/en/blog/anycast-and-bgp-how-adguard-dns-serves-millions-of-queries.html) technology so we can't manage traffic routing 100% of the time.

At this point, we're compiling problems in internal list with the possibility of their correction in nearest future.
Please provide following information via email to support@adguard.com (also share a link to this issue on GitHub):

1) Your IP address: https://adguard.com/en/test.html
2) ASN. 
3) Provider name.
4) DNS server location: https://adguard.com/en/test.html

I am closing this task as it goes to the internal list of routing issues.
