### ISSUE TITLE
AdGuard Private DNS not working with "Local DNS Caching" on Eero Router

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardDNS#673]
### Platform

Router

### Protocol

Regular

### Do you use AdGuard app?

No I don't

### Your configuration

I have an AdGuard Private Plain DNS server address on my Eero Pro 6E Router setup with iPv4 & IPv6. 

### Issue Details

1.) Setup AdGuard Private DNS on your Eero Router with Plain DNS for IPv4 & IPv6. (Will Require Reboot of Eero Router)
2.) Turn on "Local DNS Caching" (Will Reguare a Reboot of Eero Router).
3.) Go to AdGuard Services Check Page to see if you are connected to AdGuard Private DNS.

### Expected Behavior

AdGuard Private DNS should be detected with Eero's "Local DNS Caching." turned on with the AdGuard Services Check Page saying connected with Green Check mark.  

### Actual Behavior

The actual behaviour shows that with "Local DNS Caching" turned on, it's not communicating with AdGuard Private DNS where it's showing on the AdGuard Services Check Page that it's not connected to AdGuard Private DNS and not blocking ads with "Local DNS Caching" turned on. 

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

More Information on Eero feature of "Local DNS Caching" supposed to do: 

Local DNS Caching

Local DNS caching works by storing DNS information locally, which can help speed up the time it takes to load webpages or reach other resources on the internet. 

When this feature is enabled, you will notice that, instead of your ISP or custom DNS settings, you will see the IP address of your gateway eero provided to your devices. This is required for this feature to work, as devices will need to be able to query the cached DNS information on the gateway eero. 

From there, the gateway eero will then send any DNS messages out to either your ISP DNS servers by default, or to your custom DNS servers for any DNS resolution.

**Comment by Batman2814** [comment]
Might it be related to this issue? 

 Unoptimal Amazon IP addresses for a Canadian ISP Gitbub Issue #333

**Comment by Batman2814** [comment]
I know that, but Gateway eero sends the requests to the AdGuard Private DNS to get the resolution. I was working before, and I was told the problem lies with AdGuard Private DNS, and it only happens with Shaw ISP. I have confirmed it works on the Bell MTS ISP. I am wondering if this problem is Github issue #: 333 since the Eero feature Local DNS caching uses Amazon servers to send to AdGuard Private DNS, which could be sending Unoptimal Amazon IP addresses for a Canadian ISP. I'm 100% aware that this is a bug with AdGuard Private DNS. It also happens on AdGuard Public DNS when set up on my eero Router with Shaw ISP.

**Comment by D13410N3** [comment]
Anyway, it's not your router / device is sending queries to AdGuard DNS - someone else (in this case - your provider, I suppose) is doing this for you.
Using provider's DNS as "cache" server won't speed up DNS resolution - at least, until time when cache will be big enough. If this cache is pretty aggressive you won't be able to use actual AdGuard DNS filters - cached values would be sent to your device. If cache is flushing and updating time to time - response delay will be the same as if you are not using provider's cache DNS server

**Comment by Batman2814** [comment]
I was told it lies with my custom DNS, which is AdGuard Private DNS I use. It works fine on my other network at the other location I have with local DNS caching on which uses ISP  BellMTS, but it won't work with Shaw communications for AdGuard Private DNS which It was before but not anymore. So why did you close this case?

**Comment by Batman2814** [comment]
When local dns caching is on, it can only be used with custom dns or your default ISP. I have an Adguard Private DNS setup for it.
