### ISSUE TITLE
80% packet loss with AdGuard DNS

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardDNS#675]
I've been getting a lot of packet loss lately with only AdGuard, and don't know the reason why.

I used mtr with Google, Cloudflare, Quad9 and AdGuard as a comparison. For whatever reason, I only seem to be getting a huge amount of packet loss with AdGuard.

Note that this may or may not be related to #656.

<img width="1145" alt="Screenshot 2023-10-08 at 1 49 32 pm" src="https://github.com/AdguardTeam/AdGuardDNS/assets/95468948/1d5d4953-be81-438e-b3db-8a08bef21984">

**Comment by D13410N3** [comment]
Hello. I see no losses on provided MTR stats. Look at the last hop - there is 0.0% loss.
82% loss to the 9th hop may mean that there is ICMP ratelimit on this hop - it is usual situation.
