### ISSUE TITLE
Adguard dns personal apple profile link copy

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardDNS#679]
### Platform

Other

### Protocol

DNS-over-HTTPS

### Do you use AdGuard app?

Yes I am

### Your configuration

Doesnt matter

### Traceroute to AdGuard DNS

No routing issue

### Issue Details

When i copy the Apple dns config profile link /public_api/v1/settings/XXX/doh_mobileconfig.xml i get this
![image](https://github.com/AdguardTeam/AdGuardDNS/assets/64658680/dbaa9eb1-ab5d-4f74-9d64-5c93ab37ba08)

### Expected Behavior

Put back https://adguard-dns.io in front

### Actual Behavior

Put back https://adguard-dns.io in front

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Chinaski1** [comment]
Internal ID: [AGDNS-1576]

**Comment by Chinaski1** [comment]
Fixed
