### ISSUE TITLE
Websites not loading

### ISSUE THREAD

**Issue by Andrei-Iosifescu123** [AdguardTeam/AdGuardDNS#681]
### Platform

Android

### Protocol

Regular

### Do you use AdGuard app?

No I don't

### Your configuration

dns.adguard.com in private DNS settings

### Traceroute to AdGuard DNS

```
traceroute to 94.140.14.14 (94.140.14.14), 30 hops max, 60 byte packets
 1  * * *
 2  10.143.0.13 (10.143.0.13)  31.627 ms  32.313 ms  32.012 ms
 3  10.132.128.202 (10.132.128.202)  31.712 ms  31.631 ms  31.106 ms
 4  10.0.242.193 (10.0.242.193)  31.735 ms  32.430 ms  31.129 ms
 5  * * *
 6  10.0.240.150 (10.0.240.150)  53.978 ms  43.744 ms 10.0.240.186 (10.0.240.186)  46.086 ms
 7  10.0.240.9 (10.0.240.9)  45.777 ms  49.376 ms
```

### Issue Details

Steps to reproduce:
1. Set private dns to dns.adguard.com on Android
2. Try to open Google, Accuweather, Reddit, Wikipedia etc.
3. Website / App will not load 

### Expected Behavior

The websites / apps work properly when AdGuard is enabled. 

### Actual Behavior

The websites / apps do not load when AdGuard is enabled. 

### Screenshots

<details><summary>Screenshot 1:</summary>
![Screenshot_20231025_190549_com reddit frontpage](https://github.com/AdguardTeam/AdGuardDNS/assets/35394195/f61a9c22-1fd6-46f4-858b-bb5ebc54cf21)
Reddit not loading
</details>
<details><summary>Screenshot 2:</summary>
![Screenshot_20231025_191617_com android settings](https://github.com/AdguardTeam/AdGuardDNS/assets/35394195/adc3d95f-45b8-4dd9-a4b8-a9467393aa46)
Private DNS settings
</details>

### Additional Information

This issue is not always present, sometimes everything works fine, sometimes not. Usually disabling AdGuard DNS, waiting a couple minutes and re-enabling it solves the issue for some time, until it appears again.

**Comment by ameshkov** [comment]
There's an ongoing incident: https://status.adguard.com/incidents/jdr9fhxt2jwt

**Comment by Andrei-Iosifescu123** [comment]
Issue is still not fixed. Reddit won't load unless I disable AdGuard DNS
