### ISSUE TITLE
Adguard dns resolves wrong for KPN MOBILE NL to USA

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardDNS#682]
### Platform

Android

### Protocol

DNS-over-HTTPS

### Do you use AdGuard app?

Yes I am

### Your configuration

Ag dns personal

### Traceroute to AdGuard DNS

traceroute to 94.140.14.49 (94.140.14.49) , 5 relative hops max, 52 byte packets
   1  * * *
   2 145.54.66.119 (145.54.66.119) 65.144 ms 261.515 ms 263.685 ms
   3 145.54.66.192 (145.54.66.192) 37.172 ms 234.561 ms 236.412 ms
   4 139.156.156.133 (139.156.156.133) 130.109 ms 315.451 ms 317.439 ms
   5  * * *
   6 84.116.130.121 (84.116.130.121) 180.892 ms 937.596 ms 940.862 ms
   7 84.116.130.122 (84.116.130.122) 181.582 ms 1030.343 ms 1033.218 ms
   8 84.116.146.141 (84.116.146.141) 145.156 ms 925.149 ms 928.392 ms
   9 84.116.130.229 (84.116.130.229) 174.686 ms 938.478 ms 941.789 ms
 10  * * *
 11 185.156.45.241 (185.156.45.241) 211.629 ms 589.421 ms 590.778 ms
 12 94.140.14.49 (94.140.14.49) 186.521 ms 553.845 ms 556.992 ms

### Issue Details

Wrong route

### Actual Behavior

Route to frankfurt

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by ijuliank** [comment]
Same for Odido NL (tmobile netherlands old name)

**Comment by Chinaski1** [comment]
Hello there!

AdGuard DNS uses [Anycast](https://adguard-dns.io/en/blog/anycast-and-bgp-how-adguard-dns-serves-millions-of-queries.html) technology so we can't manage traffic routing 100% of the time.

At this point, we're compiling problems in internal list with the possibility of their correction in nearest future.
Please provide following information via email to support@adguard.com (also share a link to this issue on GitHub):

1) Your IP address: https://adguard.com/en/test.html
2) ASN. 
3) Provider name.
4) DNS server location: https://adguard.com/en/test.html

I am closing this task as it goes to the internal list of routing issues.
