### ISSUE TITLE
Are these strings transable?

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdGuardDNS#683]
### Issue Details

How can we localize the "INFO" string in the blue box in [here](https://adguard-dns.io/kb/tr/general/dns-providers/)?
Same for in [here](https://adguard-dns.io/kb/tr/general/dns-filtering/) too.
At the Crowdin this string source is ":::info".

### Proposed solution

Can you make these strings transable?

**Comment by Chinaski1** [comment]
Hello.

The abbreviation INFO is common all over the world, so there is no need to translate it.

**Comment by Chinaski1** [comment]
But you're still can translate by following the [link](https://crowdin.com/translate/adguard-knowledge-base/19250/en-ru?filter=basic&value=0#4026006)

**Comment by gork7777** [comment]
@Chinaski1 I've translated this but still appearing as "INFO".
