### ISSUE TITLE
Resizing Safari window with real-time updates enabled crashes AdGuard DNS dashboard (error 500)

### ISSUE THREAD

**Issue by kyjhoz-mikfip-goXci0** [AdguardTeam/AdGuardDNS#686]
### Platform

macOS

### Protocol

DNS-over-HTTPS

### Do you use AdGuard app?

No I don't

### Issue Details

1. Maximise browser window in AdGuard DNS, navigate to query log, and turn on real-time updates
2. Resize the window

### Actual Behavior

As soon as the window resizes, it causes an error 500.

Console output
```
[Error] Error: Minified React error #188; visit https://reactjs.org/docs/error-decoder.html?invariant=188 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
	i (a.main.839.min.js:227:68431)
```

### Screenshots

<details><summary>Screenshot 1:</summary>

https://github.com/AdguardTeam/AdGuardDNS/assets/149243371/432249d9-dc7b-4f13-8083-dd526d7d8c0c

</details>

**Comment by Chinaski1** [comment]
Internal ID: AGDNS-1760

**Comment by Chinaski1** [comment]
Fixed
