### ISSUE TITLE
Incorrect listing in Connect to public AdGuard DNS on the site

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdGuardDNS#687]
### Platform

Windows

### Protocol

Regular

### Do you use AdGuard app?

Yes I am

### Issue Details

1. Go to the [Connect to public AdGuard DNS server](https://adguard-dns.io/en/public-dns.html) site.
2. Select Method №2.

### Expected Behavior

The listing should be as follows:
1.
2.
3.
etc.

### Actual Behavior

But in some areas the listing is incorrect:
1.
1.
1.

### Screenshots

<details><summary>Android section:</summary>

![image](https://github.com/AdguardTeam/AdGuardDNS/assets/35523759/9143e090-44a9-4b1f-9f26-012f1c3d79e5)
</details>

<details><summary>Windows section:</summary>

![image](https://github.com/AdguardTeam/AdGuardDNS/assets/35523759/ed24ec3a-7985-4251-b1bf-21a81ad99eeb)
</details>

<details><summary>macOS section:</summary>

![image](https://github.com/AdguardTeam/AdGuardDNS/assets/35523759/20985c36-b9d2-4af7-91bd-98aa69793db7)
</details>

<details><summary>Routers section:</summary>

![image](https://github.com/AdguardTeam/AdGuardDNS/assets/35523759/aebf3d71-167e-4741-ae26-c0f6dbe00af2)
</details>

**Comment by Chinaski1** [comment]
Internal ID: AGDNS-1768
