### ISSUE TITLE
Please Provide DNS roadmap

### ISSUE THREAD

**Issue by joetimmy** [AdguardTeam/AdGuardDNS#689]
I kindly request a rough roadmap of feature coming with future DNS versions.

**Comment by joetimmy** [comment]
@Chinaski1

**Comment by Chinaski1** [comment]
There are no plans yet. But we will consider this prospect in the future.

**Comment by MineGene** [comment]
Last update was May 22, less than a month ago.

https://adguard-dns.io/en/versions.html

**Comment by Chinaski1** [comment]
This is far from a simple task from a technical point of view.

As for AGDNS updates, we regularly release new versions at 1-3 month intervals

**Comment by pictosun** [comment]
> Last update was May 22, less than a month ago.
> 
> https://adguard-dns.io/en/versions.html

Ok - was only looking at GitHub. There is an old/outdated version with no updates (v2.13).

**Comment by pictosun** [comment]
> As for AGDNS updates, we regularly release new versions at 1-3 month intervals

Thx for the update. But as I said above your GitHub release is a version behind the release on your website.
