### ISSUE TITLE
Adguard DNS breaks web.whatsapp.com

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardDNS#69]
https://web.whatsapp.com/

**Comment by Alex-302** [comment]
Whan't wrong?
![image](http://imagizer.imageshack.com/img923/3494/yARKA8.png)
<details>
![image](http://imagizer.imageshack.com/img924/3594/otyZzV.png)
</details>

**Comment by ameshkov** [comment]
Maybe this was due to "googleadapis.l.google.com"?
