### ISSUE TITLE
Top blocked companies first/top queried companies first drop down no longer functions correctly

### ISSUE THREAD

**Issue by kyjhoz-mikfip-goXci0** [AdguardTeam/AdGuardDNS#690]
### Platform

macOS

### Protocol

DNS-over-HTTPS

### Do you use AdGuard app?

No I don't

### Issue Details

Navigate to companies page
Tap 'Top blocked companies first' and try switch to 'Top queried companies first'

### Expected Behavior

Able to select either option

### Actual Behavior

Unable to select any of the available options

### Screenshots

<details><summary>Screenshot 1:</summary>

https://github.com/AdguardTeam/AdGuardDNS/assets/149243371/136fa9e2-11bf-4d63-b1db-11adefd6c87f

</details>

### Additional Information

Tested on Safari Version 17.2 (19617.1.16.11.2), and Chrome 119.0.6045.105.

**Comment by Chinaski1** [comment]
This issue also be fixed in AGDNS-1726

**Comment by Chinaski1** [comment]
Fixed

**Comment by Chinaski1** [comment]
Thank you for letting us know about the issues, our team appreciate it :)
