### ISSUE TITLE
Hover over items overlapping on Statistics and Companies page

### ISSUE THREAD

**Issue by kyjhoz-mikfip-goXci0** [AdguardTeam/AdGuardDNS#691]
### Platform

macOS

### Protocol

DNS-over-HTTPS

### Do you use AdGuard app?

No I don't

### Issue Details

Open Statistics or Companies page

Hover over any of the request types, top companies, top destinations or top domains sections on the Statistics page, or the top requested company section or top blocked company section.

### Expected Behavior

Hover over panels disappear before showing another one.

### Actual Behavior

Hover over panels are overlapping.

Browser must be maximised to repro.

### Screenshots

<details><summary>Screenshot 1:</summary>
<img width="585" alt="Screenshot 2023-11-15 at 08 11 44" src="https://github.com/AdguardTeam/AdGuardDNS/assets/149243371/5a96f95e-b9a1-470f-b4df-a32a810b739d">
<img width="626" alt="Screenshot 2023-11-15 at 08 11 52" src="https://github.com/AdguardTeam/AdGuardDNS/assets/149243371/c0958204-5784-4b8a-8e0f-db3f29e8669b">
<img width="1275" alt="Screenshot 2023-11-15 at 08 12 01" src="https://github.com/AdguardTeam/AdGuardDNS/assets/149243371/e277e484-f2fa-473e-8ca5-5f9813edeec6">

</details>

### Additional Information

Tested in Safari Version 17.2 (19617.1.16.11.2), and Chrome 119.0.6045.159

**Comment by Chinaski1** [comment]
Internal ID: AGDNS-1726

**Comment by Chinaski1** [comment]
Fixed
