### ISSUE TITLE
mejorar servidores dns

### ISSUE THREAD

**Issue by 0072002** [AdguardTeam/AdGuardDNS#695]
### Platform

Router

### Protocol

Regular

### Do you use AdGuard app?

No I don't

### Your configuration

estoy usado los dns de adguard en mi router wifi estos dns uso 94.140.14.14 94.140.15.15

### Traceroute to AdGuard DNS

94.140.14.14
94.140.15.15

### Issue Details

hola los servidores dns de adguard son lentos muy lentos me pone lento el wifi hogar, lo unico por lo que los uso es por que bloquean publicidad pero en tema de velocidad a la hora de navegar en wifi hogar es muy lento demasiado lento todo carga lento esto es problema de los servidores dns que adguard debe solucionar lo antes posible ya que los servidores dns son lentos al ver netflix, youtube en 4k y carga muy lento al abrir paginas web, falta que mejoren los dns en las siguientes cosas:
dejo lo que debe mejorar los dns adguard 94.140.14.14 94.140.15.15 deven mejorar en lo siguiente LEER BIEN Y MEJORAR ESTE MES NOVIEMBRE LOS SERVIDORES DNS

1: mejorar rendimiento
2: mejorar fluidez
3 mejorar latencia
4: bajar el ping
5:tener ubicación en pais chile y servidor en chil🇨🇱
6: hacer que adguard sea mas rápido que otros dns como cloudflare y google, hacer que adguard sea rapido a la hora de ver netflix y youtube en 4K.
7: que adguar sea el servidor dns mas rapido en latinoamerica pais chile🇨🇱 el numero 1🥇mas rapido del mundo que acelere internet fibra optica 100% veloz 24/7 en todo el mundo y en latinoamerica🇨🇱

mi idea es que adguar sea ultra veloz en chile a la hora de navegar en internet wifi hogar que al momento de poner 9.140.14.14 94.140.15.15 mi internet wifi valla ULTRA VELOZ 24/7 CON MENOR PING Y MEJOR LATENCIA Y MAYOR VELOCIDAD MBPS 

ESPERO QUE ENTIENDAN MI IDEA DE LO QUE ME GUSTARIA QUE MEJOREN EN LOS DNS DE ADGUARD LO ANTES POSIBLE ESTE 2023.

### Expected Behavior

Esperaba que andguard fuera dns rapido a la hora de ver videos de larga duracion en 4k sin importar dispositivo que no ponga internet lento y los videos 4k cargen rapido y paginas web cargen rapido mejor rendimiento etc..

### Actual Behavior

Los dns se ponen lento en chile son los dns mas lento que e probado ponen lento la fibra optica en latinoamerica pais chile

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

hola los servidores dns de adguard son lentos muy lentos me pone lento el wifi hogar, lo unico por lo que los uso es por que bloquean publicidad pero en tema de velocidad a la hora de navegar en wifi hogar es muy lento demasiado lento todo carga lento esto es problema de los servidores dns que adguard debe solucionar lo antes posible ya que los servidores dns son lentos al ver netflix, youtube en 4k y carga muy lento al abrir paginas web, falta que mejoren los dns en las siguientes cosas:
dejo lo que debe mejorar los dns adguard 94.140.14.14 94.140.15.15 deven mejorar en lo siguiente LEER BIEN Y MEJORAR ESTE MES NOVIEMBRE LOS SERVIDORES DNS

1: mejorar rendimiento
2: mejorar fluidez
3 mejorar latencia
4: bajar el ping
5:tener ubicación en pais chile y servidor en chil🇨🇱
6: hacer que adguard sea mas rápido que otros dns como cloudflare y google, hacer que adguard sea rapido a la hora de ver netflix y youtube en 4K.
7: que adguar sea el servidor dns mas rapido en latinoamerica pais chile🇨🇱 el numero 1🥇mas rapido del mundo que acelere internet fibra optica 100% veloz 24/7 en todo el mundo y en latinoamerica🇨🇱

mi idea es que adguar sea ultra veloz en chile a la hora de navegar en internet wifi hogar que al momento de poner 9.140.14.14 94.140.15.15 mi internet wifi valla ULTRA VELOZ 24/7 CON MENOR PING Y MEJOR LATENCIA Y MAYOR VELOCIDAD MBPS 

ESPERO QUE ENTIENDAN MI IDEA DE LO QUE ME GUSTARIA QUE MEJOREN EN LOS DNS DE ADGUARD LO ANTES POSIBLE ESTE 2023.

**Comment by D13410N3** [comment]
There is no need in a new issue
https://github.com/AdguardTeam/AdGuardDNS/issues/693#issuecomment-1828417800
