### ISSUE TITLE
Query log UI bug for devices dropdown

### ISSUE THREAD

**Issue by kyjhoz-mikfip-goXci0** [AdguardTeam/AdGuardDNS#696]
### Platform

Other

### Protocol

Regular

### Do you use AdGuard app?

No I don't

### Issue Details

When creating a second server for my TV and selecting that device in the query log it seems to show the selected TV in the top left of the Devices box.

### Actual Behavior

When creating a second server for my TV and selecting that device in the query log it seems to show the selected TV in the top left of the Devices box.

### Screenshots

<details><summary>Screenshot 1:</summary>

<img width="1228" alt="Screenshot 2023-11-29 at 10 05 16" src="https://github.com/AdguardTeam/AdGuardDNS/assets/149243371/08541037-dae5-419e-bdb8-53e2fbf9e5bb">

</details>

**Comment by Chinaski1** [comment]
Fixed
