### ISSUE TITLE
Suboptimal routing from Stockholm to Frankfurt

### ISSUE THREAD

**Issue by 0x9fff00** [AdguardTeam/AdGuardDNS#698]
### Platform

Linux

### Protocol

DNS-over-HTTPS

### Do you use AdGuard app?

No I don't

### Traceroute to AdGuard DNS

```
traceroute to 94.140.14.14 (94.140.14.14), 30 hops max, 60 byte packets
 1  10.0.1.1 (10.0.1.1)  0.398 ms  0.266 ms  0.244 ms
 2  gw13.A465.priv.bahnhof.se (217.31.190.1)  1.418 ms  1.388 ms  1.276 ms
 3  172.18.65.40 (172.18.65.40)  4.270 ms  4.350 ms 172.18.65.38 (172.18.65.38)  4.521 ms
 4  * * *
 5  a465-gw-c.bahnhof.net (46.59.118.215)  6.016 ms  5.965 ms  5.882 ms
 6  a465-gw.bahnhof.net (46.59.118.214)  1.373 ms  2.294 ms  2.340 ms
 7  sto-cr3.sto-cr1.bahnhof.net (46.59.112.158)  2.971 ms  3.044 ms  2.641 ms
 8  sto5-er1.se.bahnhof.net (85.24.220.18)  2.581 ms 85.24.220.17 (85.24.220.17)  2.113 ms  2.062 ms
 9  xe-2-0-7-0.sth10.core-backbone.com (194.68.128.117)  2.362 ms netnod-ix-ge-a-sth-1500.core-backbone.com (194.68.123.117)  2.397 ms  2.349 ms
10  ae13-2081.fra10.core-backbone.com (80.255.14.193)  22.037 ms  21.958 ms  21.836 ms
11  coreb-fra.cdn77.com (169.150.195.68)  26.142 ms  25.741 ms  25.734 ms
12  vl217.fra-cyx2-dist-2.cdn77.com (169.150.194.51)  26.087 ms vl215.fra-cyx2-dist-1.cdn77.com (169.150.194.49)  26.261 ms vl217.fra-cyx2-dist-2.cdn77.com (169.150.194.51)  26.087 ms
13  dns.adguard.com (94.140.14.14)  26.307 ms  26.079 ms  26.026 ms
```

### Issue Details

I'm in Stockholm and used to be routed to the Stockholm server but recently (for at least a few weeks) I've been routed to Frankfurt instead.

### Expected Behavior

I should be routed to Stockholm

### Actual Behavior

I'm being routed to Frankfurt (`dns2-dp-fra-5`)

### Additional Information

It seems like there is a route to the Frankfurt server (via Core-Backbone) on the Netnod Stockholm IX but no route to the Stockholm server, so my ISP (Bahnhof) prefers the peering route to Frankfurt over transit to Stockholm.

**Comment by D13410N3** [comment]
Hello. As you have mentioned earlier, it depends on your ISP, which has transit via CBB. CBB prefers its own backbone. Anyway, you have good results and it shouldn't affect you much
