### ISSUE TITLE
rutracker.org - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardDNS#7]
![image](https://cloud.githubusercontent.com/assets/15856304/17165979/d03fc76a-53dc-11e6-95fa-57479b49d71f.png)

<details>
![image](https://cloud.githubusercontent.com/assets/15856304/17165985/def05aae-53dc-11e6-839d-25c94b8920df.png)
![image](https://cloud.githubusercontent.com/assets/15856304/17165991/eaa5b95c-53dc-11e6-946a-ba7cf031bcb1.png)
![image](https://cloud.githubusercontent.com/assets/15856304/17165997/f1eca8ec-53dc-11e6-8661-d4b60f3043e8.png)

</details>
DNS прописаны в
роутере (чистку кеша браузера и dns делал)
952965

**Comment by Alex-302** [comment]
Добавлено в фильтр DNS
```
||rutrk.org^
||t.insigit.com^
||traffichunt.com^
||sportbets.su^
```
