### ISSUE TITLE
FBWAT.CH blocked as malicious

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardDNS#70]
Hello,

looks like this domain has been blocked by your DNS as malicious, but it is not so. This is real Facebook domain with the their video and streaming service:
https://www.facebook.com/watch/

Look at DNS output and make sure of it:
https://centralops.net/co/NsLookup.aspx?domain=fbwat.ch&type=255&server=8.8.8.8&class=1&port=53&timeout=5000&advanced=true

Thank you.

**Comment by Alex-302** [comment]
I can't reproduce. Please show your local nslookup(or similar tool) result.

**Comment by ammnt** [comment]
> I can't reproduce. Please show your local nslookup(or similar tool) result.

I actually already change my dns back to quad9, so:
```
; <<>> DiG 9.11.3-1ubuntu1.11-Ubuntu <<>> @176.103.130.130 fbwat.ch
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 54047
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 61779cbbccede110 (echoed)
;; QUESTION SECTION:
;fbwat.ch.                      IN      A

;; ANSWER SECTION:
fbwat.ch.               3600    IN      A       176.103.130.133

;; Query time: 42 msec
;; SERVER: 176.103.130.130#53(176.103.130.130)
;; WHEN: Mon Jan 27 11:44:04 MSK 2020
;; MSG SIZE  rcvd: 65
```

and:

```
nslookup fbwat.ch 176.103.130.130
Server:         176.103.130.130
Address:        176.103.130.130#53

Non-authoritative answer:
Name:   fbwat.ch
Address: 176.103.130.133
```
176.103.130.133 - IP-address of your stub. Thank you.

**Comment by Alex-302** [comment]
Strange. It does not exists in filters, and AdGuard Home does not block it.

**Comment by ammnt** [comment]
> Strange. It does not exists in filters, and AdGuard Home does not block it.

Also blocked by my AGH server and application for mac:
https://yadi.sk/i/x3eJ3Y-WLHtjnA

**Comment by Alex-302** [comment]
Hmm.
@Chinaski1 please take a look.

**Comment by ammnt** [comment]
Works fine now. Thanks, guys!
