### ISSUE TITLE
bnc.lt

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardDNS#70]
bnc.lt should be added to exceptions. Looks like a lot of apps use it as their cname.
![img_2849](https://cloud.githubusercontent.com/assets/15130139/19622015/2271bc88-9865-11e6-8bd2-274983327b23.PNG)

**Comment by jo2dan23** [comment]
Also blocks http://m.varagesale.com/m/GTcJpM

**Comment by Alex-302** [comment]
Added to DNS filter
```
@@||bnc.lt^
```
