### ISSUE TITLE
Increase number of User rules or data

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardDNS#702]
### Issue Details

Hello. We currently have a limit of 1000 rules. It's not as much as it seems.

### Proposed solution

I suggest changing the limit and basing it on the size of the user rules data. For example, 300,000 rules will take up about 7MB of data. I propose to discuss the 10MB limit.

### Alternative solution

Ability to download custom filters from trusted sources (GitHub, GitLab, GIST etc.}.

**Comment by Chinaski1** [comment]
Hello there!
We are just planning changes regarding custom rule limits in an upcoming update.
Stay tuned.

**Comment by ameshkov** [comment]
The rules limit will be linked to the tariff plan.

> I propose to discuss the 10MB limit.

It's unsustainable. We run AdGuard DNS on 32GB RAM servers. Consider us having 1000 users with 10MB user rules, they'll take too much of a server's memory.
