### ISSUE TITLE
Message showing 'Not enough data Continue using your device to see statistics here' under 'Requests, last 24 hours'

### ISSUE THREAD

**Issue by kyjhoz-mikfip-goXci0** [AdguardTeam/AdGuardDNS#704]
### Platform

macOS

### Protocol

DNS-over-HTTPS

### Do you use AdGuard app?

Yes I am

### Issue Details

Navigate to https://adguard-dns.io/en/dashboard/statistics/general?retention=HOURS_24, and view the 24hr statistics bar chart.

### Expected Behavior

I am not sure if anything is meant to be there from memory, but I'm pretty sure 53k requests in 24h is ample for whatever is meant to be displayed there.

### Actual Behavior

Message showing 'Not enough data Continue using your device to see statistics here' under 'Requests, last 24 hours'.

### Screenshots

<details><summary>Screenshot 1:</summary>

<img width="1187" alt="Screenshot 2023-12-15 at 21 45 21" src="https://github.com/AdguardTeam/AdGuardDNS/assets/149243371/f6b1d6f5-9b42-4c9d-92ce-f358913fab06">

</details>

**Comment by Chinaski1** [comment]
Internal ID: AGDNS-1820

**Comment by Chinaski1** [comment]
Fixed
