### ISSUE TITLE
Requests from China routed to Amsterdam, causing up to 200ms delays

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdGuardDNS#706]
### Platform

Windows

### Protocol

Regular

### Do you use AdGuard app?

No I don't

### Your configuration

On a router

### Traceroute to AdGuard DNS

Not posting here as we don't have permission from the user. See the 844198 ticket in the CRM system.

### Issue Details

I'm a user of Adguard DNS personal plan in China mainland. But I found it always has a high lag (150-200ms) when ping the DNS server (ip or domain).  Is there any ip or domain I can use that have a lower lag in China?

### Actual Behavior

There are closer servers

### Screenshots

<details><summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdGuardDNS/assets/15856304/3895766e-370f-4c74-b651-eb541ec309db)

</details>

**Comment by D13410N3** [comment]
Unicom prefers its backbone (which contains Europe) as the more preferable way. At this moment there are now ways to fix this behaviour
