### ISSUE TITLE
IPv6 addresses cut off in query log and statistics top clients page on desktop

### ISSUE THREAD

**Issue by kyjhoz-mikfip-goXci0** [AdguardTeam/AdGuardDNS#708]
All my devices have IPv6 addresses, and none of them fit within the size limits which isn't much use when scanning a page of IP addresses.

It would be good to improve this to show the full address rather than have all IPv6 addresses cut off.

<img width="1189" alt="Screenshot 2023-12-19 at 18 08 54" src="https://github.com/AdguardTeam/AdGuardDNS/assets/149243371/d08fd4f3-454d-45fa-abfb-3d1de7fe07be">

**Comment by Chinaski1** [comment]
Unfortunately, we are unlikely to be able to show the full IPv6 address as it is too long for these fields.
But for your convenience, you can point to the tooltip and copy the full IP address from there.
