### ISSUE TITLE
Add 'Added Blocklists' to the top of the 'Manage Blocklists' page

### ISSUE THREAD

**Issue by kyjhoz-mikfip-goXci0** [AdguardTeam/AdGuardDNS#709]
### Issue Details

When adding multiple blocklists, then wanting to remove those same blocklists it can be a chore scrolling up/down the page or typing in the name to find the ones which have been added.

### Proposed solution

Add all added blocklists to the top of the 'Manage Blocklists' page.

**Comment by Chinaski1** [comment]
Internal ID: AGDNS-1833

**Comment by Chinaski1** [comment]
We have changed the logic a bit, now all enabled filters will be displayed at the beginning of the list. But still we decided to leave the division by categories.
