### ISSUE TITLE
[Question] change DNS configuration on macOS

### ISSUE THREAD

**Issue by iDjay** [AdguardTeam/AdGuardDNS#71]
Where can I change my DNS configuration to DNS-over-TLS on macOS Catalina? Or in general see what the default configuration is?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by audip** [comment]
There are two ways to view the DNS server configuration on macOS:
 1. Go to `System Preferences` --> `Network` --> Hit `Advanced` next to the WiFi/Ethernet connection --> `DNS` tab --> list of DNS servers on left-hand side
 2. Open `Terminal` --> view contents of `hosts` file using `cat /etc/hosts`

From the https://github.com/AdguardTeam/AdGuardDNS/blob/master/README.md file, this suggest that Mozilla Firefox can be used for DNS-over-HTTPS or AdGuard Home product for DNS-over-TLS, those are the options for macOS users.

P.S. I'm in no way associated with AdGuard, but helping as an end-user
