### ISSUE TITLE
Google Play Store won't download

### ISSUE THREAD

**Issue by Smultie** [AdguardTeam/AdguardDNS#71]
Hi, 
first of all, thanks for this wonderful service.

I do have a small problem, which might've been mentioned before (can't find it though): the Google Play Store won't download with the DNS set at AdGuard.

**Comment by Alex-302** [comment]
Hi
Did you check it on Android or Windows?

**Comment by Smultie** [comment]
Oh, I'm sorry.
This was on Android

**Comment by Alex-302** [comment]
I can't reproduce.
Which IPs are you using?

**Comment by ameshkov** [comment]
@Alex-302 have you noticed that this is AG DNS repo?:)

@Smultie how have you set up AG DNS? Do you use some sort of a DNS changer app?

**Comment by Alex-302** [comment]
@ameshkov sure:) What's wrong?

**Comment by Smultie** [comment]
I'm using https://play.google.com/store/apps/details?id=com.burakgon.dnschanger

**Comment by Smultie** [comment]
The item just stays stuck at 'downloading' but nothing happens. 
Just happened again at home (wifi)

**Comment by ameshkov** [comment]
Now I got it, thank you! Unfortunately, this is a known Android issue:(.

DNS changer uses a VPN API in order to change DNS servers. Sometimes Android cannot handle it properly and it breaks "Download Manager" app.

The problem is that the bug is rare and random, that's why it is still open in Android's bug tracker.

**Comment by Smultie** [comment]
Thanks for the feedback. It's not really random at my phone though, it happens each and every time. Same goes for Gmail attachments. Unfortunately that makes the DNS servers, at least for me, pretty unusable at the moment. 

Are you talking about this bug report? https://code.google.com/p/android/issues/detail?id=33666

**Comment by ameshkov** [comment]
Yep, that's it, sometimes changing DNS servers with a VPN leads to a broken download manager.

**Comment by TPS** [comment]
Since not explicitly mentioned, the tracking issues are @: 

Android < N|7: https://github.com/AdguardTeam/AdguardForAndroid/issues/186
Android ≥ N|7: https://github.com/AdguardTeam/AdguardForAndroid/issues/597
