### ISSUE TITLE
Allow searching in the query log search box by ip address

### ISSUE THREAD

**Issue by kyjhoz-mikfip-goXci0** [AdguardTeam/AdGuardDNS#712]
### Issue Details

When tapping the block/queries links in the top clients section of the statistics page, it redirects you to the query log, automatically entering the IP address into the search box. Unfortunately searching by IP address doesn't work.

### Proposed solution

Allow searching by IP address in the search box.

**Comment by Chinaski1** [comment]
Internal ID: AGDNS-1755

**Comment by Chinaski1** [comment]
Oh that feature was added in v2.5.1 patch
Forgot to let you know :)
