### ISSUE TITLE
Unable to add multiple rules in Server Settings > Access Settings

### ISSUE THREAD

**Issue by kyjhoz-mikfip-goXci0** [AdguardTeam/AdGuardDNS#715]
Using the provided examples in Server Settings > Access Settings I am unable to add multiple entries to the Allowed Clients and Disallowed Clients text boxes.

<img width="567" alt="Screenshot 2023-12-19 at 18 50 08" src="https://github.com/AdguardTeam/AdGuardDNS/assets/149243371/fca85cf1-f8da-4c92-9606-98d7e066958c">

**Comment by Chinaski1** [comment]
Hello there!
You can only add one rule per line.

Examples:
- [Okay](https://uploads.adguard.org/Chinaskicjyva.png)
- [Not okay](https://uploads.adguard.org/Chinaskiy6hay.png)

**Comment by Chinaski1** [comment]
Also for better understanding of users we have added [placeholders](https://uploads.adguard.org/Chinaskiv2sur.png) with examples of domains and IP addresses.
