### ISSUE TITLE
500 error when trying to enable/disable any blocklist 

### ISSUE THREAD

**Issue by KnightmareVIIVIIXC** [AdguardTeam/AdGuardDNS#716]
### Platform

Windows

### Protocol

DNS-over-QUIC

### Do you use AdGuard app?

Yes I am

### Your configuration

I wasn't having the issue until I enabled the ! Title: CHN: anti-AD list. A regex entry was preventing AdGuard VPN from connecting so I added a rule for @@||slightcommunicativeinterconnectedness.xyz^ which fixed the VPN issue. I don't have any entries in the access settings section.

### Issue Details

Steps to reproduce issue:
1. Try to enable/disable/remove a list

### Expected Behavior

I expect to see the list enabled/disabled/removed from the list 

### Actual Behavior

Nothing happened when I clicked the remove and I'm getting the 500 error page when trying to disable a list.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Chinaski1** [comment]
Hello there!
Thank you for the report.
We're fixing it right now.

**Comment by Chinaski1** [comment]
Fixed!
