### ISSUE TITLE
Titles overlapping & Not Tidy

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardDNS#719]
### Platform

Other

### Protocol

Regular

### Do you use AdGuard app?

Yes I am

### Issue Details

NA

### Expected Behavior

Should be able to read titles Cleary. 

### Actual Behavior

Titles are over lapping.

### Screenshots

![Screenshot_20231220_213500_Samsung Internet](https://github.com/AdguardTeam/AdGuardDNS/assets/96619913/dfb67a3d-6e06-443c-ac80-456111b04e45)
![Screenshot_20231221_195110_Samsung Internet](https://github.com/AdguardTeam/AdGuardDNS/assets/96619913/2e3dc19a-81ea-4099-9cfd-464a8972cc7f)
![Screenshot_20231222_183446_Samsung Internet](https://github.com/AdguardTeam/AdGuardDNS/assets/96619913/52404098-54bb-412b-b803-69be8cad74ce)
![Screenshot_20231222_212931_Samsung Internet](https://github.com/AdguardTeam/AdGuardDNS/assets/96619913/bb8d41c0-a453-4216-a99b-535fef422733)

**Comment by Chinaski1** [comment]
Internal ID: AGDNS-1841

**Comment by Chinaski1** [comment]
Fixed
