### ISSUE TITLE
Dota 2 game - ping increases using Adguard DNS

### ISSUE THREAD

**Issue by Fridrix** [AdguardTeam/AdguardDNS#72]
DNS configured through the router.
Provider Таттелеком
Ping increases from 40 to 80

Traceroute screenshots
Disabled DNS
<details>
![image](https://cloud.githubusercontent.com/assets/20476168/19653740/4b27fe7a-9a1e-11e6-89a7-d56b32d99d2d.png)
</details>
Enabled
<details>
![image](https://cloud.githubusercontent.com/assets/20476168/19653780/70db8588-9a1e-11e6-99b8-4f57a1ba829f.png)
</details>

ID 1071591

**Comment by ameshkov** [comment]
@Fridrix we need to see trace to Adguard DNS servers (.130 and .131) as well.

**Comment by sandybeachit** [comment]
@Fridrix is this still an issue?

**Comment by vozersky** [comment]
looks like an obsolete issue
we've requested more data from the user, will be reopened if still exists
