### ISSUE TITLE
Wrong ECS is sent by the London resolver

### ISSUE THREAD

**Issue by ardel** [AdguardTeam/AdGuardDNS#721]
### Platform

Other

### Protocol

Regular

### Do you use AdGuard app?

No I don't

### Issue Details

London resolver(s) send Romanian ECS when resolving. This leads to Romanian IP addresses returned by the authoritative servers.

### Expected Behavior

I believe for privacy reasons there should be **no** ECS data sent

### Actual Behavior

```
$ dig +short o-o.myaddr.l.google.com TXT @94.140.14.14
"195.181.164.46"
"edns0-client-subnet 217.156.84.0/24"
```
```
$ dig +noall +add id.server CH TXT @94.140.14.14
;; Warning: Message parser reports malformed message packet.
client-ip.adguard-dns.com. 3600 CH      TXT     "<redacted>"
server-ip.adguard-dns.com. 3600 CH      TXT     "94.140.14.14"
country.adguard-dns.com. 3600   CH      TXT     "GB"
asn.adguard-dns.com.    3600    CH      TXT     "25369"
subdivision.adguard-dns.com. 3600 CH    TXT     "ENG"
resp.res-type.adguard-dns.com. 3600 CH  TXT     "normal"
```

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Chinaski1** [comment]
Hello there!

Perhaps this behavior can still be called normal because the ECS algorithm is constantly changing and improving. Such situations are acceptable.
Soon we plan to publish a blog article that will shed light on the details of EDNS operation.

Thank you for report.
