### ISSUE TITLE
AdGuard DNS + Arc Browser

### ISSUE THREAD

**Issue by K-Vers** [AdguardTeam/AdGuardDNS#722]
### Platform

macOS

### Protocol

DNS-over-HTTPS

### Do you use AdGuard app?

No I don't

### Your configuration

Paid AdGuard DNS subscription with AdGuard DNS-Filter enabled.

### Traceroute to AdGuard DNS

dns2-dp-fra-16

### Issue Details

1. set up AdGuard DNS system wide on your Mac via profile
2. download and install Arc https://arc.net
3. go to AdGuard's test page https://adguard.com/en/test.html -> conncted
4. go to a website with ads f.e. https://www.speedtest.net -> ads are not getting blocked

### Expected Behavior

Ads should be blocked in Arc

### Actual Behavior

Ads are not blocked

### Screenshots

<details><summary>Screenshot 1:</summary>
<img width="938" alt="Bildschirmfoto 2023-12-30 um 11 25 06" src="https://github.com/AdguardTeam/AdGuardDNS/assets/155230340/6f58b758-b37a-465d-b2cb-5795c5df0ac6">
<img width="1042" alt="Bildschirmfoto 2023-12-30 um 11 25 23" src="https://github.com/AdguardTeam/AdGuardDNS/assets/155230340/83fb4bc8-9ec4-46f3-a93c-4bc4d58a6af8">

</details>

**Comment by Chinaski1** [comment]
Hello there!

- Does the issue reproduced in a other browsers browser?
- What filters are enabled?

I checked the issue you mentioned in Chrome browser and did not encounter any ads

**Comment by Chinaski1** [comment]
Closed due not reply
