### ISSUE TITLE
EDNS Client Subnet (ECS) from wrong location

### ISSUE THREAD

**Issue by cherinyy** [AdguardTeam/AdGuardDNS#724]
### Platform

Windows

### Protocol

Regular

### Do you use AdGuard app?

No I don't

### Traceroute to AdGuard DNS

![image](https://github.com/AdguardTeam/AdGuardDNS/assets/9050713/e5c800d9-24df-45c3-99a1-c02d5a6631dc)

### Issue Details

```
dig @unfiltered.adguard-dns.com whoami.ds.akahelp.net TXT

; <<>> DiG 9.16.45 <<>> @unfiltered.adguard-dns.com whoami.ds.akahelp.net TXT
; (4 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 16202
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 0
;; QUESTION SECTION:
;whoami.ds.akahelp.net.         IN      TXT

;; ANSWER SECTION:
whoami.ds.akahelp.net.  47      IN      TXT     "ecs" "2c0f:f7a8:8211::/56/56"
whoami.ds.akahelp.net.  47      IN      TXT     "ns" "84.17.44.209"
whoami.ds.akahelp.net.  47      IN      TXT     "ip" "84.17.44.209"

;; Query time: 184 msec
;; SERVER: 2a10:50c0::2:ff#53(2a10:50c0::2:ff)
;; WHEN: Sun Jan 07 05:28:25 ;; MSG SIZE  rcvd: 145
```

### Expected Behavior

Covered ECS are at least accurate to the state.

### Actual Behavior

Covered ECS are from different states.

### Additional Information

According to [data published by Hurricane Electric](https://bgp.he.net/AS4134#_prefixes6 "AS4134 China Telecom Backbone - bgp.he.net"), `240e::/20` is used in the Chinese mainland. I don't know why you are using the IP segment `2c0f:f7a8:8211::/48` from South Africa for coverage.

**Comment by Chinaski1** [comment]
Hello there!

Perhaps this behavior can still be called normal because the ECS algorithm is constantly changing and improving. Such situations are acceptable.
Soon we plan to publish a blog article that will shed light on the details of EDNS operation.

Thank you for report
