### ISSUE TITLE
Only 1000 user rules in Personal subscription?

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdGuardDNS#726]
This seems to be the only limit that _didn't_ increase when I upgraded to Personal.  Is that note correct?

**Comment by ameshkov** [comment]
Well, before v2.4 everyone had 1000 rules limit. Now we changed it so free users have 100 rules limit, paid have 1000, and team/enterprise plan may go up to 50000.

Tbh, user rules is quite an issue considering the number of registered users and having higher limits for everyone (even for just the paid users) will be very expensive.

**Comment by TPS** [comment]
I think it'd be sensible to put that limit (along w/ whatever others are missing) on the Dashboard Home page & directly make Upgrade comparisons more explicit.

_(I've been trying to sync my AGA licensed DNS rules w/ AGW licensed & AGDNS [free originally, recently Personal], so that's why it's been ~200.  I must've missed the transition in the middle of all that.)_

**Comment by ameshkov** [comment]
Hm, we did put it to the license page: https://adguard-dns.io/en/license.html

**Comment by TPS** [comment]
Sure, but that's effectively for people not using AGDNS.  For those of us already invested, you'd like them to upgrade, right?  That's what that Dashboard page _does_.  It's why _I_ did.

**Comment by ameshkov** [comment]
Why, it's there too:

![image](https://github.com/AdguardTeam/AdGuardDNS/assets/5947035/f62328e0-befc-4859-8326-6d5b269c3d8a)

**Comment by TPS** [comment]
I mean the main screen right before that, in here:![AGDNS Dashboard list.png](https://github.com/user-attachments/assets/8ad5b09d-5ec6-47dd-b11b-0ab62fefe620)

That 1 section when I kept hitting a limit is what did it for me.
