### ISSUE TITLE
AdGuard Private DNS account page not loading when signing in.

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardDNS#730]
### Platform

Other

### Protocol

Regular

### Do you use AdGuard app?

Yes I am

### Issue Details

Not loading when logging in.

### Expected Behavior

Should load paged to see you account statistics 

### Actual Behavior

AdGuard DNS account page not loading on devices in any browsers. Such as windows, samsung devices, and Apple devices.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by ameshkov** [comment]
There is an ongoing incident: https://status.adguard.com/incidents/t7zj3p40chf6
