### ISSUE TITLE
AdGuard DNS routing me via Japan, rather than Central America

### ISSUE THREAD

**Issue by enakr** [AdguardTeam/AdGuardDNS#731]
### Issue Details

> 1. Country: Honduras, Region: Central America
> 2. ISP: Cable Color
> 
> I asked my ISP about the routing to the near server, and they said that they don't have control over that, they said their systems are configured to provide the best possible experience based on industry defaults.
> 
> A simple online DNS leak test shows that I'm using DNS servers in Japan, that has to be the reason why my DNS queries are so slow, but this started happening after I signed up and configured a new server, with the free AdGuard Cloud DNS tier I didn't have slow queries they were almost as good as Nextdns and ControlD using the same filter lists.

Please check **ID 861093** for traceroutes.

**Comment by Chinaski1** [comment]
Hello there!

AdGuard DNS uses [Anycast](https://adguard-dns.io/en/blog/anycast-and-bgp-how-adguard-dns-serves-millions-of-queries.html) technology so we can't manage traffic routing 100% of the time.

At this point, we're compiling problems in internal list with the possibility of their correction in nearest future.
Please provide following information via email to support@adguard.com (also share a link to this issue on GitHub):

1) Your IP address: https://adguard.com/en/test.html
2) ASN. 
3) Provider name.
4) DNS server location: https://adguard.com/en/test.html

I am closing this task as it goes to the internal list of routing issues.
