### ISSUE TITLE
Aduard dns subsciption out of range on safari

### ISSUE THREAD

**Issue by miixms** [AdguardTeam/AdGuardDNS#733]
### Platform

macOS

### Protocol

Regular

### Do you use AdGuard app?

Yes I am

### Your configuration

![image](https://github.com/AdguardTeam/AdGuardDNS/assets/149260892/a24434a7-b952-4db2-8ef0-e8e9b8f09f87)

### Issue Details

fix the out of range thing

### Actual Behavior

correct the range

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Chinaski1** [comment]
Internal ID: AGDNS-1893

**Comment by Khald4615** [comment]
733
