### ISSUE TITLE
AdGuard DNS ipv6 routing me via Johannesburg, instead of London or Europe #731

### ISSUE THREAD

**Issue by enakr** [AdguardTeam/AdGuardDNS#734]
### Issue Details

> Hi,
> Please, could you improve the ipv6 routing for my location?  With ipv4 I get 10-20ms latency, but with ipv6 it's consistently well over 100ms.
> I am in the UK (Manchester area), 
> My ISP is BT.
> The test on the website showed that I'm using DNS servers in Johannesburg. 

Please check ID **865935** for tracerts.

**Comment by Chinaski1** [comment]
Hello there!

AdGuard DNS uses [Anycast](https://adguard-dns.io/en/blog/anycast-and-bgp-how-adguard-dns-serves-millions-of-queries.html) technology so we can't manage traffic routing 100% of the time.

At this point, we're compiling problems in internal list with the possibility of their correction in nearest future.
Please provide following information via email to support@adguard.com (also share a link to this issue on GitHub):

1) Your IP address: https://adguard.com/en/test.html
2) ASN. 
3) Provider name.
4) DNS server location: https://adguard.com/en/test.html

I am closing this task as it goes to the internal list of routing issues.
