### ISSUE TITLE
Question about IOS-profile security

### ISSUE THREAD

**Issue by donald2612** [AdguardTeam/AdGuardDNS#737]
Hello!

I am wondering, after I've tested DNS-queries with an app called "Net Analyzer" 

During this test I was only connected to my mobile carrier. The app did not use the installed AdGuardDNS-profile from the profile constructor, but instead was able to talk directly with the carriers DNS.

This app may be able to do this because of evelated rights it somehow has, but I did not not give any permissions to it. The question that arises can be already be guessed. When this app can talk directly to DNS, can every other app do this as well?

Or does Apple have secret permission structures, that I do not know of?

**Comment by ameshkov** [comment]
Does this Net Analyzer tool uses a local VPN approach to intercept the device traffic.

When there's an active VPN, iOS ignores DNS profile.

**Comment by donald2612** [comment]
No VPN used, the tool examines the network adapter of the cellular-IF and uses the shown carrier DNS:
![grafik](https://github.com/AdguardTeam/AdGuardDNS/assets/57543527/2d25e3a0-ccfd-4421-a0e7-7506159896a7)

**Comment by donald2612** [comment]
"ISC Dig" is freeware and does also do this:
![grafik](https://github.com/AdguardTeam/AdGuardDNS/assets/57543527/65039278-aa0c-4b38-877e-1757d0e3d1b7)

**Comment by ameshkov** [comment]
DNS profile does not change the interface settings.

As far as I understand, when DNS profile is used all requests that use `NSURLSession` API will use the DNS profile for the lookups. Low-level code won't be routed there so dig will still use the interface's DNS settings.

**Comment by donald2612** [comment]
Good to know, I really appreciate your comment!!

What concerns me most, is that with DOH coming from our own apps, we will lose any filtering technique that can be done without lots of effort, and TV-sets that even use private-VPN to talk to their servers. What a dark future - and it can't be avoidable... I guess the war with this has just begun but we are still in team Green for now...
