### ISSUE TITLE
Private DNS server does not work on mobile Internet

### ISSUE THREAD

**Issue by jellizaveta** [AdguardTeam/AdGuardDNS#741]
### Platform

Android

### Protocol

DNS-over-TLS

### Do you use AdGuard app?

No I don't

### System configuration

Information | Value
--- | ---
AdGuard product: | AdGuard DNS
DNS setup: | Device or router settings
DNS server: | Private AdGuard DNS server
System version: | android 9
Browser: | Samsung Browser
Blocklists: | <b>DNS:</b><br/>AdGuard DNS, <br/>Malicious URL Blocklist (URLHaus), <br/>Scam Blocklist by DurableNapkin, <br/>Phishing URL Blocklist (PhishTank and OpenPhish)

### Issue Details

When adguard dns is turned on, the mobile internet becomes unusable. AdGuard DNS works when configured through AdGuard on WiFi. 

### Expected Behavior

AdGuard DNS works when configured through network settings

### Actual Behavior

AdGuard DNS does not work when configured via network settings or configured via AdGuard on the mobile internet.

### Screenshots

<details>
  <summary>Screenshot 1</summary>

  [Screenshot 1](https://cdn.adguard.info/sitereports/pa5tioh4joggosws8gg0wkko0kw8s4w4fyplfov6cg.jpg?nc=1)
</details>
<details>
  <summary>Screenshot 1 with AdGuard disabled</summary>

  [Screenshot 1](https://cdn.adguard.info/sitereports/nqppmpse6zkkkk8gg08g00oc4ocsso0ciohglphqhw.jpg?nc=1)
</details>

### Additional Information

Related issue: https://github.com/AdguardTeam/AdguardFilters/issues/172671#issuecomment-1941230104
Username: @bogara

**Comment by Chinaski1** [comment]
@bogara
Please describe in more detail what method you use to configure AdGuard Private DNS on your phone.

**Comment by ameshkov** [comment]
Let's discuss it there real quick: https://github.com/AdguardTeam/AdguardFilters/issues/172671#issuecomment-1943415153

Yesterday there were some issues in Bulgaria as far as I know.

**Comment by bogara76** [comment]
> Please describe in more detail what method you use to configure AdGuard Private DNS on your phone.

I used DNS-over-TLS method
