### ISSUE TITLE
Incorrect routing via LA, US instead of Sydney, Australia

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardDNS#743]
Product: AdGuard DNS (paid)
Protocol: DoH
Application: Configuration profile
OS: iOS
Provider: [Belong Mobile](https://www.belong.com.au/)
Location: Sydney, Australia
Routing to: LA, US

Traceroute

![image](https://github.com/AdguardTeam/AdGuardDNS/assets/149243371/d080f9e9-2e3e-43ef-b43c-5f90a0b907d9)

![image](https://github.com/AdguardTeam/AdGuardDNS/assets/149243371/9f28de70-ca03-4767-8660-ffa749c5178e)

**Comment by Chinaski1** [comment]
Hello there!

AdGuard DNS uses [Anycast](https://adguard-dns.io/en/blog/anycast-and-bgp-how-adguard-dns-serves-millions-of-queries.html) technology so we can't manage traffic routing 100% of the time.

At this point, we're compiling problems in internal list with the possibility of their correction in nearest future.
Please provide following information via email to support@adguard.com (also share a link to this issue on GitHub):

1) Your IP address: https://adguard.com/en/test.html
2) ASN. 
3) Provider name.
4) DNS server location: https://adguard.com/en/test.html

I am closing this task as it goes to the internal list of routing issues.
