### ISSUE TITLE
AdGuard DNS is blocking access to my Roborock S7 via the iOS app

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardDNS#744]
### Platform

iOS

### Protocol

DNS-over-TLS

### Do you use AdGuard app?

No I don't

### Your configuration

Router: FritzBox 7590AX
Affected Device: Roborock S7
App: Roborock (iOS)

### Issue Details

1. Turn on encrypted DNS on Fritz!Box 7590AX
2. Add AdGuard DoT to Fritz!Box 7590AX
3. Open Roborock app on iOS
4. Roborock S7 can't be accessed via app
5. Turn off encrypted DNS on Fritz!Box 7590AX
6. Roborock S7 can be accessed immediately via app

### Expected Behavior

Roborock S7 can be accessed via Roborock app on iOS

### Actual Behavior

Roborock S7 can't be accessed via Roborock app on iOS

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

This issue has only been happening within the last month. It wasn't happening prior to this.

**Comment by Chinaski1** [comment]
Hello there!

I guess AdGuard DNS blocks advertising or tracking requests, which in turn causes connection problems between your phone and device. I found several similar references on [forums](https://www.reddit.com/r/Roborock/comments/zaoutz/connection_trouble_roborock_s7/) where users were complaining about a [related issue](https://uploads.adguard.org/Chinaskipgw7d.png).

I think you can try connecting to the device and then open the filtering log and see what domains are used when connecting. Maybe adding them to Allowlist solved the issue. In any case, you can experiment with filter lists and protocols of the servers used.

**Comment by Chinaski1** [comment]
Closed due not reply
