### ISSUE TITLE
Tracking links in adguard dns newsletter

### ISSUE THREAD

**Issue by pedrohgmacedo** [AdguardTeam/AdGuardDNS#745]
### Platform

Other

### Protocol

DNS-over-HTTPS

### Do you use AdGuard app?

No I don't

### Issue Details

I received an email newsletter advertising adguard dns version 2.6. 
However, I cannot access any of the links because I use adguard dns. 
The list “Peter Lowe’s Blocklist” has a filter with rule:
```
||email-link.adtidy.org^
```
Which prevents the following changelog tracking link in your email newsletter from loading:
```
https://email-link.adtidy.org/email.html?m=bx0xf9o901&l=pHV7VQQ0SyFjQ9xT6tzdpYvsASjS5al3LjKujfZBvTB6KQPpNIiF2NOA35CxWt85ZreMXFVdaiYV1T1exuO1Xc9qS6BkUQjQPD63gK0w9ZbSmK2F8mTCufe3ddKkjiGP6VaUAzJWcbF6EgKoLoHWMM5NBxHqyR1MALLPW4j2QPBm
```

I would like to request kindly that you provide a newsletter *without* any link tracking, so that your own customers of your dns product can access the changelog.
@ameshkov 

### Actual Behavior

I see this:
![image](https://github.com/AdguardTeam/AdGuardDNS/assets/118010672/e9e5a98a-9e02-4ca2-a02c-c8b81d5e9b4d)

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by ameshkov** [comment]
@pedrohgmacedo hi, you can disable it in AdGuard account: my.adguard.com

![image](https://github.com/AdguardTeam/AdGuardDNS/assets/5947035/422d25a8-23d3-4229-bc6e-dea391180318)

We generally want to know how many people click on links in emails and in the ideal case this should be achieved by using just a query parameter i.e. `?from=email_dns_2.6_en`. It's on our roadmap, but switching to this approach globally and replacing the old one requires time.

**Comment by pedrohgmacedo** [comment]
Done, thanks! Didn't know that option existed, honestly was just annoyed about not being able to open the link.
