### ISSUE TITLE
Failed to load websiste: mlbpark.donga.com

### ISSUE THREAD

**Issue by thonfive4** [AdguardTeam/AdGuardDNS#749]
### Platform

Android

### Protocol

Regular

### Do you use AdGuard app?

No I don't

### Your configuration

- Only use AdGuard DNS

### Issue Details

1. Go to this url: https://mlbpark.donga.com/mp/b.php?m=search&p=1&b=bullpen&id=202403090089963691&select=sct&query=%EC%A0%91%EC%86%8D&subselect=&subquery=&user=&site=donga.com&reply=&source=&pos=&sig=h6jBSY-1h3HRKfX2hfj9Gf-YKmlq

### Actual Behavior

Alert: Failed to load website

### Screenshots

![image](https://github.com/AdguardTeam/AdGuardDNS/assets/151705669/66f3cdb2-6e8a-423c-b155-e83d469701d6)

### Additional Information

https://mlbpark.donga.com/mp/b.php?m=search&p=1&b=bullpen&id=202403090089963691&select=sct&query=%EC%A0%91%EC%86%8D&subselect=&subquery=&user=&site=donga.com&reply=&source=&pos=&sig=h6jBSY-1h3HRKfX2hfj9Gf-YKmlq

**Comment by piquark6046** [comment]
@thonfive4 Resolved by https://github.com/AdguardTeam/AdGuardSDNSFilter/pull/1649.
To block Ad-Shield adverts, please install AdGuard for Android and microShield userscript.
https://community.list-kr.com/docs/AdGuard/Userscripts/microShield
