### ISSUE TITLE
Add safesearch support for `search.brave.com`

### ISSUE THREAD

**Issue by omarmohamedkh** [AdguardTeam/AdGuardDNS#751]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

Enforce safesearch for the brave search engine.

### Proposed solution

Add CNAME record for `search.brave.com` to `safe.search.brave.com`.

**Comment by Chinaski1** [comment]
Hello there!

I tried enabling safesearch in the brave browser by applying a rule:`|search.brave.com^$dnsrewrite=NOERROR;CNAME;safe.search.brave.com`

Perhaps this feature is not supported by the browser itself. Could you please specify if it works for you?

**Comment by omarmohamedkh** [comment]
I added the rule `||search.brave.com^$dnsrewrite=NOERROR;CNAME;safe.search.brave.com` and indeed it works.
Before:
```text
;; ANSWER SECTION:
search.brave.com.       360     IN      A       65.9.112.23
search.brave.com.       360     IN      A       65.9.112.112
search.brave.com.       360     IN      A       65.9.112.14
search.brave.com.       360     IN      A       65.9.112.117
```

After:
```
;; ANSWER SECTION:
search.brave.com.       10      IN      CNAME   safe.search.brave.com.
safe.search.brave.com.  160     IN      A       65.9.112.82
safe.search.brave.com.  160     IN      A       65.9.112.110
safe.search.brave.com.  160     IN      A       65.9.112.7
safe.search.brave.com.  160     IN      A       65.9.112.38
```

**Comment by Chinaski1** [comment]
Added at https://github.com/AdguardTeam/HostlistsRegistry/pull/521
Should be implemented to AdGuard DNS soon
