### ISSUE TITLE
DoH not enforcing youtube restricted mode

### ISSUE THREAD

**Issue by cruxoooo** [AdguardTeam/AdGuardDNS#753]
### Platform

Windows

### Protocol

DNS-over-HTTPS

### Do you use AdGuard app?

No I don't

### Your configuration

Firefox using DoH to custom Adguard DNS, Youtube restricted mode turned on under Parental Сontrol (adguard-dns.io/en/dashboard/settings/parental)

### Traceroute to AdGuard DNS

Tracing route to 94-140-14-49.adguard.com [94.140.14.49]
over a maximum of 30 hops:

  1    <1 ms    <1 ms    <1 ms  192.168.100.1
  2     *        *        *     Request timed out.
  3     *        *        *     Request timed out.
  4     *        *        *     Request timed out.
  5     *        *        *     Request timed out.
  6    25 ms    25 ms    25 ms  94-140-14-49.adguard.com [94.140.14.49]

### Issue Details

1. Copy custom DOH address from adguard-dns.io/en/dashboard/device/id to Firefox DoH settings
2. Opening Youtube expecting Restricted mode to be turned on

### Expected Behavior

Youtube with forced restricted mode 

### Actual Behavior

Youtube with no restricted mode

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

Other filtering settings work correctly. www.youtube.com is shown in statistics without the "Modified" status.

**Comment by Chinaski1** [comment]
Hello there!

I have checked the situation yo and can confirm described issue.
Will be fixed in next updates.

Internal ID: AGDNS-2043

**Comment by Chinaski1** [comment]
Fixed
