### ISSUE TITLE
The AdGuard diagnostics website is unable to detect AdGuard DNS on the Samsung Internet Tizen Browser on Samsung TV.

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardDNS#755]
### Platform

Other

### Protocol

Regular

### Do you use AdGuard app?

No I don't

### Your configuration

AdGuard Private Custom DNS has been configured on the Eero router.

### Issue Details

Step 1: Open the Samsung Internet Tizen Browser.
Step 2: Go to the AdGuard Services check page (AdGuard diagnostics) to see if it is connected to AdGuard Private DNS.

### Expected Behavior

The device should display a connection to AdGuard Private DNS.

### Actual Behavior

Shows nothing at all.

### Screenshots

![20240401_123641](https://github.com/AdguardTeam/AdGuardDNS/assets/96619913/c3ef1123-0825-44ae-aa03-684d512b7649)

### Additional Information

The Samsung TV model in question is QN4360AAFXZC. For reference, I have included a link to the product page.
https://www.samsung.com/ca/support/model/QN43Q60AAFXZC/#downloads

This application functions optimally on my Samsung Smart TV, model year 2022.
For your reference, I have included a link to the product in question.
https://www.samsung.com/ca/support/model/QN55QN90BAFXZC/#downloads

**Comment by ameshkov** [comment]
Tbh it looks like the Tizen Browser fails to render the page.

Could you please tell us what version of Tizen browser you have installed?

**Comment by Batman2814** [comment]
Could someone from AdGuard please provide an update on when this issue will be resolved? I have not received any response regarding this matter.

**Comment by Batman2814** [comment]
I am still waiting for this issue to be fixed. Any News?
