### ISSUE TITLE
I Get routed to Singapore from Canada when using Software Program Tixati when AdGuard VPN for Windows in enabled 

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardDNS#757]
### Platform

Windows

### Protocol

DNS-over-QUIC

### Do you use AdGuard app?

Yes I am

### Your configuration

AdGuard VPN for Windows is on a US Server location While Tixati Software program is open in background. 

### Traceroute to AdGuard DNS

Shown is screenshot

### Issue Details

Step 1: Open Tixati
Step 2: connect Adguard VPN for Windows to a US Server
step 3: go to AdGuard Services Check Page to find what server it connects to. 

### Expected Behavior

Should at least connect to the server on the same Continent around Canada

### Actual Behavior

AdGuard Server connects to servers worldwide, such as Singapore. It has also connected to Tokoyo before. 

### Screenshots

![20240402_10333132_Edited](https://github.com/AdguardTeam/AdGuardDNS/assets/96619913/206458bd-0489-4eee-ba7e-0fca6f3e83e9)
![20240402_10421571_Edited](https://github.com/AdguardTeam/AdGuardDNS/assets/96619913/336a9ed6-1376-4c27-ab9a-c82d638503d9)

**Comment by Chinaski1** [comment]
Hello there!

Using the AdGuard DNS + AdGuard VPN combination, you should not rely on roaming to the nearest connected locations. 
The mechanism becomes much more complicated which leads to connecting to not the closest VPN endpoin.

**Comment by Batman2814** [comment]
I would like to inquire about the optimal configuration for establishing a connection to the nearest location using AdGuard VPN. Specifically, I am interested in determining whether it is necessary to utilize AdGuard Public DNS or an alternative configuration to achieve this objective. Kindly provide guidance on the most effective approach to ensure a connection to the closest server.
