### ISSUE TITLE
startpage.com safesearch

### ISSUE THREAD

**Issue by cruxoooo** [AdguardTeam/AdGuardDNS#759]
### Issue Details

The safesearch feature on startpage.com is either not enforced or badly implemented because it can be easily bypassed by selecting "Safe Search: off" at the top of the page. On similar search engines with proper safesearch enforcement this setting is either not available (google) or not working (duckduckgo).

### Proposed solution

properly enforce safesearch on startpage.com or block the website

**Comment by ainar-g** [comment]
See https://github.com/AdguardTeam/HostlistsRegistry/pull/563#issuecomment-2493943887.  Seems like Start Page does not really support DNS-level forcing of safe search.

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/HostlistsRegistry/pull/563#issuecomment-2493943887
