### ISSUE TITLE
Consider creating a page for tracking DNS work and reporting bugs

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardDNS#76]
I would like to recommend a block page for Adguard DNS that shows when a
page/window/tab/et cetera is blocked, and that this block page will show
what blocked it and why it was blocked and have an option to report false
positives.

I have noticed that Adguard DNS seems to block some pop-up ads and
accidentally blocks some legitimate links when they try to open a new tab
or window, the tab or windows still open but they do not load, but there is
no block page to let you know what blocked it or why and you can not report
false positives.

**Comment by ameshkov** [comment]
We have such page for requests blocked by malware/phishing module and parental control.

The thing is that we'd prefer not to do it for blocked ad/tracking requests as it will create unnecessary load on our servers (billions additional web requests from all DNS users).

**Comment by evgeniy-ADG** [comment]
>Thank you for explaining that (you reasoning makes sense when you say it
that way), I hope that one day in the future it will be possible to know
for sure if a pop-up ad was blocked by Adguard DNS or not and why and to be
able to report false positives, but for now I will have to keep guessing
when a pop-up ad was blocked by Adguard DNS and I guess I will have
manually report every false positive by submitting a ticket each time?

**Comment by ameshkov** [comment]
> manually report every false positive by submitting a ticket each time?

Yep, unfortunately it's the only way:(

It would be much better to report it here on github, though.
