### ISSUE TITLE
Show error page when Adguard Personal DNS Server blocks a request rather than not loading it at all in browser

### ISSUE THREAD

**Issue by ashutoshsaboo** [AdguardTeam/AdGuardDNS#767]
### Issue Details

So I'm sure there are multiple usecases when we wish to access a site, which is originally blocked by our Adguard Personal Server DNS filters. For example, many login verification links such as discord/slack login links have certain trackers in them which are by default blocked by Adguard. But accessing them is important, else user won't be able to login at all to those services. Many links sent by newsletters in email also contain certain trackers, and usually they won't open at all in the browser because Adguard blocks them (and rightly so). But accessing them sometimes, can be important for the user. And Adguard should make it easier for the user to override the dns blocking settings to access the previously blocked page rather than go all the way into Adguard dns account and change the dns filter settings, or worst case just change the DNS server. Changing the DNS server for a temporary time just to access that website, doesn't make much logical sense and is bad UX - because user can forget switching DNS server to their personal DNS (which offers the highest security) soon after that. And that I believe won't be the right user experience, as Adguard won't be promoting the best security for DNS blocking for users.

Currently the way to do that is by changing the DNS server to say a non-filtering one to be able to access the site. This is too cumbersome. Rather, whenever a browser request is blocked by Adguard Personal DNS, Adguard should just render a custom error page saying this page was blocked due to their dns settings, and temporarily allow the option to override the blocking settings. I think Windscribe's Control D DNS provides for this feature if I'm not wrong. This will be really useful in setting for the highest security blocking filters in DNS settings, and still not facing any issues while browsing. The request is primarily for Adguard Personal DNS, but I think it'd be useful to extend it to the public Adguard DNS servers as well to have the same handling. 

For other requests that are not made by the browser, such as analytics requests made in background by the webpages - for such requests there's no need to show any error page (because browser wasn't requesting for them to be rendered, it was just a background request). I.e, this error page can be shown for just requests made explicitly by the browser to render something, and not for other background requests. Background requests can continue to be blocked as per each user's respective DNS filter settings.

I hope the team can consider for this request hopefully soon! 🙏 Else this causes too many issues in the daily browsing usage. 

### Proposed solution

whenever a browser request is blocked by Adguard Personal DNS, Adguard should just render a custom error page saying this page was blocked due to their dns settings, and temporarily allow the option to override the blocking settings. I think Windscribe's Control D DNS provides for this feature if I'm not wrong. This will be really useful in setting for the highest security blocking filters in DNS settings, and still not facing any issues while browsing. The request is primarily for Adguard Personal DNS, but I think it'd be useful to extend it to the public Adguard DNS servers as well to have the same handling. 

For other requests that are not made by the browser, such as analytics requests made in background by the webpages - for such requests there's no need to show any error page (because browser wasn't requesting for them to be rendered, it was just a background request). I.e, this error page can be shown for just requests made explicitly by the browser to render something, and not for other background requests. Background requests can continue to be blocked as per each user's respective DNS filter settings.

### Alternative solution

Can't think of any alternative solution.

**Comment by hagezi** [comment]
Please don't be the next service to introduce a block page, with some website and app implementations (bad design) it makes a difference whether the response is `0.0.0.0/NXDOMAIN/REFUSED` when resolving a domain or a valid IP of a block page. This causes problems where there are actually none and leads to domains having to be unblocked when the block page is switched on that would not normally have to be unblocked.

Prominent example: PayPal 2FA, see: https://github.com/hagezi/dns-blocklists/issues/2335

**Comment by ameshkov** [comment]
I don't like this idea either. If we do it on public DNS, it'll probably add 30-40% load to the servers.

For personal DNS one can always set it up themselves:
![image](https://github.com/AdguardTeam/AdGuardDNS/assets/5947035/793617c7-e52e-4b64-ad0f-6112de95b7f7)

Choose custom IP and point it to a blocking page.

**Comment by ashutoshsaboo** [comment]
> Please don't be the next service to introduce a block page, with some website and app implementations (bad design) it makes a difference whether the response is `0.0.0.0/NXDOMAIN/REFUSED` when resolving a domain or a valid IP of a block page. This causes problems where there are actually none and leads to domains having to be unblocked when the block page is switched on that would not normally have to be unblocked.
> 
> Prominent example: PayPal 2FA, see: [hagezi/dns-blocklists#2335](https://github.com/hagezi/dns-blocklists/issues/2335)

Not sure if I followed entirely, but if the block page were not on, then would you not have to still unblock the page if you wanted to access it? @hagezi

**Comment by ameshkov** [comment]
But generally I prefer to wait for this RFC to be adopted by major browsers:
https://datatracker.ietf.org/doc/draft-ietf-dnsop-structured-dns-error/08/

**Comment by ashutoshsaboo** [comment]
> I don't like this idea either. If we do it on public DNS, it'll probably add 30-40% load to the servers.
> 
> For personal DNS one can always set it up themselves: ![image](https://private-user-images.githubusercontent.com/5947035/325164204-793617c7-e52e-4b64-ad0f-6112de95b7f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NTEzNzMsIm5iZiI6MTcxMzk1MTA3MywicGF0aCI6Ii81OTQ3MDM1LzMyNTE2NDIwNC03OTM2MTdjNy1lNTJlLTRiNjQtYWQwZi02MTEyZGU5NWI3ZjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjRUMDkzMTEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjgwMjRjMWZkNzgwNGE2ZDIwMDBlMWVlMTM2ODU5M2FhNjk2MmRlYzA2ZWY5YzIwZDAzNmRhNjMxNTk5OTZiYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3GA0pXHF1vyI1FS_CmEu5FHW7m76M9-JsgfQ1KgGgRE)
> 
> Choose custom IP and point it to a blocking page.

Hmm I see. Is it possible to configure a page on the personal DNS, where if needed we can temporarily override DNS blocked pages as well, to access them? I think configuring an IP and all that is fine, but how to get this override functionality for the personal DNS? @ameshkov

**Comment by ameshkov** [comment]
Well, the problem is that you'll need to run your own blocking page (basically have a server on the internet).

You can use ours if you want: `94.140.14.36`

**Comment by ashutoshsaboo** [comment]
> 94.140.14.36

No i understood that, but a blocking page would only be a static page right. How do we add functionality to it, to override the DNS block and go to the necessary page (because that's what the entire usecase is - you can't even login to various services like discord/slack etc unless you temp unblock their tracker domains to verify the logins)? Any solution possible for that? Like in your page above as well, it just seems like a static block page. @ameshkov

**Comment by ashutoshsaboo** [comment]
Going to the personal DNS server settings each time to unblock it, isn't a practical option. :( Which is why was wondering if there's an alternative possible to suffice for the same usecase?

**Comment by ameshkov** [comment]
I don't fully understand what's the connection with the blocking page here.

Why can't you just unblock the tracker domains as usual?

**Comment by ashutoshsaboo** [comment]
> I don't fully understand what's the connection with the blocking page here.
> 
> Why can't you just unblock the tracker domains as usual?

Okay let me be specific. Some practical usecases mentioned below:

1. Sometimes your email newsletters contain links to various articles, which are embedded by trackers and hence normally wouldn't open as they are blocked by the dns filters. Normally you want them perma disabled, but once in a while you find a relevant article that you wish to read and want to access it. 
2. Services like discord sometimes send verification emails whenever it detects your ip is from a new location not previously accessed. These are embedded by discord's own trackers which are again normally blocked by default in any half-decent dns filter list. You don't want those discord trackers to be perma unblocked for obvious reasons, you just wish to go to that link one time to authorise your new ip so discord allows you to login. 

I'm sure you can already imagine, there can be multiple such practical usecases (not even in minority) where you want to just access some page by temp blocking a tracker but not perma unblocking it. 

In such cases you dont want to go to the dns page each time and unblock those trackers permanently. Today when I face this issue, I just change the dns server from my personal adguard dns to a non filtering one, to access that page and then switch it back to the personal adguard dns again. But this is not an ideal solution and has bad UX. I hope I was more clear now about the usecases that I'm talking about. Happy to clarify more if in case I was still not clear. 

If it's possible to say give a page when browser tries to access a dns blocked page: mentioning that this domain is blocked, but more importantly which also has an option to override the block and go to the actual page (without changing anything on the dns filters server-side for the personal dns server) - then that can help solve for such usecases. I'm not sure if this is technically possible though, to override dns filters on a one-time basis by clicking a button?

If in case that's not the best solution according to you, then can we think of an alternative to suffice for the same usecase? Because really such usecases I don't think are miniscule in number, and I'm sure even you (and others here too) would have seen them in many practical situations by now in your daily browsing?

I hope I was more clear now! Feel free to ask anything if I was still not as precise, happy to clarify more. @ameshkov

**Comment by ameshkov** [comment]
Oh, that will be quite a complicated thing to implement tbh.

There're two ways of implementing this change:
1. First is a "temporary unblock" which is almost impossible to make correctly because of the DNS cache, you still will need to wait quite some time for the record to be removed from the cache.
2. "Proxying" to the domain that you wanted to visit. Possible, but this is very resource intensive and expensive to run. Also very hard to implement it securely and reliably.

Tbh, I doubt any other DNS provider implements any of these.

**Comment by ashutoshsaboo** [comment]
> First is a "temporary unblock" which is almost impossible to make correctly because of the DNS cache, you still will need to wait quite some time for the record to be removed from the cache.

Since this request was in context of browsers, when say user clicks on the "temp unblock" button on the blocking page - why can't the unblocked page DNS be sent to the browser with a lower TTL (as low a TTL as possible) to provide as best a UX as possible? @ameshkov

**Comment by ameshkov** [comment]
> Since this request was in context of browsers specifically, when say user clicks on the "temp unblock" button on the blocking page - why can't the unblocked page DNS be sent to the browser with a lower TTL (as low a TTL as possible) to provide as best a UX as possible?

That's just not how DNS works, it's cached by the OS.

And having low TTL will negatively affect overall performance.

> And I believe it's fine even if it ends up being say a couple of mins really

Depends. On public DNS it's 1 hour, on personal DNS it's configurable, can be low (results in many extra queries though).

A couple of minutes is IMO really a lot.

**Comment by ashutoshsaboo** [comment]
> That's just not how DNS works, it's cached by the OS.

I meant I've changed DNS servers in the Adguard app on ios many times, and almost instantly I've seen those servers to serve dns requests per their new blocking rules almost instantly. Not seen too much latency there. Is there anything special that ios does, to reduce this latency when dns servers are changed? That is the place where I was coming from when I mentioned, if really the latency would be that high for the temp-unblock solution that you had proposed initially.


Hmm, so what solution do you suggest can we do to even partially solve for this? Since perma unblocking of these trackers is really not an option, it'd only be much worse off for the user's browsing security in general :( And you know even changing dns server temporarily - say switching to non filtered adguard server for accessing the resource that user wishes to access, and then switching back to adguard personal dns server again would easily take few mins as well. I can do this still easily on adguard ios, but for mac I prefer using the dns as deep baked in on the browser settings itself (so i can use it without adguard desktop app as well), and in that case changing browser based DNS isn't even easy. :( 

Can we please think of something to solve for this, even if partially? It causes quite a lot of issues in daily browsing from time to time really. :(
