### ISSUE TITLE
AdGuard private dns is down

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardDNS#769]
### Platform

Other

### Protocol

Regular

### Do you use AdGuard app?

Yes I am

### Issue Details

N/A

### Actual Behavior

N/A

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by ameshkov** [comment]
Could you please tell us what you see when you open `dns.adguard.com/info.txt`?

**Comment by Batman2814** [comment]
dns2-dp-chi-1

**Comment by ameshkov** [comment]
Hm, it should work if you're able to open it.

I see you also has some issues with VPN right? As I recall there's a big incident with Level3 (a tier-1 provider) and connectivity between US and Europe, it may be related.

**Comment by Batman2814** [comment]
Certainly. I am currently experiencing technical difficulties with the AdGuard VPN, however, it appears to have reestablished its connection.
