### ISSUE TITLE
Add "Adguard DNS filter" to the list of available filters in all AG versions

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardDNS#77]
@mmigi @Alex-302 

Name: `Adguard DNS`
Description: `Filter used by Adguard DNS`

We should also add it's description to "Filters" page:
https://adguard.com/filters.html

**Comment by ameshkov** [comment]
@vbagirov @mmigi  let's change filter description.

Name: `Adguard DNS filter`
Description: `Filter used by Adguard DNS. Basically, it is a compilation of English filter, Social filter, Spyware filter, Mobile ads filter, EasyList and EasyPrivacy, transformed for better `

Also do the following:
1. Supply a russian translation.
2. Fix description in the filter template file: https://github.com/AdguardTeam/AdguardDNS/blob/master/Filters/filter.template
3. Change filter's license to `http://creativecommons.org/licenses/by-sa/3.0/`
4. Add filters information to oneskyapp: https://adguard.oneskyapp.com/admin/phrase/list/project/14268/project-page/30394#?p=1&filter=all&k=

File `filters.properies`.

**Comment by vbagirov** [comment]
1. Done
2. Done
3. @mmigi will do it soon
4. Done

**Comment by jo2dan23** [comment]
If people use the adguard dns filter list it completely whitelists some sites that should only be whitelisted if someone is using the dns servers. For example scorecardresearch.com in the dns exceptions list, meaning it will be whitelisted completely when using the filter list. Anyway to disable that?

**Comment by mmigi** [comment]
3. Done !

**Comment by vbagirov** [comment]
@jo2dan23 no, as far as I know. Exception rules have priority over other rules, so if you have Adguard DNS filter enabled and there is an exception in it for some website, this website will be whitelisted no matter what other filters do you have.

**Comment by vbagirov** [comment]
Also, finished with 3), closing the issue.

**Comment by Bluscream** [comment]
@vbagirov You made a copy paste mistake on https://adguard.com/en/filters.html#dns

The `View all the rules` button links you to the "Adguard Safari Filter"

**Comment by ameshkov** [comment]
@jo2dan23 yep, you are absolutely right, thank you!

We should re-think the way filter is compiled. Instead of simply concatenating it with exceptions rules list, we should exclude whitelisted domains from it.

**Comment by vbagirov** [comment]
@Bluscream thanks, fixed now.
