### ISSUE TITLE
Notify user when configuration profile is expired

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardDNS#770]
### Issue Details

My configuration profile expired, and all DNS filtering stopped, which has taken me until this issue to work out what the cause is.

![IMG_0664](https://github.com/AdguardTeam/AdGuardDNS/assets/149243371/12c5b8c3-5e04-4c9e-8388-8c44b0a3e867)

### Proposed solution

Notify the user that the certificate will expire in a period of time coming up, and notify the user when the certificate has expired.

**Comment by ameshkov** [comment]
We should also figure out if we can generate profiles with a longer lifetime.

**Comment by ameshkov** [comment]
The problem is not in the cert itself, the profile is already signed and changing/renewing the cert does not change the profile.
