### ISSUE TITLE
Manual client address not being generated on dashboard

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardDNS#772]
### Platform

Android

### Protocol

DNS-over-TLS

### Do you use AdGuard app?

Yes I am

### Issue Details

Visit android device at https://adguard-dns.io/en/dashboard/configure/device, 
Select Configure AdGuard DNS manually,
Scroll down to step 3 where the address is meant to be generated

### Expected Behavior

Client address is generated

### Actual Behavior

Client address is not generated

### Screenshots

<details><summary>Screenshot 1:</summary>

![IMG_0677](https://github.com/AdguardTeam/AdGuardDNS/assets/149243371/e8b48c00-aa89-43db-bdc7-98611e25ec09)

</details>

**Comment by Chinaski1** [comment]
Internal ID: AGDNS-2104

**Comment by Chinaski1** [comment]
Fixed
