### ISSUE TITLE
Adguard DNS returns 127.0.0.1 for newrelic.com 

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardDNS#78]
The domain (and all sub-domains) newrelic.com is blocked by Adguard DNS. Is this deliberate?

See below for output from nslookup:
<details>
kevin:~$nslookup newrelic.com
Server:	132.234.241.1
Address:	132.234.241.1#53

Non-authoritative answer:
Name:	newrelic.com
Address: 151.101.64.207
Name:	newrelic.com
Address: 151.101.0.207
Name:	newrelic.com
Address: 151.101.192.207
Name:	newrelic.com
Address: 151.101.128.207

kevin:~$nslookup newrelic.com 176.103.130.130
Server:	176.103.130.130
Address:	176.103.130.130#53

Non-authoritative answer:
Name:	newrelic.com
Address: 127.0.0.1

kevin:~$nslookup newrelic.com 176.103.130.131
Server:	176.103.130.131
Address:	176.103.130.131#53

Non-authoritative answer:
Name:	newrelic.com
Address: 127.0.0.1

kevin:~$nslookup newrelic.com 176.103.130.132
Server:	176.103.130.132
Address:	176.103.130.132#53

Non-authoritative answer:
Name:	newrelic.com
Address: 127.0.0.1

kevin:~$nslookup newrelic.com 176.103.130.134
Server:	176.103.130.134
Address:	176.103.130.134#53
</details>
Also blocked on iOS when using Adguard DNS on Adguard Pro.

**Comment by ameshkov** [comment]
@Alex-302 i guess we should block only tracking subdomains

**Comment by Alex-302** [comment]
@ameshkov It is blocked by `||newrelic.com^$third-party` in all filters with newrelic.com.
I know only one sub-domain rule `||beacon-*.newrelic.com^$third-party`
Should I remove this rule `||newrelic.com^$third-party` from spyware filter?

**Comment by jo2dan23** [comment]
Newrelic is a analytics domain. js-agent.newrelic.com should be added if newrelic.com is going to be completely removed. I dont see why there is a need to remove it though

**Comment by ameshkov** [comment]
newrelic is not just a tacking service, it can also be used for monitoring purposes.

So yes, I suggest replacing an old rule with these two:
```
||js-agent.newrelic.com^
||beacon-1.newrelic.com^
```

**Comment by Alex-302** [comment]
Done.
