### ISSUE TITLE
Releases/Tags not in sync? Github says v 2.6.0 | website says v2.7 ?

### ISSUE THREAD

**Issue by pictosun** [AdguardTeam/AdGuardDNS#784]
Hi,

did someone forget to push the update over here? Or why do we have a mismatch between Github and AdGuard DNS website (blog)? 

Looks like in the last time there is not that much development than the time before?! Would be nice to get an update that the project is still alive.

The website is pushing discounts all the time - hope that the product will not disappear?!

**Comment by ameshkov** [comment]
Thanks for the reminder :)
