### ISSUE TITLE
Youtube player not woking

### ISSUE THREAD

**Issue by miladmeidanshahi** [AdguardTeam/AdGuardDNS#786]
### Platform

Android

### Protocol

Regular

### Do you use AdGuard app?

Yes I am

### Issue Details

Open youtube app share to adgaurd player an nothing play just black screen.
![Screenshot_20240612_124249_AdGuard](https://github.com/AdguardTeam/AdGuardDNS/assets/11172818/d295700d-bb06-4946-870d-ef5d65cfc483)

### Actual Behavior

Should play video correctly.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Chinaski1** [comment]
Hello there!

First try using an unfiltered server and check if the issue is still persists.
Server address: 94.140.14.140 / 94.140.14.141

**Comment by miladmeidanshahi** [comment]
I'm using proxy with Adguard app how can I set these server address?

**Comment by Chinaski1** [comment]
Go to the AdGuard app -> DNS Settings -> Select a non-filtering server

**Comment by Chinaski1** [comment]
Closed due not reply
