### ISSUE TITLE
h3 with h2 fallback with AGDNS question

### ISSUE THREAD

**Issue by emeritaacuity0u** [AdguardTeam/AdGuardDNS#789]
When using AdGuard Personal DNS (DoH), will h3 be prioritised with h2 as a fallback?

- Is it used at all if a h3 address is not specifically used with AGDNS?
- I'm mostly using Apple devices, with mobile configs rather than the AdGuard app, will this make a difference?

**Comment by ameshkov** [comment]
It depends not on the DNS server, but on the DNS client that you're using.

Tbh, I don't know if Apple devices attempt to use H3.
