### ISSUE TITLE
Website not loading

### ISSUE THREAD

**Issue by Bhooty** [AdguardTeam/AdGuardDNS#79]
https://www.animeout.xyz/

This site doesnt load
![image](https://user-images.githubusercontent.com/46019727/75265744-8790da80-581b-11ea-9966-388a7cf8698a.png)

Plz Fix if u can :(

Using the ip
176.103.130.130
176.103.130.131

**Comment by TPS** [comment]
Blocked by `||51.158.` (DNS/Simplified list) rule .  Is there any info _why_ that rule exists?

**Comment by TPS** [comment]
Blocked by `||51.158.` (DNS/Simplified list) rule.  Is there any info _why_ that rule exists?

**Comment by Bhooty** [comment]
Why is this blocked?

**Comment by Alex-302** [comment]
That rule is loaded from EasyList. Will be excluded from SDN Filter.
