### ISSUE TITLE
https://dns.adguard.com/info.txt is showing different servers when using website & different browser on same machine/device?!

### ISSUE THREAD

**Issue by pictosun** [AdguardTeam/AdGuardDNS#790]
### Platform

Other

### Protocol

DNS-over-HTTPS

### Do you use AdGuard app?

No I don't

### Your configuration

every device (mobile or pc/mac) is behaving the same.

When using the link to check which server I'm on (https://dns.adguard.com/info.txt) it shows different results when using different browsers on the same machine/device.
And when using the website it shows another server where I'm on.

Shouldn't it be all the same server as I'm using .mobileconfigs on my machines/devices

### Traceroute to AdGuard DNS

./.

### Issue Details

- take a device which is using AdGuard-DNS as .mobileconfig (or somehow else)
On that machine:
- go to https://dns.adguard.com/info.txt with browser a
- go to https://dns.adguard.com/info.txt with browser b
- go to https://adguard-dns.io/en/welcome.html and scroll down to the map and check which server you're using

for me I'm getting different results dns2-dp-fra-4 / 7 / 17 / 8 and so on.

### Expected Behavior

Expected behaviour should be that I'm always on the same server (I know that can change, but not when checking parallel at the same time).

### Actual Behavior

Like I said the server is changing when using different browser or website-view.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by ameshkov** [comment]
No worries, that's okay. We have many different servers in a single location and you'll be connected to a random one every time.

**Comment by pictosun** [comment]
> No worries, that's okay. We have many different servers in a single location and you'll be connected to a random one every time.

Thanks for the feedback. But why do the browsers connect to different servers if I do have a .mobileconfig running (is this due to the utilization of the servers)?

And could maybe the issue from #777 be correlated to this point if the connected server is changing?

**Comment by ameshkov** [comment]
@pictosun well, the load on a single location is higher than any single server can manage so there's that. All these servers have the same IP address and when establishing a connection your traffic will be randomly routed to one of them. This is called "anycast IP" and it's a standard technique for highload & distributed services.

Tbh, I don't think that there's any correlation with #777.
