### ISSUE TITLE
Show "Company: Not applicable" as a filterable option within the query log

### ISSUE THREAD

**Issue by emeritaacuity0u** [AdguardTeam/AdGuardDNS#797]
### Issue Details

In the query log you can filter each domain by company, but you can't filter companies by "Not applicable".

### Proposed solution

Allow domains with no allocated company in the query log to be individually filtered.

**Comment by Chinaski1** [comment]
Hello there!
Filter function by `Not applicable` request is already [implemented](https://uploads.adguard.org/Chinaskim7xss.png).

**Comment by emeritaacuity0u** [comment]
@Chinaski1 that will filter countries by not applicable, not companies with no name allocation.

I would like to filter companies with no name, not the country.
