### ISSUE TITLE
Confusion regarding configuration in stuby

### ISSUE THREAD

**Issue by Techguyprivate** [AdguardTeam/AdGuardDNS#8]
Sorry for the question. I am a noob. What should be the configuration for stuby dns for ubuntu ?

Should it be like this, below ?

# Adguard servers
  - address_data: 176.103.130.130
    tls_port: 5353
    tls_auth_name: "dns.adguard.com"
  - address_data: 176.103.130.131
    tls_port: 5353
    tls_auth_name: "dns.adguard.com"
Do I need tthe line tls_port 5353 or 53 ? 

Do I need the line tls_port at all? 
Do I need anything else to write?

Huge thank you anyway.

**Comment by Techguyprivate** [comment]
I don't have the option to change my dns address of my router or modem . Old ONT modem . So  can I use adgurad home then without the ability to changing the dns address of the router or modem ? 

Anyway, I am talking about this. 

https://dnsprivacy.org/wiki/display/DP/DNS+Privacy+Daemon+-+Stubby

https://www.linuxbabe.com/ubuntu/ubuntu-stubby-dns-over-tls

**Comment by hmage** [comment]
Apologies, mistook this repo for another.

tls port should be 853.
