### ISSUE TITLE
onliner.by - missed ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardDNS#8]
vinaria cafe

![image](https://cloud.githubusercontent.com/assets/15856304/17166079/697bf7a0-53dd-11e6-9f7e-769c9e03a88c.png)

DNS прописаны в
роутере (чистку кеша браузера и dns делал)
952965

**Comment by Alex-302** [comment]
Добавил в фильтр DNS
||ad.onliner.by^
