### ISSUE TITLE
MiVideo issue

### ISSUE THREAD

**Issue by jockjoint** [AdguardTeam/AdGuardDNS#80]
Good day.
After last update MiVideo app in the miui global ROM i see many annoying online video and ask block this in the Adguard DNS over TLS.
Link for app: https://play.google.com/store/apps/details?id=com.miui.videoplayer

This is hosts which need for that

||ru.video.intl.xiaomi.com^
||video.in.intl.xiaomi.com^
||cdn.awsind0-fusion.fds.api.mi-img.com^
||preview.in.intl.video.xiaomi.com^
||gmivideo-stag.in.duokanbox.com^
||prod.fireworktv.com^
||s3-ap-southeast-1.amazonaws.com^

Thanks a lot.

**Comment by Alex-302** [comment]
> ||cdn.awsind0-fusion.fds.api.mi-img.com^

http://docs.api.xiaomi.com/en/fds/basic-concept.html
Not sure if we can block it.

> ||preview.in.intl.video.xiaomi.com^

cannot find info about it.

> ||gmivideo-stag.in.duokanbox.com^

it seems it is related to software updates.

> ||prod.fireworktv.com^

not xiaomi's domain.

> ||s3-ap-southeast-1.amazonaws.com^

definitely this domain cannot be blocked.

Can be added:
`||video.intl.xiaomi.com^`

**Comment by jockjoint** [comment]
Then others

**Comment by jockjoint** [comment]
Block please without that.

**Comment by jerryluk** [comment]
@Alex-302 @jockjoint This is Jerry from Firework. FIreworkTV is MiVideo's content partner. We are providing UGC short-form videos to apps. People are not going to see any video content if we are blocked.

**Comment by jockjoint** [comment]
> @Alex-302 @jockjoint This is Jerry from Firework. FIreworkTV is MiVideo's content partner. We are providing UGC short-form videos to apps. People are not going to see any video content if we are blocked.

Hi. Those who don't use adguard DNS can watch all this video.

**Comment by Alex-302** [comment]
@jockjoint we have DNS without blocking. The user has a choice.

**Comment by Chilace** [comment]
**Blocking video.intl.xiaomi.com domain breaks the functionality of multiple MIUI apps (MI Video, MI Browser, MI Weather).**
For example, sometimes I watch the weather forecast video through the MI Video app, but if video.intl.xiaomi.com domain is blocked, I cannot do it.
video.intl.xiaomi.com is an analogue of www.youtube.com, just a video hosting and blocking it is equivalent to blocking YouTube.
Please stop blocking it at the DNS level.
If someone doesn't like annoying video notifications, they can be turned off in the application settings.

_Related to https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/593_

**Comment by Alex-302** [comment]
Ok, removed.
