### ISSUE TITLE
AdguardDNS is not resolving...

### ISSUE THREAD

**Issue by Nestorbra** [AdguardTeam/AdguardDNS#80]
Dear all,

AdguardDNS is not resolving any website since about 1 hour ago (GMT+1:00). I had to change to other DNS servers in order to be able to report this issue. Can you check on your end?

**Comment by jo2dan23** [comment]
Resolving for me but all ads are unblocked

**Comment by jo2dan23** [comment]
Resolving for me but all ads are unblocked

**Comment by jo2dan23** [comment]
@ameshkov

**Comment by adguard1** [comment]
Same when I use the dns servers the Internet does not work

**Comment by adguard1** [comment]
Are they back up?

**Comment by jo2dan23** [comment]
@adguard1 requests are resolved nothing is being blocked though :(

**Comment by adguard1** [comment]
Dam :(

**Comment by Nestorbra** [comment]
Well, I'm having resolving issues again :-( 
Is it working well for you?

**Comment by ameshkov** [comment]
The downtime was ~1 hour again. Our reaction time during the weekend is really unacceptable, I am sorry for this.

**Comment by Bluscream** [comment]
Was that sarcastic?

**Comment by ameshkov** [comment]
Not at all, downtime more than 10 minutes is not acceptable. DNS downtime ceases the internet access for all its users.

**Comment by Bluscream** [comment]
Imagine this being the DynDNS server xD

**Comment by ameshkov** [comment]
Poor Dyn:)

**Comment by sandybeachit** [comment]
Can we close this issue off as it seems resolved ?

**Comment by vozersky** [comment]
@sandybeachit yep :)
