### ISSUE TITLE
Dashboard shows translation available during page load when it shouldn’t 

### ISSUE THREAD

**Issue by emeritaacuity0u** [AdguardTeam/AdGuardDNS#801]
### Platform

iOS

### Protocol

DNS-over-HTTPS

### Do you use AdGuard app?

No I don't

### Issue Details

When navigating to the dashboard, Safari shows translation available in the search bar, even though it’s already showing the same language my system is set to (en-AU).

I’ve never seen any other website do this, so I assume there to be an issue here.

![image](https://github.com/AdguardTeam/AdGuardDNS/assets/171407720/2b287830-5970-4c63-b142-c727eab30098)

### Expected Behavior

Translation isn’t offered when navigating to the AdGuard DNS dashboard that’s already showing in English.

### Actual Behavior

Translation is offered for the AdGuard DNS dashboard that’s already showing in English.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Chinaski1** [comment]
Internal ID: AGDNS-2387

**Comment by emeritaacuity0u** [comment]
@Chinaski1 It turned out that this was caused specifically in my situation by an additional keyboard language being added to `System Settings > Keyboard > Text Input > Input Sources`.
I have no idea why it was there, but that was the issue.
