### ISSUE TITLE
Some NextDNS features needed to introduce in AdGuard DNS

### ISSUE THREAD

**Issue by suggest132** [AdguardTeam/AdGuardDNS#811]
### Issue Details

One should visit https://my.nextdns.io/start and see the Security tab and Privacy tab of NextDNS. There are so many features available there which should also be made available in AdGuard DNS.

**Comment by ameshkov** [comment]
This is not a proper feature request, it's not specific enough.

NextDNS tends to make "features" of individual blocklists (which AdGuard DNS already provides).

This approach has two advantages:

* The user thinks that there are many different features (while in fact they all a shortcuts for enabling blocklists).
* The feature checkbox allows to convey the information to the user more easily.

These are both important advantages and for some blocklists I am okay with "extracting" them to a separate checkbox.

However, please be more specific and explain:

1. What exact feature you would like us to add.
2. Why do you think it's important to have it there.

Please open one feature request per feature.
