### ISSUE TITLE
The Blocklists is displaying the wrong time when filters are updated.

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardDNS#813]
### Platform

Other

### Protocol

Regular

### Do you use AdGuard app?

Yes I am

### Your configuration

The Blocklists are showing the wrong time when the filters are updated. All Blocklists show "Updated 1 Hour ago."

### Issue Details

Go to the blocklist in AdGuard private DNS homepage when you are logged into your account.

### Expected Behavior

Should tell you when the blocklist were updated.

### Actual Behavior

All blocklist show updated 1 hour ago.

### Screenshots

![Screenshot_20240801_174417_Samsung Internet](https://github.com/user-attachments/assets/2d9b994a-8719-45de-80e2-1d62ae1d750e)

**Comment by Chinaski1** [comment]
Hello there!

This situation is not a bug because we are showing the last filter update request.

**Comment by Batman2814** [comment]
So you're saying all the blocklists are updated simultaneously because that's what is showing right now, updated 34 minutes ago at the time I'm writing this.

**Comment by Batman2814** [comment]
![20240802_08460685](https://github.com/user-attachments/assets/d1172ca0-dc68-44c0-a479-ec95f877a3a1)

**Comment by hagezi** [comment]
@Chinaski1 This was always different, the time at which the source was last updated was displayed, i.e. when the source last changed.

The current implementation makes absolutely no sense to me.
