### ISSUE TITLE
AdGuard Private Custom DNS won't work with Amazon's Eero Router feature called "Local DNS Caching".

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardDNS#814]
### Platform

Router

### Protocol

Regular

### Do you use AdGuard app?

No I don't

### Your configuration

When using the "Local DNS Caching" feature, I set AdGuard Private DNS in the Eero app under Custom DNS. When "Local DNS Caching" is turned on, it is supposed to send a signal to the custom DNS, which is AdGuard Private DNS, and then cache that request on the Eero router to speed up page loads. 

I posted a Screenshot explaining what "Local DNS Caching" does.

### Issue Details

when AdGuard Private DNS is setup in my eero router with local DNS Caching enabled with my ISP Shaw Communications its not using my custom DNS I have set up which is AdGuard Private DNS. 

### Expected Behavior

should be able to use Local DNS Caching with AdGuard Private Custom DNS with my ISP shaw communications. 

### Actual Behavior

It does not work with the current ISP Shaw Communications where you guys said "I see what's causing this, AG DNS does indeed serves unoptimal Amazon IP address for your ISP. We'll resolve this, but this will require time.

### Screenshots

![32077 preview](https://github.com/user-attachments/assets/efbd10b0-3670-4138-9521-956b3037d4cf)

### Additional Information

I believe for sure that this is an issue with AdGuard. I'm pretty sure it has to do with a previous issue I reported way back when AdGuard Private DNS was in beta. You guys said that it would be fixed, but it required time, and I have definitely given enough time, but still, no fix is here. 

Here's a link to the GitHub issue 
https://github.com/AdguardTeam/AdGuardDNS/issues/333

Do not close this issue until it is fixed.

**Comment by emeritaacuity0u** [comment]
#673

**Comment by fpaddict** [comment]
Looks to be an issue with Eero's implementation of DNS cashing. Just disable DNS Cashing in the Eero config...
