### ISSUE TITLE
Vietnam Being Routed to United States instead of Singapore

### ISSUE THREAD

**Issue by NanKillBro** [AdguardTeam/AdGuardDNS#815]
### Platform

Windows

### Protocol

DNS-over-HTTPS

### Do you use AdGuard app?

No I don't

### Traceroute to AdGuard DNS

![image](https://github.com/user-attachments/assets/d97a6db6-8f62-4e9f-ac9f-00ce4d546033)
![image](https://github.com/user-attachments/assets/2c9b49c1-9f93-4a61-9b41-e90fff370576)

### Issue Details

The DNS server being directed to United States or Japan randomly not the closest server (Singapore)

### Expected Behavior

Connection should be correctly directed to Singapore server 

### Actual Behavior

The DNS server being directed to United States or Japan making the network slower

### Additional Information

Country: Vietnam
ISP: Viettel

**Comment by trmdi** [comment]
Probably only Viettel can change it.
https://github.com/AdguardTeam/AdGuardDNS/issues/605
