### ISSUE TITLE
All Blocklists say updated 1 hour ago even when hour is up

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardDNS#820]
### Platform

Router

### Protocol

Regular

### Do you use AdGuard app?

No I don't

### Issue Details

Step 1: log in to the account and go to the servers
Step 2: Go to server settings
Step 3: Go to Category Blocklists and look at when all filters were updated.

### Expected Behavior

Should actually tell you when they were actually updated

### Actual Behavior

always says updates 1 hour ago.

### Screenshots

![20240824_08302586](https://github.com/user-attachments/assets/0c5c8049-9905-4b10-b074-6414da459ba1)
![20240824_08303810](https://github.com/user-attachments/assets/f16cb8c3-6db4-4bd5-ab22-6a09d8d62b24)
![20240824_08304537](https://github.com/user-attachments/assets/57a8b873-f399-4e54-bc86-6b9dc12a833c)
![20240824_08305332](https://github.com/user-attachments/assets/2f607e2d-cc50-4709-b896-88bcb8ded91e)
![20240824_08305884](https://github.com/user-attachments/assets/7ef7839a-eddd-4e22-b287-81c23aab1f22)

### Additional Information

I reported this issue once and you guys closed it. this problem is not normal and would be considered a bug so could you please fix this in the next update? I would appreciate it if you guys don't close this issue until it's been fixed.

**Comment by pictosun** [comment]
I don't have that issue. Everything working like it should in my case.

**Comment by Chinaski1** [comment]
In general batman was right, the mechanism of determining the last date of updating filters was really changed.
We have now reviewed it and the situation should normalise.

Thanks for the report
