### ISSUE TITLE
http://www.thefreedictionary.com/ - anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardDNS#83]
http://www.thefreedictionary.com/vivid

The issue occurs when using the Standard DNS mode, reproduced in Firefox only. All other ad blockers are disabled.

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/20395910/2e94c8c4-aced-11e6-8824-4dc336c1a143.png)

![image](https://cloud.githubusercontent.com/assets/15856304/20395961/54261c96-aced-11e6-9e3a-d09cd57d4972.png)

**Comment by Alex-302** [comment]
It is impossible with DNS filtering. In general the site functionality is not limited.

**Comment by evgeniy-ADG** [comment]
>
Проблема не решена, она всё ещё присутствует, и по-прежнему появляется сообщение о неполной загрузке страницы и частичном нарушении её функциональности. Возможно, вы проверяли только главную страницу сайта <http://www.thefreedictionary.com/>, действительно, там подобной проблемы нет, но если вы забьёте в поисковую строку любое слово и затем откроете соответствующую ему страницу, то через 3–4 секунды увидите злополучное уведомление.
На странице GitHub <https://github.com/AdguardTeam/AdguardDNS/issues/83> по данному вопросу сказано, что проблема имеется только в браузере Firefox (“reproduced in Firefox only”). Это не соответствует действительности, т.к. проблема имеется в Pale Moon v26.5.0, в Internet Explorer v11 и в Microsoft Edge.
Ваш представитель Alex-302 написал на той же странице GitHub, что фильтрация DNS не может быть причиной данной проблемы, мол, в целом функциональность сайта не подвергается ограничению (“In general the site functionality is not limited”). Может быть, он и хороший специалист, но я верю тому, что вижу, а вижу я, что при соединении ЧЕРЕЗ сервер Adguard DNS предупреждение появляется, а при соединении НЕ ЧЕРЕЗ Adguard DNS этого сообщения нет.
Я не обязан вникать в специфические детали DNS-соединения, этим должны заниматься “специально обученные люди со специальным инструментом”, а я буду заниматься своим делом, которое за меня эти специалисты не сделают и в детали которого они тоже не станут вникать. Но если ваши коллеги не в состоянии решить проблему, то проще отазаться и от их услуг и от использования Adguard DNS.

**Comment by evgeniy-ADG** [comment]
I can't reopen tickets here for some reason, no such button. Please add your comments here.

**Comment by Alex-302** [comment]
@evgeniy-ADG at the moment this site with DNS filtering only looks as:
http://ipic.su/img/img7/fs/kiss_129kb.1479914646.png
http://ipic.su/img/img7/fs/kiss_100kb.1479914669.png
http://ipic.su/img/img7/fs/kiss_106kb.1479914765.png

> Ваш представитель Alex-302 написал на той же странице GitHub, что фильтрация DNS не может быть причиной данной проблемы, мол, в целом функциональность сайта не подвергается ограничению. 

It is incorrect translation of my words, DNS filtering can cause some issues, but we can't fix some small issues, because ads(for example Google ads) will be unblocked on all sites.

**Comment by sandybeachit** [comment]
But if this issue only occurs in Firefox then surely it's more a browser issue rather than an agguard issue? I just tried it on android /adguard DNS and I didn't see that error

**Comment by vozersky** [comment]
Can't reproduce with default DNS servers and FF 54.
Anyway, that "something went wrong" thing was just an anti-adblock kind of message. In fact, it didn't affect the functionality of the site.
