### ISSUE TITLE
AdGuard DNS still actively developed? 

### ISSUE THREAD

**Issue by pictosun** [AdguardTeam/AdGuardDNS#833]
Hi. 

Could you developers give us an update on development of the product?

In earlier times there was an update nearly every month. Now we haven’t seen any updates since 3 
months. 

even the normal AdGuard didn’t receive any update for a longer time. (As far as I understand AdGuard DNS.io is more or less an AdGuard Home within the web). 

Would be nice to get some updates here. 

Thanks

**Comment by Chinaski1** [comment]
Hello there!

Yes, of course, AdGuard DNS is being actively developed. I won't give exact dates, but the new release is very close :)
