### ISSUE TITLE
Link is not corrected when dismissing upgrade page

### ISSUE THREAD

**Issue by emeritaacuity0u** [AdguardTeam/AdGuardDNS#838]
### Platform

iOS

### Protocol

DNS-over-HTTPS

### Do you use AdGuard app?

No I don't

### Issue Details

1. Navigate to https://adguard-dns.io/en/dashboard/account?upgrade=true&tariff=TEAM
2. Tap off the upgrade panel that pops up
3. Scroll down and tap “Upgrade”

### Expected Behavior

Upgrade panel loads.

### Actual Behavior

Upgrade panel fails to load due to the page not navigating to https://adguard-dns.io/en/dashboard/account when dismissing the upgrade panel.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

Video sent to @Chinaski1 on Telegram.

**Comment by Chinaski1** [comment]
We will consider in the context of another task
