### ISSUE TITLE
Open source httpbin.agrd.workers.dev

### ISSUE THREAD

**Issue by SunsetMkt** [AdguardTeam/AdGuardDNS#840]
### Issue Details

`httpbin.agrd.workers.dev` is the most functional HTTPbin implication on Cloudflare workers that I could find. Will it be possible to be open source so we can selfhost it?

### Proposed solution

Open source `httpbin.agrd.workers.dev` codebase.

**Comment by ameshkov** [comment]
No prob:)

Here it is: https://github.com/AdguardTeam/HttpBin
