### ISSUE TITLE
Latest activity: No data for the last 8 hours

### ISSUE THREAD

**Issue by fpaddict** [AdguardTeam/AdGuardDNS#845]
### Platform

Router

### Protocol

DNS-over-HTTPS

### Do you use AdGuard app?

No I don't

### Your configuration

I have configured DNS over HTTPS on a TP-Link Omada system. It was working fine for about a day however at around 6pm EDT, it stopped reporting information.

All the tests I've done still show that I'm using AdguardDNS however the dashboard says it hasn't received any requests in x number of hours.

Ad blocking is still functioning.

### Traceroute to AdGuard DNS

traceroute to 94.140.14.14 (94.140.14.14), 64 hops max, 40 byte packets
 1  192.168.4.1 (192.168.4.1)  17.710 ms  9.167 ms  4.681 ms
 2  96.120.73.221 (96.120.73.221)  17.576 ms  19.575 ms  15.866 ms
 3  ae-253-1215-rur01.raritan.nj.panjde.comcast.net (24.124.226.1)  34.907 ms  14.080 ms  13.811 ms
 4  be-39-ar03.plainfield.nj.panjde.comcast.net (68.85.35.101)  18.047 ms  18.114 ms  19.979 ms
 5  be-31113-cs01.newark.nj.ibone.comcast.net (96.110.42.33)  18.955 ms
    be-31133-cs03.newark.nj.ibone.comcast.net (96.110.42.41)  19.889 ms
    be-31123-cs02.newark.nj.ibone.comcast.net (96.110.42.37)  18.177 ms
 6  be-1211-cr11.newark.nj.ibone.comcast.net (96.110.35.70)  21.666 ms
    be-1311-cr11.newark.nj.ibone.comcast.net (96.110.35.74)  19.376 ms
    be-1214-cr14.newark.nj.ibone.comcast.net (96.110.37.70)  17.552 ms
 7  be-301-cr12.newyork.ny.ibone.comcast.net (96.110.36.146)  19.273 ms
    be-301-cr13.newyork.ny.ibone.comcast.net (68.86.83.178)  20.707 ms  23.618 ms
 8  be-4311-pe11.60hudson.ny.ibone.comcast.net (96.110.34.58)  24.848 ms
    be-1413-cs04.newyork.ny.ibone.comcast.net (68.86.86.93)  19.232 ms
    be-1112-cs01.newyork.ny.ibone.comcast.net (96.110.35.129)  22.532 ms
 9  be-4101-pe01.60hudson.ny.ibone.comcast.net (96.110.41.146)  20.032 ms
    be-4311-pe11.60hudson.ny.ibone.comcast.net (96.110.34.58)  22.110 ms
    be-4411-pe11.60hudson.ny.ibone.comcast.net (96.110.34.62)  15.700 ms
10  * * *
11  dns.adguard.com (94.140.14.14)  32.369 ms * *

### Issue Details

Login to dashboard and review dns queries.

### Expected Behavior

I expect to see the DNS queries in the dashboard.

### Actual Behavior

Dashboard stopped reporting DNS queries.

### Screenshots

<details><summary>Screenshot 1:</summary>
<img width="752" alt="Screenshot 2024-10-28 at 00 57 32" src="https://github.com/user-attachments/assets/9afcca40-2bc7-4642-acc1-008c1ca438ab">
</details>

<details><summary>Screenshot 2:</summary>
<img width="489" alt="Screenshot 2024-10-28 at 00 56 49" src="https://github.com/user-attachments/assets/e3506880-e205-4f07-800e-0e71faa970c9">
</details>

<details><summary>Screenshot 3:</summary>

<img width="1145" alt="Screenshot 2024-10-28 at 01 54 50" src="https://github.com/user-attachments/assets/8eab4d11-d986-4079-8ce8-7a7b6ecf6bfe">

</details>

**Comment by ameshkov** [comment]
Looking into it

**Comment by ameshkov** [comment]
Resolved, thank you so much for reporting it!
