### ISSUE TITLE
Can you add this protection feature to AdGuard Private DNS?

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardDNS#846]
### Proposed solution

![Screenshot_20241021_203048_Samsung Internet](https://github.com/user-attachments/assets/3ce39f60-c759-4aee-a242-165bc34906a9)
_

### Alternative solution

It's already been added to Next DNS, so it would be great to add it to AdGuard Private DNS.

**Comment by emeritaacuity0u** [comment]
That's already included within the security tab. Try visit any typo-squatting link and most of them should be blocked.

![image](https://github.com/user-attachments/assets/6f0c499f-3496-4bbf-a2ac-4b9fc1c796f9)

There's also various custom lists such as HaGeZi's TIF, etc that handle this.
