### ISSUE TITLE
Private DNS not working in AdGuard Adblocker for Windows

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardDNS#848]
### Platform

Windows

### Protocol

DNS-over-QUIC

### Do you use AdGuard app?

Yes I am

### Issue Details

1.) have Adguard personal DNS setup in AdGuard Adblocker for Windows
2.) Go to the AdGuard services check Page to see if the server is connected.

### Expected Behavior

AdGuard Private DNS should work in AdGuard Adblocker for Windows and show that the server is connected when going to AdGuard Services Check Page. 

### Actual Behavior

AdGuard Personal DNS does not work in AdGuard Adblocker for Windows. 

### Screenshots

![20241101_14211267](https://github.com/user-attachments/assets/4dea0a32-b4c8-4e6a-a348-89d92211720c)

![20241101_14235040](https://github.com/user-attachments/assets/12d32be9-8229-43f4-8fba-829b18cddbfa)

**Comment by trmdi** [comment]
1. how do you setup it in Adguard for Windows?
2. how do you setup dns in your browser?

(post your screenshots)

**Comment by Batman2814** [comment]
I copy and Paste the Adguard Personal DNS from my Private DNS Account and paste it into AdGuard Adblocker for Windows.

**Comment by Batman2814** [comment]
I opened the report for AdGuard VPN for Windows and I believe now that the problem is with Windows AdGuard VPN.

**Comment by trmdi** [comment]
Ok, so this issue should be closed for now?
