### ISSUE TITLE
query logs can't be seen more than 20 from mobile browser

### ISSUE THREAD

**Issue by olumolu** [AdguardTeam/AdGuardDNS#849]
### Platform

Android

### Protocol

DNS-over-TLS

### Do you use AdGuard app?

No I don't

### Issue Details

Issue is on mobile browser query logs i cant see more than 20 at a time the part that give page 1 page 2 page 3 is not visible in mobile browswer hence you are stuck with the last 20 logs but if you open the desktop site you can see 20 followed by next pages to see other logs.
This need a fix for browser mobile.

### Actual Behavior

Can't see query logs more than 20 in mobile browser.

**Comment by emeritaacuity0u** [comment]
It should auto populate additional logs when you get to the end of the page.

**Comment by olumolu** [comment]
> It should auto populate additional logs when you get to the end of the page.

No it does not it only happened in nextdns i have tried with brave chrome and firefox same

**Comment by Chinaski1** [comment]
You have created similar task before: https://github.com/AdguardTeam/AdGuardDNS/issues/828

If you don't get further query logs please send me a video with the issue.

**Comment by olumolu** [comment]
> You have created similar task before: #828
> 
> If you don't get further query logs please send me a video with the issue.

That was closed but the issue is still present

**Comment by Chinaski1** [comment]
The problem is not recurring on our side, could you please send a video of the issue?

**Comment by trmdi** [comment]
I can confirm the bug. On mobile browsers, scrolling to the end does not load more older logs.

**Comment by Chinaski1** [comment]
Could you please specify the browser and its version? We will try to find out the cause of the issue.

**Comment by trmdi** [comment]
> Could you please specify the browser and its version? We will try to find out the cause of the issue.

Google Chrome 130.0.6723.86

**Comment by trmdi** [comment]
I've just found an interesting thing. When you scroll down to the end of the page, then scroll up a bit, and scroll down again very fast (you may need to repeat this several times), it will load. So, I think somehow the JavaScript code checking when the user scrolls to the end does not work perfectly in this case.

**Comment by olumolu** [comment]
> Could you please specify the browser and its version? We will try to find out the cause of the issue.

I have tested this on brave from which i have attached the screenshot from 1.71.121 which is on chromium latest 130
Tested on firefox 132 latest issue was same.
Tested on cromite which is chormium fork and issue was same.

**Comment by olumolu** [comment]
> > Could you please specify the browser and its version? We will try to find out the cause of the issue.
> 
> Google Chrome 130.0.6723.86

Yes true.

**Comment by Chinaski1** [comment]
Thank you for providing this information.
We are looking into the issue.

I will be back as soon as there are any updates on the situation.

**Comment by olumolu** [comment]
> I've just found an interesting thing. When you scroll down to the end of the page, then scroll up a bit, and scroll down again very fast (you may need to repeat this several times), it will load. So, I think somehow the JavaScript code checking when the user scrolls to the end does not work perfectly in this case.
> 
> Probably this peace of code? ![image](https://private-user-images.githubusercontent.com/11857205/383214925-775a81cd-0a3b-4408-ae73-8220a4c4c96d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MzIyNjAsIm5iZiI6MTczMDgzMTk2MCwicGF0aCI6Ii8xMTg1NzIwNS8zODMyMTQ5MjUtNzc1YTgxY2QtMGEzYi00NDA4LWFlNzMtODIyMGE0YzRjOTZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDE4MzkyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2ZDdmYjZmNmQ3MGM1NTU1MDI4NGQxMTc3MmRjZDAzNGNlNDZhZGQ0ZjRlMjc3ZDhhOWVmMzMwMTY2NjVkMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HcRGSMpnLFCVmRD93obedJaiUpL3PETY4F9y1GLQvMU) Here is a quick test on the mobile: ![image](https://private-user-images.githubusercontent.com/11857205/383215185-13f29aa9-6e88-4073-a1f6-ed403a42eee2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MzIyNjAsIm5iZiI6MTczMDgzMTk2MCwicGF0aCI6Ii8xMTg1NzIwNS8zODMyMTUxODUtMTNmMjlhYTktNmU4OC00MDczLWExZjYtZWQ0MDNhNDJlZWUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDE4MzkyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5MmE5YWE4ZDAxZmE2MzcyMjUwZjg5ODcyNjMzOTg1MWJiODE3YTg1M2Q2MjYyMDY0ZjhlMjQ1ODg5ZGQ1YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Kx6xXWrKQrcQRwXSWgR0xTRF0vADcwHeSNXLZBdDMfI)

How you test that on mobile?

**Comment by trmdi** [comment]
> How you test that on mobile?

I used the DevTools remotely. (https://developer.chrome.com/docs/devtools/remote-debugging)

But you can test like this with Google Chrome. Copy this code, go to Adguard's log page, click on the address bar and click on Copied text (make sure it does not become a search, if you do correctly, nothing seems to happen after that). Then quickly scroll to the end of the page and wait 5s, it will tell you those values.

    javascript:setTimeout(function(){alert(`${window.innerHeight+window.scrollY} vs ${document.body.scrollHeight}`)}, 5000)

**Comment by Chinaski1** [comment]
Internal ID: AGDNS-2517

**Comment by Batman2814** [comment]
I have this problem with the Samsung Internet Browser on my Galaxy Phone. At times, it will not let me continue, so if AdGuard, can you reproduce it on your end and try different times to do it, not just once?

**Comment by Batman2814** [comment]
[]https://github.com/user-attachments/assets/c2112045-e1d7-4607-bd3c-9de2516a83b3

**Comment by Batman2814** [comment]
https://github.com/user-attachments/assets/a900a60a-6f8d-4710-bf5a-b7b3a9b75f72

**Comment by Chinaski1** [comment]
@Batman2814 @trmdi @olumolu 

We recently released an update that should have fixed this bug. Could you please check on your side and report the result?

**Comment by Batman2814** [comment]
Works well now.

**Comment by olumolu** [comment]
> @Batman2814 @trmdi @olumolu
> 
> We recently released an update that should have fixed this bug. Could you please check on your side and report the result?

Yes it works good thanks for the quick resolution.

**Comment by Chinaski1** [comment]
Glad to hear it!
