### ISSUE TITLE
softkey.info - ads

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardDNS#85]
соединение через сервер Adguard DNS.Режим по умолчанию.
плохо работает фильтр счётчиков и системы аналитики, который заявлен в составе фильтра Adguard DNS.
активированные фильтры:
Social media filter, Annoyances filter, Russian filter
http://www.softkey.info/reviews/review17220.php
PaleMoon, FF
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/20455492/c6311e2a-ae65-11e6-8d35-21185c71718c.png)

![image](https://cloud.githubusercontent.com/assets/18548949/20455505/0877c28e-ae66-11e6-9b03-3d3a9bc36031.png)

![image](https://cloud.githubusercontent.com/assets/18548949/20455519/7ae8d010-ae66-11e6-8ce9-cc511ff4dd90.png)

**Comment by Alex-302** [comment]
Ресурсы, которые хранятся на основном домене, с помощью DNS не заблокировать. Скрыть элементы также невозможно. Блокируются только домены целиком, никаких адресов.
