### ISSUE TITLE
not able to sign into AdGuard DNS

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardDNS#851]
### Platform

Other

### Protocol

Regular

### Do you use AdGuard app?

Yes I am

### Issue Details

NA

### Actual Behavior

NA

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

Is Adguard having problems

**Comment by ameshkov** [comment]
Temporary issues: https://status.adguard.com/incidents/yp6t1jynrtt7
