### ISSUE TITLE
Баг в меню "Показывать 10 компаний на странице" 

### ISSUE THREAD

**Issue by eviltracker** [AdguardTeam/AdGuardDNS#855]
### Platform

Windows

### Protocol

DNS-over-QUIC

### Do you use AdGuard app?

Yes I am

### Your configuration

4.6.5. (4.6.207)

### Issue Details

В самом низу, в разделе "Компании" происходит вибрация, тряска меню "Показывать 10 компаний на странице". Проблема в моб. тел. Realme GT 5

### Expected Behavior

Стабильные отображение кол-ва строк на странице

### Actual Behavior

Тряска выпадающего списка с кол-вом строк

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

https://github.com/user-attachments/assets/200dfcf2-6db9-47d5-9d32-65521a547be2

**Comment by Chinaski1** [comment]
ID ошибки: AGDNS-2476

**Comment by Chinaski1** [comment]
Исправили данную проблему, пожалуйста, проверьте и сообщите результат.
