### ISSUE TITLE
DNS Nameserver Spoofability result

### ISSUE THREAD

**Issue by beerisgood** [AdguardTeam/AdGuardDNS#86]
The [DNS Nameserver Spoofability Test](https://www.grc.com/dns/dns.htm) recommend some improvements:
![464918490_338030](https://user-images.githubusercontent.com/9625159/78505008-c0a06100-7770-11ea-9efd-3e803afa78be.jpg)

Both server don't use alphabetic case and the second one miss some DNSSEC security.

Would be awesome if that can be improved for all AdGuard server

**Comment by mozdevcontrib** [comment]
![11FA2AE2-E8DD-48C0-8231-BBD03B63656B](https://user-images.githubusercontent.com/49786450/79075996-85e47e80-7cc4-11ea-8402-ae514827e7de.jpeg)

While the results I just received show excellent anti spoofing, along with DNNSEC validation, the site used is extremely outdated (along with Steve Gibson).

**Comment by beerisgood** [comment]
> While the results I just received show excellent anti spoofing, along with DNNSEC validation, the site used is extremely outdated (along with Steve Gibson).

a old site doesn't mean it's not valid.
Also read my comment again, as your screen only show the same as mine.

I also wonder why you downvote me. I guess you don't understand the problem here

**Comment by mozdevcontrib** [comment]
There upvoted. Apologies. The other results were the same. I do understand the issue. And Steve Gibson is past his sell-by date in the security field.

**Comment by beerisgood** [comment]
@Alex-302
@altokarev 
@ameshkov 
@atropnikov 
@Dariamag 
@Eugene-Savenko 
@IldarKamalov 
@northis 
@Revertron 
@sfionov 
@SoLenny 
@Stillness-2
@vbagirov 
@vozersky 
@zebrum 

Test from today:
![1](https://user-images.githubusercontent.com/9625159/81389925-eaa3c500-911a-11ea-9ae8-d3cad29a32c5.jpg)
![2](https://user-images.githubusercontent.com/9625159/81389932-ed9eb580-911a-11ea-9e9b-76081d84e802.jpg)
![3](https://user-images.githubusercontent.com/9625159/81389940-f0010f80-911a-11ea-86be-9bd1c1256497.jpg)
![4](https://user-images.githubusercontent.com/9625159/81389947-f3949680-911a-11ea-9c40-585adc85ab73.jpg)

Would be awesome if that can be fixed.

**Comment by altokarev** [comment]
Hey, 🍺! You can use @AdguardTeam/qa-team tag to call the right guys instead of random list developers and engineers. Thanks!

**Comment by beerisgood** [comment]
@AdguardTeam/qa-team
@https://github.com/orgs/AdguardTeam/teams/qa-team

Anyone can help?

**Comment by beerisgood** [comment]
*push*

**Comment by ameshkov** [comment]
Uh, sorry for missing it.

As I understand, the only thing is using alphabetic case? I don't fully understand what's the purpose of it from the security perspective, but I am pretty sure this would cause trouble with some software.
