### ISSUE TITLE
spellcheck24.net - anti-adblocker

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardDNS#86]
Когда соединение установлено через сервер Adguard DNS, сайт определяет использование блокиратора рекламы независимо от того, включён плагин Adguard или нет. Реклама там действительно блокируется.

браузер – Pale Moon v26.5.0, FF
соединение через сервер Adguard DNS. По умолчанию.
плагин Adguard отключён
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/20455540/19b9886a-ae67-11e6-9e2e-88a4de08b5aa.png)

На снимке не придавайте значения уведомлению об использовании куки-файлов, т.к. при активном Adguard’е (с задействованным фильтром раздражителей) этого уведомления нет.

**Comment by Alex-302** [comment]
Если отключить защиту полностью, то можно заметить, что перед отрисовкой рекламы видно эту надпись. Обнаружения нет, это просто подложка.
