### ISSUE TITLE
High Latency Due to Routing AdGuard DNS Requests to Los Angeles Instead of Sydney on Telstra Network

### ISSUE THREAD

**Issue by MineGene** [AdguardTeam/AdGuardDNS#862]
**Summary:**  
When using Telstra as my ISP, my DNS queries to AdGuard are being routed to the Los Angeles server instead of the Sydney server, resulting in significantly higher latency. I am located in Australia, and routing to the Sydney server would reduce latency considerably. 

**Details:**  
- **Provider:** Telstra
- **Expected Behavior:** DNS queries are routed to the closest AdGuard DNS server, which in this case should be Sydney, Australia.
- **Current Behavior:** DNS queries are routed to AdGuard’s server in Los Angeles, USA, when connected via Telstra, causing a ~9x increase in latency.
  - **Latency to Sydney Server (Non-Telstra Providers):** ~17 ms
  - **Latency to LA Server (Telstra):** ~193 ms

**Traceroute Results:**
```plaintext
traceroute 94.140.14.14
traceroute to 94.140.14.14 (94.140.14.14), 64 hops max, 40 byte packets
 1  172.20.10.1 (172.20.10.1)  3.171 ms  7.343 ms  4.105 ms
 2  * * *
 3  10.5.142.8 (10.5.142.8)  321.894 ms
    10.5.143.8 (10.5.143.8)  38.481 ms
    10.5.142.8 (10.5.142.8)  28.846 ms
 4  bundle-ether15.cha-edge903.brisbane.telstra.net (139.130.167.117)  24.175 ms  44.076 ms  47.239 ms
 5  bundle-ether12.cha-core30.brisbane.telstra.net (203.50.11.240)  37.869 ms  106.246 ms  92.393 ms
 6  bundle-ether5.hay-core30.sydney.telstra.net (203.50.13.157)  261.571 ms  1016.025 ms  671.761 ms
 7  bundle-ether2.oxf-gw30.sydney.telstra.net (203.50.6.106)  42.610 ms * *
 8  * * *
 9  * bundle-ether1.sydo-core04.telstraglobal.net (203.50.13.94)  2936.668 ms  382.150 ms
10  i-10604.1wlt-core02.telstraglobal.net (202.84.141.225)  257.620 ms  179.003 ms  171.693 ms
11  i-10604.1wlt-core02.telstraglobal.net (202.84.141.225)  175.616 ms  183.278 ms  177.567 ms
12  i-93.tlot02.telstraglobal.net (202.84.253.86)  169.719 ms  191.304 ms  197.010 ms
13  unknown.telstraglobal.net (210.57.53.99)  179.138 ms  192.886 ms  186.496 ms
14  ae22.cr3-lax1.ip4.gtt.net (89.149.181.102)  176.670 ms
    ae3.cr3-lax1.ip4.gtt.net (89.149.187.114)  193.507 ms  242.292 ms
15  ip4.gtt.net (208.97.210.186)  175.681 ms  201.800 ms  172.647 ms
16  * * *
17  dns.adguard.com (94.140.14.14)  196.700 ms  174.273 ms  183.989 ms

**Comment by Chinaski1** [comment]
Hello there!

AdGuard DNS uses [Anycast](https://adguard-dns.io/en/blog/anycast-and-bgp-how-adguard-dns-serves-millions-of-queries.html) technology so we can't manage traffic routing 100% of the time.

At this point, we're compiling problems in internal list with the possibility of their correction in nearest future.
Please provide following information via email to support@adguard.com (also share a link to this issue on GitHub):

1) Your IP address: https://adguard.com/en/test.html
2) ASN. 
3) ISP name.
4) DNS server location: https://adguard.com/en/test.html

I am closing this task as it goes to the internal list of routing issues.

**Comment by MineGene** [comment]
@Chinaski1 is there a way to be notified of the possible resolution to these routing imperfections when they do happen?

I purchased the 5 year VPN plan, but the excessively high latency is making it just obvious enough to be of an annoyance. For my home devices it's fine, but the mobile devices I've had to move to another provider which I would rather not have to use in the long run.

**Comment by MineGene** [comment]
@Chinaski1 Hi, are there any updates on this?
