### ISSUE TITLE
Traffic destination showing small words even when zoomed in

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardDNS#865]
### Platform

Other

### Protocol

Regular

### Do you use AdGuard app?

Yes I am

### Issue Details

1.) Login to AdGuard Personal DNS Account
2. Go under traffic destination for one of your devices on mobile version of browser.
3.) Zoom in all the way which shows small wording.

### Actual Behavior

On Mobile version of browser showing small wording under traffic destination. 

### Screenshots

![Screenshot_20241207_193424_Samsung Internet](https://github.com/user-attachments/assets/0ae3a756-a064-41e3-a298-847cb859b505)

### Additional Information

I'm using the Samsung Internet browser and also Chrome browser on mobile app.

**Comment by Chinaski1** [comment]
Internal ID: AGDNS-2589

**Comment by Chinaski1** [comment]
Fixed
