### ISSUE TITLE
Query log query details panel showing smaller than usual on macOS Safari

### ISSUE THREAD

**Issue by MineGene** [AdguardTeam/AdGuardDNS#866]
### Platform

macOS

### Protocol

DNS-over-HTTPS

### Do you use AdGuard app?

Yes I am

### Issue Details

When on the query log page, and you tap on a query when using Safari for desktop in full screen, the details box that pops up is showing smaller than usual.

### Expected Behavior

Query details box should be longer as it used to be.

### Actual Behavior

Query details box is shorter when using macOS Safari in full screen.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Chinaski1** [comment]
This change was intentional as in some cases users had to scroll down to the action button. Now we have made the button available immediately, so the window with the request details is a bit smaller.
