### ISSUE TITLE
Проблема с www.guru3d.com

### ISSUE THREAD

**Issue by WhinVader** [AdguardTeam/AdGuardDNS#867]
### Platform

Windows

### Protocol

DNS-over-HTTPS

### Do you use AdGuard app?

Yes I am

### Your configuration

Личный AdGuard DNS (DoH) через AdGuard блокировщик рекламы и впн.

### Traceroute to AdGuard DNS

Трассировка маршрута к dns.adguard-dns.com [94.140.14.14]
с максимальным числом прыжков 30:

  1    <1 мс    <1 мс    <1 мс  192.168.1.1
  2     3 ms     3 ms     8 ms  100.81.0.1
  3     7 ms     3 ms     3 ms  mpts-ss-51.msk.mts-internet.net [212.188.1.6]
  4     4 ms     4 ms     *     mag9-cr03-be12.51.msk.mts-internet.net [212.188.1.5]
  5     3 ms     3 ms     *     mag9-cr02-be13.77.msk.mts-internet.net [195.34.53.206]
  6     *        *        3 ms  a197-cr08-eth-trunk14.msk.mts-internet.net [212.188.42.42]
  7    36 ms    36 ms    35 ms  anc-cr03-ae3.77.ff.mts-internet.net [195.34.59.50]
  8    37 ms    37 ms    37 ms  ae11-0.fra30.core-backbone.com [81.95.2.201]
  9    37 ms    37 ms    37 ms  ae2-2029.fra10.core-backbone.com [81.95.15.69]
 10    36 ms    36 ms    36 ms  coreb-fra.cdn77.com [169.150.195.68]
 11    37 ms    37 ms    36 ms  vl217.fra-drt30-dist-2.cdn77.com [169.150.194.51]
 12    37 ms    37 ms    37 ms  dns.adguard-dns.com [94.140.14.14]

### Issue Details

1. Открываем сайт www.guru3d.com
2. Наблюдаем затуп загрузки сайта, грузим сайт от 10 до 40 секунд.

### Expected Behavior

Быстрая загрузка сайта через платный личный Adguard DNS

### Actual Behavior

Медленная загрузка сайта

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

Трассировка маршрута к www.guru3d.com [144.91.87.188]
с максимальным числом прыжков 30:

  1    <1 мс    <1 мс    <1 мс  192.168.1.1
  2     3 ms     3 ms     3 ms  100.81.0.1
  3     3 ms     3 ms     3 ms  mpts-ss-51.msk.mts-internet.net [212.188.1.6]
  4     *        *        *     Превышен интервал ожидания для запроса.
  5     4 ms     3 ms     3 ms  mag9-cr02-be13.77.msk.mts-internet.net [195.34.53.206]
  6     4 ms     4 ms     3 ms  a433-cr06-eth-trunk15.msk.mts-internet.net [212.188.28.102]
  7    17 ms    17 ms    17 ms  mmon-cr01-be1.spb.mts-internet.net [212.188.2.53]
  8    23 ms    43 ms    38 ms  radio-cr01-ae3.0.hel.mts-internet.net [212.188.29.109]
  9    30 ms    29 ms    30 ms  ae55.edge4.Stockholm2.Level3.net [213.242.110.181]
 10    58 ms    58 ms    58 ms  ae2.3202.ear2.frf18.neo.colt.net [171.75.8.9]
 11    58 ms    58 ms    58 ms  contabohubeurope-ic-385700.ip.twelve99-cust.net [213.248.70.177]
 12     *        *        *     Превышен интервал ожидания для запроса.
 13     *        *        *     Превышен интервал ожидания для запроса.
 14    66 ms    65 ms    65 ms  one.guru3d.com [144.91.87.188]

Публичные днс (cloudflare/google/quad9/opendns/мгтс/мтс) аналогичная картина.
Cайт живчиком мгновенно открывается только через NextDNS anycast/ultralow.

**Comment by Chinaski1** [comment]
Hello there!

AdGuard DNS uses [Anycast](https://adguard-dns.io/en/blog/anycast-and-bgp-how-adguard-dns-serves-millions-of-queries.html) technology so we can't manage traffic routing 100% of the time.

At this point, we're compiling problems in internal list with the possibility of their correction in nearest future.
Please provide following information via email to support@adguard.com (also share a link to this issue on GitHub):

1) Your IP address: https://adguard.com/en/test.html
2) ASN. 
3) ISP name.
4) DNS server location: https://adguard.com/en/test.html

I am closing this task as it goes to the internal list of routing issues.
