### ISSUE TITLE
NRD Is Out Of Control!

### ISSUE THREAD

**Issue by KnightmareVIIVIIXC** [AdguardTeam/AdGuardDNS#869]
### Platform

Windows

### Protocol

DNS-over-HTTPS

### Do you use AdGuard app?

Yes I am

### Your configuration

Block NRDs in Security

### Issue Details
Logs indicate that these were blocked by NRD:

```
raw.githubusercontent.com
amazonaws.com
googleapis.com
```

### Expected Behavior

Not having these blocked

### Actual Behavior

They are blocked

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

Disabling NRD blocking in Security fixed the issue

**Comment by GlitchHopAnonymous** [comment]
This has become a major issue for me today too. googleapis.com blocked access to Google Play Services. 

I had a major headache w/ raw.githubusercontent.com troubleshooting why I could not access a file on GitHub.

Even more serious it stopped me from updating my AdGuard filters on all of my devices.

**Comment by MineGene** [comment]
Same experience as the above.
Many services are broken as a result of this.

**Comment by ameshkov** [comment]
Looking into it.

**Comment by ameshkov** [comment]
The issue is resolved now, thank you for reporting it!
