### ISSUE TITLE
wallpaper.com - incorrect blocking

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardDNS#87]
повторилось. Режим по умолчанию
http://www.wallpaper.com/design/patricia-urquiola-jasper-morrison-bouroullecs-and-more-go-on-view-at-houselife-exhibition-bordeux#178082
всё хорошо, если соединение установлено НЕ через сервер Adguard DNS (даже при включённом плагине Adguard). Но всё очень плохо, если соединение установлено ЧЕРЕЗ сервер Adguard DNS (даже при отключённом плагине Adguard).
FF, PaleMoon
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/20455567/a0057d20-ae67-11e6-9541-101e9bacfbc7.png)

![image](https://cloud.githubusercontent.com/assets/18548949/20455568/a4e0ca3e-ae67-11e6-8c45-e9619f409f55.png)

**Comment by Alex-302** [comment]
Странно. Не повторилось.

**Comment by vozersky** [comment]
Can't reproduce
