### ISSUE TITLE
NRD said on already verified and registered long ago times domains

### ISSUE THREAD

**Issue by dalisoft** [AdguardTeam/AdGuardDNS#870]
### Platform

macOS

### Protocol

DNS-over-HTTPS

### Do you use AdGuard app?

Yes I am

### Your configuration

Using managed AdGuard DNS service

### Issue Details

1. Try to use AdGuard DNS service
2. Go-to `avatars.githubusercontent.com`

### Expected Behavior

No **NRD** for those domains. At least for `avatars.githubusercontent.com`

### Actual Behavior

Marks `avatars.githubusercontent.com` as **NRD**

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by GlitchHopAnonymous** [comment]
I could not connect to githubusercontent.com or googleapis.com on any of my devices for hours w/o manually unblocking them. Checking my Query Logs I cannot access amazonaws.com domains either.

**Comment by xRuffKez** [comment]
Resolved

**Comment by Chinaski1** [comment]
Fixed
