### ISSUE TITLE
Being able to choose country of DNS server

### ISSUE THREAD

**Issue by Krumty4351** [AdguardTeam/AdGuardDNS#871]
### Prerequisites

- [X] I have checked the [Knowledge Base](https://adguard-dns.io/kb/) and the [Discussions](https://github.com/AdguardTeam/AdGuardDNSClient/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

Hello,
Unfortunately, I've experienced an increase in blocks to various services such as streaming services (Disney+, Netflix, etc.), banking, paying services, and various websites to the extent that AdGuard DNS becomes unusable. The main problem is that the DNS server chosen for my connection with AdGuard DNS is chosen abroad instead of domestically. In my case, the server provider Datacamp in the Netherlands instead of in Denmark. And geo-blocking is only increasing with the rise of cybercrime etc. Recently I've seen that Mullvad in their browser has a feature to lock the geographical location to one country for their DNS server - for example Denmark. Would you guys look into a similar option for AdGuard DNS. I hate to leave AdGuard, but I don't have many options...

### Proposed solution

Being able to choose country of DNS server

**Comment by Chinaski1** [comment]
Hello there! 

AdGuard DNS uses [Anycast](https://adguard-dns.io/en/blog/anycast-and-bgp-how-adguard-dns-serves-millions-of-queries.html) technology so we can't manage traffic routing 100% of the time. At this stage we do not have the technical ability to let users choose which server they will be connected to.
