### ISSUE TITLE
AdGuard Private DNS Release Notes don't fit on tablet browser page

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardDNS#872]
### Platform

Other

### Protocol

Regular

### Do you use AdGuard app?

Yes I am

### Issue Details

NA

### Expected Behavior

Release notes for Adguard Private DNS should fit entire screen.

### Actual Behavior

On iPad Safari browser and Samsung Android tablet browser the release notes for AdGuard Private DNS doesn't fit the entire screen even though the browsers are set to Desktop mode for tablets.

### Screenshots

![Screenshot_20241220_144702_Samsung Internet](https://github.com/user-attachments/assets/0294076c-bc9a-4ed3-8caa-79da3cd3ee49)
![signal-2024-12-20-14-49-40-356](https://github.com/user-attachments/assets/062bc03d-98c1-4999-b133-7844210d9a92)

**Comment by Chinaski1** [comment]
Internal ID: AGDNS-2624

**Comment by Chinaski1** [comment]
Fixed
