### ISSUE TITLE
http://zone.msn.com/ - can't play the game when DNS is on

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardDNS#89]
I am very pleased with the performance of Adguard DNS except I am unable to play the free online game Text Twist 2.
http://zone.msn.com/en/texttwist2/default.htm

**Comment by Alex-302** [comment]
It is caused by blocking 
```
fwmrm.net
```
added to dns filter:
```
@@||adm.fwmrm.net^
@@||fwmrm.net^
```

**Comment by Alex-302** [comment]
please check it after 3 hours

**Comment by ameshkov** [comment]
@Alex-302 this is a perfect example of why we need to use `exclusions` sometimes.

**Comment by ameshkov** [comment]
However, I am not sure if we should really unblock this domain.
Let it break zone.msn.com.

**Comment by Alex-302** [comment]
@ameshkov But where I can exit exclusions.txt?


> Let it break zone.msn.com.

this rule is too wide. Look on exclusions in English filter, many popular video players maybe broken by this rule.

**Comment by ameshkov** [comment]
> But where I can exit exclusions.txt?

You can't yet, unless new code is merged
