### ISSUE TITLE
[Feature Request] TLSv1.3 Support  dns.adguard.com

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [AdguardTeam/AdGuardDNS#89]
please enable TLSv1.3 for DoH  dns.adguard.com

**Comment by michaelb-ae** [comment]
i think it's a very good idea

**Comment by ameshkov** [comment]
Ehm, seems to be an obsolete issue, TLSv1.3 is enabled there for ages.
