### ISSUE TITLE
add some configuration to bypass firewalls

### ISSUE THREAD

**Issue by mpas97** [AdguardTeam/AdGuardDNS#90]
I use AdGuardDNS for many years now, on mobile devices such as desktop computers as I just love the ad free life.

But I still have the "issue" that many companies / networks are blocking DoH traffic. So my question is, if you could activate ESNI on your DNS server such that I can continue using the the service everywhere I am. Always having to change my DNS settings in the browser etc as soon as I changed wlan is quite annoying. Especially that afterwards I get spamed by all those ads in such networks. I also don't want to do without DNSSEC and all those sweet features your service provides. That's why it would really be great if you could do something against this "censorship".

**Comment by mpas97** [comment]
Quick update: Though ESNI would be quite nice, it wouldn't really solve my problem. Because ie. Firefox only uses ESNI after TRR was "started". As I would need ESNI on the adguard domain to start my TRR the whole thing turns into a chicken egg problem. As a workaround I created a proxy, so all my request are going through a non censored domain first. But there would surely be a better (and faster) solution.

**Comment by mpas97** [comment]
For my main machine I now set up dnscrypt-proxy with local DoH server for Firefox. The whole installation was done with a few commands (less than 10). Everything works fine now as the proxy can also do DNSCrypt for AdguardDNS.

**Comment by BirdInFire** [comment]
Warning bypass firewall can be against law or rules of the company, and if you work there it can be a motive to fire you.
(i warn to be sure you know).

**Comment by ameshkov** [comment]
Oh, sorry that we missed that question in the beginning. Using ESNI (it's ECH now btw) won't actually solve anything, IP addresses of the public DNS resolvers are well-known so regardless of whether you use ECH or not, it is obvious that this is a DOH server.

**Comment by mpas97** [comment]
The IP is known yes, but the requests are blocked based on SNI not on IP in my case. They just block anything that uses *dns* in the SNI domain part. That's why using dnscrypt now solves the issue. Same IP but no SNI :D

**Comment by ameshkov** [comment]
Well, alternatively you could use the IP address instead:

tls://94.140.14.14` or https://94.140.14.14/dns-query`

**Comment by mpas97** [comment]
This did not work as the IP was not included in the certificate. But apparently this changed in the meantime :)
Anyway as I found a way to have a working setup, I'm fine with closing this issue :)
