### ISSUE TITLE
Add bcrj1h7e.insight.ly to exceptions

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardDNS#90]
bcrj1h7e.insight.ly is a website used for login for members of the Insightly community and is incorrectly blocked by Adguard Familly Protection DNS.

From Windows 7 CMD:
-------------------------------

DNS Servers . . . . . . . . . . . : 176.103.130.132
                                    176.103.130.134

C:\Users\Danila>ping bcrj1h7e.insight.ly

Pinging family.block.dns.adguard.com [176.103.130.130] with 32 bytes of data:
Reply from 176.103.130.130: bytes=32 time=83ms TTL=54
Reply from 176.103.130.130: bytes=32 time=82ms TTL=54
Reply from 176.103.130.130: bytes=32 time=82ms TTL=54
Reply from 176.103.130.130: bytes=32 time=83ms TTL=54

Ping statistics for 176.103.130.130:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 82ms, Maximum = 83ms, Average = 82ms

Thank You!

**Comment by ameshkov** [comment]
Resolved already guys
