### ISSUE TITLE
[Question] Why is ip-api.com blocked?

### ISSUE THREAD

**Issue by Bluscream** [AdguardTeam/AdguardDNS#91]
I just wonder why
https://github.com/AdguardTeam/AdguardDNS/blob/766069b70f019b508803d86ed057d9b3611c9a57/Filters/filter.txt#L11291
exists. For me it looks like the API itself is pretty clean. Also i'm using the API in some of my userscripts and it just blocks it which is bad

Example URL: http://ip-api.com/#62.138.2.219

**Comment by ameshkov** [comment]
It is in both spyware and easyprivacy filters, and as I understand the purpose is just that: it is used by third-party scripts to obtain user's IP address.

**Comment by Bluscream** [comment]
It doesn't give out ip addresses of users. It can tell you geolocation of a user. I think thats pretty legimate. It's just like using MaxMinds GeoDB, but always up-to-date.

**Comment by ameshkov** [comment]
You have a point there.

I guess when https://github.com/AdguardTeam/AdguardDNS/pull/84 lands we can exclude it from the DNS filter.

What for spyware filter and easyprivacy, you can disable it on your own.

**Comment by Alex-302** [comment]
excluded from DNS filter
