### ISSUE TITLE
DNS can't resolve airbrake.io

### ISSUE THREAD

**Issue by audip** [AdguardTeam/AdGuardDNS#91]
**What happened?**

Airbrake.io can't be resolved from the Adguard DNS servers
```
 dig airbrake.io                                 (us-green/nutrition-prod)

; <<>> DiG 9.10.6 <<>> airbrake.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 28565
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;airbrake.io.			IN	A

;; ANSWER SECTION:
airbrake.io.		3600	IN	A	0.0.0.0

;; Query time: 56 msec
;; SERVER: 176.103.130.130#53(176.103.130.130)
;; WHEN: Sun May 24 16:18:27 PDT 2020
;; MSG SIZE  rcvd: 67
```

**What I expected to see?**

DNS resolve airbrake.io that I use for $WORK everyday.

Let me know if there are any questions or additional information needed from me.

**Comment by audip** [comment]
Technically, it should point at these DNS servers: https://dnschecker.org/#A/airbrake.io

**Comment by Archive5** [comment]
@audip Use Non-filtering DNS
dns-unfiltered.adguard.com 
See IP addresses https://adguard.com/en/adguard-dns/overview.html

**Comment by Alex-302** [comment]
Will be fixed.

**Comment by audip** [comment]
@Alex-302 @Archive5 does it still block ad-traffic or how is it different from the default AdGuardDNS servers?

**Comment by Alex-302** [comment]
@audip Do you say about another case? Which server is selected? Is DNS cache removed?(system and browser's)

**Comment by audip** [comment]
I'll give this test a try and report back
