### ISSUE TITLE
Incompatible with BBC Sport app on iOS

### ISSUE THREAD

**Issue by sclubone** [AdguardTeam/AdguardDNS#92]
Turning on this filter prevents the app from loading any content

**Comment by ameshkov** [comment]
Thanks for reporting it!

Also the same issue is opened in AdguardForiOS:
https://github.com/AdguardTeam/AdguardForiOS/issues/243

**Comment by Alex-302** [comment]
@sclubone which filters are you using? I can't reproduce your issue even with DNS filtering.

**Comment by sclubone** [comment]
Hi, this happens without any filters enabled and only the default adguard dns switched on. App and iOS are latest versions. Have deleted and reinstalled app but makes no difference.

On 29 Nov 2016, at 18:05, Alex <notifications@github.com> wrote:

@sclubone which filters are you using? I can't reproduce your issue even with DNS filtering.

**Comment by Alex-302** [comment]
Ok. Leave the filters disabled.
1. Close this app completely, go to Adguard DNS settings and enable DNS filtering log. 
2. Enable airplane mode and disable it after few seconds. 
3. Open DNS filtering log and clear it.
4. Open the app to reproduce the issue.
5. Open Adguard, go to DNS log and make screenshot.

**Comment by sclubone** [comment]
Thanks - DNS log screenshots attached






On 29 Nov 2016, at 19:32, Alex <notifications@github.com> wrote:

Ok. Leave the filters disabled.

Close this app completely, go to Adguard DNS settings and enable DNS filtering log.
Enable airplane mode and disable it after few seconds.
Open DNS filtering log and clear it.
Open the app to reproduce the issue.
Open Adguard, go to DNS log and make screenshot.

**Comment by Alex-302** [comment]
Not attached. Please reply directly on github without quote.

**Comment by sclubone** [comment]
![img_7306](https://cloud.githubusercontent.com/assets/24208390/20729862/ba4e3e26-b67b-11e6-97eb-a215ac824eca.PNG)
![img_7307](https://cloud.githubusercontent.com/assets/24208390/20729864/ba509658-b67b-11e6-961a-8e0237a8a394.PNG)
![img_7308](https://cloud.githubusercontent.com/assets/24208390/20729863/ba4f16de-b67b-11e6-800f-62ac905c6533.PNG)
![img_7309](https://cloud.githubusercontent.com/assets/24208390/20729865/ba748f04-b67b-11e6-8611-a817e7e71738.PNG)

**Comment by Alex-302** [comment]
Excluded from DNS filter:
```
sa.bbc.com
```

**Comment by Alex-302** [comment]
Check it tomorrow.

**Comment by sclubone** [comment]
Have checked but unfortunately still being blocked - the log (as before) shows that sa.bbc.co.uk is still being blocked?

On 30 Nov 2016, at 18:32, Alex <notifications@github.com> wrote:

Check it tomorrow.

**Comment by Alex-302** [comment]
This domain was removed from DNS filter. I don't know why it is blocked on you end.

**Comment by sclubone** [comment]
It's only blocked if I turn on adguard dns.. think I will revert to normal adguard 

On 2 Dec 2016, at 22:00, Alex <notifications@github.com> wrote:

This domain was removed from DNS filter. I don't know why it is blocked on you end.

**Comment by sclubone** [comment]
Hi, clearly there has been no change - sa.bbc.co.uk and gate.hockeyapp.net are still being blocked as reported so whatever has been done is incomplete. Have you determined a resolution? 

Otherwise, seem likely that this type of issue will affect other legit apps, etc and negates the point of paying for adguard, or the lack of any user-level whitelisting - why not show users blocked dns-level domains and allow the user to exclude? It would be a better experience than having to correspond via this forum!!


On 2 Dec 2016, at 22:00, Alex <notifications@github.com> wrote:

This domain was removed from DNS filter. I don't know why it is blocked on you end.

**Comment by sclubone** [comment]
Just to add, whitelisting the blocked domains via adguard has no effect when adguard dns is on - if this is the case then whitelisting should either work or not be shown as a false user-configurable setting.


On 5 Dec 2016, at 10:55, Sailesh Patel <saileshgroups@gmail.com> wrote:

Hi, clearly there has been no change - sa.bbc.co.uk and gate.hockeyapp.net are still being blocked as reported so whatever has been done is incomplete. Have you determined a resolution? 

Otherwise, seem likely that this type of issue will affect other legit apps, etc and negates the point of paying for adguard, or the lack of any user-level whitelisting - why not show users blocked dns-level domains and allow the user to exclude? It would be a better experience than having to correspond via this forum!!


On 2 Dec 2016, at 22:00, Alex <notifications@github.com> wrote:

This domain was removed from DNS filter. I don't know why it is blocked on you end.

**Comment by Alex-302** [comment]
Please reply directly on the site, or remove unnecessary self-quoting.

Did you try to disable filters(spyware)?

**Comment by sclubone** [comment]
Yes, no filters are enabled as per original replies.

On 5 Dec 2016, at 11:43, Alex <notifications@github.com> wrote:

Please reply directly on the site, or remove unnecessary self-quoting.

Did you try to disable filters(spyware)?

**Comment by Alex-302** [comment]
> Please reply directly on the site, or remove unnecessary self-quoting.

**Comment by ameshkov** [comment]
> Just to add, whitelisting the blocked domains via adguard has no effect when adguard dns is on

Btw, this will change in the new version.

**Comment by ameshkov** [comment]
Just checked `sa.bbc.co.uk` and it is ok. 
```
$ nslookup sa.bbc.co.uk 176.103.130.130
Server:		176.103.130.130
Address:	176.103.130.130#53

Non-authoritative answer:
Name:	sa.bbc.co.uk
Address: 77.72.116.213
```

Can't say the same about `gate.hockeyapp.net`:
```
$ nslookup gate.hockeyapp.net 176.103.130.130
Server:		176.103.130.130
Address:	176.103.130.130#53

Non-authoritative answer:
Name:	gate.hockeyapp.net
Address: 127.0.0.1
```

@Alex-302 I've excluded it from the DNS filter.
@sclubone changes should go online in a few hours.

**Comment by sclubone** [comment]
Thanks, the app is mostly working okay but various content (e.g. videos) do throw up an initial error, needing a refresh to clear - from DNS log it looks like Static.chartbeat.com also needs to be whitelisted. 

From a usability perspective, will whitelists be able to sync across devices? Otherwise all settings will nerd to be manually replicated for users with multiple iOS devices.


On 5 Dec 2016, at 22:54, Andrey Meshkov <notifications@github.com> wrote:

Just checked sa.bbc.co.uk and it is ok.

$ nslookup sa.bbc.co.uk 176.103.130.130
Server:		176.103.130.130
Address:	176.103.130.130#53

Non-authoritative answer:
Name:	sa.bbc.co.uk
Address: 77.72.116.213
Can't say the same about gate.hockeyapp.net:

$ nslookup gate.hockeyapp.net 176.103.130.130
Server:		176.103.130.130
Address:	176.103.130.130#53

Non-authoritative answer:
Name:	gate.hockeyapp.net
Address: 127.0.0.1
@Alex-302 I've excluded it from the DNS filter.
@sclubone changes should go online in a few hours.

**Comment by ameshkov** [comment]
> From a usability perspective, will whitelists be able to sync across devices? Otherwise all settings will nerd to be manually replicated for users with multiple iOS devices.

We're working on the sync functionality. The thing is that it requires much time as sync should work across all Adguard products.

**Comment by ameshkov** [comment]
@Alex-302 try whitelisting `edigitalsurvey.com`

**Comment by Alex-302** [comment]
@ameshkov 
>  try whitelisting edigitalsurvey.com

added to exclusions. But why?
