### ISSUE TITLE
No connection

### ISSUE THREAD

**Issue by beerisgood** [AdguardTeam/AdGuardDNS#92]
Today I can't make any connection with enabled 
"dns.adguard.com"
In Android. Is the service down?

**Comment by AfroThundr3007730** [comment]
Since about an hour ago, I can no longer resolve queries using either DoT or DNS to adguard servers. This is both on my phone and on my laptop.

**Comment by beerisgood** [comment]
Identified - The problem is identified, we're working on the fix
May 28, 05:54 UTC

From status page.

**Comment by beerisgood** [comment]
Fixed.
