### ISSUE TITLE
Several porn sites not blocked by family filter

### ISSUE THREAD

**Issue by Tomatoide** [AdguardTeam/AdGuardDNS#93]
porn.com
pornhd.com
whataporn.tv
youjizz.com
eporner.com

**Comment by primarto** [comment]
+ porn site from Balkan

https://www.pornicisrbija.com/
https://www.balkanjizz.com/
https://www.balkancum.com/
https://m.porn555.com
http://www.goldpornfilms.com/sl/
https://domacedevojke.com/
https://www.pinkporno.xxx/
https://besplatniporno.com/
https://pornici.rs/
http://www.domacipornici.org/
https://www.pornici.eu/

**Comment by Rru247** [comment]
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/399

**Comment by mfawaz24** [comment]
Still more:
https://brazzersnetwork.com

Probably a dozen unblocked sites seem hosted by https://e702fa7de9d35c37.com, including but not limited to:
https://xnxx.rest
https://brazzersnetwork.pro
