### ISSUE TITLE
DNS filter blocks Samsung from receiving updates

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardDNS#93]
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=55506305

**Comment by sandybeachit** [comment]
Has anyone confirmed this issue is now resolved? I have a rooted Samsung so can't test.

I do know that if users are using a rooted android device Samsung will block any updates as the phone is rooted.

I'm this case is the users phone definitely not rooted?

**Comment by vozersky** [comment]
As far as I know, not yet. 
This will require an additional checking before we can close it.

**Comment by vozersky** [comment]
We've made a lot of changes recently.
And I can't confirm this bug so far.
Let's close it for now and reopen if the issue occurs again.
