### ISSUE TITLE
Incorporate more regional filter lists

### ISSUE THREAD

**Issue by seanl-adg** [AdguardTeam/AdguardDNS#95]
People outside of English-speaking country have to use language-specific filters in addition to English filter to experience better Ad blocking.
For example,  176.103.130.135: default + Russian filter,  176.103.130.136: default + German filter....

**Comment by ameshkov** [comment]
I rly suppose we should simply add regional ad servers to the specific domain filter as well.

But to do it we should first identify sources for these ad servers properly.

@Alex-302 which file is for ad servers in Russian filter?

**Comment by Alex-302** [comment]
@ameshkov 
`adservers.txt` and `adservers_firstparty.txt`(it is not big)

**Comment by Snapy** [comment]
Maybe you could have categories like OpenDNS has but for regions (although it is account based).

**Comment by ameshkov** [comment]
@Snapy this implies providing accounts functionality on our side just like OpenDNS does.

This is possible in future, but for now we need an easier solution.

@seanl-adg what file can we use as source of ad servers in List-KR?
@Alex-302 what about EasyList Germany? Do they have an "adservers" file?

**Comment by Alex-302** [comment]
@ameshkov 
> @Alex-302 what about EasyList Germany? Do they have an "adservers" file?

Yes.
`easylistgermany_adservers.txt`
`easylistgermany_adservers_popup.txt`
https://hg.adblockplus.org/easylistgermany/file/tip/easylistgermany

**Comment by seanl-adg** [comment]
@ameshkov filter.txt for List-KR.

**Comment by snhv** [comment]
Here is the adserver list for Vietnamese which I'm maintaining:
https://github.com/snhv/Vietnamese-hosts

**Comment by ameshkov** [comment]
@snhv AG DNS supports ad blocking rules syntax. The list would be much shorter if you convert it:
```
!
! eclick
!
||eclick.vn^
!
! admicro
!
||admicro.vn^
!
! vcmedia
!
||admicro*.vcmedia.vn^
||adi.vcmedia.vn^
||vcplayer.vcmedia.vn^
||video-thumbs.vcmedia.vn^
||static.hosting.vcmedia.vn^
!
! adnetwork
!
||adnetwork.vn^
!
! adtima
!
||adtimaserver.vn^
!
! ad360
!
||ad360.vn^
!
! anthill
!
||anthill.vn^
!
! ants
!
||ants.vn^
!
! polyad
!
||polyad.net^
!
! epi
!
||epi.vn^
!
! ambient-platform
!
||ambient-platform.com^
!
! vnecdn
!
||st.f1.vnecdn.net^
||qc.st.f1.vnecdn.net^
||c0.f37.img.vnecdn.net^
||c0.f38.img.vnecdn.net^
||raovat.vnecdn.net^
||img.f1.raovat.vnecdn.net^
||img.f2.raovat.vnecdn.net^
||img.f3.raovat.vnecdn.net^
||img.f4.raovat.vnecdn.net^
||st.f2.raovat.vnecdn.net^
||st.f3.raovat.vnecdn.net^
||shop.vnecdn.net^
||img.f1.shop.vnecdn.net^
||img.f2.shop.vnecdn.net^
||img.f3.shop.vnecdn.net^
||img.f4.shop.vnecdn.net^
!
! vnexpress
!
||raovat.vnexpress.net^
!
! tuoitre
!
||s.tuoitre.vn^
!
! thanhnien
!
||quangcao.thanhnien.vn^
!
! 24
!
||game.24h.com.vn^
||thongke.24h.com.vn^
||24hstatic.com
!
! zing
!
||log.news.zing.vn^
!
! fptad
!
||fptad.com^
!
! mookie1
!
||mookie1.com^
!
! sparkling
!
||sparkling.vn^
!
! nixcdn
!
||stc.nas.nixcdn.com^
!
! a1515150
!
||a1515150.com^
!
! novanet
!
||novanet.vn^
!
! vimobi
!
||vimobi.com^
!
! channelvn
!
||channelvn.net^
!
! ad.org
!
||ad.org.vn^
!
! adap
!
||adap.tv^
```

Not sure about `onthe.io`, though. As I recall, blocking it may cause issues with some websites.

What for others, we can add this modified list right away.

**Comment by snhv** [comment]
Thank you @ameshkov 

Under your cue, I have modified and also updated the filter accordingly.

Please note that I changed the ads filter's name and URL. Now it is at:
https://github.com/snhv/vietnamese-domain-filters/blob/master/ads

And I also added the adults filter, to be used with Family Protection DNS, here:
https://github.com/snhv/vietnamese-domain-filters/blob/master/adults

**Comment by ameshkov** [comment]
@snhv nice, thank you!

However, we don't have a separate filter for Family Protection DNS just yet, for now we'll add `ads` only.

@Alex-302 could you please do it?

**Comment by Alex-302** [comment]
@ameshkov these two files? Only to DNS filter?

**Comment by ameshkov** [comment]
@Alex-302 

1. ads only
2. yes

**Comment by Alex-302** [comment]
Ok.
`https://github.com/snhv/vietnamese-domain-filters/blob/master/ads`
added to DNS filter, except
```
||game.24h.com.vn^&third-party
||collagenbeauty.vn^&third-party
```

**Comment by snhv** [comment]
Hi @Alex-302 , I've just added 3 more domains for Vietnamese filter:
||imgraovat.vnecdn.net^
||straovat.vnecdn.net^
||imgraovat.vnexpress.net^

Thanks.

**Comment by Alex-302** [comment]
I can't just add these domains to DNS filter, I need examples.

**Comment by snhv** [comment]
Hi @Alex-302 , for the first 3 domains, please visit vnexpress.net or vitalk.vn ; for the last one, please thuvienphapluat.vn
Thanks

**Comment by vozersky** [comment]
obsolete

**Comment by snhv** [comment]
Hi,

Could you please consider adding these lists:
- ABPVN hosts list (https://abpvn.com/android/abpvn.txt) - homepage: https://abpvn.com/android/
- HostsVN hosts list (https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts) - homepage: https://github.com/bigdargon/hostsVN

Thank you.

**Comment by ameshkov** [comment]
@snhv hi! moved to a separate issue:https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/6
