### ISSUE TITLE
AdGuardDNS support zones .lib, .emc .bazar *.coin other...

### ISSUE THREAD

**Issue by edgiru** [AdguardTeam/AdGuardDNS#95]
I would like to see domain zones in DNS support: Emercoin (EMCDNS: .lib, .emc .bazar *.coin)
![image png ce46e30b66c9f82296ed81d6594aa7e5](https://user-images.githubusercontent.com/4624056/84579967-319c6e80-addb-11ea-8318-45a193b35bf9.png)

**Comment by ammnt** [comment]
https://github.com/AdguardTeam/AdGuardDNS/issues/66

**Comment by ameshkov** [comment]
Marked as dup for now
