### ISSUE TITLE
Facebook virus redirect

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardDNS#96]
These appear in my dns logs. Leading to a fake survey

tracking.trksrv.com
tracking.crobo.com
tracking.trackmobistore.com
voluumtrk2.com
www.bundasnovinhas.com
click.newviralmobistore.com
cdnaws.mobidea.com

**Comment by ameshkov** [comment]
Huh, any idea what app sends it?

**Comment by jo2dan23** [comment]
I clicked on a Facebook video in Facebook app and I guess it was fake or something

**Comment by Alex-302** [comment]
Blocked(100% advertising):
```
voluumtrk2.com
bundasnovinhas.com
newviralmobistore.com
```
