### ISSUE TITLE
Possible phishing website is not blocked in AdGuardDNS

### ISSUE THREAD

**Issue by bilal-guvenc** [AdguardTeam/AdGuardDNS#97]
When I clicked http://www.playtcubed.com/ in the chrome web store page
https://chrome.google.com/webstore/detail/colorful-rubiks-cube/ndmelloaocjpkhmajmkdbbhimohlclkd?hl=en&utm_source=chrome-ntp-launcher
Below site is opened and it seems a phishing website. When you reopen the page, it shows another phishing website in the same url always.

https://hstavern12.live/4456363710/?utm_campaign=QPF8euu28II5lw7O2iHhCugVqK5RzfdNsTpLaMM91qY1&t=main9&f=1&sid=t4~zdokqfonmozctu2erewwyhuf&fp=vjNkUWDztCWl5ybaR6ui31Y42ExbkzvjTOoVIp%2FNiASZ%2BHq5St50CLJw4KjbtoxONPMxLA4wTZ3XYnoObzj3zMgnyjo8metJ%2FROeFi4Z2a%2F0IkU%2FnyuWkoiVfHiNKiCOnNhGsRocOezm9t3KGeiYelfoS5ZTnQP%2Blzid0nK0HQGyHrPwLevzHQAycF%2FQrTnBUlKFiO1A8x7%2BwRZy7Fvo9QFEKPu4%2F0AxX4jI8TUvCSPf%2FdFYc2AlunhnBrUL2RKwDfybMQgx%2BWvPTZlxr%2BBaT9KruDHY1HAMyX4QBGgUzDTllsveDDbSAdarCvqbLLmzyDw8pxyxOnnRZ9wK%2FIPwPd0wde2O23yGA16AWX7sInR%2BMvJcCwaXSiSFP2%2BZFGzRpEsvvg3YnrEC3qOX5q582Zh8o%2BSRSyUAx3ea36pPgnn7vE0iR%2BvA6jw0l0wprny5b2VKYk3MdHJm3YBdpLpumJtCOtvB1p8gn%2BrezcBAjGMXkluAYQMUY%2B4bbYdf9HWFX41yZFNUHUlOr8UXb4qySjNiEFOwU9JeUI1mTadH%2FpgQ9XPubTT92%2BOTZza6fM8dhLoeWo79zf6kydT%2FGaRyR%2Fo6gEwWU%2F75OjCg0f5eSxwTTmqJpwmuUSm2rRmFoHNjopthRPG7jopkCVazifQA5s50MJll%2Fl87N8UnpEYgPXxdpJamOLv2BLy7KkhxsKekXwlUvMHx2yVxMZ1PlEEBAyCFueg3psx6ftjmtkcC0viOWZy3JLCtrGCTUicjWQrJR%2FZfwoXn4ZOPntDkgUfohMansd33XharsuE9Bd2%2FKjrkgkQyfboX0eEW4Mvx5slpRO0SZMgArtlKEKMmig3Tq0MZ06G5pr3DR2rFlUrhEmS0F8h4D2CfBjTB%2BnMdCK%2BgbGf6%2FgiaFwbjkcGqDGm3aviJOvh4Aby6PF0QDxhXqBThY9cpeVnXBAM0raLAvOTToKNAtUrzGyvTa%2BOUtzeOoAQ2DKccsBNdGH4%2BaQJcnxjnyaLYMlgDgMXzS%2FKhUowscs1NNYb%2BSDOmlRaoEuCEOBGZsEr4zjLCb1Jl9YneKDEBdOW%2B8Fq32zNaY9eNR9ZY%2BHYaS4zTOFs1GLMvnmbqk%2F0ya9B7c%2BpLfGCIiC8u%2FN1wYA%2FS0WXInc4dbxHJTHxxOiVQP%2FbxPuPEfUUIPbAaZOoN%2FrufdK9QxLdJFSI0CEqlqCOu1xS3ZER1D%2FXBxyB9wcjvY%2Fw7%2BO3%2FesN1%2FD2XUN4Nt3b%2BtrtDrdsJ0r4tZykO3orZOB2fXvuyXdf%2Fw%2BbUz3GCcAgHCKBA1lVbLIxDXiRsrt7sV2sbsjNUdbmcQUujE9I93SSYAuP%2FXytQt5kG%2FQgDNTJ8MSSdBeV0BedE7onJO4vi5p7QMhNGjl7Ao9mriIBB%2BfYg67dcCbUXkwCiIlDvLV6f0aFszfCX3tX%2B0z5K2OtudVXI4o4wwYlVVPw%3D

**Comment by bilal-guvenc** [comment]
Also this website is related with above phishing website https://c.bestdealfor21.life/newrobot_12/index.html?c=28c2aa22-fbb6-4719-8ad1-738f3065e8e5&a=l74625# which was shown after reopening the page.

**Comment by Chinaski1** [comment]
Thank you for the report.
We have added these websites to the blacklist:

- c.bestdealfor21.life
- hstavern12.live
