### ISSUE TITLE
Adguard DNS blocks Google Play downloads on Android

### ISSUE THREAD

**Issue by pghant** [AdguardTeam/AdguardDNS#97]
I'm not able to download new apps or update existing ones after enabling Adguard DNS on my Android phone. Disabling the DNS resolves the issue again.

**Comment by Alex-302** [comment]
what DNS servers are you using?

**Comment by pghant** [comment]
I'm using
176.103.130.130
176.103.130.131

**Comment by Alex-302** [comment]
Not reproduced. 
@vozersky please слусл it on your device

**Comment by vozersky** [comment]
@Alex-302 can't reproduce
@pghant could you please give us more details on steps to reproduce/details, soft you use etc.

**Comment by ameshkov** [comment]
Guys, this is clearly not about DNS, but about the way it is enabled.

@pghant do you have Nougat? How exactly did you enable AG DNS on it?

**Comment by pghant** [comment]
I'm using an app that creates a local VPN with the Adguard DNS. After some more testing it does appear that it's the app causing the issue not the DNS. I have the same issue if I use Google DNS with the same app. Closing the issue.

**Comment by ameshkov** [comment]
Yeah, this is a known bug in Android Nougat.

Changing DNS settings through VPN API ends in breaking the Download Manager app.
