### ISSUE TITLE
||xm0siulufost.com^

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdGuardDNS#98]
Seems to be a new ad host used by a few image boards.

**NSLOOKUP**
nslookup xm0siulufost.com dns.adguard.com
Server:  176-103-130-131.dns.adguard.com
Address:  176.103.130.131

Non-authoritative answer:
Name:    xm0siulufost.com
Addresses:  192.243.59.13
          192.243.59.12
          192.243.59.20

**Comment by Alex-302** [comment]
added
