### ISSUE TITLE
Mediametrics на iOS вылетает 

### ISSUE THREAD

**Issue by Flammable777** [AdguardTeam/AdguardDNS#99]
iPhone 7, последняя прошивка, без джейла, после установки Adguard Pro и включении Adguard DNS, приложение Mediametrics  не запускается (вылетает на старте). Хороший агрегатор новостей, но при этом рассадник рекламы... Что посоветуете?

**Comment by Flammable777** [comment]
Похоже, я не в ту ветку написал. Перенесите в iOS плз.

**Comment by vbagirov** [comment]
@Flammable777 насколько я знаю, прям перенести нельзя. Надо создать новый таск там, а этот закрыть.
