### ISSUE TITLE
AdGuard encrypted DNS is super slow and is not using the nearest servers

### ISSUE THREAD

**Issue by andreldmonteiro** [AdguardTeam/AdGuardDNS#99]
I'm using a Switzerland, Europe IP address and AdGuard DNS servers map says I'm using the Seoul DNS servers, this doesn't make any sense, because of that, internet speed is super slow with AdGuard DNS compared to other DNS servers, tested with DNS-over-TLS and DNS-over-HTTPS.

**Comment by ameshkov** [comment]
Could you please show the output of this command?
`traceroute 176.103.130.130`

**Comment by monterrr** [comment]
Here it is: https://gist.github.com/monterrr/6d64f62229db1d1d6793f14206cb3d18

**Comment by ameshkov** [comment]
Thank you! This may take quite some time to resolve as this is a routing issue, but we'll do what we can to fix this.

**Comment by monterrr** [comment]
Is this a misconfiguration on your part or someone else? If so who is causing this exactly?

**Comment by ameshkov** [comment]
Here's how it works:

1. We announce the same IP address from different servers all over the world.
2. The server that will be used is selected based on the shortest "route" from you to that server.
3. As this is a network route, the shortest route is not necessarily the same as the shortest geographical route.

So this is rather complicated, the route depends on both your ISP and our servers connectivity. We can change it a little bit by making other routes "longer", but it may mess up connectivity for other users. Generally, the only feasible way is for us to add more servers that use different network providers, this way we can minimize the rate of such issues.

**Comment by monterrr** [comment]
I guess there is no way to manually choose the server location on my part? I'm forwarding the DNS queries to your servers using the unbound server.

**Comment by ameshkov** [comment]
> I guess there is no way to manually choose the server location on my part? 

Not really:(

> I'm forwarding the DNS queries to your servers using the unbound server.

Btw, have you considered AdGuard Home?

**Comment by monterrr** [comment]
Actually I have a pfsense server that served the DNS queries, I checked and adguard home isn't on the package list of pfsense so I can't consider it.

**Comment by Sandro-mi** [comment]
Hello, i have the same issue in Belgium. My isp is edpnet, my dns requests are redirected to Tokyo or Seoul, exactly to this address: 141.164.44.161.
I tried unencrypted and  DoH and i have the same issue. I installed AdGuardHome and i tried first the normal adguard dns and later DoH but i'm steel been rerouting to Asia. This is happening since 1 or 2 weeks. Before my dns requests were redirected to Amsterdam, Paris, sometimes to Frankfurt, that was pretty perfect, from the place i live  the ping is 12 ms to Amsterdam, 18 to Paris, 20 to Frankfurt. For now i'm running AdGuardHome with other public dns servers :-(  I have no problem with my mobile network provider,  adguard for android sends my dns requests to Paris or to Amsterdam. Thank you fo your attention

**Comment by Sandro-mi** [comment]
> Hello, i have the same issue in Belgium. My isp is edpnet, my dns requests are redirected to Tokyo or Seoul, exactly to this address: 141.164.44.161.
> I tried unencrypted dns and DoH and i have the same issue. I installed AdGuardHome and i tried first the normal adguard dns and later DoH but i'm steel been rerouting to Asia. This is happening since 1 or 2 weeks. Before my dns requests were redirected to Amsterdam, Paris, sometimes to Frankfurt, that was perfect for the place where i live. For now I'm running AdGuardHome with other public dns servers :-( I have no problem with the network of my mobile cellphone provider, adguard for android sends my dns requests to Paris or to Amsterdam. Thank you for your attention P.S. I'm not running any vpn that changes my location

Hello, since today adguard dns sends my requests to the resolver in Amsterdam..like before,  excellent.

**Comment by Sandro-mi** [comment]
Hello, since today adguard dns sends my requests to the resolver in Amsterdam..exactly like before,  excellent. The issue seems to be ended, thank you!

**Comment by monterrr** [comment]
I've tested and it was sending me to London right now, much better and faster but not perfect and it's again sending to Seoul just a moment after it was better.

**Comment by ameshkov** [comment]
Please keep us informed，we're making some changes to routing right now

**Comment by monterrr** [comment]
It's sending me to London right now, big improvement but I think you have nearer servers than that for Switzerland.
Traceroute: https://gist.github.com/monterrr/39bfcf90897d1a9b7a1ee20d87f79e49

**Comment by ravibaskaran** [comment]
I have the same problem. I live in India but the Adguard DNS takes me to London :(. Here is my traceroute - https://gist.github.com/ravibaskaran/4608ddfcaac39e13aad49c4a85d7b68c

**Comment by monterrr** [comment]
It's now better, now it's sending me to Amsterdam but Frankfurt and Paris are closer to me:
https://gist.github.com/monterrr/9435aa835ef050d6a59704a6d3ab5f9e

**Comment by hampton8** [comment]
I'm based in the UK, pretty close to London, using my real IP address and I can see on the [AdGuardDNS page](https://adguard.com/en/adguard-dns/overview.html) that you do have a server in London. However, I am consistently (as in 100% of the time) being connected to the Amsterdam DNS server according to [DNSLeakTest.com](dnsleaktest.com) and the [AdGuardDNS map](https://adguard.com/en/adguard-dns/overview.html)?!

![DNS Leak Test results](https://user-images.githubusercontent.com/75634978/101394089-f083a380-38bf-11eb-8bf3-78ee99cfb993.png)

![AdGuardDNS Map results](https://user-images.githubusercontent.com/75634978/101394115-f6798480-38bf-11eb-8b48-baffae832c0e.png)

@ameshkov, here is my traceroute: https://gist.github.com/hampton8/fb18bead119f940b34e3d2271e690d31

NextDNS and 1.1.1.1 always connect me to a London DNS server when I use them, so I'm not sure why AdGuardDNS is behaving differently?

**Comment by Sandro-mi** [comment]
Hi, I live in Belgium and since I use the new dns addresses, I have a weird routing issue. I have a dual stack ipv4/ipv6 connection, the IPv6 requests are redirected to Amsterdam or Paris, while the IPv4 requests are redirected to the USA . Maybe it's because of my isp, I put here the traceroutes, one for ipv4 and the other for ipv6.
![Capture d’écran du 2020-12-08 09-02-10](https://user-images.githubusercontent.com/67803134/101457830-50b52c80-3936-11eb-9c3b-ee419e2eb67b.png)
![Capture d’écran du 2020-12-08 09-05-35](https://user-images.githubusercontent.com/67803134/101457843-53b01d00-3936-11eb-8dfc-639677a42904.png)

**Comment by monkitrainer** [comment]
I'm located in NY, US and having extremely slow DNS response since few days ago. It seems I'm connected to Singapore DNS servers when using Adguard DNS servers (94.140.14.14, 94.140.15.15):

<img width="1055" alt="Screen Shot 2020-12-13 at 1 07 50 PM" src="https://user-images.githubusercontent.com/75947617/102019969-5484ec80-3d44-11eb-967d-e2cbe293de2b.png">

```
➜  ~ traceroute 94.140.14.14
traceroute to 94.140.14.14 (94.140.14.14), 64 hops max, 52 byte packets
 1  192.168.50.1 (192.168.50.1)  1.157 ms  0.793 ms  0.681 ms
 2  * * *
 3  b3332.nycmny-lcr-22.verizon-gni.net (130.81.221.222)  6.900 ms  8.904 ms  5.486 ms
 4  * * *
 5  0.ae4.br2.nyc4.alter.net (140.222.1.61)  20.572 ms
    0.ae3.br2.nyc4.alter.net (140.222.1.59)  5.805 ms
    0.ae4.br2.nyc4.alter.net (140.222.1.61)  5.947 ms
 6  63-218-223-149.static.pccwglobal.net (63.218.223.149)  7.067 ms  5.682 ms  6.599 ms
 7  hundredge0-4-0-0.br04.sin02.pccwbtn.net (63.223.34.138)  251.800 ms  251.900 ms  268.711 ms
 8  63.217.24.86 (63.217.24.86)  244.919 ms  244.019 ms  246.431 ms
 9  * * *
10  * * *
11  * * *
12  dns.adguard.com (94.140.14.14)  249.764 ms  244.504 ms  237.768 ms
```

**Comment by rodaimi** [comment]
I have also been experiencing severe latency using Adguard DNS. I'm located in NYC however, dnsleak.com as well as the adguard DNS map show that I am using a server in Japan.

Traceroute from my iPhone is attached below.
```
Host Name or IP Address: dns.adguard.com
Time: 2021-02-05 22:57:08 +0000

Warning: dns.adguard.com has multiple addresses; using 94.140.14.14
traceroute to dns.adguard.com (94.140.14.14) , 5 relative hops max, 52 byte packets
   1 192.168.2.1 (192.168.2.1) 1.991 ms 194.591 ms 197.152 ms
   2 192.168.1.1 (192.168.1.1) 2.492 ms 206.944 ms 209.770 ms
   3  * * *
   4 100.41.25.214 (100.41.25.214) 17.003 ms 846.831 ms 849.949 ms
   5 0.csi1.grcynygc-mse01-bb-su1.alter.net (140.222.3.206) 9.148 ms 1890.725 ms 1894.087 ms
   6  * * *
   7 0.ae3.br2.nyc4.alter.net (140.222.1.59) 9.118 ms 1840.356 ms 1843.711 ms
   8 63.218.223.149 (63.218.223.149) 8.099 ms 1096.067 ms 1099.663 ms
   9 63.218.250.173 (63.218.250.173) 174.077 ms 557.433 ms 560.931 ms
 10 63.216.242.46 (63.216.242.46) 270.249 ms 1502.706 ms 1506.418 ms
 11  * * *
 12  * * *
 13  * * *
 14 dns.adguard.com (94.140.14.14) 279.862 ms 477.460 ms 487.881 ms

Host Name or IP Address: dns.adguard.com
Time: 2021-02-05 23:08:34 +0000

Warning: dns.adguard.com has multiple addresses; using 94.140.15.15
traceroute to dns.adguard.com (94.140.15.15) , 5 relative hops max, 52 byte packets
   1 192.168.2.1 (192.168.2.1) 1.393 ms 9.139 ms 10.721 ms
   2 192.168.1.1 (192.168.1.1) 2.104 ms 3.638 ms 5.188 ms
   3  * * *
   4 100.41.25.216 (100.41.25.216) 15.243 ms 733.426 ms 739.441 ms
   5 0.csi1.whplnywp-mse01-bb-su1.alter.net (140.222.3.212) 8.136 ms 1728.092 ms 1732.118 ms
   6  * * *
   7 0.ae4.br2.nyc4.alter.net (140.222.1.61) 13.969 ms 1186.580 ms 1190.054 ms
   8 63.218.223.149 (63.218.223.149) 9.951 ms 205.208 ms 209.442 ms
   9 63.218.250.173 (63.218.250.173) 174.737 ms 369.201 ms 372.951 ms
 10 63.216.242.46 (63.216.242.46) 177.384 ms 181.158 ms 184.592 ms
 11  * * *
 12  * * *
 13  * * *
 14 dns.adguard.com (94.140.15.15) 199.000 ms 409.697 ms 414.865 ms

```

**Comment by dj02** [comment]
I have also been experiencing more latency using Adguard DNS. I live in finland, helsinki. stockholm shold be the nearest server but it routes to frankfurt, germany?

![Näyttökuva 2021-09-22 123118](https://user-images.githubusercontent.com/7875447/134319979-ab198bb7-b2f6-4537-896f-a7d297f5d70b.jpg)
![Näyttökuva 2021-09-22 123346](https://user-images.githubusercontent.com/7875447/134319995-8c332d13-1bea-47de-af31-ffd5ea3071f2.jpg)
![Näyttökuva 2021-09-22 123710](https://user-images.githubusercontent.com/7875447/134320252-13692301-4a65-4f93-89de-52f5ff69d48c.jpg)

**Comment by ameshkov** [comment]
Hello to everyone.

If you have a problem with routing to AdGuard DNS, here's what we need to know:

1. Your country
2. Your Internet Service Provider
3. Results of running the following 3 commands:

```
traceroute 94.140.14.14
traceroute 94.140.15.15
traceroute 2a10:50c0::ad1:ff
```

**Comment by ameshkov** [comment]
@monkitrainer your traffic goes through Orange ISP.

We've been able to get rid of it, but now it's rerouted through Vodafone (checking it [here](https://enterprise.verizon.com/why-verizon/looking-glass/)):

```
traceroute to 94.140.14.14 (94.140.14.14), 30 hops max, 52 byte packets
 1  0.ae14.GW14.NYC1.ALTER.NET (140.222.235.131)  1.118 ms  0.939 ms  0.795 ms
 2  vodafone-gw.customer.alter.net (204.148.1.254)  1.854 ms  1.187 ms  1.132 ms
 3  ae3-xcr1.nyh.cw.net (195.2.16.133)  88.537 ms ae0-xcr1.nyh.cw.net (195.2.25.70)  89.336 ms ae3-xcr1.nyh.cw.net (195.2.16.133)  88.376 ms
     MPLS Label=30087 CoS=0 TTL=1 S=1
 4  et-10-1-5-xcr1.ptl.cw.net (195.2.24.242)  88.288 ms  88.350 ms  88.167 ms
     MPLS Label=968129 CoS=0 TTL=1 S=1
 5  ae1-pcr1.fnt.cw.net (195.2.9.125)  81.357 ms  96.249 ms  82.086 ms
     MPLS Label=917906 CoS=0 TTL=1 S=1
 6  ae4-ucr1.czs.cw.net (195.2.10.233)  88.303 ms  88.395 ms  88.352 ms
 7  * * *
 8  cst2-254-1.cust.vodafone.cz (31.30.254.1)  88.653 ms  89.203 ms  88.573 ms
 9  cst2-191-18.cust.vodafone.cz (31.30.191.18)  93.927 ms  93.841 ms  94.600 ms
10  dns.adguard.com (94.140.14.14)  95.012 ms  94.453 ms  110.695 ms
```

We're looking how to get rid of that route.

**Comment by ameshkov** [comment]
@monkitrainer please check it again. Hopefully, the issue is resolved now for Verizon.

**Comment by monkitrainer** [comment]
@ameshkov thanks! much better now

```
➜  ~ traceroute 94.140.14.14
traceroute to 94.140.14.14 (94.140.14.14), 64 hops max, 52 byte packets
 1  rt-70b0 (172.19.1.1)  0.980 ms  0.637 ms  0.689 ms
 2  * * *
 3  b3332.nycmny-lcr-21.verizon-gni.net (130.81.221.220)  11.721 ms
    b3332.nycmny-lcr-22.verizon-gni.net (130.81.221.222)  11.601 ms
    b3332.nycmny-lcr-21.verizon-gni.net (130.81.221.220)  6.502 ms
 4  * * *
 5  0.ae2.br2.nyc4.alter.net (140.222.229.93)  6.620 ms
    0.ae1.br2.nyc4.alter.net (140.222.229.91)  6.472 ms
    0.ae2.br2.nyc4.alter.net (140.222.229.93)  6.426 ms
 6  * * *
 7  be3495.ccr41.jfk02.atlas.cogentco.com (66.28.4.181)  5.772 ms
    be3496.ccr42.jfk02.atlas.cogentco.com (154.54.0.141)  6.744 ms
    be3495.ccr41.jfk02.atlas.cogentco.com (66.28.4.181)  7.815 ms
 8  be3362.ccr31.jfk04.atlas.cogentco.com (154.54.3.10)  5.368 ms
    be3363.ccr31.jfk04.atlas.cogentco.com (154.54.3.126)  6.969 ms
    be3362.ccr31.jfk04.atlas.cogentco.com (154.54.3.10)  5.031 ms
 9  38.88.195.154 (38.88.195.154)  7.384 ms  6.505 ms  6.665 ms
10  dns.adguard.com (94.140.14.14)  4.870 ms  6.734 ms  5.525 ms
➜  ~ traceroute 94.140.15.15
traceroute to 94.140.15.15 (94.140.15.15), 64 hops max, 52 byte packets
 1  rt-70b0 (172.19.1.1)  0.953 ms  0.635 ms  0.683 ms
 2  * * *
 3  b3332.nycmny-lcr-21.verizon-gni.net (130.81.221.220)  4.976 ms  7.215 ms  4.233 ms
 4  * * *
 5  0.ae1.br2.nyc4.alter.net (140.222.229.91)  4.898 ms  5.758 ms  7.158 ms
 6  * * verizon-com.customer.alter.net (152.179.110.202)  4.047 ms
 7  be3496.ccr42.jfk02.atlas.cogentco.com (154.54.0.141)  5.682 ms
    be3495.ccr41.jfk02.atlas.cogentco.com (66.28.4.181)  6.606 ms
    be3496.ccr42.jfk02.atlas.cogentco.com (154.54.0.141)  7.501 ms
 8  be3362.ccr31.jfk04.atlas.cogentco.com (154.54.3.10)  7.122 ms
    be3363.ccr31.jfk04.atlas.cogentco.com (154.54.3.126)  5.728 ms  3.840 ms
 9  38.88.195.154 (38.88.195.154)  5.478 ms
    38.104.72.2 (38.104.72.2)  6.043 ms
    38.88.195.154 (38.88.195.154)  5.714 ms
10  dns.adguard.com (94.140.15.15)  5.897 ms  4.401 ms  5.672 ms
➜  ~
```
